getmoto/moto

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

I have some code that looks at instance launch times, and looks for either the oldest or newest instance. This allows me to call `run_instances` with a sleep in between and ensure everything works correctly.

Feature instance launch time

---

moto/s3/models.py
tests/test_s3/test_s3.py
tests/test_s3bucket_path/test_s3bucket_path.py

This matches actual AWS results, the behavior in the [`if prefix` branch](https://github.com/jbalogh/moto/blob/c7bf6ffc91b378a14c653d6cbf7594f379e38504/moto/s3/models.py#L329), and the [docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html) which say:
> Amazon S3 groups these keys and return a single CommonPrefixes element with prefix value photos/ that is a substring from the beginning of these keys to the first occurrence of the specified delimiter.

Folder results should include the delimiter.

---

moto/rds/urls.py
tests/test_rds/test_rds.py

At the moment moto does not work with us-east-1 because boto endpoint does not specify that region: https://github.com/boto/boto/blob/e271ff09364ea18d9d8b6f4d63d6b0ac6cbc9b75/boto/endpoints.json#L285
This pull request fixes that issue by changing the RDS regex pattern to have the region as an optional value.

Make RDS interface work with us-east-1 region

---

moto/rds/models.py
tests/helpers.py
tests/test_rds/test_rds.py

API Version 2014-10-31: http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBInstance.html
Unfortunately boto does not support accessing StorageType through `storage_type` yet: https://github.com/boto/boto/issues/2923

Add StorageType and Iops elements to DBInstance XML response

---

moto/core/exceptions.py
moto/ec2/exceptions.py
moto/s3/exceptions.py
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

The multipart code ignores the request body when completing a multipart upload and just assume the client wants all the parts it uploaded (and in that order). This PR adds support for using and validating the request body which contains the list of parts that should be included (possibly a subset of total uploaded parts).
I have also done some refactoring in the REST error code generation, inspired by the work done in the ec2 backend.
Last, I have a commit, not pushed yet, that patches the S3 backend during the multipart tests so that the minimum part size is smaller (e.g. 256 bytes instead of 5 MB). This speeds the tests up significantly. Do you think it's a good idea? If so, I'll push it here.

Support for client supplied part order in multipart uploads

---

moto/cloudformation/parsing.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

It was missing an entry at `MODEL_MAP`.

Add support to create AWS::EC2::VPCPeeringConnection through the CloudFormation interface

---

moto/ec2/responses/tags.py

Calling "get_all_tags" of an ec2 connection fails, because the template doesn't get escaped. Iterating through the results to escape them individually. Issue happens when using tags including special characters.

Escaping tags individually for building the describe_tags template

---

moto/core/models.py
tests/test_s3bucket_path/test_s3bucket_path_combo.py

Trying to get the full test suite running for me, and I've ran into some issues. One, fixed for me with this PR, is that the s3bucket_path tests all fail when run together with the s3 tests. The reason is that the URL patterns between them conflict in some cases (such as listing all buckets). If someone is using moto to test code that needs to handle both calling formats then they might have to do call reset on the backend manually. Instead I thought we could just call it when disabling the backend. I added a test case so you can see the problem.
Also, is there any reason there are no `__init__.py` files in the test suite? If I want to run a specific test I have to `touch` the needed files for `nose` to find the module.

allow running mock_s3 and mock_s3bucket_path one after the other

---

moto/s3/responses.py
tests/test_s3/test_server.py

The code that handles parsing the the PUT body assumes that the data is stored on `request.body`. However, moto_server uses Flask and data from a PUT request is on `request.data`.

Fix handling of bucket versioning for moto_server

---

moto/ec2/utils.py
tests/test_ec2/test_instances.py

I added support for the instance filters listed above, including tests.
This time I've verified that travis-ci passes.  Sorry, I've never contributed to a project using travis-ci before. I needed to rewrite the failed test.  Thanks!

Support tag-key, tag-value and instance_type filters (second try)

---

moto/cloudformation/parsing.py
moto/ec2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Can you please review, @spulec?
I noticed that CloudFormation resources do not get tags, this PR adds tags to security groups only. We need to review all models in `parsing.MODEL_MAP` to add proper tagging.

Add support to AWS::EC2::SecurityGroupIngress creation

---

moto/ec2/models.py
moto/ec2/responses/security_groups.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

this fixes a problem with cloudformation and security groups. The test in this PR was failing with this traceback:
```
ERROR: tests.test_cloudformation.test_cloudformation_stack_integration.test_security_group_ingress_separate_from_security_group_by_id_using_vpc
File "/Users/hugo/.virtualenvs/moto/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/Users/hugo/yipit-stuff/moto/moto/core/models.py", line 69, in wrapper
File "/Users/hugo/yipit-stuff/moto/moto/core/models.py", line 69, in wrapper
File …
```

Change SecurityGroupBackend.{authorize,revoke}_security_group_ingress() methods to receive group name or id, never both

---

tests/test_s3/test_s3.py

While writing a test for #324 I noticed that the tests using the new `reduced_min_part_size` decorator were not being run.
This fixes it and shows that `test_s3.test_multipart_etag` fails too:
```
FAIL: test_s3.test_multipart_etag
File "/Users/jean/ws/python/moto-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/Users/jean/ws/src/moto/moto/core/models.py", line 69, in wrapper
File "/Users/jean/ws/src/moto/tests/test_s3/test_s3.py", line 37, in wrapped
return f(*args, **kwargs)
File "/Users/jean/ws/src/moto/tests/test_s3/test_s3.py", line …
```

Fix reduced_min_part_size so that tests run

---

moto/core/models.py

The ultimate motivation for this is working around HTTPretty bugs that cause it to interfere with other network calls when moto is enabled, specifically [this](https://github.com/gabrielfalcao/HTTPretty/issues/182), [this](https://github.com/gabrielfalcao/HTTPretty/issues/65), etc. Relatedly https://github.com/spulec/moto/issues/303.
I'm using moto in some Big Fat Integration Tests™, and HTTPretty was causing other http calls in my tests to fail. Obviously the right thing to do is fix HTTPretty, but in the meantime I figured I would just `mock.patch` out my calls to functions that do S3 interaction so that they turn moto on and off before and after running respectively.
Unfortunately this doesn't work, since the backends get reset every time a `MockAWS` is `start`ed. For now I'm …

allow starting without reseting

---

moto/route53/models.py
moto/route53/responses.py
tests/test_route53/test_route53.py

Paired with @kpdonn
Route53 Hosted Zones can be created with a comment in boto. This is currently the only way to differentiate two hosted zones via boto when retrieving a list. Wanted to get support in this for moto.

Adding support for comments on hosted zones.

---

moto/s3/responses.py

The '<?xml version="1.0" encoding="UTF-8"?>' bit must be on the first line, but the templates used for versioning were generating strings that started with a newline

Bad XML from S3_BUCKET_VERSIONING and S3_BUCKET_GET_VERSIONING

---

moto/iam/models.py
tests/test_iam/test_iam.py

This better mimics the behaviour of Boto

IAM: get_role should thrown when role is unexisting

---

moto/iam/models.py

The `if role` check is not necessary anymore, per #366.

IAM: unnecessary check for role

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Just a couple small modifications to range request handling.
The current implementation of range request handling raises errors on byte-range-spec range requests with explicit last-byte-pos that are greater than or equal to the length of the underlying data. The expected behavior of such a request is that it will be interpreted as a request for all remaining bytes after and including the first-byte-pos, similar to a byte-range-spec range request where no last-byte-pos was specified.
Likewise, suffix-byte-range-spec range requests with last-byte-pos that are greater than the length of the underlying data raise errors. The expected behavior of such a request is that it will be interpreted as a request for the entire length of the data.
These behaviors are also observable using AWS S3. You …

Improves range request support.

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

If the Item‘s original data is inconsistent with what's in DynamoDB,
the request should fail (unless overwrite is set to True).
http://boto.readthedocs.org/en/latest/ref/dynamodb2.html#boto.dynamodb2.table.Table.put_item

Adds the ConditionalCheckFailedException to put_item

---

moto/emr/__init__.py
moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr.py

@spulec 
This pr makes EMR mock support multi region.
https://github.com/spulec/moto/issues/347
Note:
Since this issue https://github.com/boto/boto/pull/3186 can't be resolved, moto's EMR multi region can only support ```us-east-1``` and ```eu-west-1```. These two regions are only regions which have compatible endpoints (```elasticmapreduce.eu-west-1.amazonaws.com``` and ```elasticmapreduce.us-east-1.amazonaws.com```) with moto's ```emr/urls.py```. However, we can use other regions with moto when boto3 is used instead of boto.

Make EMR multi region

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
setup.py
tests/test_cloudwatch/test_cloudwatch.py

Adds support for filtering by:
action_prefix
alarm_name_prefix
alarm_names
And throw NotImplementedError when filtering by:
state_value

CloudWatch DescribeAlarm filters.

---

setup.py

By using PEP 426 markers with `extras_require` in `setup.py`, wheel can parse the marker and install ordereddict only on Python 2.6.
ref: https://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies
Fixes #340.

Use extras_require to build a wheel usable on Python 2.6

---

moto/elb/responses.py
tests/test_elb/test_elb.py

Turns out I was wrong in #403, the issue was not API versions, but some of the existing responses did not have the `<FooBarResponse>` wrappers and only had `<FooBarResult>` which did not work with boto3. 
This commit adds all the appropriate wrappers and tests for the endpoints that changed. I'm happy to go back and fill in another set of boto3 compatibility for the rest of the endpoints. Let me know.

Make all existing ELB endpoints compatible with boto3

---

moto/sqs/models.py
tests/test_sqs/test_server.py

If one or more messages are available, stop waiting and return them.
This avoids waiting the full `wait_seconds_timeout` when there are messages in the queue
More importantly, it avoids returning more than `count` messages.  Boto's `Queue.read` passes `count=1`, an then returns the message if `len(rs) == 1`, otherwise None.  So if `len(rs) > 1`, it returns `None` and discards the multiple messages returned.

Return messages once they are gathered

---

moto/cloudformation/parsing.py
moto/datapipeline/models.py
moto/datapipeline/responses.py
moto/datapipeline/utils.py
requirements-dev.txt
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_datapipeline/test_datapipeline.py

Can you please take a look at this PR, @spulec?
I am not happy with the implementation of `remove_capitalization_of_dict_keys`, but I don't know how to make it simpler (the package `six` is only used by that function). It is necessary because AWS accepts capitalized and non-capitalized property names for data pipelines.
The value of variable `cloudformation_unique_id` was arbitrarily chosen. Do you think that a different value should be used?

Data pipeline improvements: Add support to ListPipelines & change CloudFormation to support Data Pipelines

---

moto/route53/models.py
tests/test_route53/test_route53.py

Store and marshal the region field of records
Similar to the support of weighted records.
Signed-off-by: Kevin Donnelly <kevin.donnelly@getbraintree.com>

Add support for latency based route53 records

---

moto/s3/responses.py
moto/s3bucket_path/responses.py
tests/test_s3bucket_path/test_s3bucket_path.py

Add `ResponseObject.is_delete_keys`, so `_bucket_response_post` also recognize delete_keys response with s3bucket_path: The response path is `/bucket/?delete`, not `/?delete`.

Tweak ResponseObject to let bucket.delete_keys work with s3bucket_path.

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py

This fix returns 400 and ResourceInUseException, in case  you try to create the table but the table already exists. According to AWS DynamoDB documentation.

DynamoDB2 is overwriting the table instead of returning an error

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

This pull request fixes #432.
I noticed that some methods use a constant as XML template and other methods use an inline dict (and then call `json.dumps()` on it). This should probably be all constants, right? I followed what existed, but I think it can be improved.
Also, this works perfectly with boto2, [which has JSON as content type hardcoded for `GetTemplate`](https://github.com/boto/boto/blob/dc33c30ee24623c3cc6418bcdaa5c1254ae45b21/boto/cloudformation/connection.py#L692-L715), but it will not work with any client that relies on XML.
Can you please review, @spulec?

Change CloudFormationResponse.get_template() to return `GetTemplateResponse/GetTemplateResult/TemplateBody`

---

moto/ec2/utils.py
tests/test_ec2/test_utils.py

The function ``ec2.utils.random_key_pair`` returned fixed material and fingerprint. I've made a simple system for produce it randomly like written in the comment above.
I use ``list()ˋ` around ranges because, they are generators in Python 3 and can't be sum together.
I've also added unittest and test perf:
```
>>> %timeit random_key_pair()
1000 loops, best of 3: 1.69 ms per loop
```
(On a 1CPU VM on MacBook Pro)
Let me know if you want to create real keys with paramiko, it will be more realist but more expensive in performance. Paramiko is included in boto.

Remade ec2.utils.random_key_pair for be really random

---

moto/sqs/models.py

Resolves compatibility issues with Amazon PHP SDK for SQS.

Fixes #430: MD5 hashing should be done to the real body, not an escaped one

---

moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

This would mirror the functionality of volumes when snapshot.update() is called.

Set snapshots to be in a completed state after being created and added

---

moto/rds2/models.py
moto/rds2/responses.py

This uses the correct [kwarg to set the `master_user_password`](https://github.com/spulec/moto/blob/master/moto/rds2/models.py#L40) in the rds2 backend.

Use correct kwarg for master_user_password when creating rds2 database

---

moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

This adds support for the following KMS endpoints:
* EnableKeyRotation
* DisableKeyRotation
* GetKeyRotationStatus
Signed-off-by: Jesse Szwedko <jesse.szwedko@getbraintree.com>

Add support for KMS key rotation operations

---

moto/ec2/models.py
moto/ec2/responses/subnets.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_subnets.py

The first VPC created will be elected as default.
All subnets of the default VPC are considered default for their availability zone.

Add support for default VPCs and subnets.

---

README.md
moto/__init__.py
moto/autoscaling/responses.py
moto/ecs/__init__.py
moto/ecs/models.py
moto/ecs/responses.py
moto/ecs/urls.py
tests/test_autoscaling/test_autoscaling_boto3.py
tests/test_autoscaling/test_launch_configurations_boto3.py
tests/test_ecs/test_ecs_boto3.py

This PR is a proposal for ECS support in moto. I've implemented the following methods (and corresponding unit tests):
* `create_cluster()`
* `list_clusters()`
* `delete_cluster()`
* `register_task_definition()`
* `list_task_definitions()`
* `deregister_task_definition()`
* `create_service()`
* `list_services()`
* `update_service()`
* `delete_service()`
A couple things to be aware of:
* I only implemented ECS for boto3 because it's all I need. If that's a deal breaker, I'm happy to talk about what it would take to make this available for legacy boto.
* I stupidly pushed an earlier bug fix to jbencook/moto master, which means this PR depends on spulec/moto#492. In a perfect world, we could get both changes merged in, but I'm happy to roll back the first one if you want me to.

Basic ECS support

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Added support for using `Item.partial_save()` with DynamoDB tables that have both a range and hash key. Previously an exception was raised. Issue #498

Partial save support with range key

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

This is (I think) a bug where if you reverse your query (ScanIndexForward) and limit your results, you will get the wrong set of items do to limiting them before reversing them.
I say "I think" because I'm assuming this is not the expected behavior of DynamoDB2, but I guess I could be wrong.
The test I added would fail before:
```
FAIL: test_dynamodb_table_with_range_key.test_reverse_query
File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/Users/joshink/Development/moto/moto/core/models.py", line 71, in wrapper
File …
```

Reverse before limit

---

moto/dynamodb2/models.py

Found a small issue with one of my previous changes, if you try to delete an attribute that's already deleted.

Delete missing attribute results in KeyError.

---

moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

This adds filters for volumes and snapshots. 
The following filters are implemented for volumes.
* attachment.attach-time
* attachment.device
* attachment.instance-id
* create-time
* size
* snapshot-id
* status
* tag
* tag-key
* tag-value
The following filters are not implemented for volumes due to missing information etc.
* attachment.delete-on-termination
* availability-zone (would currently only work for us-east AZs)
* encrypted
* volume-type
The following filters are implemented for snapshots.
* description
* snapshot-id
* start-time
* tag
* tag-key
* tag-value
* volume-id
* volume-size
The following filters are not implemented for snapshots.
* owner-alias
* owner-id
* progress
* status

Add filters for describeVolumes and describeSnapshots.

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

Basic support for secondary indexes (`AllIndex`). Will need to ass support for QueryFiltering to get full support.
Currently when creating a table like this one:
```
Table.create(settings.NOTIFICATIONS_TABLE_NAME, schema=[
HashKey('user_id', data_type=NUMBER),
RangeKey('uniq', data_type=NUMBER),
], throughput={
'read': 5,
'write': 5,
}, indexes=[
AllIndex('timestamp_index', parts=[
HashKey('user_id', data_type=NUMBER),
RangeKey('timestamp'),
])
])
```
When querying this table like so:
```
notification_table.query_2(
recipient_id__eq=user_id,
timestamp__gt=timestamp_cutoff,  # this isn't supported yet, I will be working on that next
index='recipient_timestamp_index',
reverse=True
)
```
You will get an error in your test since currently the key `LocalSecondaryIndexes` isn't added to the …

Bug fix secondary indexes ignored

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

* Supporrt ADD Value for numeric types
* Create item when it doesn't exist on update (to match real DynamoDB behavior)
* When hash/range key overlap, range key may end up null

Add value and UPDATE fixes

---

moto/s3/responses.py
moto/s3bucket_path/utils.py

Was getting errors when running tests against `moto_server s3` and boto3 client:
- first on the client: `ClientError: An error occurred (400) when calling the DeleteObjects operation: Bad Request`
- then on the server (after fixing first error): `AttributeError: 'Request' object has no attribute 'body'`

Fix delete keys with moto_server s3

---

moto/ec2/responses/instances.py

This is another subtle boto3 issue, it seems that it no longer expects that a dict will be passed ```{'id': '', 'name': ''}```. Instead it only requires (and passes) the security groupId. My guess was that the name was no longer needed. I believe the changes I made will be backward compatible with boto. 
There are probably a few other places this is an issue. I will try to update them as I find them.

Ensuring boto3 can correctly identify instance security groups

---

moto/ecs/models.py
moto/ecs/responses.py

Add method describe_clusters and I fix create_cluster when it doesn't have name. 
It should create a cluster with name default and not with name None. See documentation http://docs.aws.amazon.com/cli/latest/reference/ecs/create-cluster.html
Remove nexToken from methods:
* list_clusters
* list_task_definitions
* list_services
Because the library doesn't support pagination and it  doesn't send nextToken or put it to None if it doesn't exceed maxResults. See documentation http://docs.aws.amazon.com/cli/latest/reference/ecs/list-clusters.html

Add method describe_clusters and fix create_cluster,  list_clusters, list_task_definitions,  list_services for service ecs

---

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

Thanks for this module, finding it very useful!
Boto/AWS lets you specify the availability zone when starting [new instances](http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.run_instances)

Support placement when starting new instances

---

moto/cloudwatch/responses.py
moto/route53/models.py
moto/route53/responses.py
moto/route53/urls.py

* Add IsTruncated to False in template list_hosted_zones_response in route53. Because it always has it.
* add private zone in templates. Because it should have. It is always to False because it doesn't support for private zones.
* Comment's params is optional in create_hosted_zones. It is fix to support and templates adapted to it.
* add responses for methods don't have implemented in route53

Fix route53

---

MANIFEST.in

Allows downstream users and operating system packagers and porters to test released package within their own QA, build or other environments

Include tests module and test files in sdist

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

In boto3, the SQS `set_queue_attributes` items are now presented as a list of values of the form `Attribute.1.Name`, `Attribute.1.Value`, `Attribute.2.Name`, and so on.
This patch ensures these are properly handled.

boto3 SQS set attributes fix.

---

moto/awslambda/responses.py

I remove NextMarker in response for list_functions (Lambda), because It doesn't have a correctly support to call with markers and it shouldn't send if it doesn't have more functions to response. Reference to documentation: http://docs.aws.amazon.com/cli/latest/reference/lambda/list-functions.html 
Best.

remove NextMarker in response list_functions (Lambda)

---

requirements-dev.txt

botocore 1.3.29 (new as of yesterday) breaks a few of the s3 and
lambda tests; something about a StringIO being closed prematurely.
¯\\\_(ツ)\_/¯
boto3 doesn't pin the botocore version; as a result the new version of
botocore gets pulled in transitively, breaking today's builds.
Signed-off-by: Scott Greene <scott.greene@getbraintree.com>

Pin boto3 and botocore (fix the builds!)

---

moto/cloudformation/parsing.py
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/nat_gateways.py
moto/ec2/utils.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_ec2/test_nat_gateway.py

Can you please review, @spulec? The NatGateway `__init__` method is the most important part IMO because it creates the ENI. From the CreateNatGateway docs:
> This action creates a network interface in the specified subnet with a private IP address from the IP address range of the subnet
References:
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNatGateways.html
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNatGateway.html
* http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteNatGateway.html
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html

Implement NAT Gateways

---

moto/ec2/responses/route_tables.py
tests/test_ec2/test_route_tables.py

There are two 'tagSet' nodes in the DESCRIBE_ROUTE_TABLES_RESPONSE, so responses to 'DescribeRouteTables' requests are buggy.

Fix a typo in DESCRIBE_ROUTE_TABLES_RESPONSE

---

moto/route53/models.py

While there isn't an API method exposed for directly deleting a Route 53 RecordSet [it's performed via `POST` that acts more like a `PATCH` than anything else](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html), CloudFormation can have templates which contain RecordSets which refer to zones that don't exist inside the template. Ergo, we need a way to effect a delete upon these RecordSets when we don't have a direct reference to the zone.
This exposes a delete method that isn't hooked up to any response (and rightfully so), it just enables the ~polymorphic deletion behavior that we've written into the CloudFormation implementation.
Signed-off-by: Scott Greene <scott.greene@getbraintree.com>

Allow cloudformation to delete Route 53 RecordSets

---

moto/route53/models.py

Before this commit, using `HostedZoneId` would result in you not being able to find the hosted zone.

Support HostedZoneId in RecordSet templates

---

moto/iam/responses.py
tests/test_iam/test_iam.py

Hi Steve, instance profiles can have a role associated with them. This PR adds the role to the list instance profile response

Add roles to the list instance profiles response

---

moto/cloudformation/models.py
moto/cloudformation/parsing.py
moto/ec2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

According to
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
"All stack-level tags, including automatically created tags, are
propagated to resources that AWS CloudFormation supports. Currently,
tags are not propagated to Amazon EBS volumes that are created from
block device mappings."
I didn't take care of the EBS volume case from block device mappings, but generally fixed that stack level tags are propagated to any taggable ec2 resource.

Propagate stack-level tags to resources

---

setup.py

Moto imports a class in boto that did not exist before boto 2.33.0
Partial traceback showing ImportError with versions of boto < 2.33.0:
File "/src/python/moto/moto/__init__.py", line 8, in <module>
from .autoscaling import mock_autoscaling  # flake8: noqa
File "/src/python/moto/moto/autoscaling/__init__.py", line 2, in <module>
from .models import autoscaling_backends
File "/src/python/moto/moto/autoscaling/models.py", line 5, in <module>
from moto.elb import elb_backends
File "/src/python/moto/moto/elb/__init__.py", line 2, in <module>
from .models import elb_backends
File "/src/python/moto/moto/elb/models.py", line 4, in <module>
from boto.ec2.elb.attributes import (
ImportError: cannot import name ConnectionSettingAttribute
And boto.awslambda didn't exist until 2.36.0

Moto requires boto >= 2.36.0

---

moto/ec2/utils.py

Please let me know if I'm missing anything. 
These filters are described in
http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.Client.describe_instances
and map to the instance methods of public_ip() and private_ip() respectively.

Add ip-address and private-ip-address to the list of filters for instance filtering

---

moto/dynamodb/comparisons.py
moto/dynamodb2/comparisons.py

Previously experiencing this error when using the "IN" comparison function:
```
File "[path]/moto/dynamodb2/models.py", line 65, in compare
return comparison_func(self.value, *range_values)
TypeError: <lambda>() takes exactly 2 arguments (3 given)
```
Modified the lambdas to take an argument list.

Fixed DynamoDB 'IN' comparison function

---

moto/cloudwatch/models.py

it appears in template's response but it didn't have it in model.
Boto3 needs a non-empty date.
Best.

Add datetime to cloudwatch's alarms

---

moto/ec2/utils.py

Code Changes:
* Adds the ability to filter by availability zones as described in: http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.ServiceResource.instances
* maps to placement function which describes the availability zone
Please let me know if anything else can be done.
Thanks!

Added availability-zone filtering to instance collections

---

moto/ec2/models.py
moto/ec2/responses/dhcp_options.py
tests/test_ec2/test_dhcp_options.py

Implement specific filters for DHCP options set objects, and use moto generic_filter's capabilities for 'regular' filters.

Filtering implementation for DHCP options sets

---

moto/elb/models.py
moto/elb/responses.py
tests/test_elb/test_elb.py

This change implements subnet and tag handling for the CreateLoadBalancer call.
* when subnets are given, the corresponding VPC is assigned to the ELB
* tags can also be set on creation
Before, subnets and tags passed on creation where silently ignored.

Improved the ELBBackend

---

moto/route53/urls.py

Fixes #529. The [API docs](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html) make no mention of a trailing slash but adding one seems to make it work.

Add trailing slash to route53 rrset url path

---

moto/ec2/utils.py
tests/test_ec2/test_instances.py

This is a fix for issue [#581](https://github.com/spulec/moto/issues/581).
* Modified moto/ec2/utils.py to add 'architecture' to the filter dict, as well as change the exception message to format correctly.
* Added a test for filtering by architecture in tests/test_ec2/test_instances.py
There are still plenty more filters that need to be added, but this was the one that our team needed. If we need more in the future, I will add them.

Added ec2 describe-instances filter: 'architecture'

---

moto/ec2/exceptions.py
moto/ec2/models.py
tests/test_ec2/test_security_groups.py

The boto documentation is pretty vague about egress rules management, but according to boto3 documentation, it looks pretty clear that the same logic should apply for both ingress and egress rules, because the API expects the same payloads. See:
http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.SecurityGroup.authorize_egress
http://boto3.readthedocs.org/en/latest/reference/services/ec2.html?#EC2.SecurityGroup.revoke_egress
and:
http://boto3.readthedocs.org/en/latest/reference/services/ec2.html?#EC2.SecurityGroup.authorize_ingress
http://boto3.readthedocs.org/en/latest/reference/services/ec2.html?#EC2.SecurityGroup.authorize_ingress
These modifications make it possible to authorize or revoke an outbound rule for another security group.
It also add the default outbound …

Fix security groups

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

This fixes an issue where copy operations fail when the source object is versioned.

Add support for src_version_id to bucket copy_key op.

---

moto/s3/responses.py
tests/test_s3/test_s3.py

This PR adds support for passing version IDs in key HEAD requests. This fixes an issue where the boto3 client head_object method would only return information about the current object version.

Add S3 versioned bucket support to key head requests.

---

moto/ses/models.py

Pull request #560 removed the public `sent_messages` list from the `SESBackend`. This should add 'em back in.

Add sent_messages back to SESBackend

---

moto/elb/exceptions.py
moto/elb/models.py
moto/elb/responses.py
tests/test_elb/test_elb.py

As the AWS API does: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLoadBalancer.html
This commit also makes sure that the ELB dns_name is always unique.

Disallow creation of ELBs with duplicate names.

---

moto/autoscaling/models.py
tests/test_autoscaling/test_autoscaling.py

Also, fix name clash in autoscaling tests.

ELBs can now be deleted before their autoscaling groups.

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Previously, receive_message would always use the queue's default
visibility timeout instead of the value passed as a query parameter when
calling the receive_message method on an SQS connection.

Respect VisibilityTimeout when calling receive_message

---

moto/sns/models.py

This makes it easier to test the correct sns messages are sent.
For example in my test cases I can now do:
```python
from moto.sns.models import sns_backends
messages = sns_backends['eu-west-1'].platform_endpoints.values()[0].messages
assert len(messages) == 1
assert 'Hello' in messages.values()[0]
```

Save the sns messages in the PlatformEndpoint

---

moto/core/responses.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Whitespace and newlines in the template strings are significant, and it seems boto is usually not expecting it. This leads to things like `'RequestId': '\n 27daac76-34dd-47df-bd01-1f6e873584a0\n '`.
The solution is to remove newlines/whitespace completely when not using variables (i.e. RequestId blocks), or use `{{-` and `-}}` when using variables in a new line, so that Jinja2 ignores them.
I tried a generic solution in `core/responses.py`, both using `replace()` and regexes, but none of them satisfied all tests, so perhaps the best solution is to fix all template strings instead.
Fixes #623

Strip extra whitespace and newlines from SQS response templates.

---

moto/ec2/utils.py
moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

Hi there! I really like moto and I would like to use it for a project of mine where I fiddle with ECS. For this I started extending the support for ECS. This pull request implements mocks and tests for the following ECS ```ContainerInstance``` related methods:
* [```register_container_instance()```](http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.register_container_instance)
* [```list_container_instances()```](http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.list_container_instances)
* [```describe_container_instances()```](http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.describe_container_instances)
I intend to implement the remaining ```ContainerInstance``` related methods in a following pull request: …

Introduce ContainerInstance handling in ECS

---

moto/rds/models.py
setup.py

In AWS RDS API, after deleting a RDS instance the status of the instance should be 'deleting' (http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteDBInstance.html)
Adding database.status = 'deleting' will create the right response using the DELETE_DATABASE_TEMPLATE since the main block is the xml rep of the db instance.

Updating RDS instance status after deleting it

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

Added the possibility to call dynamodb_v2 by supplying an additional ExpressionAttributeNames and ExpressionAttributeValues dictionaries.
Also fixed some wrong tests related to the update_item functionality.

Fix update item on dynamodb2

---

requirements-dev.txt

Builds started failing 7 days ago. Turns out it was because of the bump from 1.4.28 to 1.4.29. It may not be worth playing whac-a-mole - I'll file an issue in either the boto3 or botocore repo in the meantime.
Affected PRs:
* #644 
* #645 
* #653

Pin boto3 and botocore (again)

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py

Filters in boto3 are passed in a list, which means any comparisons will currently fail.  Update to model and tests to resolve this issue.

Support Filters in describe_security_groups() for boto3

---

moto/ec2/utils.py
tests/test_ec2/test_tags.py

Currently the tag filter fails when describing resources and using wildcards.
e.g. an instance with the tags ("Key1", "Value1") wouldn't get picked up with a filter of {'tag:Key1': 'Value*'}

Fix tag filter

---

moto/core/exceptions.py
moto/s3/exceptions.py
tests/test_s3/test_s3.py

To match
http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#RESTErrorResponses
which documents that it should be at the top level rather than nested
under `Errors`.

Update format of S3 client errors

---

moto/ec2/models.py
tests/test_ec2/test_elastic_block_store.py

Adds volume attachment status for filtering. 
Current possible statuses are `attached` or `detached`, the intermediate states (`attaching` and `detaching`) are not implemented yet, because I couldn't figure out a good implementation.  The `detached` status is tricky to test, since you have to keep the `VolumeAttachment` from `detach_volume`.

Add volume attachment status

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

When trying to retrieve an inexistent queue with boto3, instead of returning None (or a boto3 exception) we get an XML parsing exception. I'm adding these tests so we can reproduce the problem, although you should probably hold on merging until the problem is fixed.
I admit I only had a very quick look at the code, but I couldn't find the cause, stack trace shows mostly botocore calls. If you have a rough idea of what's happening I'm happy to look into it.

Fix retrieving inexistent queue errors when using boto3

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Hello,
I think the QueueArn attribute of SQS queues is broken. If you split the ARN by `:` the third element shall be the region coded as `us-east-1`, but it is hardcoded to be `sqs.us-east-1`. The unit test hardcodes the same mistake and is not able to detect a problem.
For this reason code like the following fails:
```python
sns = boto3.client('sns')
sns_arn = sns.create_topic(Name='test-topic')['TopicArn']
sqs = boto3.client('sqs')
sqs_url = sqs.create_queue(QueueName='test-queue')['QueueUrl']
sns.subscribe(
TopicArn=sns_arn,
Protocol='sqs',
Endpoint=sqs.get_queue_attributes(
QueueUrl=sqs_url,
AttributeNames=['QueueArn']
)['Attributes']['QueueArn']
)
```
As the unit tests of subscribe use hardcored endpoints they are also not able to detect a problem.

Fix broken SQS QueueArn attribute

---

tests/test_apigateway/test_apigateway.py
tests/test_awslambda/test_lambda.py
tests/test_ec2/test_nat_gateway.py

botocore 1.4.29 started adding this. I'd match against it, but it contains a date object and it's just not worth rewriting the assertions for a key-by-key approach.
If this is acceptable it will eliminate the need for #654

Remove HTTPHeaders from ResponseMetadata in some tests

---

moto/ec2/models.py
tests/test_ec2/test_vpcs.py

Additional filters on get_vpcs (isDefault and state)
First VPC created by moto is the default VPC. Was required by user to remove default VPCs prior to rebuilding.
state is difficult to filter in moto as state is only pending on initial create; subsequent describe results is available. However this may show up when creating a VPC when running live (loop until a vpc is available for instance). Unit tests for this are lame as not sure how to test for pending state.

additional filters to get_all_vpcs

---

moto/apigateway/models.py
moto/apigateway/responses.py
setup.py
tests/test_apigateway/test_apigateway.py

This PR adds support for the requestTemplates=... parameter for the put_integration method in apigateway mock. See http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.put_integration
This is a non-breaking change. New test cases have been added to ensure we keep backward compatibility.
@spulec Thanks for maintaining this awesome project! :)

Add support for requestTemplates parameter in apigateway integrations mock

---

moto/iam/models.py
tests/test_iam/test_iam.py

When no certificate with the name exists, the API should return a 404
(NoSuchEntity).

Causes get_server_certificate to fail correctly

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Without this, any region passed to boto3.resource is ignored and unit
tests depending on it break.

Use region from ctor to set queue_arn.

---

moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
moto/server.py
tests/test_apigateway/test_apigateway.py

This PR adds initial support for deployment stages for the apigateway service.
When a new deployment is created, a new stage is automatically created for the `stageName` that has been specified for this deployment. Using the `update_stage` operation (which is an HTTP `PATCH` method), the stage information can be modified. Currently this works only for very simple examples, and the `"/*/*/<fieldName>"` path syntax is not supported yet. Will be added as part of a future PR.
Additional tests have been added to cover the new functionality.

Initial support for apigateway stages

---

README.md
docs/getting_started.rst
moto/server.py
tests/test_core/test_server.py

Please accept this patch which changes to bind by default to 127.0.0.1 so that mistakes during testing are less likely to cause problems.  I've updated also the documentation and this passes tests on travis.  
Thanks for moto in any case.  Very nice.

Make testing a bit safer binding to 127.0.0.1

---

moto/s3/utils.py
tests/test_s3/test_s3.py

Unicode keys returned by `bucket.list()` have malformed name in Python 2.
Using separating key name unquoting logic for Python 2 fixes the problem (Call `unquote` with `str`, then decode to `unicode` again). Updated the test case for unicode key to reproduce the error (without the fix).

Fix unicode S3 key listing in Python 2

---

moto/cloudwatch/models.py
moto/core/responses.py
moto/dynamodb/models.py
moto/dynamodb2/models.py
moto/rds/models.py
moto/sns/models.py
moto/sts/models.py
tests/test_swf/responses/test_workflow_executions.py

Moto only returns the right CreationDateTime for DynamoDB tables if the current timezone is UTC. This PR fixes that behavior.

ALWAYS use utcnow(), never now()

---

moto/ec2/models.py
setup.py

If the resource-type in describe_tags was invalid it would skip adding that filter. 
This behavior differed from that of AWS behavior which would instead return 0 results.

Invalid resource types would return all resources if no other filters were included

---

moto/s3/responses.py
tests/test_s3/test_s3.py
tox.ini

When using `boto3`, GET S3 object responses do not include ETag in the response headers. The updating response headers with `key.response_dict` appears to fix the issue without breaking the existing `boto` behavior.
This resolves #703, without breaking `boto`.
The `boto3` version of relevant tests have been added.

Update S3 object GET response headers with response_dict from key

---

README.md
setup.py

Adding `moto` to the requirements file for my Django project pulls in `flask`, even though I don't need the server component. By making the `server` 'extra' then there is no hard requirement on flask.

setup.py - use extras_require for flask

---

moto/route53/models.py
tests/test_route53/test_route53.py

Hey Steve, 
I suppose I should have tried using the built library locally. Although the Unittests were passing, the underlying implementation was not producing the correct results. I've refactored the models file to correct the issue.
Tags for a resourceID were all being placed under `self.resource_tags[UUID]['Value']`. Keys are now correctly added under the UUID with the proper key name and the delete logic works. 
I also tested this build code against the project I'm working on. Looks solid to me!

Fix Route53 tagging code

---

moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

Doing some work with KMS and noticed moto only supported KeyId rather than the ARN or Aliases (describe_key only). This will allow testing to include:
Key ARN Example - arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
Alias ARN Example - arn:aws:kms:us-east-1:123456789012:alias/MyAliasName
Globally Unique Key ID Example - 12345678-1234-1234-1234-123456789012
Alias Name Example - alias/MyAliasName
One area I found which I didnt change was the _assert_valid_key_id in kms/response.py is a regex search on the beginning of the string which results in it failing for the Key ARN example above. For this I use the backend get_key_id routine which determines the KeyId from Key ARN or returns the KeyID if used.
Unit tests have been included as always.

Add ARN and Alias functionality to KMS

---

setup.py

They still exist in requirements-dev.txt. Opening for testing.
This addresses #717.

Remove sure and freezegun from setup.py

---

moto/awslambda/models.py
moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

This patch allows someone to run some rudimentary python lambda functions for unit testing. For example one can have a lambda function working within moto which can get a list of EC2 instances and return them to an existing moto'd lambda function (as per test).
Some minor tweaks were required on cloud-formation unit test as it was developed for node and well this just uses the python exec function to invoke the retrieved zip function and runs it.
Hopefully this will work for python 3, but I haven't caught up with it yet ;)
Also a few issues found. regions is retrieved from boto and for some reason only US and EU are in the latest boto release so have an append in for AUS, may require others or maybe use boto3 regions collection or something?
Also noticed 202 is returned on invoke rather …

lambderize the moto lambda

---

moto/ec2/responses/vpcs.py
setup.py
tests/test_ec2/test_vpcs.py

After associate a vpc with a dhcp_options moto wasn't updating the id of the dhcp_options in the vpc describe response.

Return the right dhcp_options id in the vpc response

---

moto/compat.py
moto/core/responses.py
moto/emr/models.py
moto/emr/responses.py
moto/emr/urls.py
moto/emr/utils.py
setup.py
tests/test_core/test_responses.py
tests/test_emr/test_emr.py
tests/test_emr/test_emr_boto3.py

This revision started with an intention to resolve #707, but I needed more end point/feature coverage for EMR and boto3 compatibility, so ended up updating quite a bit of EMR code to make whole a lot of things work (which simply wasn't working).
I have tried not to break any existing tests, but this obviously ended up becoming a bit more than a casual patch, and as such I am not exactly sure if merging this revision is desired, at least in the current form. However, I hope some mechanism like this to share code/data would become available to make it easier to mock both boto and boto3 from the same template.
Please review the code with care, if any of this is desired in the upstream.
This revision includes:
- A handler for requests for which content-type is JSON (from boto3).
- A decorator …

Better EMR coverage and boto3 request/response handling

---

moto/kms/responses.py
tests/test_kms/test_kms.py

This adds support for testing the /encrypt and /decrypt endpoints
of Amazon KMS

Implementing KMS encrypt/decrypt

---

moto/iam/models.py
moto/iam/responses.py
moto/iam/utils.py
tests/test_iam/test_iam.py

This revision adds mock objects and a few end points for IAM managed policies, which are not mocked yet (only inline policies are mocked in the existing code base).

Implement IAM managed policy

---

moto/dynamodb/responses.py
tests/test_dynamodb/test_dynamodb_table_with_range_key.py
tests/test_dynamodb/test_dynamodb_table_without_range_key.py

Fixes #731 
It wasn't causing problems with range key (perhaps `has_item` follows a different path there) but I suppose good to test it in any case?

Fix failure of scan() after has_item()

---

moto/core/responses.py
moto/emr/models.py
requirements-dev.txt
tests/test_apigateway/test_apigateway.py
tests/test_ec2/test_nat_gateway.py
tests/test_emr/test_emr.py
tests/test_emr/test_emr_boto3.py

The boto3 and botocore packages in the install requirement (for development) are pinned to older versions, due to a recently added field `RetryAttempts` in JSON response making existing tests to fail. That field doesn't appear important for mocking purposes, and can therefore safely be ignored for testing. This revision modifies tests to ignore it, so that more recent version of boto3 and botocore can be used while testing.
This revision also includes a minor update to JSON response generation routine to align its behavior more closely to the unmocked behavior.

Remove botocore version pinning

---

moto/ec2/models.py
tests/test_ec2/test_tags.py

bump tag limit from 10 to 50 to align with actual AWS limit

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Internally these get converted into simpler Expected={} parameters, so
for now only `attribute_exists` and `attribute_not_exists` are supported;
OR is also not suported since `expected` does not support it.

Attempt to parse simple ConditionExpressions in DynamoDB put_item().

---

moto/sns/models.py
tests/test_sns/test_application.py
tests/test_sns/test_application_boto3.py

SNS endpoints currently only hold exactly the `attributes` dict that is passed into the constructor. While this naively seems correct, it turns out it doesn't match the behavior of AWS typically, which automatically sets 2 attributes - `Token` and `Enabled`. My change simply auto-sets those attributes if they weren't explicitly included, and modifies the tests accordingly.

Fix SNS application endpoint to match AWS return format

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Support the creation of login profiles using boto3 and deletion of login profiles.
A KeyError was raised when attempting to create a login profile using boto3:
- Fixed typo in XML result.
- Add test to cover boto3.
delete_login_profile:
- Resets user password to None.
- If user password is already none (login profile does not exist) raise exception.

Add support for login profile deletion

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

Added support for `describe_services` and `describe_task_definition` actions in the ECS client.
http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeTaskDefinition.html
http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeServices.html

Add ECS Descriptors 

---

moto/cloudformation/parsing.py

We were using this and noticed that list parameters weren't getting properly turned into lists by moto. This short addition will check the `Type` of a resolved parameter and if it's a `CommaDelimitedList` will split it on commans (',').

Make Cloudformation/parsing#load_parameters handle lists

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

ECS `update_service` is trying to store the full task_definition object rather than the name/arn.
Crash happens when response is JSON serialized.
```python
File "/home/pior/.virtualenvs/moto/lib/python3.5/site-packages/botocore/endpoint.py", line 204, in _get_response
proxies=self.proxies, timeout=self.timeout)
File "/home/pior/.virtualenvs/moto/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/home/pior/.virtualenvs/moto/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
timeout=timeout
File "/home/pior/.virtualenvs/moto/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen …
```

Fix JSON dump error in ecs.update_service with task_definition

---

moto/s3/responses.py

I've made some additions to the 'Host' field checking to determine whether it is subdomain based or url path based.
With this change it works with plain IP-Addresses.
This partially fixes issue #532

Fix s3bucketpath handling for IP based requests

---

moto/ec2/models.py
tests/test_opsworks/test_layers.py

Fixed time formatting in ec2/models.py didn't match the format returned by the API.  Merged master, fixed conflicts, and re-created pull request.

Fixed time formatting in ec2/models.py

---

moto/rds/models.py

This is needed for [clean_json](https://github.com/spulec/moto/blob/master/moto/cloudformation/parsing.py#L98) to correctly handle 'Ref's for DBInstanceIdentifiers.
You'll notice that in the changed file an assignment happens to `self.db_instance_identifier` twice, the same value each time. I suspect that this may have been a copy paste error that forgot to rename the second occurrence to physical_resource_id.

rename duplicate rds/models db_instance_identifier to physical_resource_id

---

AUTHORS.md
CHANGELOG.md
moto/s3/responses.py
tests/test_s3/test_s3.py

Fix for https://github.com/spulec/moto/issues/748
This turns on XML escaping by default.

Turn on XML escaping by default

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

Before this PR, moto only worked with service names, but AWS also supports service ARNs.

Add service ARNs support to the `DescribeServices` ECS API

---

moto/sqs/models.py

unix_time() from moto.core.utils is used as the time source through moto,
and it is identical to time.time() in output. Hence, using unix_time()
since it makes mocking easier during testing (when time is mocked out).

sqs: Use unix_time in place of time.time()

---

moto/cloudformation/exceptions.py

It should be a string, not a tuple, and it has a different form.
I'm not sure if it used to be different, but in the most recent
boto3/botocore, the message is "Stack with id {id} does not exist"
```python
>>> cf = boto3.client('cloudformation', region_name='us-west-2')
>>> try:
...     cf.describe_stacks(StackName='adfgfhghg')
... except botocore.exceptions.ClientError as e:
...     print e.response['Error']['Message']
...
Stack with id adfgfhghg does not exist
```
I am on boto3 1.4.2 and botocore 1.4.82 as of this commit message.

Fix the CloudFormation ValidationError message

---

moto/__init__.py
moto/ec2/models.py
moto/ec2/responses/subnets.py
moto/ec2/urls.py
moto/elb/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_ec2/test_availability_zones_and_regions.py
tests/test_ec2/test_key_pairs.py
tests/test_ec2/test_network_acls.py
tests/test_ec2/test_route_tables.py
tests/test_ec2/test_security_groups.py
tests/test_ec2/test_subnets.py
tests/test_ec2/test_vpcs.py

This PR includes the following revisions on `mock_ec2`:
- Add more regions
- Add three availability zones for each region, and create default VPC (and its default subnet). This is more inline with the current EC2 behavior. (With the prior code base default VPC/subnet needed to be created manually)
- Bug fix: Add `availability-zone` as an appropriate filter name.
- Bug fix: Add more filter name variety (e.g., 'vpc-id' and 'vpcId')
- Bug fix: Use `subnet_ids` parameter if provided through query string. Currently `subnet_ids` filter results appropriately only when they are provided as filter, and it is not compatible with boto/botocore interface.
- Appropriate fixes for affected tests
The overall the assumptions on default VPC/availability zones/subnets change quite a bit, so please review …

Add more availability zones and implement default VPC

---

moto/sqs/models.py

SQS SenderId does actually have a format to use from a bit of trial and error (there's still more services to go for testing).   I've inserted the "autoscale" type of format.  Ideally in future, decorator could take arguments to set some of the variables.
Format is as follows for services I use so-far:
SQS SenderID:
AIDAIT2UOQQY3AUEKVGXU  (autoscale)
AROAIL6GAI2XEC672SWG2:awslambda_39_20161007224708400   (lambda)
AROAIL6GAI2XEC672SWG2:i-12345678901234567 (send from an ec2 instance)
Sample regex:
```
aws_re1 = "(?P<awsid>[A-Za-z0-9]{21})(:((?P<instance>i-[a-fA-F0-9]{17})|(?P<lambda>awslambda_[0-9]{2}_(?P<year>(?:19|20)\d\d)"
aws_re2 = "(?P<month>0[1-9]|1[012])(?P<day>0[1-9]|[12][0-9]|3[01])(?P<hour>[0-2][0-9])(?P<mins>[0-5][0-9])(?P<seconds>[0-5][0-9])(?P<nano>[0-9][0-9][0-9]))))?"
aws_rg …
```

Use a sane aws sender_id in SQS.

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

Changes summary:
- Adding the `PolicyType` property to the autoscaling policy, which is currently missing from the mocking code
- Implementing filtering for the `describe_policies` function in autoscaling

Adding PolicyType to scaling policy and implementing filtering in describe_policies

---

moto/cloudformation/parsing.py
moto/rds/models.py
moto/rds/responses.py
moto/rds2/exceptions.py
moto/rds2/models.py
moto/rds2/responses.py
tests/test_cloudformation/fixtures/rds_mysql_with_db_parameter_group.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_rds/test_rds.py
tests/test_rds2/test_rds2.py

We need to mock out deploying RDS instances with full disk encryption
and detailed tagging. We also need to be able do deploy these instances
with Cloudformation, and then access them with both boto and boto3.
The following changes were made to support this use case:
* Join RDS and RDS2 backends - this makes RDS resources created via
either of the two boto RDS APIs visible to both, more closely
mirroring how AWS works
* Fix RDS responses that were returning JSON but should be returning XML
* Add mocking of RDS Cloudformation calls
* Add mocking of RDS full disk encryption with KMS
* Add mocking of RDS DBParameterGroups
* Fix mocking of RDS DBSecurityGroupIngress rules
* Make mocking of RDS OptionGroupOptions more accurate
* Fix mocking of RDS cross-region DB replication
* Add tag support …

Various RDS, RDS/Cloudformation, RDS/KMS fixes and additions

---

moto/iam/models.py
tests/test_iam/test_iam.py

Borrowed the same approach missing roles takes
Signed-off-by: Andrew Harris <andrew.harris@getbraintree.com>

IAM: raise error if requiested instance profile does not exist

---

moto/ec2/exceptions.py
moto/ec2/models.py
tests/test_ec2/test_security_groups.py

I have used the default limits from:
- [https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_ec2](EC2-classic sec group limits)
- [https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-security-groups](EC-VPC sec group limits)

made the Security Group backend throw the same error as AWS if the nb of sec groups limit is hit

---

moto/route53/responses.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_route53/test_route53.py

This commit is to make sure #725 and #799 pass.  This commit should not pass tests as the tests need to be changed.  If tests change before commit then it should pass.
get_all_zones() does not return just the zone ID, it returns '/hostedzone/zoneid'

Fix Route53 response and tests

---

moto/elb/models.py
moto/elb/responses.py

Also more closely mirror AWS by not returning ELB
BackendServerDescriptions that don't have policies.
Signed-off-by: Michael Nussbaum <michael.nussbaum@getbraintree.com>

Allow ELB policies to be set via Cloudformation.

---

moto/ecs/models.py

This enhances metadata retrieval and it's more complete. We should do physical resource IDs for anything that supports CloudFormation at some point.
I found that Cluster uses name and Service uses ARNs looking at existing CFN stacks with those resources.

Add resource IDs to ECS Cluster and Service models

---

moto/s3/responses.py
tests/test_s3/test_s3.py

This change adds a separate implementation for list_objects_v2. Previously, it used the same implementation as list_objects.
The unit tests still work if you run them without the mock_s3 decorator (and change the bucket name) using boto3 version 1.4.4 and botocore version 1.5.4 against the real AWS. Which means they only check for behavior that Amazon/boto3 actually implement.
This adds/fixes the following things:
- Add missing KeyCount in result (fixes #734).
- Do not hard code MaxKeys to 1000.
- Truncate result if it has more than MaxKeys items. Set IsTruncated
and NextContinuationToken accordingly.
- Support the StartAfter parameter.
- Return Owner information only when FetchOwner=True is given.
- "Prefix" in response is now "" instead of None when omitted in request.
- "Delimiter" is …

Implement list_objects_v2 for S3 buckets

---

moto/server.py

Using the default Werkzeug reloader. I prefer a reload using SIGHUP, but that's kinda difficult with Werkzeug. This works by "touching" one of the moto module files. This can be used for resetting a Moto server without actually killing it (useful for Docker for example)

Reload the server on a file change

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py

Currently, if you call `get_all_security_groups()` with values for `group_ids` and `filters`, security groups will be returned if they match the `group_ids` OR the `filters`. This patch changes it so that they will be returned if they match the `group_ids` AND the `filters`.  A test case is also included so you can confirm the old behavior fails the unit test.

make get_all_security_groups filter AND match group ids, not OR them

---

Dockerfile

Use the server install of moto for Dockerfile.
This allows the ~~flake~~ flask prerequisite of the server to be installed.

install server version of moto for Dockerfile

---

moto/kms/responses.py
tests/test_kms/test_kms.py

This upgrades the KMS encrypt and decrypt endpoints to work
under both Python 2 and 3

KMS encryption under Python 3

---

moto/cloudformation/parsing.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

This patch is a little non-obvious so I've included a write-up.
Included is a test which has a Condition and a Resource with the same name. When run the function `create_stack` throws an exception:
File "/home/dave/Projects/moto/moto/cloudformation/parsing.py", line 252, in parse_condition
if 'Condition' in value:
TypeError: argument of type 'bool' is not iterable
This code is a little weird:
condition_values = []
for value in list(condition.values())[0]:
if 'Condition' in value:
condition_values.append(condition_map[value['Condition']])
else:
condition_values.append(clean_json(value, resources_map))
if condition_operator == "Fn::Equals":
return condition_values[0] == condition_values[1]
the error is occuring because `type(value) == bool`, where usually it would only be `dict` or `str`. I …

Cloudformation ResourceMaps incorrectly share namespaces for Conditions and Resources

---

moto/ecs/models.py
moto/ecs/responses.py
requirements-dev.txt
tests/test_ecs/test_ecs_boto3.py

Features:
* Added initial method to set container instance states to `DRAINING` or `ACTIVE`
* Updated boto3 dependency to the corresponding version introducing the new method
Fixes:
* PEP8 fixes - minor issues as well as a couple of duplicate methods - have kept the newer version where appropriate
References:
* https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-ecs-supports-container-instance-draining/
* https://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.update_container_instances_state
I've updated the run_task method to only place tasks on active instances for now but the chunk of work to fully implement container draining as well as resource checking when placing tasks/services will be made in a different merge request as it's a fairly substantial …

Feat: ECS container status updating

---

moto/route53/models.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

Currently a `KeyError: u'HostedZoneName'` is thrown when supplying a `HostedZoneId` to a RecordSetGroup in a CloudFormation template and only a `HostedZoneName` will work. Both of these options are supposed to work, as per [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup.html#cfn-route53-recordsetgroup-hostedzoneid).
This PR updates `RecordSetGroup.create_from_cloudformation_json()` to perform an identical check to the one in `RecordSet`. This behavior could be abstracted into a function if desired but all occurrences in `moto/route53/models.py` appear to be handled now.

Route53: allow hosted zone id as well when creating record sets

---

moto/iam/responses.py

This removes the `<ServerCertificateMetadata>` tag from within the <member> elements of the server certificate list.
This occurred because the documentation for this method here https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListServerCertificates.html
say the return type is this  `ServerCertificateMetadataList.member.N`
but the sample response incorrectly include a `<ServerCertificateMetadata>`. I've sent feedback to the AWS docs telling them to fix their stuff but this also needs to be fixed. I haven't checked other templates with <member> tags in them, as they may be prone to this same problem.

Correct IAM list_server_certs template that was based off incorrect docs

---

moto/ec2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

According to the [CloudFormation `Ref` docs][docs], the `Ref` return value (and physical ID of the resource) for an Elastic IP is its public IP address.
[docs]: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html

Elastic IP PhysicalResourceId should always be its public IP

---

moto/cloudformation/models.py
moto/cloudformation/parsing.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

Currently when updating a stack, if parameters are provided they are ignored. This patch reads the parameters from the Response in the same way that `create_stack` does, passes it on through to the underlying `ResourceMap.update()` method and updates the `input_parameters` attribute. I'm not sure if there might be a preferred way to do this, but this seems like a reasonably small change.
As always, I'm happy to discuss or incorporate feedback to make this PR more conforming.

make cloudformation update stack use parameters provided

---

moto/autoscaling/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Cloudformation passes MaxSize, MinSize and DesiredCapacity as strings, but
we want to store them as ints.  Also includes tests of this fix, to help
avoid regression.

Cast desired capacity for cloudformation asg to int

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

This is how the AWS API works: http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.describe_stack_events
I wasn't sure whether it would be better to make the internal representation be in reverse chronological order instead of just changing the response. I could go either way. Let me know if you want me to change it!

Return CF Stack events in reverse chronological order

---

moto/awslambda/models.py

Originally, the code was setting sys.stdout and sys.stderr back to the
original, official forms, but this breaks idioms like mocking stdout to
capture printing output for tests. So instead, we will reset sys.stdout
and sys.stderr to what they were before running the lambda function, so
that in case someone is mocking stdout or stderr, their tests won't
break.
I realize that technically someone could write code that overwrites these variables, but I think it is unlikely. Let me know if this is a dealbreaker.

Fix lambda stdout/stderr mocking

---

moto/cloudformation/models.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

So that events can be uniquely identified.
I tried to match the format documented here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-listing-event-history.html

Add event IDs to CF Stack events

---

moto/s3/models.py

An Exception is raised when writing keys to the moto server using the Java AWS SDK:
```
com.amazonaws.AmazonClientException: Unable to complete transfer: null
at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.unwrapExecutionException(AbstractTransfer.java:277)
at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.rethrowExecutionException(AbstractTransfer.java:261)
at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.waitForCompletion(AbstractTransfer.java:103)
Caused by: java.lang.NullPointerException: null
at com.amazonaws.util.BinaryUtils.fromHex(BinaryUtils.java:61)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1441)
at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:135)
at …
```

fix etag metadata field name in key response dict (etag --> ETag)

---

moto/ec2/models.py
moto/ec2/responses/instances.py

Before this fix, I tried to run a "terraform apply" (Terraform by HashiCorp) against a moto server (running at localhost:48411). It failed with some parsing errors. After this change, it no longer fails. Here's how to reproduce.
`terraform apply -var 'env=local' -var 'instance_name=chellman-deleteme' -var 'owner=chellman' -var 'ec2_endpoint=http://localhost:48411' -state=terraform.tfstate -input=false default_instance`
My template is fairly simple (slightly altered to remove sensitive info):
> variable "region" {
>     default = "us-west-2"
> }
> 
> variable "env" {
>     type = "string"
> }
> 
> variable "instance_name" {
>     type = "string"
> }
> 
> variable "ec2_endpoint" {
>     type = "string"
> }
> 
> variable "image" {
>     default = "ami-f173cc91"
> }
> 
> variable …

Fixed terraform deploy against moto fails

---

moto/route53/responses.py
moto/route53/urls.py
tests/test_route53/test_route53.py

I implemented both the lookup and the sorting for when you don't specify a `dnsname`.
Added a new test and uncommented/fixed a piece of test code that can now run because the method is now supported.

Add ListHostedZonesByName

---

moto/sqs/models.py

While using moto server with a test SQS client, I noticed significant CPU usage while the client was long polling. I narrowed this down to the `receive_messages` call of the SQS service sitting in a `while True:` statement with no work to be done, thus looping forever.
To produce this issue, I do:
```
$ python3 -m venv venv
$ . ./venv/bin/activate
(venv) $ pip install moto moto[server] boto3
Collecting moto
Downloading moto-0.4.31-py2.py3-none-any.whl (303kB)
--snip--
(venv) $ moto_server sqs &
[1] 31727
* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
(venv) $ python3
Python 3.6.0 (default, Dec 24 2016, 08:01:42)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> client …
```

Prevent 100% cpu usage while SQS long polling on an empty queue

---

moto/route53/models.py

We will continue to store just the unique ID, but since the AWS API
returns `/hostedzone/<id>`, we should accept attempts to pass that back.
For example, both just the ID as well as `/hostedzone/<id>` work for
specifying the `HostedZoneId` of a `ResourceRecordSet` in CloudFormation. So
we should support that too.
Signed-off-by: Scott Greene <scott.greene@getbraintree.com>

Be flexible with Route53 Hosted Zone IDs with /hostedzone/ prefix

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Limitations:
* does not update the tags of the resources in the stack. that can be
implemented later.
* does not support the supposed feature of clearing tags by passing an
empty value that boto3 mentions in its documentation. I could not find
anything in the request body to indicate when an empty value was passed.

Allow CloudFormation stack tags to be updated

---

moto/sqs/models.py

This PR fixes SQS message polling to abort after `wait_seconds_timeout`. In the current implementation, we loop until a new message becomes available in the queue, and never actually abort the loop based on the timeout value.
Steps to reproduce the issue:
1) create queue
2) send message to the queue
3) run `sqs receive-message` against the queue -> returns the message immediately
4) run `sqs receive-message --wait-time-seconds 1` against the queue (immediately after previous command)
- expected behavior: call returns after 1 second and returns empty result
- actual behavior: call waits roughly 30 seconds (until `visibility_timeout` expires and the message gets re-added to the queue) and returns the message

Fix SQS message polling to abort after wait_seconds_timeout

---

moto/s3/responses.py

This PR fixes domain handling for local domain names in the moto S3 API.
We have a use case where the S3 API is accessed from a cross-container Docker environment: Container *A* hosts the moto S3 API, container *B* contains the `aws` CLI. We try to contact the API on container *A* from container *B* with the following command:
```
aws --endpoint-url="http://container_A:4572" s3api create-bucket --bucket my-bucket
```
In the current implementation, moto only considers `localhost` as a special host name (https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L56) and hence falls back to subdomain based bucket addressing (instead of path based bucket addressing).
This PR fixes this issue and considers all hostnames that do *not* contain a dot (`.`) as local hostnames, and treats …

Fix domain handling for local domain names in S3 API

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

*Features:*
* Now implements a basic model of Container Instance Resources (providing defaults based on C4.Xlarges - future work to base this on the EC2 instance type to follow) - existing tests updated and new ones added for this
* Check for ability to place a task on each instance - refuse to place on a task without the `MEMORY`, `CPU` or `PORTS` reminding to place the task on the instance - new tests for this
* Reserve resources on start of a task, free up on removal - new tests added for this
*Bug Fixes:*
* Now able to use container instance ARNs for `describe_container_instances` - one new test covers this case
I'm not sure I've followed your preferred practice in all the cases, creating a few private helper methods for calculating resources given the AWS implementation as a list of …

Container Instance Resource implementation

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

- Add response and endpoint methods.
- Add test covering put, get, delete and list user policy.
Closes #878
Note: I was a bit confused about the type being returned by get_user_policy hence the assertion based on policy doc in the string.

Add list user policies endpoint to iam backend.

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

S3 keys has a special header x-amz-website-redirect-location/WebsiteRedirectLocation which results into permanent redirection when a key is accessed.
boto3 put_object/get_object key: WebsiteRedirectLocation
s3 header name: x-amz-website-redirect-location
spulec/moto#821

s3: handle WebsiteRedirectLocation

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

This matches boto, see
http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.register_task_definition

Return the revision in ecs.register_task_definition

---

AUTHORS.md
moto/__init__.py
moto/backends.py
moto/ssm/__init__.py
moto/ssm/models.py
moto/ssm/responses.py
moto/ssm/urls.py
tests/test_ssm/test_ssm_boto3.py

This commit adds initial support for the Simple System Manager client.
It currently only mocks the following api endpoints:
- delete_parameter()
- put_parameter()
- get_parameters()

Implement support for SSM parameter store

---

moto/route53/responses.py
tests/test_route53/test_route53.py

Changes in this PR:
----
- Added validation for record set creation in route53 (boto3)
- Added a few test cases for ```change_resource_record_sets``` function(boto3) which is used to create, update and delete record sets in Route53.
Steps to reproduce the issue with record set creation
---
* Create a hosted zone with ```Name=database.```
* Create a invalid record```Name=prod.redis.scooby.doo``` - moto treats it as a valid request and returns a 201.
The same request using boto3(with real credentials) would give:
```
InvalidChangeBatch: An error occurred (InvalidChangeBatch) when calling the 
ChangeResourceRecordSets operation: RRSet with DNS name prod.redis.scooby.doo. is not 
permitted in zone database.
```

Added validation for record names in route53 (boto3)

---

moto/s3/models.py
tests/test_s3/test_server.py

ETag metadata key is being returned as "Etag" instead of "ETag". This leads to issues in some AWS SDKs using MotoServer. This change fixes the issue by updating the key to the correct format.
This closes #920

Fixing metadata key on s3 operation response

---

moto/s3/responses.py
tests/test_s3/test_s3.py

When calling S3 [list_object_versions](http://boto3.readthedocs.io/en/latest/reference/services/s3.html?highlight=s3#S3.Client.list_object_versions) the following exception is raised:
```
ValueError: invalid literal for int() with base 10: ''
```

ValueError when calling boto3 list_object_versions

---

moto/packages/httpretty/core.py

I won't give the whole lecture about bundling dependencies, but I will say that when I've *really had to* bundle a modified dependency I've found it effective to point to it through a git submodule, allowing the forked lib to exist as its own repo which can have updates merged back & forth from the upstream with ease. The fix for this appears to have been in the upstream httpretty for quite some time.
Without this patch, in python 3.4, a `HEAD` request to an S3 object will return duplicate content type headers (`Content-Type` and `content-type`). Which is really weird to debug.
I haven't fully investigated why this only appears to happen in py3.

bundled httpretty: re-normalize headers after executing callable_body

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Add the creation date, including timezone info, to the data returned
when requesting all AccessKeys for an IAM user.
This fixes #75

Update list IAM AccessKeys

---

moto/core/models.py

object takes no constructor argument whatever the python version.
we simplify the code to not use constructor arguments
fix #942

fix warning on py2 as well

---

setup.py

This fixes issue #949. The fix can be verified by running the following:
```
import moto
with moto.mock_s3():
pass
```

Fixes issue #949 - Add mock as dependency

---

moto/iam/exceptions.py

Spotted this while trying to improve some error handling code.
If you look at the AWS Reference under any method (e.g. AttachGroupPolicy) you will see that the error code for an http status code of 404 is `NoSuchEntity`.
A general rule of thumb is that these error codes are camel cased and with no spaces.
[Example with AttachGroupPolicy (see under *Errors*](http://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachGroupPolicy.html)**

Fix the error code for IAMNotFoundException to NoSuchEntity used by AWS.

---

tests/test_sqs/test_sqs.py

One of these tests actually waited the entire 60 seconds of the
visibility timeout but that value appears to have been copied
from a previous test that didn't. Updating all tests with shorter
timeouts so folks who copy setup code in the future don't fall
into this trap

Shorter sleeps in SQS test

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

This implements the same MD5 hashing pattern as implemented in the Ruby
and Java AWS SDKs
Fixes #918

MD5 calculation of SQS message attributes

---

moto/ec2/models.py
tests/test_ec2/test_regions.py

Boto can be configured with extra regions, but moto will fail to import
if they are not in the hardcoded list in ec2/models.py. Instead, use the
region list from boto to build the ec2_backends dict to ensure all
regions are available.

Use region list from Boto.

---

moto/elb/responses.py
tests/test_elb/test_elb.py

The 'timeout' parameter is optional in AWS so lets make it optional in Moto

ELB connection draining timeout defaults to 300 seconds

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

There was a bug when WaitTimeSeconds was set to zero causing an infinite loop if no messages came in. Added two unit tests

Bug fix for infinite loop when WaitTimeSeconds was set to 0

---

moto/awslambda/models.py
moto/cloudformation/parsing.py
moto/cloudwatch/models.py
moto/dynamodb/models.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

This PR adds extended CloudFormation models for Lambda and DynamoDB. We encountered that these classes are missing when deploying a simple sample project via *serverless* (https://github.com/serverless/serverless)
* new class `EventSourceMapping`
* new class `LambdaVersion`
* new class `LogGroup`
* new mappings in `parsing.py`
Additionally, this PR introduces an environment variable `VALIDATE_LAMBDA_S3` to allow us to configure whether creating an instance of `LambdaFunction` should necessarily raise an exception if the code does not exist in S3. This is also required to get serverless working locally. Note that the default behavior has been left unchanged (i.e., do validate if `VALIDATE_LAMBDA_S3` is not set), so there should be no issues with backwards compatibility whatsoever.

Add extended CloudFormation models for Lambda and DynamoDB

---

moto/cloudformation/models.py
moto/cloudformation/parsing.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

@spulec This PR adds <a href="http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ListExports.html">list_exports</a> call to the CloudFormationResponse. To do that, I implemented <a href="http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Export.html">Exports</a>, an optional argument for <a href="http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html">Ouputs</a>.
Related to #962 
Please let me know if you have any feedback. Thanks!

Add exports

---

moto/cloudformation/models.py
moto/cloudformation/parsing.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
tests/test_cloudformation/test_stack_parsing.py

@spulec This PR adds a few parsing options, specifically: `Fn::Split`, `Fn::Select`, `Fn::Sub`, and `Fn::ImportValue`. 
To implement `Fn::ImportValue`, I added a field, `cross_stack_resources` to `FakeStack`.
Additionally, I refactored two things. 
(1) `Fn::Join`:
It wasn't working correctly when joining on another intrinsic functions. For example, previously 
`{"Fn::Join": ['"-", {"Fn::Split": ["_", "foo_bar"]}]}` evaluated to `"Fn::Split"`, rather than `foo-bar` due to the iteration over ` {"Fn::Split": ["_", "foo_bar"]}`.
(2) `Export`:
I parsed the name and values before creating the `Export` object. It is likely one or both of those values will use some intrinsic functions.
Please let me know if you have any feedback. Thanks!
cc @hltbra

Add cf parsing

---

moto/autoscaling/models.py
tests/test_autoscaling/test_autoscaling.py

When you launch instances through an ASG currently, they have no tags. However, in practice, the instances get copied any tags that have `PropagateOnLaunch` set to true.
This PR adds the tag handling for propagating tags as well as for assigning the "Name" tag that AWS assigns on launch.

Improve instance tag handling for ASGs

---

moto/elb/exceptions.py
moto/elb/models.py
tests/test_elb/test_elb.py

Throw the appropriate error when defining a loadbalancer with no ports

create_load_balancer requires port definitions

---

moto/ecr/models.py
moto/ecr/responses.py
tests/test_ecr/test_ecr_boto3.py

Added the ability to mock describe_images and pass an image tag or image digest to filter the results.
This is branched off of https://github.com/spulec/moto/pull/985, so it would probably be easier to merge that first before looking at this.

Ecr describe images filter with image

---

moto/ecr/models.py
tests/test_ecr/test_ecr_boto3.py

If images had been pushed to a repository, they would be included in the
response object, and the json encoder could not serialize the Image class.
Since they are not included in the boto response, I just deleted the images
field from the response object for Repositories.
I also found a duplicate test for put_images in the ecr tests, so I combined them.

Make sure the repository response_object is json serializable with images

---

moto/core/responses.py
tests/test_emr/test_emr_boto3.py

- Updates _RecursiveDictRef to implement `__getitem__`, avoiding errors when using recursive settings for an emr job flow.
Previously, when using settings like the following, `moto` would throw a `TypeError: '_RecursiveDictRef' object has no attribute '__getitem__'` exception.
```
{
"Classification": "spark-env",
"Configurations": [
{
"Classification": "export",
"Configurations": [],
"Properties": {
"JAVA_HOME": "/usr/lib/jvm/java-1.8.0"
}
}
],
"Properties": {}
}
```
From the `boto3` docs, these recursive settings should be supported: http://boto3.readthedocs.io/en/latest/reference/services/emr.html#EMR.Client.run_job_flow
I also tested this and `boto3` correctly launched an emr cluster with these settings, so `moto` should support mocking it.

Add support for recursive emr settings

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

bug fix for https://github.com/spulec/moto/issues/993
The `MD5OfMessageAttributes` parameter should only be included in the response when there is at least 1 message attribute.

SQSResponse: include MD5OfMessageAttributes parameter only when there are message attributes

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Fixes #996 
Timestamps of SQS message should not have exponential notation.

Don't use exponential notation for SQS message timestamps

---

moto/server.py

This PR adds an `--ssl` flag for the `moto_server` CLI to enable encrypted connections. This is an important requirement for users that want to test their service calls via HTTPS.
The SSL certificate is generated on the fly and does not require any additional configuration. (However, as this approach uses a self-signed certificate, most clients using the server will have to be configured with a flag to skip the certificate validation).

Add CLI flag to enable SSL for moto_server

---

moto/elb/exceptions.py
moto/elb/models.py
tests/test_elb/test_elb.py

AWS returns an error condition when a listener is defined that interferes with an existing listener on the same load balancer port.

Raise error on duplicate elbv1 listener

---

moto/sns/models.py
tests/test_sns/test_subscriptions.py
tests/test_sns/test_subscriptions_boto3.py

By the documentation from AWS (http://docs.aws.amazon.com/cli/latest/reference/sns/delete-topic.html), deleting SNS should also delete all of the subscriptions. Current implementation of moto only deletes the topic.
Although in https://forums.aws.amazon.com/thread.jspa?threadID=219168 they state:
> 
> When you delete a topic, subscriptions to the topic will not be "deleted" immediately, 
> but become orphans.  SNS will periodically clean these orphans, usually every 10 hours, but not 
> guaranteed. 
> If you create a new topic with the same topic name before these orphans are cleared up, 
> the new topic will not inherit these orphans. So, no worry about them.
> 
Currently in moto, recreating the topic with same topic-name actually inherits the orphaned subscriptions.  Therefore i purpose …

SNS delete_topic should also delete subscriptions.

---

moto/sns/models.py
tests/test_sns/test_publishing_boto3.py

By the documentation from AWS - http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html , SNS would send messages to HTTP/HTTPS endpoint in JSON format. But current implementation of `moto` sends messages in form-data format.

Send JSON message to HTTP endpoint of SNS

---

moto/redshift/responses.py
tests/test_redshift/test_redshift.py

Boto3 deviates from the AWS docs in the way subnets are described when
creating a Redshift cluster subnet group.
This entry in botocore nests the SubnetIds under SubnetIdentifier tags:
https://github.com/boto/botocore/blob/develop/botocore/data/redshift/2012-12-01/service-2.json#L5423-L5429
referenced here:
https://github.com/boto/botocore/blob/develop/botocore/data/redshift/2012-12-01/service-2.json#L2296
And the AWS docs do not nest them that way:
https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateClusterSubnetGroup.html
Fixes #1029

Allow boto3 redshift cluster subnet group creation

---

moto/sqs/urls.py
tests/test_sqs/test_server.py

This PR changes the `url_path` regex for SQS to allow the dot character (`.`) in queue names. This change fixes https://github.com/spulec/moto/issues/866
Tests have been extended to cover the change and avoid possible regressions in the future.

Fix receiving of messages from queues with a dot character in their name

---

moto/server.py
tests/test_s3/test_server.py

This PR adds support for non-ASCII characters in request URLs. This is required to support, for instance, unicode bucket or object names in S3 (when using S3 path encoding).
The change has been manually tested in Python 2.x and 3.x.
A simple test has been added to test the new functionality. Note that the `PATH_INFO` contains Japanese unicode characters.

Allow non-ascii characters in request URLs

---

moto/redshift/exceptions.py
moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

I'm working on a project involving Redshift and implemented a few more endpoints as well as a bit of miscellaneous clean up and bug fixes.  Let me know what you think. I could probably commit to more work on the Redshift endpoints, if you're happy with what you see.
Here's a summary of my changes:
- Implement create_cluster_snapshot endpoint
- Implement describe_cluster_snapshots endpoint
- Implement delete_cluster_snapshot endpoint
- Implement restore_from_cluster_snapshot endpoint
- Implement limited support for describe_tags endpoint
- Correctly serialize errors to json (for boto) or xml (for boto3)
- Simulate cluster spin up by returning initial status as 'creating' and subsequent statuses as 'available'
- Fix issue with modify_cluster endpoint where cluster values get set to None …

Redshift Updates

---

moto/ecr/exceptions.py
moto/ecr/models.py
moto/ecr/responses.py
moto/sqs/models.py
requirements-dev.txt
tests/test_ecr/test_ecr_boto3.py

This pull requests adds proper error handling to missing ECR images and ECR repositories. I didn't add error handling to validate the parameters. The error messages were copied from real boto3 calls.
I updated botocore to the current latest version to get the latest features from the ECR client.
P.S.: I had to change the `struct` calls in the SQS models file because of older versions of Python (I am running 2.7.6): https://bugs.python.org/issue19099

Add proper errors to ECR calls

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

- attach_user_policy
- detach_user_policy
- list_attached_user_policies
This PR is purely additive (i.e. low risk), but does introduce some code duplication.  I may make another pass (in a future PR) if I can find the time to implement attach/detach/list for all entities (user, group, role) using a more DRY approach.

Implement additional IAM endpoints

---

moto/rds2/exceptions.py
moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py

Basic Stop and Start RDS Instances implementation - currently doesn't create snapshot as per AWS documentation and doesn't check all instance types which are invalid for stopping/starting.

Rds stop start

---

moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Invalid parameters should be listed in response['InvalidParameters'] for get_parameters.
http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.get_parameters

SSM get_parameters should list InvalidParameters

---

.travis.yml

I suspect that the pyOpenSSL package (required by the coveralls 1.2 version) is causing the builds to fail. Testing to check if the build passes.

[DNM] Test travis

---

setup.py

use requests version more than 2.5.0, because requests.request started supporting json argument from v2.4.2

use requests version more than 2.5.0

---

moto/sns/models.py
tests/test_sns/test_publishing_boto3.py

When acquiring messages published to SQS via SNS, the message structure that can be acquired differs between when using real AWS and when mocking with moto.

escape json string when sending message from sns mock to sqs mock

---

moto/elbv2/exceptions.py
moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

API doc
http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html
```
Name
The name of the target group.
This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, and must not begin or end with a hyphen.
```

validate target group name

---

moto/sns/models.py
tests/test_sns/test_publishing.py
tests/test_sns/test_publishing_boto3.py

According to the doc, message published to SNS is wrapped as json when sending it to SQS queue.
http://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html
Fixing: https://github.com/spulec/moto/issues/1063

Envelope sns message when sending to sqs

---

moto/ec2/models.py
moto/ec2/responses/instances.py
moto/ec2/utils.py
tests/test_ec2/test_instances.py

This is a fix for https://github.com/spulec/moto/issues/1075
- Added the 'network-interface.private-dns-name' and 'private-dns-name' ec2 filters
- Fixed public/private DNS values. This should be set depending on the region ([aws documentation](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html); see _Amazon DNS Server_)
- Added the region_name attribute to Instance class so that it is available to the dns setters.
- Added/updated tests

Add private-dns-name filter and fix regional DNS

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
moto/cloudformation/utils.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
tests/test_cloudformation/test_stack_parsing.py

fix bug that create_stack fails when call it with yaml template which includes shorthand intrinsic function such as `!Join`.

handle short form function in cfn yaml template.

---

moto/ecs/models.py

Volumes property of ecs task-definition is not required paramter in cfn template
http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-volumes

set None to Volumes property of ecs task-definition when called from cfn template

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

This is to address [this](https://github.com/spulec/moto/issues/1129) issue. It returns the correct ValidationException, with the correct response message, for attributes set to empty strings when calling the put_item method on a table. I'm very new to the moto codebase, so any feedback would be welcome.

Add empty string validation exception

---

moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

This adds the invoke_async function to aws_lambda. All it really does is wrap invoke, there's nothing asynchronous about it, it simply takes the correct arguments and returns the correct response, which is pretty much nothing because you can't get anything back from an asynchronously invoked lambda.
I'm not a hundred percent sure this is a valid approach.

Add invoke_async to aws_lambda

---

implementation_coverage.py

@spulec I wanted a way to reference which operations have yet to be implemented so we could make suggestions to, say, Google Summer of Code, or so I could pick one off and implement it from time to time. Here's a script that outputs the progress toward 100% implementation of AWS.
It might look like a lot of it is missing but I'm consistently amazed at how much Moto is, for all serviceable needs, a complete AWS. Just amazed. This project is the best and I'm so grateful for your work.
```
-----------------------
acm - 0% implemented
-----------------------
[ ] add_tags_to_certificate
[ ] delete_certificate
[ ] describe_certificate
[ ] get_certificate
[ ] import_certificate
[ ] list_certificates
[ ] list_tags_for_certificate
[ ] remove_tags_from_certificate
[ ] request_certificate
[ ] …
```

Adding implementation_coverage.py script

---

moto/ec2/responses/amis.py
moto/ec2/responses/customer_gateways.py
moto/ec2/responses/dhcp_options.py
moto/ec2/responses/elastic_block_store.py
moto/ec2/responses/elastic_ip_addresses.py
moto/ec2/responses/elastic_network_interfaces.py
moto/ec2/responses/general.py
moto/ec2/responses/instances.py
moto/ec2/responses/internet_gateways.py
moto/ec2/responses/key_pairs.py
moto/ec2/responses/network_acls.py
moto/ec2/responses/route_tables.py
moto/ec2/responses/security_groups.py
moto/ec2/responses/subnets.py
moto/ec2/responses/tags.py
moto/ec2/responses/virtual_private_gateways.py
moto/ec2/responses/vpc_peering_connections.py
moto/ec2/responses/vpcs.py
moto/ec2/responses/vpn_connections.py
moto/ec2/utils.py

This PR cleans up duplication of logic between base response and ec2 util classes.
It replaces functions such as sequence_from_querystring with the inherited _get_multi_param.
It also replaces direct querystring index based access with _get_param where possible.

Refactor querystring params

---

moto/ec2/models.py
tests/test_ec2/test_elastic_ip_addresses.py

This PR fixes the following issues
1. When disassociating an EIP, the instance's public ip address does not get cleared
2. Cleans up a duplicated assignment of instance public ip during EIP association
3. Adds tests to enforce these

Fix for instance public ip not being cleared on eip disassociation

---

moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py
tests/test_ec2/test_security_groups.py
tests/test_ec2/test_subnets.py
tests/test_ec2/test_vpcs.py

This PR fixes an issue where DescribeSecurityGroups does not raise an InvalidSecurityGroup exception when invalid ids/names are supplied, returning an empty list instead. Also fixes the same for snapshots, volumes, vpcs and subnets.

Raise InvalidGroup.NotFound in DescribeSecurityGroups

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

I noticed that the dynamodb2 scan operation was not returning the consumed capacity object because it was incorrectly named. This fixes that.

fix scan return CapacityUnits

---

Dockerfile

Have switched the Dockerfile from using Debian to Alpine which is far smaller. Also switched to Python3 but seeing as we run tests against both I see no issue with that.
After switching to Alpine the image size has gone down from 298MB to 34MB. 
My test repo on DockerHub - https://hub.docker.com/r/terrycain/moto/
It would be nice for someone with write access or possibly it might need to be the owner to setup the project with DockerHub, its pretty easy, you link it with GitHub, then pushes to master will add to the "latest" image, and you can configure it to make tagged released based on tags. Perhaps setting up an organisation on DockerHub might be better, haven't done that so unsure if it'll be of any use.

Shrink Dockerfile

---

moto/ssm/responses.py

This PR fixes a bug in release 1.1.13, namely that `ssm.get_parameter()` does not honor its WithDecryption parameter.
(Note that `tox` is reporting some errors elsewhere in the codebase--not in the change I just made--which seem to be environment related. I'm sorry that I haven't been able to get a clean tox build before submitting. Will continue to investigate that separately.)

ssm get_parameter to honot WithDecryption

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Very minor fix to return the consumed capacity in the proper format.

Return consumed capacity correctly for dynamodb2.get_item, put_item, update_item

---

moto/core/responses.py

Fixed #1192
Dont have a testcase for this one.
More info in the issue, but the gist of it is, the code relies on that the header is in the V4 format which contains a region, the other format just contains accesskey:secretkey which then results in `IndexError`s. Simple check for if were using V4 headers.

Fix parsing non V4 Authorization headers

---

moto/sns/models.py
moto/sns/responses.py
moto/sns/utils.py
tests/test_sns/test_publishing_boto3.py
tests/test_sns/test_subscriptions_boto3.py

Fixes #1189 
Currently SNS.publish expects an ARN, but you can actually publish with a phone number subscribed to a topic. This patch adds in the logic to look up said subscription and get the topic arn from that. Else fail gracefully.

SNS Publish by phone number

---

moto/redshift/exceptions.py
moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

- Implement create_tags, describe_tags, and delete_tags endpoints
- Clusters, Parameter Groups, Security Groups, Snapshots, and Subnet Groups can all be tagged
- Test Suite updated
- Minor clean-up of restore_from_cluster_snapshot endpoint
- Miscellaneous typo fixes

Implement Redshift Taggable Resources

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py

Use the `tag_filter_matches` function from utils, but could perhaps use `generic_filters` somehow. This solves the issue though!

Support wildcard tag filters on SecurityGroups

---

moto/dynamodb2/comparisons.py
moto/dynamodb2/models.py
moto/dynamodb2/responses.py
moto/packages/httpretty/core.py
tests/test_dynamodb2/test_dynamodb.py

Ok I got a bit carried away. DynamoDB Scan now works. 
There is a function get_filter_expression, which takes a filter expression, name substitutions and value substitutions. Removes all whitespace, tokenizes the string, then uses the shunting-yard algorithm to convert the expression into reverse polish notation which removed execution order ambiguity. Then as it steps through the RPN form, it builds the expression in Object form, as there are classes now for AND, OR BETWEEN etc.. operations etc... Its a bit messy but should handle most correct filter expressions.
... all to get FilterExpression to work.

Added overkill FilterExpression to dynamodb scan

---

moto/iam/responses.py

Newlines in the iam.create_access_key response template was causing the secret key to be returned as `u'\n    vr7PlfZyCVt3QHT2fpiqeKyL8lJlzYLC  \n'` instead of `u'vr7PlfZyCVt3QHT2fpiqeKyL8lJlzYLC'`.  This likely has gone unnoticed because ultimately the secret is just a string, but we are concatenating it with other data to form a URI and the newlines are obviously problematic in that scenario.  So...merging this shouldn't break anything and it will help us.  Thanks!

Remove newlines from create-access-key response

---

moto/__init__.py
moto/awslambda/responses.py
moto/core/responses.py
moto/core/utils.py
moto/dynamodb2/responses.py
moto/sqs/responses.py
moto/xray/__init__.py
moto/xray/mock_client.py
requirements-dev.txt
setup.py
tests/test_ecr/test_ecr_boto3.py
tests/test_xray/test_xray_client.py

So the most common use of AWS X-Ray will be someone importing the AWS X-Ray SDK and running `patch_all()`, this will then go and infect botocore, add headers to outgoing requests, look for headers on incoming ones and after it gets the data it wants, it will send UDP packets to a "local" daemon. 
This essentially patches the X-Ray SDK so that it doesnt try and send data X-Ray daemon, and eventually it will just feed straight into our X-Ray backend so that the trace info will be there for when its queried.
Have also implemented the headers 'x-amz-crc32' and 'x-amzn-requestid' which you can then decorate requests for it to then pass on those headers. You can also decorate the `call_action` method to add crc's and requestids to all methods. I added the relevant CRCs and request IDs to the …

AWS X-Ray client mock.

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

This adds three methods to the autoscaling service: attach_load_balancers, describe_load_balancers, and detach_load_balancers; all of which manipulate "classic" Elastic load balancers and their association to an autoscaling group.

Add autoscaling load balancer methods

---

moto/autoscaling/models.py
tests/test_autoscaling/test_autoscaling.py

So, I also wanted to add the elbv2 methods to autoscaling. I started on that and came across this weird bug where the `create_auto_scaling_group` method was erroneously adding the group's instances to all available ELBs when the group was created with no load balancers specified.
In the test below, I create an ELB and an ASG. I expected the ELB to have an instance count of 0, but to my amazement I found that it had a count of the autoscaling group's desired size.
I tracked it down to models.py L511. On create, if no load balancers are specified, `group.load_balancers` is an empty list. the `elb_backend.describe_load_balancers` method returns all available elbs if you pass in nothing for it to match on. This is expected, however in this specific case it is the opposite of what we want. So, …

Fix bug with update_attached_elbs

---

moto/sns/models.py

The `Enabled` Attribute in the PlatformEndpoint of SNS current returns a boolean, however, the 'enabled' property is expecting a string as `.lower()` is called on the result.
This change simply changes the default from `True` to `'True'` so the property works as expected.

Correct the type of a default attribute in SNS PlatformEndpoint

---

setup.py

Boto and Boto3 can be a little old but Moto will throw an error if
botocoe doesn't even know about some of the services it supports.
As of this commit Polly is new enough some users are running into
exceptions.

requiring minimum botocore

---

moto/autoscaling/models.py

Hey there, I overlooked something the other day:
While attaching load balancers, we need to filter the list by determining which are already attached. This will prevent duplicates from getting added. Right now, if you use attach_load_balancer to attach an elb, then call it again, you'll end up with a duplicate.

Prevent attaching a load balancer multiple times

---

moto/acm/models.py

The certificate created time is set in UTC, but the check to see if it has expired is done using local time which causes certificates to be erroneously marked as expired.

Fix timezone mismatch in acm certificate created date and now date check

---

moto/acm/responses.py
tests/test_acm/test_acm.py

Calling describe_certificate was returning the following error:
File "/usr/local/lib/python3.6/site-packages/moto/acm/responses.py", line 188, in request_certificate
if len(subject_alt_names) > 10:
TypeError: object of type 'NoneType' has no len()

Check if subject_alt_names is not none before checking length

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

Add support for the [`set-instance-health`](http://docs.aws.amazon.com/cli/latest/reference/autoscaling/set-instance-health.html
) aws autoscaling API.
It only sets the HealthStatus that will be returned through `describe-auto-scaling-groups`, it does not actually terminate the instances.   It also ignores the `ShouldRespectGracePeriod` parameter since that applies to the AutoScaling health check termination behavior (see the [Custom Healthcheck section](http://docs.aws.amazon.com/autoscaling/latest/userguide/healthcheck.html#as-configure-healthcheck) of the docs).  Implementing the actual health checking and automatic replacing would be more involved.

Add support for HealthStatus for Auto Scaling Groups

---

setup.py

Use '>=' instead of '==' to allow future versions to be updated.
cf https://github.com/spulec/moto/issues/1290

Do not freeze requirement aws-xray-sdk to a specific version 

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py
tests/test_autoscaling/test_elbv2.py

This adds elbv2 functionality to the autoscaling service.
The `create_auto_scaling_group` now supports target group arns, and the attach, detach, and describe methods have been implemented. 
A note about the update_auto_scaling_group method:
I noticed that the [mocked method](https://github.com/spulec/moto/blob/master/moto/autoscaling/responses.py#L148)  takes a `LoadBalancerNames` argument. This does not actually conform with the boto3 spec; the way to 'update' an existing autoscaling group with a new load balancer config is to actually use the `attach_load_balancers` method. The same thing goes for the elbv2 resource.
Since this doesn't relate strictly to the elbv2 integration, I was going to open a new PR with the fix. I thought it was worth mentioning because the v1 methods work as a …

Add ELBv2 Support  to Autoscaling Service

---

moto/autoscaling/models.py
moto/autoscaling/responses.py

the boto3 autoscaling client's `update_auto_scaling_group` method does not support modifying load balancer properties. This PR removes that parameter.

update_auto_scaling_group method incorrectly supports LoadBalancerNames

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

ECS container instances have attributes of 'runningTasksCount' and 'pendingTasksCount'.
See Boto3 docs here: http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.describe_container_instances
REST API docs here: http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeContainerInstances.html#API_DescribeContainerInstances_ResponseSyntax

Fix runningTasksCount ECS container instance attribute

---

requirements-dev.txt

Fix flake8's version to 3.4.1. 
flake8 3.5.0 makes failure to current moto's code base.
```
$ make test
flake8 moto
moto/acm/responses.py:114:9: E722 do not use bare except'
moto/acm/responses.py:118:9: E722 do not use bare except'
moto/acm/responses.py:123:13: E722 do not use bare except'
moto/s3bucket_path/utils.py:8:5: E741 ambiguous variable name 'l'
moto/awslambda/models.py:258:9: E722 do not use bare except'
moto/awslambda/models.py:265:9: E722 do not use bare except'
moto/awslambda/responses.py:9:1: E722 do not use bare except'
moto/core/responses.py:286:9: E722 do not use bare except'
moto/core/responses.py:293:13: E722 do not use bare except'
make: *** [lint] Error 1
```

Fix flake8 version to 3.4.1

---

moto/logs/responses.py

When an user request get-log-events commands returns next error:
TypeError: <moto.logs.models.LogEvent instance> is not JSON serializable
Fixed bug with new list of dictionary attributes from LogEvent Object

Fix Error in get-logs request LogEvent instance is not JSON serializable

---

moto/ec2/models.py
moto/ec2/responses/instances.py

@JackDanger Here's a potential fix for #1273 
I debated whether or not to just copy the instance list (like you suggested) but thought that seemed more brittle in the long-term than just making a shallow copy of the reservation object.  This seems to work fine in my tests, and all tests pass locally.  Let me know what you think!

fix deep-copy in ec2.models.all_reservations

---

moto/route53/models.py
moto/route53/responses.py
tests/test_route53/test_route53.py

Do not treat StartRecordName and StartRecordType in the Route53 list_resource_record_sets as filters.
According to [AWS API reference](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html) and [Boto](http://boto.readthedocs.io/en/glacier/ref/route53.html#boto.route53.connection.Route53Connection.get_all_rrsets) [documentation](http://boto3.readthedocs.io/en/latest/reference/services/route53.html#Route53.Client.list_resource_record_sets) they are to begin the record listing from, not for filtering. So their current behaviour in moto is not consistent with AWS.

Do not treat StartRecordName and StartRecordType as filters

---

moto/backends.py
moto/core/responses.py
scripts/scaffold.py
scripts/template/lib/__init__.py.j2
scripts/template/lib/models.py.j2
scripts/template/lib/responses.py.j2
scripts/template/lib/urls.py.j2
scripts/template/test/test_server.py.j2
scripts/template/test/test_service.py.j2

I fixed scaffold script and `moto/core/responses.py` to support rest-json style API in scaffold.
In `moto/core/responses.py`,  I mainly changed `_get_param` method and `_dispatch`+`_get_action` method.
**In `_get_param`**
Response class has been getting parameters only from queryparameter. In the PR, it will try to get parameters in order of queryparameter, json body and path parameter.
**In `_dispatch`+`_get_action`**
previously Response class had been dispatching request to appropriate method  based on the operation name in the request. Unfortunately, rest-api request does not include operation name in itself. In this PR, when it cannot find operation name in the request, it looks up operation name in boto3 client by request method and request uri.
some refactors + fixes to adapt to …

Fix scaffold to support rest-json style API

---

moto/cloudformation/parsing.py
moto/elbv2/models.py
moto/elbv2/responses.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

This pull request adds support to some ELBv2 resources (load balancer, target group, and listener).
I tested this implementation in an internal project and it works as expected. I found that outputs weren't properly evaluated (didn't support functions such as Fn::GetAtt). I fixed it to always evaluate output values.

Add CloudFormation support to ELB V2

---

moto/autoscaling/responses.py

LaunchConfiguration and AutoScalingGroup returns appropriate ARNs based on the names passed instead of hard coded values.

ASG and LC arn fix

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
moto/core/utils.py
tests/test_cloudwatch/test_cloudwatch.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Fixes #1311 
Adde SetAlarmState, also takes into account alarm state history which can be viewed with DescribeAlarmHistory
Added `filter(...)` for alarm state when describing.

CloudWatch: Added SetAlarmState and filter

---

moto/core/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Fixing this issue constantly reminding me why I dislike Python2 :unamused: 
Closes #1199 
Fixes #1198 
Ok so after fixing various random parts of string handling. We're left with the original issue @JackDanger eventually faced.
Looks like the issue lies in a grey area, `httplib` in Python2 is dirt, and doesnt respect unicode properly, and `botocore` normally sends out using a `AWSHTTPConnection` class which is a nicer patched copy of `httplib` but for some reason (I suspect `endpoint_url` being set) its changed to using regular old `httplib` so it dies.
This [line](https://github.com/boto/botocore/blob/c632931a6cc5eab4113c976d430bcb9c059f829f/botocore/vendored/requests/packages/urllib3/connectionpool.py#L155) eventually ends up to be `AWSHTTPConnection` which then works, but not in our …

utf 8 in key deletions V2

---

moto/ec2/models.py

This resolves a bug in the packaging of this package that occurs in some situation :
When `moto` is installed manually from a source distribution, in a `PYTHONDONTWRITEBYTECODE=1` environment, it ends up in the shape of a **zipfile egg** in dist-packages, as it is not marked **zip-unsafe**.
This means that importing it will result in an error, because `moto/ec2/models.py` will try to open a file in what it thinks is inside a directory, when it is actually inside a zipfile.
The package could be marked as **zip-unsafe**, but there is an even better way to solve the problem: `pkg_resources` (which is part of setuptools) that will take care (when needed) of unzipping and caching the data file, returning a valid filename which can be consumed.

Use pkg_resources to keep the package zip-safe

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

If you used a projection expression with a query, subsequent queries without projection expressions would return the same result because the attrs were being removed from the underlying data store when generating the query result set.

dynamodb2: Fix for ProjectionExpressions changing the data in storage

---

moto/autoscaling/models.py
moto/autoscaling/responses.py

I was curious as to why the implementation details page wasn't reporting on methods that I knew existed, so I took a look. 
For each module, the implementation script is looking up the Backend object in the services `models.py` file (e.g. for the auto scaling service the backend is called AutoScalingBackend), getting a list of methods, and comparing directly to the boto3 client. It seems that for moto itself to register that the method has been mocked (i.e. when moto is used in a test), the method contained in the `responses.py` file needs to match the boto3 client. 
It seems that both the method in `responses.py` and the method it calls in `models.py` need to be named the same? Just so the mocked method works, and the implementation script picks it up.

AutoScalingBackend / Implementation Coverage quirk

---

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

Hi,
It appears that describe_instances not returns EbsOptimized field.
Here is a improvment which takes EbsOptimized into account during create_instances and correctly return the value with a describe_instances.
Default value is  False.
Regards,

fix EC2 instances ebsOptimized not handled

---

moto/elbv2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

When I originally implemented `elbv2.models.FakeLoadBalancer.get_cfn_attribute()` I didn't realize `moto` would raise an exception if anything tried to use undefined attributes. I mimicked the `elb.models.FakeLoadBalancer.get_cfn_attribute()` method (but focused on elbv2 load balancers).

Add proper CFN attribute handling to elbv2.FakeLoadBalancer

---

moto/elbv2/models.py
moto/elbv2/responses.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

My CloudFormation TargetGroup creation was not passing the default values to the model because I had assumed the FakeTargetGroup model would have the default values in its `__init__` (it didn't).
Before this commit everything that creates target groups had to handle the default values (i.e., cloudformation call & ELBV2Response call) separately from the model. The default values are the model's responsibility and this PR moves the default values to the initializer of FakeTargetGroup. This PR also fixes issues when creating `TargetGroup`s via CloudFormation without all optional parameters.

Move target group default values to model FakeTargetGroup

---

moto/s3/responses.py

Use S3 path style addressing when running in [Kubernetes](https://kubernetes.io/).
Services in Kubernetes use the domain name scheme `<service_name>.<namespace>.svc.cluster.local`, hence we can simply check for the suffix `svc.cluster.local` in the target host of the request.
Without this fix, moto defaults to hostname based addressing and assumes that the domain name refers to an existing bucket, resulting in a `404` error on `ListBuckets`.

Use S3 path style addressing when running in kubernetes

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Some softwares like https://github.com/segmentio/chamber rely on the following fields in the SSM.DescribeParameters action:
- Version
- Description
- LastModifiedDate
- LastModifiedUser
Also move `KeyId` only in DescribeParameters response as in the official AWS API.

Improve SSM PutParameter & DescribeParameters actions

---

AUTHORS.md
moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

This PR does two things:
1) It adds the built-in attributes automatically applied by ECS. More on that in the docs, [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html#attributes).
- Note: In order to do that I had to initialize the EC2ContainerServiceBackend and ContainerInstance with `region_name`.
2) Formats the `ContainerInstance` attributes to be consistent with the `describe_container_instances` [response](http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.describe_container_instances).
- Note: I didn't exactly implement it the way the docs suggest with `targetType` and `targetId` because I do not see that when I call `describe_container_instances` locally, I only see `name` and `value` (optional). Please let me …

Add default ecs attributes and format in response obj

---

moto/rds2/models.py
tests/test_rds2/test_rds2.py

This fix is just to change the status of an rds instance from "shutdown" to "stopped" to match the AWS state.

updated rds status from shutdown to stopped to match aws

---

moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

Setting `None` to property of FakeTargergroup in ElbV2 class breaks response of create_target_group sometimes.
So, set aws's default values to them
The error status is as below.
```
ERROR: test_elbv2.test_create_target_group_without_non_required_parameters
File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/app/moto/core/models.py", line 71, in wrapper
File "/app/moto/core/models.py", line 71, in wrapper
File "/app/tests/test_elbv2/test_elbv2.py", line 453, in …
```

Set default value to elbv2 FakeTargetGroup

---

moto/elbv2/models.py

@terrycain  
Small fix for [earlier PR](https://github.com/spulec/moto/pull/1349).
As `FakeTargetgroup`'s default values are defined as default value of method parameter (modified to be so in #1343), aws's default parameters are now defined in two places.
So, I set `None` as default values in method parameter and set instance member's value to aws's default value in initialization phase if passed parameters are 'None'.
When service is called directly from `elbv2` client, not from cfn, these optional parameter are passed as `None`. So we have to check if passed parameters are None and set to default values if some of them are None.

tweak elbv2 FakeTargetgroups's default value

---

moto/kms/models.py
tests/test_kms/test_kms.py

If there're several aliases in the backend, previously we will bump into an unexpected KeyError here.
I haven't created a unit test for this little change. If the devs are inclined to add one, I'd be happy to do it.

fix KeyError in delete_alias in the KmsBackend.

---

moto/rds/responses.py
moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py

Fix the RDS and RDS2 backends to recognize the NewDBInstanceIdentifier argument and update their models accordingly.
Added a unit test to be sure this time.

modify_db_instance should be able to rename DB instances

---

moto/ec2/models.py

Currently, AMI info is retrieved for AMIs from `eu-west-1` region only(https://github.com/spulec/moto/blob/master/scripts/get_amis.py#L13). With this change, allow people to create their own list of available AMIs by exporting `MOTO_AMIS_PATH` env var that points to a file with the format like [amis.json](https://github.com/spulec/moto/blob/master/moto/ec2/resources/amis.json).

Allow AMIs to be read from a custom file path

---

moto/cloudformation/parsing.py
moto/cloudformation/responses.py
moto/ec2/models.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Updating a cloudformation stack from a template body works, but not from an s3 template url.  This adds support for updating a stack from the s3 url.
In the process, I ended up finding a bug where the `dummy_update_template_json` in tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py was pointed at the wrong template, so I fixed that and needed to add support for cloudformation deleting an ec2 instances to get the tests to pass afterwards.

Add cloudformation update from s3 support

---

moto/ec2/models.py

Small change to fix co-operative inheritance model for ec2 model.
I was working on a private fork for work and spent a lot of time trying to get my new features to work before I realised that NatGatewayBackend wasn't calling super() and breaking the chain.
Hopefully this will save someone some time in the future.

Fix co-operative inheritance for ec2 model

---

moto/acm/responses.py
moto/awslambda/models.py
moto/awslambda/responses.py
moto/s3bucket_path/utils.py
requirements-dev.txt

Use latest version of flake8 (not sure exactly why this needs pinning - newer versions are catching real issues) and fix the violations it mentions.
The bare exceptions will catch things such as keyboard interrupts which is bad behaviour.

Bump flake8 version and handle new lint errors

---

moto/core/responses.py
moto/core/utils.py

In the current implementation, an invalid client request results in a 500 error, instead of a 4xx style error. Steps to reproduce:
```
$ moto_server cloudwatch
$ curl http://localhost:5000
```
... results in this error:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
... with the following stack trace:
```
...
File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Library/Python/2.7/site-packages/moto/core/utils.py", line 137, in __call__
result = …
```

Return 404 error on missing action

---

moto/ec2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

I found when creating a vpc via cloudformation tags where not being applied.  This fixes that.

Cloudformation vpc add tags

---

moto/ec2/models.py
moto/ec2/responses/availability_zones_and_regions.py
tests/test_ec2/test_availability_zones_and_regions.py

I have been testing terraform against moto, this PR helps fix the terraform construct
```
data "aws_region" {
current = true
}
```
That code uses the RegionNames parameter to limit the return to just the current region

describe_regions: handle region-names parameter

---

moto/s3/exceptions.py
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

This adds in `put_bucket_acl` from the XML Body. This also adds in `put_bucket_logging` support.
Not a full exhaustive test of the ACL combos, but it's about 90% there and good enough for the vast majority of users.
Put logging verify that the destination bucket exists in the same region with the proper ACLs attached.

Added Logging and ACL from Body support

---

.bumpversion.cfg
CHANGELOG.md
moto/__init__.py
scripts/bump_version
setup.py

@georgeionita @terrycain @spulec @jbbarth 
I updated CHAGELOG.md with the changes since the last release and since 1.1.25 was getting to be a pretty high patch number I've opened this PR as version 1.2.0. No major changes though.
I'm using `script/bump_version` because I couldn't figure out the bumpversion package and if any of you know how to get that package to write to the two files containing the version I'd love to see it. Otherwise this works.

releasing version 1.2.0

---

moto/ec2/responses/elastic_block_store.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
tests/test_ec2/test_tags.py

This allows adding tags to an ebs volume object when calling create_volume, see #1431

add tags when creating ebs volume

---

tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

@dbfr3qs  cc: @JackDanger 
thank you for the commit https://github.com/spulec/moto/pull/1432/commits/7d0733ad1026e8d251e90d82aa4a3afdafbd51b5 to fix bug
but, the commit has unneeded comments for debug.
This pull requests  remove the comment.
btw, I think that we should fix test code. 
The test expect return type is" Ordered Dict". however, the code convert return value "Ordered Dict" to "Dict".
the code have to check the result as   "Ordered Dict"

Remove unneeded comments and fix test code on cloudformationstack tests 

---

moto/ec2/models.py
moto/ec2/responses/spot_fleets.py
requirements-dev.txt
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_ec2/test_spot_fleet.py

When price is omitted, AWS will default to the on-demand price.
Documentation:
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetLaunchSpecification.html

Make SpotPrice optional when requesting a spot fleet

---

moto/awslambda/models.py

There are breaking changes in docker-py 3.0.0 as depicted [here](https://github.com/docker/docker-py/releases). We were using 2.7.0 and on Feb 1st Travis started picking up the 3.x.x version so the builds are failing. We can either limit the version of docker dependency in setup.py to <3.0.0 or support the breaking changes and upgrade docker dependency. I think the latter would be preferable since the changes are relatively small and lambda tests are green.

Change lambda backend to support docker-py dependency changes

---

moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

In order to search target_groups by LB, we need this link in place.
Resolves #1500

ELBv2.create_listener links TargetGroup to LB

---

moto/s3/responses.py

This PR is a minor fix for the S3 bucket HEAD response to return an empty body when the bucket does not exist, so that `botocore` would not complain about being unable to parse the body into XML. The real AWS API returns an empty body, so this is the correct mock response.

Fix the S3 HEAD response body

---

moto/s3/responses.py
moto/s3/utils.py
tests/test_s3/test_s3_utils.py

This PR adds a little more robust helper function for parsing a region name from an S3 bucket URL. In particular, it explicitly supports both virtual-hosted and path-style URLs, and also allows a possibility (which the real API via `botocore` appears to sometimes use) where region appears in the form `s3.<region>` as opposed to `s3-<region>` (which is mentioned by the AWS API documentation).

Support both virtual-hosted and path-style URLs for region name parsing

---

moto/apigateway/models.py

This is a PR for the issue i opened a while back
https://github.com/spulec/moto/issues/1365
When using local stack that relies on moto to generate api data the response is not the same as aws.
Moto results for create-rest-api
{
"id": "823788A-Z5A-Z1",
"name": "My First API",
"description": "This is my first API",
"createdDate": "2017-11-29T22:59:03.320Z"
}
AWS results
aws apigateway create-rest-api --name 'My First API' --description 'This is my first API'
{
"id": "yd8wlf5aw1",
"name": "My First API",
"description": "This is my first API",
"createdDate": 1511983669
}
This is causing issues in validation of the createdDate value.
It should be updated to use int(time.time()) instead of current datetime object

fixes apigateway timestamp to match aws

---

moto/core/responses.py
tests/test_ec2/test_elastic_block_store.py

When I tried to search for a long list of snapshots by ID I got the following error:
```
...
moto/ec2/models.py line 1957 in describe_snapshots
unknown_ids = set(snapshot_ids) - set(matches)
TypeError: unhashable type: 'dict'
```
This fixes that and preserves the original correct behaviour.

Snapshot search bug

---

moto/redshift/exceptions.py
moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

This adds three methods to the boto3 redshift client, dealing with cross-region snapshot copies.

Redshift: Add Cross Region Snapshot Functionality

---

moto/redshift/exceptions.py
moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

This builds off of https://github.com/spulec/moto/pull/1451. That PR should also probably be reviewed/merged first.
To copy KMS-enabled snapshots cross region, you need to create a copy grant allowing the redshift service to use a KMS key in the destination region. This PR is adding that functionality. 
As you can see in the tests, there's no validation around the given kms key when creating these snapshot grants. It didn't look too bad to wire that up, however that mixed with what I have here was rather large, so I'll add the validation later.

Redshift: Add Copy Grant Functionality

---

moto/ec2/models.py

This makes the create_from_cloudformation_json function aware of the CidrIpv6 as a valid filter for SecurityGroupIngress.

Add support for CidrIpv6 in Cloudformation Security Ingress rules.

---

moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_tags.py

The AWS docs say that: "Currently, the resource types that support tagging on creation are instance and volume." Calling `create_volume` and passing `image` as the resource type in tag specifications causes an `InvalidParameterValue` error.

Change `'image'` for `'volume'` when getting tags

---

moto/sns/models.py
tests/test_sns/test_subscriptions_boto3.py

Hi.
This is apparently is a bug. If I try to create 2 subscriptions between a topic and an endpoint, Amazon will create only a single one and on the 2nd call will return the ARN of the 1st one.
Though, I couldn't any description of it in the docs (event [stackoverflow](https://stackoverflow.com/questions/48016591/amazon-sns-multiple-subscriptions-of-the-same-endpoint) didn't help.) But the experiments show that this is the behavior they have.

SNS: do not duplicate subscriptions

---

moto/rds2/responses.py
tests/test_rds2/test_rds2.py

I couldn't call describe_db_instance with MaxRecords in rds2
boto3 expect MaxRecords argument as Integer, but rds2 use the variable as string
http://boto3.readthedocs.io/en/latest/reference/services/rds.html#RDS.Client.describe_db_instances

cast MaxRecords to int on  describe_db_instances

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Addresses https://github.com/spulec/moto/issues/1483.
This adds very basic support for `send_command` by simply returning a successful send command with the parameters the user has sent.

Add support for SSM send_command

---

AUTHORS.md
moto/cloudformation/responses.py

serverless cli use the PUT + TemplateBody + TemplateURL to upload cloudformation template
This fix try to get the TemplateBody from the request first, if not exist, fetch the one from s3 bucket
And it fix the issue reported to localstack here
[https://github.com/localstack/localstack/issues/580](https://github.com/localstack/localstack/issues/580)

Use the TemplateBody by default it exist

---

moto/autoscaling/responses.py

When setting `MaxRecords` when issuing `describe_autoscaling_groups` I'm encountering the following error:
```
self = <moto.autoscaling.responses.AutoScalingResponse object at 0x10d2d75c0>
def describe_auto_scaling_groups(self):
names = self._get_multi_param("AutoScalingGroupNames.member")
token = self._get_param("NextToken")
all_groups = self.autoscaling_backend.describe_auto_scaling_groups(names)
all_names = [group.name for group in all_groups]
if token:
start = all_names.index(token) + 1
else:
start = 0
max_records = self._get_param("MaxRecords", 50)
>       if max_records > 100:
E       TypeError: '>' not supported between instances of 'str' and 'int'
```
Here is my call:
`asg_client.describe_auto_scaling_groups(MaxRecords=100)`
This issue seems to be introduced after 0.4.31. I've …

Fix MaxRecords compare issue

---

AUTHORS.md
moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

This is to address https://github.com/spulec/moto/issues/1370. Let me know if you have any feedback, happy to add more tests if necessary!
* Implement `suspend_processes` in `autoscaling.models` and `autoscaling.responses`
* Use suggested test from https://github.com/spulec/moto/issues/1370

Add suspend processes to AutoScaling service

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

* Return correct error code when fetching a queue that does not exist
* Queue creation and set_attributes uses the same code path
- ensure bool/int values are cast correctly
* RedrivePolicy is handled properly with set_attributes
- _setup_dlq is called
- is json decoded, so that returned RedrivePolicy is not json encoded twice
* As per AWS not all attributes are returned when they are not set, for  example RedrivePolicy, fifoQueue, Policy, Kms*
* WaitTimeSeconds is not a queue attribute switch to ReceiveMessageWaitTimeSeconds

Improve SQS Compatibility with AWS

---

moto/sns/models.py
moto/sns/responses.py
moto/sqs/responses.py
tests/test_sns/test_publishing_boto3.py
tests/test_sns/test_subscriptions_boto3.py

This adds support for exact string value matching along with AND/OR logic as described here:
https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html
It does not provide support for:
- Anything-but string matching
- Prefix string matching
- Numeric Value Matching
The above filter policies (if configured) will not match messages.

Implement basic SNS message filtering

---

moto/logs/responses.py
tests/test_logs/test_logs.py

As Cloudwatch logs mock have error with response, fixed it.
```
File "/Users/kawasakitoshiya/.pyenv/versions/3.6.0/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
File "/Users/kawasakitoshiya/.pyenv/versions/3.6.0/lib/python3.6/site-packages/botocore/client.py", line 588, in _make_api_call
operation_model, request_dict)
File "/Users/kawasakitoshiya/.pyenv/versions/3.6.0/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
return self._send_request(request_dict, operation_model)
File "/Users/kawasakitoshiya/.pyenv/versions/3.6.0/lib/python3.6/site-packages/botocore/endpoint.py", line 170, in _send_request
success_response, exception):
File …
```

Fix cloudwatch logs' response error

---

moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_amis.py

This addresses #1454, and also adds the `owner_id` to the `Snapshot` object.
The test is actually dependent on the fix in #1455 so this pull request is likely to be failing until that gets merged and I rebase master onto this branch.

Don't create volumes for AMIs

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

This patch makes SSM PutParameter behaviour consistent with the real endpoint in SSM.
It will return a response containing a 'Version'-key on successful calls and can now also return a ParameterAlreadyExists error if you attempt to Put a parameter that already exists (and overwrite is set to False).
Also reworked the tests to account for this functionality.

Make putparameter behaviour consistent with real endpoint

---

moto/emr/responses.py
tests/test_emr/test_emr.py

Some of our steps include a literal `&` and this caused the EMR list_steps call to fail due to invalid xml.
This adds a fix to the template and tests.
(Sorry, this was edited via Github web-ui so is done as two commits. I can squash if desired.)

XML escaping in EMR responses

---

setup.py

(see also https://github.com/spulec/moto/issues/1472)
In commit 4157abe8de154b7ff00c79d6427c0d774889da3f, the Jinja2 dep in `setup.py` was changed from being unpinned to requiring version 2.8 or newer. That change was made in response to issue https://github.com/spulec/moto/issues/728, which pointed out that the use of `lstrip_blocks` needed to be supported. Support for that option was added in Jinja 2.7, so it seems like the best option here (unless 2.8 is truly required by moto) would be to allow Jinja 2.7.3 and newer -- preventing dependency resolution conflicts in Python projects that pin Jinja2 2.7.3 but also need to use moto.

Allow slightly older Jinja2 dep for project compatability

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/vpcs.py
moto/ec2/utils.py
tests/test_ec2/test_vpcs.py

August 29, 2017 AWS announced the ability to expand their VPCs by adding additional CIDR ranges (up to 5 at this time), as well as added support for IPV6. Note: Boto which is effectively out of date now doesnt support extended cidrs in the API and has to be done via Boto3! Error codes from actual runs on AWS.
This is not fully tested with all VPC networking as someone added docker to lambda which makes it bit more awkward for developers running Windows 7 or non dockerable Windows 10 environments. So will see how the unittests work here. 
Tested for Python 2.7.14 and 3.6.4.

Enable Extended CIDR Associations on VPC

---

moto/s3/exceptions.py
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Implements `get_bucket_notification_configuration` and `put_bucket_notification_configuration`.
Supports SNS, SQS, and Lambda. I don't check for the existence of the Queues, Topics, or Functions -- I assume that is already there.
This does check that the event names are correct, that the notification target is in the same region as the bucket, and that the ARN is "correct".
closes #973

Implemented S3 get/put_notification_configuration

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

This adds support for the UsePreviousValue field of the CloudFormation Parameter data type when updating a CloudFormation stack as described at https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html
I hope this is helpful. I have been using moto _alot_ lately, and I'm glad to be able to contribute in some small way!

add UsePreviousValue support for parameters when updating a CloudFormation stack

---

moto/s3/responses.py
moto/s3/utils.py
tests/test_s3/test_s3_utils.py

Some circumstances need subdomains to be ignored rather that interpreted as bucketname, this patch allows such behaviour to be configured.

S3 Ignore Subdomain for Bucketname Flag

---

moto/s3/models.py
moto/s3/responses.py
setup.py
tests/test_s3/test_s3_lifecycle.py

Added Filtering support for S3 lifecycle and also added `ExpiredObjectDeleteMarker`.
Note: The `Filter` feature is pretty new, so I bumped up the `boto3` and `botocore` versions to the latest. @JackDanger Please let me know if this is a problem.
closes #1533
closes #1479

Added Filtering support for S3 lifecycle

---

moto/core/responses.py

Hey, I was facing annoying problem while trying to execute it on python3
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 78357```
I was referred to the modified line in the code, I changed it from the standard 'r' which is the default to 'rb' and everything is working like it should now.

Fix Unicode problem while reading AWSServiceSpec

---

moto/logs/models.py
tests/test_logs/test_logs.py

An AttributeError would be thrown if the `interleaved` parameter was
passed.

Fix AttributeError in filter_log_events

---

AUTHORS.md
moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

The default ClusterName was already taken care of for ECS clusters, but if the `Properties` key wasn't provide, it throws a KeyError.
This is a pretty rare situation, since almost every cloudformation resource has at least one required property.

If Properies isn't set, cloudformation will just use default values

---

moto/apigateway/models.py
tests/test_apigateway/test_apigateway.py

Hello :), here is my firt PR that fixes an issue with API Gateway keys identification
API Gateway keys are identified by their ids and not their values
- https://docs.aws.amazon.com/cli/latest/reference/apigateway/get-api-key.html#examples
- http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.get_api_key

Fix ApiGateway key identification

---

moto/iot/responses.py
tests/test_iot/test_iot.py

create_key_and_certificate's setAsActive was getting pulled in as a string. Updating code to pull the parameter in as boolean.

Fixing create_key_and_certificate boolean parameter

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Solves issue detailed in #1578, where some system-level attributes on a message don't survive the mock queuing.
Does **not** change or enhance FIFO queue behavior for true deduplication or groups.

Fix missing MessageGroupId and MessageDeduplicationId

---

setup.py

The `dateutil` dependency was tightened in #1519, in order to match `botocore`. However, it looks like `botocore` is working on loosening that dependency for Python 2.7 and above: https://github.com/boto/botocore/pull/1433. Therefore it makes sense that this project should _also_ loosen its dependencies, and since we don't support Python 2.6 or below, we can do so more simply.

Allow dateutil below 3.0.0

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Motivation - I noticed that it was possible to fetch more than 10 messages from an SQS queue with moto, where as AWS enforces a limit of between 1 and 10. 
Also updated WaitTimeSeconds validation while I was near by.

SQS add missing validation to ReceiveMessage

---

moto/sns/responses.py
tests/test_sns/test_publishing_boto3.py

Fixes regression in test coverage from #1574 
Fixes up bug in return value of moto.sns.responses.SNSResponse._parse_message_attributes due to accidental recycling of a variable.

Add tests for message attribute validation in SNS

---

moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses_boto3.py

The Email ``from`` header is either formatted as ``name <address>`` or ``address``.
This commit will use `parseaddr` to extract a ``(name, address)`` tuple, which we will use the ``address`` to check if it's verified.
Also support the case where ``Source`` is omitted (which AWS requires the ``from`` header to be set).
Fixes #1621

Support optional Source, parse from header

---

moto/sns/models.py
tests/test_sns/test_topics_boto3.py

This change updates the regex to simply `^[a-zA-Z0-9_-]{1,256}$` as AWS does not have prohibitions against starting/ending the topic name with underscores and/or dashes.
Fixes #1619

Allow dashes, underscores in SNS topic creates for first/last characters

---

moto/server.py

This PR makes it so the user can control the SSL certificate used by moto_server. This is particularly useful to whitelist the certificate when writing blackbox tests: for example, being able to pass in an `AWS_CA_BUNDLE` for boto, or `REQUESTS_CA_BUNDLE` for requests, which points at your self-signed certificate.
The existing behavior is unchanged: run with an auto-generated SSL certificate by doing
```
$ moto_server --ssl
```
Now you can alternately specify the certificate and private key files:
```
$ moto_server --ssl-key key.pem --ssl-cert cert.pem
```

Accept paths to user-controlled SSL cert

---

moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py

This patch teaches `LogsResponse` class how to handle the DescribeLogGroups
request, so that we can mock out the `boto.describe_log_groups()` call.
With this change in place, we can write as below:
```python
@mock_logs
def test_log_group():
conn = boto3.client('logs', 'us-west-2')
some_method_to_init_log_groups()
resp = conn.describe_log_groups(logGroupNamePrefix='myapp')
assert ...
```
This should be fairly useful for a number of programs which handles
CloudWatchLogs.
The basic support this patch adds should solve #1554.

Implement describe_log_groups() method for CloudWatchLogs

---

moto/sqs/models.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Adds a unit-test for issue #1393 and fixes it. 
Note that this is focused towards the CloudFormation use-case, and not the SQS client or resource APIs. Those other ways of creating queues may still have their own validation requirements, which may-or-may-not still need to require JSON-only inputs.

Fix Cloudformation not accepting non-JSON SQS redrive policy

---

moto/cloudwatch/models.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

While this doesn't implement statistics, it should stop `put_metric_data` from erroring on a `KeyValue` when the `Value` attribute is missing.  
Issue: https://github.com/spulec/moto/issues/1615

Issue 1615 - missing Value should not kill put_metric_data

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

To mirror behavior of actual dynamodb as demonstrated as follows:
```
>>> item = client.get_item(TableName=os.getenv('DB_TABLE'), Key={'request_id': {'S':'test_request'}})
>>> item['Item']['myexistingattr']
{'M': {'existingkey': {'S': 'thing'}}}
>>> client.update_item(Key={'request_id': {'S':'test_request'}}, TableName=(os.getenv('DB_TABLE')), UpdateExpression='SET myexistingattr.#newkey=:newvalue', ExpressionAttributeNames={'#newkey': 'newkey'}, ExpressionAttributeValues={':newvalue': {'S': 'newvalue'}})
{'ResponseMetadata': {'RequestId': '98AILFCCDKGSMCAUCLO7EC9DGRVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Tue, 08 May 2018 09:19:54 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '2', 'connection': 'keep-alive', …
```

Support assignment of nested attributes if only the topmost value exists

---

moto/events/models.py
tests/test_events/test_events.py

boto3.client('events')['Policy'] must be a string as per:
http://boto3.readthedocs.io/en/latest/reference/services/events.html#CloudWatchEvents.Client.describe_event_bus
Adding json.dumps() around the policy value ensures we do not return an unexpected dict
import boto3
from moto import mock_events
real_events = boto3.client('events')
real_bus_policy_json = real_events.describe_event_bus()['Policy']
mock = mock_events()
mock.start()
moto_events = boto3.client('events')
mock_bus_policy_json = moto_events.describe_event_bus()['Policy']
print("Real bus policy returned as %{0}".format(str(type(real_bus_policy_json))))
print("Mock bus policy returned as %{0}".format(str(type(mock_bus_policy_json))))

Bugfix: describe_event_bus()['Policy'] should be JSON string, not object

---

moto/events/models.py
tests/test_events/test_events.py

The Action parameter for events.put_permission must be fully qualified as per:
http://boto3.readthedocs.io/en/latest/reference/services/events.html#CloudWatchEvents.Client.put_permission
It expects 'PutEvents' where as it should expect 'events:PutEvents'
This corrects this behaviour

Bugfix events put permission action filter

---

moto/autoscaling/responses.py

The statement that defines LaunchConfigurationARN had a newline and whitespace prefix
The ARN reported in describe_launch_configurations has this newline and white space.
Arns should not have whitespace or newlines!
import boto3,json
from moto import mock_autoscaling
from six import string_types
mock = mock_autoscaling()
mock.start()
moto_autoscaling = boto3.client('autoscaling')
moto_lc = moto_autoscaling.create_launch_configuration(
LaunchConfigurationName="test-lc",
ImageId="ami-12345678",
SecurityGroups=["sg-12345678"]
)
arn = moto_autoscaling.describe_launch_configurations(LaunchConfigurationNames=["test-lc"])['LaunchConfigurations'][0]['LaunchConfigurationARN']
print arn
if ' ' in arn:
print "Has spaces"
if '\n' in arn:
print "Has newline"
This code returns: …

New line in LaunchConfigurationARN

---

moto/sns/models.py
tests/test_sns/test_publishing_boto3.py

Currently, `RawMessageDelivery` is assumed to be `false` for all calls to `Subscription.publish`. This PR adds a check and skips the envelope if it is given.

Add RawMessageDelivery for SNS subscriptions (fixes #1571)

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

#1655 
> The SQS backend currently does not support the message attribute MessageGroupId (Message.queue_id).
> 
> The attribute basically allows creating sub-queues within a fifo-queue which are separated by the message group. SQS makes sure to have at most one concurrent consumer receiving a message for each group, guaranteeing that all messages in the group are consumed in order. Once a message is either deleted or returned to the queue, the next one with equal group id can be consumed.
> 
In this PR the queue takes note of pending tasks and their message groups. If a new message is fetched from the queue and a pending message with the same group already exists, it is skipped.
Additionally, I have moved the infinite-loop check in `SQSBackend::receive_messages` below the message loop so …

Add MessageGroupId support to SQS queues (fixes #1655)

---

moto/core/responses.py

The load() method provided by the built-in JSON module does not accept a
byte-type value in Python 3.5 (or versions before), and will raise an exception
if one is passed.
Because of this reason, the current implementation can cause errors like below
depending on Python version in use:
```python
...
File "/url/lib/python3.5/moto/moto/emr/responses.py", line 47, in ElasticMapReduceResponse
aws_service_spec = AWSServiceSpec('data/emr/2009-03-31/service-2.json')
File "/url/lib/python3.5/moto/moto/core/responses.py", line 626, in __init__
spec = json.load(f)
File "/usr/lib/python3.5/json/__init__.py", line 268, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads …
```

AWSServiceSpec: Fix `TypeError` exceptions within json.load()

---

moto/rds2/models.py
tests/test_rds2/test_rds2.py

* Correctly return all snapshots for a given DBInstanceIdentifier.
* If an invalid DBInstanceIdentifier is passed in, return an empty array
instead of raising a ClientError (which is what AWS actually does).
Fixes #1569

Fix rds.describe_db_snapshots bugs

---

moto/cloudformation/exceptions.py
moto/cloudformation/models.py
moto/cloudformation/parsing.py
tests/test_cloudformation/test_import_value.py

This PR addresses the issues raised in #1657:
1. If a `FakeStack` has no cross-stack resources (i.e., those created by previous `create_stack` operations), it sets `self.cross_stack_resources` to an empty dict instead of an empty list.
2. If a CF template tries to import a non-existent export value, `create_stack` will raise a `ExportNotFound` exception.
This PR also adds a test when creating a stack that imports (existing) export values, and a test when creating a stack that import nonexistent export values.

Fixed CF creation to trap imports of non-existent values

---

moto/cloudformation/parsing.py
moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

They need to have less than 32 character names, so when you don't specify a name
cloudformation generates a name that is less than 32 characters.

Correctly generate resource name for target groups when using cloudformation

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

When you create a global index via the table resource `update` command, it was getting stored as a `dict_values` object, but most of the codebase expected a list.
I added a test and fixed the problem.
I also fixed an invalid import of pytest - as reported in #1674, travis isn't running the `test_dynamodb2` tests, so this import error was not caught.  I'm not sure why travis isn't running those tests, nor do I know what other tests it is missing.

Make dynamodb table indexes a list

---

moto/ecs/exceptions.py
moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

- Have `update_service` throw the correct error if the service doesn't exist
- Allow `describe_tasks` to accept the task id in addition to ARNs.

Improve ECS update_service and describing tasks.

---

moto/kinesis/models.py
moto/kinesis/responses.py
tests/test_kinesis/test_kinesis.py

Adds `ApproximateArrivalTimestamp` and `MillisBehindLatest` that were missing to Kinesis `get_records` response.
https://boto3.readthedocs.io/en/latest/reference/services/kinesis.html#Kinesis.Client.get_records

Add ApproximateArrivalTimestamp and MillisBehindLatest to Kinesis get_records response

---

.gitignore
moto/dynamodb2/comparisons.py
moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

The [AWS documentation ](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Condition.html) says that a ComparisonOperator of NULL means the attribute should not exist, whereas NOT_NULL means that the attribute should exist. It explicitly says that an attribute with a
value of NULL is considered to exist, which contradicts our previous implementation. This affects both put_item and update_item in dynamodb2.
Note that I only updated dynamodb2, not dynamodb, because I wasn't sure if that was expected to have different behaviour. Let m  know if I should copy this across to dynamodb also.

dynamodb2 ComparisonOperator should treat NULL/NOT_NULL correctly

---

moto/sns/responses.py
tests/test_sns/test_subscriptions_boto3.py

https://github.com/spulec/moto/issues/1704
I have run into an issue with mock the subscribe functionality from moto not recording the subscription attributes.  I have made an attempt to fix the issue myself, hence this pull request.

Allow attributes to be set with subscribe command

---

moto/kms/models.py
tests/test_cloudformation/fixtures/kms_key.py
tests/test_cloudformation/test_stack_parsing.py

This PR adds support for using Fn:GetAtt in CloudFormation templates referencing a KMS Key.
Example CloudFormation template
```
{
"AWSTemplateFormatVersion": "2010-09-09",
"Description": "AWS CloudFormation Sample Template to create a KMS Key.  The Fn::GetAtt is used to retrieve the ARN",
"Resources" : {
"myKey" : {
"Type" : "AWS::KMS::Key",
"Properties" : {
"Description": "Sample KmsKey",
"EnableKeyRotation": False,
"Enabled": True,
"KeyPolicy" : {
"Version": "2012-10-17",
"Id": "key-default-1",
"Statement": [
{
"Sid": "Enable IAM User Permissions",
"Effect": "Allow",
"Principal": {
"AWS": { "Fn::Join" : ["" , ["arn:aws:iam::", {"Ref" : "AWS::AccountId"} ,":root" ]] }
},
"Action": "kms:*",
"Resource": "*"
}
]
}
}
}
},
"Outputs" : {
"KeyArn" : {
"Description": "Generated Key Arn",
"Value" …
```

Add support for CloudFormation Fn::GetAtt to KMS Key

---

moto/apigateway/models.py
tests/test_apigateway/test_apigateway.py

On AWS when creating an API key if a value is not provided then AWS generates a value for you.
Example:
`aws apigateway create-api-key --name "Test"`
Returns:
```
{
"name": "Test",
"enabled": true,
"value": "dsasDDsn7qweQWE2r327lq44nLRNq0AsdAd",
"stageKeys": [],
"lastUpdatedDate": 1531220553,
"createdDate": 1531220553,
"id": "twvchui76ac"
}
```
On moto the value was only generated when the `--generate-distinct-id` flag was passed, which is a bug.
This PR fixed this.

APIGateway - Generate API key value when no value provided

---

moto/s3/models.py
tests/test_s3/test_s3.py

This pull request is to address the issue encountered in #1513 
My team encountered this issue while working with a library that built upon the Java AWS SDK. There was no eTag modification being done in the library, but we saw that on the completion step, our XML body had etags without quotes. 
Live S3 supports multipart upload completion in both cases, whether etags are quoted or not.
As @spulec requested, we added a minimum failing test case that now works with our proposed change.
@bwidmeier's comments about the Java SDK vs other SDKs reflect what we've seen. We understand the intention of moto is to mock out for boto specifically. But, with popular projects such as localstack developing against moto, it would be beneficial to work with as many SDK's as possible.

Added support for multipart upload completion with unquoted etags

---

moto/ses/models.py

These were removed in #560 but I think we should keep them around. I work with a test suite that makes liberal use of snapshots & I would like to use this style of testing with moto. It is useful to check that you sent the right thing to the right people.

feature: add parameters back to Message models

---

moto/__init__.py
moto/backends.py
moto/glue/__init__.py
moto/glue/exceptions.py
moto/glue/models.py
moto/glue/responses.py
moto/glue/urls.py
moto/glue/utils.py
tests/test_glue/__init__.py
tests/test_glue/fixtures/__init__.py
tests/test_glue/fixtures/datacatalog.py
tests/test_glue/helpers.py
tests/test_glue/test_datacatalog.py
tests/test_s3/test_s3_storageclass.py
tests/test_s3/test_s3_utils.py

I started implementing the AWS Glue mock mentioned in issue #1561. My primary use case is the Glue Data Catalog -- so far I implemented basic database and table interactions. This felt like a good point to get some feedback. I'm happy to work on this w/ others that are interested in mocking AWS Glue
cc @spulec

Scaffolding for AWS Glue Data Catalog

---

moto/secretsmanager/models.py
tests/test_secretsmanager/test_secretsmanager.py

- Save friendly name in create_secret.
- Reference the saved friendly name in responses that have "Name" field.
- Verify the received secret_id matches the current value. Don't just
test for an empty string.
- Add test for mismatched secret_id.

Issue 1770: Deal with the friendly name properly

---

setup.py

Mitigate #1793 by restricting maximum version for botocore.
botocore v1.11.0 [changed it's internal implementation](https://github.com/boto/botocore/pull/1495) so that it now uses a different library for HTTP requests. This means that moto's mocking will not work, and test code will inadvertently call the live AWS service.
As an interim solution to reduce the impact of this breakage, we restrict the "required" (ie. recommended) version of botocore so that users will be less likely to use an incompatible version, and will receive a pip warning when they do.

RFC: Change setup.py to require older version of botocore with compatible implementation

---

setup.py

Pinning boto3 to this version would remove the mismatch between
boto3 and the botocore dependency in setup.py.
Closes #1800

Fix botocore/boto3 dependency version mismatch

---

moto/cloudformation/parsing.py

This PR closes #1816 by adding the AWS::Partition resource to CloudFormation templates. According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition, the default value is `aws`.

Add AWS::Partition as a variable available to CloudFormation templates

---

moto/elb/responses.py
tests/test_elb/test_elb.py

Fixes #1748.
When an instance is not registered in an ELB, its health status should be "Unknown", not "InService".

Add support for unregistered instances in ELB DescribeInstancesHealth.

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

This commit adds a `name` and `last_modified` so it does not break when listing object versions if an object has more than one delete marker. 
Setting `last_modified` on the `FakeDeleteMarker` will allow list object versions to display the actual last_modified of the `DeleteMarker` rather than just displaying the DeleteMarker's key's `last_modified`.

Fix #1820: Add support for multiple delete markers on an s3 object

---

moto/logs/exceptions.py

- Updated ResourceAlreadyExistsException(LogsClientError) to latest Boto3 error msg when using CWL Logs

- Updated ResourceAlreadyExistsException(LogsClientError) to latest msg

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Fixes https://github.com/spulec/moto/issues/1764
Creating a queue a second time with the same attributes should not raise an error. Since the Queue casts the values and applies defaults it's best to create a new queue and compare all the attributes.

Don't error on double create queue with same attrs

---

moto/ec2/models.py
moto/ec2/responses/vpc_peering_connections.py
tests/test_ec2/test_vpc_peering.py

AWS has announced Inter-Region VPC Peering on Nov 29, 2017
Add a class level store in models/VPCBackend of ec2
for saving vpcs of all regions info. Any instance can correctly find vpc in another region
when connecting vpc of cross-region or vpc of same region.
Modify vpc_peering_connections in ec2/responses to handle
vpc peering of same region or cross region.
Update vpc_peering_connections response
template content to latest (2016-11-15) .
Add vpc cross region peering successful test case.
Add vpc cross region peering fail test case.
Related: https://github.com/spulec/moto/issues/1830
Reference
CreateVpcPeeringConnection Sample Response
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcPeeringConnection.html
Announcing Support for Inter-Region VPC Peering …

Fix #1830 Add support for cross-region VPC peering

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Fixes https://github.com/spulec/moto/issues/1762
When a queue is created with the ReceiveMessageWaitTimeSeconds
attribute the value is never converted to an integer. When the
ReceiveMessage action is called it tries to compare the string
ReceiveMessageWaitTimeSeconds with the min and max wait times which
raises a TypeError.
The solution is to convert this value to an integer before comparing.

Force receive_message_wait_time_seconds to be int

---

.travis.yml
moto/packages/httpretty/core.py
requirements-dev.txt

Fixes #1706
`.travis.yml` is so complicated as Python 3.7 is not fully supported on Travis CI. See https://github.com/travis-ci/travis-ci/issues/9815

Python 3.7 support

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Dynamodb2 update_item does not raise validation exception for attribute values set to empty strings
This pull requests fixes issue #1744
and raises ClientError, when using the update_item  method with empty string on DynamoDB2

BugFix dynamodb2 update_item with empty string Fixes#1744

---

moto/ses/models.py

Closes #1738. It is not clear in the docs but you can use this form with both `SendEmail` and `SendRawEmail`.

bugfix: support name-addr mailbox form

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

This pull request addresses two issues with respect to IAM managed policies:
* Resolves #1434, #1240 and #1238 by implementing the get_policy method, along with the appropriate test case.
* Corrects a deviation in behavior with respect to the IAM API for policy versions. [According to AWS](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html) and my own tests, when CreatePolicy is called, the PolicyDocument that is provided automatically becomes the first policy version. Therefore, list_policy_versions should always return at least one version, even before additional create_policy_versions are called. The test cases have been updated as well as the model behavior.

Implement IAM get_policy and correct policy version behavior

---

moto/logs/models.py
tests/test_logs/test_logs.py

according to aws api docs (https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html#CWL-PutLogEvents-request-sequenceToken), nextSequenceToken's type should be string, not int.

nextSequenceToken that return by cloudwatch logs putLogEvents should be string, not int.

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

- PynamoDB generate `if_not_exists`, `attribute_exists` and `attribute_not_exists`  with [extra spaces](https://github.com/pynamodb/PynamoDB/blob/3.3.1/pynamodb/expressions/operand.py#L173)
- DynamoDB (and [DynamoDB local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)) works fine but moto does not work `if_not_exists` with extra spaces.

Allow spaces to if_not_exists, attribute_exists and attribute_not_exists

---

moto/logs/models.py
tests/test_logs/test_logs.py

Based on the boto docs, eventId should be returned as a string.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.filter_log_events

Filter event log ids should be strings

---

moto/cognitoidp/models.py
tests/test_cognitoidp/test_cognitoidp.py

To resolve #1857 this commit changes the format of the id string generated for a new user pool. It prefixes the id with the region, followed by an _ then the uuid as a hex. This matches the AWS id format for user pools, validating against the pattern declared in the API documentation (https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserPoolType.html)

Fixes #1857 Ensures a UserPool Id starts like {region}_

---

moto/dynamodb2/models.py

- `cast_value` s are always `"S"` (string type) value
- Because `cast_value` does not in `expression_attribute_values`

Fix wrong type if exists

---

moto/s3/models.py
moto/s3/responses.py
tests/test_ec2/test_elastic_block_store.py
tests/test_s3/test_s3_lifecycle.py

Resolves #1845 (adds AbortIncompleteMultipartUpload), and also adds support for NoncurrentVersionTransition and NoncurrentVersionExpiration lifecycle actions in S3.

Add support for NoncurrentVersionTransition, NoncurrentVersionExpiration, and AbortIncompleteMultipartUpload actions to S3 lifecycle rules

---

moto/glue/exceptions.py
moto/glue/models.py
moto/glue/responses.py
tests/test_glue/fixtures/datacatalog.py
tests/test_glue/helpers.py
tests/test_glue/test_datacatalog.py

This expands on #1750  and adds some more APIs (much easier to have a base to work on! As pointed out in #1561)
This adds some of the missing Get/Update/Create APIs relating to the Glue data catalog -- but not yet all of them, and improves some of the error handling/edge cases when tables or DBs don't exist etc.

Mock more of the Glue Data Catalog APIs

---

docs/index.rst

The EC2 endpoint status was overflowing and creating a scroll bar on my screen. It was bugging me so I fixed it via the GitHub web interface. Will test to ensure it builds correctly when I get home from work, but it does render correctly on GitHub's preview.

Updated index.rst to fix overflow

---

moto/iam/responses.py

remove the marker since this is truncated.
The original PR I left the marker in which can break some code depending on how pagination is implemented.

remove the marker since this is truncated

---

moto/cognitoidp/models.py
tests/test_cognitoidp/test_cognitoidp.py

resolves #1831
A missing user in a cognito user pool has raises a UserNotFoundException,
not a ResourceNotFoundException. This commit corrects the behaviour so
that the correct exception is raised

Missing users now raise a UserNotFoundException

---

moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

to resolve #1881 
apigateway is able to filter the result set, returning only usage plans
with the given keyId.
This commit supports filtering the usage plans returned to the user by
filtering the list of usage plans by checking for usage plan keys

Adds keyId support to apigateway get_usage_plans

---

setup.py

Fixes spulec/moto#1947.
This was originally locked down in 31eac49e1555c5345021a252cb0c95043197ea16.

Loosen aws-xray-sdk requirements

---

README.md

On my system without quotes:
```
pip install moto[server]
zsh: no matches found: moto[server] 
```
with quotes:
```
pip install "moto[server]"
Requirement already satisfied: moto[server] [..] 
```

Without double quotes, pip would not install

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

resolves #1896 
PR adds in a decorator for wrapping current methods that return non paginated responses in cognito (might be useful elsewhere?) 
It converts the returned iterable from a backend call into a list and then slices from the pagination token, through the limit/maxitems -- default page sizes can be configured in the decorator creation, to handle many calls not requiring the maxitems / limit to be explicitly set by the caller.

Adds limiting/pagination to cognitoidp list_* functions

---

.gitignore
moto/secretsmanager/models.py
moto/secretsmanager/responses.py
moto/secretsmanager/utils.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_secretsmanager/test_server.py

@sirech thanks for the ideas and help here! See: https://github.com/spulec/moto/issues/1893 
* Refactor for multiple secrets @sirech
* Use UUID replace hardcoded value
* Use random string in ARN id value
* Fix datetime stamp
* Adding support for Tags https://github.com/spulec/moto/issues/2004
* Add tests

Refactor to store multiple scrects, use uuid, tags support

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

Fixes #1009 
Converts a container instance full arn into a container instance id, so that these can be arns work as expected.
**Test Results**
```
$ nosetests tests/test_ecs
Coverage.py warning: --include is ignored because --source is set (include-ignored)
...........................................
Name                                                   Stmts   Miss  Cover
--------------------------------------------------------------------------
moto/__init__.py                                          54      2    96%
moto/acm/__init__.py                                       5      0   100%
moto/acm/models.py                                       200     27    86%
moto/acm/utils.py                                          3      0   100%
moto/apigateway/__init__.py …
```

Support full ARN in update_container_instance_state calls

---

moto/sqs/models.py

For our local development setup we have found that moto is using around 25% CPU constantly. Digging in with gdb it turned out that it was burning that CPU in the sleeping loop. Here i'm increasing the sleep by 10x which brings the idle CPU usage down by 10x (to ~2%).
I'm not familiar enough with the moto/sqs codebase to know if lengthening this sleep will have an adverse effect; however, in other Python dev I've noticed that (in Python 2.7 anyway..) Python threading won't context switch a thread until a sleep of at least 0.01 seconds is performed (shockingly long!). So based on this guesswork I suspect sleeping for 0.01 seconds won't cause any grief.

Go easier on the CPU when moto sqs is idle

---

.travis.yml
moto/core/models.py

This should allow Moto-users to keep using existing tests without having to export dummy credentials from v1.3.7 onward. See also https://github.com/spulec/moto/issues/1924

Mock AWS credentials

---

setup.py

I'm working with an environment that is using jose 3.x for things, and it appears that forcing versions >3.0.0 was a legacy from before 3.x came out.
It appears that the usage of jose in moto works just fine with jose 3.0.1

Update to jose 3.x

---

IMPLEMENTATION_COVERAGE.md
moto/iot/models.py
moto/iot/responses.py
tests/test_iot/test_iot.py

This adds support for IoT attach_policy.
Because attach_principal_policy is deprecated
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iot.html#IoT.Client.attach_principal_policy

Add support for IoT attach_policy

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Resolve issue #1937 by correctly returning attributes as specified by the ReturnValues parameter to the DynamoDB `put_item` and `update_item` methods.

Correct behavior of ReturnValues parameter to put_item and update_item

---

moto/batch/responses.py
moto/cloudformation/models.py
moto/cloudformation/responses.py
moto/cloudformation/utils.py
setup.py
tests/test_cloudformation/test_validate.py

cfn-lint (https://github.com/awslabs/cfn-python-lint) is an official cloudformation linting tool -- it has an active community and stays up to date.
This PR effectively adds the power of `cfn-lint` to moto's `cloudformation-validate` command.

Adding cloudformation-validate. Cfn-lint does the heavy lifting.

---

moto/iam/models.py

[`iam.client.create_instance_profile()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.create_instance_profile) and [`iam.client.create_role()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.create_role) both have default paths of `/` if `Path` is omitted.
In moto, the `arn` property for both [Role](https://github.com/spulec/moto/blob/master/moto/iam/models.py#L139-L141) and [InstanceProfile](https://github.com/spulec/moto/blob/master/moto/iam/models.py#L183-L185) both depend on `self.path` being set during initialization, so if the path is omitted, moto will transform the arn to look something like this: `arn:aws:iam::123456789012:instance-profileNoneExampleInstanceProfile`.
This PR sets the …

Add default path to Role & InstanceProfile

---

.gitignore
moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Addresses issue #1955 by adding `AllowedPattern` as an argument to `put_parameter` and as a returned field to `describe_parameters`.

 Add AllowedPattern to SSM describe_parameters response

---

moto/s3/responses.py
tests/test_s3/test_s3.py
tox.ini

Should fix #1959 
* First commit forces some dummy credentials in tox tests. This is because some users (like me) are using "hidden" credentials through aws-vault and I would expect the test to not depend on the developer setup.
* Makes LocationConstraint behaves "properly" (i.e. inconsistently :) ) for us-east-1

Fix 1959 location constraint us east 1

---

moto/route53/responses.py
tests/test_route53/test_route53.py

Hi!
[AWS docs says](https://docs.aws.amazon.com/cli/latest/reference/route53/list-resource-record-sets.html) 
> AWS Route53 treats www.example.com (without a trailing dot)
> and www.example.com. (with a trailing dot) as identical.
Hence, after creating a `www.example.com` record, `www.example.com.` name is saved in Route53.
```sh
$ cat sample.json
{
"Changes": [
{
"Action": "CREATE",
"ResourceRecordSet": {
"Name": "foo.local", # without a trailing dot
"Type": "A",
"TTL": 1200,
"ResourceRecords": [
{
"Value": "192.168.10.1"
}
]
}
}
]
}
$ aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch file://sample.json
$ aws route53 list-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID
{
{
"ResourceRecords": [
{
"Value": "192.168.10.1"
}
],
"Type": "A",
"Name": …
```

Add a trailing dot to the Name of Route53 ResourceRecordSet

---

moto/s3/exceptions.py
moto/s3/models.py
tests/test_s3/test_s3.py

Check that s3 bucket names follow the documented length restriction:
'Bucket names must be at least 3 and no more than 63 characters long.'
See https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

Check bucket name length at CreateBucket

---

moto/core/responses.py

When I tried to use @mock_emr and create a cluster some of the values from the spec for InstanceFleets are double.

Added double to to_str/from_str, returned by emr create_cluster

---

moto/dynamodb2/responses.py

The "bloop" package uses parenthesis in the KeyConditionExpression, so the "query" method returns nothing due to the wrong parsing of the parameters.

Strip parenthesis in the KeyConditionExpression

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

This issue refers to/fixes #1982.
- In autoscaling, instances can be 'protected'; i.e. they are not terminated during scale-in.
- Currently, moto does not have the relevant flags and methods implemented, so instances always terminate.
- I have created optional arguments for instance protection (ASG: `new_instances_protected_from_scale_in`, instances: `protected_from_scale_in`). They are optional since deprecated boto does not support them.
- I have implemented the relevant method to set instance protection (`set_instance_protection`)
- I have made changes to describe methods to include instance protection, including their templates
- I have written tests for all new functionality (hopefully!)

Add instance protection support in autoscaling, with tests

---

setup.py

[fix #1991]
Note: I tried simply removing the pyaml dependency and saw travis tests fail, but replacing it with PyYAML allows them to continue to pass.

Replace pyaml with PyYAML dependency

---

moto/ecr/urls.py

This changed in botocore 1.12.85. See https://github.com/boto/botocore/commit/b5fa8a51393e24fbc7337a357a2d51a0f750c627
This fixes https://github.com/spulec/moto/issues/2035

ECR now uses api.ecr as its endpoint.

---

moto/ec2/models.py
tests/test_ec2/test_network_acls.py

I fixed the following smaller inaccuracies/differences from AWS:
- When creating a subnet in a non-default VPC, it was associated with a network ACL from a different VPC than the one the subnet was created in. This was caused by the first (default) VPC's default network ACL being associated with all new subnets regardless of what VPC it was created in.
- When a default network ACL gets created, a number (4) of default routes are automatically added to it. Refer to [the official documentation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html#default-network-acl).

Network ACL fixes

---

moto/ec2/models.py
moto/ec2/responses/spot_fleets.py
tests/test_ec2/test_spot_fleet.py

This addresses #1644.
I've added code that parses the tag specifications on the incoming spot fleet request, and propogates any `instance` tag specifications to the instances that are launched as a part of that spot fleet request.  I've also added a test to check that this code works (and existing tests confirm that it works without any tag specifications).

tag specifications for spot fleet requests

---

moto/iam/responses.py
tests/test_iam/test_iam.py

Fixed a bug in the XML template for `get_account_authorization_details` where attached managed policies were empty strings.

Fixed a bug in get_account_authorization_details for attached managed policies

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Adding support for a few things I needed to test a library I am using with Moto
1. Support for `NOT()` in the ConditionExpression
2: Support for `#key ExpressionAttributeNames` and `:value ExpressionAttributeValues ` placeholders in the condition expression
3. Support for `#key = :value` in the condition expression
Some examples are in the test cases.

support a bit more of the dynamoDB ConditionExpression syntax

---

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

The `run-instances` command returned a constant 0 in the `AmiLaunchIndex` field for every created instance even if multiple instances were created in the same command (specifying the `--count` option with a value other than 1). This PR fixes this, the launch indexes are returned properly.

Correctly returning ami launch index

---

moto/logs/models.py

Fix sorting of log groups - use `creationTime` as the sort key.
python3 doesn't support sorting of lists that contain dicts:
```
$ python3 -c 'sorted([{}, {}])'
File "<string>", line 1, in <module>
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
Only a minor change - would be great if we could get this merged @mikegrima @spulec . Thanks!

Fix sorting of log groups

---

moto/__init__.py

Forgot to add Config to the `__init__.py`.
This makes it properly importable for unit tests.

Add Config mock to init

---

moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

This PR modifies the response format of the ec2 calls `create_volume` and
`describe_volumes` to resolve https://github.com/spulec/moto/issues/2097. A test case is also included.
When an EBS volume has no tags, calls to the aws ec2 endpoints `create_volume`
and `describe_volumes` do not include the `Tags` key in the
`response.Volumes[]` object.
However, moto does include the `Tags` key in this case. This discrepancy
in behaviour can result in code passing a moto test but failing in
production.
Sample snippets that trigger this condition:
```
def create_volume_and_then_get_tags_from_response():
client = boto3.client('ec2', region_name='us-east-1')
volume_response = client.create_volume(
Size=10,
AvailabilityZone='us-east-1a'
)
keys = volume_response['Keys']
```
```
def …
```

Fix describe volumes response with no tags

---

moto/acm/models.py
moto/route53/models.py
tests/test_route53/test_route53.py

Previously this was not checked so an existing record (e.g. with type A) would be overwritten on upsert by a record with the same name but different type (e.g. TXT).
This commit also:
* publicizes the type variable appending the underscore affix (required to maintain compatibility with CloudFormation which sets type as the CF type),
* fixes a wrong assumption in tests that UPSERT applies a change to Type (it creates a distinct record instead),
* updates ACM model to use serial_number instead of deprecated and removed serial causing Travis failures.

Check record type when upserting.

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Currently, if versioning is disabled or suspended on a bucket, moto will push a new version of the object instead of replacing the old one. This is very different from what happens in real life and from what is documented on AWS docs. Instead, when the versioning is deactivated or suspended on a bucket, they will use what they call the null version id, which is just like a normal version id, except it's the string `null`.
Less relevant, but moto actually creates predictable, incremental `VersionId`s for versioned objects. According to my tests, AWS uses a random string as `VersionId`. That's kind of logical, a counter wouldn't be a great fit for them as it would require locks and ugly stuff. However, I think using an incremental id might lead to some confusion to moto users because they …

[S3] Support null version ids for buckets with versioning disabled

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

[describe_cluster](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#describe_clusters-instance_method) is supposed to return an empty array of clusters when given the name of a cluster that does not exist.
```
$ aws ecs describe-clusters --clusters "foobar"
{
"clusters": [],
"failures": [
{
"arn": "arn:aws:ecs:us-east-1:123456:cluster/foobar",
"reason": "MISSING"
}
]
}
```

Returns an empty list when the cluster does not exist

---

moto/ecs/models.py
moto/iam/models.py

This adds `get_cfn_attribute` methods for ECS clusters and services.
Supported `Fn::GetAtt` attributes are in the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html), a screen grab of the ECS ones are below
EDIT: I also fixed the `get_cfn_response` return for iam instance profiles. I'm happy to rename this branch if you'd prefer as it's no longer just ECS outputs!

Add get_cfn_attribute support for ECS Cluster and Service

---

moto/iam/models.py
tests/test_iam/test_iam.py

When creating a new IAM policy version with create_policy_version,
we cannot use the length of the versions list to calculate VersionId.
Keep track of the next version id to use as a non-decreasing counter.
Fixes #2157

[iam] create_policy_version: Fix version id calculation

---

setup.py

Given how moto is intended to be used, and how it uses Jinja2, [CVE-2019-10906](https://nvd.nist.gov/vuln/detail/CVE-2019-10906) is unlikely to affect many users, but we should use a secure version anyway just in case moto is being used in unforeseen ways.

Security: CVE-2019-10906

---

moto/s3/models.py
tests/test_s3/test_s3.py

The response of the copy-object operation was missing VersionId property
when source bucket is not versioned.

Fixed copy-object from unversioned bucket to versioned bucket

---

moto/ec2/models.py
tests/test_ec2/test_tags.py

Raise MissingParameterError exception in models/validate_resource_ids of ec2.
Add ec2 create tag with empty resource test case.
Add ec2 delete tag with empty resource test case.
Related: #2129
Reference
boto3 create_tags
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_tags
boto3 delete_tags
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.delete_tags
Amazon EC2 API Reference Actions CreateTags
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html
Amazon EC2 API Reference Actions DeleteTags
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteTags.html

Fix #2129 EC2 tag should raise ClientError when resource is empty

---

moto/kms/responses.py
tests/test_kms/test_kms.py

add KeyId value to [kms.responses.encrypt](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms.html#KMS.Client.encrypt) and [kms.responses.decrypt](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms.html#KMS.Client.decrypt) per boto docs:
*Encrypt*
> Return type
> dict
> 
> Returns
> Response Syntax
> 
> {
>     'CiphertextBlob': b'bytes',
>     'KeyId': 'string'
> }
> Response Structure
> 
> (dict) --
> 
> CiphertextBlob (bytes) --
> 
> The encrypted plaintext. When you use the HTTP API or the AWS CLI, the value is Base64-encdoded. Otherwise, it is not encoded.
> 
> KeyId (string) --
> 
> The ID of the key used during encryption.
*Decrypt*
> Return type
> dict
> 
> Returns
> Response Syntax
> 
> {
>     'KeyId': 'string',
> …

add KeyId value to kms.responses.encrypt and kms.responses.decrypt

---

IMPLEMENTATION_COVERAGE.md
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

This covers both the NewPath and NewUserName parameters for update_user, but
without regex validation for these values.
I'm in two minds about adding validation. It would be fairly trivial to add validation, but that currently isn't in place on create_user either. Happy to add this If people prefer it. I also didn't fancy adding two new exception classes for the validation errors either (side point: should all validation exceptions be one exception class?)
Fixes #2105

Add support for iam update_user

---

moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py

This pull request fix #2113.
moto must return Http status code 201 when lambda publish_version has succeeded

Fix lambda publish_version returns wrong status code

---

moto/ec2/responses/instances.py

This is a very simple fix for the tags problem metioned in #2148 be aware a similar problem may occur in other places. It is also not easy to find what it should act like aside from probing boto3 this means a similar problem will no doubt have to be fixed at somepoint in the future.
The fix is increadibly simple all it does is remove tagSet from the response when there are no tags to be contained within it. This means it acts the same as AWS and by virtue boto3.

A fix for tags not mimicking AWS

---

tests/test_iam/test_iam.py

When testing that a role ARN is created as expected, if path is not passed to the create_role call then the ARN is returned with None for the path. 
```
iam_client = boto3.client('iam')
iam_client.create_role(
RoleName="test-role",
AssumeRolePolicyDocument=json.dumps(policy_document),
Description="test-description")
resp = iam_client.get_role(RoleName="test-role")
print(resp['Role']['Arn'])
```
results in `arn:aws:iam::123456789012:roleNonetest-role` being printed.

Add test to verify create_role path defaults to /

---

moto/kms/exceptions.py
moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

Added generate_data_key and generate_data_key_without_plaintext
Fixed some errors with raising exceptions in kms response handlers where it would get rendered as XML errors instead of the JSON form. Caused issues when testing NotFound and ValidationExceptions in server mode.
Aint been here in a while, no clue whats changed, am I forgetting to do anything else?

KMS generate_data_key

---

AUTHORS.md
moto/autoscaling/responses.py
moto/core/utils.py
moto/sqs/responses.py
tests/test_autoscaling/test_autoscaling.py
tests/test_sqs/test_sqs.py

I noticed moto does not mimic the behavior of boto when it comes to returning the correct request ID in the response body.  Some services work, but those using XML templates that get rendered by Jinja unfortunately are broken.  This PR fixes that inconsistency.
The XML templates contain the text `{{ requestid }}`.  When the template is rendered that text is removed.  When removed, the decorator `@amzn_request_id` executes and is unable to find the `{{ requestid }}` text to be replaced.  The example below highlights how the `RequestId` is missing despite `x-amzn-requestid` being populated.
This PR removes the need for `{{ requestid }}` to appear in the XML templates.  Instead, the `@amzn_request_id` decorator looks for the `<RequestId></RequestId>` tag and populates the Request ID between …

Fix sending the Request ID in the response body

---

moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

When running:
```python
client.delete_cluster(ClusterIdentifier="identifier", SkipFinalClusterSnapshot=False, FinalClusterSnapshotIdentifier="Identifier-snapshot")
```
It would delete the cluster but not create the final snapshot. I have extended the functionality of `delete_cluster` such that a final snapshot will be generated. 
[boto3's delete_cluster reference](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift.html?highlight=redshift#Redshift.Client.delete_cluster)

Updated delete_cluster() for redshift

---

moto/kinesis/utils.py

Using right encode and decode methods according to python version.
There was an attempt in #1854 before, but python 2 were not covered.

Fix base64 deprecated methods in kinesis.utils

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/utils.py
tests/test_awslambda/test_lambda.py

fix #2190
- list_versions_by_function return published version not only $LATEST
- when create_function called with Publish=True, Lambda Backend will automaticaly publish new function version.
- fixed some wrong existing test case and lambda backend behavior.Because  I fix this issue, those test case will fail
- Some api response that control lambda function, will return arn that not contains lambda version.
For example get_function without qualifier,create_function.
- And Some api response that control lambda version, will return arn that contains lambda version.
For example get_function with qualifier,list_versions_by_function.

fix #2190 lambda list_versions_by_function should  return published function versions

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Fixes #2212. Raises exceptions properly when functions are attempted that don't have support yet, to prevent confusion.

#2212 add support for delete on update_with_attribute_updates

---

moto/awslambda/models.py

Change docker library version check so that it sends the correct arguments for library versions 3+
@mikegrima mind reviewing before I merge.

Fix lambda test failures in travis

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/vpc_peering_connections.py
tests/test_ec2/test_vpc_peering.py

Add a class level store in models/VPCPeeringConnectionBackend of ec2
for saving vpc peering connection.
Any instance can correctly save VPC peering connection info
on both region when it create vpc peering connection.
Update vpc_peering_connections in ec2/responses to meet new version:
DESCRIBE_VPC_PEERING_CONNECTIONS_RESPONSE,
ACCEPT_VPC_PEERING_CONNECTION_RESPONSE,
Previous code only create one region VPC peering connection but
doesn't create the other region VPC peering connection
when create cross region VPC peering connection.
Tested in real AWS environment at first
and create unit test case according to real AWS environment response.
Add 5 test cases
VPC cross region delete case
VPC cross region accept case
VPC cross region accept wrong region case
VPC cross region reject case
VPC …

Fix #1842 Create cross region VPC peering connection in both region

---

moto/sns/models.py

Hello,
I have submitted a fix to this issue over at [localstack](https://github.com/localstack/moto/pull/1)'s fork of this project,  I figured I'd submit this here as well since it seems to be more of a bug in moto than localstack.  Please forgive me for reproducing this issue with localstack and not just moto, but I think it's pretty clear what's going on.
Here's a copy of that issue:
---
I'm using the aws .net sdk to connect to sns - AWSSDK.SimpleNotificationService v3.3.101.1
debug output from localstack docker image 0.9.0:
```
127.0.0.1 - - [30/Apr/2019 16:43:39] "POST / HTTP/1.1" 500 -
Error on request:
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File …
```

SNS models.py _get_values_nexttoken doesn't handle next_token empty string

---

moto/ec2/models.py
tests/test_ec2/test_elastic_block_store.py

This is in reference to issue #2141.  Making the owner-id filter available when querying for a Snapshot.
https://github.com/spulec/moto/issues/2141
**Update: May 24, 2019**
This issue and PR have been up for quite some time. The tests pass and I sure would like to be able to use the code. I have received no feedback so far. What does it take to get this done?

Issue #2141 Adding owner-id to the filter for Snapshot

---

moto/glue/models.py
moto/glue/responses.py
tests/test_glue/test_datacatalog.py

As the title says, this just adds the `delete_table` call to glue.

Add glue.delete_table endpoint, for allowing tables to be deleted

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py
tests/test_autoscaling/test_elbv2.py
tests/test_autoscaling/utils.py
tests/test_ec2/test_elastic_block_store.py
tests/test_ec2/test_instances.py
tests/test_ec2/test_regions.py
tests/test_elb/test_elb.py
tests/test_redshift/test_redshift.py

This is picking up @kawaiwanyelp's #1985, we can close the other one.  The change in that PR said:
> This issue refers to/fixes #1984.
> * I have made changes to ASG initialization that properly sets and updates availability zones (both direct setting, and if there are VPC identifiers that need to be taken into account).
> * I have made changes to propagate one of an ASG's availability zone to its instances when creating them.
> * I have made changes to the return templates for an ASG's describe methods (describe_auto_scaling_groups, describe_auto_scaling_instances) so that instead of returning a hardcoded AZ (us-east-1e), a 'real' AZ is returned.
> * I have written tests for the above changes.
In addition to the above changes, I'm going through and fixing tests that were broken by the …

Autoscaling instance azs

---

moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr_boto3.py

This change adds support for passing `CustomAmiId` in EMR's `run_job_flow` and returning `CustomAmiId` in EMR's `describe_cluster`.
https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-custom-ami.html
I only added tests to `test_emr_boto3.py` since `test_emr.py` appears to be deprecated. If you'd like, I can add tests there as well.

Support CustomAmiId in EMR

---

README.md

While I was checking moto library I found a small typo in the first example. This PR fix it.

Fix small issue in README example

---

moto/core/responses.py
tests/test_core/test_responses.py

It seems like we always call `parse_qs` on the request body, which may raise a `UnicodeEncodeError` for some bodies. I observed this happening with polylines in particular when using this with DynamoDB.
This just ignores those errors, as if it happens then we wouldn't usually look at the querystring anyway.

Handle UnicodeEncodeError when parsing querystring

---

moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

Adds binary values (SecretBinary parameter) support for the following operations in SecretsManager:
* [create_secret](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.create_secret)
* [get_secret_value](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.get_secret_value)

SecretsManager secret value binary support

---

moto/iam/models.py
moto/iam/responses.py

`str(datetime.utcnow())` returns a timestamp that's not of the same format as the AWS SDK uses, in short it's missing the `T` between the date and the time.
This causes issues for e.g. Terraform and probably other AWS Go SDK users. There seems to be some differences between endpoints whether they return milliseconds or not, the AWS API docs were reviewed and the decision whether to return timestamps with milliseconds or not based on the example response documented.
As the timstamps are generated for uniqueness rather than being hardcoded and then directly cast to a UTC (Z) formed timestamp pytz was removed as timezone correctness is probably not important.

Uniform IAM datetime ISO 8601 handling

---

moto/iam/aws_managed_policies.py
moto/iam/models.py
scripts/update_managed_policies.py
tests/test_iam/test_iam.py

When `get_policy` and `get_policy_version` was called with an AWS managed policy, moto did not return any results. This has been fixed now.

Fixes for get_policy and get_policy_version with AWS managed policies

---

moto/iam/models.py
tests/test_iam/test_iam.py

My previous fix (#2231) accidentally returned policy version's Document for AWS managed policies as Python `dict`s which did not get converted successfully. This is fixed now by returning them as properly converted strings.

Fixed policy version's Document type for AWS managed policies

---

moto/glue/responses.py
tests/test_glue/test_datacatalog.py

I added the `batch_delete_table` endpoint for glue, and while adding that realized the `batch_create_partition` endpoint wasn't correct.
`batch_create_partition` always returned a dict with the `Errors` key, which should only be present when errors actually occur.

Add glue.batch_delete_table, and fix glue.batch_create_partition to respond correctly

---

moto/iam/exceptions.py
moto/iam/models.py
moto/iam/policy_validation.py
tests/test_iam/test_iam.py
tests/test_iam/test_iam_groups.py
tests/test_iam/test_iam_policies.py

I implemented the basic validation of IAM policy documents. The implementation is not complete, for example, I only validate a few conditions (those starting with `Date`) thoroughly, but all the basic cases are covered. 
I added a lot of test cases for both valid and invalid policy documents. I also verified the results (responses returned by AWS) for every test case.
Fixes #1435.

IAM policy document validation

---

moto/cloudformation/parsing.py

Per the AWS docs, load balancers are also restricted to a name of <= 32 char 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
`The name of the load balancer. This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, must not begin or end with a hyphen, and must not begin with "internal-".`
In my specific case, I was using CF to make the both an NLB and target group and my target group was inheriting it's name from the NLB.  
Down in the target group code, it failed name validation for length.  
I'm suspicious there may be a secondary issue in the ELBv2 code as I would have expected a name too long error for the NLB.  Though, this may be an …

ELBv2 LBs names must be 32 char or shorter

---

moto/cloudformation/utils.py

The bug: `random.choice` cannot interpret `'A-Z'`, it requires all the individual characters in the parameter list.
This should resolve the sometimes failing `test_create_target_groups_through_cloudformation` test case.

Fixed random_suffix()

---

moto/ecr/models.py
tests/test_ecr/test_ecr_boto3.py

This should fix the bug identified in #2246 
This is a bug fix to my initial work when implementing
batch_delete_image. Deleting the last tag for a given image should
delete the image from the backend.
I also cleaned up the tests previously-added in the initial
implementation.

Delete ECR image when it has no tags

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Ability to use ProjectionExpression with dynamodb.scan().
ProjectionExpression is not implemented for table.scan() but is for table.query() - took the majority of my inspiration for this from the query function.
#1491

ProjectionExpression works with table.scan()

---

moto/dynamodb2/responses.py

The golang client doesn't send this parameter by default, resulting in a `KeyError` in moto

not requiring the provisioned throughput key

---

setup.py

This is to address the `load` vs `safe_load` issue detailed in this CVE[1] now that PyYAML finally has non-beta versions with this fix.
[1] https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342

bump PyYAML minimum version

---

other_langs/sqsSample.scala

This is an example of a stand-alone server configuration using Scala.
The application logic is the same as for a [Java example](https://github.com/spulec/moto/blob/master/other_langs/sqsSample.java_langs/sqsSample.java). It also uses AWS SDK for Java. However, the Java example uses deprecated API, so the implementation for Scala is slightly different.

Example of using a moto server with Scala

---

moto/packages/httpretty/core.py
tests/test_core/test_socket.py

This PR includes changes to make the fake socket actually conform to the socket.socket module API on Python 3. Previously, the `fd` argument was not supported, which resulted in effectively breaking Python's asyncio module (which creates a `socket.socketpair` while the mock was active.
Resulting exception under Py3: https://travis-ci.org/spulec/moto/jobs/553839413#L5184
```
ERROR: test_asyncio_deprecated (test_socket.TestSocketPair)
File "/home/travis/build/spulec/moto/moto/core/models.py", line 80, in wrapper
File "/home/travis/build/spulec/moto/tests/test_core/test_socket.py", line …
```

Adds failing test for socket.socketpair()

---

moto/iam/models.py
tests/test_iam/test_iam.py

This change raises an exception if an inline policy of a role could not be found.
Also adds a test to validate the behaviour.
Fixes #2254

Raise exception if a role policy is not found

---

moto/iam/responses.py

Add the CreateDate field to the list_groups_for_user to match the correct AWS response. Fixes #2242

Add CreateDate to iam list_groups_for_user.

---

moto/sts/models.py
moto/sts/responses.py
moto/sts/utils.py
tests/test_sts/test_sts.py

Previously, the operation AssumeRole returned fixed hardcoded credentials. This PR fixes this by using randomly generated credentials, which are in the same format as the ones from AWS.

AssumeRole returns randomly generated credentials.

---

moto/ses/feedback.py
moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses_sns_boto3.py

Enable SES feedback (Delivery, Bounce, Complaint) via SNS topic.
- SES implements the AWS SES API method set_identity_notification_topic that will save the topic configuration
- `send_email` and `send_raw_email` check the SNS Topic configuration
- The SES feedback messages are static and are extracted from https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html

Enable SES feedback via SNS

---

README.md
setup.py
tox.ini

Python 3.4 is EOL, also add python 3.7 to tox.ini.
https://github.com/asherf/moto/blob/versions/README.md

Update supported python versions, add badages.

---

moto/ec2/models.py
moto/ec2/responses/elastic_network_interfaces.py
tests/test_ec2/test_elastic_network_interfaces.py

Extend EC2 DescribeNetworkInterface filter support
* add description property to EC2 NetworkInterface
* extend DescribeNetworkInterfaces filter support with description,
subnet-id, private-ip-address attributes
Resolves: #1786

Extend EC2 DescribeNetworkInterface filter support

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

To support it, we need to keep multipart info in the key itself when
completing multipart upload.
Fixes #2154
Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>

moto: s3: support partNumber for head_object

---

setup.py

This entry is added in [1]. New statements in [1] use the built-in datetime module, which is available since Python 2.3 [2]. On the other hand, when running `pip install moto`, pip installs Zope Datetime module [3], which is unnecessary.
[1] https://github.com/spulec/moto/commit/ed93821621af337b701319823f9cb022e49c7a6d
[2] https://docs.python.org/2.7/library/datetime.html
[3] https://pypi.org/project/DateTime/

setup.py: remove unnecessary 'datetime' entry

---

moto/core/models.py
moto/sqs/models.py
tests/test_core/test_context_manager.py

Closes https://github.com/spulec/moto/issues/1915

Have context manager return mock.

---

IMPLEMENTATION_COVERAGE.md
moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Introduce the CognitoIDP's UpdateUserPoolDomain to update configuration
options of the associated domain to a Cognito IDP (e.g. ACM certificate).
This implements feature #2308

Implement update_user_pool_domain

---

IMPLEMENTATION_COVERAGE.md
moto/sts/models.py
moto/sts/responses.py
tests/test_sts/test_sts.py

The AssumeRoleWithWebIdentity is a similar endpoint to STS's AssumeRole
where the authentication element is a JWT id_token from a configured OP.
This commit implements the functionality and relies on the same result
generated for the regular AssumeRole.
This implements feature #2312

Implement assume_role_with_web_identity

---

moto/autoscaling/models.py
moto/ec2/responses/instances.py
tests/test_autoscaling/test_autoscaling.py

When an EC2 instance that is attached to an Auto Scaling group is terminated through the `TerminateInstances` API operation, the Auto Scaling group should automatically replace this terminated instance.

Auto Scaling groups recreate terminated instances

---

moto/elbv2/models.py
moto/elbv2/responses.py
tests/test_elbv2/test_elbv2.py

When an EC2 instance is registered as a target in an ELBv2 target group, and it is stopped, the following should be its health status:
```json
{
"State": "unused",
"Reason": "Target.InvalidState",
"Description": "Target is in the stopped state"
}
```

ELBv2 DescribeTargetHealth returns correct response for stopped instance

---

moto/autoscaling/models.py
tests/test_autoscaling/test_autoscaling.py

A change in UpdateAutoScalingGroup:
* if a value for MinSize is specified without specifying a value for
DesiredCapacity, and the new MinSize is larger than the current size of
the group, set the group's DesiredCapacity to the new MinSize value
* if a value for MaxSize is specified without specifying a value for
DesiredCapacity, and the new MaxSize is smaller than the current size of
the group, set the group's DesiredCapacity to the new MaxSize value
Resolves: #2257

Handle change of ASG desired capacity on min and max size update

---

moto/autoscaling/responses.py
moto/rds/responses.py
moto/rds2/responses.py

It fixes the **TypeError** described below by alternating `_get_param()` with `_get_int_param()` on parsing the parameter `MaxRecords` in below APIs:
* `autoscaling.describe_launch_configurations()`
* `rds.describe_db_instances()`
* `rds2.describe_option_groups()`
* `rds2.describe_db_parameter_groups()`
I checked `MaxRecords` should be `int` in the above APIs in Boto3 API documents.
I got an error when I set `MaxRecords` in `describe_launch_configurations()`:
```python
self = <moto.autoscaling.responses.AutoScalingResponse object at 0x1178d2518>
def describe_launch_configurations(self):
names = self._get_multi_param('LaunchConfigurationNames.member')
all_launch_configurations = self.autoscaling_backend.describe_launch_configurations(names)
marker = self._get_param('NextToken')
all_names = …
```

Fix 'MaxRecords' type issues by _get_param()

---

moto/glue/responses.py
tests/test_glue/test_datacatalog.py

Unexpectedly, the actual response from AWS when attempting to `batch_get_partition` is to just ignore missing partitions in the call, and not error or place them in another key.

Add glue.batch_get_partition endpoint

---

moto/route53/models.py
tests/test_route53/test_route53.py

Implemented UPSERT for `change_resource_records()` in Route 53 if the record is not a simple routing policy i.e. weighted or latency based.
Without this PR, moto only compares the record name and type and will always change the first record in the list. Now, upsert also looks at the `set_identifier` to change the correct record.

added support to UPSERT records that are not simple routing policy such as weighted records

---

moto/autoscaling/exceptions.py
moto/autoscaling/models.py
moto/autoscaling/responses.py
moto/ec2/models.py
tests/test_autoscaling/test_autoscaling.py
tests/test_autoscaling/utils.py

Implemented creating Auto Scaling group from instance and added tests for it.
Without this PR, when `CreateAutoScalingGroup` was called without a `LaunchConfigurationName` parameter, and the `InstanceId` was specified instead, moto returned an internal server error (500).

Implemented creating Auto Scaling group from instance

---

IMPLEMENTATION_COVERAGE.md
moto/cognitoidentity/models.py
moto/cognitoidentity/responses.py
moto/server.py
tests/test_cognitoidentity/test_cognitoidentity.py

Introduce the CognitoIdentity's GetOpenIDToken endpoint to retrieve a
JWT tuple from Cognito's Identity Pool for a given IdentityId.
This implements feature #2310

Implement get_open_id_token

---

tests/test_s3/test_s3.py

There is no reason to use 5M chunks, especially with the reduced_part_size
decorator. Also made part_size to be variable to add extra layer of
testing to make sure that moto is handling that scenario correctly.
Related to #2307
Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>

tests: multipart: use REDUCED_PART_SIZE and variable part size

---

moto/s3/responses.py
tests/test_s3/test_s3.py

This PR fixes the S3 behavior when the `delete_objects()` (via boto3) is called without parameters. According to the AWS API usage, it should raise an exception:
```
>>> import boto3
>>> boto3.client('s3').delete_objects(Bucket='bucket-name-here', Delete={'Objects': []})
File "<stdin>", line 1, in <module>
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 324, in _api_call
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py", line 622, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the …
```

Raising MalformedXML exception when using boto3 client and s3.delete_objects()

---

moto/ec2/models.py
tests/test_ec2/test_amis.py
tests/test_ec2/test_elastic_block_store.py

When attempting to use Moto to do something similar to this:
``` python
@mock_ec2
def test_copy_image_example():
conn = boto3.client("ec2")
copy_resp = conn.copy_image(SourceImageId="one of the default ami ids from resources")
describe_resp = conn.describe_images(Owners=["self"])
describe_resp["Images"].should.have.length_of(1)
```
The test ended up failing, and `describe_images` responded with an empty list.
To me, the expected result would be that any image created with `copy_image` would be given the same OwnerId as images found when using `Owners=["self"]`.
The first commit does just that, by creating a common `OWNER_ID` used by all the ec2 models.
The second commit adds a test case for the above example code to ensure future changes don't accidentally result in `copy_image` using a …

Use the same default Owner ID between EC2 models

---

moto/ecs/exceptions.py
moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

This adds support for setting tags on task definitions and retrieving them via `list_tags_for_resource`
See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.list_tags_for_resource

Add ecs list tags for resource

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

The AWS SDK for Go fails to parse the response of the `ecs.DescribeServices()` function because it expects the values of the fields [`createdAt`][1] and [`updatedAt`][2] to be timestamps, not ISO 8601.
This change converts the value of each field to a timestamp instead of ISO.
[1]: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Deployment.html#ECS-Type-Deployment-createdAt
[2]: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Deployment.html#ECS-Type-Deployment-updatedAt

Convert fields createdAt and updatedAt of ECS deployment to timestamp

---

moto/dynamodb2/responses.py

When run not as a decorator dynamodb2 displays an invalid escape sequence error in 3.6/7
/moto/dynamodb2/responses.py:603: DeprecationWarning: invalid escape sequence \s
'\s*([=\+-])\s*', '\\1', update_expression)

Resolve invalid escape sequence

---

README.md
moto/config/exceptions.py
moto/config/models.py
moto/config/responses.py
moto/iam/models.py
setup.py
tests/test_config/test_config.py

- Added support for the following APIs:
- put_configuration_aggregator
- describe_configuration_aggregators
- delete_configuration_aggregator
- put_aggregation_authorization
- describe_aggregation_authorizations
- delete_aggregation_authorization

AWS Config Aggregator support

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/launch_templates.py
moto/ec2/utils.py
tests/test_ec2/test_launch_templates.py

Specifically, this adds the CreateLaunchTemplate, CreateLaunchTemplateVersion, DescribeLaunchTemplates, and DescribeLaunchTemplateVersions endpoints.
I'm not super sure that I matched the code conventions, and if I didn't please let me know and I'll fix them. This is the first time I've tried to add an entirely new resource type, and I think I eventually got there, but it still feels rough.
One other note is that the travis tests for my fork failed on the python2.7 `SERVER_MODE=true` set, and I'm not sure why, though it does appear to have succeeded in not server mode python2.7, and server mode for python3. Not sure if it'll continue with this PR or if it's an intermittent thing, and if it does continue I have no idea how to fix it. [Link to failing …

Add basic endpoints for EC2 Launch Templates

---

moto/s3/responses.py

Base on AWS [document](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html#v2-RESTBucketGET-responses) and real behavior, the `KeyCount` field in `list_objects_v2` should be sum of Keys and CommonPrefixes, though it's called "Key"Count.

Fix KeyCount in s3.list_objects_v2

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Fix for https://github.com/spulec/moto/issues/2380

2380 - Validate parameter-list for duplicates in dynamodb.batch_get_item

---

moto/ec2/responses/instances.py
moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

Previously, when querying the target healths for an ELBv2 target group (DescribeTargetHealth), it showed terminated instance to be healthy. Now when an instance is terminated, it is also completely removed from any ELBv2 target group it has been registered with.

Terminated EC2 instances are deregistered from ELBv2 target groups.

---

moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

Enhanced VPC Routing was added sometime ago and now add for unit testing.
Also EnhancedVpcRouting is only available when mock_redshift not mock_redshift_deprecated (boto3 not boto).

add enhanced vpc routing option to redshift moto

---

moto/sqs/models.py

I got list of static attributes from list of **Attributes** in docs here https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs.html#SQS.Client.create_queue

issues-2386 make comparing exists and new queues only by static attrs

---

moto/apigateway/models.py
tests/test_apigateway/test_apigateway.py

This PR add support for API Gateway key tags. 
boto3 support tags since version 1.9.154.

Add tag support to API Gateway keys

---

moto/iotdata/exceptions.py
moto/iotdata/models.py
tests/test_iotdata/test_iotdata.py

This PR add validation for iot-data update_thing_shadow(),fixing #2392

fix #2392 Add validation for device shadow version

---

moto/logs/models.py

As documented here:
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_LogGroup.html
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_LogStream.html
The type for `creationTime` and `lastIngestionTime` should be Long.

Change creationTime and lastIngestionTime type in LogStream and LogGroup to Long

---

moto/s3/urls.py
moto/server.py
tests/test_s3/test_s3.py

Allows request paths to start with multiple slashes for S3. This PR fixes #1637 for mocked requests.
Unfortunately, similar problem exists for server mode, but it's caused by an error in Werkzeug.

Allows leading // for mocked s3 paths (fix for #1637)

---

moto/route53/models.py
tests/test_route53/test_route53.py

Currently, when you call `boto3.client('route53').list_tags_for_resource()` on a resource without any tags, it results in a jinja templating error (because the backend returns `None` when the template expects a dict).
This fixes the backend to return an empty dict when no resources are found, so that the call works as expected.

Don't error out on route53.list_tags_for_resource when resource has no tags

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Fixes #2382
The `maxReceiveCount` value is stored as an int, reflects the behavior as in AWS.

Store SQS RedrivePolicy maxReceiveCount value as int

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

This patch handles the case when ProjectionExpression looks like "#1, ..., #10" - the previous code used `replace`, which would make the resulting projection into "foo, ..., foo0".

Prevent overlapping expr name prefixes from corrupting projection expr

---

tests/test_batch/test_batch.py

This PR strengthens the `tests/test_batch/test_batch.py` unit test.
**Expected behavior:**
When you register a job definition using the name of a pre-existing job, the revision number should increment.  E.g., using the AWS CLI:
```
williamharvey@fnord $ aws batch register-job-definition --job-definition-name='wjh-bippy-2019-09-10' --type='container' --container-properties='{"image": "busybox", "vcpus": 1, "memory": 128, "command": ["sleep", "10"]}'
arn:aws:batch:us-east-1:scrubbed:job-definition/wjh-bippy-2019-09-10:1    wjh-bippy-2019-09-10    1
williamharvey@fnord $ aws batch register-job-definition --job-definition-name='wjh-bippy-2019-09-10' --type='container' --container-properties='{"image": "busybox", "vcpus": 1, "memory": 127, "command": ["sleep", "10"]}' …
```

Fix/tighten AWS Batch test_reregister_task_definition unit test

---

moto/iam/policy_validation.py
tests/test_iam/test_iam_policies.py

When I executed terraform with multiple statements it generate an request with empty `Sid` attribute on each statement.
This problem was originally created in localstack ([Issue 1556](https://github.com/localstack/localstack/issues/1556)), but the related validation was applied by moto.
The same request were sent to AWS and were successful.

Fix multiple IAM Policy Statement creation with empty sid

---

moto/apigateway/models.py
moto/core/models.py
tests/test_core/test_request_mocking.py

This unblocks requests to other websites with requests while Moto
is activated. It also adds a wildcard for AWS services to still
ensure no accidental requests are made for unmocked services

Cleanup responses mocking. Closes #1567

---

IMPLEMENTATION_COVERAGE.md
moto/kms/exceptions.py
moto/kms/models.py
moto/kms/responses.py
moto/kms/utils.py
requirements-dev.txt
tests/test_kms/test_kms.py
tests/test_kms/test_utils.py

There are a variety of properties that the `kms:Encrypt`, `kms:Decrypt`, and `kms:GenerateDataKey/WithoutPlaintext` methods in `moto` have been lacking in order to properly model the properties of the KMS API. Some of the most important of these are honoring encryption context, only allowing decryption by the master key that encrypted a ciphertextblob (and finding that master key based on a blob), and identifying the decrypting master key on decrypt. A less important, but valuable, property is that the ciphertextblob should be reasonably small and opaque.
I was discussing these issues with a colleague a while ago, and it occurred to us that the simplest way to achieve all of these would be to just actually do the encryption. So I did.
I do want to note a few very important things here for …

Making kms:Encrypt/Decrypt/GenerateDataKey more real

---

moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

Following up from #2397, this:
1. Normalizes how key IDs are validated for KMS calls.
2. Adds key ID validation to all KMS calls that were missing key ID validation.
I also made sure that each method accepts the same types of key IDs (ex: aliases or no aliases) as the actual KMS APIs.

Normalize KMS key ID validation

---

moto/s3/responses.py
moto/s3/utils.py
tests/test_s3/test_s3.py
tests/test_s3/test_s3_utils.py

Issue: https://github.com/spulec/moto/issues/2431
~~Open to suggestions on a better approach than just calling clean_key_name multiple times.~~
Updated solution in the PR is to undo the the key cleaning in the delete keys method.
Open to any other suggestions.
update 2019-09-24:
Something is still not quite right - I am using moto to mock an s3 back for use some spark integration tests. The write is still failing and I haven't been able to full figure out what is different when the key is url encoded. I'll work on getting some tcpdumps of a working flow and non-working flow for further analysis.

WIP Fix for #2431 delete objects fails with url encoded key

---

moto/core/exceptions.py

In the golang SDK this throws an unmarshaling error:
/usr/local/Cellar/go/1.12.6/libexec/src/encoding/xml/read.go:209 &errors.errorString{s:"unknown error response tag, {{ Response} []}"}
err: <*>SerializationError: failed to unmarshal error message

fixing ErrorResponse top-level tag

---

moto/s3/responses.py
tests/test_s3/test_s3.py

PR #2062 fixes copy for unicode keys. However, the change breaks keys
with question marks. Here is an alternative fix that works for both
emojis and question marks.
I notice this when running the test suite of aiobotocore. One of the
tests [1] is broken with moto >= 1.3.8.
@domtes Could you check if your tests are still green after this change?
[1] https://github.com/aio-libs/aiobotocore/blob/0.10.3/tests/test_basic_s3.py#L314-L329

Fix copying S3 objects with question marks in keys

---

moto/stepfunctions/models.py
moto/stepfunctions/responses.py
tests/test_stepfunctions/test_stepfunctions.py

Some updates for the recently added stepfunctions utility.
* The ARN format for IAM seems to be wrong, there should be a double colon after ``iam``: ``arn:aws:iam::<account>...``
* I spotted a probable copy-paste mistake in an exception message, where it reported "Invalid Role ARN" where it meant "Invalid State Machine ARN"
* ``start_execution()`` can accept a ``name`` argument in which case stepfunctions will use that instead of a random UUID as the execution ID

Stepfunctions minor improvements

---

CONFIG_README.md
README.md
moto/config/exceptions.py
moto/config/models.py
moto/config/responses.py
moto/core/exceptions.py
moto/core/models.py
moto/s3/config.py
tests/test_config/test_config.py
tests/test_s3/test_s3.py

PR to add experimental support for listing and querying AWS Config for resource types that have the feature implemented.
The benefit of this PR is to develop unit tests against a data set that AWS Config would likely return based on the existing state in Moto.
At this time, I am developing the feature for S3 as I have an immediate need for it. This PR only contains the ability to list S3 buckets in AWS Config (both aggregated and non-aggregated). A follow-up PR will contain a feature to return the object from the Config API.

Adding support for querying AWS Config

---

IMPLEMENTATION_COVERAGE.md
moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

Adds support for:
* Passing `tags` to `create_service`
* Getting tags for an ECS service from `list_tags_for_resource`
* Tagging an ECS service with `tag_resource`
* Untagging an ECS service with `untag_resource`

Add support for tagging and untagging ECS services

---

moto/ecs/models.py
moto/events/__init__.py
moto/events/models.py
moto/events/responses.py
tests/test_ecs/test_ecs_boto3.py
tests/test_events/test_events.py

This PR does two things:
1) Pass the `region_name` to ECS models to use when creating and describing resources. Previously `us-east-1` was hard coded in the ARNs
2) Add multi region support for Cloudwatch Events
Please let me know if there are any questions, thanks!

Events and ecs multi region

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

This adds nested map support to the REMOVE operation on dynamodb2, fixing #1834

#1834 Fix DynamoDB UpdateExpression support for REMOVE on nested maps

---

moto/awslambda/models.py
moto/dynamodb2/models.py
tests/test_awslambda/test_lambda.py

Currently, only option for EventSourceMappings is to kick off a Lambda function after receiving an SQS message
This PR adds the option to kick off a Lambda function after updating a DynamoDB table

Feature: Add option for DynamoDB stream to kick off lambda

---

moto/dynamodb2/models.py

When returning results in `query` method, results are sorted by `range_key`.
```
results.sort(key=lambda item: item.range_key)
```
However, when comparing `range_key`, it uses `DynamoType.value` instead of `DynamoType.cast_value`. It causes errors when `DynamoType` is a number.
```
>>> '10' > '2'
False
```

BUG FIX: Use cast_value when comparing DynamoType

---

moto/kinesis/models.py
moto/kinesis/responses.py
tests/test_kinesis/test_firehose.py

This implements ExtendedS3DestinationConfiguration, allowing
serialization to Parquet and ORC formats as part of a Firehose
destination.

Supporting more modern Firehose features

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Also fixes #1686
Also adjusted the `CREATE_QUEUE_RESPONSE` to align with the current API response. See https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#API_CreateQueue_ResponseElements

Add tags parameter to sqs.create_queue

---

moto/cognitoidp/exceptions.py
moto/cognitoidp/models.py
tests/test_cognitoidp/test_cognitoidp.py

If a user is attempted to be added to a pool that already contains a user with that username, the UsernameExistsException is thrown, to match AWS behaviour.
resolves https://github.com/spulec/moto/issues/2356

Existing user now raises a UsernameExistsException

---

moto/sns/models.py
tests/test_sns/test_subscriptions_boto3.py

As I explained in the issue #2441 the field `attributes` of SNS subscription is empty when they are created with moto. 
This PR is only here to have mocked subscriptions that look a bit more like real subscriptions.

Issue #2441 Add informations in SNS subscriptions `attributes`

---

moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py

In all of the tests of `create_db_instance()`, the `AllocatedStorage` parameter is provided.  The [RDS API reference](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html) says this parameter is optional; however, when none is provided, moto returns an obscure error message:
```
self = <botocore.parsers.QueryParser object at 0x113745890>, shape = <Shape(Integer)>, text = 'None'
@_text_content
def _handle_integer(self, shape, text):
>       return int(text)
E       ValueError: invalid literal for int() with base 10: 'None'
/usr/local/Cellar/pyenv/1.2.13_1/versions/3.7.4/envs/rds_encrypt/lib/python3.7/site-packages/botocore/parsers.py:466: ValueError
```
This PR adds default values that correspond to the current default API behaviors.

fix(rds2): handle create_db_instance when AllocatedStorage is not specified

---

moto/s3/models.py
tests/test_s3/test_s3.py

The variable `key` may `None`.
But, its attribute `multipart` will be accessed even though `key` is `None`.
https://github.com/spulec/moto/blob/4da9ec134693afbbcf05d8ae284a140d103ba422/moto/s3/models.py#L1110-L1111
#2307

Avoid exception occur in `moto.s3.models.S3Backend.get_key`

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Adding the ability to specify the version id of an S3 key when tagging an object.
Issue: https://github.com/spulec/moto/issues/2486

Add tagging to s3 versioned objects

---

moto/secretsmanager/exceptions.py
moto/secretsmanager/models.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_secretsmanager/test_server.py

Secretsmanager will raise a ResourceNotFoundException with a slightly different message when a secret exists but has not SecretString or SecretBinary. Current behaviour of moto is to successfully return a response dictionary with no SecretString or SecretBinary, which does not happen with boto3.
Existing uses of ResourceNotFoundException will still give the same message, and the newly added one will give the observed, different message. A slight punctuation mistake was fixed in the original message.

Fix getsecretmananger error

---

tests/test_awslambda/test_lambda.py

Python 3.8 will probably [raise SyntaxWarnings](https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior) on the flake8 F632 issue raised below.
[flake8](http://flake8.pycqa.org) testing of https://github.com/spulec/moto on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./tests/test_awslambda/test_lambda.py:1137:24: F632 use ==/!= to compare str, bytes, and int literals
assert len(messages) is 3
^
1     F632 use ==/!= to compare str, bytes, and int literals
1
```

Use ==/!= to compare str, bytes, and int literals

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

As per https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-KeyConditionExpression:
Hash Keys only support the equals-operator.
Sort keys support everything else
This PR adds a simple validation when attempting to use a non-equals operator on hash keys.
Fixes #520

DynamoDB - Add validation for Query Key Expression

---

moto/iam/models.py
tests/test_iam/test_iam.py

Add validation for delete_role and delete_user to ensure that:
- Any managed policies have been detached
- Any inline policies have been deleted
- The IAM entity has been removed from instance profiles (roles only)
prior to allowing successful deletion. This is being added to match the current behaviour in AWS.
Issue: #2503

Conflict detection for IAM delete_role and delete_user

---

setup.py

This adds a [Documentation URL](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls), which will display in the left-hand nav of the projects PyPI page, allowing users arriving there to get to the documentation slightly faster.

Add Documentation URL

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

Existing tests only tested whether Lambdas could be deleted when passing in a name.
According to the docs, Lambdas can also be deleted by passing in an ARN: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.delete_function
The list of mock-URLs had to be adjusted to account for the fact we're passing a HTML-safe ARN in the URL, which can contain ampersands

Feature - Lambda Delete by arn

---

moto/dynamodb2/comparisons.py

In Python 3 comparison functions `<` and `>` evaluate to `NoneType Exception` when a value is `None`. This did not happen in Python 2 where `None` was auto evaluated to an integer less than any available integer. This update is to make comparisons in `dynamodb2` work with Python 3.
This is a fix for Issue 2510

Fixing comparisons for python 3 in dynamodb Issue 2510

---

moto/iot/models.py
tests/test_iot/test_iot.py

Detach principal from thing when it is deleted

---

IMPLEMENTATION_COVERAGE.md
moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_topics.py
tests/test_sns/test_topics_boto3.py

The whole permission handling was wrongly implemented. If you add or remove a permission it changes the access policy of the topic. I also changed the default policy to the correct one and create it with the correct region and account id. Additionally I added more tests and some extra error handling.

Fix sns.add_permission & remove_permission

---

moto/config/models.py
moto/s3/models.py
tests/test_config/test_config.py
tests/test_s3/test_s3.py

- Small bug in tags with AWS Config
- Aggregated results lack "tags" in the result set
- Buckets also add a supplementary configuration of
"BucketTaggingConfiguration"

Small fix for S3-AWS Config compatibility

---

moto/core/responses.py

This is a fix for [#1870].
This is a second attempt at resolving the issues with producing an XML consistent with what is produced from AWS (i.e., no spaces/new lines between tags). Another attempt (https://github.com/spulec/moto/pull/2205) is currently failing in tests.
This attempt uses precompiled regex patterns as class attributes of the `_TemplateEnvironmentMixin` to remove trailing spaces and newlines after a `">"`, and preceding newlines/spaces before a `"<"`. This *explicitly* wasn't done with a single regex to ensure that even things like `"...<ID>\n      12345\n    </ID>"` are properly collapsed.

Remove newlines from XML responses

---

.travis.yml

https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release
> skip_cleanup is now deprecated, and cleanup is false by default. The default used to be true, so you had to opt out using skip_cleanup … and has been used a lot. Cleaning up the working directory from any left over build artifacts only made sense for few providers, so we have changed this default.

Fix deprecations in travis.yaml

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Basically, this PR changes how SSM parameters are stored in the backend to keep all previous versions, and then allow access to those versions via a `get_parameter_history` request.  All other endpoints should work exactly the same, grabbing the latest version of the parameter.

Add ssm `get_parameter_history` support

---

moto/secretsmanager/exceptions.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_secretsmanager/test_server.py

Sometime since I made the PR to represent the smart-quotes in the error messages sent by AWS secretsmanager AWS appear to have changed them to regular old quotes. This PR matches that change in order to make moto representative of actual behaviour once again.

Match AWS's change from smart-quote to ASCII quote

---

moto/iam/models.py
tests/test_core/test_auth.py
tests/test_iam/test_iam.py

IAM create_policy should throw an exception if the policy exists: [link](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html#API_CreatePolicy_Errors)
Also updated two tests that broke because of this.

Added Exception for create_policy when policy exists

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #2562 
DynamoDB allows item attributes to gain a different type. All scenarios have been verified against AWS

 #2562 - DynamoDB - allow updates to be of a different type

---

IMPLEMENTATION_COVERAGE.md
moto/awslambda/models.py
moto/awslambda/responses.py
scripts/implementation_coverage.py

Two changes:
- Make sure implementation_coverage.py knows that the boto-service 'lambda' maps to folder 'awslambda'
- Move logic from responses.py to models.py, ensuring that implementation_coverage can find all implemented functions in models.py

Add/improve Lambda coverage - no functionality changes

---

IMPLEMENTATION_COVERAGE.md
moto/events/models.py
moto/events/responses.py
tests/test_events/test_events.py

I had to redo the whole permissions handling in events to support Event Buses. I left out the implementation of `NextToken` & `Limit` in `list_event_buses()`, because the PR is already big enough and it doesn't add up any meaningful functionality at the moment.
Adds support for custom event buses, but not for partner ones, because per default an AWS account doesn't have any partner event buses available for usage. Any advice or idea on how to support partner event buses? Add a new decorator `@mock_event_bus(partner="datadog")` or extend existing one `@mock_events(partner_event_bus="datadog")`?
Partially solves #2322

Add events event bus

---

moto/iam/models.py
tests/test_core/test_auth.py
tests/test_iam/test_iam.py

Adds a check when creating a role, to make sure a role with that name doesn't already exist.
Now matches AWS behaviour.
Edit: Added the same validation when creating an IAM policy

IAM - Validate duplicate role names

---

setup.py

Due to changes by boto/botocore@e87e7a7 the `python-dateutil` dependency was capped to version 2.8.0.
When issue boto/botocore#1872 is fixed the cap can be reverted to the old one.
Also fixes #2540 and fixes #2568

Cap python-dateutil to 2.8.0

---

moto/awslambda/models.py
tests/test_awslambda/test_lambda.py

It looks like lambci is pre-pending the lambda responses with an
escape character `\033`. This was breaking the unit tests.

Fixed the Lambda invocation due to lambci changes.

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Needed these for some testing that I was doing, so just tried to follow the patterns that were there for the similar access_key capabilities.
I didn't do any validation of keys, or conversion (PEM vs SSH encoded) for the get method as I'd probably have to pull in some crypto lib to do so, and wasn't sure what the preference would be there

Add the ssh_public_key methods that were missing from IAM

---

.travis.yml
moto/core/models.py
tests/test_awslambda/test_lambda.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_stepfunctions/test_stepfunctions.py

- Fixes #2575
- Also upgraded Travis CI to make use of Bionic instead of Xenial
- This may also address concerns raised in #1793

Fix for moto not unmocking

---

moto/core/responses.py

Updating the converting logic to handle URIs with `+`s.
https://github.com/boto/botocore/commit/129bf6969fe2e1e7fd6327e217af2096c265fbb0#diff-34c08e9aac3a60b91e3416db722dca7dR259

Fix for updated botocore IoT requestUris.

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

AWS defines this option as:
```
--family-prefix (string)
The full family name with which to filter the ListTaskDefinitions results.
Specifying a familyPrefix limits the listed task definitions to task definition revisions that belong to that family.
```
This option behaves differently than ecs:ListTaskDefinitionFamilies. Instead of doing a comparison like `startswith`, it does a full string comparison by matching the entire task definition family to the prefix. For example, let's say there exists a task definition with the family `super-cool-task-def`.
ListTaskDefinitionFamilies would look like this:
```
aws ecs list-task-definition-families --family-prefix super-cool
{
"families": [
"super-cool-task-def"
]
}
```
ListTaskDefinitions would look like this:
```
aws ecs list-task-definitions …
```

Add familyPrefix option to ecs:ListTaskDefinitions

---

moto/logs/models.py
tests/test_logs/test_logs.py

The order of log events and handling of `nextToken` was completely off. Now it is as close to the AWS behaviour as possible.
I'm happy to change any code part, if someone has some good ideas on how to make it easier or more readable.
Fixes #2587

Fix order and nextToken handling in logs.get_log_events

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

The ADD operation already existed to add items to top-level sets.
This PR adds the option to:
ADD an item to a nested set (which may or may not exist yet)
DELETE an item from a nested set

Dynamodb - DELETE/ADD item from/to nested sets

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

A query fails if it has a space between `begins_with` and `(`,
for example: ```begins_with (#1, :1)```
Fix #1996

Improve parsing DynamoDB begins_with expression

---

moto/ec2/models.py
tests/test_ec2/test_nat_gateway.py

Support describe_nat_gateway filters by using nat-gateway-id, vpc-id,
subnet-id and state filter parameters.
Resolves: #2603

Add describe_nat_gateway filters support

---

moto/batch/models.py

This is necessary when the Docker daemon on the host is configured to use a different log driver by default.

Batch: explicitly specify json-file log driver

---

moto/batch/models.py
tests/test_batch/test_batch.py

```
>aws batch register-job-definition  --job-definition-name test --type container --container-properties "$(cat batch_job_container_properties.json)"
```
```
{
"jobDefinitionName": "test",
"jobDefinitionArn": "arn:aws:batch:us-west-2:123456789012:job-definition/test:1",
"revision": 1
}
```
```
>aws batch describe-job-definitions --job-definition-name test
```
```
{
"jobDefinitions": [
{
"jobDefinitionName": "test",
"jobDefinitionArn": "arn:aws:batch:us-west-2:123456789012:job-definition/test:1",
"revision": 1,
"status": "ACTIVE",
"type": "container",
"parameters": {},
"containerProperties": {
...
}
}
]
}
```

Batch: job definitions default to ACTIVE

---

moto/batch/models.py
tests/test_batch/test_batch.py
tests/test_batch/test_cloudformation.py

It's not an IAM role (the API parameter name in Batch is a misnomer).
Validation by matching against known role ARNs will always fail.
Scan the known instance profile ARNs instead.
Relevant part of Batch docs:
> instanceRole (string) -- [REQUIRED]
> The Amazon ECS instance profile applied to Amazon EC2 instances in a compute environment. You can specify the short name or full Amazon Resource Name (ARN) of an instance profile. For example, `` ecsInstanceRole `` or ``arn:aws:iam::<aws_account_id> :instance-profile/ecsInstanceRole `` . For more information, see Amazon ECS Instance Role in the AWS Batch User Guide .

Batch: computeResources.instanceRole is an instance profile

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Had this issue when I was using localstack (which uses moto underneath) with terraform. 
Was causing continual redeploys due to not storing the MaxSessionDuration field and description not being optional.

Add MaxSessionDuration field to IAM Role, Remove Description field from response if empty

---

moto/ssm/models.py
moto/ssm/responses.py
moto/ssm/utils.py
tests/test_ssm/test_ssm_boto3.py

We were missing some new information returned by SSM.
A typical message now looks like:
```
{
"Parameter": {
"Name": "test",
"Type": "String",
"Value": "test",
"Version": 1,
"LastModifiedDate": 1575156149.591,
"ARN": "arn:aws:ssm:us-east-1:1234567890:parameter/test"
}
}
```

Add missing information in SSM parameters

---

moto/sns/models.py
tests/test_sns/test_subscriptions_boto3.py

Adds missing attributes to the subscription and I also updated the default EffectiveDeliveryPolicy.
I got one question regarding the code in [moto/sns/response.py](https://github.com/spulec/moto/blob/3d5d477/moto/sns/responses.py#L101). Most of the methods have the part `if self.request_json:` in it. Is it some kind of legacy code or what is it used for?
Fixes #2441

Add missing attributes to SNS subscription

---

moto/cloudformation/parsing.py
moto/compat.py
moto/datapipeline/utils.py

Importing ABC from collections module has been deprecated since Python 3.4 and removed in Python 3.9. I have made the import fix in compat.py to reuse it across other modules . Reference : https://github.com/python/cpython/pull/10596

Import ABC from collections.abc for Python 3.9 compatibility.

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

I think this was introduced in https://github.com/spulec/moto/pull/2605 (not a 100% sure thought).
I know this logic works properly in the v1.3.13 and it is busted in v1.3.14.
I have written a test to repo the issue, here is the relevant part of the call stack from the test failure.
```
File "/Users/asher/projects/moto/moto/dynamodb2/models.py", line 620, in add
self.items.append(StreamRecord(self.table, t, event_name, old, new, seq))
File "/Users/asher/projects/moto/moto/dynamodb2/models.py", line 589, in __init__
self.record["dynamodb"]["SizeBytes"] = len(json.dumps(self.record["dynamodb"]))
File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File …
```

Fix issue when working with dyanmodb stream and complex types.

---

moto/s3/responses.py
tests/test_s3/test_s3.py

This is a small change to avoid rendering "None" as the value for `Prefix` in S3 response templates.
Currently, we're sometimes receiving `<Prefix>None</Prefix>` in S3 responses, which leads to issues with paginated requests, e.g., when using `listNextBatchOfObjects(..)` from the Java SDK.
Cheers

Avoid rendering "None" as S3 Prefix value

---

moto/route53/responses.py
tests/test_route53/test_route53.py

We should return `IsTruncated: False`  on `list_resource_record_sets`.
I've tested this, and code relying on this flag works as expected with this PR.
Fixes #2660

Add IsTruncated to Route53.list_resource_record_sets

---

setup.py

Hi!
This line in `setup.py` prevents me from updating jsondiff to the latest release:
https://github.com/spulec/moto/blob/d596560971ae289f102b9aecb9939b3c49a56ac5/setup.py#L46
Dependency jsondiff was introduced with `==1.1.1` in 0de2e55b1379f3de040485cedbf5c6fdc5a61a2d without any documentation about why `==` rather than `>=` would be needed.  It was then bumped from 1.1.1 to 1.1.2 in 5ca68fbf06adecb0c0478f102a9cc7d331aa36c4, keeping the `==` untouched. So far no signs why 1.1.2 and only 1.1.2 would need to be used. Did I miss any?
It would be great if we could lift `==` to `>=` to play nice with other Python packages in the same virtualenv and allow users to use recent jsondiff. Tests seem to still pass after the change.  Does it take anything more to make this work, from your point of …

setup.py: Unlock use with jsondiff >1.1.2

---

moto/dynamodb2/comparisons.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #2626 
LT/GT expressions in FilterExpression should evaluate to false if one of the attributes is None, following the official behaviour
Fixes #2627 
Comparison for LT/GT treated numerical 0 as a None-value, and so would always evaluate to False if one of the attributes is 0

DynamoDB - Update Item doesnt handle LT/GT properly

---

scripts/scaffold.py

* updated the way some prompt_toolkit resources are imported
* changed regex to match double-quotes in `BACKENDS` of `backends.py`
most of the requirements for the scaffold script aren't in requirements.txt or anything, so I assumed there wasn't any venv typically used to run it.  Was able to generate scaffolding for rekognition to test.
thanks for the awesome mocking library, hope to contribute to coverage now that this works for me

fix: small fixes to get scripts/scaffold.py working

---

moto/awslambda/models.py
tests/test_awslambda/test_lambda.py

Return actual output of the Lambda instead of echoing the input.

awslambda: return actual result in sync invoke

---

moto/iam/responses.py
tests/test_iam/test_iam.py

This update adds conditional logic to support IAM access key operations that do not include the (optional) `UserName` parameter.
This change uses the existing `get_access_key_last_used` function to retrieve an IAM user name based on IAM access key.
Fixes #2666

Made UserName parameter optional for IAM access key functions

---

moto/awslambda/exceptions.py
moto/awslambda/models.py
moto/awslambda/policy.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py
tests/test_awslambda/test_policy.py

- adds support for multiple policy statements
- adds support for RevisionId parameter
- adds support for lambda/RemovePermission
- adds State parameter to lambda/GetFunctionConfiguration (always returns Active)
Most of these changes were required in order to more closely mimic the AWS API and resolve issues when using moto[server] with terraform.

Fixes awslambda policy management

---

moto/sqs/exceptions.py
moto/sqs/models.py
tests/test_sqs/test_sqs.py

The permission implementation in SQS was quite off, so I fixed it and it now can be directly set during `sqs.create_queue` . Furthermore I added some error handling with tests.

Fix sqs permission handling & add more error handling

---

moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py

#2690 . This PR adds `EnableIAMDatabaseAuthentication` parameter into rds's `create_db_instance`. Also a small patch to fix snapshot creation with this new option.
First contribution here, hope it helps :-).

RDS Feature: Add EnableIAMDatabaseAuthentication

---

setup.py

https://github.com/boto/botocore/pull/1910
https://github.com/boto/botocore/issues/1872
https://github.com/spulec/moto/pull/2570

Botocore no longer needs an older version of python-dateutil.

---

moto/ec2/models.py

When loading AMIS and INSTANCE_TYPES in moto.ec2.models a file handle is
potentially leaked when loading the JSON.  This results in a
ResourceWarning which is a bit of unnecessary noise.
Rather than pass a call to open() to json.load() this instead uses a
context-manager in a small private helper function.
This fixes https://github.com/spulec/moto/issues/2620

Remove ResourceWarnings when loading AMIS and INSTANCE_TYPES

---

moto/ses/models.py
tests/test_ses/test_ses_sns_boto3.py

When utilizing sns the `__type_of_message__` can receive either a list or a map.
map:
- https://github.com/spulec/moto/blob/master/moto/ses/responses.py#L58
- https://github.com/spulec/moto/blob/master/moto/ses/responses.py#L79
list:
- https://github.com/spulec/moto/blob/master/moto/ses/responses.py#L104

Handle map or list parameters in sns processing

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

The maximum number of queues that the ListQueues API can return is 1000:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ListQueues.html
I had a couple of tests on another project that were incorrectly passing becuase Moto wasn't mimicking the same behavior as the AWS API.

Limit SQS list_queues response to 1000 queues

---

moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py
tests/test_awslambda/test_lambda_cloudformation.py

This is so that lambda client get_function() method will raise the same exception that AWS does for a non-existent function.

Added 'x-amzn-ErrorType' in the return header for missing lambda function

---

moto/swf/models/workflow_execution.py
tests/test_swf/models/test_workflow_execution.py

[`describe_workflow_execution`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/swf.html#SWF.Client.describe_workflow_execution) includes extra fields "closeStatus" and "closeTimestamp" in its output if the workflow is closed.

Include closed execution extra info

---

moto/events/models.py
moto/events/responses.py
moto/utilities/tagging_service.py
tests/test_events/test_events.py
tests/test_utilities/test_tagging_service.py

The CloudWatch events service lacks tagging support. This causes Terraform to fail when executing against a running moto server.
This pull request updates the following:
- Adds `TaggingService` (a generic implementation of tagging for easing the adoption of tagging support across moto)
- Implements tagging for CloudWatch events using `TaggingService`
- removes duplicate `test_list_rules` in `test_events.py`

adds tagging support for cloudwatch events service

---

moto/s3/responses.py

If there is a port in the host for the request, then this if statement
is not tripped.

Allow ports in k8s service urls for s3 mock

---

moto/dynamodb2/models.py
tests/test_awslambda/test_lambda.py

Created DynamoDB items were already send to DynamoDB streams.
This PR also adds supports updates to be send through

DynamoDB - Send item to DDB Stream on update, not just on create

---

moto/swf/models/workflow_type.py
moto/swf/responses.py
tests/test_swf/responses/test_workflow_types.py

SWF workflow type now keeps track of the default task-priority and default AWS Lambda role, set at workflow registration.
This requires the test to use `boto3` and `mock_swf` (instead of the existing import of `boto` and `mock_swf_deprecated`), as `boto` doesn't support these parameters in workflow registration.
A future PR will be needed to support decision task priority.

Support default task-priority and Lambda-role in SWF workflow registration

---

moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr_boto3.py

Fixes #1427 
'Starts' the first step of a cluster, and sets the start time of that step.

EMR - Return start time of first step

---

moto/swf/models/decision_task.py
moto/swf/models/workflow_execution.py
tests/test_swf/models/test_decision_task.py
tests/test_swf/responses/test_decision_tasks.py

Have the workflow execution keep track of the previous started event ID, to correctly include in decision tasks so deciders only have to process new events.
Closes #2107

Keep track of previous started event ID in SWF executions

---

moto/swf/responses.py
tests/test_swf/responses/test_activity_tasks.py
tests/test_swf/responses/test_decision_tasks.py

To match the [SWF documentation](https://docs.aws.amazon.com/amazonswf/latest/apireference/API_PollForActivityTask.html), an empty task is one where the task-token is the empty string, rather than being a non-existent key

Return empty task-token on no-task

---

IMPLEMENTATION_COVERAGE.md
moto/swf/models/__init__.py
moto/swf/responses.py
tests/test_swf/responses/test_activity_types.py
tests/test_swf/responses/test_domains.py
tests/test_swf/responses/test_workflow_types.py

SWF API docs:
* [UndeprecateDomain](https://docs.aws.amazon.com/amazonswf/latest/apireference/API_UndeprecateDomain.html)
* [UndeprecateActivityType](https://docs.aws.amazon.com/amazonswf/latest/apireference/API_UndeprecateActivityType.html)
* [UndeprecateWorkflowType](https://docs.aws.amazon.com/amazonswf/latest/apireference/API_UndeprecateWorkflowType.html)
Note tests required `boto3` and `mock_swf` as `boto` doesn't support those endpoints

Add SWF domain and type undeprecation

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Hello,
I found a error on use **if_not_exists** combined with **list_append**.
I know in merge https://github.com/spulec/moto/pull/2740 they tried to correct it.
But now raise a new error, is `Validation Exception` because in this line 454.
If the function **_get_default** dont return the default value will crash on `expression_attribute_values[key]`
This error occurs because if the data in db has the key.
The **_get_default** will not return an key of `expression_attribute_values`. 
In this case the **_get_default** return an `DynamoType` with data value in the db.

fixing error when _get_default return value that already exists, on _get_appended_list

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

**Reference Issues/PRs**
N/A
**What does this implement/fix? Explain your changes.**
Currently, the `delete_parameter` function for the ssm client will respond with a `dict` containing a key of` InvalidParameter` which has a value of a list containing the parameter name that was requested to be deleted when a parameter with said name doesn't exist which doesn't match the behavior of `boto3`. 
With this merge request, `delete_parameter` not responds with a 400 error and ParameterNotFound exception is raised. 
**Any other comments?**
N/A

Changes behavior of delete_parameter when parameter doesn't exist

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py

This PR fixes issue #2646. I'm not sure if my approach is correct, however, I can confirm that this patch actually causes Terraform to succeed in creating the security group. For some reason,  Terraform was expecting the IPv6 range to be an empty array. I have not yet confirmed if this indeed how AWS behaves.

Security Groups - Create a second default egress rule for IPv6

---

moto/ecr/exceptions.py
tests/test_ecr/test_ecr_boto3.py

Change `RESTError` to `JsonRESTError` for `ImageNotFoundException`
When using `RESTError` boto3 falls back to a generic `ClientException` instead of `ImageNotFoundException`. 
I've updated the `test_describe_image_that_doesnt_exist` test to expect `ImageNotFoundException` instead.

Change RESTError to JsonRESTError for ImageNotFoundException

---

requirements-dev.txt
tests/test_core/test_auth.py

Fixes #2774 
Botocore versions between 1.15.8 and 1.15.12 (inclusive) have the bug in place, so 1.15.13 and up works fine

Add test case in case botocore breaks again

---

requirements-dev.txt
setup.py

https://github.com/spulec/moto/pull/2776 pinned the `mock` version, but unfortunately there are other packages that are more strict. Specifically, I cannot install moto + [azure-cli](https://github.com/Azure/azure-cli/blob/1174a3350fad3f308688fd37c9dacf12b7afa044/src/azure-cli/setup.py#L134).

support mock versions < 3.0.5

---

setup.py

This allows repos consuming moto to use the latest jinaj2 2.11.x patched version (currently 2.11.1) w/o breaking moto's python 2 support.
See https://github.com/spulec/moto/pull/2776

Loosen jinja2 requirement.

---

moto/cloudformation/parsing.py
moto/core/models.py
moto/core/utils.py
moto/dynamodb2/comparisons.py
moto/ecr/models.py
moto/s3/utils.py

I am seeing a lot of deperecation warnings when I use moto for my tests (running under pytest), so I figured I'll clean up some of them.

Fix some 'DeprecationWarning: invalid escape sequence' warnings and use str.format for string interpolation.

---

moto/ec2/utils.py
tests/test_ec2/test_tags.py

Fixes #718
Before, the filter_from_querystring method would use this dict:
```{'tag-key': key, 'tag-value': value}```
This way, only a single tag (the last one) could be returned. This explains the unpredictable results.
Fix: Store all tags in the query under their own name, prefix them with 'tag:' and filter appropriately
```{'tag:key': name}```

EC2 - Allow filtering by multiple tags

---

tests/test_s3/test_s3.py

Verifies #657 is fixed, by adding a test case that verifies the content type of an S3 object is no longer returned as 'text/html' by default

S3 - Verify content type is set/returned as appropriate

---

moto/cloudwatch/models.py
tests/test_cloudwatch/test_cloudwatch.py

Work done  by @syunwei and supercedes his PR at #1558
Changes the CW metrics model so it doesn't expect microseconds
Not sure why GitHub thinks the entire test file is new - there's only one new test, test_get_metric_statistics
Fixes #2743 #2614 #2581

Cloudwatch - Fix timestamp format

---

moto/iam/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Sets the IAM rolename if specified, otherwise randomly generates one
Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
Supercedes #1932 
Fixes #2746

Cloudformation - Set IAM role name

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
tests/test_cloudwatch/test_cloudwatch.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

this is to avoid errors with terraform when creating metric alarms 
relates to https://github.com/localstack/localstack/issues/2161
I saw that enable and disable of metric alarms is currently not implemented. I'm happy to implement it in a follow up Pull Request to first fix issues with Terraform and Localstack.
_Edit:_ Btw shouldn't https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#cloudwatch `describe-images` be marked as included?

set value for actions enabled on describe-alarms

---

moto/events/responses.py

AWSEvents.DescribeRule throws an error that references a rule named "test" rather than the specified rule name when a rule with the specified name does not exist. It has been fixed to reference the specified rule name.

Fix a misleading error message

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

This should fix #2798
The general idea was to play all the UpdateItem queries on a real DynamoDb and dump the value in the tests.
I then added a method that recursively checks for changes in the new item. It works but as stated in the issue I may miss some corner cases.
I don't do a lot of python so this may not be the cleanest code you've reviewed, i'll be glad to improve it following advices 😉

Fix UPDATED_NEW return values differences

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #2760 
Ensures that results are ordered properly if the keys are numeric

Dynamodb - Global index ordering

---

moto/stepfunctions/models.py
tests/test_stepfunctions/test_stepfunctions.py

Fixes #2846
Calling stop_execution on a stepfunction should set the status to `ABORTED` not `SUCCEEDED`.

fix: stepfunction stop_execution

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #2849
Changes made:
* Added additional check in `put_item` to make sure that passed item has range attribute key in it when table in which we are inserting has range key set.
* Changed the type of exception to `KeyError` to not break existing `ConditionalCheckFailedException` behavior.
* Added `ValidationException` in responses when `KeyError` is raised in `put_item`.
* Fixed existing `test_put_item_nonexisting_hash_key` test to check for error code and not just message.
* Added `test_put_empty_item` and `test_put_item_nonexisting_range_key` tests.

DynamoDB - fix put_item ValidationException

---

moto/s3/exceptions.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Cannot tag S3 buckets with reserved tag key space `aws:`

Raise errors on tagging buckets with aws:*

---

moto/s3/responses.py

I think most tools just look at the response headers for PutObject, but where the response body is consumed, I suspect that the top-level `<PutObjectResponse>` should not be duplicated.
Same issue for `<DeleteObjectResponse>` nearby, so I altered that too.

Fix duplicated elements in S3 put_object / delete_object response XML structure

---

moto/s3/responses.py

PutObject and DeleteObject are not expected to a response body, with any response metadata in HTTP headers only.
The presence of this XML payload seems to have [tripped-up at least one S3 client implementation](https://github.com/rusoto/rusoto/pull/1728).
Superseeds https://github.com/spulec/moto/pull/2866

PutObject and DeleteObject should produce no XML

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

`ecs.run_task` allows the caller to omit the `cluster` parameter, in which case `run_task` assumes the `default` cluster. This PR changes `mock_ecs` to also support this behavior instead of raising an exception on an implicit `None` value for `cluster`.
For reference: Boto 3 `ECS.Client.run_task` [API documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task)

Changed mock_ecs to support ecs.run_task calls with a default cluster

---

moto/ec2/responses/availability_zones_and_regions.py
tests/test_ec2/test_availability_zones_and_regions.py

Adding missing Param zoneId in the describe-availability-zone and added tests against the same

Adding missing Param zoneId in the ec2 describe-availability-zone

---

moto/dynamodb2/__init__.py
moto/dynamodb2/models/__init__.py
moto/dynamodb2/models/dynamo_type.py
moto/dynamodb2/models/utilities.py
moto/dynamodb2/responses.py

By having models.py as one big file it causes to
easily create circular dependencies. With the current
setup it is not possible to re-use DynamoType. This
refactor moves it out to its own file while trying to
keep the structure as much as it is.
Creating a separate pull request given that it is a refactor change without functional change.
At this time models contains a lot of code in one file due to which it is easy to get circular dependencies. For example; for adding Validation to the tree-based parsing https://github.com/spulec/moto/pull/2885#issuecomment-612452300 I want to re-use the DynamoType class but I would need to import it from models.py which is the component that would already be creating the parser.  This can be solved by splitting out model.py.
There are multiple options …

Allow reuse of DynamoType from models.py

---

moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

Fixes #2895 
The support in this patch is preliminary and may or may not be feature complete.
It provides the basic support for update_secret so that future work can build on it as needed.

Adds initial support for secretsmanager update_secret

---

moto/ec2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_ec2/test_instances.py
tests/test_ec2/test_subnets.py

Fixes #2877 
The bug appeared when describing subnets, specifically when trying to get the number available ip addresses: https://github.com/spulec/moto/blob/master/moto/ec2/models.py#L2998
This line assumed that an ENI would always have a subnet attached
The actual bug: an ENI only had a subnet attached if a subnet ID was supplied by the user
Fix: If not user-supplied, find the default subnet for that availability zone and attach it to the ENI (which is the AWS behaviour)

EC2 - Ensure NCI always has a Subnet

---

moto/ec2/urls.py
moto/ssm/models.py

I am seeing `DeprecationWarning: invalid escape sequence` when those lines get hit.
this should fix it.

Fix deprecation warnings.

---

moto/elb/models.py
moto/elb/responses.py

Similar issue to https://github.com/spulec/moto/issues/2665 - JodaTime as used in the Java AWS SDK throws an exception when receiving `DescribeLoadBalancers` results.
See https://github.com/rwhogg/aws-elb-test for a program that demonstrates the problem.
Based on a quick look at the code, I strongly suspect this issue affects ELB v2 as well, but I've only fixed it for v1 at the moment.

Use ISO 8601 format for ELB DescribeLoadBalancers

---

IMPLEMENTATION_COVERAGE.md

Seems like it's implemented but not marked

Mark sts > get_caller_identity() as implemented

---

IMPLEMENTATION_COVERAGE.md
moto/glue/models.py
moto/glue/responses.py
tests/test_glue/test_datacatalog.py

- Add get_databases method to glue moto client
- Update IMPLEMENTATION_COVERAGE.md with methods that were implemented previously
It only adds the simplified functionality. As in the rest of the glue methods, this method assumes no optional parameters are provided (CatalogId, NextToken, MaxResults)
Test can be checked with:
`nosetests --tests tests/test_glue/test_datacatalog.py`

Add get_databases method to glue and update IMPLEMENTATION_COVERAGE.md

---

moto/core/models.py
moto/s3/responses.py

The "request" object in CallbackResponse is the PreparedRequest send by
whatever client is used to contact the mocked moto service. This can end
up with unparsed bodies, as we added for processing presigned post
requests in #2155. This will make sure that all of the requests comming
in from mocked functions also get processed by werkzeug as if it was
running a live server.

Make all CallbackResponse requests into a Werkzeug Request

---

moto/ec2/models.py

The new version of botcore adds this region: https://github.com/boto/botocore/commit/f7dc4730ad34c6c3322da7d43ba64452bb3ae0d8#diff-9dfab05d4ba739e097a193e8b5fa61caR13
Which in turn, breaks moto:
```
/moto-1.3.15.dev640-py2.py3-none-any.whl/moto/__init__.py:3: in <module>
from .acm import mock_acm  # noqa
/moto-1.3.15.dev640-py2.py3-none-any.whl/moto/acm/__init__.py:2: in <module>
from .models import acm_backends
/moto-1.3.15.dev640-py2.py3-none-any.whl/moto/acm/models.py:7: in <module>
from moto.ec2 import ec2_backends
/moto-1.3.15.dev640-py2.py3-none-any.whl/moto/ec2/__init__.py:2: in <module>
from .models import ec2_backends
/moto-1.3.15.dev640-py2.py3-none-any.whl/moto/ec2/models.py:5169: in <module>
ec2_backends = {
/moto-1.3.15.dev640-py2.py3-none-any.whl/moto/ec2/models.py:5170: in …
```

Add new AWS Region: af-south-1

---

moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

We needed to be able to unit test lambda code that checks the existence of policy, added policy to ApiGateway model and response.
Fixes #2721

Add policy to API Gateway 

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
moto/s3/models.py
moto/s3/utils.py
tests/test_cloudwatch/test_cloudwatch.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Fixes #2711 
Adds a framework for services to register AWS OOTB metrics in CloudWatch.
Currently only implemented for S3, which registers ```BucketSizeBytes``` and ```NumberOfObjects``` per bucket.
Can be fairly easily extended for EC2 for instance, if we want to return e.g. ```CPUUtilization```
Also adds the missing feature of being able to filter metrics by dimension - before you could only filter by name or namespace.

Cloudwatch  - Add default metrics for other services

---

moto/ec2/models.py
tests/test_ec2/test_instances.py

Fixes #2699 
The bug described the behaviour that the device size was not stored, but block devices were not persisted at all using CloudFormation.
A default volume with size 8 was always created, which was what the user was seeing - in reality, this default volume should only be created if no volumes have been specified.

EC2 - Add option to add volumes using CloudFormation

---

moto/awslambda/models.py
moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py

Fixes #883
All missing features that were mentioned in the ticket (add_permission, remove_permission, update_function_code, update_function_configuration) have already been implemented.
The methods have been renamed so that it's picked up the by implementation coverage script.
The remove_permission-functionality didn't have a test yet, so I added one

Lambda - Add test to verify remove_permission functionality

---

moto/__init__.py
moto/core/utils.py
moto/eb/__init__.py
moto/eb/exceptions.py
moto/eb/models.py
moto/eb/responses.py
moto/eb/urls.py
moto/ec2/responses/tags.py
moto/ec2/utils.py
tests/test_eb/test_eb.py

Related to issue #2405 
This PR (currently) adds failing tests for Elastic Beanstalk `create_application()`
Update: tests no longer fail because I've added a try to implement an absolute minimal mock for `create_application()` and `describe_application()`

Add mock for ElasticBeanstalk

---

moto/cloudformation/models.py
moto/cloudformation/parsing.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Fixes #2388 
Before, creating a ChangeSet would automatically create the underlying resources
Now, creating a changeset allows you to review the changes first.
Only after calling ```execute_change_set``` are the resources created
Relevant docs: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-change-set.html

CloudFormation - CreateChangeSet should not create resources

---

moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

Fixes #2810 
Go expects a a boolean attribute, but moto returned None if ```ebs_optimized``` was not specified

EC2 - Explicitly set ebs_optimized to false if not specified

---

moto/s3/responses.py
moto/s3/urls.py
tests/test_s3/test_s3.py

Fixes #2759 
S3 allows objects keys to start with slashes (`/`); all leading slashes were previously incorrectly removed from key in `parse_key_name` instead of only removing the first one.
`moto.s3.urls` was also updated to clearly include the leading slash in the `key_name` group.

S3 - Allow keys to start with leading slashes

---

moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

This PR addresses two issues I've originally created in localstack project:
https://github.com/localstack/localstack/issues/2347
https://github.com/localstack/localstack/issues/2348
In short: it adds support for secret description, and fixes an issue, where tags would be cleared upon updating secret value.
Please note, that I'm not a python developer, so perhaps some changes could be introduced, however I've tested those changes locally and they seem to fix mentioned issues.

Do not remove tags after secret update, handle description

---

MANIFEST.in
setup.py

Do not place reserved_keywords.txt in the root
as this can give environment errors.
This was raised in: https://github.com/spulec/moto/pull/2885#discussion_r415150276
From testing in virtual_env it avoids placing the one in the root and there will only be one in the parsing module directory.
@kislyuk could you verify whether this works for your setup as well?

Place reserved_keywords.txt not in root.

---

moto/server.py
moto/sts/models.py
moto/sts/responses.py
tests/test_sts/test_sts.py

My company uses SAML to get access to our accounts on AWS. So we wrote a module that would use the STS call assume_role_with_saml to retrieve certificates. I went to test this new module we wrote using moto and found out that the endpoint for this had not been done yet. This is my take on adding this endpoint.
I used the responses I received to create the templates for the SAML assertion and the response from the endpoint. The SAML assertion is large and I am open to getting it into the test in some other way, but the test follows the pattern of the STS calls. All of the digests and hashes are faked, please let me know if higher fidelity of hashes are need.
Thanks for making a super useful Python module. I hope this helps make it better!

Add the STS call assume_role_with_saml

---

moto/dynamodb2/exceptions.py
moto/dynamodb2/models/__init__.py
moto/dynamodb2/models/dynamo_type.py
moto/dynamodb2/parsing/executors.py
moto/dynamodb2/parsing/validators.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodb2/test_dynamodb_executor.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Part of structured approach for UpdateExpressions:
1) Expression gets parsed into a tokenlist (tokenized)
2) Tokenlist get transformed to expression tree (AST)
3) The AST gets validated (full semantic correctness)
4) AST gets processed to perform the update -> this commit
This commit uses the AST to execute the UpdateExpression.
All the existing tests pass. The only tests that have been
updated are in test_dynamodb_table_with_range_key.py because
they wrongly allow adding a set to a path that doesn't exist.
This has been alligend to correspond to the behavior of AWS
DynamoDB.
This commit will resolve https://github.com/spulec/moto/issues/2806
Multiple tests have been implemented that verify this.
This would have conflicts with https://github.com/spulec/moto/pull/2896 but this solution …

Improve DDB expressions support4: Execution using AST

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py
tests/test_apigateway/test_server.py

On master get_usage_plan_key and  get_usage_plan does not honor the behavior of API gateway, it hangs and fails with an unexpected error.
Hangs if invoked with a not existing usagePlanId, now returns NotFound and 404 status code
In the follwing use cases it raise an unexpected error due to a non existing item
| Api key exists | Api Key Subscribed | Usage Plan exists | Raised Exception | Status Code |
|:--------:|:----:|:-------:|-------------------|:--------------:|
|  :x: | |  :white_check_mark:  | ApiKeyNotFoundException | 404 |
|  :x: | | :x:  | ApiKeyNotFoundException | 404 |
|  :white_check_mark:  | :x: | :white_check_mark:  | UsagePlanNotFoundException | 404 |
|  :white_check_mark:  | |:x:  | UsagePlanNotFoundException | 404 |

Api gateway api get_usage_plan and get_usage_plan_key revised to handle missing values

---

moto/ec2/models.py
moto/ec2/responses/availability_zones_and_regions.py
tests/test_ec2/test_availability_zones_and_regions.py

The `describe_regions` call now includes an `OptInStatus` key in the return.
Examples:
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_regions
- https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html
Added this capability given these constraints:
- Regions can have a status of `opt-in-not-required`, `not-opted-in`, or `opted-in`
- Regions introduced by AWS after 3/20/19 must be enabled (ie, status of `not-opted-in`, or `opted-in`)
- Source: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html (under "Available Regions" section)
- Far as I know, this should be `me-south-1` and `ap-east-1`
- Regions before 3/20/19 should have status of `opt-in-not-required`
I am not exactly …

Support OptInStatus for EC2 describe_region calls

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Fixes #2937 
The [official API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) expects this request when deleting objects:
```POST /?delete HTTP/1.1```
However, GOlang apparently automatically encodes this to:
```POST /?delete= HTTP/1.1```
This change allows requests in both formats.
Further info:
Both styles are acceptable according to the RFC spec
Some spicy discussions on why GOlang does this:
https://github.com/golang/go/issues/20820
(The test change is unrelated, but it's nice to have a single source of truth for this setting, especially when testing stuff like this locally)

Fix S3:DeleteObjects in GoLang

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Amazon SQS updated MaximumMessageSize from 64K to 256K back in 2013:
https://aws.amazon.com/about-aws/whats-new/2013/06/18/amazon-sqs-announces-256KB-large-payloads/
Tested with Python 2.7 and 3.7. I updated the one test that failed (as expected, since it tested the value I changed). I also see 4 `test_cloudformation.test_cloudformation_stack_crud_boto3` tests with errors, but the errors also happened before I made any changes:
* `test_create_change_set_from_s3_url`
* `test_create_stack_from_s3_url`
* `test_create_stack_set_from_s3_url`
* `test_update_stack_from_s3_url`

update SQS MaximumMessageSize from 64K to 256K

---

moto/apigateway/models.py
tests/test_apigateway/test_apigateway.py

Fix response_parameter being ignored in put_integration_response

---

moto/opsworks/models.py
tests/test_opsworks/test_instances.py

When an instance is running, OpsWorks reports its status as "online" [1], while EC2 reports it as "running". Until now, moto copied the EC2 instance's status as is. This commit introduces the converts the running status to online when returned by OpsWorks.
[1]: https://docs.aws.amazon.com/cli/latest/reference/opsworks/describe-instances.html

Fix the online status in OpsWorks

---

moto/dynamodb2/parsing/executors.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

When using the ADD syntax to sum up different components
the path that is provided is allowed to be non-existent.
In such a case DynamoDB will initialize it depending on
the type of the value.
If it is a number it will be initialized with 0.
If it is a set it will be initialized with an empty set.
From the docs "If the attribute already exists, the behavior of ADD depends on the attribute's data type" but they don't specify the behavior if it doesn't exist but from testing against real DDB it does create the elements.
I apologize for the inconvenience caused by this bug. We actually had tests covering this aspect it seems but when I was implementing the functionality I tried those against real DDB but they seemed broken and I got path validation errors but it seems that somehow I messed …

[Bugfix] UpdateExpression using ADD from zero

---

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

This PR adds a parser for BlockDeviceMappings argument that passed to `ec2_client.run_instances`
Fixes: https://github.com/spulec/moto/issues/418

Add support for BlockDeviceMappings argument

---

moto/awslambda/models.py
moto/logs/exceptions.py
moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py

Adds also log event transmission to specified destinations. At the moment only AWS Lambda is implemented. I had to move the `lambda_backends` import to the function level, because circular dependency issues.
I hope I correctly connected CloudWatch Logs with Lambda, if not please some feedback on which parts should be changed/fixed.
Fixes #2955

Add CloudWatch logs subscription filters

---

moto/awslambda/models.py
moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py

Fixes #2886 
Before: LogResult was always returned, and contained the Lambda response
Now: LogResult is only returned when LogType=Tail, and contains the actual logs

Lambda - Return LogResult only if requested

---

moto/dynamodb2/exceptions.py
moto/dynamodb2/models/__init__.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #2985 
DynamoDB#transact_write_items now returns a list of encountered errors (if any), instead of a single generic exception

#2985 - DynamoDB - TransactWriteItems - Fix error-type returned

---

moto/core/responses.py
tests/test_cloudformation/test_validate.py

CC https://github.com/spulec/moto/issues/3008
With the `ClientToken` being add to the RunInstances request, the order of the data parameters was getting scrambled on Py2 because of lack of dictionary stability. This resulted in the signing in Moto not being consistent with the signing in botocore.
By using an OrderedDict, we ensure the parameter ordering is consistent.

Keep order in request body to ensure auth signing works.

---

moto/resourcegroupstaggingapi/models.py
tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py

Also fixed resource identifier for elb (was `elasticloadbalancer`, changed to `elasticloadbalancing` as per [user guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancingv2.html). Resolves #3011

Add tag get_resources support for target groups

---

moto/ec2/exceptions.py
moto/ec2/models.py
tests/test_ec2/test_instances.py

This PR fixes https://github.com/spulec/moto/issues/1922
Includes:
- Detach volumes upon instance termination and delete volumes with `deleteOnTermination=True` property
- Update Instance device mapping upon volume detachment
- Bugfix: In case of adding a device that mapped to `/dev/sda1` and detaching him before instance termination, an error was thrown.

Add support for detaching volumes upon instance termination

---

moto/stepfunctions/responses.py
tests/test_stepfunctions/test_stepfunctions.py

This fixes #3005 .
I also fixed a duplicate test name, but I don't think that has any affect on anything.

SFN - fix InvalidARN exception on start_execution

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Fixes #2433 
Fixes #3006 
Changes the behaviour for message groups. A single call to `receive_messages` will receive all messages in the same group, but a subsequent call will now skip messages in that group if they haven't processed yet.
Before, the first request would only receive a single message per group.

SQS: fix message group behaviour

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Fix #3032 :
- Status of change set should be 'CREATE_COMPLETE'
- Execution status of change set should be 'AVAILABLE'
- Creation time of change set should be set to the datetime.utcnow()
- Stack Id of change set should contain the same region in its name as the change set itself

Cfn change set fix outputs

---

moto/events/responses.py
tests/test_events/test_events.py

Hi,
In the AWS documentation, events put-targets action should return something like this:
```
[
'FailedEntries' => [
[
'ErrorCode' => '<string>',
'ErrorMessage' => '<string>',
'TargetId' => '<string>',
],
// ...
],
'FailedEntryCount' => <integer>,
]
```
https://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html#output
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-events-2015-10-07.html#puttargets

Fix incorrect response for put-targets action

---

moto/cloudformation/models.py
moto/cloudformation/parsing.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Hi,
This PR fixes issue #3038 by adding the changes property when describing a change set.
Example:
```
{
"Changes": [
{
"Type": "Resource",
"ResourceChange": {
"Action": "Add",
"LogicalResourceId": "BucketResource",
"ResourceType": "AWS::S3::Bucket",
"Scope": [],
"Details": []
}
}
],
...
}
```
When creating a change set, ``stack_template`` variable has to be initialized withan empty dict instead of ``template`` variable because the stack is not created at this time. If we don't do that, the call to ``diff`` function gives nothing (e.g. no change) because it compares the stack_template to itself.

Add missing changes when creating a change set

---

moto/core/models.py
tests/test_s3/test_s3.py

Resolves a bug where streaming uploads made via requests to a presigned s3 url were failing because their request bodies are file-like objects.
See https://2.python-requests.org/en/master/user/advanced/#streaming-uploads for details of this feature in `requests`.

Fix: Support streaming upload from requests.

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

#3046 - DynamoDB - Add Key-size Validation for BatchGetItem

---

moto/dynamodb2/models/__init__.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

ATM it's not possible to create a DynamoDB stream via CloudFormation.
This PR fixes that.

CloudFormation - Support DynamoDB Streams

---

moto/s3/models.py

Fix for the TZ in `CreationDate` of s3 buckets, fixes #2665 (similar to the fix for #2904 )
`bucket.creation_date.isoformat()` doesn't include timezone info if it's utc. The AWS Java SDK fails on this missing field:
```
com.amazonaws.util.DateUtils.parseISO8601Date("2020-06-02T08:43:57.470630")
// java.lang.IllegalArgumentException: Invalid format: "2020-06-02T08:43:57.470630" is too short
```

Make sure the UTC tz is included in the bucket creation timestamp

---

moto/dynamodb2/models/__init__.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Fixes #3066 
Terraform is high-maintenance when it comes to the expected response. Our DDB wasnt returning the `ProvisionedThroughput`-field as part of the GSI, but those fields are required for TF, even if the RCU/WCU are 0.
Solution now uses models for all indexes, instead of a dict, to avoid having to reference hardcoded dictionary-keys all over the place

DynamoDB - Add default GSI throughput

---

moto/iam/responses.py
tests/test_iam/test_iam.py

GetAccountAuthorizationDetails returns an invalid response in group inline policies.
`PolicyDocument` should be an IAM policy document JSON, however the current implementation returns a Python dict expression.
Similar implementation can be found just below the code, in role inline policies, which seems correct.
https://github.com/spulec/moto/blob/cb600377b48ca676fc6a29a6690aeb51e702da43/moto/iam/responses.py#L2123
This PR fixes group inline policy rendering just like role inline policy.
The small code below is a PoC with a group and a policy.
Backend data are correct: you can see a normal JSON.
```python
#!/usr/bin/env python
from moto import mock_iam
from moto.iam.models import iam_backend
import boto3
@mock_iam
def t():
policy_document = """
{
"Version": "2012-10-17",
"Statement":
{ …
```

Correct group inline policy rendering

---

moto/cloudformation/models.py
tests/test_cloudformation/test_stack_parsing.py

Valid json can have `\t` characters, this currently throws a yaml scanner error so json.loads never gets called instead.
Also the loader arg in json.loads is invalid.
Can add tests if needed to exemplify this.

fix to use json for yaml scanner error

---

CONTRIBUTING.md
moto/s3/responses.py
tests/test_s3/test_s3.py

1. See problem described in #2210.
2. One of the other S3 tests (`test_streaming_upload_from_file_to_presigned_url`) is failing on my machine due to the lack of a region. See #3080 for more information.
3. Some of the contributor documentation is a little sparse for newbies.
This PR:
* updates the contributor documentation
* fixes the failing S3 test by providing a region
* adds a test for empty `CreateBucketConfiguration`
* returns the correct exception when presented with an empty `CreateBucketConfiguration`
* 🙏  This is my first PR against this codebase, please be gentle!
* ℹ️   I'm using this as practice because I want to implement Application Autoscaling (#1931).
* ❓ I'm not sure why `test_streaming_upload_from_file_to_presigned_url` is failing, it was passing yesterday.
Fixes #2210, …

Return correct error when creating a bucket with empty CreateBucketConfiguration

---

moto/elbv2/responses.py
tests/test_elbv2/test_elbv2.py

Fixes https://github.com/spulec/moto/issues/3090, I wasn't able to get tests running locally, but I verified it fixes the repro script from the linked issue. The problem is that the values returned from `_condition.items()` are `('field', 'path-pattern'), ('path_pattern_config._values.member.1', '/test_repo/test_branch/*')`, so the key doesn't actually start with `"values.member"`

Fix condition filtering bug in elbv2.create_rule()

---

moto/core/models.py
moto/core/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Fixes #3098 
Stores the region in the UserAgent-header in the following format:  
`User-Agent: Boto3/1.14.12 Python/2.7.15+ Linux/4.15.0-106-generic Botocore/1.17.12 region/us-west-2`
~~Marked as draft, as I haven't accounted for the fact that the user might have provided their own extra user-agent information - just verifying the POC for now~~
Edit: Changed the PR to extend the UserAgent-header, in case the user has supplied their own Config object with a UserAgentExtra-option. Ready for review now

Transfer Region in UserAgent-header

---

moto/cognitoidp/models.py
moto/cognitoidp/urls.py
tests/test_cognitoidp/test_cognitoidp.py

Fixes #3078 
Also fixes an invalid regex when requesting the public key, so now `https://cognito-idp.{}.amazonaws.com/{}/.well-known/jwks.json` is properly mocked

CognitoIDP: Return kid header as part of respond_to_auth_challenge

---

moto/dynamodb2/models/__init__.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #3055 
GSI's/LSI's can be configured to only store a subset of the data, to save space/money, by specifying a ProjectionType.
This PR adds support for the projection type KEYS_ONLY.
The ProjectionType 'ALL' is supported by default.
The ProjectionType 'INCLUDE' is not yet supported, but can be easily added later on.

Feature: DynamoDB: Support projectiontype KEYS_ONLY for GSI/LSI

---

moto/ssm/models.py

Passes in the region to SSMBackend, instead of cycling through the dict of known backends.
This aligns with how all other backends handle the region.
Fixes https://github.com/localstack/localstack/issues/2618

SSM: Use EC2 region

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_validate.py

This change fixes:
* Replace call to non-existent exception yaml.ParserError
* Catches yaml scanner error for valid json with tabs
* Supply yaml loader to ensure yaml loading throws exception validly for json with tabs and doesn't try to load the json incorrectly

Cloudformation: Fix - validate template yml fixes

---

moto/cloudformation/parsing.py
tests/test_cloudformation/test_stack_parsing.py

Resolves #3109.
Thanks @bblommers for the suggestion on where to start. This PR adds "NUMBER" and "LIST<NUMBER>" type parsing to `cloudformation/parsing.py`. Since CloudFormation "NUMBER" parameters can be either ints or floats, this PR uses a function that first tries to convert to int and then falls back to float if that doesn't work. I added tests to cover the additions and I think the new tests also cover the pre-existing "LIST*" if statement.

Add NUMBER and LIST<NUMBER> parsing to cloudformation/parsing.py

---

moto/iam/responses.py
tests/test_iam/test_iam.py

When calling actual (boto3 or via aws cli) `iam.get_account_password_policy()`, AWS always returns a value for `HardExpiry` whether its value is `true` or `false`.  This can be replicated via the aws cli or boto3. 
Sample output:
```
{
"PasswordPolicy": {
"MinimumPasswordLength": 12,
"RequireSymbols": false,
"RequireNumbers": true,
"RequireUppercaseCharacters": true,
"RequireLowercaseCharacters": true,
"AllowUsersToChangePassword": true,
"ExpirePasswords": true,
"MaxPasswordAge": 90,
"PasswordReusePrevention": 3,
"HardExpiry": false
}
}
```
When using moto, `HardExpiry` is only returned if it happens to be `true`.
Sample moto output:
```
{
"PasswordPolicy": {
"MinimumPasswordLength": 12,
"RequireSymbols": false,
"RequireNumbers": true,
"RequireUppercaseCharacters": true, …
```

Always return 'HardExpiry' for account password policy.

---

moto/config/exceptions.py
moto/config/models.py
moto/config/responses.py
tests/test_config/test_config.py

I added all endpoints with some sanity checks, but there are still parts missing. The code doesn't pull the conformance pack from S3 and all the Config Rules inside that template would result in a creation of those Config Rules in all accounts. Due to the lack of an implementation of Config Rules at the moment, this should/could be done an other time.

Config - implement Organization Conformance Pack functionality

---

moto/dynamodb2/models/__init__.py
tests/test_dynamodb2/test_dynamodb.py

It appears there's a bug in the implementation of #3097. When a dynamo index is marked `KEYS_ONLY` it includes not just the index hash & range key, but also the table hash & range key (if the range key exists).
The two tests added in #3097 both did not quite pass when ran directly against dynamo. This PR
- fixes those two tests so they pass when ran against dynamo
- adjusts the implementation of `LocalSecondaryIndex` and `GlobalSecondaryIndex` so that table keys can be included when the index is `KEYS_ONLY`
Note I can see a few different ways this could have been implemented - I chose the one that looked like the simplest from what I can see, but if you'd like a different implementation let me know I can make adjustments.
Cheers & as always thanks a ton for this project. Super helpful.

Fix dynamodb2 KEYS_ONLY Indexes

---

moto/apigateway/models.py
tests/test_apigateway/test_apigateway.py

This pull request will fix #3129.
Fix invalid default value
- `enabled` should be return False
- `stageKeys` should be return empty list

fix #3129 API Gateway create_api_key generate wrong default value

---

moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

create_api_key should return 201.
https://docs.aws.amazon.com/apigateway/api-reference/link-relation/apikey-create/

fix API Gateway:create_api_key return wrong status code

---

moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

create_usage_plan_key should return 201.
https://docs.aws.amazon.com/apigateway/api-reference/link-relation/usageplankey-create/

fix API Gateway:create_usage_plan_key return wrong status code

---

moto/events/models.py
moto/events/responses.py
tests/test_events/test_events.py

Hi All,
Thanks for the library. I wanted to use it to test an application I'm working on that is using the PutEvents API and noticed that there is a discrepancy for the events service between what Amazon says it returns and what moto returns. This change fixes that issue.
* [AWS API Documentation for Put Events](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html)
The current response looks like this:
```
{
"ResponseMetadata": {
"HTTPStatusCode": 200,
"HTTPHeaders": {"server": "amazon.com"}, 
"RetryAttempts": 0
}
}
```
This merge request changes to match the API documentation:
```
{
"FailedEntryCount": 0,
"Entries": [
{"EventId": "uuid"}
]
}
```
Thanks again and let me know if you have any questions, comments or concerns!

Fix: Put Events API

---

moto/ec2/models.py
tests/test_ec2/test_virtual_private_gateways.py

Per #3154, adds `attachment.vpc-id`, `attachment.state`, `vpn-gateway-id`, and `type` filters. `amazon-side-asn` and `availability-zone` still remain unimplemented - the current implementation of VpnGateway does not appear to use them at all, and I was looking to implement what I could to allow terraform to run against moto.

Adding VPN Gateway filters

---

moto/cognitoidp/models.py
moto/cognitoidp/utils.py
tests/test_cognitoidp/test_cognitoidp.py

cognito-idp `ClientId` created by `create_user_pool_client` is too long (Because it's using `uuid.uuid4()`)
According to boto3 `ClientId` should be 26 characters

fix cognito-idp UserPool ClientId

---

moto/s3/models.py

Currently when generating an S3 multi-part upload ID, occasionally an upload ID will contain a `/` character. This is not consistent with how the actual API creates IDs (it does contain special characters `.` and `-` characters, but not `/`).
This small PR simply filters out `/` characters when generating S3 multi-part upload IDs in a similar way as how the code was already filtering out `=` and `+` characters.

When generating multi-part upload IDs remove `/` characters

---

moto/core/utils.py
moto/s3/models.py

As per amazon s3's documentation, they are not storing time with milliseconds precision.
While in moto it was storing it in milliseconds. Which was causing s3 sync command with --exact-timestamp to download the files everytime when syncing data from s3 to local.
This fix solved the bug.

Bugfix: S3 time precision issue fixed

---

moto/s3/responses.py
moto/s3/utils.py
tests/test_s3/test_s3.py

Fixes #2104 
Also adds validation for error scenarios: metadata set when creating the URL should also be send through when PUTing the URL
I ran the tests as they are against AWS for validation.

S3 - Persist metadata for Presigned URL

---

moto/dynamodb2/models/__init__.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Fixes #3114 
Used to throw an error because, without the `physical_resource_id`-attribute, the object-representation would be used instead of the name (`<OutputValue><moto.dynamodb2.models.Table object at 0x7f5ce7c3b240></OutputValue>`)

CFN - Allow DynamoDB table as an Output

---

moto/ssm/models.py
tests/test_ssm/test_ssm_boto3.py

This PR adds the Contains functionality (Issue #3159). Tests were created to mimic behavior in AWS/boto3, including that filters with values in the form of `/string` will match parameters named `string...` but not parameters named `...string...`. In the test example, a Contains filter with the value `/tan` would match both `/tangent-3` and `tangram-4` but not `standby-5`.
This PR also enforces the parameter filter restrictions on `get_parameters_by_path`. According to the boto3 documentation [1], `Name`, `Path`, and `Tier` are not allowed values for `Key` in a parameter filter for `get_parameters_by_path`. This PR enforces this by calling `_validate_parameter_filters` from the `get_parameters_by_path` method, and adding a check to `_validate_parameter_filters`. I added 3 test cases to …

Implement Filter: Contains functionality for describe_params

---

moto/ssm/exceptions.py
moto/ssm/models.py
tests/test_ssm/test_ssm_boto3.py

Parameters are not allowed to start with `ssm` or `aws`. This PR adds error messages which
correspond exactly to the error messages returned by boto3.

Enforce parameter naming

---

moto/core/utils.py
moto/sqs/models.py
tests/test_sqs/test_sqs.py

Moving this PR here - raised originally by @hudovisk [here](https://github.com/localstack/moto/pull/8), but I believe this change should better be merged upstream. Thanks!
---
The method `create_from_cloudformation_json` of the Sqs resource does not handle the difference of format of the Tags field in the resource template and the format expected in Sqs resource class.
In cfn resource template Tags is specified as a list of dicts. But the Sqs resource expects that the tags field be a single dict.
This behaviour causes a crash when a queue is created with tags from `create_from_cloudformation_json` and later the list_queue_tags is called because it tries to call `items` from `queue.tags` but tags is actually a list of dicts.

Fix SQS tag list from CloudFormation resource creation

---

moto/ec2/responses/instances.py
tests/test_ec2/test_instance_types.py

The [`ec2.describe_instance_types`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_instance_types) endpoint is already implemented in moto but it is using an incorrect XML schema. This means that the current output is:
```python
{'InstanceTypes': [{}],
'ResponseMetadata': {'HTTPHeaders': {'server': 'amazon.com'},
'HTTPStatusCode': 200,
'RequestId': 'f8b86168-d034-4e65-b48d-3b84c78e64af',
'RetryAttempts': 0}}
```
This PR changes the schema (and adds a test to check the output) such that the output is now:
```python
{'InstanceTypes': [{'InstanceStorageInfo': {'TotalSizeInGB': 0},
'InstanceType': 't1.micro',
'MemoryInfo': {'SizeInMiB': 644874240},
'ProcessorInfo': {'SupportedArchitectures': ['x86_64']},
'VCpuInfo': {'DefaultCores': 1, …
```

Fix XML schema for ec2.describe_instance_types

---

moto/dynamodb2/parsing/tokens.py
tests/test_dynamodb2/test_dynamodb_expression_tokenizer.py

When using pynamodb's support for transactions it makes use of of `ExpressionAttributeNames` that look like `#0` `#1` etc. According to the [ExpressionAttributeName documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html) and when testing against dynamodb-local these names work. However, when testing with moto they fail.
This PR modifies the regex for an expression attribute to allow for names that start with a number. This fix allows for tests in my codebase to pass.
As an aside - when reading the documentation it specifies that `ExpressionAttributeNames` must be alphanumeric, however, looking at the regex and moto tests `_` appears to be used. Possibly I'm slightly confused or this regex is used in multiple places??

Fix DynamoDb2 ExpressionAttributeNames can start with a number
