getmoto/moto

moto/ec2/models.py
moto/ec2/responses/amis.py
tests/test_ec2/test_amis.py

ModifyImageAttribute: Added support for user permissions.

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Adding iam credentials report

---

moto/rds2/models.py

fix: put db name in quotes, if present. - Chris Henry

Adding rds2 support

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py

I think that https://github.com/spulec/moto/pull/316 would be a great addition to this PR

Add support to tag filtering to Security Groups

---

setup.py

boto 2.2.20 introduces kinesis.  alternatively, this requirement could be
relaxed by using conditional imports.

Update minimum support boto version.

---

moto/core/responses.py
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Hello:
I have added in a test for the IAM method `list_intance_profiles_for_role()`
The most "jarring" change would be `moto/core/responses.py`, as I needed to pass in a parameter to one of my response methods -- Not sure of another way of doing this...
Thank You
Note: This is my second attempt at the pull-request... Still learning how to use GitHub as well...

Added in test for the boto IAM method: list_instance_profiles_for_role()

---

tests/test_s3/test_s3.py

Test to make sure we do not duplicate data when uploading the same part twice (issue #324 )

Add test_multipart_duplicate_upload

---

moto/sns/responses.py
tests/test_sns/test_application.py

Add mock for `list_endpoints_by_platform_application` method

Add SNS method

---

moto/elb/models.py
moto/elb/responses.py
tests/test_elb/test_elb.py

Enable support for retrieving and modifying ELB attributes such as connection draining, cross zone load balancing, idle timeout and s3 access logs.

Add support for ELB attributes.

---

moto/ec2/models.py
moto/ec2/responses/subnets.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_ec2/test_subnets.py

This pull request:
* Adds `availability_zone` parameter to Subnet initializer
* Adds `availabilityZone` filter to Subnet
* Replaces hardcoded `us-east-1a` availability zone from Subnet responses

Improve availability zone Subnet support

---

moto/ec2/responses/elastic_block_store.py

It would really help and avoid problems if the returning dates are actually valid ones. I used the same date as found in other response bodies.

Use dummy date instead of an invalid date

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

includes additional test coverage
please take a look @spulec

[dynamodb2] adds lookup method to Table class

---

moto/elb/responses.py
tests/test_elb/test_elb.py

Added test to cover that case.
Paired with @jszwedko

Fix bug creating elb with a listener certificate

---

moto/autoscaling/urls.py
moto/cloudformation/urls.py
moto/cloudwatch/urls.py
moto/core/responses.py
moto/dynamodb/urls.py
moto/dynamodb2/urls.py
moto/ec2/urls.py
moto/elb/urls.py
moto/emr/urls.py
moto/iam/urls.py
moto/kinesis/urls.py
moto/rds/urls.py
moto/rds2/urls.py
moto/redshift/urls.py
moto/server.py
moto/ses/urls.py
moto/sns/urls.py
moto/sqs/urls.py
moto/sts/urls.py
setup.py

Dispatching is not threadsafe. We had request bodies overwriting each other with a high number of simultaneous requests. This pull requests fixes all cases we've found until now.

threadsafe fix

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
tests/test_cloudwatch/test_cloudwatch.py

Very simple implementation of the Cloudwatch PutMetricData and ListMetrics actions.

Add put_metric_data and list_metrics

---

moto/route53/responses.py
tests/test_route53/test_route53.py

[API reference](http://docs.aws.amazon.com/Route53/latest/APIReference/CreateAliasRRSAPI.html)

Add support for alias records in Route53.

---

moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr.py

feature emr: support for instance_groups param in run_jobflow ( in case user has provided instance_groups argument)
feature emr: set_termination_protection implementation

feature emr: set_termination_protection  and instance_groups param in run_jobflow constructor

---

moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

Paging is not done for `list_aliases()`

KMS: aliases

---

moto/backends.py
moto/iam/responses.py
moto/server.py
tests/test_cloudformation/test_server.py
tests/test_iam/test_server.py
tests/test_sns/test_server.py

Hi, I've added two new backends and started a little bit refactoring in server tests for them. I'll appreciate any constructive comments :)

Added server backends with tests for IAM and SNS services.

---

tests/test_s3/test_s3.py

I was debugging a mis configuration on my end and ended up writing these tests for head_object in boto3.  Figured I would offer them back.

Add more boto3 s3 tests

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_server.py

Initial version of support for WaitTimeSeconds in sqs, @spulec  could you review?

Added support for WaitTimeSeconds in SQS #392

---

moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_application_boto3.py
tests/test_sns/test_publishing_boto3.py
tests/test_sns/test_server.py
tests/test_sns/test_subscriptions_boto3.py
tests/test_sns/test_topics_boto3.py

Hi @spulec,
I partially implemented the XML responses for the SNS backend (the topic related responses).
There is a new Boto3 specific test: https://github.com/ludia/moto/blob/feature/implement-sns-xml-response/tests/test_sns/test_topics_boto3.py 
If you think this is the right direction, I could probably finish this today.

Implement XML responses for SNS (for Boto3)

---

moto/dynamodb2/responses.py

Attribute field must be a mapping (not a list)

Fix incorrect dynamodb2 delete_item response

---

README.md
moto/__init__.py
moto/backends.py
moto/datapipeline/__init__.py
moto/datapipeline/models.py
moto/datapipeline/responses.py
moto/datapipeline/urls.py
moto/datapipeline/utils.py
tests/test_datapipeline/test_datapipeline.py
tests/test_datapipeline/test_server.py

First version, I still need to finish the implementation of Pipeline.activate.
@hltbra thoughts?

Datapipeline

---

moto/datapipeline/models.py
moto/datapipeline/responses.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_datapipeline/test_datapipeline.py
tests/test_datapipeline/test_server.py

* Added `physical_resource_id` property
* Normalize response case sensitiveness
Can you please review, @spulec?

Data pipeline improvements

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

For writes, this adds support for "x-amz-acl" headers as well as "x-amz-grant-*" headers. For reads this adds support for the ?acl endpoint. ACLs aren't actually enforced.

Add S3 ACL support.

---

Dockerfile

Create DockerFile for use Moto's stand-alone server as a container. It uses Python 2 image.
With it:
```
docker build .
docker run <image_id>
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```
Maybe you want to register this image at DockerHub ?

Added DockerFile

---

moto/kinesis/exceptions.py
moto/kinesis/models.py
moto/kinesis/responses.py

Kinesis:
add put_records
fix create_stream to emit right response in case of stream already exists

Fix Kinesis API

---

moto/core/responses.py
moto/emr/responses.py
moto/kms/responses.py
tests/test_emr/test_emr_boto3.py

@spulec 
I started adding Boto3 support for EMR module, and will be happy if you can review the modification. 
Most of my modification is pretty much the same with https://github.com/spulec/moto/pull/404, but one difference is switching JSON and XML response by looking at `User-Agent` instead of `querystring` since I couldn't get `JSON` string from QueryString created by boto3 emr client, and IMHO it makes a bit more clear this is for Boto3.

Implement JSON responses for EMR (for Boto3)

---

moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

Adds the following to the KMS service
* PutKeyPolicy
* GetKeyPolicy
* ListKeyPolicies
Signed-off-by: Jesse Szwedko <jesse.szwedko@getbraintree.com>

Add KMS policy actions

---

moto/autoscaling/models.py
tests/test_autoscaling/test_autoscaling.py

This replicate the AWS functionality of keeping the ELB instances in sync with the autoscaling group instances.

Manage instances of ELBs attached to autoscaling group.

---

moto/elb/exceptions.py
moto/elb/models.py
moto/elb/responses.py
requirements-dev.txt
tests/test_elb/test_elb.py
tests/test_swf/responses/test_timeouts.py

This will add the endpoints AddTags, RemoveTags and DescribeTags to ELB.
This should fix #479

Add new endpoints to ELB (fix #479)

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/vpn_connections.py
moto/ec2/utils.py
tests/test_ec2/test_vpn_connections.py

support create, delete, describe

Adding Support for VPN Connections

---

moto/ec2/models.py
moto/ec2/responses/dhcp_options.py
moto/ec2/utils.py

add DescribeDhcpOptionsResponse
support filtering describe_dhcp_options
add get_all_dhcp_options

Adding Support for Get All DHCP Options

---

README.md
moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

This adds a bunch of support and tests for boto3 dynamodb.
I've tested this as part of a larger upgrade for one of the projects I work on.

Add query index support for boto3 via dynamodb2

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

@spulec Thanks for taking #499 and my PR #486 as well.
This is more work I did as part of a boto3 upgrade for DynamoDB. Improvements to UPDATE and support for `Select=COUNT`.
Don't hesitate to leave comments!

Support for other UPDATE DynamoTypes and query Select=COUNT

---

moto/ec2/models.py
moto/ec2/responses/security_groups.py
tests/test_ec2/test_security_groups.py

Adds basic support for egress permission on aws security groups (vpc only)

Adds support for authorizing and revoking egress permissions

---

moto/ec2/models.py
tests/test_ec2/test_elastic_block_store.py

Add missing filter for volume-id on volumes.
Fixes #515

Add filter for volume-id on volumes.

---

moto/autoscaling/models.py
moto/autoscaling/responses.py

Boto3 was complaining about not being able to find these attributes.

Adding additional params to response

---

moto/cloudwatch/responses.py

I added tag DescribeAlarmsResult to work with boto3. If it doesn't have it , it gives the following error.
```python
Error
File "/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
File "python2.7/site-packages/moto/core/models.py", line 71, in wrapper
File "/tests_cloudwatch/tests_cloudwatch_watcher.py", line 26, in test_with_one_topic
pprint(client.describe_alarms())
File "/python2.7/site-packages/botocore/client.py", line 310, in _api_call
File "/home/antonioirizar/anaconda/lib/python2.7/site-packages/botocore/client.py", line 396, in _make_api_call
operation_model, request_dict)
File …
```

add tag (<DescribeAlarmsResult>) to describe_alarms_template

---

moto/cloudwatch/__init__.py
moto/cloudwatch/models.py
moto/cloudwatch/responses.py

Update Cloudtwatch to support multiple regions. Now it can have different metrics in multiple regions.

Cloudwatch support multiple regions

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
moto/cloudformation/models.py
moto/cloudformation/parsing.py
moto/cloudformation/responses.py
moto/core/responses.py
moto/sns/responses.py
requirements-dev.txt
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
tests/test_cloudformation/test_server.py

This lets boto3's cloudformation API work with moto.
A lot of this work was inspired by https://github.com/spulec/moto/pull/404.
fixes #444 
Signed-off-by: Scott Greene <scott.greene@getbraintree.com>

Add XML support for cloudformation commands that lacked it

---

moto/__init__.py
moto/apigateway/__init__.py
moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
moto/apigateway/utils.py
moto/backends.py
moto/core/responses.py
tests/test_apigateway/test_apigateway.py
tests/test_apigateway/test_server.py

Apigateway

---

moto/ses/exceptions.py
moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses.py
tests/test_ses/test_ses_boto3.py

includes test cases for ses client with boto3

update SES backend to support domain identities and multiple recipients

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Added support for query filters as requested in issue #164

Query filters issue 164

---

moto/ec2/models.py
moto/ec2/responses/subnets.py
tests/test_ec2/test_subnets.py

Add support for the 'ModifySubnetAttribute' action. Regarding subnets, there is only one attribute involved (MapPublicIpOnLaunch).

Add support for 'ModifySubnetAttribute' action

---

.gitignore
Makefile
moto/cloudformation/parsing.py
moto/cloudformation/responses.py
moto/s3bucket_path/utils.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

* Fix path detection for deleting keys in S3 bucket
* Fix stack deletion ensure delete method exists on object
* Previous tests were using a stack with no resources
* Fix DESCRIBE_STACK_RESOURCES_RESPONSE,
* Previously untested code path

Fix multiple bugs encountered with boto3

---

moto/route53/models.py
moto/route53/responses.py
tests/test_route53/test_route53.py

Issue: https://github.com/spulec/moto/issues/415

Adding support for UPSERT'ing route53 records

---

moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_application.py

Adds missing implementation for deleting endpoints in sns
Thanks for this library btw, cool stuff 👍

Implement support for sns delete_endpoint()

---

moto/ec2/models.py
moto/ec2/responses/elastic_network_interfaces.py
tests/test_ec2/test_elastic_network_interfaces.py

Add support for tag filtering, as well as for the following filters:
* addresses.private-ip-address
* private-ip-address
* subnet-id
* vpc-id
Also check if the interface is associated to return the correct status ('available' vs. 'in-use') in the DESCRIBE_NETWORK_INTERFACES_RESPONSE template, which is very useful when testing code that uses boto3 waiters.

Extend filtering support for elastic network interfaces

---

moto/cloudformation/parsing.py
moto/kms/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

This adds support for mocking out KMS key manipulation using Cloudformation. Please let me know if there's any changes you'd like to see!

Adds KMS support to mock_cloudformation

---

moto/cloudformation/exceptions.py
moto/cloudformation/parsing.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

- Fix typo in exception message for cloudformation.
- Fix delete stack functionality for stacks with resources for which 'delete' attribute is not defined.

Fix cfn error message and delete stack

---

.gitignore
moto/route53/models.py
moto/route53/responses.py
tests/test_route53/test_route53.py

support for `HostedZone.Config.PrivateZone=True`

Route53 private zone support

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

This only adds the events for the stack itself, but it's possible to add events for the other resources (I just didn't have a need to implement events for any of them.)

Add CloudFormation:DescribeStackEvents

---

moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

This change allows the encrypted attribute to exist on volumes/snapshots.

Add encrypted attribute to Volumes/Snapshots

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

Added Lambda invoke capability.

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

implemented iam list users (Closes #668)

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

Add support for the following ECS commands:
- Run Task
- Start Task
- Stop Task
- List Tasks

Add support for ECS tasks

---

moto/s3bucket_path/utils.py
tests/test_s3/test_s3.py

Stop stripping the trailing slash off keys listed from s3 buckets

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
tests/test_apigateway/test_apigateway.py

Hi there,
Firstly, thank you very much for all the work on moto.  Great library.
I've added extra support for apigateway, as a result of developing ansible modules using boto3 from provisioning api gateways.  This pull request covers the features we are intending to use at work, so I built the additional mocking around the testing of our ansible modules.
The features added are:
- get_stages, 
- stage not found exception 
- update stage configuration
- descriptions on deployments
- creation date on deployments
- setting stage variables on deployments and stage creation
Hopefully the changes make sense.  Please let me know if you need us to make any changes.
thanks
/dom

added more api gateway coverage

---

moto/route53/models.py
moto/route53/responses.py
moto/route53/urls.py
tests/test_route53/test_route53.py

This commit adds support for Route53 tagging. Unit tests included.

Add support and unittests for Route53 tags

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

Add support for dynamodb2 Expected conditions.

fix: dynamodb2 conditions

---

moto/dynamodb2/responses.py

Updating the Dynamodb2 Batch Write response format to match the official documentation:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html

fix: change dynamodb2 batch write response

---

moto/core/responses.py
moto/ec2/responses/amis.py
moto/ec2/responses/elastic_block_store.py
moto/ec2/responses/elastic_ip_addresses.py
moto/ec2/responses/elastic_network_interfaces.py
moto/ec2/responses/instances.py
moto/ec2/responses/internet_gateways.py
moto/ec2/responses/ip_addresses.py
moto/ec2/responses/key_pairs.py
moto/ec2/responses/monitoring.py
moto/ec2/responses/placement_groups.py
moto/ec2/responses/reserved_instances.py
moto/ec2/responses/security_groups.py
moto/ec2/responses/spot_instances.py
moto/ec2/responses/tags.py
moto/elb/responses.py
tests/test_ec2/test_amis.py
tests/test_ec2/test_elastic_block_store.py
tests/test_ec2/test_elastic_ip_addresses.py
tests/test_ec2/test_elastic_network_interfaces.py
tests/test_ec2/test_instances.py
tests/test_ec2/test_internet_gateways.py
tests/test_ec2/test_key_pairs.py
tests/test_ec2/test_security_groups.py
tests/test_ec2/test_spot_instances.py
tests/test_ec2/test_tags.py

Add dry_run capability for a number of boto EC2 calls and also provided unit tests where applicable.

Add dry_run to a number of EC2 services

---

moto/core/responses.py
moto/emr/models.py
moto/emr/responses.py
setup.py
tests/test_emr/test_emr.py
tests/test_emr/test_emr_boto3.py

This revision implements proper filtering and paging (with marker) for relevant EMR end points.

Implement filters and pagers for some EMR end points

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Add DynamoDB tests for update_item() with UpdateExpression, support spaces.

---

moto/cloudformation/parsing.py
moto/ec2/models.py
moto/ecs/models.py
moto/ecs/responses.py
moto/rds/models.py
moto/s3/models.py
moto/s3/responses.py
tests/test_ecs/test_ecs_boto3.py
tests/test_opsworks/test_layers.py

Changes:
* Refactor of existing method `fetch_task_definition`
* Response added for `describe_task_definition`
* Test added for method `describe_task_definition`

Support for ecs describe_task_definition

---

moto/s3/responses.py
moto/s3/urls.py
tests/test_s3bucket_path/test_bucket_path_server.py

This pull request fixes a issue within s3 when creating a bucket and the URL ends with a slash.
It as well fixes the compatibility issue mentioned in issue #780 .
Testcases were extended to cover these cases.

Fix s3bucket_path

---

moto/awslambda/models.py
tests/test_awslambda/test_lambda.py

Issues with #780 aside,
Here is attempt 2 or 5 (forget) for fixing Lambda. Issue #769 - Invoking Lambda function does not generate the correct payload.
As mentioned there was only putting data out for Cloud Watch Logs not in actual payload - hopefully this will address it.

Fixup lambda for ResponseRequest

---

moto/sts/responses.py
tests/test_sts/test_server.py
tests/test_sts/test_sts.py

Return a canned response
Signed-off-by: Andrew Harris <andrew.harris@getbraintree.com>

sts: Implement get_caller_identity

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Signed-off-by: Andrew Harris <andrew.harris@getbraintree.com>

cloudformation: Support RoleARN for create and update stack

---

moto/ec2/models.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_vpcs.py

Adds the ability to set InstanceTenancy for VPCs.

make instanceTenancy configurable for VPCs

---

moto/ec2/models.py
tests/test_cloudformation/fixtures/vpc_single_instance_in_subnet.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

EC2 tags specified in CloudFormation should be applied to the instances

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Use request URL to generate SQS queue URLs

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam_groups.py

Implemented mocks for:
* get_all_group_policies
* list_group_policies (boto3)
* get_group_policy
* put_group_policy

iam: add group policy methods

---

moto/sqs/models.py

This just ensure that the `WaitTimeSeconds` property is in integer.

Ensure SQS property WaitTimeSeconds is an integer

---

AUTHORS.md
moto/rds/models.py
moto/rds2/models.py
tests/test_rds2/test_rds2.py

update RDS responses to return DBInstanceArn

---

moto/ec2/models.py
tests/test_ec2/test_elastic_network_interfaces.py

Small PR that implements availability-zone filter for EC2 DescribeNetworkInterfaces

Implement availability-zone filter for DescribeNetworkInterfaces

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

- Add mfa device class
- Add mfa devices dictionary to user class
- Add responses, endpoints and tests

Add mfa device endpoints to iam backend.

---

moto/s3/responses.py

Issue is described here: https://github.com/spulec/moto/issues/900

Fixed S3 copyObject compatibility with the Java AWS SDK

---

AUTHORS.md
moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

**Features**
* Implemented `deregister_container_instance` - tests added for behaviour around exception raising etc.
**Changes**
* Changed ContainerInstance object attributes to use snake case for consistency
* Added myself to the authors list

ContainerInstance deregistration

---

moto/datapipeline/models.py
moto/datapipeline/responses.py
tests/test_datapipeline/test_datapipeline.py

Also added basic tags for Data Pipeline

Implementation of delete_pipeline

---

moto/s3/responses.py
tests/test_s3/test_server.py

Require content-length header

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

Idempotent Dynamodb2 deletes

---

moto/cloudformation/models.py
setup.py
tests/test_cloudformation/test_stack_parsing.py

Allow yaml templates for cloud formation

---

moto/ec2/models.py
moto/ec2/responses/network_acls.py
tests/test_ec2/test_network_acls.py

Hello,
Please find an implementation for ec2.delete_network_acl_entry and ec2.replace_network_acl_entry.
With tests.
Hope this helps.
Note: could you please give me some quick steps to build/run on Windows? Thanks.

Replace and delete Network ACL Entries

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

S3 DeleteMarker support

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

implementing IAM delete_role

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

NoSuchKey error in S3 is actually '404'

---

moto/core/utils.py
moto/s3/responses.py
tests/test_s3/test_s3.py

See http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html

feat(s3) HeadObject: honor If-Modified-Since header

---

moto/packages/responses/responses.py

add pass_through option to responses

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

DynamoDB supports Expected on UpdateItem http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html.
moto does not have that implemented, so this PR adds support for providing Expected on update_item requests.

Support Expected in dynamoDB updateItem

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Closes https://github.com/spulec/moto/issues/1008. This adds support for S3 object tagging gets and puts

Implement S3 object tagging

---

moto/ec2/responses/__init__.py
moto/ec2/responses/account_attributes.py
tests/test_ec2/test_account_attributes.py

> ----------------------------------------------------------------------
> Ran 1356 tests in 207.346s
> 
> OK

Added DescribeAccountAttributes

---

moto/cloudformation/parsing.py
moto/kinesis/models.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

This PR adds initial support for Kinesis streams in CloudFormation templates.

Add CloudFormation model for Kinesis streams

---

moto/s3/responses.py
tests/test_s3/test_s3.py

With `boto` and `boto3`, the responses are different when HEAD bucket operation returns 404, the former returning `S3ResponseError` but the latter returning `ClientError`. `moto` returns `S3ResponseError` for both `boto` and `boto3`, which makes exception handling for the specific case to be incompatible assuming the real API behavior. This PR should fix the issue and resolves #1004.

Make HEAD bucket throw ClientError instead of NoSuchBucket on boto3

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Adds the following SSM endpoints:
- [add_tags_to_resource](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.add_tags_to_resource)
- [list_tags_for_resource](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.list_tags_for_resource)
- [remove_tags_from_resource](http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.remove_tags_from_resource)

Add add, remove, list endpoints for SSM tags

---

moto/ecr/responses.py
tests/test_ecr/test_ecr_boto3.py

Pretty straightforward - not sure what else to add.

Add ecr get_authorization_token response and tests

---

README.md
tests/test_s3/test_s3.py

Updating examples in README to latest API

---

docs/index.rst
moto/__init__.py
moto/backends.py
moto/elb/urls.py
moto/elbv2/__init__.py
moto/elbv2/exceptions.py
moto/elbv2/models.py
moto/elbv2/responses.py
moto/elbv2/urls.py
tests/test_elb/test_server.py
tests/test_elbv2/test_elbv2.py
tests/test_elbv2/test_server.py

```
-----------------------
elbv2 - 38% implemented
-----------------------
[ ] add_tags
[X] create_listener
[X] create_load_balancer
[ ] create_rule
[X] create_target_group
[X] delete_listener
[X] delete_load_balancer
[ ] delete_rule
[X] delete_target_group
[X] deregister_targets
[ ] describe_account_limits
[X] describe_listeners
[ ] describe_load_balancer_attributes
[X] describe_load_balancers
[ ] describe_rules
[ ] describe_ssl_policies
[ ] describe_tags
[ ] describe_target_group_attributes
[X] describe_target_groups
[X] describe_target_health
[ ] modify_listener
[ ] modify_load_balancer_attributes
[ ] modify_rule
[ ] modify_target_group
[ ] modify_target_group_attributes
[X] register_targets
[ ] remove_tags
[ ] set_ip_address_type
[ ] set_rule_priorities
[ ] set_security_groups
[ ] …
```

Implemented core endpoints of ELBv2

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Adds support for DetachRolePolicy and DeleteRolePolicy.

Add support for iam:DetachRolePolicy and iam:DeleteRolePolicy.

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Added support for [delete_parameters](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DeleteParameters.html)

Added support for SSM delete_parameters

---

moto/elbv2/exceptions.py
moto/elbv2/models.py
moto/elbv2/responses.py
tests/test_elbv2/test_elbv2.py

- create_rule
- delete_rule
- describe_rules
- modify_rule
- set_rule_priorities
advanced validation like checking content of condition values is not implemented.

Implement methods related to listener rules at ELBv2

---

moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

Fixing this. https://github.com/spulec/moto/issues/1062

fix bug that Names filter dont work at describe_target_groups

---

moto/elbv2/exceptions.py
moto/elbv2/models.py
moto/elbv2/responses.py
tests/test_elbv2/test_elbv2.py

Fixing: https://github.com/spulec/moto/issues/1070
When modify_rule is called without either Actions or Conditions parameter,  or one of them is empty list, the parameter which is empty/None should be remained in the original record.

ELBv2 modify_rule changes listener rule partially

---

Makefile

I'm pretty forgetful so I doubt I'd remember to do this

Create git tag on release

---

moto/dynamodb/responses.py
moto/dynamodb/urls.py
moto/dynamodb2/responses.py
moto/dynamodb2/urls.py

Fixes #1095
Also removed some older STS related logic from Dynamo that wasn't relevant.

Fixed Dynamo mocking STS bug

---

moto/elbv2/exceptions.py
tests/test_elbv2/test_elbv2.py

error log
```
File "/Users/kawasakitoshiya/workspace/moto/moto/elbv2/exceptions.py", line 45, in __init__
super(TooManyTagsError, self).__init__(
TypeError: super(type, obj): obj must be an instance or subtype of type
```

fix TargetGroupNotFoundError is not defined correctly

---

moto/s3/exceptions.py
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Fixes #1109 
Tested internally and works properly.

Fixed S3 lifecycle error message.

---

moto/dynamodb2/models.py

fix uppercase only issue in update_expression #1091

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Fix issue #1126 
Add support for doing an update_item ADD for a string set in dynamodb2

Dynamodb2 - Allow doing an ADD update_item of a string set

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.tag_resource
http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.untag_resource
http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.list_tags

add Lambda tag_resource, untag_resource, and list_tags methods

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Add support for the ADD and DELETE operations in dynamodb update expressions
Fixes #766

Add support for the ADD and DELETE operations in dynamodb update expressions

---

moto/ec2/models.py
moto/ec2/responses/key_pairs.py
tests/test_ec2/test_key_pairs.py

This PR adds keypair filtering support by key-name and fingerprint.
Also improves error reporting if an InvalidKeyPairNameError occurs

Added keypair filtering

---

moto/ec2/models.py
moto/ec2/responses/elastic_ip_addresses.py
tests/test_ec2/test_elastic_ip_addresses.py

This PR improves filtering for DescribeAddresses.
Also fixes issue where the address's eni is None despite being attached.
Includes tests.

Improved support for VPC Address filtering

---

moto/ec2/exceptions.py
moto/ec2/models.py

@JackDanger @dbfr3qs This PR is based on review comment: https://github.com/spulec/moto/pull/1148#pullrequestreview-63172356
It makes the handling of all unknown filter names consistent, by throwing a FilterNotImplementedError()

Refactored handling of unknown filter names

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

SSM now has GetParameter (boto added get_parameter) so I added it here.
Any issues with this?

Added SSM GetParameter support

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #1162 (issue contains stacktrace etc...)
Also added message support when returning errors to make it more AWS like.

Fix hang when querying a table that doesnt exist

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
moto/cloudwatch/utils.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Should help fix #696 eventually
TODO:

Cloudwatch Implementation

---

moto/s3/responses.py
tests/test_s3/test_s3.py

supporting signed urls for private keys

---

moto/core/responses.py
moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Various cleanups in the SQS part. If [this](https://github.com/spulec/freezegun/pull/210) PR is merged, can then cut down test time from 15s to 9s and could probably get test_messages_polling down from 3s.
Passed more options to Queue class.
Cleaned some parts of the web request attribute management.
Fixes #1105

SQS Cleanup, and fix #1105

---

moto/opsworks/models.py
tests/test_opsworks/test_layers.py

Layer per stack

---

moto/route53/models.py

#1044 - I thought it too would confuse people for a second if it doesn't look like what they're used to.

Updated R53 ID's to match what AWS do now

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Fixed bug in S3 put_bucket_tagging. Closes #1181.

---

moto/ec2/responses/general.py
tests/test_ec2/test_general.py

Fix for issue: https://github.com/spulec/moto/pull/1152#issuecomment-332487599

Fix for regression in get_console_output()

---

scripts/scaffold.py

Just added line at the bottom that reminds others what files also need to be modified, pretty sure I got everything.

Added more output to scaffold.py

---

CHANGELOG.md

ae110dc
changelog-1.1.14
4b5d780
changelog-1.1.15

changelog-1.1.14

---

moto/redshift/responses.py
tests/test_redshift/test_redshift.py

boto uses the param.member.N syntax, but boto3 replaces the generic
.member with a more specific identifier.
Example:
boto: ClusterSecurityGroups.member.N
boto3: ClusterSecurityGroups.ClusterSecurityGroupName.N
This commit addresses this issue for the ClusterSecurityGroups, SubnetIds,
and VpcSecurityGroupIds parameters.

Fix boto/boto3 multi-param discrepancies

---

scripts/scaffold.py
scripts/template/lib/urls.py.j2

When adding new service:
- add `urls.py`
- add mocks declaration to `moto/__init__.py` and `moto/backends.py`
When adding new operation to a service:
- add uri to `urls.py`

Add more files and lines when scaffolding

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam_groups.py

37ae618
add model methods for iam attached group policies
3788e42
implement handlers for iam attached group policies
9f02a84
test attaching group policies
cdb1ebf
pep8 fixes
feb4616
implementing detach_group_policy

Implement IAM attached group policies

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

This adds simple implementations for aws_lambda.add_permission and aws_lambda.get_policy.

add basic awslambda get_policy

---

moto/ec2/models.py
moto/ec2/responses/spot_fleets.py
tests/test_ec2/test_spot_fleet.py

Hi, it's me again!  I really want to be able to test modify_spot_fleet_request operations in my code so I went ahead and added this into moto.  I'm using this code right now in my application too, so I have some additional confidence it's correct.  Would love to hear what you think.
All tests pass!

Modify spot fleet request

---

moto/sqs/exceptions.py
moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

implement SQS QueueDoesNotExist error

---

moto/dynamodb2/comparisons.py
tests/test_dynamodb2/test_dynamodb.py

FilterExpression was incorrectly handling numbers, stupid typo there. 
Also `>=` `<=` and `<>` was not being parsed correctly.
Should be good now.

Fixed #1261 dynamodb FilterExpression bugs

---

moto/autoscaling/exceptions.py
moto/autoscaling/models.py
moto/autoscaling/responses.py
moto/ec2/models.py
tests/test_autoscaling/test_autoscaling.py

Hello! Long time fan, first time contributor. I wanted the detach_instances functionality for a project of mine, so I decided to try my hand at implementing it. 
Edit: I also added the `attach_instances` method, as requested in this issue: https://github.com/spulec/moto/issues/893

Add attach_ and detach_instances methods to autoscaling service

---

moto/s3/models.py
tests/test_s3/test_s3.py

Fixed S3 versioning bug + minor cleanup

---

scripts/template/lib/models.py.j2

Fixed bug that Backend is not instantiated in model.py

[WIP]fix scaffold template

---

moto/dynamodb2/comparisons.py
tests/test_dynamodb2/test_dynamodb.py

Make some general improvements, thanks @batkuip for a non working example that lead to me discovering a logical issue with handling brackets, code now recurses to parse nested brackets properly.
Also after some reading looks like I was overthinking the NOT operator and it just behaves like a normal right associative operator like the `!` in C. So added NOT functionality too.

DynamoDB FilterExpression NOT logic

---

CHANGELOG.md
setup.py

fc78e6fe
bumping to version 1.1.24
4a354df7
changelog for 1.1.23
b79a4bf2
Changelog for 1.1.24

bumping to version 1.1.24

---

IMPLEMENTATION_COVERAGE.md
Makefile
scripts/implementation_coverage.py

Also creating a make task for generating implementation coverage output

Adding initial implementation coverage

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/ec2/models.py
moto/rds2/models.py
tests/test_awslambda/test_lambda.py
tests/test_ec2/test_instances.py
tests/test_ec2/test_route_tables.py
wait_for.py

Ok I changed how we assign IPs to instances so that they get assigned IPs that fall within the subnet the instance is started in.
Fixes #1175 
Travis has spammed many errors at me, am sure most of them are bs, will look into it in the morning.

Fixed a few ip issues

---

IMPLEMENTATION_COVERAGE.md
README.md
moto/core/exceptions.py
moto/dynamodb2/__init__.py
moto/dynamodb2/models.py
moto/dynamodb2/responses.py
moto/ecs/models.py
moto/ecs/responses.py
moto/elbv2/models.py
moto/elbv2/responses.py
moto/events/models.py
moto/events/responses.py
moto/sqs/models.py
moto/sqs/responses.py
tests/test_acm/test_acm.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py
tests/test_ecs/test_ecs_boto3.py
tests/test_elbv2/test_elbv2.py
tests/test_events/test_events.py
tests/test_sqs/test_sqs.py

@JackDanger sorry in advance, is quite a bit to review :wink:. Got a bit bored and had little access to internet so went on a service completion spree.

Lotsa stuff

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Signed-off-by: Kai Xia <xiaket@gmail.com>

Added support for SSM get_parameters_by_path.

---

moto/sns/models.py
tests/test_sns/test_topics_boto3.py

Makes SNS topics indempodent

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Adds FilterExpression to dynamodb.query

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #1043 
Should really create proper KeyConditionExpression parser

DynamoDB: Fixed requiring optional parameter

---

moto/iot/exceptions.py
moto/iotdata/exceptions.py

As iot/iot-data seemed different from the actual response, I modified the following points.:
- format the response body from xml to json
- status code from 400 to 404 when ResourceNotFound

fix error response on iot/iot-data

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #1342
Isn't a total solution but I think we might get away with this until someone tries to do something really complicated.
Looked at the dynamodb source code and they just use generated ANTLR so reverse engineering that is far too much hassle. We'll make do with our great string parsing :smile:

Added support for dynamo update_item on nested dicts

---

moto/iotdata/models.py
moto/iotdata/responses.py
tests/test_iotdata/test_iotdata.py

Add publish operation to iotdata

---

moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
moto/awslambda/utils.py
moto/core/responses.py
tests/test_awslambda/test_lambda.py

Fixes #1338 
Completely revamped how lambdas are stored, now we have lambda publishing working and aliasing should be trivial to add, attempted to spam `weakref` everywhere but I have a feeling my debugger was messing with the refs so theres more boilerplate code that I would of expected.
Done the majority of this whilst sleep deprived, @JackDanger keep an eye out for the spelling mistakes ;-).
Also cleaned up the responses.py, made use of a json property and backend property, I think I inadvertently fixed some region malarkey when in server mode too.

Lambda improvements

---

IMPLEMENTATION_COVERAGE.md
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Implementation of IAM delete_server_certificate with unit tests.

IAM delete_server_certificate

---

moto/kinesis/models.py
moto/kinesis/responses.py
moto/kinesis/utils.py
tests/test_kinesis/test_kinesis.py

add support for kinesis AT_TIMESTAMP shard iterator

---

moto/iam/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Based on http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html

Path is an optional property of instance profile cloudformation resource

---

moto/ec2/models.py
tests/test_ec2/test_amis.py

Closes: https://github.com/spulec/moto/issues/1408

Make sure invalid or malformed AMIs raise an exception

---

CHANGELOG.md
IMPLEMENTATION_COVERAGE.md
moto/backends.py
moto/swf/models/__init__.py
moto/swf/models/history_event.py
moto/swf/models/workflow_execution.py
moto/swf/responses.py
tests/test_swf/responses/test_workflow_executions.py

* Implemented signal_workflow_execution for SWF
* Wired SWF backend to the moto server
* Fixed incorrect handling of task list parameter on start_workflow_execution

Improved SWF support

---

moto/xray/mock_client.py

fixes #1399
this won't help with fixtures though

mock_xray_client: don't swallow function's return value

---

moto/cloudformation/models.py

Change needed to allow update to a FakeStack to accept both JSON and YAML templates.

FakeStack update to support both JSON and YAML templates

---

moto/iot/exceptions.py
moto/iot/models.py
moto/iot/responses.py
tests/test_iot/test_iot.py

Added group related features to aws-iot. @terrycain @JackDanger please review if you time ;)

Add group features to iot

---

moto/core/responses.py
moto/ec2/models.py
moto/ec2/responses/amis.py
tests/test_ec2/test_amis.py

Closes: https://github.com/spulec/moto/issues/1396

Added support for filtering AMIs by self

---

moto/__init__.py

fixing version number

---

moto/iot/exceptions.py

Small fix for defining exception class

Fix iot exception definition

---

moto/cloudformation/parsing.py
tests/test_cloudformation/test_stack_parsing.py

Implement `Fn::GetAZs` function in CloudFormation. This PR also adds a simple test to cover the new functionality.

Implement Fn::GetAZs function in CloudFormation

---

moto/logs/exceptions.py
moto/logs/models.py
tests/test_logs/test_logs.py

As logs module has not raises boto fashion exceptions, we could not test the resource coflict. I therefore added exceptions.

Add logs exceptions

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Adds if_not_exists function to DynamoDB Update Expression

---

tests/test_opsworks/test_instances.py
tests/test_opsworks/test_layers.py

Add some more tests for exceptions in OpsWorks mocks.

Add more exception tests for opsworks

---

moto/elb/responses.py
moto/elbv2/responses.py

Fix handling of PageSize for ELB/ELBv2

---

moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

Attempting to add support for iam roles to the redshift via https://github.com/spulec/moto/issues/1487

add iam roles to redshift

---

moto/ec2/models.py
tests/test_ec2/test_elastic_block_store.py

Requires https://github.com/spulec/moto/pull/1456 before merge

Add in filtering of EBS volumes on availability-zone

---

.bumpversion.cfg
CHANGELOG.md
IMPLEMENTATION_COVERAGE.md
moto/__init__.py
setup.py

7ee21a70
Adding CHANGELOG entry for 1.3.0
d1ce6a35
bumping to version 1.3.0
22cbf201
Updating implementation coverage

Releasing version 1.3.0

---

moto/opsworks/models.py
moto/opsworks/responses.py
tests/test_opsworks/test_apps.py

Add the mocks of OpsWork create_app and describe_apps calls. This is part of #1477

Add opsworks app mocks

---

moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
tests/test_apigateway/test_apigateway.py

~Update: I dont want to setup travis on my fork, and locally im getting weird errors. Created the PR just so i can use yours.~
~Update: Turns out the your master branch is the problem O_O. At any rate, when you can merge me in, id really appreciate it.~
Update: All are tests passing, please merge or comment on what changes you want me to make. Thanks!
---------
Don't know where else to document this, but if you want to test this without worrying too much about setup:
```
docker run --rm -it -v $(pwd):/moto python:3.6-alpine sh -c 'apk --update add bash alpine-sdk libffi-dev libxml2-dev libxslt-dev openssl-dev; cd moto; pip install -r requirements-dev.txt; cd ..; exec bash'
```
Once inside the docker machine:
```
cd moto
TEST_SERVER_MODE=true AWS_SECRET_ACCESS_KEY=server_secret …
```

Basic support for AWS Gateway apikeys

---

Makefile
moto/glacier/models.py
moto/glacier/responses.py
tests/test_glacier/test_glacier_jobs.py

This PR addresses the issue raised here:  https://github.com/spulec/moto/issues/1113
In short, the Flask Request object does not support a 'body' attribute. Changed here to 'data'.

Use 'data' attribute of Flask Request object.

---

.bumpversion.cfg
IMPLEMENTATION_COVERAGE.md
moto/__init__.py
setup.py

136d4915
bumping to version 1.3.1
13e28b03
Updating implementation coverage

bumping to version 1.3.1

---

moto/route53/responses.py

Clearly a missed typo, I found while working on Route53 mocks

Change REPONSE to RESPONSE for consistency

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

http://boto3.readthedocs.io/en/latest/reference/services/ecs.html#ECS.Client.register_task_definition

ECS CPU, memory hard limits and host ports are all optional.

---

moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_tags.py

Largely copying what was done for volume creation in https://github.com/spulec/moto/pull/1432

Allow tagging snapshots on creation

---

moto/sns/models.py

SNS support for all boto3 regions.

---

IMPLEMENTATION_COVERAGE.md
moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

I haven't yet created unit tests for this, but it was an essential addition I needed for my testing. If I have the time I'll submit tests ASAP.

Add support for copying EBS snapshots

---

docs/docs/getting_started.rst

Found a few sentences in the Docs that I thought could be a bit more readable, hopefully improved them.

UPDATE getting_started.rst - improve wording

---

AUTHORS.md
moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

This PR implements #1517.
I have added support for the `ParameterFilters` argument of the `GetParametersByPath` API.

Implement SSM Parameter Store filters support (GetParametersByPath API)

---

moto/redshift/models.py
tests/test_redshift/test_redshift.py

* Add `restored_from_snapshot` boolean to Cluster metadata.
* Return `RestoreStatus` from describe_db_clusters if cluster was restored from a snapshot.
Fixes #1506

Add support for Redshift.Waiter.ClusterRestored

---

moto/batch/models.py

Adds what I needed to fix https://github.com/spulec/moto/issues/1606
Note: this doesn't add all the data that could be returned from AWS for Batch job status, just a few extra fields.

1606 Add additional fields to Batch job status endpoint

---

moto/awslambda/models.py

Adds the govcloud region to the lambda back ends.  This fixes #1614

Add gocloud to lambda back ends

---

moto/awslambda/models.py

LambdaVersion providing ARN on __repr__

---

moto/iam/responses.py

IAM get_user_policy() response was not properly rendered (#1547)

fixes #1547

---

IMPLEMENTATION_COVERAGE.md
Makefile
moto/ecr/responses.py
moto/iot/models.py
moto/iot/responses.py
scripts/implementation_coverage.py
tests/test_ecr/test_ecr_boto3.py
tests/test_iot/test_iot.py

**ECR**
Fix the way `get_authorization_token` is used to work the way it is described in the AWS docs (see #1624 )
**IoT**
Added `create_job` and `describe_job` functions together with tests
Updated `implementation_coverage.py` script to write changes to implementation coverage directly to `IMPLEMENTATION_COVERAGE.md` (see #1633)

Fixes #1624 and closes #1633

---

moto/s3/exceptions.py
moto/s3/models.py
tests/test_s3/test_s3_storageclass.py

This pull request will add code to check for a valid storage class.
This is in reference to Issue #1652 [https://github.com/spulec/moto/issues/1652](https://github.com/spulec/moto/issues/1652)

Fix Storage Class error handling

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

Add support for creating ECS services with Load Balancer and fixes #1668

Extend support for ECS

---

Makefile
README.md
moto/__init__.py
moto/backends.py
moto/secretsmanager/__init__.py
moto/secretsmanager/models.py
moto/secretsmanager/responses.py
moto/secretsmanager/urls.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_secretsmanager/test_server.py

Adding basic SecretManager support:
Done:
get_secret_value()
Todo:
list_secrets()
create_secret()
delete_secret()

[WIP] Adding secretmanager support

---

moto/secretsmanager/exceptions.py
moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_secretsmanager/test_server.py

* Adding create_secret for SecretManager
* Need region reset for test to work
* update secret_arn to take arguments

Adding create_secret for SecretsManager

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Extends the SSM backend with the ListCommands endpoint. Resolves #1602.

Extend ssm backend

---

moto/s3/models.py
tests/test_s3/test_s3.py

… otherwise an exception is raised when trying to iterate over an empty list

BugFix: Exception in ListObjectVersions with a Prefix that Returns an Empty Result Set

---

moto/ecr/models.py
tests/test_ecr/test_ecr_boto3.py

ECR: list_images should return RepositoryNotFoundException when repository is not found

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
tests/test_apigateway/test_apigateway.py
tests/test_apigateway/test_server.py

This PR adds support for usage plans and usage plan keys to API gateway.

APIGateway: Added API for usage plans and usage plan keys

---

moto/iam/models.py
tests/test_iam/test_iam.py

Adding account id to ManagedPolicy ARN

---

moto/secretsmanager/exceptions.py
moto/secretsmanager/models.py
moto/secretsmanager/responses.py
moto/secretsmanager/utils.py
tests/test_secretsmanager/test_secretsmanager.py

Added SecretsManager get_random_password mock with tests
Ref: https://boto3.readthedocs.io/en/latest/reference/services/secretsmanager.html#SecretsManager.Client.get_random_password

Added SecretsManager get_random_password mock

---

setup.py

Addresses https://github.com/spulec/moto/issues/1812.

Remove unused cookies dependency

---

moto/redshift/models.py
tests/test_redshift/test_redshift.py

Add `ClusterCreateTime` to Redshift response

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Add support for getting command invocations to the SSM backend.

Ssm backend get command invocation upstream

---

IMPLEMENTATION_COVERAGE.md
moto/ecr/models.py
moto/iot/models.py
moto/iot/responses.py
scripts/implementation_coverage.py
tests/test_ecr/test_ecr_boto3.py
tests/test_iot/test_iot.py

Fixes #1673 
Fixes #1684 
Fixes #1685

Fix ECR and bug fixes

---

moto/kms/models.py
moto/kms/responses.py
tests/test_kms/test_kms.py

Resolves #1853 (adds schedule_key_deletion), and also adds support for disable_key, enable_key and cancel_key_deletion to KMS.

Add support for disable_key, enable_key, cancel_key_deletion, schedule_key_deletion to KMS

---

moto/iam/exceptions.py
moto/iam/models.py
moto/iam/responses.py
moto/iam/utils.py
tests/test_iam/test_iam.py

Made a bunch of fixes and additions:
Fixes:
- Fixed InstanceProfiles having `Path` set to `None`.
- Added in some dynamic `CreateDate`s.
- Fixed issue where the `InstanceProfileId` wasn't being received.
Additions:
- Added support for IAM User Self-Signing Certificates
Rebased with the latest and greatest updates and changes.

IAM Improvements

---

moto/iam/responses.py
tests/test_iam/test_iam.py

Lowercase XML element names in API responses seem to cause issues for boto3.

Support IAM Credential Report in boto3

---

moto/__init__.py
moto/backends.py
moto/dynamodb2/models.py
moto/dynamodb2/responses.py
moto/dynamodbstreams/__init__.py
moto/dynamodbstreams/models.py
moto/dynamodbstreams/responses.py
moto/dynamodbstreams/urls.py
moto/server.py
setup.cfg
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodbstreams/test_dynamodbstreams.py

Resolves issue #1875 by completing the implementation for DynamoDB Streams.

Support DynamoDB Streams

---

moto/ec2/models.py
tests/test_ec2/test_vpc_peering.py

Set deleted status on vpc peer deletion.

---

IMPLEMENTATION_COVERAGE.md
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Adds ability to do CRUD mocking for IAM SAML provider types :D

Add functionalities for SAML Providers

---

moto/cloudformation/models.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

This matches the behaviour of the AWS API.
Fixes #1968

Return the deleted stacks in the list stacks call

---

IMPLEMENTATION_COVERAGE.md
Makefile
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Written test that still do not work due to:
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "UserName", must be one of: AccessKeyId
Refactored update_access_key and delete_access_key functions

Implement get_access_key_last_used

---

IMPLEMENTATION_COVERAGE.md

I have done a bugfix on it, so I guess it's there. Cannot think of something missing :)

get_bucket_location is already implemented

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py

The AWS API represents a set object as a list of values. Internally moto also represents a set as a list. This means that when we do value comparisons, the order of the values can cause a set equality test to fail.
To implement, we extend the `cast_value` property on the DynamoType to also have an internal representation for `set` objects, and update our comparisons to use `DynamoType.compare()`

Make EQ conditions on sets work reliably in DynamoDB

---

IMPLEMENTATION_COVERAGE.md
moto/iam/exceptions.py
moto/iam/models.py
moto/iam/responses.py
setup.py
tests/test_iam/test_iam.py

IAM Role Tagging support

---

moto/acm/models.py
setup.py

requests 2.21.0 allows idna 2.8 [1]
[1] https://github.com/kennethreitz/requests/commit/8761e9736f7d5508a5547cdf3adecbe0b7306278

Bump idna to 2.8

---

.gitignore
README.md
moto/backends.py
moto/config/__init__.py
moto/config/exceptions.py
moto/config/models.py
moto/config/responses.py
moto/config/urls.py
tests/test_config/test_config.py

Added basic AWS Config support mostly for testing enablement and disablement.

Basic AWS Config service support.

---

IMPLEMENTATION_COVERAGE.md

SQS get_queue_url was implemented in dbf2368aa.

IMPLEMENTATION_COVERAGE.md: SQS get_queue_url is implemented

---

moto/config/models.py
tests/test_config/test_config.py

More accurately reflects the behavior of the API.

Fixed validation bugs in put_configuration_recorder

---

moto/kms/models.py

Addresses this issue https://github.com/spulec/moto/issues/2072

fix creation date in create key response to unix timestamp type

---

moto/cloudformation/models.py
tests/test_cloudformation/test_stack_parsing.py
tests/test_kms/test_kms.py
tests/test_s3/test_server.py
tests/test_s3bucket_path/test_bucket_path_server.py

Fixing broken tests #2126

---

IMPLEMENTATION_COVERAGE.md
moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

Implement the Secrets Manager `ListSecrets` endpoint.
Fixes #2140

Feature: aws secretsmanager list-secrets

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

fix #2161 DyanmoDB query method using GSI with range key

---

IMPLEMENTATION_COVERAGE.md
moto/cloudformation/models.py
moto/cloudformation/responses.py
moto/cloudformation/utils.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Added most of the stackset methods except for a few of the stack_set_operation ones. I'll probably have a follow up PR with those if I get a chance.

#1514 Stackset Support

---

IMPLEMENTATION_COVERAGE.md
moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

Feature: Secrets Manager restore-secret

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Thank you for this great library.
This is a patch for #2046 .

Support create_table with PAY_PER_REQUEST billing mode of DynamoDB

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECS/Client.html#list_services-instance_method

Adds Support for filtering on schedulingStrategy in ECS#list_services

---

IMPLEMENTATION_COVERAGE.md
moto/kinesis/models.py
moto/kinesis/responses.py
tests/test_kinesis/test_kinesis.py

Dear moto team.
I added implementation of the `describe_stream_summary` method for kinesis.

add implemented kinesis method describe_stream_summary

---

moto/kms/models.py
tests/test_kms/test_kms.py

Platform independent KMS timestamp generation

---

moto/redshift/models.py
tests/test_redshift/test_redshift.py

Fixes https://github.com/spulec/moto/issues/2215

Updating redshift.describe_cluster_snapshots to return multiple snapshots for cluster_identifier

---

moto/cloudformation/parsing.py
moto/dynamodb2/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

add support to create dynamodb resource by cloudformation.

support to create dynamodb resource by cloudformation

---

IMPLEMENTATION_COVERAGE.md
moto/organizations/models.py
moto/organizations/responses.py
moto/organizations/utils.py
tests/test_organizations/organizations_test_utils.py
tests/test_organizations/test_organizations_boto3.py

I have added the following mock endpoints to the Organizations service:
- create_policy
- list_policies
- describe_policy
- attach_policy
- list_policies_for_target
- list_targets_for_policy

[Resolves #2196] - endpoints for querying organizations SC policies

---

IMPLEMENTATION_COVERAGE.md
moto/iot/models.py
moto/iot/responses.py
tests/test_iot/test_iot.py

This adds support for importing a certificate by specifying the certificate PEM. Fix for #1826

Fix #1826, Add support for IoT register_certificate

---

IMPLEMENTATION_COVERAGE.md
moto/ecr/models.py
moto/ecr/responses.py
tests/test_ecr/test_ecr_boto3.py

This implements the missing endpoint from issue #2224

Implement ECR batch_delete_image

---

moto/ecr/models.py
setup.py
tests/test_ecr/test_ecr_boto3.py

This implements the enhancement for ECR images stated in issue #2228

Set ECR imagePushedAt to current date and time

---

moto/glue/responses.py
tests/test_glue/test_datacatalog.py

As the title says, this adds the `batch_create_partition` endpoint to the Glue client.

Add batch_create_partition endpoint to Glue client

---

IMPLEMENTATION_COVERAGE.md
moto/glue/models.py
moto/glue/responses.py
tests/test_glue/test_datacatalog.py

Added more glue endpoints, also updated the implementation coverage list with the covered glue endpoints.

Add glue.delete_partition and glue.batch_delete_partition

---

moto/route53/models.py
tests/test_route53/test_route53.py

route53.list_resource_record_sets() with StartRecordName= behaves different from real service

---

moto/kinesis/models.py
tests/test_kinesis/test_kinesis.py

fix bug in Stream init (wrong number of shards)

---

moto/route53/models.py
moto/route53/responses.py
tests/test_route53/test_route53.py

Route53 Delete: respect the given Type

---

moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_topics_boto3.py

Add attributes parameter for SNS create_topic API. Resolves #2049

Add attributes parameter support for sns create_topic API

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Resolves Issue: #2263 
Please pull and run this code against your testing suite since I am not confident that I am running the tests correctly.

Implement If-Modified-Since in GET Object for S3 Bucket

---

moto/rds2/models.py
tests/test_rds2/test_rds2.py

Add missing InstanceCreateTime attribute to DBInstance. Resolves #2220

Add InstanceCreateTime to DBInstance

---

moto/rds2/exceptions.py
moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py

Add support for OptionGroupName parameter in create_db_instance. Resolves: #2183

Add support for OptionGroupName in create_db_instance

---

moto/apigateway/utils.py

Fix ID generation

---

moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py

Add support for VpcSecurityGroups set/update in RDS. Resolves: #2249

Add support for VpcSecurityGroups set/update in RDS

---

moto/dynamodb2/comparisons.py
tests/test_dynamodb2/test_dynamodb.py

The test case should hopefully explain why this is an issue. I was doing some testing with more complicated condition expressions and came across this

dynamodb2: Defer evaluation of the OR RHS in condition expr

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Fix issue https://github.com/spulec/moto/issues/2328

Fix DynamoDB update_item to deal with list-type attributes

---

moto/server.py
tests/test_core/test_server.py

Refactor host parsing logic. Allow wildcard through.
Closes #1855 and #2323

Host parsing

---

moto/ecs/models.py

Before when a task definition revision was de-registered all revisions after that changed their revision id. This doesn't match the way it is handled in AWS. Using a dict and manually increment the revision id solves that.

Use a dict instead of a list for storing task definition revisions

---

.gitignore
IMPLEMENTATION_COVERAGE.md
moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

Implements APIGateway [update_api_key](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway.html#APIGateway.Client.update_api_key) fixing #2340

implements APIGateway update_api_key

---

moto/redshift/models.py
tests/test_redshift/test_redshift.py

Fix timezone problem in test create cluster boto3

---

moto/logs/models.py
tests/test_logs/test_logs.py

* Add nextForwardToken and nextBackwardToken to every GetLogEvents response
* Handle end of stream by returning the same token as passed in
Resolves: #2259

Implement pagination support for GetLogEvents

---

moto/batch/models.py
tests/test_batch/test_batch.py

* Add option to call batch submit_job with job definition name only
* Fix bug which causes register_job_definition not to increment job
revision number after a second revision
Resolves: #1976

Add option to call batch submit_job with job definition name only

---

moto/kms/responses.py
tests/test_kms/test_kms.py

regression introduced in #2071 "KMS generate_data_key"

restore KeyId to kms decrypt response

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

- Updated some of the APIs to properly return IAM role descriptions and tags

Fixed some IAM APIs for tagging and role descriptions

---

IMPLEMENTATION_COVERAGE.md
moto/cognitoidentity/exceptions.py
moto/cognitoidentity/models.py
moto/cognitoidentity/responses.py
tests/test_cognitoidentity/test_cognitoidentity.py

This allows it to work with Terraform.

Adds Cognito Identity describe-identity-pool

---

moto/dynamodb2/comparisons.py
tests/test_dynamodb2/test_dynamodb.py

if lhs evaluates to false, rhs must be ignored, but rhs was evaluated then ValueError is occurred.
I fixed this issue same as OR operator.

fix: raises ValueError on conditional and operator

---

moto/s3/responses.py
tests/test_s3/test_s3.py

As mentioned in https://github.com/spulec/moto/pull/2375
<blockquote>
Besides, the <code>MaxKeys</code> limits the sum of CommonPrefixes and Contents other than each. If this change got accepted I will propose that one.
</blockquote>

MaxKeys limits the sum of folders and keys

---

IMPLEMENTATION_COVERAGE.md
moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py

I also implemented list_tags_log_group as it was required to test tag/untag

Issue 2432

---

moto/sts/responses.py

trim invalid newline

---

AUTHORS.md
IMPLEMENTATION_COVERAGE.md
moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses_boto3.py

#2437 Implementing send_templated_email method.

#2437 Implementing send_templated_email

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

Fix for https://github.com/spulec/moto/issues/2445

#2445 - DynamoDB - Add validation for AttributeDefinitions

---

moto/ssm/exceptions.py
moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Fixes #2013
Additionally added validation for ParameterFilters and cleaned up some of the tests.
I think there is still a lot to do, but this should be enough to fix the issue and I didn't want to blow up this PR.

Add ParameterFilters to SSM describe_parameters

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3_lifecycle.py

Found some bugs in my initial S3 lifecycle implementation.  Made some fixes to be consistent with the API behavior.

Made fixes to the S3 Lifecycle mocks to be more consistent with the API

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Fixes #2410
I also renamed the `keys` variable to `key` to be closer to the boto3 parameter naming.

Add evaluation of ConditionExpression to DynamoDB2 delete_item

---

moto/awslambda/models.py
moto/dynamodb2/comparisons.py
moto/dynamodb2/models.py
moto/rds/models.py

Removed some small methods that were never called.
The RDS model was deprecated in favour of RDS2

Remove dead code

---

tests/test_dynamodb2/test_dynamodb.py

Fixes #2384 
Implementation by and all credits to @johnlpuc163 - this PR simply adds a test case to his PR: https://github.com/spulec/moto/pull/2167

DynamoDB - Fixes query sorting on numerical values

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

Added Exception to describe_container_instances to match aws api

---

IMPLEMENTATION_COVERAGE.md
moto/sns/exceptions.py
moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_topics_boto3.py

I added following methods to SNS
- list_tags_for_resource
- tag_resource
- untag_resource

Add sns tags

---

CONFIG_README.md
moto/config/exceptions.py
moto/config/models.py
moto/config/responses.py
moto/core/models.py
moto/s3/config.py
moto/s3/models.py
tests/test_config/test_config.py
tests/test_s3/test_s3.py

- Need to add support still for batch requests and batch aggregation requests in a future PR

Added initial support for querying AWS Config for S3

---

moto/config/models.py
moto/config/responses.py
tests/test_config/test_config.py

- Support for aggregated and non-aggregated batching
- Currently only implemented for S3

Added AWS Config query batching capabilities

---

moto/dynamodb2/exceptions.py
moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

DynamoDB: Add List index operations

---

IMPLEMENTATION_COVERAGE.md
moto/sqs/exceptions.py
moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

I had to rewrite `sqs.send_message_batch` a bit to be able to handle most errors.
Also fixes #1799
Over time I will also check other functions in the SQS implementation and update the coverage file while doing so.

Add sqs error handling

---

moto/ec2/utils.py

fix deprication warning invalid escape sequence

---

IMPLEMENTATION_COVERAGE.md
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Added an additional test for delete_user as well, as that was missing

Feature - [IAM] Delete Policy

---

IMPLEMENTATION_COVERAGE.md
moto/iam/exceptions.py
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Add iam open id connect provider

---

moto/s3/responses.py
tests/test_s3/test_s3.py

s3 list_object: return the NextMarker info if it's truncated

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

Hi, I've done some refactoring to the if/else/for hell in the DynamoDB update-method. (Think I'm allowed to call it that.. considering I've contributed to it as well :) )
Major changes:
- Internal representation is now nested DynamoTypes.
Before, only the toplevel was a DynamoType:
```
DynamoType('M', {'foo': 'bar', 'foo2': ['bar2']
```
and is now
```
DynamoType('M', {'foo': DynamoType('S': 'bar'), 'foo2': DynamoType('L', [DynamoType('S', 'bar2')])})
```
- Updating nested items is now the responsibility of the (DynamoType) item itself, rather than inside the update-method
- Thanks to the new DynamoType structure, updates uses recursion rather than a for-loop.
IMHO, this is a lot more readable/understandable now.
LMKWYT - open to suggestions

Refactor DynamoDB update expressions

---

moto/__init__.py
moto/athena/__init__.py
moto/athena/exceptions.py
moto/athena/models.py
moto/athena/responses.py
moto/athena/urls.py
moto/athena/utils.py
moto/backends.py
tests/test_athena/test_athena.py

This implements create_work_group() and list_work_groups()

Athena - implementing first two endpoints

---

IMPLEMENTATION_COVERAGE.md
scripts/implementation_coverage.py

95a82671
Updating implementation coverage

b582afd3 Fixing implementation_coverage script

---

moto/s3/models.py
tests/test_s3/test_s3.py

Fixed an exception getting an S3 bucket policy via AWS Config and added corresponding unit tests.

Fixed a bug with S3 bucket policies for AWS Config

---

moto/logs/models.py
tests/test_logs/test_logs.py

add NotImplementedError when filter_pattern is given to filter_log_events

---

moto/config/models.py
moto/s3/config.py
moto/s3/models.py
tests/test_config/test_config.py
tests/test_s3/test_s3.py

- Fixed some log bugs in the Config querying APIs
- Fixed an issue with S3 ACLs when described from Config (it's actually a double-wrapped JSON)

Fixed bugs in AWS Config Querying

---

IMPLEMENTATION_COVERAGE.md
moto/core/responses.py
moto/sqs/exceptions.py
moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

I had to adjust `core.responses._get_multi_param` for correctly adding empty strings to the result list.
I moved most function logic from `response.py` to `models.py` so it can be detected by `implementation_coverage.py` Script.
Also fixes #457

Refactor sqs

---

.travis.yml
moto/__init__.py
moto/cloudwatch/responses.py
moto/compat.py
moto/core/__init__.py
moto/dynamodb2/comparisons.py
moto/ec2/models.py
moto/ecr/models.py
moto/ecs/models.py
moto/iotdata/models.py
moto/rds2/models.py
moto/resourcegroupstaggingapi/models.py
moto/ssm/models.py
moto/swf/models/__init__.py
requirements-dev.txt
scripts/scaffold.py
tests/test_ec2/test_vpcs.py
tox.ini

Enable tests on Python 3.8 and fix them.

Python 3.8 support

---

IMPLEMENTATION_COVERAGE.md
moto/iam/exceptions.py
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Add iam account password policy

---

docs/_build/html/_sources/index.rst.txt
file.tmp
moto/__init__.py
moto/backends.py
moto/datasync/__init__.py
moto/datasync/exceptions.py
moto/datasync/models.py
moto/datasync/responses.py
moto/datasync/urls.py
moto/sqs/responses.py
setup.cfg
tests/test_datasync/test_datasync.py
tests/test_sqs/test_sqs.py

Added mocks and tests for AWS DataSync

Added mocks for AWS DataSync #2526

---

moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_subscriptions_boto3.py

Fix sns.subscribe validation for sms numbers

---

CHANGELOG.md

Attempt at updating the ChangeLog.
I've gone through all PRs starting at https://github.com/spulec/moto/pull/2305 until now, as I believe that's the first PR after 1.3.13 was released.
I've took some artistic liberty with the format to account for the mere amount of updates - hope that's acceptable :)

Change log next version

---

.travis.yml
moto/datasync/models.py
moto/datasync/responses.py
tests/test_datasync/test_datasync.py

Some enhancements to DataSync code:
Added task metadata
Added update_task mock
Also changed Travis.yml so that lint checks are done before the build.
This (should) speed up CI/CD by failing the Travis build if linting is not correct

Datasync improvements #2526

---

moto/ec2/models.py
moto/ec2/responses/elastic_network_interfaces.py
moto/ec2/responses/subnets.py
tests/test_ec2/test_subnets.py

Fixes #2002 
Builds on the work done by @alidonmez in PR https://github.com/spulec/moto/pull/2009
Available IP count now takes the ENIs attached to the subnet into account, as requested by @terrycain 
Also added a test to verify various combinations of CIDR ranges, subnets and reserved IP addresses

Fix available ip addresses subnets

---

IMPLEMENTATION_COVERAGE.md
moto/ec2/models.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_vpcs.py

Update to https://github.com/spulec/moto/pull/2404, didn't want to step over his branch

Adds basic implementations for vpc-classic-link and vpc-classic-link-dns-support - Redo

---

moto/sns/responses.py
tests/test_sns/test_publishing_boto3.py

Fix sns.publish with number type and 0 value

---

moto/batch/models.py
moto/packages/httpretty/core.py
moto/server.py
moto/ses/models.py
moto/sns/models.py
moto/sqs/models.py
moto/swf/models/workflow_execution.py

Found some typos in comments across the code base and fixed them.

Fix some typos

---

IMPLEMENTATION_COVERAGE.md
moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

I'm not really sure, if this are the account default quotas. At least in our accounts they are all the same.
Fixes #882

Add iam.get_account_summary

---

IMPLEMENTATION_COVERAGE.md
moto/organizations/exceptions.py
moto/organizations/models.py
moto/organizations/responses.py
tests/test_dynamodbstreams/test_dynamodbstreams.py
tests/test_organizations/test_organizations_boto3.py

Add organizations tags

---

moto/iot/models.py
tests/test_iot/test_iot.py

iot describe_thing_group metadata implementation

---

moto/secretsmanager/models.py
moto/secretsmanager/utils.py
tests/test_secretsmanager/test_secretsmanager.py

Fixing https://github.com/spulec/moto/issues/2593

fixing fetch secret manager via arn 

---

moto/awslambda/models.py
tests/test_awslambda/test_lambda_cloudformation.py

Add CF update/delete methods for Lambda

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py

Fix ec2.revoke_security_group_egress for IpProtocol -1

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

The list_append operation was already supported - this PR adds the option to use the list_append on a nested list, i.e. a list inside a map.

Dynamodb: nested list_append

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
tests/test_cloudwatch/test_cloudwatch.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Fixes #2010 
Also fixes the issue that 'test_cloudwatch_boto3.py' never ran in tests.
This is because it was marked as executable (https://stackoverflow.com/a/1579787) - I've chowned it as appropriate and fixed a time-format issue

CloudWatch - Implement list_metrics pagination

---

moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_server.py

Fixing https://github.com/spulec/moto/issues/2600

adding get policy endpoint

---

IMPLEMENTATION_COVERAGE.md
moto/core/utils.py
moto/s3/exceptions.py
moto/s3/models.py
moto/s3/responses.py
tests/test_core/test_utils.py
tests/test_s3/test_s3.py

Implemented the S3 Public Access Block feature.
Also added support for AWS Config querying of this feature.

Implemented S3 Public Access Block

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

FIX handling duplicated api keys values on api gateway
Closes: #2537

api gateway handle duplicate api key values

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Adds NextToken to response and paginates parameters to the AWS default max results of 10

Add Pagination to ssm:get_parameters_by_path. Closes #1864

---

moto/ec2/models.py
moto/ec2/responses/route_tables.py
tests/test_ec2/test_route_tables.py

Add support for NatGatewayId parameter to create_route and to describe_route_tables response.
Resolves: #2496

Add nat_gateway_id to route and describe_route_tables

---

moto/batch/models.py

Derive image, command, environment, volumes, and the privileged flag
from job definition and container overrides.
Pass them to Docker daemon running the container.

Batch: derive and pass container params to Docker

---

requirements-dev.txt

Pinned coverage to fix XRay tests.

---

IMPLEMENTATION_COVERAGE.md
moto/__init__.py
moto/backends.py
moto/codepipeline/__init__.py
moto/codepipeline/exceptions.py
moto/codepipeline/models.py
moto/codepipeline/responses.py
moto/codepipeline/urls.py
tests/test_codepipeline/test_codepipeline.py

I also updated the implementation coverage and due to the reInvent there are a lot of changes.
I actually wanted to implement the the tag endpoints, but I think it is better to do it in a second PR :)

CodePipeline - implement CRUD endpoints

---

IMPLEMENTATION_COVERAGE.md
moto/__init__.py
moto/backends.py
moto/ec2/urls.py
moto/ec2_instance_connect/__init__.py
moto/ec2_instance_connect/models.py
moto/ec2_instance_connect/responses.py
moto/ec2_instance_connect/urls.py
tests/test_ec2_instance_connect/test_ec2_instance_connect_boto3.py

resolving #2637  by adding support for ec2-instance-connect
@spulec would appreciate some review. thanks!

Resolves #2637  added send_ssh_public_key

---

IMPLEMENTATION_COVERAGE.md
moto/codepipeline/exceptions.py
moto/codepipeline/models.py
moto/codepipeline/responses.py
tests/test_codepipeline/test_codepipeline.py

Add codepipeline tags

---

moto/sns/models.py
tests/test_sns/test_subscriptions.py
tests/test_sns/test_subscriptions_boto3.py

I checked the real behavior of the `delete_topic` function and it doesn't delete any subscriptions.
Fixes #2645

Fix sns unsubscribe & delete_topic behavior

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

Store 'networkMode' in ECS Task Definitions instead of just throwing it away

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb.py

DynamoDB - ListAppend should also work when adding maps to a list

---

moto/awslambda/models.py

awslambda: explicitly specify json-file log driver

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
tests/test_apigateway/test_apigateway.py

Fix this regression: https://github.com/localstack/localstack/issues/1940

Support greedy resource path in API Gateway

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

throw ValidationError on non existing stack

---

moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

- Fixed an issue where Lambda invokes via an ARN was hitting real AWS.

Fixed issue with Lambda invoke via ARN

---

moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Add 'Filter' parameter for cognito-idp function 'list_users()'

---

moto/organizations/exceptions.py
moto/organizations/models.py
moto/organizations/responses.py
tests/test_organizations/test_organizations_boto3.py

This just adds implementation for the UpdateOrganizationalUnit to the organizations API mock. I also included raising duplicate exception when appropriate.

Add update organizational unit endpoint

---

moto/cognitoidp/models.py
tests/test_cognitoidp/test_cognitoidp.py

Bug: Arn missing from cognito user pool model and response

---

.travis.yml
README.md
moto/config/models.py
moto/core/models.py
moto/s3/config.py
moto/s3/exceptions.py
moto/s3/models.py
moto/s3/responses.py
moto/s3/urls.py
tests/test_awslambda/test_lambda.py
tests/test_core/test_server.py
tests/test_s3/test_s3.py

- Also added AWS Config listing and fetching support

Implemented S3 Account-level public access block.

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Support x-amz-tagging-directive in s3 copy_object

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

MessageAction for cognito admin_create_user is now handled

---

moto/route53/models.py
tests/test_route53/test_route53.py

Support GeoLocation and Failover on Route 53

---

moto/config/exceptions.py
moto/config/models.py
moto/config/responses.py
tests/test_config/test_config.py

Feature: Add test mode support for Config PutEvaluations

---

moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr_boto3.py

Enhancement: Adding support to EbsConfiguration on configuration of Instance Groups for an EMR Endpoint

---

setup.py

requests 2.23.0 allows idna<3 [1]
[1] psf/requests@c46f55b

Loosen idna requirement

---

moto/dynamodb2/models.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

DynamoDB - Improve error handling for put_item without keys

---

IMPLEMENTATION_COVERAGE.md
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

Implementation by @cm-iwata - I've just taken his PR and rebased it
Supercedes #2017 
Removed an error condition that's not specified in the docs, and updated the max items to 25 (again as per the docs)

Feature - DynamoDB: transact_get_items

---

moto/batch/models.py
tests/test_batch/test_batch.py

Fixes an NPE, as container_overrides is an optional argument
Adds a docker-tag for all tests - without tag, it will try to download all versions (see https://github.com/docker/docker-py/issues/2257#issuecomment-557678099)
Supercedes #2203 
Fixes #2201 thanks to @mztechins
Fixes #2777 by always setting the self.log_stream_name
All of the above fixes the Batch-tests, so I dropped the @expected_failure around them

Batch - various fixes

---

moto/dynamodb2/models.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py

DynamoDB - Add status to Global Indexes

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Fixes #2773 
Most of the work taken from the PR from @saadgit : #1310

Cloudformation - Stack creation time

---

moto/ses/models.py
tests/test_ses/test_ses_boto3.py

SES - Parse email address on verification

---

moto/cloudformation/parsing.py
moto/cloudwatch/models.py
moto/logs/models.py
moto/s3/utils.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Fixes #2255 
Basic implementation for the specific use case in the ticket - suggestions on other use cases that we can support are welcome
Also fixed the CW implementation to create LogGroups, so that log groups are actually created in the backend

CloudFormation - Add Support for FN:Transform and AWS:Include

---

moto/sns/models.py
tests/test_sns/test_publishing_boto3.py

Fix missing MessageAttributes when using RawMessageDelivery

---

moto/cloudformation/parsing.py
moto/events/models.py
moto/events/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_events/test_events.py

@bblommers , related with our ealier discussion in #2831.
I'm not quite sure about the cloudformation tests. Any tips to improve or create new ones ?
I'm also not quite sure about using `resource_name` during stack creation but I think it's enough for now.

Cloudformation support for Events::Rule

---

moto/elbv2/models.py
moto/events/models.py
moto/packages/httpretty/http.py
moto/secretsmanager/utils.py

Similar to https://github.com/spulec/moto/pull/2811

Fix some 'DeprecationWarning: invalid escape sequence' warnings and use str.format for string interpolation.

---

moto/cloudwatch/models.py
moto/events/models.py
moto/logs/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_events/test_events.py
tests/test_logs/test_logs.py

Hi @bblommers , this PR is related with our latest discussion in #2831. 
You may see I'd changed some elements in `logs` before I implented the change for `events`. That's because the cloudformation test for the rule was failing due the lack of value for `retentionInDays`. 
Sorry to implement both of them in a single PR. Thanks and hope it's ok :).

CloudFormation support for events

---

moto/dynamodbstreams/models.py
tests/test_dynamodbstreams/test_dynamodbstreams.py

DynamodBStreams get_records gets JSON errors when processing complex types

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
tests/test_apigateway/test_apigateway.py

Adding functionalities aws apigateway create domain name,get domain names,get domain name.

Adding functionalities aws apigateway create domain name,get domain names,get domain name

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

Also handle standby instances in other relevant actions.

Implement enter_standby, exit_standby and terminate_instance_in_auto_scaling_group

---

moto/awslambda/responses.py

@bblommers this addresses the issue in #2704

awslambda: Do not assume X-Amz-Invocation-Type is set

---

moto/iot/exceptions.py
moto/iot/models.py
tests/test_iot/test_iot.py

Added existence check of target thing to IoT ListThingPrincipals

---

moto/s3/responses.py
tests/test_s3/test_s3.py

and add support for success_action_redirect.
Based on https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html
Posts should default to `204`.
Also, add support for setting a `success_action_redirect` on

set default status for s3 posts and add success_action_redirect support

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

DynamoDB - Allow case insensitive AND in KeyConditionExpression

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

CloudWatch - Initial get-metric-data implementation

---

moto/cognitoidentity/utils.py
tests/test_cognitoidentity/test_cognitoidentity.py
tests/test_cognitoidentity/test_server.py

CognitoIdentity - Fix Format of Identity ID

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Handle VersionId in S3:delete_objects

---

moto/cloudwatch/responses.py
moto/s3/models.py
tests/test_cloudwatch/test_cloudwatch.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Fixed a regression in CloudWatch.
Also fixes an unmocking issue related to a recent CloudWatch change.
@bblommers FYI ^^

Fixed a regression with CloudWatch

---

moto/__init__.py
moto/backends.py
moto/cloudformation/utils.py
moto/core/models.py
moto/core/responses.py
moto/ec2/utils.py
moto/ec2_instance_connect/models.py
moto/iam/models.py
moto/rds2/models.py
moto/server.py

This speeds up import time from ~5.4s to 0.2s on my machine.

Import time reduction

---

moto/ec2/models.py

https://github.com/boto/botocore/commit/f54c9316f2c98918f92c1381d4c39bf6c18b6f9b#diff-9dfab05d4ba739e097a193e8b5fa61caR43
similar to https://github.com/spulec/moto/pull/2917
AWS regions are on a roll .... ;-)

Add eu-south-1

---

moto/s3/models.py
requirements-dev.txt
setup.py

relax version pins in setup.py for non-Py2 users

---

moto/core/responses.py
moto/iam/access_control.py

Breaks importing backend.
See 
https://github.com/spulec/moto/pull/2697#issuecomment-621300975
Reverts spulec/moto#2697
@spulec Would you mind reviewing this?

Circular import error

---

moto/iot/models.py
tests/test_iot/test_iot.py

Added exception for deleting a thing_group which has childs.

---

tests/test_dynamodb2/test_dynamodb.py

Fixes #1822
Fixes #2860
Adds tests to verify that the UpdateExpression: set x = x + 1 works as expected.
Actual work was done by @pvbouwel 
Supercedes PR #2896, which had some weird merge conflicts

DynamoDB - Implement atomic counter

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

https://github.com/localstack/localstack/issues/1658
Fix SQS send_message_batch empty array Exception handling

Fix SQS send_message_batch empty array Exception handling

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

I'm trying to add additional information `placementConstraints` into task definition mentioned in #2943 . Any advice would be appreciated.

ECS: add placement constraints

---

moto/ses/exceptions.py
moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses.py
tests/test_ses/test_ses_boto3.py

https://github.com/localstack/localstack/issues/909
Enhancement Adding SES get_send_statistics,create_configuration_set functions.

SES Enhancement Adding  get_send_statistics,create_configuration_set functions.

---

moto/redshift/exceptions.py
moto/redshift/models.py
tests/test_redshift/test_redshift.py

Add `Redshift.ClusterAlreadyExists` Error

---

moto/ses/responses.py
tests/test_ses/test_ses.py

@bblommers  Can you please merge this.A small change in response of get send statistics.

SES get send statistics response modification

---

moto/dynamodb2/models/__init__.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_ssm/test_ssm_boto3.py

Implements the continuous backups methods for DynamoDB. Solves a part of the issue #2955 
And I somehow added a print statement in my last PR... shame one me!

Add dynamodb continuous backups

---

IMPLEMENTATION_COVERAGE.md

Forgot to check off the API function, but now it is implemented! Might as well get the credit for it.

Check off assume_role_with_saml since it is implemented now.

---

moto/autoscaling/models.py
tests/test_autoscaling/test_autoscaling.py

Fixed a bug where the ELBs were not getting updated with the correct instances for the ASG.

Always call update  of LBs for ASG changes

---

moto/s3/exceptions.py
moto/s3/models.py
tests/test_s3/test_s3.py

Fix s3 Added Error handling in case of invalid uploadID
https://github.com/localstack/localstack/issues/2401

Fix s3 Added Error handling in case of invalid uploadID

---

moto/managedblockchain/exceptions.py
moto/managedblockchain/models.py
moto/managedblockchain/responses.py
moto/managedblockchain/urls.py
moto/managedblockchain/utils.py
tests/test_managedblockchain/__init__.py
tests/test_managedblockchain/helpers.py
tests/test_managedblockchain/test_managedblockchain_invitations.py
tests/test_managedblockchain/test_managedblockchain_members.py
tests/test_managedblockchain/test_managedblockchain_networks.py
tests/test_managedblockchain/test_managedblockchain_proposals.py
tests/test_managedblockchain/test_managedblockchain_proposalvotes.py
tests/test_managedblockchain/test_managedblockchain_propposals.py

Most functions complete - will send the rest in another PR

Managedblockchain member additions

---

moto/ses/models.py
tests/test_ses/test_ses_boto3.py

SES - Validate domain before sending raw email

---

moto/managedblockchain/exceptions.py
moto/managedblockchain/models.py
moto/managedblockchain/responses.py
moto/managedblockchain/urls.py
moto/managedblockchain/utils.py
tests/test_managedblockchain/helpers.py
tests/test_managedblockchain/test_managedblockchain_invitations.py
tests/test_managedblockchain/test_managedblockchain_members.py
tests/test_managedblockchain/test_managedblockchain_networks.py
tests/test_managedblockchain/test_managedblockchain_nodes.py
tests/test_managedblockchain/test_managedblockchain_proposals.py
tests/test_managedblockchain/test_managedblockchain_proposalvotes.py

Completes all actions for managedblockchain

Added node actions and other fixes

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

implemented s3 default encryption methods

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

Implemented IAM delete_instance_profile

---

moto/cloudwatch/models.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

https://github.com/localstack/localstack/issues/2447
@bblommers  Need your help in getting this small PR merged.

Fix: Cloudwatch delete Alarm status code handling on invalid alarm name

---

moto/secretsmanager/models.py
tests/test_secretsmanager/test_secretsmanager.py

https://github.com/localstack/localstack/issues/2429
@bblommers  Need your help in getting this small change merged

Fix: SecretsManager Added VersionIdsToStages key in describe_secret function

---

moto/events/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Rule's cloudformation support for updates

---

moto/cloudformation/parsing.py
moto/events/models.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Cloudformation - EventBus support

---

moto/athena/models.py
moto/athena/responses.py
tests/test_athena/test_athena.py

Implemented Athena create_named_query, get_named_query (#1524)

---

IMPLEMENTATION_COVERAGE.md
moto/awslambda/models.py
moto/cloudformation/parsing.py
moto/cloudformation/responses.py
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Moves/renames some S3 methods to ensure that the coverage script picks them up - no logic changes.

Improve implementation coverage

---

moto/ec2/models.py
tests/test_ec2/test_route_tables.py

Enhancement: EC2 added create route with networkInterfaceId
https://github.com/localstack/localstack/issues/2530

Enhancement: EC2 added create route with networkInterfaceId

---

moto/awslambda/models.py
moto/dynamodb2/models/__init__.py
tests/test_awslambda/test_lambda.py
tests/test_awslambda/test_lambda_cloudformation.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

Fixes #3044. Did some refactoring to improve readability.
It would be great to hear some tips about these [lines](https://github.com/spulec/moto/pull/3045/files#diff-2df06bdd95e3c78b9335da9f260a3472R650-R653)

Cloudformation support for EventSourceMapping

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Fixes #1954 
Based on work by @grahamlyons in #1956, which can be closed if this PR is approved

CloudFormation - Check stack name in use

---

moto/ec2/responses/amis.py
tests/test_ec2/test_amis.py

EC2 : Fix - modified volume type in ec2 describe images.
https://github.com/localstack/localstack/issues/2551

EC2 : Fix - modified volume type in ec2 describe images.

---

moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

This PR fixes a bug that I introduced during https://github.com/spulec/moto/pull/2999

Improve parsing of string values that represents booleans during block device mapping construction

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_validate.py

Added as boto supports both TemplateBody and TemplateUrl
* Adds TemplateURL as a validate_template option
* Adds a test to validate this

Add support for template urls in cfn validation

---

moto/ssm/exceptions.py
moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_docs.py
tests/test_ssm/test_templates/good.yaml

Implemented some of the AWS SSM document API calls (Get, Delete, Create, Update, Describe, Update Default Version, and List).

SSM documents

---

IMPLEMENTATION_COVERAGE.md
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

S3: Delete Object Tagging

---

moto/rds/exceptions.py
moto/rds/models.py

- Duplicated CF exception in RDS to prevent circular imports.

Fixed circular import with RDS and CF

---

moto/ec2/responses/vpc_peering_connections.py
tests/test_ec2/test_vpc_peering.py

Fix: Ec2 - add VPCPeeringConnections region response support.

Fix: Ec2 - add VPCPeeringConnections region response support.

---

moto/awslambda/models.py
moto/ec2/models.py
moto/ec2/responses/route_tables.py
moto/ec2/utils.py
tests/test_ec2/test_route_tables.py

Fix: Ec2 - add destinationIpv6CIDR support.
https://github.com/localstack/localstack/issues/2651

Fix: Ec2 - add destinationIpv6CIDR support.

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Fix: CloudFormation support status filter in list stacks
https://github.com/localstack/localstack/issues/2698

Fix: CloudFormation support status filter in list stacks

---

moto/organizations/exceptions.py
moto/organizations/models.py
moto/organizations/responses.py
tests/test_organizations/test_organizations_boto3.py

I added a link, where it is possible to find the Service Principals, which support AWS Organizations, but I couldn't find any API endpoint to query it, that's why I added the list in the class.

Organizations - implement AWS Service Access functionality

---

moto/batch/utils.py
tests/test_batch/test_cloudformation.py

Make batch.utils.lowercase_first_key() recursive

---

moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

This pull request will fix #3131 
Fix  delete_api_key response status code to 202

fix #3131 fix API Gateway:delete_api_key return wrong status code

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

fix #3133 
Cognito Identity Provider : create_user_pool_client `GenerateSecret=True` doesn't work

fix #3133 Cognito Identity Provider : create_user_pool_client `GenerateSecret=True` doesn't work

---

moto/cloudwatch/responses.py
tests/test_cloudwatch/test_cloudwatch.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Fix : Added implementation for CloudWatch Describe Metric for Alarm
https://github.com/localstack/localstack/issues/2707

Fix : Added implementation for CloudWatch Describe Metric for Alarm

---

moto/ec2/utils.py
tests/test_ec2/test_instances.py

Fix : EC2 - Added ownerId filter for describe instances
https://github.com/localstack/localstack/issues/2646

Fix : EC2 - Added ownerId filter for describe instances

---

moto/cloudformation/models.py
moto/dynamodb2/models/__init__.py
tests/test_cloudformation/test_cloudformation_stack_crud.py

Fix :  cloudFormation dynamodb : delete resource on delete stack
https://github.com/localstack/localstack/issues/2699
https://github.com/localstack/localstack/issues/2697

Fix :  cloudFormation dynamodb : delete resource on delete stack

---

moto/sagemaker/models.py
moto/sagemaker/responses.py
moto/sagemaker/urls.py
tests/test_sagemaker/test_sagemaker_endpoint.py
tests/test_sagemaker/test_sagemaker_training.py

Basic Support for Endpoints, EndpointConfigs and TrainingJobs

---

IMPLEMENTATION_COVERAGE.md
moto/cognitoidp/exceptions.py
moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Implements cognito-idp create_resource_server.

Add basic implement for cognito-idp create_resource_server

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Adding MessageGroupId and MessageDeduplicationId when sent from batch (#3101)

SQS messages don't contain MessageGroupId and MessageDeduplicationId when sent from batch #3101

---

moto/ec2/models.py
moto/ec2/responses/amis.py
tests/test_ec2/test_amis.py

* Implemented mock function for `ec2.register_image()`.
* Added test for new function.
https://github.com/spulec/moto/issues/3176

Implement ec2.register_image()

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

ECS - UpdateService - Allow service ARN to be passed in

---

moto/awslambda/models.py

Fixes #3150 
Not sure how to add a unit test for this, if that's at all possible - open to suggestions.
The scripts in the linked issue now returns "error running docker: FileNotFound" as the Lambda-payload, instead of throwing an AttributeError.

AWS Lambda - Verify Docker is running when executing a Function

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

CF : Added support for get template summary

CF : Added support for get template summary

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py

FIX : IAM - Added support for pathPrefix in list_users_function
https://github.com/localstack/localstack/issues/2767

FIX : IAM - Added support for pathPrefix in list_users_function

---

moto/sqs/exceptions.py
moto/sqs/models.py
moto/sqs/responses.py
moto/sqs/utils.py
tests/test_sqs/test_sqs.py

Issue fixed:
https://github.com/localstack/localstack/issues/2731

Fix : SQS - Added support for attribute labels for send_message function

---

moto/ssm/models.py
tests/test_ssm/test_ssm_boto3.py

- Add logic filter by parameter name, version or labels in get_parameter function
- Add integration tests
Issues fixed:
- https://github.com/spulec/moto/issues/1638
- https://github.com/localstack/localstack/issues/2726

Enhance function get_parameter by parameter name, version or labels

---

moto/resourcegroups/urls.py

With the new boto3 version the handling for resource groups changed.

Fix resource groups tests

---

moto/organizations/exceptions.py
moto/organizations/models.py
moto/organizations/responses.py
tests/test_organizations/test_organizations_boto3.py

I tried my best to mimic AWS behaviour, but it definitely feels a bit inconsistent. I also changed some of the RESTErrors to dedicated Exceptions.

Organizations - implement Delegated Administrator functionality

---

moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_amis.py
tests/test_ec2/test_elastic_block_store.py

* Modernize snapshot attribute testing.
* Implement UserId parameter for snapshot attributes.
* Add tests for UserId.
* Implements https://github.com/spulec/moto/issues/3178

Implement UserIds for Snapshot Attributes

---

moto/organizations/exceptions.py
moto/organizations/models.py
moto/organizations/responses.py
moto/organizations/utils.py
tests/test_organizations/organizations_test_utils.py
tests/test_organizations/test_organizations_boto3.py

I tried my best to also add support for AISERVICES_OPT_OUT_POLICY policy.

Organizations - implement Policy Type functionality

---

moto/cloudformation/parsing.py
moto/ec2/models.py
moto/ec2/responses/security_groups.py
tests/test_ec2/test_security_groups.py

Fix:EC2-authorize_security_group_ingress- add description to IP-Ranges
https://github.com/localstack/localstack/issues/2775

Fix:EC2-authorize_security_group_ingress- add description to IP-Ranges

---

IMPLEMENTATION_COVERAGE.md
moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py
tests/test_cloudformation/test_cloudformation_stack_integration.py

Related with #3067. Still **missing** implementation for provisioned concurrency.

Lambda reserved concurrency

---

IMPLEMENTATION_COVERAGE.md
moto/autoscaling/exceptions.py
moto/autoscaling/models.py
moto/autoscaling/responses.py
moto/core/responses.py
moto/ec2/models.py
tests/test_autoscaling/test_autoscaling.py
tests/test_autoscaling/test_cloudformation.py

Add the ability to use Launch Templates within Auto Scaling Groups.

Add support for Launch Templates in Auto Scaling Groups

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Fix:SQS:Added Non existent queue name in ERROR RESPONSE
https://github.com/localstack/localstack/issues/2878

Fix:SQS:Added Non existent queue name in ERROR RESPONSE

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

refs #3138 
First time working with `moto`. Is this the right approach for a fix? Let me know and I can apply it to `ecs.describe_service` and write tests.

include=["TAGS"] for describe_task_definition

---

moto/sqs/models.py
moto/sqs/responses.py
tests/test_sqs/test_sqs.py

Fix:sqs get-queue-attributes response template
https://github.com/localstack/localstack/issues/2857

Fix:sqs get-queue-attributes response template

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Fix:s3 Presign Put Request with File upload
https://github.com/localstack/localstack/issues/2837

Fix:s3 Presign Put Request with File upload

---

CONTRIBUTING.md

Add introduction of using scaffold.py. That can automatically generate template code of new services and method of existing services.

Add introduction of using scaffold.py

---

tests/test_ec2/test_instances.py

Similar to https://github.com/spulec/moto/pull/1854

Fix deprecation due to base64.decodestring

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Fix:s3 Presign Post with object acl
https://github.com/localstack/localstack/issues/2407

Fix:s3 Presign Post with object acl

---

Makefile
moto/__init__.py
moto/backends.py
moto/kinesisvideo/responses.py
moto/kinesisvideoarchivedmedia/__init__.py
moto/kinesisvideoarchivedmedia/exceptions.py
moto/kinesisvideoarchivedmedia/models.py
moto/kinesisvideoarchivedmedia/responses.py
moto/kinesisvideoarchivedmedia/urls.py
tests/test_kinesisvideoarchivedmedia/test_kinesisvideoarchivedmedia.py
tests/test_kinesisvideoarchivedmedia/test_server.py

Added basic operations of kinesisvideoarchivedmedia
- `get_hls_streaming_session_url`
- `get_dash_streaming_session_url`
- `get_clip`

Add kinesisvideo archived media

---

CHANGELOG.md

@spulec As requested in #3095 - a list of all changes since the last release. I _think_ I've got everything..

Changelog updates 1.3.15

---

moto/s3/exceptions.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Add If-Match, If-None-Match and If-Unmodified-Since to S3 GET/HEAD

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

This PR fixes issue https://github.com/spulec/moto/issues/3312

Include response headers when deleting objects.

---

moto/server.py
requirements-dev.txt
setup.py
tests/test_s3/test_server.py

Fixes issue https://github.com/spulec/moto/issues/1007
This is required for browser-based uploads to a standalone Moto S3 server during front-end development.

Enable CORS from everywhere using flask-cors.

---

moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

[fix] cognito-idp list_users Filter arg now support spaces

---

moto/applicationautoscaling/models.py
tests/test_applicationautoscaling/test_applicationautoscaling.py
tests/test_s3/test_s3.py

ApplicationAutoscaling: support for all the current various forms of resource_id

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Fix:s3 List Object delimiter in response
https://github.com/localstack/localstack/issues/2859

Fix:s3 List Object response:delimiter 

---

IMPLEMENTATION_COVERAGE.md
moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Fixes: https://github.com/spulec/moto/issues/3327

added cognito idp function admin_set_user_password to the code

---

CONFIG_README.md
moto/config/models.py
moto/core/models.py
moto/iam/config.py
moto/iam/models.py
moto/s3/config.py
tests/test_iam/test_iam.py

I've tried to add some new AWS Config resources. Before I get too far into adding more resources, I want to make sure that my approach is in line with what's in the CONFIG_README.

Config for IAM roles and policies

---

moto/s3/models.py
moto/s3/responses.py

Fixes #3306 
Verified against AWS CLI and the Java SDK
Re-uses solution from #3182

Fix S3 creation date for AWS Java SDK

---

moto/ec2/models.py
moto/ec2/responses/subnets.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_subnets.py
tests/test_ec2/test_vpcs.py

Fix:EC2 Tags in create vpc and create subnet
https://github.com/localstack/localstack/issues/3031

Fix:EC2 Tags in create vpc and create subnet

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/flow_logs.py
moto/ec2/utils.py
tests/test_ec2/test_flow_logs.py
tests/test_ec2/test_flowlogs.py

Hi! 
I'm new to `moto` :) I would like to add support for the VPC Flow Logs. I'm open to and suggestions, let me know if the approach I took fits the rest of the library.

WIP: Introducing VPC Flow Logs

---

moto/sqs/models.py
moto/sqs/responses.py
moto/sqs/utils.py
tests/test_sns/test_publishing_boto3.py
tests/test_sqs/test_sqs.py

Fix:SQS Receive Message (MessageAttributes) in response
https://github.com/localstack/localstack/issues/2965

Fix:SQS Receive Message (MessageAttributes) in response

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

Fixes #3352 
Easy fix and adjusted test.

Add registeredAt to ecs container instance

---

IMPLEMENTATION_COVERAGE.md
moto/ec2/models.py
moto/ec2/responses/flow_logs.py

Hello! Small update here, what do you think about it? I guess the `Unsuccessful` class may look ugly since it's not used anywhere outside the `FlowLogs`, so maybe it's a good idea to remove it.

Updates to FlowLogs and IMPLEMENTATION_COVERAGE

---

moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

The `@freeze_time` decorator was removed because it is not necessary (and was
causing the test to be skipped).
Closes #2940

Add tagging to ec2.CopySnapshot

---

moto/iot/models.py
tests/test_iot/test_iot.py

`iot:DeleteThingGroup` should return success for non-existent groups

---

moto/sqs/exceptions.py
moto/sqs/models.py
tests/test_sqs/test_sqs.py

Add better support for SQS `MaximumMessageSize` attribute

---

moto/resourcegroupstaggingapi/models.py
tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py

Add `ec2.vpc` resource support to Tagging API

---

moto/ecs/models.py
tests/test_ecs/test_ecs_boto3.py

Implement additional filters for `ecs.ListTasks`

---

moto/iam/models.py
moto/iam/responses.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_iam/test_iam.py

I also noticed the regex validation is not performed on PathPrefix but figured that was a wider issue and does not belong in this PR

issue-3379 iam list_roles: implement PathPrefix, MaxItems and Marker

---

moto/s3/models.py
tests/test_s3/test_s3_cloudformation.py

Fix: S3 Bucket does not support attribute type Arn in Fn::GetAtt

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Including Message attributes when ALL is passed

Including Message attributes when ALL is passed

---

moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

FIX:Add secrets Manager Tag resoruce Funtionality
https://github.com/localstack/localstack/issues/3102

FIX:Add secrets Manager Tag resource Funtionality

---

moto/cloudformation/utils.py

CF - Allow multiple cfn-lint API versions

---

moto/ec2/responses/vpn_connections.py
tests/test_ec2/test_vpn_connections.py

Fix: `VpnGatewayId` parameter casing in ec2:CreateVpnConnection request

---

moto/sns/models.py
tests/test_sns/test_subscriptions.py
tests/test_sns/test_subscriptions_boto3.py

Fix: SNS Delete subscriptions on topic deletion 
https://docs.aws.amazon.com/cli/latest/reference/sns/delete-topic.html
https://github.com/localstack/localstack/issues/3152

Fix: SNS Delete subscriptions on topic deletion 

---

moto/applicationautoscaling/models.py
tests/test_applicationautoscaling/test_applicationautoscaling.py

Also adds suspended_state as an updatable attribute for ApplicationAutoScaling::ScalableTarget

Fix update for application autoscaling register target

---

moto/sagemaker/exceptions.py
moto/sagemaker/models.py
moto/sagemaker/responses.py
tests/test_sagemaker/test_sagemaker_notebooks.py

Notebook Lifecycle Config create, describe and delete

---

moto/cloudformation/parsing.py
moto/stepfunctions/models.py
tests/test_stepfunctions/test_stepfunctions.py

Add support for CloudFormation resource `AWS::StepFunctions::StateMachine`

---

moto/ec2/models.py
moto/ec2/responses/internet_gateways.py
moto/ec2/responses/network_acls.py
moto/ec2/responses/route_tables.py
tests/test_ec2/test_internet_gateways.py
tests/test_ec2/test_network_acls.py
tests/test_ec2/test_route_tables.py

Fix:Added Tags for Network-ACL,RouteTable,InternetGateway
https://github.com/localstack/localstack/issues/3193

Fix:Added Tags for Network-ACL,RouteTable,InternetGateway

---

moto/stepfunctions/models.py
moto/stepfunctions/utils.py
tests/test_stepfunctions/test_stepfunctions.py

Add CloudFormation Update support for `AWS::StepFunctions::StateMachine`

---

README.md

Solving Add doc to glue etl #3415

adding docs for athena e glue

---

moto/ssm/models.py
tests/test_ssm/test_ssm_boto3.py

Replace the special-case code to handle Cloud Formation tags with a more
generic implementation that covers all instance tags.
Supersedes #2863
Closes #2862

Add ssm:SendCommand support for instance tag Targets

---

moto/ec2/models.py
moto/ec2/responses/subnets.py
tests/test_ec2/test_subnets.py

* Add response/model/test coverage for filtering by `state`
* Add explicit test case for filtering by `vpc-id`
Closes #801

Improve ec2:DescribeSubnets filtering

---

.gitignore
moto/emr/exceptions.py
moto/emr/models.py
moto/emr/responses.py
requirements-dev.txt
tests/test_emr/test_emr_boto3.py

Added support for EMR Security Configurations and Kerberos Attributes.

---

moto/batch/models.py
tests/test_batch/test_batch.py

The `test_submit_job` in `test_batch.py` kicks off a job, calls `describe_jobs`
in a loop until the job status returned is SUCCEEDED, and then asserts against
the logged events.
The backend code that runs the submitted job does so in a separate thread. If
the job was successful, the job status was being set to SUCCEEDED *before* the
event logs had been written to the logging backend.
As a result, it was possible for the primary thread running the test to detect
that the job was successful immediately after the secondary thread had updated
the job status but before the secondary thread had written the logs to the
logging backend.  Under the right conditions, this could cause the subsequent
logging assertions in the primary thread to fail.
Additionally, the code that collected the logs from …

Fix Race Condition in batch:SubmitJob

---

moto/cloudwatch/models.py
tests/test_cloudwatch/test_cloudwatch_boto3.py

Fix:CloudWatch List metrics with dimensions
https://github.com/localstack/localstack/issues/3222

Fix:CloudWatch List metrics with dimensions

---

moto/redshift/exceptions.py
moto/redshift/models.py
tests/test_redshift/test_redshift.py
tests/test_redshift/test_server.py

I discovered and fixed a number of (minor) Redshift issues while working on an unrelated task.
I took care to separate all these changes into atomic commits, so if you don't squash them it should provide a better experience for anyone using `git blame` down the road.

Redshift improvements

---

tests/test_iam/test_iam_policies.py

Fix: yield tests ignored by pytest runner

---

IMPLEMENTATION_COVERAGE.md

Ref: https://github.com/spulec/moto/search?q=get_caller_identity

Mark sts.get_caller_identity as implemented

---

moto/ses/responses.py
tests/test_ses/test_ses_boto3.py

Fix:SES:Get Template Html part
https://github.com/localstack/localstack/issues/3214

Fix:SES:Get Template Html part

---

moto/ec2/models.py
moto/ec2/responses/elastic_ip_addresses.py
tests/test_ec2/test_elastic_ip_addresses.py

FIX:Ec2:Added:Tags for EIP
https://github.com/localstack/localstack/issues/3228

FIX:Ec2:Added:Tags for EIP

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Fix:Cloudformation descibe stacks special chars
https://github.com/localstack/localstack/issues/3300

Fix:Cloudformation descibe stacks special chars

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_vpcs.py

Fix:Ec2-VPC:Added functionality describe-vpc-endpoint
https://github.com/localstack/localstack/issues/3310

Fix:Ec2-VPC:Added functionality describe-vpc-endpoint

---

moto/glue/responses.py
tests/test_glue/test_datacatalog.py

This change would add support for the Glue `batch_update_partition` method.

Add glue.batch_update_partition

---

moto/ec2/responses/vpcs.py

Fix owner ID in describe-vpc-endpoints response.

---

moto/s3/exceptions.py
moto/s3/responses.py
tests/test_s3/test_s3.py

https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+language%3Ago

Fix: ListObjectsV2 behaving differently than AWS API 

---

moto/sns/models.py
tests/test_sns/test_application.py

As per sample response:
https://docs.aws.amazon.com/sns/latest/api/API_GetEndpointAttributes.html

Enabled SNS endpoint attr must be lowercased

---

moto/ec2/models.py
moto/ec2/responses/nat_gateways.py
tests/test_ec2/test_nat_gateway.py

Fix:Added nat-gateway tags
https://github.com/localstack/localstack/issues/3377

Fix:Added nat-gateway tags

---

moto/awslambda/urls.py
moto/sts/urls.py
tests/test_awslambda/test_lambda.py
tests/test_sts/test_sts.py

Enable AWSLambda and STS mocking for AWS China regions/endpoints

---

moto/glue/models.py
moto/glue/responses.py
tests/test_glue/fixtures/datacatalog.py
tests/test_glue/helpers.py
tests/test_glue/test_datacatalog.py

This potentially fixes #3571 .

Implement full Database object for Glue get_database() - fix for #3571.

---

moto/ec2/models.py
tests/test_ec2/test_security_groups.py
tests/test_ec2/test_security_groups_cloudformation.py

Fixes #3542 
Fixes #1895
Supports SecurityGroupIngress (IP + description) for CloudFormation

CloudFormation - Fix SecurityGroup ingress rules

---

moto/s3/exceptions.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Fixes #2710
Verified against AWS itself

Raise specific error when GetObject is called with unknown VersionId

---

README.md

add mock_stepfunctions to top-level README [fixes 3587]

---

moto/s3/responses.py
tests/test_s3/test_s3.py

addresses https://github.com/localstack/localstack/issues/3433

Sort s3 object versions by last_modified_on in descending order

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

**Added**
**Support for SSE attributes**
- Added headers: `ServerSideEncryption`, `SSEKMSKeyId`, `BucketKeyEnabled`
- Added test cases for headers
**Fix**
- [localstack/issues/3463](https://github.com/localstack/localstack/issues/3463)

added sse support for s3

---

IMPLEMENTATION_COVERAGE.md
moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

Implemented as described in #3609.

Added redshift.get_cluster_credentials

---

moto/sns/models.py
tests/test_sns/test_topics_boto3.py

Fix:SNS Create FIFO Topic
https://github.com/localstack/localstack/issues/3336

Fix:SNS Create FIFO Topic

---

IMPLEMENTATION_COVERAGE.md
moto/ec2/models.py
moto/sts/models.py

Update Implementation Coverage script

---

moto/events/exceptions.py
moto/events/models.py
moto/events/responses.py
tests/test_events/test_events.py
tests/test_events/test_events_cloudformation.py

I also added CloudFormation functionality and hope I did right, first time for me 😄 
I also added a comment regarding nested dict matching for event patterns, which I didn't add yet. I think the PR is already big enough.

Add EventBridge Archive CRUD endpoints

---

moto/iot/models.py
tests/test_iot/test_iot.py

Add arns to iot responses

---

moto/iam/models.py
moto/iam/responses.py
tests/test_iam/test_iam.py
tests/test_iam/test_iam_cloudformation.py

Fixes #3564 
I also added the `TaggingService` to handle the tags for the user. I removed one test because it was a duplicate.

Add tag & untag user

---

moto/applicationautoscaling/models.py
moto/ecs/exceptions.py
moto/ecs/models.py
moto/ecs/responses.py
tests/test_cloudformation/test_cloudformation_depends_on.py
tests/test_ecs/test_ecs_boto3.py

Fixes #2898
I also changed the Account ID to the main one and added a `_get_cluster()` method to centralize the `ClusterNotFoundException`.

Add failures output to ecs.describe_services

---

Makefile
moto/iot/responses.py
moto/iot/urls.py
moto/iotdata/responses.py
moto/iotdata/urls.py
moto/server.py
tests/test_iot/test_server.py
tests/test_iotdata/test_server.py

Fix: IoT does not work in server mode

---

moto/s3/responses.py
tests/test_s3/test_s3.py

- addresses https://github.com/localstack/localstack/issues/3514

Add versionid header in complete multipart if enabled 

---

moto/ses/exceptions.py
moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses_boto3.py

This patch adds the functions test_render_template and update_template so the SES service.
Also adds validation to the function add_template.
Each new function has its corresponding test.
This should close issue localstack/localstack/issues/3466

Functionality added to SES service

---

MANIFEST.in
moto/__init__.py
moto/backends.py
moto/ec2/models.py
moto/support/__init__.py
moto/support/exceptions.py
moto/support/models.py
moto/support/resources/describe_trusted_advisor_checks.json
moto/support/responses.py
moto/support/urls.py
moto/utilities/utils.py
tests/test_support/test_server.py
tests/test_support/test_support.py

Hi,
I noticed in the week there was not one yet so this is a first attempt at the implementation for the support feature.
Currently only returns the call from `describe_trusted_advisor_checks` and as this is just a static response have included it as part of a json.
The contribution page did not say anything about a minimum number of operations to add so I kept it small as this is my first PR to moto. I would like to do more for this module but would like to know what you think of my PR for feedback
Thanks!

support - intial commit to kick off trusted advisor checks

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

Add validation to API Key min length value

---

moto/cognitoidp/models.py
tests/test_cognitoidp/test_cognitoidp.py

Refs https://github.com/spulec/moto/issues/3706

pool domain should always return a domain

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

add tags support to ECS tasks
@bblommers please review.

add tags support to ECS tasks

---

.github/workflows/release.yml

This does nothing at the moment, just using it to verify we can:
- Start a workflow manually
- Pass in a custom variable (such as the version we want to release)

Automate release - Test Github Action

---

IMPLEMENTATION_COVERAGE.md
tox.ini

3730 update api key - doc update

3730 update api key - doc update 

---

moto/events/exceptions.py
moto/events/models.py
moto/events/responses.py
tests/test_events/test_events.py

Added the needed endpoints for the replay functionality. The state is quite often faked, because the real replay had to be done asynchron, which I didn't want to implement. I also implemented the possibility to send events to a Log Group target.

Add eventbridge replay

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Add support for SSM Parameter tags.

Support SSM Parameter tags (put_parameter, describe_parameters)

---

moto/core/utils.py
moto/sqs/models.py
moto/sqs/responses.py
tests/test_core/test_utils.py
tests/test_sqs/test_sqs.py

Fix AttributeNames for sqs.receive_message

---

moto/secretsmanager/models.py
moto/secretsmanager/responses.py
tests/test_secretsmanager/test_secretsmanager.py

Secrets manager untag resource

---

moto/ec2/models.py
moto/ec2/responses/route_tables.py
tests/test_ec2/test_route_tables.py

fix route table association by internet gateway per https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateRouteTable.html

fix route table association by internet gateway

---

docs/docs/server_mode.rst

See: https://github.com/Homebrew/homebrew-core/pull/73903

Document installing Moto with Homebrew

---

setup.py

Set upper bound for dependency decorator (Py2)

---

README.md

document use with unittest

---

moto/iot/models.py
tests/test_iot/test_iot.py

This pull request will fix #3867
Fix iot list_principal_things response list of thingnames.

fix #3867 IoT list_principal_things 

---

moto/emr/models.py
moto/emr/responses.py
moto/swf/models/__init__.py
moto/swf/models/domain.py
tests/test_emr/test_emr_boto3.py
tests/test_swf/models/test_domain.py
tests/test_swf/responses/test_domains.py
tests/test_swf/utils.py

Reference:
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.list_clusters
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/swf.html#SWF.Client.list_domains

EMR and SWF - add arn to response

---

setup.py

fix MarkupSafe and Jinja2 dependency

---

moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

Fix : Remove Invalid request error when response-template is not specified
https://github.com/localstack/localstack/issues/3936

Fix : Remove Invalid request error when response-template is not specified

---

moto/logs/models.py
tests/test_logs/test_logs.py

Modified the pagination for FilterLogEvents to more closely follow
the real AWS behaviour.

`nextToken` value in `logs:describeLogStreams` response

---

moto/logs/models.py

This change allows these object types to appear in the Moto API dashboard

Register classes in `logs/models.py` as models

---

IMPLEMENTATION_COVERAGE.md
docs/index.rst
moto/__init__.py
moto/backends.py
moto/dms/__init__.py
moto/dms/exceptions.py
moto/dms/models.py
moto/dms/responses.py
moto/dms/urls.py
moto/dms/utils.py
tests/test_dms/test_dms.py

Adds basic implementation of DMS task replication methods.

DMS - basic task replication methods implementation

---

IMPLEMENTATION_COVERAGE.md

Hi again, @bblommers, I realized that I forgot to update the coverage document in my last PR. This should fix it.

Update Coverage with MFA Actions

---

moto/resourcegroups/models.py
moto/resourcegroups/responses.py
moto/resourcegroups/urls.py
tests/test_resourcegroups/test_resourcegroups.py

ResourceGroup - Add Support for getGroupConfiguration

ResourceGroup - Add Support for getGroupConfiguration

---

moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_boto3.py

Fix tags for resource in ListTagsForResource
https://github.com/localstack/localstack/issues/4019

Fix tags for resource in ListTagsForResource

---

moto/cloudwatch/models.py
moto/cloudwatch/responses.py
tests/test_cloudwatch/test_cloudwatch.py

Add unit support to cloudwatch get_metric_statistics
https://github.com/localstack/localstack/issues/4027

Add unit support to cloudwatch get_metric_statistics

---

moto/ses/exceptions.py
moto/ses/models.py
tests/test_ses/test_ses_boto3.py

Fix:SES-Added params check in template
https://github.com/localstack/localstack/issues/3664

Fix:SES-Added params check in template

---

moto/resourcegroups/models.py
moto/resourcegroups/responses.py
tests/test_resourcegroups/test_resourcegroups.py

Fix resource group get-group-query & update-query-query

Fix resource group get-group-query & update-query-query

---

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_ec2_integration.py

Add support for KmsKeyId in ec2:RunInstances

---

moto/ec2/models.py
tests/test_ec2/test_instances.py

Add support for tagging Volumes in ec2:RunInstances

---

IMPLEMENTATION_COVERAGE.md
moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

#3061 - update rest API basic implementation

basic implementation of update rest api

---

moto/s3/utils.py
tests/test_s3/test_s3.py

Add dot as a valid s3 metadata key

---

moto/glacier/urls.py
tests/test_glacier/test_glacier_vaults.py

Allow Glacier VaultName to contain period

---

moto/batch/models.py

The initial ordering of the attribute declaration:
```
job_state = FAILED
job_stopped = True
```
Which lead to the race condition like this:
```diff
! Client thread
! job.run()
! describe_jobs()
! No-op, as the jobs are still running
! job = describe_jobs()
! job.status == FAILED
! job.container != None
@@ FAIL -  job.container is only set if the `job_stopped`-attribute is True @@
```
Switching the ordering of the attribute declaration should solve this.

Batch - remove potential race condition

---

moto/s3/models.py
tests/test_s3/test_s3.py

- AWS Config appears to have changed how ACLs are returned
- This PR makes moto's behavior consistent with AWS Config's S3 representation
Fixes #3986

Fixed AWS Config S3 ACL issues

---

moto/organizations/models.py
tests/test_organizations/test_organizations_boto3.py

fixes #3980 
- Adding checking for resource type in tag functions
- Adding TargetNotFoundException when no resource found
- Adding support for tags for root OU, OU and Policies
- Adding tests covering the new code
- Adding test for deletion of a tag

Add Tag support for other resource types then an account

---

moto/events/models.py
moto/events/responses.py
tests/test_events/test_events.py

Added connection API's
https://github.com/localstack/localstack/issues/4065

Fix:Add list connection API's

---

moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py

Fix : Logs - Add start_query functionality
https://github.com/localstack/localstack/issues/4078

Fix : Logs - Add start_query functionality

---

moto/s3/models.py
moto/settings.py
tests/test_s3/test_s3.py

Continuation from: https://github.com/spulec/moto/pull/3994

Env variable for default key buffer size

---

moto/emr/exceptions.py
moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr_boto3.py

Error message verified against real AWS backend.

Disallow termination of protected EMR job flows

---

moto/emr/models.py
tests/test_emr/test_emr_boto3.py

Reference: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-ha-launch.html

Support EMR clusters with multiple master nodes

---

moto/rds2/models.py
moto/secretsmanager/utils.py
moto/ssm/utils.py
tests/test_rds2/test_rds2.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_ssm/test_ssm_boto3.py

Use centralized ACCOUNT_ID

---

moto/s3/exceptions.py
moto/s3/models.py
tests/test_s3/test_s3.py
tests/test_s3/test_s3_multipart.py

Fixes #4018 
Both modified tests have been verified against AWS

Raise NoSuchUpload when listing a non-existing multipart upload

---

moto/dynamodb2/parsing/reserved_keywords.py
moto/utilities/utils.py

Rewrite unnecessary importlib dependency in DynamoDB

---

moto/s3/responses.py
tests/test_s3/test_s3.py
tests/test_s3bucket_path/test_s3bucket_path.py

Fixes #1581
Verified against AWS.

S3 - Dont error when deleting unknown keys

---

IMPLEMENTATION_COVERAGE.md
moto/mediaconnect/models.py
moto/mediaconnect/responses.py
moto/mediaconnect/urls.py
tests/test_mediaconnect/test_mediaconnect.py

The aim of this PR is to add support for:
- add_flow_outputs
- add_flow_vpc_interfaces

Add outputs and vpc interfaces to a mediaconnect flow

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Fixes #1688
Supercedes #1689 - this just adds a few tests to the original PR

CognitoIDP: get_user

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Fixes #3113
Verified test against AWS

S3#list_object_versions - verify prefix argument

---

moto/logs/models.py
tests/test_logs/test_logs.py

Fix error message for missing log stream

---

moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py

AWSLambda - set content-type to app/json

---

moto/ses/models.py
tests/test_ses/test_ses_boto3.py

Verified test case against a real AWS backend.
Fixes #3947

SES domains are case-insensitive

---

moto/sns/models.py
tests/test_sns/test_application_boto3.py

sns#create_platform_endpoint: If token and attributes are the same, return endpoint

---

moto/ec2/models.py
moto/ec2/responses/elastic_network_interfaces.py
tests/test_ec2/test_elastic_network_interfaces.py

Add support for DescribeNetworkInterfaces tag filters

---

moto/applicationautoscaling/models.py
tests/test_applicationautoscaling/test_applicationautoscaling.py

https://github.com/spulec/moto/issues/4053

Bugfix for put_scaling_policy in applicationautoscaling.

---

IMPLEMENTATION_COVERAGE.md
moto/kinesis/models.py
moto/kinesis/responses.py
tests/test_kinesis/test_kinesis.py

Fixes #4067.
This PR aims to add support for the functions `increase_stream_retention_period` and `decrease_stream_retention_period` in Kinesis.

#4067: Add support for kinesis retention hours

---

moto/eks/models.py

Further testing against the actual API shows that the final state of `nextToken` is `None`, not `"null"`.  The meat of the PR is that change on L481.
- Support for Fargate Profiles is being added in a coming PR.  `list_fargate_profiles` will reuse the same logic as `list_clusters` and `list_nodegroups`.  This bug is in the affected overlapping code, so that logic has been moved into a helper method as part of the correction.

Fix EKS list models bug

---

.github/workflows/dependency_test.yml
scripts/dependency_test.sh

Successful test run: 
https://github.com/bblommers/moto/runs/3191640387?check_suite_focus=true

Fix CI Dependency test

---

moto/s3/responses.py

Fixes https://github.com/spulec/moto/issues/4107

Remove leading space from DeleteObject action name

---

CHANGELOG.md
CONTRIBUTING.md
IMPLEMENTATION_COVERAGE.md
setup.py

Dependency test on this branch passes: 
https://github.com/bblommers/moto/actions/runs/1092699414

Prep release 2.2.1

---

IMPLEMENTATION_COVERAGE.md
moto/autoscaling/models.py
moto/autoscaling/responses.py
tests/test_autoscaling/test_autoscaling.py

Add delete_tags to AutoScaling. Closes #4121.

Add autoscaling delete_tags

---

moto/core/responses.py
moto/rds2/models.py
moto/rds2/responses.py

Add support for RDS ModifyDBSubnetGroup - resolves a Terraform test. Test file `terraform-tests.success.txt` not yet update as a few other things are still missing for RDS - going to happen in a future PR. /cc @bblommers Thanks!

Add support for RDS ModifyDBSubnetGroup

---

moto/kms/responses.py
tests/terraform-tests.success.txt

Add support for KMS `UpdateAlias` API (covered by Terraform test case). /cc @bblommers

Add support for KMS update-alias

---

moto/cloudformation/models.py
moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

Resolves #4141 
Thanks for the patience, this PR is ready for review now. Please take a look at the commit message as I've left my rationale there for this bigger than expected change.
Signed-off-by: Kai Xia <kaix+github@fastmail.com>

add stack status in execute_change_set call.

---

moto/ec2/models.py
moto/ec2/responses/route_tables.py
tests/terraform-tests.success.txt

**Updated**
- Fixed account id in subnet and table
**TF test fix**
- TestAccAWSRouteTable_disappears
**Upcoming Test Fixes**
- - TestAccAWSRouteTable_

removed depricated account id

---

moto/events/models.py
tests/test_events/test_events_integration.py

Fix events target for custom event bus

---

moto/ecr/exceptions.py
moto/ecr/models.py
moto/ecr/responses.py
tests/test_ecr/test_ecr_boto3.py

the result from `ecr. describe_image_scan_findings()` is of course totally fake and this implementation is just for completeness and if someone wants to construct some kind of custom code around those methods and needs `moto` to mock those requests 😄

Add ecr image scan

---

moto/ecr/models.py
moto/ecr/responses.py
tests/test_ecr/test_ecr_boto3.py

Support force flag in ecr.delete_repository

---

moto/cognitoidp/models.py
tests/test_cognitoidp/test_cognitoidp.py

**Linked issue:**
https://github.com/spulec/moto/issues/4162
**Test coverage:**
`tests/test_cognitoidp/test_cognitoidp/test_initiate_auth_USER_PASSWORD_AUTH`

Add support for USER_PASSWORD_AUTH auth method (cognito-idp)

---

moto/ec2/models.py
moto/events/models.py
tests/test_ec2/test_prefix_lists.py
tests/test_ec2/test_vpcs.py
tests/test_elbv2/test_elbv2.py
tests/test_events/test_events.py

Also removed the unused `delete_from_cloudformation_json`-methods, as CF directly calls the Model.delete() method instead

Tech debt - improve test coverage EC2/ELBv2/Events

---

moto/ec2/utils.py
tests/test_ec2/test_instances.py

Fix ec2 wildcard tag filters

---

tests/test_s3/test_s3.py
tests/test_s3/test_s3_multipart.py

Add missing default regiono in s3 client

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/egress_only_internet_gateways.py
moto/ec2/utils.py
tests/terraform-tests.success.txt

- Support for egress-only-internet-gateway
- CreateEgressOnlyInternetGateway
- DescribeEgressOnlyInternetGateways
- DeleteEgressOnlyInternetGateway
- TestAccAWSEgressOnlyInternetGateway

added support for egress-only-internet-gateway

---

moto/s3/responses.py
tests/test_s3/test_s3.py

Hi, first of all a bit of background:
- I'm using moto in server mode, to mock AWS in java integration tests
- AWS SDK v2 PutObject failed, due to failing ETag [validation](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L147)
- Upon some debugging, I've found out that java client sends chunked body with [signatures](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html#sigv4-chunked-body-definition), for example executing:
```java
s3Client.putObject(putObjectRequest, RequestBody.fromString("CONTENT"))
```
is on moto side:
`b"7;chunk-signature=bd479c607ec05dd9d570893f74eed76a4b333dfa37ad6446f631ec47dc52e756\r\nCONTENT\r\n0;chunk-signature …

Added handling for V4 signatures in PutObject body

---

CHANGELOG.md
IMPLEMENTATION_COVERAGE.md
moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3.py

Contains refactoring of the S3 logic, by renaming and moving things into the S3Backend, to ensure that our implementation coverage-script picks up all of the implemented methods.
There should be no functional changes.

Prep Release 2.2.4

---

tests/test_ec2/test_egress_only_igw.py

Adds missing unit tests for #4196

EC2 - Add tests for egress_only_internet_gateway

---

moto/config/resources/aws_managed_rules.json
scripts/pull_down_aws_managed_rules.py

Thought `pull_down_aws_managed_rules.py` could have been written a little better, so I made a few corrections.  When the script was rerun for testing purposes, the JSON containing managed rules showed some updates, so these are included as well.

Cleanup pulldown script a bit, update managed rules

---

moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

Support alternate EC2:ModifyInstanceAttribute request syntax

---

moto/dynamodb2/models/__init__.py
moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py

DynamoDB - Describe_Endpoints() method

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

SQS - get_queue_attributes() might not have AttributeNames-parameter

---

moto/logs/exceptions.py
moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py

CloudWatchLogs - Transform assertions into proper exceptions

---

moto/awslambda/models.py
tests/test_awslambda/test_lambda.py

When the Docker service is not running, any async Lambda invocations will fail silently.
This PR adds a log message to the CloudWatch Logs, alerting the user of what's wrong.
Verified this behaviour locally - our tests now fail with this message: `error running docker: Error while fetching server API version: ('Connection aborted.'..`

Improve logs when Docker is not running

---

moto/cloudformation/parsing.py
moto/iam/models.py
moto/iam/responses.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_iam/test_iam_cloudformation.py

IAM - Delete Role/InstanceProfile via CloudFormation

---

.github/workflows/build.yml
CHANGELOG.md
IMPLEMENTATION_COVERAGE.md
moto/s3/models.py
moto/s3/responses.py

Renames some S3-backend methods to ensure they're picked up by the implementation coverage script.
Does not contain any actual logic/changes

Prep release 2.2.6

---

moto/s3/responses.py
tests/test_s3/test_s3_auth.py

S3 - HeadObject should authenticate requests

---

moto/ecr/models.py
moto/kms/models.py
moto/utilities/tagging_service.py
tests/test_utilities/test_tagging_service.py

Got carried away pylinting tagging_service.py while making the additions.

Add validation of tags to TaggingService

---

moto/sagemaker/exceptions.py
moto/sagemaker/models.py
moto/sagemaker/responses.py
requirements-dev.txt
tests/test_sagemaker/test_sagemaker_models.py
tests/test_sagemaker/test_sagemaker_training.py

Added mock implementation of sagemaker list_training_jobs. Tried to follow convention of str.format.
Also added prompt_toolkit to dev requirements.
Any comments appreciated

Implement sagemaker list_training_jobs enhancement (issue #4248)

---

IMPLEMENTATION_COVERAGE.md
moto/transcribe/models.py
moto/transcribe/responses.py
tests/test_transcribe/test_transcribe_boto3.py

Hi 👋.
For #4268 I tried to add some aws-transcribe calls, following the Job-Progress-Approach created by [https://github.com/jweite](https://github.com/jweite) in ([https://github.com/spulec/moto/pull/3299](https://github.com/spulec/moto/pull/3299)). Hope it's ok for moto-standards. 
Let me know if improvement can be made.
Content:
- `start-`, `get-`, `list-`  and `delete-transcription-jobs`
- `create-`, `get-`, `list-`  and `delete-vocabularies`

A small bit of Transcribe support 

---

moto/core/exceptions.py
tests/test_ec2/test_amis.py
tests/test_ec2/test_elastic_block_store.py
tests/test_ec2/test_elastic_ip_addresses.py
tests/test_ec2/test_elastic_network_interfaces.py
tests/test_ec2/test_flow_logs.py
tests/test_ec2/test_instances.py
tests/test_ec2/test_internet_gateways.py
tests/test_ec2/test_key_pairs.py
tests/test_ec2/test_security_groups.py
tests/test_ec2/test_spot_instances.py
tests/test_ec2/test_tags.py

EC2 - DryRun-requests should return 412 status code

---

moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/carrier_gateways.py
moto/ec2/utils.py
tests/terraform-tests.success.txt

- Added support for carrier gateway
- CreateCarrierGateway
- DescribeCarrierGateway
- DeleteCarrierGateway
- CarrierGatewayNotFound - Exception
- TestAccAWSEc2CarrierGateway
(Sub Test Cases)
- TestAccAWSEc2CarrierGateway_basic
- TestAccAWSEc2CarrierGateway_Tags
- TestAccAWSEc2CarrierGateway_disappears

added support for carrier gateway

---

IMPLEMENTATION_COVERAGE.md
moto/logs/metric_filters.py
moto/logs/models.py
moto/logs/responses.py
tests/test_logs/test_logs.py

Full credit here goes to @brady-gsa, I have just resolved the conflicts with master as well as some linting issues from his original pull-request here:
https://github.com/spulec/moto/pull/2839
If there are any remaining issues, I will happily attempt to work through them in order to get this feature in.

add metric filter support to cloudwatch logs (updated)

---

moto/firehose/models.py
moto/logs/models.py
tests/test_firehose/test_firehose.py
tests/test_logs/test_integration.py

The CloudWatch APIs `put_subscription_filter` and `put_log_events` will now support a Firehose destination.
Data is stored in the S3 bucket specified as a Firehose destination.  That data is written in Base64 encoded gzip format and can be retrieved from that bucket.  
However, I'm not sure I did everything that needs to be done.  Perhaps additional logic will be required at a future date.

Allow CloudWatch logs to be sent to Firehose

---

moto/firehose/models.py

Corrected create and update timestamp formats.

Firehose timestamps should be in ISO format

---

moto/cloudformation/models.py
tests/test_cloudformation/test_cloudformation_stack_crud.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

When creating/updating a CloudFormation stack, you can supply NotificationARNs in order to receive stack related events. This change will make moto publish those events to the given SNS topics.

Publish messages to SNS when CloudFormation NotifcationARNs is set

---

moto/apigateway/models.py
moto/apigateway/responses.py
moto/logs/responses.py
moto/sagemaker/responses.py
moto/transcribe/models.py
tests/test_apigateway/test_apigateway.py

Added implementation add/remove  update-rest-api , I would like to add @jainmnsh he also worked with me on this.

added update rest api

---

moto/kms/models.py
tests/test_kms/test_kms_boto3.py

KMS - CreateKey without description should return empty description

---

.github/workflows/dependency_test.yml
tests/test_config/test_config_rules.py
tests/test_config/test_config_rules_integration.py

Also adds feature to automatically archive logs when running this test

Dependency test - move Config tests around

---

.github/workflows/dependency_test.yml
setup.py
tests/test_config/test_config_rules.py
tests/test_config/test_config_rules_integration.py

Add dataclasses dependency Py3.6

---

moto/kms/models.py
tests/test_kms/test_kms.py
tests/test_kms/test_kms_boto3.py

- Adds ARN support to the tagging calls
- Adds test to test ARN support

Fixes issue #4312

---

moto/ec2/responses/route_tables.py
tests/terraform-tests.success.txt

**Fixed**
- fixed describe subnet response
**Work suit completed**
- `TestAccAWSRouteTableAssociation_`

fixed route table associations

---

tests/test_core/test_nested.py
tests/test_sqs/test_sqs.py

SQS - duplicate deprecated tests

---

moto/route53/urls.py
tests/test_route53/test_route53.py

Rewrite deprecated Route53 tests

---

tests/test_sns/test_application.py
tests/test_sns/test_application_boto3.py
tests/test_sns/test_publishing.py
tests/test_sns/test_subscriptions.py
tests/test_sns/test_topics.py

SNS - duplicate deprecated tests

---

tests/test_ses/test_ses.py
tests/test_ses/test_ses_boto3.py

SES - duplicate boto tests

---

moto/server.py
tests/test_sts/test_sts.py

STS - duplicate boto tests

---

tests/test_emr/test_emr.py

EMR - mark tests as duplicated

---

tests/test_datapipeline/test_datapipeline.py

DataPipeline - duplicate deprecated tests

---

tests/test_redshift/test_redshift.py
tests/test_redshift/test_server.py

Rewrite deprecated Redshift tests

---

moto/sqs/responses.py
tests/test_sqs/test_sqs.py

SQS - Allow XML content to be received as a message attr

---

scripts/pull_down_aws_managed_rules.py

One shouldn't have to look through the script's logic to figure out how to run it.  Added invocation info at the top of the script.

Add invocation info to pull_down_aws_managed_rules.py

---

moto/secretsmanager/models.py
tests/test_secretsmanager/test_secretsmanager.py
tests/test_secretsmanager/test_server.py

Fixing https://github.com/spulec/moto/issues/4340

ISSUE-4340: SecretsManager cannot find specified secret using ARN in some operations

---

moto/ec2/models.py
moto/ec2/responses/instances.py
tests/test_ec2/test_instances.py

#4298 // fix warning when image id from template if specified

---

moto/cloudformation/responses.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

feat: Adding validation to Cloudformation to reject same template_body and parameters
First PR to moto, please let me know if I'm missing anything or if anything should be changed. 
Addresses #4157

feat: Adding validation to Cloudformation to reject same template_body

---

moto/ssm/models.py
tests/test_ssm/test_ssm_boto3.py

[issue-4283] ssm put_parameter with tags and overwrite should error

---

moto/s3/models.py
moto/s3/responses.py
tests/terraform-tests.success.txt

object locking mechanism in s3
S3_OBJECT_LEGAL_HOLD 
TestAccAWSS3Bucket_forceDestroyWithObjectLockEnabled
This is a test PR. Please do not merge as of now.

fixed object locking mechanism in s3

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Hi, I've added the implementation of `add_custom_attributes`.

Add add_custom_attributes implementation

---

.gitignore
IMPLEMENTATION_COVERAGE.md
moto/emr/models.py
moto/emr/responses.py

EMR: Rename get_cluster to describe_cluster

---

IMPLEMENTATION_COVERAGE.md
moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses_boto3.py

feat: add update_receipt_rule to ses mock

---

moto/ses/models.py
moto/ses/responses.py
tests/test_ses/test_ses_boto3.py

feat: add describe_receipt_rule_set to ses mock

---

moto/sagemaker/exceptions.py
moto/sagemaker/models.py
moto/sagemaker/responses.py
tests/test_sagemaker/test_sagemaker_search.py
tests/test_sagemaker/test_sagemaker_trial.py
tests/test_sagemaker/test_sagemaker_trial_component.py

We are mocking sagemaker we corrected some behaviour

More improvements for sagemaker.

---

moto/s3/exceptions.py
moto/s3/responses.py
tests/test_s3/test_s3_storageclass.py

Fixes #4299 
Test was validated against AWS

S3 - get_object() should error for Glacier-class

---

IMPLEMENTATION_COVERAGE.md
moto/ds/exceptions.py
moto/ds/models.py
moto/ds/responses.py
moto/ds/validations.py
tests/test_ds/test_ds.py
tests/test_ds/test_ds_ad_connect.py
tests/test_ds/test_ds_microsoft_ad.py
tests/test_ds/test_ds_simple_ad_directory.py

Adds support for the APIs:
- `create_microsoft_ad()`
- `connect_directory()`
- `create_alias()`
- `enable_sso()`
- `disable_sso()`

DirectoryService: Add support for other directories

---

moto/cognitoidentity/models.py
moto/cognitoidentity/responses.py
tests/test_cognitoidentity/test_cognitoidentity.py
tests/test_cognitoidentity/test_server.py

Add cognito identity pool list_identities method and integrate it with get_id

Add cognito-identity list identities method

---

moto/apigateway/exceptions.py
moto/apigateway/models.py
moto/apigateway/responses.py
moto/apigateway/urls.py
tests/test_apigateway/test_apigateway.py

Implement APIGateway get_base_path_mappings

Implement APIGateway get_base_path_mapping

---

moto/elbv2/models.py
tests/test_elbv2/test_elbv2.py

Fix missing valid_attrs required when create application load balancer in terraform
related to #4529

Fix missing valid_attrs (issue 4529)

---

moto/sagemaker/models.py
moto/sagemaker/responses.py
tests/test_sagemaker/test_sagemaker_processing.py

Hello,
I noticed that coverage of methods related to SageMaker Processing job is missing.
In this pull request I tried to cover:
- create_processing_job
- describe_processing_job
- list_processing_jobs
It's my first contribution to this repository, so please let me know how can I improve my code.
Thanks in advance!

Add new methods related to SageMaker Processing job

---

moto/events/models.py
tests/test_events/test_event_pattern.py

Events - match full list against pattern

---

moto/iot/models.py
moto/iot/utils.py
tests/test_iot/test_iot.py

IOT list_executions_for_thing: fix pagination

---

moto/cloudformation/parsing.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py

CloudFormation - allow updates of unknown resources

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

Fixes #1944
The Filter-param requested in that ticket was already implemented - this PR just adds the logic for the AttributesToGet-parameter

CognitoIDP:list_users() - Implement AttributesToGet-parameter

---

moto/s3/models.py
moto/s3/responses.py
tests/test_s3/test_s3_multipart.py

S3 - create_multipart_upload - support tags

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/ssm.rst
moto/ssm/models.py
moto/ssm/responses.py
tests/test_ssm/test_ssm_maintenance_windows.py

SSM - Maintenance Windows

---

moto/s3/exceptions.py
moto/s3/responses.py
tests/test_s3/test_s3_acl.py

Fixes #4023 
Test was verified against AWS

S3 - PutObject cant specify ACL and Grant

---

moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

Implement delete_base_path_mapping

APIGateway - Implement delete_base_path_mapping

---

moto/utilities/paginator.py

I don't believe six should be used anymore. 
Closes https://github.com/spulec/moto/issues/4575

Remove six import

---

setup.py

I don't believe more-itertools is in use. 
Closes https://github.com/spulec/moto/issues/4573

Remove more-itertools from install_requires

---

docs/docs/contributing/faq.rst
docs/docs/faq.rst
docs/index.rst

Add FAQ page for users

---

moto/glue/models.py
moto/glue/responses.py
tests/test_glue/test_glue.py

I have been working with Glue for a while and noticed the `job` interface has low coverage in the `moto` library
From my POV this is the first PR that will be followed by a few in order to cover the `Glue job` interface
On top of that, i work TDD and started to use a lot of `boto` clients recently in my new job, therefor i guess that i will be more than happy to contribute interfaces that i currently miss in `moto` 😄

Glue jobs initial implementation

---

moto/rds2/models.py
moto/rds2/responses.py
tests/test_rds2/test_rds2.py
tests/test_rds2/test_rds2_clusters.py

RDS - Implement DeletionProtection for Instances/Clusters

---

moto/batch/models.py
tests/test_batch/test_batch_jobs.py

Allow batch job definition tags to be updated

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodb2/test_dynamodb_exceptions.py

Closes #4622 
Test has been verified against AWS

DynamoDB Query - fix bug in invalid operator detection

---

moto/glue/models.py
moto/glue/responses.py
tests/test_glue/test_datacatalog.py

Glue - delete_database()

---

moto/emr/models.py
moto/emr/responses.py
tests/test_emr/test_emr_boto3.py

Added AutoScalingRole='string' in describe emr clusters.

emr auto scaling role

---

moto/autoscaling/models.py
moto/autoscaling/responses.py
scripts/scaffold.py
tests/test_autoscaling/test_autoscaling.py
tests/test_autoscaling/test_autoscaling_tags.py

Autoscaling - Describe Tags

---

moto/iam/models.py
moto/iam/responses.py
tests/terraform-tests.success.txt

- added supoort for UpdateGroup API for IAM

added support for update IAM groups

---

moto/batch/models.py
moto/batch/responses.py
tests/test_batch/test_batch_jobs.py

Batch - implement attemptDurationSeconds

---

moto/secretsmanager/list_secrets/filters.py
tests/test_secretsmanager/test_list_secrets.py

Resolves #4644 - Add negative filter support in secretsmanager

---

moto/iam/exceptions.py
tests/terraform-tests.success.txt

fixed tf-test

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

ECS - create_cluster with tags

---

moto/iam/models.py
moto/iam/responses.py
tests/terraform-tests.success.txt

- updated `CreateOpenIdConnectProvider` for tagging support
- added support for API `UpdateOpenIdConnectProviderThumbprint`
- added support for API `TagOpenIdConnectProvider`
- added support for API `UntagOpenIdConnectProvider`
- added support for API `ListOpenIdConnectProviderTags`
TestAccAWSIAMOpenIDConnectProvider
- TestAccAWSIAMOpenIDConnectProvider_basic
- TestAccAWSIAMOpenIDConnectProvider_tags
- TestAccAWSIAMOpenIDConnectProvider_disappears

added support for openid connect

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/exceptions/test_dynamodb_exceptions.py

DynamoDB - Error when providing table with 0 indexes

---

moto/sqs/models.py
tests/test_sqs/test_sqs.py

Add support to remove RedrivePolicy from SQS.

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/elasticache.rst
moto/__init__.py
moto/backend_index.py
moto/elasticache/__init__.py
moto/elasticache/exceptions.py
moto/elasticache/models.py
moto/elasticache/responses.py
moto/elasticache/urls.py
scripts/scaffold.py
tests/test_elasticache/test_elasticache.py
tests/test_elasticache/test_server.py

Initial implementation for ElastiCache. 
Closes #3002

Feature: Elasticache

---

moto/iot/models.py
tests/test_iot/test_iot.py

IOT - Use regular AccountId for Thing ARN

---

moto/sns/models.py
tests/test_sns/test_publishing_boto3.py

Closes #4676 
Behaviour was verified against AWS

SNS - Do not pass empty subject

---

moto/elbv2/responses.py
tests/test_elbv2/test_elbv2.py

ELBV2 - Fix elbv2 modify_rule expects Conditions (#4677)

---

moto/dynamodb2/parsing/expressions.py

use dedicated logger for dynamodb2

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/redshift.rst
moto/redshift/models.py
moto/redshift/responses.py
tests/test_redshift/test_redshift.py

Redshift - Pause/Resume clusters

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/ec2.rst
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/settings.py
tests/test_ec2/test_settings.py

Added new functionality for EC2: 
- disable_ebs_encryption_by_default, 
- enable_ebs_encryption_by_default, 
- get_ebs_encryption_by_default

Added new functionality for EC2

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/es.rst
moto/__init__.py
moto/backend_index.py
moto/es/__init__.py
moto/es/exceptions.py
moto/es/models.py
moto/es/responses.py
moto/es/urls.py
tests/test_es/test_es.py
tests/test_es/test_server.py

Initial implementation of ElasticsearchService
Closes #2719

Feature: ElasticsearchService

---

moto/xray/mock_client.py

Mocked xray client should handle args and kwargs gracefully.

Update xray client to forward args

---

moto/ec2/models.py
moto/ec2/responses/route_tables.py
tests/test_ec2/test_route_tables.py

Closes #1647
Behaviour was verified against AWS

EC2 - DescribeRouteTables should always show main association

---

moto/batch/models.py
moto/batch/responses.py
tests/test_batch/test_batch_jobs.py

Batch:list_jobs() - extend list of return fields

---

moto/apigateway/models.py
moto/apigateway/responses.py
tests/test_apigateway/test_apigateway.py

Implement update_base_path_mapping

Implement APIGateway update_base_path_mapping

---

moto/ecs/models.py
moto/ecs/responses.py
tests/test_ecs/test_ecs_boto3.py

ECS:run_task() - persist launchType-attribute

---

moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_publishing_boto3.py

Fix publishing to fifo sns->sqs subscription

---

moto/ecr/models.py
moto/ecr/responses.py
tests/test_ecr/test_ecr_boto3.py

ECR - Persist RegistryID when creating a repository

---

moto/core/responses.py
moto/sns/exceptions.py
moto/sns/models.py
moto/sns/responses.py
tests/test_sns/test_publish_batch.py

Fixes #4612 
Negative tests have been verified against AWS

SNS: publish_batch()

---

moto/__init__.py
moto/backend_index.py
moto/ssoadmin/__init__.py
moto/ssoadmin/exceptions.py
moto/ssoadmin/models.py
moto/ssoadmin/responses.py
moto/ssoadmin/urls.py
tests/test_ssoadmin/test_server.py
tests/test_ssoadmin/test_ssoadmin.py

SSO-Admin - Initial implementation

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/appsync.rst
moto/__init__.py
moto/appsync/__init__.py
moto/appsync/exceptions.py
moto/appsync/models.py
moto/appsync/responses.py
moto/appsync/urls.py
moto/backend_index.py
moto/utilities/tagging_service.py
setup.py
tests/terraform-tests.success.txt
tests/test_appsync/test_appsync.py
tests/test_appsync/test_appsync_apikeys.py
tests/test_appsync/test_appsync_schema.py
tests/test_appsync/test_appsync_tags.py
tests/test_appsync/test_server.py

AppSync - initial implementation

---

moto/awslambda/responses.py
tests/test_awslambda/test_lambda_invoke.py
tests/test_awslambda/utilities.py

AWSLambda - throw error on large responses (>6MB)

---

moto/core/responses.py
moto/ec2/models.py
moto/ec2/responses/elastic_block_store.py
tests/test_ec2/test_elastic_block_store.py

EC2 - create_snapshots

---

moto/cloudfront/models.py
moto/cloudfront/responses.py
tests/test_cloudfront/test_cloudfront_distributions.py

Cloudfront - add missing fields

---

docs/docs/contributing/new_feature.rst
docs/docs/faq.rst
docs/docs/getting_started.rst
moto/core/models.py
tests/test_core/test_decorator_calls.py

Class decorator - allow possibility of setUp in parent class

---

IMPLEMENTATION_COVERAGE.md
moto/rds2/exceptions.py
moto/rds2/models.py
moto/rds2/responses.py
moto/resourcegroupstaggingapi/models.py
tests/test_rds2/test_rds2.py
tests/test_rds2/test_rds2_clusters.py

Hi team. 
I'm implementing RDS operators for Aifrow and I'm going to use `moto` for testing purposes.
So I need to implement some methods for `mock_rds2`
- **DB instance copy snapshot method** (`copy_db_snapshot`) 
- **Cluster snapshot methods** (`copy_db_cluster_snapshot`, `create_db_cluster_snapshot`, `delete_db_cluster_snapshot`, `describe_db_cluster_snapshots`)
- Export task methods (`cancel_export_task`, `describe_export_tasks`, `start_export_task`)
- Event subscriptions (`create_event_subscription`, `delete_event_subscription`, `describe_event_subscriptions`)
I'll be very happy if you'll help me

Add RDS methods

---

moto/batch/models.py
tests/test_batch/test_batch_jobs.py

Ports https://github.com/spulec/moto/pull/4658 to batch

Add host to batch

---

docs/docs/services/route53.rst
moto/route53/models.py
moto/route53/responses.py
moto/route53/urls.py
tests/test_route53/test_route53.py

Hi,
This is my first attempt at implementing something for moto. Please tell me if I'm even on the right track with this one :)
-Paul

Implement list_hosted_zones_by_vpc() functionality

---

docs/docs/services/route53.rst
moto/route53/models.py
moto/route53/responses.py
moto/route53/urls.py
tests/test_route53/test_route53.py

implement get_hosted_zone_count() api

---

.github/workflows/build.yml
IMPLEMENTATION_COVERAGE.md
MANIFEST.in
docs/docs/services/ec2.rst
moto/ec2/_models/core.py
moto/ec2/_models/vpc_service_configuration.py
moto/ec2/exceptions.py
moto/ec2/models.py
moto/ec2/responses/__init__.py
moto/ec2/responses/vpc_service_configuration.py
moto/ec2/utils.py
moto/elbv2/models.py
tests/terraform-tests.success.txt
tests/test_ec2/test_elastic_network_interfaces.py
tests/test_ec2/test_vpc_service_configuration.py
tests/test_elbv2/test_elbv2.py
tests/test_elbv2/test_elbv2_target_groups.py

Adds several new EC2 features.
Behaviour was verified against AWS and using the Terraform tests.
This also starts a refactoring of the `ec2/models.py` file, by moving related Backends/Models into dedicated files. Further refactoring is necessary to split up the current 8000+LOC file
Also fixes some ELBv2 bugs required to get Terraform to pass.

EC2 - VpcEndpointServiceConfiguration

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/route53.rst
moto/route53/exceptions.py
moto/route53/models.py
moto/route53/responses.py
moto/route53/urls.py
tests/test_route53/test_route53.py
tests/test_route53/test_route53_delegationsets.py

Route53 - Reusable Delegation Sets

---

moto/awslambda/exceptions.py
moto/awslambda/policy.py
moto/awslambda/responses.py
tests/test_awslambda/test_lambda.py

Fixes #4227
Test was verified against AWS

AWSLambda - Error when removing unknown permission

---

moto/acm/models.py
tests/terraform-tests.success.txt
tests/test_acm/test_acm.py

ACM improvements

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/iot.rst
moto/iot/exceptions.py
moto/iot/models.py
moto/iot/responses.py
moto/iotdata/models.py
moto/iotdata/responses.py
tests/terraform-tests.success.txt
tests/test_iot/test_iot_ca_certificates.py
tests/test_iot/test_iot_certificates.py
tests/test_iot/test_iot_search.py
tests/test_iotdata/test_iotdata.py

Closes #2079
Closes #3333
Closes #3890
Closes #4694 
Supercedes #4697

IOT improvements

---

moto/dynamodb2/exceptions.py
moto/dynamodb2/models/__init__.py
moto/dynamodb2/parsing/validators.py
moto/dynamodb2/responses.py
tests/test_awslambda/test_lambda_eventsourcemapping.py
tests/test_dynamodb2/conftest.py
tests/test_dynamodb2/exceptions/test_dynamodb_exceptions.py
tests/test_dynamodb2/test_dynamodb.py
tests/test_dynamodb2/test_dynamodb_condition_expressions.py
tests/test_dynamodb2/test_dynamodb_consumedcapacity.py
tests/test_dynamodb2/test_dynamodb_create_table.py
tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
tests/test_dynamodb2/test_dynamodb_table_without_range_key.py
tests/test_dynamodb2/test_dynamodb_update_table.py

Closes #4755 
Closes #4781 
Adds support for the Tags and SSESpecification parameters, and improves the behaviour of BillingMode and AttributeDefinitions.
Some existing tests have been moved around, to reduce the number of files per test, but no tests have been removed

DynamoDB improvements

---

setup.py

Setup.py - requires python_requires

---

moto/sqs/models.py
tests/test_sqs/test_sqs_cloudformation.py

SQS - Use full URL as the physical resource ID

---

docs/docs/services/ec2.rst
moto/ec2/models.py
moto/ec2/utils.py
scripts/get_amis.py
tests/test_ec2/test_utils.py

Also documents the MOTO_AMIS_PATH environment variable.
fixes #4865

refactor scripts/get_amis.py into moto.ec2.utils.gen_moto_amis()

---

.github/workflows/build.yml
.github/workflows/release.yml
CHANGELOG.md
IMPLEMENTATION_COVERAGE.md
docs/docs/server_mode.rst
docs/docs/services/application-autoscaling.rst
docs/docs/services/athena.rst
docs/docs/services/cloudformation.rst
docs/docs/services/cognito-identity.rst
docs/docs/services/cognito-idp.rst
docs/docs/services/dynamodb.rst
docs/docs/services/ec2-instance-connect.rst
docs/docs/services/ec2.rst
docs/docs/services/emr-containers.rst
docs/docs/services/es.rst
docs/docs/services/iot-data.rst
docs/docs/services/kinesis-video-archived-media.rst
docs/docs/services/mediastore-data.rst
docs/docs/services/rds.rst
docs/docs/services/redshift-data.rst
docs/docs/services/resource-groups.rst
docs/docs/services/ses.rst
docs/docs/services/sso-admin.rst
docs/docs/services/timestream-write.rst
docs/docs/services/wafv2.rst
moto/ec2/_models/vpc_service_configuration.py
scripts/implementation_coverage.py

- Fix Docker action to output the correct digest
- Add the digest to the Release Notes automagically
- Document the existence of the Docker-image for MotoServer
- Fix a minor bug in EC2

Prep release 3.0.4

---

moto/dynamodb2/responses.py
tests/test_dynamodb2/exceptions/test_dynamodb_exceptions.py

Fix: Calling dynamodb:UpdateItem with non-existent table name should raise ResourceNotFoundException

---

moto/s3control/responses.py
moto/server.py
tests/test_s3control/test_s3control.py

This PR addresses localstack/localstack#5168. With this patch s3control works fine in server mode.

Addition of s3control support in server mode

---

moto/cognitoidp/models.py
moto/cognitoidp/responses.py
tests/test_cognitoidp/test_cognitoidp.py

* Update set_user_mfa_preference to handle PreferredMFA option
* Add tests

Add implementation for cognitoidp admin_set_user_mfa_preference

---

moto/ec2/models.py
moto/ec2/responses/vpcs.py
tests/test_ec2/test_ec2_cloudformation.py

CF - Support for VPCEndpoint

---

moto/sns/__init__.py
moto/sns/models.py
moto/sqs/__init__.py
moto/swf/__init__.py
tests/test_sns/test_publishing_boto3.py

SNS Docs - do not specify default region

---

moto/core/responses_custom_registry.py

Reduce duplicate matches - ensures compatibility Responses 0.19.0

---

IMPLEMENTATION_COVERAGE.md
docs/docs/services/pinpoint.rst
moto/__init__.py
moto/awslambda/policy.py
moto/backend_index.py
moto/moto_server/werkzeug_app.py
moto/pinpoint/__init__.py
moto/pinpoint/exceptions.py
moto/pinpoint/models.py
moto/pinpoint/responses.py
moto/pinpoint/urls.py
tests/terraform-tests.success.txt
tests/test_awslambda/test_policy.py
tests/test_pinpoint/test_pinpoint.py
tests/test_pinpoint/test_pinpoint_application_tags.py
tests/test_pinpoint/test_pinpoint_event_stream.py

Pinpoint - initial implementation

---

moto/ec2/exceptions.py
moto/ec2/models.py
tests/test_ec2/test_instances.py

Test was verified against AWS.
Closes #4903

EC2:terminate() - fix error message

---

moto/rds/models.py

Fixed RDS incorrect statuses that were added by me in previous PRs

Fix RDS incorrect statuses

---

setup.py
tests/test_apigateway/test_apigateway_integration.py
tests/test_awslambda/test_lambda_eventsourcemapping.py
tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
tests/test_cloudformation/test_cloudformation_stack_integration.py
tests/test_core/test_mock_regions.py
tests/test_core/test_socket.py
tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
tests/test_dynamodb/exceptions/test_key_length_exceptions.py
tests/test_xray/test_xray_client.py

Remove more DynamoDB2 references

---

moto/core/models.py
tests/test_core/test_decorator_calls.py

Ensure setup_method resets state

---

moto/awslambda/exceptions.py
moto/awslambda/models.py
moto/awslambda/responses.py
moto/awslambda/urls.py
tests/test_awslambda/test_lambda.py

AWSLambda - raise correct error when publishing unknown function

---

moto/acm/responses.py
moto/apigateway/responses.py
moto/apigatewayv2/responses.py
moto/appsync/responses.py
moto/awslambda/responses.py
moto/batch/responses.py
moto/cloudfront/responses.py
moto/core/exceptions.py
moto/core/models.py
moto/databrew/responses.py
moto/eks/exceptions.py
moto/eks/responses.py
moto/es/responses.py
moto/forecast/responses.py
moto/mq/exceptions.py
moto/mq/responses.py
moto/pinpoint/responses.py
moto/route53/responses.py
moto/s3control/responses.py
moto/sagemaker/responses.py
moto/stepfunctions/models.py
moto/stepfunctions/responses.py
moto/xray/responses.py
tests/test_core/test_decorator_calls.py

Various services had different ways of catching and dealing with errors. This PR streamlines the exception handling across all services - every error that extends either RESTError or AWSError is now caught by Moto, and the appropriate response format is determined uniformly.

Simplify error handling

---

moto/awslambda/models.py
moto/awslambda/policy.py
moto/awslambda/responses.py
moto/config/models.py
moto/logs/models.py
moto/secretsmanager/models.py
tests/test_awslambda/test_lambda_policy.py
tests/test_logs/test_integration.py

Improves error handling for non-existing functions
Adds support for the Qualifier-parameter of the `add_permission()`-function

Improvements: AWSLambda policies

---

moto/organizations/models.py
moto/organizations/responses.py
moto/organizations/utils.py
moto/utilities/paginator.py
tests/test_organizations/test_organizations_boto3.py

Add Pagination for Organizations:ListAccounts

---

moto/ec2/models.py
tests/test_ec2/test_instances.py

EC2:run_instances() - fix bug when supplying the NIC with security groups

---

CHANGELOG.md
IMPLEMENTATION_COVERAGE.md
docs/docs/services/config.rst
docs/docs/services/glue.rst

Can be merged the moment #4975 passes

Prepare release 3.1.3

---

moto/efs/models.py
tests/test_efs/test_file_system.py

see: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/efs.html#EFS.Client.create_file_system
and https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/efs.html#EFS.Client.describe_file_systems

Create & Describe file system APIs return Name property based on tags

---

moto/elbv2/responses.py
tests/test_elbv2/test_elbv2.py

ELBV2 - Ensure ResourceARN is returned when describing tags
