- moto/autoscaling/models.py
- moto/awslambda/models.py
- moto/batch/models.py
- moto/cloudformation/parsing.py
- moto/cloudwatch/models.py
- moto/core/__init__.py
- moto/core/models.py
- moto/datapipeline/models.py
- moto/dynamodb/models.py
- moto/dynamodb2/models/__init__.py
- moto/ec2/models.py
- moto/ecr/models.py
- moto/ecs/models.py
- moto/elb/models.py
- moto/elbv2/models.py
- moto/events/models.py
- moto/iam/models.py
- moto/kinesis/models.py
- moto/kms/models.py
- moto/rds/models.py
- moto/rds2/models.py
- moto/redshift/models.py
- moto/route53/models.py
- moto/s3/models.py
- moto/sns/models.py
- moto/sqs/models.py
Continuing from #3185 opened by @bblommers.
From the original PR:
> First pass at decentralizing the CF responsibility to individual models.
> Each Model that wants to be recognized by CloudFormation's parser now needs to:
> 
> - Extend the moto.core.CloudFormationModel class
> - Implement the abstract method cloudformation_type
> - Implement the abstract method cloudformation_name_type
> - Implement the create/update/delete_from_cloudformation_json methods (as before)
> 
> This removes the need to explicitly list all known/supported models in our CloudFormation-service.
> 
> TODO:
> 
> - [x] Change all other models to subclass CloudFormationModel (Only DynamoDB::Table is done atm)
> - [x] Add the create_from_cloudformation_json-methods to CloudFormationModel, to ensure clarity on what to …
> Decentralize cloudformation naming responsibilities

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
I'm using this product through localstack, and always helped me.
Compared to the real SQS behavior, it seems that some messages may not be retrieved after calling `purge_queue`.
I thought it was due to lack of clearing `_pending_messages` in `purge_queue`, but I'm not confident...
(I'm using FIFO Queue in my test code because that was exactly where I encountered the problem.)
> fix: clear pending messages when call purge_queue

- moto/cloudformation/parsing.py
- moto/core/models.py
- moto/kinesis/models.py
- tests/test_kinesis/test_kinesis.py
- tests/test_kinesis/test_kinesis_cloudformation.py
Addresses #3211
* Support for CloudFormation update and delete of Kinesis Streams
* Support for CloudFormation stack resource deletion via backend resource method
delete_from_cloudformation_json() via parse_and_delete_resource().
* Correction to the inappropriate inclusion of EndingSequenceNumber in open shards.
This attribute should only appear in closed shards.  This regretfully prevents
confirmation of consistent record counts after split/merge in unit tests.
* Added parameters/decorator to CloudFormationModel method declarations to calm-down Pycharm.
> * Support for CloudFormation update and delete of Kinesis Streams

- .travis.yml
- moto/awslambda/models.py
- travis_moto_server.sh
AWS Lambda runtime sets a few envs, according to:
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime
This PR set credentials and two other basic envs. It's another approach to fix #3225 (also try in #3220)
> Set lambda credentials' variables in runtime

- moto/ses/models.py
- moto/sns/models.py
- moto/sns/responses.py
- tests/test_sns/test_publishing_boto3.py
Proper behaviour when publishing to PhoneNumber is sending
message directly to this number, without any topic or
previous confirmation.
https://docs.aws.amazon.com/sns/latest/dg/sns-mobile-phone-number-as-subscriber.html
Fix #2198 and duplicated #3251
> [SNS] Mock sending directly SMS

- moto/ses/models.py
- tests/test_ses/test_ses_boto3.py
When sending emails by SES, it allows use source addresses that were verified by `verify_email_address` method.
Fix #3240
> SES: Fix sending email when use verify_email_address

- moto/awslambda/models.py
- moto/cloudformation/parsing.py
- moto/cloudwatch/models.py
- moto/datapipeline/models.py
- moto/dynamodb2/models/__init__.py
- moto/ecr/models.py
- moto/ecs/models.py
- moto/elbv2/models.py
- moto/events/models.py
- moto/iam/models.py
- moto/kinesis/models.py
- moto/kinesis/responses.py
- moto/rds/models.py
- moto/rds2/models.py
- moto/route53/models.py
- moto/s3/models.py
- moto/sns/models.py
- moto/sqs/models.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_cloudformation/test_validate.py
- tests/test_iam/test_iam.py
- tests/test_iam/test_iam_cloudformation.py
- tests/test_kinesis/test_kinesis_cloudformation.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_cloudformation.py
I set out to add CloudFormation support for a few IAM entities I need in my current project, and quickly found myself adding special cases to funcs in the CloudFormation parsing.py to cope with things like un-specified names and deletion of resources without unique identities.  I found myself struggling to understand the resulting logic, with the troubling sense that it had unnecessarily grown unmaintainable, and perhaps some of the existing logic wasn't quite right.  IMO the generalized logic for creating, updating and deleting stacks should be pretty straightforward.  So I got up my courage and wrote them how I figured they should be, made my IAM models work with them, and then fixed up the rest.  
Listing my general strategies first:
-	Resource names never get injected into the json. …
> Iam cloudformation update, singificant cloudformation refactoring

- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
Fix: Api-Gateway ApiKeyAlreadyExists headers change.
https://github.com/localstack/localstack/issues/2753
> Fix: Api-Gateway ApiKeyAlreadyExists headers change.

- requirements-dev.txt
- scripts/scaffold.py
Fixed `scripts/scaffold.py` to work again.
- Upgraded prompt-toolkit
- Support new format of `moto/__init__.py` and `moto/backends.py`
- Support AWS operation name that is not pure upper camel case.
> Fix scaffold.py

- moto/__init__.py
- moto/backends.py
- moto/kinesis/urls.py
- moto/kinesisvideo/__init__.py
- moto/kinesisvideo/exceptions.py
- moto/kinesisvideo/models.py
- moto/kinesisvideo/responses.py
- moto/kinesisvideo/urls.py
- tests/test_kinesisvideo/test_kinesisvideo.py
- tests/test_kinesisvideo/test_server.py
Added basic operations of `kinesisvideo`
- `create_stream`
- `describe_stream`
- `list_streams`
- `delete_stream`
- `get_data_endpoint`
> Add kinesisvideo

- moto/stepfunctions/models.py
- moto/stepfunctions/responses.py
- tests/test_stepfunctions/test_stepfunctions.py
Closes #3283 
* Allows for `start_execution(<..>, input=<an-input>)` - Not just defaulting to `'{}'`
* Add test to ensure that a custom input is returned correctly by `describe_execution`
* Remove unnecessary `as exc`'s
> Implement Execution inputs for Step Functions

- requirements.txt
- setup.py
- travis_moto_server.sh
Rebase of #2676 to fix merge conflicts
Hope you don't mind @slafs .  @spulec noted on #2676 that the current state was probably mergeable as is, so hoping we can do just that, since the merge conflicts in setup.py get tricky to resolve.
> Fix #1728 by introducing per-service extras_require

- moto/stepfunctions/exceptions.py
- moto/stepfunctions/models.py
- tests/test_stepfunctions/test_stepfunctions.py
* Validates that the input is a valid JSON string
* Adds `InvalidExecutionInput` from exceptions [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.start_execution)
* Adds another test to cover valid custom inputs to `start_execution`
* Non-string inputs are already caught via `moto.core.responses._get_param`
> Add Step Function Execution Input validation

- setup.py
Fixes #3290 
S3 is dependent on IAM, which is dependent on the cryptography-module.
This PR adds S3 as an additional service (`pip install moto[s3]`) to ensure it installs the required dependencies.
This also adds all dependencies to the [server], as at the moment people would have to use `pip install moto[server,all]` to get the full functionality.
FYI @spulec - this might need a new release, considering it broke 1.3.15
Edit: Considering it was a breaking change in the API, we could make this a major version change to reflect this? (2.0.0)
Edit 2: Marking it as draft, because the SNS/SQS services also need additional dependencies - will need to do more testing to verify other services
> #3290 - Add additional dependencies in extras_require

- moto/sns/models.py
- tests/test_sns/test_topics.py
- tests/test_sns/test_topics_boto3.py
Deleting a non-existent topic shouldn't raise KeyError
Related Issues:
- https://github.com/spulec/moto/issues/2992 <- slightly different, here they called `unsubscribe` instead of `delete_topic`
> fix: deleting non-existent topic shouldn't raise KeyError

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_storageclass.py
Issue #3224 (enhancement) - S3 - Copying Objects that have StorageClass = 'GLACIER' but have been restored 
Fix for allowing restored Glacier and Deep Archive objects to be copied without throwing error.
> Issue 3224 s3 copy glacier object

- moto/iot/exceptions.py
- moto/iot/models.py
- tests/test_iot/test_iot.py
Fixes #3320
When using boto3, trying to register a certificate that already
exists will throw a ResourceAlreadyExistsException. Moto should
follow the same pattern to allow testing error handling code in
this area.
---
Fixes #3321
As per https://stackoverflow.com/questions/55847788/how-does-aws-iot-generate-a-certificate-id,
the IoT certificate ID is the SHA256 fingerprint of the
certificate. Since moto doesn't generate full certificates we will
instead use the SHA256 hash of the passed certificate pem.
> Make IoT certificate ID generation deterministic and prevent duplicate certificates from being created

- moto/iam/models.py
- moto/iam/responses.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_iam/test_iam.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_storageclass.py
This PR adds support for `PutRolePermissionsBoundary` and `DeleteRolePermissionsBoundary`.
Fixed the response template `GET_ROLE_TEMPLATE` for RolePermissionBoundary support.
Added test case for `PutRolePermissionsBoundary` and `DeleteRolePermissionsBoundary`.
This PR should fix the issue in localstack: [localstack/localstack#2888](https://github.com/localstack/localstack/issues/2888)
> feature added: support for api RolePermissionsBoundary

- moto/events/models.py
- moto/events/responses.py
- tests/test_events/test_events.py
This PR updates the response for the Events `RemoveTargets` API call.
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_RemoveTargets.html
The response will now return a JSON formatted object including the `FailedEntryCount` and `FailedEntries` as expected from the AWS API.
> feat: update events remove_targets API response

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
Fix:SQS md5 calculation for custom string data type.
https://github.com/localstack/localstack/issues/2976
> Fix:SQS md5 calculation for custom string data type.

- moto/secretsmanager/list_secrets/filters.py
- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
Fixes #3302 
Now only generates the ARN once once on creation, instead of generating a new one for every describe_secret/list_secrets call.
Also stores every secret into a dedicated FakeSecret-object, instead of in a dictionary. Should make it more maintainable down the line.
> SecretsManager: Make Secret ARN persistent

- moto/iam/models.py
- moto/iam/responses.py
- tests/test_iam/test_iam.py
Playing with the Ansible's `iam_managed_policy` I noticed it uses the `set_default_policy_version` which is currently not supported in `moto`. Would you be interested in this PR?
> Add `set_default_policy_version` to the IAM backend

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
There is an issue with secret rotation. During the call secret_binary has got the value of the description and the description has got the tags value.
> Fix issue with wrong parameter signed to secret_binary during secret rotation in Secrets Manager

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
The get_secret_value method should raise ResourceNotFoundException
if a secret exists but the provided VersionId does not.
> [SecretsManager] Handle missing secrets versions

- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb.py
Started working on a testcase to repro this issue when I encountered it in one 
of my codebases, but then the fix seemed pretty simple so figured I'd throw this
up here!
When comparing old and new values when doing a nested item update, the
`!=` implementation fails when the value being compared is `None`. This
results in an exception when trying to insert a new item into a nested
map. So just do a quick check that the original value is exists before
doing the comparison, as the `None` default is what is tripping this.
> fix(dynamodb2): Fix update_item nested insert

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
The `tag_filter` method has been re-arranged to mimic the actual AWS behavior:
Return `True` if *any* tag matches a filter and *all* filters are matched.
Python's closures are late-binding, so we have to modify the lambdas accordingly!
Closes #2814
> Fix `TagFilter` implementation in `tag:GetResources`

- moto/acm/models.py
- tests/test_acm/test_acm.py
https://github.com/spulec/moto/blob/c4b630e20fb9004ef4b1eab345ceab5ef9e4c2ff/moto/acm/models.py#L230-L235
While describing imported acm certificate, if the certificate does not have any SANs, `get_extension_for_oid()` could throw a `cryptography.x509.ExtensionNotFound.`
The [unit test](https://github.com/spulec/moto/blob/d00cefa25cfd338caaabcefc7a79e6e803f577cf/tests/test_acm/test_acm.py#L129) should have failed here. But unfortunately, it is overwritten by next function with same name.
This PR fixes `describe_certificate()` to handle imported certificates with missing SAN extension. unit test is updated to run the corresponding tests.
Fixes #3371
> Fixes acm:describe_certificate for imported certificates having no SAN extension

- moto/acm/models.py
- moto/acm/responses.py
- tests/test_acm/test_acm.py
Implements `Tags` parameter which is acceptable in boto3 ACM client methods: [import_certificate()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm.html#ACM.Client.import_certificate) and [request_certificate()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm.html#ACM.Client.request_certificate) APIs
Fixes #3377
> support Tags parameter in ACM import_certificate() and request_certificate() methods

- tests/test_acm/test_acm.py
Some unit tests for ACM implementation were [commented](https://github.com/spulec/moto/pull/1174/files?file-filters%5B%5D=.md&file-filters%5B%5D=.py#r140904537) out due to a then pending [PR](https://github.com/spulec/freezegun/pull/210) on **freezegun**
Enabling those tests with minor changes.
> Enable more unit tests for ACM

- moto/core/utils.py
- moto/ecs/models.py
- tests/test_ecs/test_ecs_cloudformation.py
There's a larger problem here that needs a more generalized solution,
but this solves the immediate issue with a minimum amount of code.
Closes #3171
> Fix missing properties when ecs:TaskDefinition created via CloudFormation

- moto/ec2/exceptions.py
- moto/ec2/models.py
- moto/ec2/responses/elastic_block_store.py
- tests/test_ec2/test_elastic_block_store.py
NOTE: A client-provided `KmsKeyId` is simply stored as-is, and is *not* validated
against the KMS backend.  This is in keeping with other moto backends (RDS, Redshift)
that currently also accept unvalidated customer master key (CMK) parameters, but could
be an area for future improvement.
Closes #3248
> Add KMS Support to EBS Encrypted Volumes

- moto/dynamodb2/parsing/executors.py
- tests/test_dynamodb2/test_dynamodb.py
DynamoDB does not support empty sets.  If the last item in a set is
deleted as part of an UpdateExpression, the attribute must be removed.
Ref: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html
Fixes #3296
> Fix: Empty sets not removed from item after UpdateExpression

- moto/sns/models.py
- moto/sns/responses.py
- tests/test_sns/test_topics.py
- tests/test_sns/test_topics_boto3.py
We do not do any validation of the `KmsMasterKeyId` attribute, and simply
store it as-as.  This mimics the behavior in AWS, where the key is not
validated until it is actually used (when publishing[1]).
[1]: https://docs.aws.amazon.com/sns/latest/dg/sns-server-side-encryption.html
Closes #3216
> Add Support for SNS Topic `KmsMasterKeyId` Attribute

- moto/ec2/models.py
- tests/test_ec2/test_subnets.py
This change allows creation of subnets from secondary VPC IPv4 CIDR blocks in the `mock_ec2` framework.
Previously, if you attempted to create a subnet in a secondary VPC CIDR you would get a IP range validation error.
Fixes #3385
> Allow creation of subnets from secondary VPC IPv4 CIDR blocks

- moto/logs/models.py
- moto/logs/responses.py
- tests/test_logs/test_logs.py
The pagination for this endpoint has been modified to more closely
model the real AWS behavior:
* Log Groups are now sorted alphabetically by `logGroupName`.
* `nextToken` is now a string containing the last `logGroupName` in the
current response.
* Specifying an invalid `nextToken` does not generate an error, but does
return an empty group list.
* `nextToken` is not included in the response if there are no additional
items to return.
Fixes #3395
> Fix: `nextToken` value in `logs:DescribeLogGroups` response

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
Issue: https://github.com/spulec/moto/issues/3399
Wrong attributes md5 hash is generated. Client side application fails after comparing hashes. 
Added md5 attribute hashing according to aws sqs documentation.
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-attributes
> Fix SQS md5 attribute hashing.

- moto/s3/models.py
- tests/test_s3/test_s3_cloudformation.py
Prevent valid CloudFormation templates containing S3 `Fn::GetAtt` from raising unexpected `ValidationError`.
Spec for valid cases referenced from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#aws-properties-s3-bucket-return-values.
Addresses an issue reported here: https://github.com/localstack/aws-cdk-local/issues/1
> Add missing `Fn::GetAtt` attributes to S3 bucket mock

- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb.py
If the requested item has no projected attributes, the corresponding ItemResponse
object is an empty Map.[1]  Verified against real AWS.
Fix existing general test case and add an explicit test case to cover this scenario.
[1]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactGetItems.html#API_TransactGetItems_ResponseElements
Fixes #3404
> Fix `dynamodb:TransactGetItems` response for items that do not exist

- moto/applicationautoscaling/exceptions.py
- moto/applicationautoscaling/models.py
- moto/applicationautoscaling/responses.py
- tests/test_applicationautoscaling/test_applicationautoscaling.py
Also, changes so same ClientError is returned for validation exceptions as AWS does.
> ApplicationAutoscaling: support autoscaling policies, deregister_scalable_target

- moto/cloudwatch/models.py
- moto/cloudwatch/responses.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
Fixes issue #3408
I added support for metric data queries in PutMetricAlarms sufficiently for my own needs. I'm not sure if the style in the implementation is ideal, but can modify as required.
- Add support for Metric Data Queries in `PutMetricAlarms` and `DescribeAlarms`
- Add unit test for `describe_alarms`
> Metric data query alarms

- moto/stepfunctions/exceptions.py
- moto/stepfunctions/models.py
- moto/stepfunctions/responses.py
- moto/stepfunctions/utils.py
- tests/test_stepfunctions/test_stepfunctions.py
Implement filtering for stepfunctions:ListExecutions
Add pagination to Step Functions endpoints
Implements a generalized approach to pagination via a decorator method for the
Step Functions endpoints.  Modeled on the real AWS backend behavior, `nextToken`
is a dictionary of pagination information encoded in an opaque string.
With just a bit of metadata hard-coded (`utils.PAGINATION_MODEL`), backend `list`
methods need only be decorated with `@paginate` and ensure that their returned
entities are sorted to get full pagination support without any duplicated code
polluting the model.
Closes #3137
> Stepfunctions improvements

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodbstreams/test_dynamodbstreams.py
Verified API documentation[1] against the real AWS backend.
[1]: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_Record.html#DDB-Type-streams_Record-eventName
Fixes #3400
> Fix: eventName for a deleted record should be REMOVE instead of DELETE

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_list_secrets.py
- tests/test_secretsmanager/test_secretsmanager.py
`secretsmanager:DescribeSecret` returns `VersionIdsToStages`
`secretsmanager:ListSecrets` returns the same information in `SecretVersionsToStages`
* Verified fix against real AWS backend.
Fixes #3406
> Fix: describe/list attribute discrepancy in Secrets Manager

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/test_dynamodb.py
Linked GitHub Issue to be fixed by this PR: https://github.com/spulec/moto/issues/3441.
Implemented the fix to use the default value for `Action`, according to `boto3.DynamoDB.Client.update_item()` [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.update_item), which is 'Put'.
Added a unit test to make sure the default value is used in case of absence of `Action` passed by the caller.
Tests pass:
```
...
test_dynamodb.test_update_item_with_list ... ok
test_dynamodb.test_update_item_with_no_action_passed_with_list ... ok
...
```
as well as Black check.
> dynamodb2 support for default Action ('Put') in update_item

- moto/iam/responses.py
- tests/test_iam/test_iam.py
> Fix: Return `Tags` in iam:CreateUserResponse

- moto/core/models.py
- setup.py
Fixes #3460 
Before:
```
$ pip freeze | grep responses
responses==0.12.1
$make test
...
Ran 3601 tests in 705.949s
FAILED (SKIP=1, errors=28, failures=6)
```
After:
```
$ pip freeze | grep responses
responses==0.12.1
$make test
...
Ran 3601 tests in 591.731s
OK (SKIP=1)
```
> Fix failures with latest responses library (0.12.1)

- moto/rds2/models.py
- tests/test_rds2/test_rds2.py
Previously, tags were only available via rds:ListTagsForResource, but are now
included in the Create/DescribeDBInstance responses as of Botocore 1.18.17[1]
[1]: https://github.com/boto/botocore/commit/f29d23c53ec0477e58450744986b0f8f23c97da1#diff-d10722c0e11ded323c8d240066d7ed31e93a1e6423d54e091b7d54b86e6bd4e0
Fixes #3458
> Fix: `TagList` missing in rds:DescribeDBInstance response

- moto/events/models.py
- moto/events/responses.py
- tests/test_events/test_events.py
Store the `EventBusName` property in the `EventsBackend` and modify `test_put_rule` to verify it's stored by `put_rule` and returned by `list_rules`.
If an `EventBusName` isn't specified it defaults to the account's default event bus (named "default"):
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/events.html#EventBridge.Client.put_rule
> EventBridge: put_rule and list_rules should store and retrieve EventBusName property

- moto/route53/models.py
- tests/test_route53/test_route53.py
Use Jinja2 escape functionality to escape html attributes in value response of route53
Fix for: https://github.com/spulec/moto/issues/3469
> Fix XML encoding in Route53 JInja2 Templates #3469

- moto/awslambda/models.py
- tests/test_awslambda/test_lambda.py
https://github.com/spulec/moto/issues/3464
This implementation fixes the bug in awslambda/models.py when updating the VPCconfig. The code in def update_configuration was trying to set a value to vpc_config which is a property (not an attribute) that doesn't have a setter. Changing to setting self._vpc_config = value fixes the problem.
This PR also updates the test case "test_update_configuration" in tests/test_awslambda/test_lambda.py to add the VpcConfig property and an assertion to verify the change.
> fixed issue in update_configuration for lambda when setting VPCconfig

- moto/s3/utils.py
(old) `boto` is no longer being developed, and importing it raises
deprecation warnings. copy Key.base_user_settable_fields in here instead
of importing boto
> lift user_settable_fields from (old) boto

- moto/route53/responses.py
- moto/route53/urls.py
- tests/test_route53/test_route53.py
This PR implements a dummy GetChange endpoint for the Route53 mock within moto. This change has been discussed in #3449.
The Route53 mock in moto does not store Change IDs in it's backend at the moment, this is why I created a dummy endpoint that always returns INSYNC status together with the same SubmittedAt date for all requests.
Ideally, the Route53 mock backend would store Change IDs the same way it stores hostedzones, healthchecks, etc. I've discussed the possibility of doing this with @bblommers and he's keen on that, but for now I'll stick with this approach as the ideal option would require significant changes in the route53 mock to support and store those change IDs.
GetChange is used by existing tooling around Route53, which makes supporting this endpoint in moto very …
> Route53: Implement dummy GetChange endpoint

- moto/ec2/exceptions.py
- moto/ec2/models.py
- moto/ec2/responses/__init__.py
- moto/ec2/responses/iam_instance_profiles.py
- moto/ec2/utils.py
- moto/iam/models.py
- tests/test_ec2/test_iam_instance_profile_associations.py
This PR adds: associate_iam_instance_profile, describe_iam_instance_profile_associations, disassociate_iam_instance_profile, replace_iam_instance_profile_association with cloudformation support while creating and terminating instance.
https://github.com/spulec/moto/issues/2206
https://github.com/localstack/localstack/issues/3241
> Implement IAM instance profile associations

- moto/redshift/models.py
- tests/test_redshift/test_redshift.py
The previous code was trying to raise a botocore ClientError directly, which
was actually generating a secondary AttributeError because the arguments passed
to ClientError() were incorrect.
This replaces the ClientError() call with a proper moto exception class for
Redshift and fixes the test assertions appropriately.
Supersedes #1957
> Fix: redshift:EnableSnapshotCopy raises incorrect Exception

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Previous code would raise `TypeError: 'dict_keys' object is not subscriptable`
when run under Python 3.
* Re-write code in Python 2/3 compatible way.
* Add clarifying comment.
* Add test coverage.
Supersedes #3227
> Fix: Python 2/3 Incompatibility

- .coveragerc
- moto/emr/responses.py
- moto/emr/utils.py
- tests/test_emr/test_emr_boto3.py
- tests/test_emr/test_utils.py
I changed the existing test to use a ReleaseLabel version specifically called out in the issue report as not working.
Fixes #3474
> Fix: EMR `ReleaseLabel` validation does not respect semantic versioning

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/test_dynamodb.py
Adds support for `INCLUDE` projections for DynamoDB indexes, per https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Projection.html
> [dynamodb2] Support include projection on indexes

- moto/server.py
As already mentioned in #3494 I verified this fix by modifying this file locally on my system and re-running the reproducer given in the issue.
The issue is that the Go SDK uses `EventBridge` in the SigV4 header instead of `events` as expected by moto.
> #3494 fix using EventBridge via Go SDK

- moto/autoscaling/models.py
- moto/cloudformation/parsing.py
- moto/ec2/models.py
- moto/ec2/responses/instances.py
- moto/ec2instanceconnect/models.py
- moto/elb/models.py
- moto/elb/responses.py
- moto/packages/boto/README.md
- moto/packages/boto/cloudformation/stack.py
- moto/packages/boto/ec2/blockdevicemapping.py
- moto/packages/boto/ec2/ec2object.py
- moto/packages/boto/ec2/elb/attributes.py
- moto/packages/boto/ec2/elb/policies.py
- moto/packages/boto/ec2/image.py
- moto/packages/boto/ec2/instance.py
- moto/packages/boto/ec2/instancetype.py
- moto/packages/boto/ec2/launchspecification.py
- moto/packages/boto/ec2/spotinstancerequest.py
- moto/packages/boto/ec2/tag.py
- moto/rds/models.py
- setup.py
- tests/test_cloudformation/test_stack_parsing.py
- tests/test_ec2/test_ec2_cloudformation.py
The `boto` library (long ago superseded by `boto3`) has not had an official
release in over two years or even a commit in the last 18 months.  Importing
the package (or indirectly importing it by via `moto`) generates a deprecation
warning.  Additionally, an ever-increasing number of `moto` users who have
left `boto` behind for `boto3` are still being forced to install `boto`.
This commit vendors a very small subset of the `boto` library--only the code
required by `moto` to run--into the /packages subdirectory.  A README file
is included explaining the origin of the files and a recommendation for how
they can be removed entirely in a future release.
NOTE: Users of `boto` will still be able to use `moto` after this is merged.
closes #2978
closes #3013
closes #3170
closes #3418
relates to …
> Remove `boto` package dependency

- .travis.yml
- travis_moto_server.sh
Focal is Ubuntu version 20.04, which is the latest available in Travis: https://docs.travis-ci.com/user/reference/linux
> Travis: Use Focal-distribution, so we no longer have to downgrade Docker

- IMPLEMENTATION_COVERAGE.md
- Makefile
- moto/settings.py
- moto/stepfunctions/models.py
- moto/stepfunctions/responses.py
- tests/test_stepfunctions/test_stepfunctions.py
This PR adds a very simplistic implementation of the [`get_execution_history`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/stepfunctions.html#SFN.Client.get_execution_history) method on the Step Function client. For now it only uses the parameter `executionArn`.
I've hard coded two histories to be returned:
**A successful execution (Presumably useful to 99% of users) with events :**
```
ExecutionStarted -> PassStateEntered -> PassStateExited -> ExecutionSucceeded
```
**A failed execution (We have a use case where we need failures in the execution history for our testing) with events:**
```
ExecutionStarted -> FailStateEntered -> ExecutionFailed
```
One can enforce which history they want with the environment variable `EXECUTION_HISTORY_TYPE`. If `SUCCESS` …
> Add basic get_execution_history implementation for Step Functions

- moto/elasticbeanstalk/responses.py
- tests/test_elasticbeanstalk/test_eb.py
Fixes #3510
There's quite a bit of hardcoded stuff in `responses.py` (e.g. aws account_id) that I may try to address in a future PR, but this fixes the immediate problem.
> Fix: elasticbeanstalk ApplicationArn does not contain ApplicationName

- tests/test_iam/test_iam.py
There were only two of these left after the migration to pytest, so I refactored them to be a bit more explicit in their assertions.
> Refactor tests marked `xfail` to use proper assertions

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/test_dynamodb.py
Fixes #3506 
The core of this issue is a lack of input validation (raised in #3231).
Until that's fixed, there are two choices when determining the data type: 
1) check which type is supplied by the user
2) check the type of the user-supplied value.
As the user-supplied value of a StringSets might be a list, we have to accept the type supplied by the user.
When proper validation is implemented, and we know 1) and 2) match up, we can refactor this entire logic flow to always accept the type supplied by the user.
> DynamoDB - Allow StringSets to be passed to update_item()

- moto/ecs/exceptions.py
- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
There are two fundamental changes to behavior in this PR that brings the Mock ECS implementation more in line with the behavior of real ECS:
- For many actions, the "default" cluster is now passed if a cluster is not provided. Most notably, this (correctly) changes the behavior of Mock ECS's ListTasks action to only list tasks for a single cluster.
- Many exceptions have been changed from custom moto exceptions to mirror the actual ECS exception.
I expect that both of these could represent breaking changes to users' tests - but they're changes that better represent the actual behavior of ECS.
This does not provide full coverage of exceptions. In general, I ran these operations against actual ECS resources and cross-referenced the documentation to figure out what actual exceptions should …
> Pass the default ECS cluster and raise accurate exceptions

- tests/test_stepfunctions/test_stepfunctions.py
These tests were passing with `TZ=UTC`, but under a non-UTC timezone they were failing:
```
E       AssertionError: given
E       X = [{'timestamp': datetime.datetime(2020, 1, 1, 0, 0, tzinfo=tzutc()), …}, …]
E           and
E       Y = [{'timestamp': datetime.datetime(2020, 1, 1, 0, 0, tzinfo=tzlocal()), …}, …]
E       X[0]['timestamp'] != Y[0]['timestamp']
```
With this fix, they pass either way.
Cc @ciaranevans, who introduced these tests in #3507.
> test_stepfunctions: Fix failures under non-UTC timezone

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Applies the user credentials pattern from the ADMIN_NO_SRP_AUTH flow
to the ADMIN_USER_PASSWORD_AUTH auth flow for Cognito admin_initiate_auth
requests.
2nd attempt, hopefully the build works this time.
> Support cognito admin user password auth flow

- moto/managedblockchain/responses.py
- moto/managedblockchain/urls.py
- moto/managedblockchain/utils.py
- moto/sqs/models.py
- requirements-dev.txt
- setup.py
The AWS HTTP API changed for the ManagedBlockchain service.
TLDR: For some actions, the memberId variable is no longer part of the REST URL, but is passed through as a query-string or in the body.
These changes came into effect as of botocore >= 1.19.41: https://github.com/boto/botocore/commit/5a79e3e757e92f68565dafeeb86dee429774cfe9#diff-7114261314a2eb504c53bfc9322e5104a6dd124518e7a51f0fcebdf93facb823R58
The changes in this PR ensure moto support both API versions.
Also includes a downgrade for the mock-requirement, to make Travis until we have a more permanent fix.
> Fix Blockchain to work with new API

- moto/ec2/responses/vpcs.py
- tests/test_ec2/test_vpcs.py
* Properly coerce `privateDnsEnabled` to boolean value when parsing requests.
* Per AWS spec, default `privateDnsEnabled` request value to `True`.
* Properly serialize `privateDnsEnabled` as boolean value in responses.
* Add test coverage.
Ref: #3540
> Fix: handling of boolean value `privateDnsEnabled` in ec2:VpcEndpoint

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
Fixes #3551 
I also implemented the missing logic for launchType to `create_task_set`. And I changed the tests I touched to use the `should` syntax instead of `asserts`.
> Add launchType parameter to ECS

- setup.py
From Python Safety:
Cryptography 3.3 no longer allows loading of finite field Diffie-Hellman parameters of less than 512 bits in length. This change is to conform with an upcoming OpenSSL release that no longer supports smaller sizes. These keys were already wildly insecure and should not have been used in any application outside of testing.
> Bump cryptography library

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_ecs/test_ecs_cloudformation.py
The mocked response for ECS RegisterTaskDefinition has drifted from what actually returns when run against a real ECS endpoint. I created a minimal task definition for both EC2:
```python
>>> ecs.register_task_definition(
family="moto",
containerDefinitions=[
{
"name": "hello_world",
"image": "hello-world:latest",
"memory": 400
}
]
)["taskDefinition"]
{'taskDefinitionArn': 'arn:aws:ecs:us-east-1:************:task-definition/moto:1',
'containerDefinitions': [{'name': 'hello_world',
'image': 'hello-world:latest',
'cpu': 0,
'memory': 400,
'portMappings': [],
'essential': True,
'environment': [],
'mountPoints': [],
'volumesFrom': []}],
'family': 'moto',
'revision': 1,
'volumes': [],
'status': 'ACTIVE',
'placementConstraints': [],
'compatibilities': ['EC2']}
```
and Fargate:
```python
>>> …
```
> More accurately mock ECS RegisterTaskDefinition

- moto/cognitoidentity/models.py
- tests/test_cognitoidentity/test_cognitoidentity.py
From `None` to the `identity_pool_id`.
> Fix ResourceNotFoundError exception message

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/test_dynamodb.py
This handles the add-to-list case using the legacy `AttributeUpdates` parameter.
* Added test coverage.
* Verified against real AWS backend.
Closes #3561
> Implement Add to List for dynamodb:UpdateItem

- moto/awslambda/responses.py
- tests/test_awslambda/test_lambda.py
This adds support for `boto3.client('lambda').get_function_configuration(FunctionName='blalbla')`
> Add get_function_configuration support for Lambda

- moto/events/exceptions.py
- moto/events/models.py
- tests/test_events/test_events.py
Fixes #3384 
It is a quite interesting behaviour of the `put_events` endpoint, because each event is validated separately and the status is send back for all of them.
> Add validation to put_events

- tests/__init__.py
- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_autoscaling_cloudformation.py
- tests/test_autoscaling/test_policies.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
- tests/test_cloudformation/test_validate.py
- tests/test_ec2/test_amis.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_elastic_block_store.py
- tests/test_ec2/test_elastic_ip_addresses.py
- tests/test_ec2/test_general.py
- tests/test_ec2/test_iam_instance_profile_associations.py
- tests/test_ec2/test_instances.py
- tests/test_ec2/test_regions.py
- tests/test_ec2/test_route_tables.py
- tests/test_ec2/test_server.py
- tests/test_ec2/test_spot_fleet.py
- tests/test_ec2/test_spot_instances.py
- tests/test_ec2/test_subnets.py
- tests/test_ec2/test_tags.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Unknown image ID's would show this warning:
`PendingDeprecationWarning: Could not find AMI with image-id:ami-123456, in the near future this will cause an error.\nUse ec2_backend.describe_images() to find suitable image for your test`
The build log was completely full of warnings like this.
Not all warnings are gone with this change, but it's a start.
> Tech Debt - Remove unknown ImageID in internal tests

- moto/s3/responses.py
- tests/test_s3/test_s3.py
Fixes #2965 
Special use case in S3 - when specifying an empty Range-argument, it will ignore it, returning the full object. This PR mimicks this edge case in moto.
> S3 - GetObject - Treat empty Range-argument as a regular GET

- moto/apigateway/models.py
- moto/core/models.py
- tests/test_apigateway/test_apigateway.py
- tests/test_sns/test_publishing_boto3.py
Instead of modifying `responses._default_mock`, create our own `responses.RequestsMock` object that we can modify as needed without interfering with other users of the `responses` library.
Fixes #3264.
> Leave the global responses configuration alone

- tests/test_awslambda/test_lambda.py
This test is flaky, but when it fails we don't get any indication as to why.
This commit ensures that the reason for failure will be part of the assertion
message.
Once we have information about why this test fails, we can troubleshoot further
and hopefully come up with a permanent fix.
> Expose contextual data when Lambda test fails

- moto/cloudformation/models.py
- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Currently, any operation that uses 'get_stack' method from 'CloudFormationBackend' class
will fail with AttributeError or jinja2 exception if ran against non-existing stack(created/deleted)
To fix the issue I explicitly raised a 'ValidationError' exception.
Added tests for boto and boto3 responses.
Fixes  #3558
> Added explicit exception raise when no stack found.

- moto/awslambda/models.py
- moto/awslambda/responses.py
- moto/awslambda/urls.py
- moto/awslambda/utils.py
- tests/test_awslambda/test_lambda.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
This adds basic support for layers to the lambda resource.
Adding support for `boto3.client('lambda').publish_layer_version(...)` and `boto3.client('lambda').list_layer_versions(LayerName='')` and also supporting Layer information passed to functions.
It does **not** implement all the layers API and it is **not** adding the layers to the lambda invocation simulation.
Fixes: #3188
> adding layers support for lambda backend

- moto/server.py
When running alone as pid 1 in a container, most signals that would
cause the process to exit by default, are instead ignored by default.
The container runtime will send SIGTERM, wait 10 seconds, then send
SIGKILL, which will work, but moto.server can exit much faster if
it has an explicit SIGTERM handler.
------
An alternative way to fix the slow-container-stop problem is to use a separate "init" process, which forwards signals to the actual container command running as a child process (which then has PID != 1). You can get very easily get this with "docker run --init ..." which uses the "tini" init process included in docker ... but kubernetes doesn't offer this option, and the separate init process isn't _really_ necessary.
------
If I could switch from `werkzeug.serving.run_simple()` …
> server: explicit signal handler for SIGINT and SIGTERM

- moto/ec2/exceptions.py
- moto/ec2/models.py
- moto/ec2/responses/amis.py
- requirements-dev.txt
- tests/test_ec2/test_amis.py
* Bump `botocore` to minimum version that supports TagSpecifications for this action.
* Add test coverage.
Closes #3602
> Add TagSpecification support to ec2:CreateImage

- moto/ec2/models.py
- moto/ec2/utils.py
- tests/test_ec2/test_amis.py
Return `None` instead of an empty string when the tag key does not exist
and replace the falsy check with a more explicit `is None`, which allows
empty string values to correctly pass through the filter comparator.
Behavior confirmed against a real AWS backend.
Closes #3603
> Fix ec2 filter by empty tag value

- moto/awslambda/models.py
- tests/test_awslambda/test_lambda.py
If `InvocationType` is not provided to `boto.client("lambda").invoke`, then the request header `x-amz-invocation-type` is not present, which breaks an assumption in the model's implementation `moto.awslambda.models.LambdaFunction.invoke`.
In the tests, this results in the response not having a `LogResult` key (when `LogType="Tail"`), or trying to delete a non-existent response header key `x-amz-log-result` (when `LogType` is not provided).
This PR updates the assumption to match the current API definition.
> Assume synchronous Lambda invocation by default

- tests/test_ec2/test_instances.py
- tests/test_ec2/test_regions.py
- tests/test_ec2/test_tags.py
This commit eliminates the following warning (of which there are currently dozens):
../boto/ec2/connection.py:582:
PendingDeprecationWarning: The current get_all_instances implementation will be replaced with get_all_reservations.
`boto` isn't likely to ever make good on this warning, but doing the replacement will
declutter the `moto` test output.
> Address `boto` deprecation warnings

- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_autoscaling_cloudformation.py
- tests/test_autoscaling/test_elbv2.py
- tests/test_autoscaling/test_launch_configurations.py
- tests/test_cloudformation/test_cloudformation_depends_on.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
Moto's implementation of autoscaling:CreateLaunchConfiguration is a little too loose,
allowing the ImageId parameter to be omitted and defaulting it to None, which results
in dozens of deprecation warnings:
`PendingDeprecationWarning: Could not find AMI with image-id:ami-123456, in the near future this will cause an error.`
This commit refactors calls to CreateLaunchConfiguration to explicitly pass in a known
AMI ImageId in order to avoid these warnings.
The integrity of the tests is unaffected by this change.
> Tech Debt - Use known AMI in internal tests

- setup.py
PyPI does not run `setup.py` separately for each Python version to resolve requirements, so these conditional requirements need to be properly specified in the metadata, not in code.
> Use environment markers for Python 2 dependency pins

- requirements-dev.txt
Most of these were already pulled in via `-r requirements.txt` → `-e .[all]`; add the remainder with `-e [all,server]`.
> requirements-dev.txt: Remove requirements copied from setup.py

- .github/workflows/build.yml
* Trigger workflow on any push or pull request.
* Conditionally run Codecov Upload and Deploy *only* on `spulec/moto` repository.
This allows contributors to get CI results on their forked repo before
submitting PRs to `moto`.  Previously, forked repos could not run the
actions on any non-master branch and the master branch workflow
would fail (rightfully) on the steps that should only be run on the
main repo (and require tokens/secrets).
> Enable GitHub Actions to run successfully on forks

- tests/test_sagemaker/test_sagemaker_notebooks.py
- tests/test_ssm/test_ssm_boto3.py
Fix: broken build with release of botocore 1.19.62
The latest release of `botocore` (1.19.62) makes changes to the parameter
validation code, which for some reason was also covered by a couple of
`moto` tests.
These tests, when run, do not execute any `moto` code.  They fail the
parameter validation check in `botocore`, which raises an exception
before ever sending a request.  These tests do not cover or verify
any `moto` behavior and have been removed.
Ref: https://github.com/boto/botocore/commit/ff8ae76ecc0ee29713c51fd2a17c945d776dc44b
Closes #3627
> ** Merge me first - I fix the build! **

- moto/awslambda/models.py
- moto/batch/models.py
- tests/__init__.py
- tests/test_autoscaling/test_autoscaling.py
- tests/test_cloudformation/fixtures/route53_ec2_instance_with_public_ip.py
- tests/test_cloudformation/fixtures/single_instance_with_ebs_volume.py
- tests/test_cloudformation/fixtures/vpc_single_instance_in_subnet.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
- tests/test_core/test_decorator_calls.py
- tests/test_core/test_nested.py
- tests/test_ec2/test_instances.py
- tests/test_elb/test_elb.py
- tests/test_elbv2/test_elbv2.py
- tests/test_opsworks/test_instances.py
- tests/test_ssm/test_ssm_boto3.py
- tests/test_ssm/test_ssm_cloudformation.py
This should just about do it for cleaning up the pytest output.
Commits are atomic and probably best left un-squashed for git blame/history purposes.
> Address pytest warnings

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
This argument allows you to delete a service even when its DesiredCount is non-zero.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.delete_service
> Add support for the force argument for ecs.delete_service

- moto/elbv2/models.py
- tests/test_elbv2/test_elbv2.py
The `botocore` response parsers are forgiving when it comes to timestamps,
but a real AWS backend does return time zone details for this attribute.
Verified failure/fix using the Go repo included in the issue report.
Fixes #3516
> Fix: Golang aws-sdk fails to parse elbv2:CreateLoadBalancer response

- tests/test_applicationautoscaling/test_validation.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_ec2/test_flow_logs.py
- tests/test_ec2/test_subnets.py
- tests/test_ecr/test_ecr_boto3.py
- tests/test_elbv2/test_elbv2.py
- tests/test_kms/test_kms_boto3.py
- tests/test_rds2/test_rds2.py
- tests/test_s3/test_s3.py
These tests, when run, do not execute any `moto` code. They fail the
parameter validation check in `botocore`, which raises an exception
before ever sending a request.  These tests do not cover or verify
any `moto` behavior and have been removed.
* Where possible, tests were modified to exercise `moto` backend code 
instead of `botocore` code.
* The weird diff in `test_elbv2` is because the original commit that added 
`test_fixed_response_action_listener_rule_validates_status_code` accidentally 
copy/pasted the test into itself one indentation level. (https://github.com/spulec/moto/commit/2b8bdc9bca85d97852e0bd9b4fddccd009554d35)
> Remove redundant test code

- moto/sns/exceptions.py
- moto/sns/models.py
- tests/test_sns/test_application_boto3.py
Currently the response to `get_endpoint_attributes` for a non existent endpoint
differ from boto and moto, in the following way (shown in JSON instead of xml
for shortness):
* **boto**: `{ErrorResponse:  { Error: { Code: "... ", Type: "... ", Sender: "..." }}`
* **moto**: ` { ErrorResponse: { Errors: [ { Error: { Code: "... ", Type: "... ", Sender: "..." }}]}}`
The template used to generate the NotFound error was the default for [RESTError](https://github.com/spulec/moto/blob/master/moto/core/exceptions.py).
Moreover, although `RESTError` has another template called [SINGLE_ERROR_RESPONSE](https://github.com/spulec/moto/blob/master/moto/core/exceptions.py#L8). 
That at first sight looks like the right one, it lacks the `ErrorResponse` node at the root
of the XML, which causes an error …
> Update SNS get_endpoint_attributes response for Not Found endpoints #3477

- README.md
- Adds a link to moto’s PyPI page
- Makes the “Python Versions” badge unclickable (nobody wants to see the badge image in a new tab when clicking a badge)
- Adds a link to PyPIstats for download stats
> Link remaining badges in README

- moto/sns/exceptions.py
- moto/sns/responses.py
In e9dc5ed a custom error template was added to correct the response
returned by get_endpoint_attributes for a non-existent endpoint.
However, after some more inspection, it was found that a valid template
already existed in moto/sns/responses.py. This commit removes the 
template introduced in e9dc5ed and takes into use the existing template.
It is a marginal improvement, but helps keeping a cleaner code base.
fixes #3646
> Remove duplicate template of SNS error response #3646

- moto/elbv2/models.py
- tests/test_elbv2/test_elbv2.py
Fixes `create_rule` and `describe_listener` behaviors to more closely mock actual AWS behavior.
> (fix) Fixes #3648

- moto/redshift/models.py
- moto/redshift/responses.py
- tests/test_redshift/test_redshift.py
Add the KmsKeyId property when creating a cluster so that it is also returned when querying the describe_clusters endpoint.
Resolves https://github.com/spulec/moto/issues/3665
> Add KmsKeyId to Redshift Cluster

- moto/s3/responses.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_server.py
…irect
- Add the bucket/key values to the redirect url like s3 does, which
supports code that relies on the key value being there on the
redirect.
- Add support for replacing ${filename} in the key value with the actual
filename from the form upload.
See Issue #3667
> #3667: Update the s3 post functionality to better support success_action_redirect

- moto/forecast/models.py
I noticed in testing today that we weren't using `six` for the `iteritems` import. This avoids the needless dependency on `future` in this file by using `six` instead. This matches how `iteritems` is imported across the remainder of the project.
> moved iteritems backwards compatibility to six

- moto/cloudformation/responses.py
- moto/cloudwatch/responses.py
- moto/ses/responses.py
Fixing invalid XML node order in some response, the node order is important for valid XML unmarshalling in the Java AWS SDK v2.
Par of unmarshalling code in Java AWS SDK v2
```java
XmlElement resultRoot = hasResultWrapper ? document.getFirstChild() : document;
``` 
Closes #3645
> Fix response parsing error on Java SDK v2 for CW GetMetricData (#3645)

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Adds support for the following resources:
- AWS::RDS::DBInstance
- AWS::RDS::DBSnapshot
Closes #3651
> Add ResourceGroupsTaggingAPI Support for RDS Resources

- moto/swf/models/activity_task.py
- moto/swf/responses.py
- tests/test_swf/models/test_activity_task.py
- tests/test_swf/responses/test_activity_tasks.py
- tests/test_swf/responses/test_decision_tasks.py
While using moto swf with AWS Java Flow SDK 1.11.22, I found some incompatibilities with activity heartbeatTimeout and decision/activity polling.
When activities don't define a heartbeatTimeout, moto/swf/models/activity_task.py fails and returns:
`ValueError: invalid literal for int() with base 10: 'NONE'`
when this code runs:
`
heartbeat_timeout_at = self.last_heartbeat_timestamp + int(
self.timeouts["heartbeatTimeout"]
)
`
When poll_for_decision_task and poll_for_activity_task in moto/swf/responses.py execute, they currently return an empty string for taskToken:
`return json.dumps({"startedEventId": 0, "taskToken": ""})`
or
```
return json.dumps(
{"previousStartedEventId": 0, "startedEventId": 0, "taskToken": ""}
)
```
But this results in an exception thrown by my Java decision/activity …
> Fix heartbeatTimeout of NONE and polling responses when there are no tasks

- moto/core/utils.py
- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_server.py
Hi, when we point [aws-sdk-v2-go](https://github.com/aws/aws-sdk-go-v2)'s DynamoDB client at the Moto server, the SDK complains that the responses don't have the `X-Amz-Crc32` header. This PR adds the decorator which populates those checksums on the responses from the DynamoDBv2 API.
> Add CRC32 to DynamoDB responses

- moto/rds2/exceptions.py
- tests/test_rds2/test_filters.py
- tests/test_rds2/test_rds2.py
Just some minor clean up of some things I found while working on something else.
Changes the DBInstanceNotFound message to match what is returned from a real AWS backend.
Removes a duplicate test that was not getting run (and wouldn't have succeeded if it had run).
Makes the existing test (that was duplicated) a little more explicit.
> Minor RDS Clean up

- moto/autoscaling/models.py
- moto/autoscaling/responses.py
- tests/test_autoscaling/test_launch_configurations.py
Something I discovered when cleaning up the "missing AMI" warnings (#3620) was that the implementation of CreateLaunchConfiguration was a bit too permissive.
AWS requires certain parameters to be mutually inclusive.
Moto wasn't doing anything with the InstanceId parameter, which is now made clear with a TODO.
> Improve autoscaling:CreateLaunchConfiguration request validation

- moto/ec2/utils.py
- tests/test_ec2/test_instances.py
Closes: https://github.com/spulec/moto/issues/3693
One thing to note, if an EC2 instance is created without a subnet, that instance is _not_ searchable with this addition (or even using `vpc-id` as the filter) `aws --endpoint-url=http://localhost:5000 --region eu-west-1 ec2 run-instances --output json`
```json
{
"Groups": [
{
"GroupName": "default",
"GroupId": "sg-245f6a01"
}
],
"Instances": [
{
"AmiLaunchIndex": 0,
"ImageId": "None",
"InstanceId": "i-dad0ab2131fc1975f",
"InstanceType": "m1.small",
"KernelId": "None",
"KeyName": "None",
"LaunchTime": "2021-02-14T21:49:14+00:00",
"Monitoring": {
"State": "enabled"
},
"Placement": {
"AvailabilityZone": "eu-west-1a",
"GroupName": "",
"Tenancy": "default"
},
"PrivateDnsName": "ip-10-162-83-21.eu-west-1.compute.internal",
"PrivateIpAddress": …
```
> EC2: Enhancement: implement EC2 instance filtering by `subnet-id`  #3693

- moto/events/models.py
- tests/test_events/test_events.py
There is a missing `return True` for the positive match case in
matches_pattern, causing all valid patterns to fail.
> events: fix archive event pattern match check

- .github/workflows/build.yml
- codecov.yml
- requirements-tests.txt
- setup.cfg
When enabling coverage, the XRay tests are throwing an error in Py2:
INTERNALERROR> SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
Edit:
This was a known bug in coverage 5, and was already prevented in moto by pinning the coverage to 4.5.
After moving to codecov.io, we needed pytest-cov - which required coverage > 5.
The downgraded pytest-cov that is now in place for Py2 does not require coverage > 5, so it's back to using the tried and tested coverage 4.5
> Enable Py2 test coverage

- moto/dynamodb2/models/__init__.py
- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb.py
> Fix: DynamoDB:GetItem throws wrong error when table doesn't exist

- moto/awslambda/models.py
- moto/batch/models.py
- moto/settings.py
- moto/utilities/docker_utilities.py
- tests/test_utilities/test_docker_utilities.py
Podman supports all Docker APIs used in moto since version 3.0. Note
that Podman requires pulling the image before creating a container
using a fully-qualified image name (e.g., "docker.io/library/busybox"
instead of "busybox").
Test plan:
$ podman system service -t 0
$ DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock" pytest
Fixes https://github.com/spulec/moto/issues/3276
> Support Podman for mocking Lambda

- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
'FakeStackSet' does not have a 'stackset_id' attribute, the current implementation silently returns a blank ID.
> Update stackset create operation to correctly return the resource's ID.

- moto/dynamodb2/parsing/executors.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_dynamodb2/test_dynamodb_executor.py
When deleting last element(s) of a set, the attribute itself is cleared from the container. This is fixing support for specifying such attributes through attribute name placeholders in update expressions.
> dynamodb: fix deleting last set element (w/attr name)

- moto/cloudformation/models.py
- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
StackSets can be described/deleted using their name or id (as per docs [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.describe_stack_set) and [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.delete_stack_set)). 
Updating StackSet parameters should support omitting providing a value and specifying a `UsePreviousValue` flag [instead](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.update_stack_set
), as it does for Stack updates. Refactored the mechanism for resolving the parameters to be shared by both FakeStacks and FakeStackSets.
> Fix stackset describe/delete. Fix stackset update.

- moto/ecs/models.py
- tests/test_ecs/test_ecs_boto3.py
Also I found extra tests for describe_task_definition and deregister_task_definition that were not being run,
so I changed their names so they are found by pytest and made them pass.  I also added checks to them for the new
status field.
> Add the status field to ECS task definitions

- moto/iam/responses.py
- tests/test_iam/test_iam.py
`list_roles` and `create_roles` should return the `Description` field if it is non-null.
> Fixes for IAM Role Description field in responses from list_roles and create_roles

- moto/apigateway/models.py
- moto/apigateway/responses.py
- moto/batch/models.py
- moto/elb/models.py
- moto/elb/responses.py
- moto/opsworks/models.py
- moto/server.py
- tests/test_apigateway/test_apigateway.py
Added update_usage_plan feature and fixed some of the lint errors
> added feature update_usage_plan and fixed some lint errors

- IMPLEMENTATION_COVERAGE.md
- moto/apigateway/models.py
- moto/apigateway/responses.py
Changes method names to ensure the implementation is recognized  by the implementation coverage script
> Update ImplementationCoverage for APIGateway

- .github/workflows/release.yml
- requirements-dev.txt
- update_version_from_git.py
This workflow would automate the release flow.
For this to work, we do need to add Docker credentials to the repository secrets:
DOCKERHUB_USERNAME
DOCKERHUB_TOKEN
(https://docs.docker.com/docker-hub/access-tokens/)
Before a release:
Manual steps required:
- Create an entry in CHANGELOG
To create a release:
Go to https://github.com/spulec/moto/actions/workflows/release.yml
Click 'Run workflow', and type the version that you want to release
Steps automated with this workflow:
- Validation that the version does not exist yet as a tag
- Validation that the version does have an entry in the Changelog
- Upload to PyPi
- Tag Github
- Upload to Docker
- Increase the version in moto/__init__.py
Example run:
https://github.com/bblommers/moto/runs/1989056691
> Automate releases

- moto/ec2/models.py
A few days ago Osaka became a regular AWS region, so I added the missing AZs.
https://aws.amazon.com/about-aws/whats-new/2021/03/announcing-the-newly-expanded-aws-asia-pacific-osaka-region/
> Fix Osaka region problem

- moto/kinesis/models.py
- tests/test_kinesis/test_kinesis.py
The Record class was already capturing a unix timestamp, but it was incorrectly
converting it to ISO format when sending back to the client.
Updating the model to return the correct timestamp necessitated a minor change
to one of the tests because `botocore` converts non-timezone aware timestamps
to local time.
Defect and fix were verified using the example Java code referenced in the 
issue description.
Fixes #3749
> Fix: `ApproximateArrivalTimestamp` should be epoch with millisecond precision

- moto/route53/responses.py
- tests/test_route53/test_route53.py
DNSName key retrieval for list-hosted-zones-by-dns-name per https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListHostedZonesByName.html#API_ListHostedZonesByName_RequestSyntax
> DNSName key retrieval for list-hosted-zones-by-dns-name

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Similar to `admin_create_user` (#2357), the `sign_up` method in the Cognito identity provider client should raise a `UsernameExistsException` if a user already exists within the user pool
> Cognito IdP: Raise UsernameExistsException from sign_up when user exists

- moto/s3/responses.py
- tests/test_s3/test_s3.py
Currently trying to set ACL on a key does not exist fails with 
```
AttributeError: 'NoneType' object has no attribute 'set_acl'
```
S3 returns 404 (`NoSuchKey`) if the object referenced by the key does not exist
> S3 - Make put-object-acl return 404 if the object does not exist

- moto/ses/models.py
- tests/test_ses/test_ses_boto3.py
When sending templated emails
Closes #3783
> Raise `TemplateDoesNotExist` if template does not exist

- moto/ec2/models.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
Adding physical_resource_id in SubnetRouteTableAssociation, Route and NatGW classes in `moto/ec2/models.py` in order to avoid https://github.com/localstack/aws-cdk-local/issues/44
> adding physical_resource_id in SubnetRouteTableAssociation, Route and NatGW classes

- .github/workflows/build.yml
- update_version_from_git.py
Parsing the msg was quicker, but also uglier and more difficult, as the message will differ depending on whether it's a straight merge or squashed merge.
Still outstanding: 
If there are multiple associated PR's, we should leave a message on all PR's that have been merged
> Admin - Use GraphQL to find PR, instead of commit msg

- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
See #3799
When using the compact API this would not be an issue, since `Key("whatever").eq("the-key")
& Key("range-attribute").begins_with("some_text")` would use "begins_with" behind the scenes. 
The same goes for *between*, which would set it to uppercase.
Almost all tests use the compact version, and both conditions are thoroughly being tested.
However, KeyConditionExpression "text" syntax is also supported allowing something like `"KeyConditionExpression="key_attribute = :key_value and BEGINS_WITH(range_attribute, :some_text )"`
This should raise a controlled exception:
```botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Invalid KeyConditionExpression: Invalid function name; function: BEGINS_WITH```
However, moto would raise an …
> Improve dynamodb query case sensitivity

- moto/ec2/models.py
- tests/test_ec2/test_security_groups.py
The `InvalidPermission.Duplicate` error was already implemented for inbound rules,
but AWS also returns this error for duplicate outbound rules.
Very minor changes were needed on existing tests that were adding duplicate
outbound rules (when testing the RulesPerSecurityGroupLimitExceeded error).
> Raise error when adding duplicate egress rule to ec2:SecurityGroup

- moto/ec2/models.py
- tests/test_ec2/test_security_groups.py
Behavior and error code/message confirmed against real AWS backend.
Fixes #1676
> Return error when trying to add rules to a non-existent security group

- moto/s3/responses.py
- moto/s3/utils.py
- moto/settings.py
- tests/compat.py
- tests/test_s3/test_s3_utils.py
- tests/test_s3/test_server.py
This PR fixes #3795 by checking the `S3_IGNORE_SUBDOMAIN_BUCKETNAME` environment variable in the same way `bucket_name_from_url` does in utils.py
With this PR, performing the test as described in #3795 creates the bucket as expected.
Also a unittest was added to test the change
> Check S3_IGNORE_SUBDOMAIN_BUCKETNAME environment variable

- moto/events/models.py
- tests/test_events/test_events.py
Fixes #3803 by converting `event_bus_name` (which could be an ARN) to a simple name when sending an event to a Rule's targets. This is verified through a new test that constructs an Archive, sends an event where EventBusName is an ARN, and confrims that the event is routed to the Archive.
> Modify Rule.send_to_targets() to handle event_bus_name as ARN

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
Fixes #3794 by checking `put_parameter()` value for an empty string and raising a ValidationException if this is the case.
> Modify SSM `put_parameter()` to raise ValidationException if value is empty string

- moto/events/models.py
- tests/test_events/test_events.py
Fixes #3807. Updates default `Rule` ARN building logic to use the `MOTO_ACCOUNT_ID` environment variable. Updates relevant `describe_rule()` unit test.
> Use `MOTO_ACCOUNT_ID` when building default `Rule` ARN

- moto/events/models.py
- moto/events/responses.py
- tests/test_events/test_events.py
The rule ARN for rules added to a custom event bus have the event bus name prefixed.
Additionally  added `ManagedBy` and `CreatedBy` for event rules.
Also quite interesting scheduled events can only be added on the default event bus.
> Fix events rule ARN for custom event bus

- moto/events/models.py
- moto/events/responses.py
- tests/test_events/test_events.py
- tests/test_events/test_events_targets.py
I also cleaned up the targets methods a bit.
During implementation I realised that the rules are stored for all Event Buses centrally, which is kind of wrong, because they are bound to the specific Event Bus. In the past there was only one (default), so it was ok. @bblommers should I refactor it and move the list of rules to the specific Event Bus?  If yes, then I would create a dedicated issue and implement it via a separate PR.
> Add events target integration for sqs queue

- moto/support/models.py
- tests/test_support/test_support.py
> Support - Allow describe_cases without any params

- moto/utilities/utils.py
Apparently this breaks on Windows-7 machines, as the default encoding is not UTF-8
Fixes #3772
> Support - Ensure advisors_checks-file is properly encoded

- moto/events/models.py
- tests/test_events/test_events.py
Fixes #3831  by adding "exists" filtering functionality when determining to route an event to an `Archive` using an `EventPattern` and adding a test case. I've also refactored the existing `Archive` filtering functionality to make it easier to add the remaining filter types and refactored the existing `Archive` filtering tests to make them more isolated.
> Add exists filtering functionality to `Archive`

- moto/iam/responses.py
- tests/test_iam/test_iam.py
- fixing issue where the get_user method does not return tags
Fixes #3828
Documentation:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.get_user
> IAM - get_user() #3828

- moto/events/models.py
- tests/test_events/test_events.py
Adds logic for "prefix" and "numeric" filters in an `Archive` `EventPattern` with related test cases. Also removes a rogue print and reverts to defaulting to `True` if a named filter is not implemented
> Add prefix and numeric filtering logic for Archive EventPattern

- moto/cloudformation/parsing.py
- moto/sagemaker/models.py
- tests/test_sagemaker/test_sagemaker_cloudformation.py
Issue: https://github.com/spulec/moto/issues/3568
Updates the `FakeSagemakerNotebookInstance` class to inherit from `CloudFormationModel` and adds tests around the creation, deletion, and updating of a Notebook Instance via CloudFormation templates.
> Add CloudFormation support for SageMaker Notebook Instances

- moto/acm/models.py
- moto/settings.py
- tests/test_acm/test_acm.py
We are using AWS lambda to create/delete the acm certificates and doing the validation via DNS, when writing unittest for these lambdas we'll have to wait 60 seconds. This PR make it possible to customize this wait time.
> Make it possible to customize the ACM cert validation wait time.

- moto/sagemaker/models.py
- tests/test_sagemaker/test_sagemaker_cloudformation.py
Issue: https://github.com/spulec/moto/issues/3846
- Updates the `FakeSageMakerNotebookInstanceLifecycleConfig` class to inherit from `CloudFormationModel` and adds tests around the creation, deletion, and updating of a Notebook Instance via CloudFormation templates.
- Additionally, I reduced the overhead for adding the "create", "get_attr", and "delete" CloudFormation tests by using `pytest.mark.parametrize` because these tests will be similar across the SageMaker resources. I kept the "update" tests unparameterized since needing to know how to update and how to inspect the updates varies across the SageMaker resources.
> Add CloudFormation support for SageMaker Notebook Instance Lifecycle Configs

- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/cloudformation_test_configs.py
- tests/test_sagemaker/test_sagemaker_cloudformation.py
Issue: https://github.com/spulec/moto/issues/3846
- Updates the `Model` class to inherit from `CloudFormationModel` and adds tests around the creation, deletion, and updating of a Model via CloudFormation templates.
- Although the refactoring of SageMaker CloudFormation tests in https://github.com/spulec/moto/pull/3855 reduced the redundancy in the number of tests, I wasn't satisfied with all of the repeated data being passed into the `pytest.mark.parametrize` decorator. Thus, I decided to create a simple interface for test configuration objects to encapsulate all of the necessary data needed in the `create`, `get_attr`, and `delete` test parameterizations.
*Side-note*: I'm still thinking through how to make the `update` tests less redundant but I may just keep these separate and out of …
> Add CloudFormation support for SageMaker Models

- moto/sagemaker/models.py
- tests/test_sagemaker/cloudformation_test_configs.py
- tests/test_sagemaker/test_sagemaker_cloudformation.py
Closes https://github.com/spulec/moto/issues/3846
- Updates the `FakeEndpoint` and `FakeEndpointConfig` classes to inherit from `CloudFormationModel` and adds tests around the creation, deletion, and updating of an Endpoint/EndpointConfig via CloudFormation templates.
- Also needed to add the `run_setup_procedure` method to the test configuration class so that I was able to easily add prerequisite SageMaker resources during the parametrized CloudFormation tests.
- Typo fixes from my previous contributions.
> Add CloudFormation support for SageMaker Endpoint Configs and Endpoints

- moto/route53/models.py
- moto/route53/responses.py
- tests/test_route53/test_route53.py
According to the [docs](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html) resource record sets should have the following order:
```
ListResourceRecordSets sorts results first by DNS name with the labels reversed, for example:
com.example.www.
Note the trailing dot, which can change the sort order when the record name contains characters that appear before . (decimal 46) in the ASCII table. These characters include the following: ! " # $ % & ' ( ) * + , -
When multiple records have the same DNS name, ListResourceRecordSets sorts results by the record type.
```
Also API should return 400 Bad Request if you specify only `Type`.
> sort Route53 resource record sets

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
It doesn't actually use or verify these roles, but I didn't see a good way to do that in the `ecs_backend`.
> Add the abilitiy to set ECS task definition task role and execution role arns

- .github/workflows/build.yml
- requirements-dev.txt
This lxml-dependency is only required for the scaffold-script, not for regular development, so pinning it to any specific version is not necessary as far as I can tell.
It also doesn't support Python 3.8 and 3.9 natively, so unpinning it will simplify `make init` for many people
> Unpin LXML dependency

- moto/logs/models.py
- tests/test_logs/test_logs.py
Plagiarizing freely from @bpandola and his PR #3398, I have
modified the pagination for FilterLogEvents to more closely follow
the real AWS behaviour.
Fixes #3882
> Fix: `nextToken` value in `logs:FilterLogEvents` response

- moto/s3/exceptions.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
Fixes exception that is raised if a versionID is not found for calls to s3.
> S3 - Fix exception for missing versionID

- moto/ec2/models.py
- moto/ec2/responses/network_acls.py
- tests/test_ec2/test_network_acls.py
Added `ownerId` to response: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNetworkAcls.html#API_DescribeNetworkAcls_Examples
I thought about adding support for the filter to the parent "TaggedEC2Resource" because many ec2 resources do support it, but wasn't sure if that would be welcome. Somebody would have to check that all the subclasses support it, and possibly add logic to prevent some subclasses from using that filter.
My previous contributions to this project:
https://github.com/spulec/moto/pulls?q=is%3Apr+author%3Akhneal+is%3Aclosed
> EC2 describe_network_acls: add support for owner-id filter

- moto/server.py
This is required if running as a Github Action which doesn't allow passing parameters to `docker create` but allows environment variables
> allow specifying the service as env var

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/test_cognitoidp/test_cognitoidp.py
Closes #3901
---
- Implements `set_user_pool_mfa_config`
- Implements `get_user_pool_mfa_config`
- Updates `CognitoUserPool`'s JSON representation to include `MfaConfiguration` field so that the `DescribeUserPool` endpoint remains correct
- Creates tests for the new actions
I have added some checks in the response layer to ensure that the input aligns with what boto3 expects, and then raise a `ValueError` if it doesn't. I don't see anything similar being done anywhere else, so I ask: Should I be raising a different error? Should I be checking at all? 
Thanks.
> Implement User Pool MFA Actions

- moto/logs/models.py
- tests/test_logs/test_logs.py
The old separator could be present in some of the values being concatenated.
> Fix separator in filter_log_events nextToken value.

- setup.py
This should fix #3922 and #3921. Pinning only Werkzeug doesn't solve the issue since sometimes flask dependency might be installed first creating an impossible lock state when using tools like Pipenv.
This is a temporary fix until this project upgrades to Flask 2
> Lock Flask

- .github/workflows/build.yml
- moto/managedblockchain/exceptions.py
- moto/managedblockchain/responses.py
- requirements-dev.txt
- setup.py
- tests/test_managedblockchain/test_managedblockchain_invitations.py
- tests/test_managedblockchain/test_managedblockchain_members.py
- tests/test_managedblockchain/test_managedblockchain_networks.py
- tests/test_managedblockchain/test_managedblockchain_nodes.py
- tests/test_managedblockchain/test_managedblockchain_proposals.py
- tests/test_managedblockchain/test_managedblockchain_proposalvotes.py
Fixes #3921 
With this  PR, moto will werk with both flask/werkzeug 1.x, and flask/werkzeug 2.x.
Issues encountered while trying to fix this
**Problem**: CodeCov throws an error for some builds:
`{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`
**Solution:** 
- Don't fail if this happens - we'll notice it in the report if anything goes wrong
---------------
**Problem**: `test_s3_server_post_without_content_length ` fails with werkzeug 2.x/flash 1.x
**Solution**: Described in #3921 
---------------
**Problem**: `managedblockchain` error handling fails in werkzeug 2.x
**Underlying cause**:
This service would return XML-errors, when boto3 expects them in JSON format. …
> Make Moto (tests) compatible with flask/werkzeug 2.x

- moto/sqs/models.py
- tests/test_sns/test_publishing.py
- tests/test_sns/test_publishing_boto3.py
- tests/test_sqs/test_sqs.py
Sqs should check created timestamp of message, not queue attribute
> Fix sqs message retention logic

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2.py
This change updates the elbv2 load balancer state from `provisioning` to `active` after the first call to `describe_load_balancers()`.
> feat: transition elbv2 state to `active` on first describe

- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_stack_parsing.py
When using ssm parameters in cloudforamtion, and `Ref` node is replaced with the corresponding `physical_resource_id.`
Have mention more here:
Related issue:
https://github.com/spulec/moto/issues/3928
> SSM parameters in cloudformation (`AWS::SSM::Parameter::`) are not recognized and resolved

- setup.py
A search of the repository shows zipp is not imported anywhere, so this PR removes the dependency.
> Drop dependency on zipp

- moto/mediastore/exceptions.py
- moto/mediastore/models.py
- moto/mediastore/responses.py
- tests/test_mediastore/test_mediastore.py
Idelete_container and list_tags_for_resource were not implemented. 
I did it following boto3 & AWS documentation. I added the ContainerNotFound exception which it's the actual being thrown when trying to delete an unexistent container. 
All tests are passing.
> MediaStore delete container and list tags endpoints implemented

- moto/ssm/exceptions.py
- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
Behavior verified against a real AWS backend.
Closes #3963
> Enforce SSM Parameter Version Limit

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
SSM Parameter Store returns a ParameterVersionNotFound error code when requesting a parameter with version where the parameter exists but the requested version does not. 
Provided example below with actual AWS responses.
> SSM Parameter Store Error Message When Requesting Invalid Version

- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_boto3.py
A few improvements to GetParameterHistory & GetParameters. 
GetParameterHistory
- Implemented NextToken & MaxResults functionality
- Existing test covers pagination functionality
- Included validation of boto3 requiring MaxResults <= 50
GetParameters
- Filtered to only send unique requests in response (ie, "test", "test", "test2" will return 2 results)
- Implemented functionality to fetch specific versions and labeled parameters
> SSM Parameter Store improvements in GetParameterHistory & GetParameters 

- setup.py
`python-jose` had an update to 3.3.0, where support for Py2 was dropped.
Failure log: https://github.com/spulec/moto/runs/2752216996?check_suite_focus=true
> Pin Jose-dependency for Py2

- moto/elbv2/models.py
The code that generates an ARN for a listener rule was relying on a random
number between 0 and 50 to ensure uniqueness.  As a result, there was a decent
chance of generating a collision, particularly when adding multiple rules.
When a collision occurred, the new rule simply overwrote an existing rule,
causing a test that asserts on an expected number of rules being returned
to fail.
Reference the following runs for related test failures:
https://github.com/spulec/moto/runs/2772429387
https://github.com/spulec/moto/runs/2786330037
> Refactor listener rule ARN generation to avoid collisions

- IMPLEMENTATION_COVERAGE.md
- moto/dynamodb2/models/__init__.py
- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb.py
Basic support for the following endpoints has been implemented with full test coverage:
- create_backup
- delete_backup
- describe_backup
- list_backups
- restore_table_from_backup
Behavior and error messages verified against a real AWS backend.
> Add support for DynamoDB Backup/Restore

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
Currently you cannot have a SSM parameter name that contains a hyphen such as `/my-cool-parameter` due to a missing backslash.
> Escape Hyphen in Regular Expression

- moto/dynamodb2/parsing/validators.py
- tests/test_dynamodb2/test_dynamodb_validation.py
This fixes a bug where all updates to keys (including GSIs) would raise
EmptyKeyAttributeException, even when the new value was not an empty string.
> Only raise EmptyKeyAttributeException when the value node is empty

- moto/iam/responses.py
- tests/test_iam/test_iam.py
This PR adds the isTruncated attribute to the xml for the ListsUserResponse.
According to the documentation mentioned in the issue localstack/localstack#4150, the Java AWS SDK v2 is expecting the attribute when parsing the response.
> Added "isTruncated" attribute for listUsersResponse

- moto/dynamodb2/models/__init__.py
In case of DELETE action we don't pass the value if we want to remove the attribute.
There are more cases but it's for you to handle.
> Fix validation of values in case of DELETE action

- moto/__init__.py
- moto/applicationautoscaling/models.py
- moto/applicationautoscaling/responses.py
- moto/core/models.py
- moto/ec2/models.py
- moto/ecs/models.py
- moto/elb/models.py
- moto/elbv2/models.py
- moto/packages/httpretty/core.py
- moto/route53/models.py
- tests/test_applicationautoscaling/test_applicationautoscaling.py
Helper function _get_resource_type_from_resource_id() did not handle custom-resources correctly.  the resource id of a custom-resource does not need to conform to a standard and thus does not need to be validated.
> Fixed validation on custom-resource in applicationautoscaling

- tests/test_awslambda/test_lambda.py
Fixes #981
The ability to invoke a Lambda with multiple files was already implemented - this PR just adds a test case for it.
> AWSLambda - Verify we can add multiple files to a Function

- moto/s3/models.py
- tests/test_s3/test_s3_multipart.py
Fixes #3593 
Verified test against AWS
> S3 - Return appropriate error when provided with invalid multipart ID

- moto/core/utils.py
- moto/iotdata/models.py
- tests/test_iotdata/test_iotdata.py
Device shadow updates affect only the fields specified in the request state document.
Any field with a value of null is removed from the device's shadow.[1]
Verified behavior against a real AWS backend.
[1]: https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-rest-api.html#API_UpdateThingShadow
Fixes #3850
> Fix: iot:UpdateThingShadow does not properly maintain state document

- moto/s3/models.py
- moto/settings.py
- tests/test_s3/test_s3.py
This is a continuation of https://github.com/spulec/moto/pull/3994
This PR reduces the default value for DEFAULT_KEY_BUFFER_SIZE to 1KB less than the UPLOAD_PART_MIN_SIZE. This prevents in memory caching for multi part uploads. To facilitate this change I had to move the constant UPLOAD_PART_MIN_SIZE to the settings.py so that I was able to use it in the `get_s3_default_key_buffer_size` function without circular import issues.
> Reduce default value for DEFAULT_KEY_BUFFER_SIZE

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Fix for #4069 - Creation of users should not include default attributes.
This fix removes the additional attributes.
> fix: cognito-idp: admin_create_user remove default attributes

- setup.py
Since commit https://github.com/spulec/moto/commit/3b9635b3c72acc1770ef9666dadec6c3c650e712, the SSM module doesn't directly depend on the `cloudformation` module anymore.
The `cfn-lint` extra dependency shouldn't be required anymore for clients that install the `ssm` extra but don't need the `cloudformation` one.
This change avoids many big libraries like `numpy` or `pandas` to be installed when running `pip install 'moto[ssm]'`, which are indirect dependencies retrieved by `cfn-lint`->`networkx`.
Without this change:
> $ pip install 'moto[ssm]'
> (...)
> Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 PyYAML-5.4.1 attrs-21.2.0 aws-sam-translator-1.37.0 boto3-1.17.111 botocore-1.20.111 certifi-2021.5.30 cffi-1.14.6 cfn-lint-0.52.0 charset-normalizer-2.0.1 cryptography-3.4.7 …
> Remove cfn-lint as a dependency for ssm extra

- moto/core/responses.py
- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_core/test_responses.py
- tests/test_elbv2/test_elbv2.py
- tests/test_elbv2/test_elbv2_listener_rules.py
This PR adds support for the following condition types:
- http-header
- http-request-method
- host-header
- path-pattern
- query-string
- source-ip
Addresses #2544
> Support all ELBv2 ListenerRule condition types

- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
Fixes https://github.com/localstack/localstack/issues/4225
Fixes an issue with the terraform AWS provider that sets the SQS policy to an empty string, as seen in [the following function](https://github.com/hashicorp/terraform-provider-aws/blob/ccc13f55709c860a2130ecee6e21acde2318e936/aws/resource_aws_sqs_queue_policy.go#L104) via query parameters in the URL, for example:
`Action=SetQueueAttributes&Attribute.1.Name=Policy&Attribute.1.Value=&QueueUrl=http%3A%2F%2Flocalhost%3A4566%2F000000000000%2Fdistributor_queue&Version=2012-11-05`
In the end the `set_queue_attributes` receives the following:
```
odict_items([('Action', ['SetQueueAttributes']), ('Attribute.1.Name', ['Policy']), ('Attribute.1.Value', ['']), ('QueueUrl', ['http://localhost:4566/000000000000/distributor_queue']), ('Version', …
```
> Fix: Adding fix when setting empty policy attr to queue

- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
Fixes https://github.com/localstack/localstack/issues/4343, it seems like newly created queues do not add tags if there is an empty among them. This behavior works in AWS but not in moto and is fixed by retrieving the missing params instead of passing `self.tags`
> Fix: Adding empty tags to SQS queue on creation time

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/test_cognitoidp/test_cognitoidp.py
This PR adds support for admin_user_global_sign_out for Cognito. 
[admin_user_global_sign_out](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-user-global-sign-out.html) requires that refresh tokens are invalidated - hence the code removes any user specific refresh tokens. 
I added a check to `initiate_auth` to confirm if the refresh token exists - if it doesnt (which is shouldn't if `admin_user_global_sign_out` has been called) it responds with a ResourceNotFoundException
I've added a test case to cover this code and have run all cognitoidp test cases to confirm the small change to `initiate_auth` has not broken anything.
> Add support for admin_user_global_sign_out to cognitoidp

- moto/ec2/responses/route_tables.py
The AWS API documentation specifies that the [association state](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RouteTableAssociationState.html) is a part of the [DescribeRouteTables](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRouteTables.html) response object. Although it's not a required attribute of the object, it is consistently provided by the API and the Terraform AWS provider expects it to be present. Without including it in the response the provider throws a null pointer reference and testing can fail.
> include associationState when DescribeRouteTables

- .github/workflows/dependency_test.yml
- moto/sns/models.py
- moto/sqs/models.py
- scripts/dependency_test.sh
- setup.py
- tests/test_acm/test_acm.py
- tests/test_core/test_utils.py
- tests/test_s3/test_s3.py
- tests/test_sqs/test_sqs.py
- tests/test_sqs/test_sqs_integration.py
- tests/test_stepfunctions/test_stepfunctions.py
Fixes #4086 
Adds a GithubActions workflow to run a dependency test, which will point out if a specific module is missing dependencies.
For EC2, removes the Docker-dependency that was not required
For SQS/SNS, brings down the AWSLambda-import where it's absolutely necessary. So it will only import AWSLambda when really necessary, i.e. when the user tries to send a message/notification
Also removes some unnecessary Py2 tests/code that I came across
> Remove unnecessary dependencies EC2/SQS

- moto/core/responses.py
- moto/ec2/models.py
- tests/test_core/test_responses.py
Fix parsing regex to support request parameters with dicts of lists. Example:
```
Action=CreateDBCluster&Version=2014-10-31&VpcSecurityGroupIds.VpcSecurityGroupId.1=sg-123&VpcSecurityGroupIds.VpcSecurityGroupId.2=sg-456...
```
The `VpcSecurityGroupIds` parameters should be parsed into:
```
{"VpcSecurityGroupId": ["sg-123", "sg-456"]}
```
... instead of:
```
{'VpcSecurityGroupId': {'1': 'sg-123', '2': 'sg-456'}}
```
/cc @bblommers
> Fix parsing regex to support request params with dicts of lists

- moto/server.py
Add exception handling to signal handlers if moto is started from non-main thread. /cc @bblommers
> Add exception handling to signal handlers if moto is started from non-main thread

- moto/ec2/exceptions.py
- moto/ec2/models.py
- moto/ec2/responses/vpcs.py
- tests/terraform-tests.success.txt
- VPC was missing `ownerId` attribute which caused terraform to calculate wrong ARN
- Added ModifyVpcTenancy API
- All 21 cases under TestAccAWSVpc_ are working now
> fixed vpc with terraform; added modify vpc tenancy

- moto/cognitoidp/responses.py
- tests/test_cognitoidp/test_cognitoidp.py
Hi, I've added the option to filter users by implicit attributes in `users_list` endpoint:
- username
- status (`enabled` field)
- cognito:user_status (`status` field)
Those aren't stored in `user.attributes`, which lead to an empty response if such a filter was specified, even though they are listed in AWS [docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html#API_ListUsers_RequestSyntax).
> Support cognito:user_status filter in cognito-idp list_users

- IMPLEMENTATION_COVERAGE.md
- moto/config/exceptions.py
- moto/config/models.py
- moto/config/responses.py
- tests/test_config/test_config_tags.py
Implementation of three tag-related ConfigService APIs, with the exception of handling ConfigRule as that resource has not yet been implemented:
- `list_tags_for_resource`
- `tag_resource`
- `untag_resource`
> Add support for ConfigService APIs list_tags_for_resource, untag_resource, tag_resource

- moto/cognitoidp/responses.py
- tests/test_cognitoidp/test_cognitoidp.py
Hi, coming back to the `inherent_attributes` filter. The `status` filter handling wasn't done correctly: 
- `user.enabled` is a `bool`, so `inherent_attributes['status'](user) == value` is a `bool == str` comparison - obviously failing.
- AWS expects a case-sensitive *Enabled* or *Disabled* value for this filter, as can be seen working correctly here:
With that mistake out of the way, I've decided to make a separate test case, to verify **all** `inherent_attributes`.
> Fix for 'status' filter, separate inherent_attributes test

- IMPLEMENTATION_COVERAGE.md
- moto/autoscaling/models.py
- moto/autoscaling/responses.py
- tests/test_autoscaling/test_autoscaling.py
Implements AutoScaling resume_processes.
Also changes the behavior of suspend_processes to match [the AWS Documentation](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_SuspendProcesses.html) by suspending all processes when the parameter is unspecified, and preserving previously suspended processes on subsequent calls.
Closes #4132.
> Implement AutoScaling resume_processes and correct behavior of suspend_processes

- moto/config/models.py
- moto/core/models.py
- moto/core/responses.py
- moto/dynamodb2/parsing/reserved_keywords.py
- moto/ec2/models.py
- moto/support/models.py
- moto/utilities/utils.py
- scripts/dependency_test.sh
- setup.py
- tests/test_ssm/test_ssm_docs.py
As the `setuptools` dependency was removed, the `pkg_resources`-module is no longer available to Moto.
This PR rewrites all functionality that depended on pkg_resources, to instead use the `importlib_metadata` and `pgkdata`-modules.
It also explicitly removes the `pkg_resources`-module from the dependency test, to ensure it works.
(Note: XRay has an implicit dependency on pkg_resources, so we're adding setuptools back to that module only.)
(Note 2: For Py3.8, we could start using the buildin `importlib.metadata`, but for we'll need the backport for 3.6 and 3.7.)
Successful dependency test: https://github.com/bblommers/moto/runs/3253699280?check_suite_focus=true
> Remove pkg_resources module

- moto/ec2/models.py
- moto/ec2/responses/vpc_peering_connections.py
- moto/ec2/responses/vpcs.py
- moto/ec2/utils.py
- tests/terraform-tests.success.txt
**Added**
- Added support for tags in VPCPeeringConnection
**Fixed**
- Refractored VPCEndpoint to streamline code
- Removed `generate_vpc_end_point_id` and added `random_vpc_ep_id`
- fixed responses with missing tagsets
Terraform script
```
resource "aws_vpc" "main" {
cidr_block                       = "10.0.0.0/16"
assign_generated_ipv6_cidr_block = false
tags = {
Name = "Main"
}
}
resource "aws_vpc" "main1" {
cidr_block = "10.2.0.0/16"
}
resource "aws_vpc_peering_connection" "foo" {
peer_owner_id = "000000000000"
peer_vpc_id   = aws_vpc.main.id
vpc_id        = aws_vpc.main1.id
auto_accept   = true
tags = {
Name = "VPC Connection"
}
}
```
> added support for tags in vpc peering connections

- moto/kinesis/models.py
- moto/kinesis/responses.py
- tests/test_kinesis/test_firehose.py
UnboundLocalError is thrown when creating a Firehose delivery stream.
Error:
moto/kinesis/responses.py:198: UnboundLocalError
Sample Code:
```
firehose_client = boto3.client("firehose", region_name=REGION)
firehose_client.create_delivery_stream(DeliveryStreamName=OUTPUT_STREAM_NAME)
```
> Fixing UnboundLocalError

- moto/ec2/models.py
- moto/ec2/responses/transit_gateway_attachments.py
- API `DisassociateTransitGatewayRouteTable`
- Terraform
```terraform
resource "aws_vpc" "main" {
cidr_block = "10.0.0.0/16"
}
resource "aws_subnet" "example" {
vpc_id            = aws_vpc.main.id
availability_zone = "us-east-2a"
cidr_block        = "10.0.1.0/24"
}
resource "aws_ec2_transit_gateway" "example" {
description = "example"
}
resource "aws_ec2_transit_gateway_vpc_attachment" "example" {
subnet_ids         = [aws_subnet.example.id]
transit_gateway_id = aws_ec2_transit_gateway.example.id
vpc_id             = aws_vpc.main.id
}
resource "aws_ec2_transit_gateway_route_table" "example" {
transit_gateway_id = aws_ec2_transit_gateway.example.id
}
resource "aws_ec2_transit_gateway_route_table_association" "example" {
transit_gateway_attachment_id  = …
```
> Added DisassociateTransitGatewayRouteTable API

- moto/iot/exceptions.py
- moto/iot/models.py
- tests/test_iot/test_iot.py
IoT : `create_policy_version`  should throw `VersionsLimitExceededException` if the number of policy versions exceeds 5
> IoT: Add VersionsLimitExceededException

- .github/workflows/build.yml
- requirements-dev.txt
- requirements-tests.txt
Reverts #4083 
Fixes #4190 
Relates to https://github.com/pypa/pip/issues/10201
Our coverage-dependency was unresolvable, with `pytest-cov` requiring `coverage>5`, but because of the XRay SDK we required `coverage<5`.
Before, pip would complain about it, but leave it up to us to figure it out. The new Pip resolver thinks it can fix it, but then takes literal hours trying to find a compatible set of dependencies.
Downgrading `pytest-cov` leads to an even bigger dependency hell, as it is quite tightly coupled with pytest itself.
Installing the old version of `coverage` separately when running the CI is IMO the least-impactful solution. 
Contributors would not normally run `make test-coverage` anyway - just `make test` - so this should not impact anyone.
> Resolve coverage dependency conflict

- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
The cloudformation describe-stack-resource API action raises a ValidationError when the specified resource in the specified stack doesnot exist. This change seeks to have moto emulate that behavior.
> Raise ValidationError on bad resource id

- moto/events/models.py
- tests/test_events/test_events_cloudformation.py
The CloudFormation API takes a [dictionary for `EventPattern`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#aws-resource-events-rule-syntax), whereas the EventBridge API takes [a string only](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutRule.html#API_PutRule_RequestSyntax). The "real" cloudformation backend must do a translation. This PR emulates that behavior.
> Translate Cloudformation API data to EventBridge API data

- moto/ec2/exceptions.py
- moto/ec2/models.py
- tests/test_ec2/test_instances.py
Unfortunately `moto` does not store the `DisableApiTermination` attribute as a boolean value--and fixing that ended up being a lot of work--so I had to resort to a string comparison instead.
I followed the existing convention for OperationNotPermitted errors.
Closes #4097
> Raise error when attempting to terminate protected ec2 instance

- moto/cloudformation/models.py
- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
* **Fix bug.** If a cloudformation stack is updated with a new parameter, that parameter should be honored. Several unit tests had bugs where they were not providing parameters required by the (updated) template. Solve this by by setting `self._template` in `ResourceMap.update`, and updating the unit tests.
* **Fix bug.** Do not update reload parameters until after all removed resources are deleted, so that any references from deleted resources to removed parameters can be resolved when deleting the resources.
* **Fix bug.** Per the API, creation of a change set should not modify a stack. The `ResourceMap.diff` method, called in the creation of a FakeChangeSet, was mutating the resource map which was problematic.
This is a complete rework of https://github.com/spulec/moto/pull/4187
> Fix bugs. Cloudformation updates are complex!

- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2.py
Looks like a simple copy/paste mistake from the other templates.
> Fix IsDefault bug in elbv2 describe_rules

- moto/dynamodb/models.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/test_server.py
Fixes #2822
This old API-version of DynamoDB does not have a boto3-equivalent, as far as I know, that's why I've chosen to add tests using the `test_client`.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/API_UpdateItem_v20111205.html
> DynamoDB (V1) - implement UpdateItem

- moto/organizations/models.py
- tests/test_organizations/test_organizations_boto3.py
As pointed out by @dpowley in #3278:
Detaching a policy was broken, and the existing test didn't actually assert that the detachment was successful.
> Organisations - Detach policy, and asserts it actually happens

- moto/route53/models.py
- moto/route53/responses.py
- tests/test_route53/test_route53_boto3.py
Fixes #3786 
Fixes #3787 
- Persists and returns CallerReference
- Fixes default values for some integers
- Modifies response-values based on whether it's a calculated healthcheck or not
The new test cases have been verified against AWS itself.
~~Marking it as draft for now, as I need to add tests to verify what happens when we add parameters:~~
Edit: Ready for review now
> Route53 - Persist CallerReference

- IMPLEMENTATION_COVERAGE.md
- moto/batch/models.py
- moto/batch/responses.py
- tests/test_batch/test_batch_job_queue.py
- tests/test_batch/test_batch_jobs.py
Fixes #1850
Note that the method was already implemented, it was just a simplified implementation without any tests.
Docs for reference: https://docs.aws.amazon.com/batch/latest/APIReference/API_CancelJob.html
Includes some refactoring as well, to make the tests more readable/maintainable
> Feature: Batch: cancel_job

- moto/core/models.py
- setup.py
[`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html) is in the standard library in Python ≥ 3.8, so we can avoid installing the backported `importlib_metadata` except on older Python versions, using an [environment marker](https://www.python.org/dev/peps/pep-0496/).
> Only use backported importlib_metadata on Python < 3.8

- moto/iam/models.py
- moto/iam/responses.py
- tests/test_iam/test_iam.py
- tests/test_iam/test_iam_cloudformation.py
Fixes #3324 
Adds CF support for the creation of `AWS::IAM::ManagedPolicy`
Also improves the `iam.list_entities_for_policy()` method by making the `Entity`-parameter optional, as per the AWS docs.
> CloudFormation support for IAM:ManagedPolicy (create only)

- moto/s3/responses.py
- tests/test_s3/test_s3_metadata.py
> S3 - Add RequestId to responses

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/test_dynamodb.py
Fixes #3729 
When updating a non-existing item, we create a empty item first - then apply the UpdateExpression on top.
This change validates the UpdateExpression first, before creating a new item.
> DynamoDB - Validate AST before creating new item

- moto/awslambda/models.py
- tests/test_awslambda/test_lambda.py
Fixes #3992 
Failed Lambda invocations currently return a combination of log-statements and the actual error. This PR simplifies the response, so that we'll always separate the log-statements from the Docker-response, regardless of whether the invocation was successful.
See also: #2669
> Streamline success/failure response from AWSLambda

- README.md
- docs/docs/getting_started.rst
- moto/sqs/models.py
- scripts/dependency_test.sh
- setup.py
- tests/test_sqs/test_integration.py
- tests/test_sqs/test_sqs.py
Fixes #3737 
We only need to import AWS Lambda if we have entries in the `lambda_event_source_mappings`-map, i.e. if there are any Lambda-functions registered.
Also changes the installation-method to support all services, i.e.
`pip install moto[acm]`
will no longer give a warning `moto 2.x.x does not provide the extra 'acm'`
> Remove Docker-dependency from SQS

- .github/workflows/build.yml
- codecov.yml
- moto/core/models.py
- tests/test_core/test_request_mocking.py
Fixes #3790 
When a method has multiple decorators, and a moto-call is made to a specific service, the first (unrelated) decorator might only return a non-implemented-callback.
For example, with a test-method that has both the `@mock_sts` and `@mock_s3` decorator:
When calling the `s3.get_object()`-method, Moto will cycle through the following matches (in `_find_first_match`):
- catch-all non_implemented_callback (from STS)
- get_object (from S3)
- catch-all non_implemented_callback (from S3)
Note that this bug would only appear when the decorators are in the 'wrong' order - if the S3 decorator is listed first, the get_object match would be correctly found first.
This PR fixes this behaviour, so that a implemented callback is always returned first.
- get_object (from S3)
- catch-all …
> Request matching - return known requests first

- moto/wafv2/urls.py
> Update WAFv2 URLs with proper regex

- moto/awslambda/models.py
- moto/awslambda/responses.py
- tests/test_awslambda/test_lambda.py
Fixes #3422 
Only return full version list when the user specifies `FunctionVersion="ALL"`
Also makes some changes to ensure that FunctionARN is always returned in the correct format.
Tests have been verified against AWS.
> AWSLambda:list_functions() should only return the latest version by default

- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_boto3.py
fixes #4215 
This PR adds the `DataType` attribute to SSM parameters #4215 
`DataType` parameter on SSM is now added to the Parameter class. The parameter is now accepted and validated on the `put_parameter` function and also returned back when getting parameters from the store.
`aws:ec2:image` Data Type parameters are not created instantly on AWS. It depends on the existence of an AMI ID of the provided value so it can keep the value updated. This is still not supported.
`DataType` defaults to `text` as the documentation describes.
> enhancement(SSM): Add DataType attribute to SSM Parameters

- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_dynamodb2/test_dynamodb_consumedcapacity.py
Only returns the param now if required, and throws an error if the value is unknown.
The validation and content is exactly the same across all methods, so being able to use a single decorator across all of them reduces the need for repeated code.
Fixes #2851
Fixes #3959
> DynamoDB - Improve handling of ReturnConsumedCapacity-param

- moto/core/responses.py
- moto/sqs/responses.py
Relates to https://github.com/localstack/localstack/issues/4343 and https://github.com/localstack/localstack/pull/4365
When tagging an existing SQS queue and one of the values is an empty string, this line breaks the loop because `not(k and v)` does not expect an empty str.
Example:
```
response = self.client.tag_queue(
QueueUrl=queue_url, Tags={"tag1": "value1", "tag2": "value2", "tag3": ""}
)
```
With this change, it won't break the tag (and hopefully won't break either for the rest of the modules using this, as empty tags are accepted across AWS services AFAIK)
> Fix: Issue with empty tags created on SQS queues

- moto/s3/exceptions.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
Fixes #1371
Supercedes #1390
Tests was verified against AWS
Edit:
Originally I wanted to also add the S3 Location header, to more closely resemble AWS' behaviour. This is a bit more complicated though, as Flask will mess with the output. AWS returns `Location: /{bucketname}`, and in it's infinite wisdom, Flask converts this into `Location: http://localhost:5000/{bucketname}`. See https://stackoverflow.com/a/22707491/13245310
> S3 - Correct error when creating a bucket that already exists

- moto/sqs/models.py
Using `remove` in this case causes a `KeyError` when deleting messages with changed visibility (because those messages are not present in `pending_messages`). Changing it to `discard` avoids the error.
Also, the comment suggests the message is only removed from `pending_messages` but as messages which have the correct handle are not appended to the new list they will be removed regardless. The behavior is correct though (tested against AWS).
Relates to [issue in localstack](https://github.com/localstack/localstack/issues/4470)
> Change message deletion behavior of SQS queue to use discard

- moto/ecs/models.py
- tests/test_ecs/test_ecs_cloudformation.py
I recently added Moto to a project, and got an error related to the DesiredCount on my Ecs Servie declaration in the CloudFormation template. According to [the AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-desiredcount), DesiredCount is not required in some circumstances.
> Fix error when AWS::ECS::Service does not include a DesiredCount

- moto/backends.py
- moto/core/models.py
- moto/mediapackage/models.py
- moto/server.py
Follow up to #4209 
Only backends that are loaded into memory will now be reset when calling `/moto-api/reset`, reducing the waiting time drastically.
@whummer @thrau Does LocalStack use the reset-api, and/or you do expect there to be any impact for you?
> Performance improvement - Only reset backends loaded into memory

- moto/acm/models.py
- moto/acm/responses.py
- tests/test_acm/test_acm.py
This is an implementation of the [ACM ExportCertificate action](https://docs.aws.amazon.com/acm/latest/APIReference/API_ExportCertificate.html). I changed the google root ca to the aws root ca [found here](https://censys.io/authorities/7a3a96e64a895c66676cc71400ed0e3ce9718be9ec5d46edb4f4a52d96a4414d) because it looks like that is the cert that matches the issuer in the `generate_cert()` method.
> Implement ACM export_certificate function

- moto/cloudformation/models.py
- tests/test_cloudformation/test_cloudformation_stack_crud.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Calling CloudFormation's CreateStack action seems to always return a StackId with 'us-east-1' in it.
> Fix CloudFormation create_stack returning stack_id with wrong region 

- moto/iam/responses.py
The GENERIC_EMPTY_TEMPLATE jinja template already adds a `...Response` suffix to the XML tag name so some of these were incorrectly leading to a double suffixes such as `<DeleteRolePolicyResponseResponse>`.
Also fixes the `delete_group_policy` endpoint by using the same GENERIC_EMPTY_TEMPLATE to render the response.
> Fix response rendering for IAM endpoints using GENERIC_EMPTY_TEMPLATE

- moto/batch/models.py
- moto/batch/responses.py
- tests/test_batch/test_batch_task_definition.py
resolves spulec/moto#4284
I have updated batch job definition creation, such that tags will be associated with the definition.
Following [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.describe_job_definitions), the tags are submitted with the job def as a dict: 
```
tags={
'string': 'string'
},
```
The tagging object is used to store the values, but when a batch job definition is retrieved, it will have the tags returned in a dict: 
```
'tags': {
'string': 'string'
},
```
If there are no tags, an empty dictionary will be returned:
```
'tags': {},
```
I have submitted at this point to check I am doing something along the lines you would find acceptable and any necessary feedback would be appreciated.
Currently this affects …
> Add tagging to batch job definitions

- moto/secretsmanager/models.py
- moto/secretsmanager/responses.py
- moto/secretsmanager/utils.py
- tests/test_secretsmanager/test_secretsmanager.py
Fixes https://github.com/localstack/localstack/issues/4618
* Adds ClientRequestToken to the `update_secret` method.
* Improving validation of the param on most of methods using it
> Fix: Adding ClientRequestToken for SecretsManager update_secret method

- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_lifecycle.py
See #3842 - adds equivalent boto3 tests for S3, so that the deprecated tests can be removed without losing any test coverage
> Rewrite deprecated S3 tests

- tests/test_cloudwatch/test_cloudwatch.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
See #3842  - adds equivalent boto3 tests for CloudWatch, so that the deprecated tests can be removed without losing any test coverage
(Most functionality was already duplicated for this service.)
> Rewrite deprecated CloudWatch tests

- tests/test_swf/responses/test_activity_tasks.py
- tests/test_swf/responses/test_activity_types.py
- tests/test_swf/responses/test_decision_tasks.py
- tests/test_swf/responses/test_domains.py
- tests/test_swf/responses/test_timeouts.py
- tests/test_swf/responses/test_workflow_executions.py
- tests/test_swf/responses/test_workflow_types.py
- tests/test_swf/utils.py
See #3842 - adds equivalent boto3 tests for SWF, so that the deprecated tests can be removed without losing any test coverage
> Rewrite deprecated SWF tests

- moto/ec2/models.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
- tests/test_ec2/test_spot_instances.py
Follow-up from spulec/moto#4260.
Using a real boto3 client:
```
>>> list(boto3.resource("ec2", region_name="us-west-2").instances.all())[0].instance_lifecycle is None
True
```
> EC2 - instance lifecycle defaults to None when not using spot

- IMPLEMENTATION_COVERAGE.md
- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_launch_configurations.py
- tests/test_autoscaling/test_policies.py
See #3842 - adds equivalent boto3 tests for Autoscaling, so that the deprecated tests can be removed without losing any test coverage
> Rewrite deprecated Autoscaling tests

- IMPLEMENTATION_COVERAGE.md
- tests/test_core/test_socket.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
- tests/test_dynamodb2/test_dynamodb_table_without_range_key.py
See #3842 - adds equivalent boto3 tests for DynamoDB2, so that the deprecated tests can be removed without losing any test coverage
> Rewrite deprecated DynamoDB2 tests

- tests/test_iam/test_iam.py
- tests/test_iam/test_iam_groups.py
- tests/test_iam/test_iam_server_certificates.py
See #3842 - adds equivalent boto3 tests for IAM, so that the deprecated tests can be removed without losing any test coverage
> IAM - Rewrite deprecated boto tests

- moto/kms/responses.py
- tests/test_kms/test_kms.py
- tests/test_kms/test_kms_boto3.py
See #3842 - adds equivalent boto3 tests for KMS, so that the deprecated tests can be removed without losing any test coverage
> KMS - rewrite deprecated boto tests

- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_dynamodb_table_with_range_key.py
- tests/test_dynamodb/test_dynamodb_table_without_range_key.py
- tests/test_dynamodb/test_server.py
See #3842
This old API-version of DynamoDB does not have a boto3-equivalent, as far as I know - the only way to invoke it is by manually adding the `X-Amz-target`-header. 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Appendix.APIv20111205.html
> DynamoDB - Rewrite boto tests

- moto/glacier/models.py
- moto/glacier/responses.py
- moto/glacier/urls.py
- moto/glacier/utils.py
- tests/test_glacier/test_glacier_archives.py
- tests/test_glacier/test_glacier_jobs.py
- tests/test_glacier/test_glacier_vaults.py
See #3842 
This also fixes the Glacier-service in ServerMode. The existing implementation would redirect all calls to the us-east-1 region.
Extending GlacierResponse from `BaseResponse` streamlines the implementation with how other services work, and also finds the  correct region for incoming ServerMode requests.
Some logic has been renamed/moved  (from `responses.py` to `models.py`) to ensure these methods are picked up by the implementation coverage script.
> Glacier - rewrite deprecated tests

- moto/core/exceptions.py
- tests/test_ses/test_ses_boto3.py
> SES - SendEmail: source attr can contain chevrons

- moto/iot/models.py
- tests/test_iot/test_iot.py
If the methods `list_job_executions_for_thing` and `list_job_executions_for_job` are used with an explicit `status` parameter then it will always run into a `KeyError "status"`.
[log.txt](https://github.com/spulec/moto/files/7218426/log.txt)
This PR fixes a bug where wrong fields of job executions are accessed when filtering by status.
> Fix list_job_excecutions_for_thing with status parameter

- moto/elbv2/responses.py
I can write a test for this if really desired. I didn't write one for this, since this API requires an LB or Listener as a parameter, it's quite a bit of setup, for not much gain.
> fix incorrect response tag for DescribeListeners

- moto/elb/models.py
- moto/elb/responses.py
- tests/test_elb/test_elb.py
See #3842 
Also identifies and fixes a few bugs that only showed up for Boto3 tests.
> Rewrite deprecated ELB tests

- moto/config/models.py
- tests/test_config/test_config_rules.py
Valid InputParameters were being flagged as invalid, causing an InvalidParameterValueException to be raised.
> Fix validation of ConfigService PutConfigRule InputParameters

- moto/ec2/responses/elastic_block_store.py
- tests/__init__.py
- tests/test_ec2/test_amis.py
- tests/test_ec2/test_availability_zones_and_regions.py
- tests/test_ec2/test_customer_gateways.py
- tests/test_ec2/test_dhcp_options.py
- tests/test_ec2/test_elastic_block_store.py
- tests/test_ec2/test_elastic_ip_addresses.py
- tests/test_ec2/test_elastic_network_interfaces.py
- tests/test_ec2/test_general.py
- tests/test_ec2/test_instances.py
- tests/test_ec2/test_internet_gateways.py
- tests/test_ec2/test_key_pairs.py
- tests/test_ec2/test_network_acls.py
- tests/test_ec2/test_regions.py
- tests/test_ec2/test_route_tables.py
- tests/test_ec2/test_security_groups.py
- tests/test_ec2/test_spot_instances.py
- tests/test_ec2/test_subnets.py
- tests/test_ec2/test_tags.py
- tests/test_ec2/test_virtual_private_gateways.py
- tests/test_ec2/test_vpc_peering.py
- tests/test_ec2/test_vpcs.py
- tests/test_ec2/test_vpn_connections.py
See #3842 - adds equivalent boto3 tests for EC2, so that the deprecated tests can be removed without losing any test coverage
> Rewrite deprecated EC2 tests

- moto/s3/responses.py
- tests/test_s3/test_s3_auth.py
Fixes #4335 
This PR fixes authentication for HEAD-requests to buckets.
Same problem as #4240, which fixes authentication for HEAD-requests to objects.
> S3: HeadBucket requests should be authenticated

- moto/iam/responses.py
boto3 is forgiving on this front but other SDKS are not.  Since moto is
used behind localstack it causes some SDKs (namely Go SDK) to fail to
properly look up tags on localstack.
I made this change on my localstack container and it did indeed fix the Go SDK behavior.
https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListUserTags.html
This should resolve https://github.com/spulec/moto/issues/4341
> Use proper xml tag for ListUserTagsResult's Tags

- moto/ssm/exceptions.py
- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
- tests/test_ssm/test_ssm_docs.py
In #1024 changes were made to emulate tagging methods in the ssm subsystem.  Unfortunately they do not behave like AWS does.  When a resource is not available, AWS returns an `InvalidResourceId` error.  Here is an example I recorded with vcrpy:
```
request:
method: POST
uri: https://ssm.us-west-2.amazonaws.com/
body: '{"ResourceType": "Parameter", "ResourceId": "special-not-there-4"}'
response:
body:
string: '{"__type":"InvalidResourceId"}'
status:
code: 400
message: Bad Request
```
Here is the response from moto, which is incorrect:
```
(Pdb) pp client.list_tags_for_resource(ResourceType="Parameter", ResourceId="special-not-there-4")
{'ResponseMetadata': {'HTTPHeaders': {'server': 'amazon.com'},
'HTTPStatusCode': 200,
'RetryAttempts': 0},
'TagList': []}
```
I also fixed the case where a …
> [issue-4360] Fix InvalidResource Id,Type responses for ssm tagging methods

- scripts/scaffold.py
This script was not properly updated after the handling of backends was changed.  
My original intention was to remove the function that updated `moto/backends.py` and to add a note to the user to run `scripts/update_backend_index.py`.  However, you can't just remove the logic to update the backends and have the user run `update_backend_index.py` afterwards, because `scaffold.py` needs the backend in place to finish the rest of its work.
I thought I would provided the changes I've made so far, but someone else will need to finish the changes as I need to move onto another project.
```
$ scaffold.py
Select service: ebs
==Current Implementation Status==
[ ] complete_snapshot
[ ] get_snapshot_block
[ ] list_changed_blocks
[ ] list_snapshot_blocks
[ ] put_snapshot_block
[ ] start_snapshot …
```
> Correct several issues in scripts/scaffold.py

- moto/route53/models.py
- tests/test_autoscaling/test_autoscaling_cloudformation.py
- tests/test_cloudformation/test_cloudformation_stack_crud.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
- tests/test_datapipeline/test_datapipeline_cloudformation.py
- tests/test_dynamodb2/test_dynamodb_cloudformation.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_security_groups_cloudformation.py
- tests/test_elb/test_elb_cloudformation.py
- tests/test_iam/test_iam_cloudformation.py
- tests/test_rds2/test_rds2_cloudformation.py
- tests/test_redshift/test_redshift_cloudformation.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
- tests/test_route53/test_route53_cloudformation.py
- tests/test_sns/test_sns_cloudformation.py
- tests/test_sqs/test_sqs_cloudformation.py
Ref #2950 , deprecated decorator removal
In line with @spulec's idea to create a PR per service, IMO it makes most sense to make this a two-step process:
- For each service: replicate all deprecated tests to test the same functionality with the boto3-decorator
- When all deprecated test cases are duplicated and redundant, we can remove the deprecated tests and decorators at the same time without having to worry about losing any test coverage
This also removes any time constraint - we can merge this whenever, and remove the deprecated tests months later, without having to worry about merge conflicts.
This PR does exactly that for CloudFormation - create equivalent boto3-tests for all `mock_cloudformation_deprecated`-tests
> Rewrite deprecated CloudFormation tests

- tests/test_kinesis/test_kinesis.py
See #3842.
This is the last in the series - all `*_deprecated` tests should now have equivalent boto3 tests.
> Kinesis - duplicate deprecated tests

- scripts/pull_down_aws_managed_rules.py
The `pull_down_aws_managed_rules.py` script takes a while to run because it's pulling down quite a few markdown files from the AWS website.  I added a "verbose" switch `-v` or `--verbose` so the invoker can have a sense of the script's progress and not worry that the script has stalled somewhere along the line.
Also updated some comments and cleaned up a pylint error in the script.
> Add verbose option to pull_down_aws_managed_rules.py

- moto/s3/responses.py
- tests/test_s3/test_s3.py
Fixes #4203
`headers` parameter was unused in `_handle_range_header()` method, causing some headers to be lost
This looked like a typo as the method is invoked using `response_headers` as argument name:
https://github.com/spulec/moto/blob/5771dcf73bef22adb2e7c54ee4787ea6eebceebd/moto/s3/responses.py#L1063-L1065
I simply changed the argument back to `response_headers` and it fixed the issue.
> Fix range headers: use response_headers parameters instead of creating a new dict

- moto/ecr/models.py
- tests/test_ecr/test_ecr_boto3.py
Fix: #4499 
This PR ensures that the `imagePushedAt` field returned by `describe_images` has a timezone set. This matches the behaviour or `boto3` when not mocked.
> Ensure that imagePushedAt fields from ECR is timezone aware

- moto/s3/models.py
- moto/s3/responses.py
- moto/server.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_server.py
Hacktoberfest contribution 🎃 
Fixes #4220 
The default headers from CORS plugin was not enough to mock S3 CORS Rules behavior
We need to manually define response headers depending on the bucket rules
- Fixed typos:
-  `ExposedHeader` --> `ExposeHeader` (defined as such in AWS documentation)
- `MaxAgeSecond` --> `MaxAgeSeconds`(defined as such in AWS documentation)
- I implemented OPTIONS method instead of relying on the defaults from Flask
- Iterated through CORS rule to return some CORS headers
This is not a perfectly accurate strategy: I didn't check but according to the docs, when multiple CORS Rules are defined, S3 returns the most relevant (I suppose the most permissive one, depending on the request)
In the strategy I implemented, the last rule takes precedence over the other rules. …
>  S3: Implement CORS headers in OPTIONS requests 

- moto/batch/models.py
- tests/test_batch/test_batch_cloudformation.py
- tests/test_batch/test_batch_task_definition.py
Resolves #4505 
This PR allows the user to specify Batch job definition memory and vCPUs using the `resourceRequirements` key in the `containerProperties` dictionary, rather than using the (now deprecated) top level `memory` and `vcpus` keys.
This PR adds a new method to the `JobDefinition` class in `moto/batch/models.py` called `_get_resource_requirement` which gets a resource requirement from container properties by first checking the `resourceRequirements` list and then falling back on the top level `containerProperties` keys.
The PR then uses these methods to validate input the the `memory` and `vcpus` requirements. It also calls this method in the `Job` class' `get_container_property` method if the property is either `memory` or `vcpus`.
Finally, the PR adds tests of the new job …
> ENH: Add resource_requirements to batch job definition

- IMPLEMENTATION_COVERAGE.md
- docs/index.rst
- moto/emrcontainers/exceptions.py
- moto/emrcontainers/models.py
- moto/emrcontainers/responses.py
- moto/emrcontainers/urls.py
- moto/emrcontainers/utils.py
- tests/test_emrcontainers/test_emrcontainers.py
Hi All,
I have created a new feature for [EMRContainers](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr-containers.html) service. In the second PR I focused only operations with `jobs`.
Upon request I can add missing EMRContainers features (endpoints, tags).  Next item on my roadmap [Managed Streaming for Kafka](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kafka.html), however that will be more complicated to mock.
Thanks,
Andor
> Feature - emr-containers - jobs

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
There were a few areas where a provided S3 object key was being URL decoded multiple times, which created a problem for S3 objects whose key contained embedded percent encodings. This looked to be happening mostly in areas where existing functions that already decoded the object key were being reused by higher level functions that were themselves decoding the key.
These changes defer the URL decoding until the last moment to prevent passing already decoded keys into functions that are expecting keys to be url encoded. I've added a couple of test cases for the copy object calls and multipart copy object calls.
There is one change below to `moto/s3/models.py:append_to_key` that does not have an associated test with it. It doesn't seem to have any current test coverage and I did not quite …
> fix: S3 CopyObjects with embedded percent encoding

- moto/s3/responses.py
Whitelists `host.docker.internal` in `subdomain_based_buckets`. Fixes issue 4521.
Signed-off-by: eric schkufza <eric.schkufza@gmail.com>
> [BUGFIX] Can't perform GET/PUT operations against server from inside docker container 

- IMPLEMENTATION_COVERAGE.md
- moto/iam/models.py
- moto/iam/responses.py
- tests/test_iam/test_iam.py
Resolves #4519
This PR includes everything required to implement IAM policy tagging.
The PR uses IAM role tagging as a template so should cover all required aspects. Tests have been run locally and appear to be successful.
> Added policy tagging that was previously marked as missing

- moto/s3/responses.py
- tests/test_s3/test_server.py
In #4497 I forgot to implement OPTIONS on key response, I only added unit tests for bucket responses (queries on `/`)
The OPTIONS key response on a real S3 endpoint is essentially the same as the bucket response.
If the bucket doesn't exist, return 403. If the bucket exists, return 200 with the bucket CORS headers, disregarding if the key exists or not.
So I used the same method for both key and bucket responses.
> add back OPTIONS key response after implementing CORS in #4497

- moto/s3/models.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_encryption.py
Fixes #4172 
Improved behaviour of `put_bucket_encryption`
Reuse existing `put_object` logic when copying keys, to ensure that the encryption config is set correctly.
Tests have been verified against AWS
> Feature: S3 -  enable encryption when copying keys

- moto/kinesis/exceptions.py
- moto/kinesis/models.py
- tests/test_kinesis/test_kinesis.py
- tests/test_kinesis/test_kinesis_boto3.py
Fixes `split_shards` behaviour to create two new shards, instead of the existing behaviour of reusing one
Adds error scenarios, and fixes existing error messages
Fixes some erroneous Response-attributes when describing a stream
All new tests were validated against AWS.
Closes #1405
Closes #1475
> Kinesis - Fix split_shards behaviour

- moto/ds/models.py
- moto/ds/responses.py
Issues fixed:
- `ipaddress.ip_network()` should be used instead of `ipaddress.IPv4Network()` in order to handle both IPv4 and IPv6 addresses.
- 
- There are checks for the maximum number of tags, but those checks don't account for no tags being present.  Set the default value for tags to an empty list.
> Directory Service: Handle IPV6 addresses and no tags

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
See: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html
Adds the option to filter SSM parameters by their labels.
Example usage: `aws ssm get-parameters-by-path --path "/foo" --parameter-filters Key=Label,Values=label1`
> Add support for Label filter in get_parameters_by_path

- moto/cloudtrail/models.py
- tests/test_cloudtrail/test_cloudtrail.py
> Cloudtrail `get_trail_status()` also accepts ARN in `Name` parameter

- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Closes #2451
The actual fix for that issue was already included in #1103, as far as I can tell - not sure why it was still failing two years after that PR was merged.
This PR adds test cases to verify that both `Fn::Equals` and `!Equals` work - I couldn't find any existing tests that explicitly test this behaviour/functionality. It also fixes a small bug related to boolean comparisons.
> CloudFormation - verify shorthand Yaml-functions

- moto/dynamodb2/exceptions.py
- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/conftest.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_dynamodb2/test_dynamodb_exceptions.py
- tests/test_dynamodb2/test_dynamodb_executor.py
- tests/test_dynamodb2/test_dynamodb_table_with_range_key.py
- tests/test_dynamodb2/test_dynamodb_table_without_range_key.py
- tests/test_dynamodb2/test_dynamodb_validation.py
Closes #3231
Throws an error when trying to persist an item with the wrong item type, i.e. storing Strings if the table expects Numbers etc.
> DynamoDB - error when persisting item with wrong type

- moto/s3/models.py
- tests/test_s3/test_s3.py
Potential fix for #4551. Bug was introduced in #4535 
The internal value of the `etag`-parameter _should_ be the md5 representation of the content. Whenever someone calls the property `key.etag`, Moto will then add the required quotes around it.
The line `etag=key.etag` on copy would ensure that the internal value of the etag already had quotes. Calling the `copied_key.etag` property would add another set of quotes. (Presumably ad-infinitum, if you would copy the same object over and over...)
By not supplying the etag-parameter it will be recalculated, so this way we don't have to worry about removing/counting quotes.
> S3 - Remove double quotes on ETag after copy

- moto/ec2/models.py
- tests/test_ec2/test_elastic_block_store.py
Using `aws ec2 run-instance ...` automatically creates a Volume. This volume had an empty AvailabilityZone field when not deployed in us-east-1 since this was hardcoded previously. Creating Volumes manually did set the AZ properly, so no changes where necessary in this case.
> EC2 - fix missing AZ on auto-generated volumes for instances

- moto/batch/models.py
- moto/events/models.py
- moto/logs/models.py
- moto/logs/responses.py
- tests/test_events/test_events_integration.py
- tests/test_logs/test_integration.py
- tests/test_logs/test_logs.py
Closes #3979 
Implements validation for:
- log events not in chronological order
- log events that are too old (> 2 weeks ago)
- log events that are too recent (> 2 hours in the future)
Tests were validated against AWS
> CloudwatchLogs - implement validation for old/new messages

- moto/dynamodb2/comparisons.py
- tests/test_dynamodb2/test_dynamodb.py
Bug where 'between 0 and 10' would fail, because it would interpret '0' as None
> DynamoDB - fix bugfix between 0 and x

- moto/s3/exceptions.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
Closes #4524 
The bug itself was accidentally fixed as part of #4535, this PR just brings the error response in-line with how AWS behaves
> S3 - Fix NoSuchKey-format

- moto/s3/models.py
- tests/test_s3/test_s3.py
The real S3 API returns `"null"` for `versionId` if bucket versioning
is disabled; not `None`. Moto returns `None`.
This causes behavior for the added test case to diverge between the real
API and the mock one: if you enable bucket configuration after objects
already exist in the bucket, it becomes impossible to empty the bucket
with moto.
> Set version_id to null without bucket versioning

- moto/cognitoidp/models.py
- moto/config/models.py
- moto/core/exceptions.py
- moto/ds/validations.py
- moto/emr/exceptions.py
- moto/emr/models.py
- moto/emr/responses.py
- moto/managedblockchain/exceptions.py
- tests/test_cognitoidp/test_cognitoidp.py
- tests/test_emr/test_emr_boto3.py
Encountered an issue with the json serialization/parsing of exception messages because they were simply substituted in the jinja2 template instead of being properly encoded. Since there didn't seem to be any reason to keep using jinja2 for this manual json rendering, I've replaced this in favor of using the built-in json module.
> Core - Use json module for error_json exception type rendering instead of jinja2

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2_target_groups.py
Closes #3554
Ensures the default actions are properly tracked, and fixes a bug where the new default action didn't actually have any data when modifying a listener
> ELBv2 - Store default action when modifying listener

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
References and address #3741.
`cognito:groups` claims in the payload are not present when using `respond_to_auth_challenge`. moto tests are unable to test or verify group based access since `cognito:groups` is not present. Referencing [Using the Access Token - AWS Docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html) `cognito:groups` claim is present when a user is in a group.
When an access token is generated, gather extra information corresponding to the users association to a group. Pass that extra information to `CognitoIdpUserPool.create_jwt` as `kwgs: extra_data`.
1. Original commit adds functionality for `cognito:groups` (*note*: referencing AWS documentation `cognito:roles` is not mentioned in claims in access token) …
> Adding functionality for cognito:groups in access_token

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
AWS S3 allows [KMS key parameters to be passed in a copy_object request](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.copy_object), however moto did not pass these on
This PR simply passes the parameters through
There is also one supplementary change of test_s3.py wherein a create_bucket call was failing with an invalid region
> [s3] Allow KMS SSE parameters in copy_object

- moto/route53resolver/models.py
- moto/route53resolver/responses.py
- tests/test_route53resolver/test_route53resolver_endpoint.py
I tried to write this so the filter validation functions can be used by the other Route53Resolver list functions.  
Note that the allowed filter names can be in the old style (all caps, snake case) or in the new style (camel case), which complicates things.  And of course, there is an exception to the filter name rules!
> Route53Resolver:  Add support for filters for list_resolver_endpoints

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
See the test for the behavior this PR is trying to fix.
Because the filtering in `receive_message` was removing items from the attributes on the actual message item in the backend, the next (less restricted) call would not be able to get the previously filtered out attributes anymore.
> SQS - Fix message attributes disappearing on multiple receives

- moto/batch/models.py
At least with Podman, log timestamps contain timezone information
(ex: 2021-11-20T13:45:15+08:00). As a result, timestamps parsed with
`ignoretz=True` may be several hours later (ex: 8 hours) than the actual
time, causing logs to be rejected.
The issue can be reproduced by running tests on a UTC+8 machine:
$ DOCKER_HOST=unix:///run/user/1000/podman/podman.sock pytest -v tests/test_batch/test_batch_jobs.py -k test_submit_job --capture=no
============================================================================ test session starts =============================================================================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /home/yen/tmp/moto, configfile: setup.cfg
plugins: …
> Correctly handle the timezone in batch job logs

- tests/test_sqs/test_sqs.py
Attempt at fixing/debugging the `test_sqs.py::test_message_becomes_inflight_when_received_boto3` test, that keeps failing in builds.
Details:
- It fails intermittently
- It fails on Python 3.9 only
- It works in ServerMode
- I can't reproduce it locally
- I haven't seen it in builds on my own fork (recently)
Possible fixes:
- Different region - is there a queue with the same name in the other region?
- Sleep longer - is Py3.9 too slow, and is the message already available again by the time it gets there?
> SQS - try circumvent test errors

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/apigateway.rst
- moto/apigateway/integration_parsers/aws_parser.py
- moto/apigateway/integration_parsers/http_parser.py
- moto/apigateway/integration_parsers/unknown_parser.py
- moto/apigateway/models.py
- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
- tests/test_apigateway/test_apigateway_integration.py
Closes #2951
HTTP integrations were already mocked:
```
client.put_integration(
restApiId=api_id,
...,
uri="http://httpbin.org/robots.txt",
integrationHttpMethod="GET",
)
deploy_url = f"https://{api_id}.execute-api.us-east-1.amazonaws.com/dev"
requests.get(deploy_url).content.should.equal(b"a fake response")
```
This PR also adds support for:
Mocking an integration with `type=AWS` and `uri=arn:aws:apigateway:region:dynamodb:target/...`
Mocking integrations with HTTP-methods other than "GET"
Mocking of nested resources, i.e. `amazonaws.com/stage/resource` now works - before, only the root resource was mocked (`amazonaws.com/stage`)
> API Gateway - improve mocking of public API

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/route53resolver.rst
- moto/route53resolver/models.py
- moto/route53resolver/responses.py
- moto/route53resolver/utils.py
- moto/route53resolver/validations.py
- tests/test_route53resolver/test_route53resolver_endpoint.py
- tests/test_route53resolver/test_route53resolver_rule.py
Adds support for the following APIs:
- `create_resolver_rule`
- `get_resolver_rule`
- `delete_resolver_rule`
- `list_resolver_rules`
> Route53Resolver: Add resolver rule-related APIs

- Makefile
- moto/__init__.py
- moto/xray/__init__.py
- moto/xray/mock_client.py
- tests/test_core/test_mock_all.py
- tests/test_xray/test_xray_client.py
At the moment `@mock_all` works as a decorator only, but it should also be usable as a context manager (`with mock_all():`).
In order for this to work, the `mock_xray_client` also needed to be changed to work as a context manager.
Tests have been added to verify the behaviour of both.
Based on and supercedes #4596 - does this look OK to you @jmsanders?
> Rework mock_all to work as a context manager

- moto/ec2/responses/vpcs.py
- tests/test_ec2/test_vpcs.py
The XML generated for describe_vpc_endpoints did not have the expected schema for DnsEntries, so creating an interface endpoint and then describing it gave you an empty DnsEntries array.  I fixed that and I updated the tests to test both gateway and interface endpoints.
> Fix incorrect DnsEntries XML for describe_vpc_endpoints

- moto/s3/exceptions.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_multipart.py
Closes #4586 
Adds correct error messaging when providing too big a number when getting a multipart
Adds error when creating an upload with part > 10000
Fixes behaviour when retrieving parts where some uploaded parts are missing (i.e., only part 1, 2, and 10000 are uploaded)
All affected tests are verified against AWS
> S3 - Fix corner cases multi upload

- moto/cloudformation/models.py
- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_policies.py
Closes #845
This PR add support for methods:
`get_stack_policy()`
`set_stack_policy()`
As discussed in the attached issue, we only persist the policy - no validation or policy enforcement takes place. This is also noted in the docs.
> CloudFormation - Get/Set stack policy (no parsing)

- moto/ds/models.py
- moto/ds/responses.py
- moto/route53resolver/models.py
- tests/test_ds/test_ds.py
- tests/test_route53resolver/test_route53resolver_endpoint.py
Directory Service creates a security group and network interfaces, but those weren't being deleted when a directory was deleted.  Also, the Security Group Id should be displayed in the `describe_directory` output.
Route53Resolver creates network interfaces for the endpoint and those should be deleted when the endpoint is deleted.
> Directory Service, Route53Resolver:  Delete network interfaces created during initialization

- setup.py
As moto doesn't support Python 2.7 anymore, the minimum supported
version of python-jose doesn't need to support Python 2.7 either. This
allows updating the minimum supported version of python-jose to a
version with fixed version contraints on its ecdsa dependency, making
the workaround of pinning ecdsa to specific versions unnecessary. That
in turn then allows using newer ecdsa versions as well, as the version
constraint python-jose uses is ecdsa!=0.15 instead of ecdsa<0.15
currently used by moto.
> Bump python-jose to support newer ecdsa versions

- docs/docs/services/dynamodb.rst
- moto/dynamodb2/models/__init__.py
- moto/dynamodb2/responses.py
- tests/test_dynamodb2/test_dynamodb.py
I added the `restore_table_to_point_in_time` DyanmoDB method to the library. I _think_ I got adequate coverage for the unique use case I have (which is restore a table's most recent PIT to another table), but please let me know if you think I've missed anything.
**Please note**: There are 4 failing tests when I run the tests locally, which also failed when I checked out the `master` branch. They are in code I haven't touched so either it's a local issue or something pre-existing from what I can tell.
Thanks for your consideration!
> Added restore table to point in time DynamoDB method

- moto/sts/responses.py
- tests/test_sts/test_server.py
Found from this issue in localstack https://github.com/localstack/localstack/issues/4807 we were getting \n characters in the xml for the GetFederationToken call. Thinking this will fix it
> fix: STS xml was malformed

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
This PR introduces the validation to prevent sending a message group ID when using a queue of standard type.
Closes #4594.
> Validate message group ID for standard queues

- moto/s3/responses.py
- tests/test_s3/test_s3.py
This PR addresses issue localstack/localstack#4624.
Changes: 
- Before searching for a versioned key, now the S3 Backend checks if the bucket is versioned, if it isn't, it responds with the correct status code.
> Correct status code for a versioned key search in not versioned bucket.

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudfront.rst
- moto/__init__.py
- moto/backend_index.py
- moto/cloudfront/__init__.py
- moto/cloudfront/exceptions.py
- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- moto/cloudfront/urls.py
- moto/core/utils.py
- moto/server.py
- scripts/scaffold.py
- tests/test_cloudfront/test_cloudfront_distributions.py
- tests/test_cloudfront/test_server.py
Initial implementation of the CloudFront -service
Closes #2408
Methods implemented with this PR:
- create_distribution
- delete_distribution
- get_distribution
- list_distributions
The number of possible input-parameters for the `create_distribution`-method is endless. This PR only adds support for a small subset of possible parameters, focusing on a simple S3-backed distribution.
Custom distributions, backed by ELB/EC2/non-AWS domains have not been validated. They may work, they may not work.
The distribution-endpoint itself is not mocked.
This PR also extends the scaffolding-script to add support for the "rest-xml" protocol. The implementation is not perfect yet, but it's does provide a response-template that can be used as a starting point.
> Feature - CloudFront

- scripts/scaffold.py
- scripts/template/test/test_server.py.j2
- scripts/template/test/test_service.py.j2
New features:
- Adds support for the `rest-xml`-protocol (Mainly used by global services such as S3/Cloudfront/Route53)
- Adds operation-specific test cases
Fixes:
- In Responses, use the generic `self._get_param()` method, instead of type-specific methods
`_get_param()` should work for any type - String/List/Dict/etc
UX fixes:
- Allows the user to try again when providing an unknown service
- Allow the user to try again when providing an unknown operation
- Allow the user to try again when providing an operation already implemented
- Allow the user to implement multiple operations in one session
@kbalk Thanks for the feedback earlier - you raised some good points on how to simplify/improve the usage of this script.
I've separated all the scaffold-changes out, so the other PR just …
> Scaffold-script improvements

- docs/docs/contributing/development_tips/utilities.rst
- moto/cognitoidp/models.py
- moto/cognitoidp/utils.py
- moto/ds/models.py
- moto/ds/utils.py
- moto/events/models.py
- moto/events/utils.py
- moto/glue/models.py
- moto/iot/utils.py
- moto/kinesis/models.py
- moto/kinesis/utils.py
- moto/logs/models.py
- moto/logs/utils.py
- moto/route53/models.py
- moto/route53/utils.py
- moto/route53resolver/models.py
- moto/route53resolver/responses.py
- moto/route53resolver/utils.py
- moto/stepfunctions/utils.py
- moto/utilities/paginator.py
- tests/test_utilities/test_paginator.py
Improvements to the `@paginate`-decorator:
- Improve documentation
- Rename `page_ending_range_keys` to `unique_attribute`, as that is more readable
- Allow option to pass a string as a `unique_attribute` (instead of always having a list)
- Allow passing an Exception on `fail_on_invalid_token`, so that custom exception will be thrown
- Make `max_results` and `next_token` parameters optional in the model
- Fixes a bug where model-arguments could not have a list as default arg (`def model(arg=[])`)
Closes #4584 
FYI @kbalk - this does not yet `check for a limit that exceeds the allowable value for limit`. I couldn't find an example of that use case, and I didn't want to pollute this PR with adding additional service-specific logic.
> Paginator - make development easier + docs

- moto/sqs/exceptions.py
- moto/sqs/models.py
- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
Closes #3435
Supercedes #3586
Summary:
Old receipt handles should be kept, as it is possible to change message visibility or delete a message using them.
The `ReceiptHandleIsInvalid`-error is only thrown when providing a receipt handle that was never issued by AWS.
All tests have been verified against AWS.
The `MessageNotInFlight` has been removed, as I could not find a way to raise this error in AWS.
> SQS - Align logic around receipt_handles with AWS

- moto/core/models.py
- moto/utilities/distutils_version.py
Distutils is deprecated in Python3.10, and will be removed in Python3.12.
The recommendation is tto replace this with either `packaging` or `pkg_resources`, but considering we only need the one class (`LooseVersion`), I reckon it's easier to just package it with Moto for now.
This version is used in one place, to check the version of the `responses`-module and patch it accordingly.
A future improvement would be to:
- Set a lower limit on the `responses`-dependency, so that we only need to support the latest version
- Register a custom matcher with the `responses`-module - the moment they have a registry implemented. (They are currently working on something like that, and I can't wait to use it: https://github.com/getsentry/responses/pull/416)
> Techdebt - remove dependency on deprecated distutils

- moto/s3/models.py
- tests/test_s3/test_s3.py
I have created a test case for https://github.com/localstack/localstack/issues/5068 and run it against AWS S3, `Metadata` and `ContentType` are copied over to a new object, so updating it in `moto` as well
> S3 - copy ContentType and Metadata from source object

- moto/s3/responses.py
- tests/test_s3/test_s3.py
While writing a test to restore an S3 object, I noticed that restore_object() of moto3 does not error on standard class objects.  
For example, bellow code end with InvalidObjectState error message in the case of using real S3.
```py
import boto3
BUCKET_NAME = "SOME_BUCKET"
KEY = "STANDAR_CLASS_FILE"
client = boto3.client('s3')
response = client.restore_object(Bucket=BUCKET_NAME, Key=KEY)
```
```bash
$ python restore_test.py
File "restore_test.py", line 7, in <module>
response = client.restore_object(Bucket=BUCKET_NAME, Key=KEY)
File "C:\Users\TakahisaIshikawa\AppData\Local\Programs\Python\Python37\lib\site-packages\botocore\client.py", line 386, in _api_call
File …
```
> S3 - restore_object() should error on non archived class

- IMPLEMENTATION_COVERAGE.md
- moto/iot/models.py
- moto/iot/responses.py
- tests/test_iot/test_iot.py
Summary: 
Added support for the IoT DomainConfiguration object, and the create/update/describe/list/delete operations.
Added tests covering each operation plus validation. 
Checklist:
> Add support for IoT Domain Configuration

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2_target_groups.py
Also fixes a minor bug where the Matcher-parameter was not picked up in the `create_target` call
Fixes #4702 
Fixes #4695
> ELBv2 - Support create_listener with ForwardConfig param

- moto/sqs/models.py
I am using moto with terraform. After a recent update we can no longer create SQS queues without a policy. I am not totally sure which change caused this issue but after reading through the code it appears there is a way for the `Queue` object to end up in a bad state. Based on the age of the code it seems like this potential has been there for a while but maybe something upstream is depending on the state being valid now.
If `self.policy` is called as a getter it must have `self._policy_json` defined or it will throw an error:
```python
@property
def policy(self):
if self._policy_json.get("Statement"):
return json.dumps(self._policy_json)
else:
return None
```
This method is called in the `attributes` method like so:
```python
if self.policy:
result["Policy"] = self.policy
```
To me the …
> prevent a missing policy json

- moto/batch/models.py
I am testing Batch jobs in moto and many of my batch jobs fail. It appears that some jobs are posting log events that are not in chronological order. I believe this is because here:
```python
for line in logs_stdout + logs_stderr:
date, line = line.split(" ", 1)
date_obj = (
dateutil.parser.parse(date)
.astimezone(datetime.timezone.utc)
.replace(tzinfo=None)
)
date = unix_time_millis(date_obj)
logs.append({"timestamp": date, "message": line.strip()})
```
stdout and stderr are appended together but some stderr events may come before some stdout events. I considered a few things to fix this but ultimately I think sorting the logs after the fact is the best way to fix this. If the logs are out of order for any reason and you want them to stay that way this removes that.
I also considered …
> Batch - ensure that logs are posted in chronological order

- moto/ec2/exceptions.py
- moto/ec2/models.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
Fixes #2762 (Again. Maybe.)
When calling `run_instances`, it is not possible to specify `SubnetId` and `NetworkInterfaces` as main parameters.
AWS throws an error when this happens - this PR emulates that behaviour.
Instead, the subnet-id should be part of the `NetworkInterfaces`-parameter - so this PR also tries to capture any `SubnetId`s that are passed in like that.
> EC2 - SubnetId and NetworkInterfaces cannot both be specified on run_instances

- moto/ec2/exceptions.py
- moto/ec2/models.py
- tests/test_ec2/test_amis.py
Closes #1928
Closes #1829
The latter (auto-create snapshots when creating images) was already fixed in #180, but it used the wrong error message - this PR fixes that.
All affected tests were verified on AWS.
> EC2 - Error when deleting snapshots in use

- moto/s3/responses.py
- tests/test_s3/test_s3_multipart.py
* With Multipart Uploads, If there is no parts yet, `is_truncated` value is set `[]`.
* `parts and self.backend.is_truncated(...)` result is always  `[]` if `parts` is empty list.
* Check `len(parts) != 0` not `parts`.
> fix(s3/listparts): check parts length

- moto/swf/models/__init__.py
- moto/swf/models/history_event.py
- moto/swf/models/timer.py
- moto/swf/models/workflow_execution.py
- tests/test_swf/models/test_timer.py
- tests/test_swf/models/test_workflow_execution.py
- tests/test_swf/responses/test_decision_tasks.py
This PR somewhat addresses https://github.com/spulec/moto/issues/4708, in that more of the unimplemented decision types now have logic backing them.
I was interested also in the StartChildWorkflowExecution decision, but felt the PR was getting big enough and I can live without that for a little while longer.
I have also tried to implement a couple of 'common' failure modes for these decisions, but they are not completed. I have marked TODOs in the code where other failure states should be considered.
> Implement "RecordMarker", "StartTimer", "CancelTimer" and "CancelWorkflowExecution" decisions

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Sign out method assigns `None` instead of tuple. But code expect exactly tuple.
Error on request:
File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
application_iter = app(environ, start_response)
File "/usr/local/lib/python3.7/site-packages/moto/server.py", line 239, in __call__
return backend_app(environ, start_response)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File …
> admin_user_global_sign_out works only once

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
This PR addresses issue localstack/localstack#5172 where is described that the SQS service removes the "\r" character from the body messages when receiving the messages from a queue.
Changes:
- replacement of the `\r` for its unicode representation `&#xd;`. 
- replacement of the `"` for the html entity `&quot;`. This was not necessary but it makes the responses more in pair with the AWS responses.
- Test added to validate character is not being removed.
> Escape windows return character

- Makefile
Followup from #4728, but now we actually enforce pylint
> Pylint on D/E directories

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
This PR addresses issue localstack/localstack#5000 . The issue is that list-metrics does not return all the unique metrics.
The conditional logic here https://github.com/spulec/moto/blob/master/moto/cloudwatch/models.py#L197 checks only if the metrics dimension's name and value are same , to be considered as already present in the list , causing the referenced issue.
Changes
- Improved the conditional logic to check uniqueness by considering all three properties(namespace, name , dimensions)
- Added test case to validate the modified logic and only unique metrics are always returned
> Fix : cloudwatch list metrics 

- moto/kinesis/models.py
- tests/test_kinesis/test_kinesis.py
This PR fixes a bug in kinesis operations returning the fields `"SequenceNumber"`, `"StartingSequenceNumber"`, and `"EndingSequenceNumber"`. This includes `put_record()`, `put_records()`, and `list_shards()`.
Each of these fields now returns a string rather than an int, as per the spec:
Reference: https://docs.aws.amazon.com/kinesis/latest/APIReference/kinesis-api.pdf
> Fix response data types for kinesis operations

- .github/workflows/build.yml
- codecov.yml
- moto/apigateway/models.py
- moto/core/custom_responses_mock.py
- moto/core/models.py
- moto/core/responses_custom_registry.py
Extracts all the custom responses-logic into a dedicated file
Adds a CustomRegistry that works with 0.17.0
Test more versions of `responses`, to ensure Moto works with every possible version
Changes the `responses.reset()` to `responses.calls.reset()`, to ensure that our custom registry and passthru-prefixes are not being reset.
Related PR where the possibility of using the CustomRegistry was raised: #4657
> Fix interoperability with responses 0.17.0

- .github/workflows/build.yml
- moto/apigateway/models.py
- moto/core/custom_responses_mock.py
- moto/core/models.py
Adds more test cases with older versions of `responses`
Removes a method that will no longer exist in the next `responses`-release
Removes a parameter that throws warnings in the latest `responses`-release
> Improve future interoperability with responses-module

- moto/ec2/models.py
- tests/test_ec2/test_prefix_lists.py
This PR adds support for filtering by tags (instead of ignoring the tag filter and returning all results) during calls to `describe_managed_prefix_lists` (EC2 client).
The test added in this PR doesn't pass without the associated change.
I made the minimal change that would allow me to use moto to test a project I'm working on. Please let met know if that approach is OK!
> feat: add support for filtering by tags in describe_managed_prefix_lists

- moto/ec2/models.py
- moto/ec2/responses/vpc_peering_connections.py
Bug where Python would throw an UnboundLocalError in the `get_cross_vpc`-method if no vpc was found in that region.
There was a test for this usecase, `test_vpc_peering_connections_cross_region_fail`. This test fails when running it on it's own, but would pass when running the entire EC2-test suite. That's why it was never discovered.
When a (cross-region) VPC is not found, it should throw a `VpcNotFound` error. 
The new solution simplifies this approach  - it tries to find the VPC in the other region, and the `get_vpc`-method throws the error if the VPC does not exist. 
The test now passes when running on it's own, as well as when running the entire suite.
> EC2 - Cross region VPC peering bug

- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
Currently, if the input to SQS.delete_message_batch() includes an invalid receipt handle, moto returns an error:
```
File "test.py", line 26, in <module>
sqs.delete_message_batch(
File "<...>/botocore/client.py", line 391, in _api_call
File "<...>/botocore/client.py", line 719, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.errorfactory.ReceiptHandleIsInvalid: An error occurred (ReceiptHandleIsInvalid) when calling the DeleteMessageBatch operation: The input receipt handle is invalid.
```
However, if the input to Amazon SQS DeleteMessageBatch API includes an invalid receipt handle, the Amazon SQS API returns the error in Failed field of an 200 OK response:
```
{ …
```
> SQS - Improve delete_message_batch() error responses

- docs/docs/services/ecs.rst
- moto/ecs/models.py
- moto/settings.py
- tests/test_core/test_settings.py
- tests/test_ecs/test_ecs_account_settings.py
- tests/test_ecs/test_ecs_boto3.py
Following AWS' behaviour around this subject, where all new ECS resources created after April 1st, 2021 have the long ARN by default. 
See https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/
> ECS - LongARN is enabled by default

- .github/workflows/build.yml
- .github/workflows/test_outdated_versions.yml
- setup.py
- Removes support for Py3.5
- Speed up Terraform tests, by splitting up the tests over 4 VM's (instead of 3)
> Enable testing for Py3.10

- docs/docs/contributing/new_feature.rst
region must be selected or the script terminates with an error
I was unable to run the script until I set the default region. I chose us-east-1 arbitrarily.
> set region before executing the script

- moto/cloudwatch/exceptions.py
- moto/cloudwatch/responses.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
This PR addresses localstack/localstack#5134. The issue is that exception message thrown currently is bit misleading. 
Changes
1. Changed the `NotImplementedError` exception to `InvalidParameterCombination` exception.
2. Added test case to verify the behaviour.
> Fix : Exception type in cloudwatch get_metric_statistics

- moto/ses/models.py
- moto/ses/utils.py
- tests/test_ses/test_ses_boto3.py
- tests/test_ses/test_ses_utils.py
Adding validation of source and destination addresses as I need a mock related to the following specification.
https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html
> If you send a single message to more than one recipient address, and one of the recipient addresses isn't in a valid format (that is, it's not in the format UserName@[SubDomain.]Domain.TopLevelDomain), Amazon SES rejects the entire message, even if the other addresses are valid.
The validation is minimal and only checks if the domain part of the email address exists.
Full validation is not implemented because the exact specification is unknown.
> feat: SES add (minimal) address validation

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_list_secrets.py
- tests/test_secretsmanager/test_secretsmanager.py
Currently, these dates are missing, but should be present.
As an example, here is a request for list-secrets against AWS:
```
$ aws secretsmanager list-secrets
{
"SecretList": [
{
"ARN": "arn:aws:secretsmanager:...",
"Name": "testsecret",
"Description": "some desc",
"LastChangedDate": "2022-01-17T10:41:35.163000+01:00",
"SecretVersionsToStages": {
"e75a49b6-e07a-4bd9-acd7-510557dfc9b1": [
"AWSCURRENT"
]
},
"CreatedDate": "2022-01-14T19:43:03.127000+01:00"
}
]
}
```
This PR introduces this behavior in moto. As their names say, CreatedDate will only be set on creation of the secret, LastChangedDate also on update operation.
The PR also includes the corresponding tests, both in existing test cases (where fitting, for additional attributes this seemed appropriate) and adds a new test …
> Add CreatedDate and LastChangedDate in secretsmanager responses

- docs/docs/services/organizations.rst
- moto/organizations/models.py
- moto/organizations/responses.py
- tests/test_organizations/test_organizations_boto3.py
As seen in the specification of DeleteOrganization (https://docs.aws.amazon.com/organizations/latest/APIReference/API_DeleteOrganization.html), organizations cannot be deleted when accounts are still assigned to it (except for the master account).
This PR implements this behavior, and implements a rudimentary remove_account_from_organization (so testing is easier).
I hope I did not miss any reference onto this account when deleting it though.
Both behaviors are tested with new test cases.
> Implement remove_account_from_organization, disallow organization deletion if accounts exist

- moto/dynamodb2/comparisons.py
- moto/dynamodb2/exceptions.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_dynamodb2/test_dynamodb_condition_expressions.py
fix [#3635](https://github.com/spulec/moto/issues/3635)
Adds:
- a new type of exception for dynamodb2 (InvalidConditionExpression)
- check if identifiers are reserved keywords during ConditionExpression parsing
- adds test to check behavior
> Enhancement: Add check for reserved keywords in condition expression attributes [dynamodb2]

- moto/dynamodb2/exceptions.py
- moto/dynamodb2/models/__init__.py
- moto/dynamodb2/responses.py
- tests/test_dynamodb2/exceptions/test_dynamodb_exceptions.py
fixes #4779 
during a call of `transact_write_items`
- look for (key, table) pairs in the items
- if there is a match, throw a (newly created) `MultipleTransactionsException`
> DynamoDb2 transact_write_items: Check multiple transacts on same item

- tests/test_logs/test_logs.py
This PR tests the CW logs method `delete_log_stream()` which was missing tests. This checks the happy path:
* create log group
* create log stream
* describe log streams
* assert one exists
* delete log stream
* assert zero exist
> test: add missing test for delete_log_stream

- moto/swf/models/workflow_execution.py
- tests/test_swf/models/test_workflow_execution.py
- tests/test_swf/responses/test_decision_tasks.py
Hello again! A bug fix for the implementation of the timers in https://github.com/spulec/moto/pull/4713
As not explicitly pointed out in the API docs, but mentioned instead [here](https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dg-timers.html), when a timer has fired, a decision task should be scheduled. If this doesn't happen, then the workflow will not progress, as there is nothing notifying it that it should do something.
> When a timer fires, it should also schedule a decision

- moto/s3/models.py
- moto/s3/responses.py
- tests/terraform-tests.success.txt
- tests/test_s3/test_s3.py
Closes #4751 
Adds support for the following headers:
`bucket-key-enabled` - is now returned on CopyObject
`tagcount` - is now returned on GetObject
> S3 - missing features

- AUTHORS.md
- moto/s3/responses.py
- tests/test_s3/test_s3.py
Regarding the API docs, https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_object_tagging `get_object_tagging` method (as well as some others get_object related methods) should return `VersionId` in response.
The current implementation of moto does not return this value which makes it incompatible with real API for this use case.
This PR makes a small change by adding `x-amz-version-id` header to the response in case version exists.
> Missing VersionID for versioned buckets in API

- IMPLEMENTATION_COVERAGE.md
- moto/rds2/exceptions.py
- moto/rds2/models.py
- moto/rds2/responses.py
- tests/test_rds2/test_rds2_export_tasks.py
Hi team.
I'm implementing RDS operators for Aifrow and I'm going to use moto for testing purposes.
So I need to implement some methods for mock_rds2
* DB instance copy snapshot method: #4790
* Cluster snapshot methods: #4790
* **Export task methods (cancel_export_task, describe_export_tasks, start_export_task)**
* Event subscriptions (create_event_subscription, delete_event_subscription, describe_event_subscriptions)
> Add RDS functionality: export tasks

- moto/dynamodb2/models/__init__.py
- tests/test_dynamodb2/test_dynamodb.py
As discussed in spulec/moto#3909 and as per the AWS documentation:
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.FilterExpression
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.FilterExpression
A DynamoDB filter expression should be applied after the query or scan completes.
This PR includes a test case which failed prior to the changes made.
> dynamodb: filter expression should applied after query/scan. fixes spulec/moto#3909

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2.py
- tests/test_elbv2/test_elbv2_target_groups.py
Closes #4711 
Improvements:
- Add ProtocolVersion to the response (defaults to HTTP1)
- Expand the number of valid protocols inline with what AWS considers valid atm
- Move modify_target_group_attributes to `models.py` - no logic changes
- Fixes a bug so that certificates are always persisted after a `modify_target_group`. (Before, they were only persisted if the protocol was changed to `HTTPS` at the same time
> ELBv2 improvements

- moto/batch/models.py
- tests/test_batch/test_batch_task_definition.py
Closes #4806
Seems like part of the cause was that the tests were building a `containerProperties` argument, but then discarding it. Maybe it was a git merge that went wrong some time in the past? Anyway, I've updated it so it actually tests what is intended - which failed as per the issue. Fixed that by coercing the fields to the appropriate types.
I've also removed the randomisation, so that the tests are deterministic and reproducible. It only covers one combination of vCPU and memory, but I think thats enough. Note that AWS Batch on Fargate uses partial vCPUs which might be a bit unexpected, so thats why it is testing 0.25 for vCPU via `resourceRequirements`.
> AWS Batch containerProperties.resourceRequirements as strings

- moto/rds2/exceptions.py
- moto/rds2/models.py
- moto/rds2/responses.py
- tests/test_rds2/test_rds2_event_subscriptions.py
Hi team.
I'm implementing RDS operators for Aifrow and I'm going to use moto for testing purposes.
So I need to implement some methods for mock_rds2
* DB instance copy snapshot method: Add RDS methods #4790
* Cluster snapshot methods: Add RDS methods #4790
* Export task methods #4803
* **Event subscriptions (create_event_subscription, delete_event_subscription, describe_event_subscriptions)**
> Add RDS functionality: event subscriptions

- .github/workflows/build.yml
- moto/batch/models.py
- moto/settings.py
- tests/test_batch/test_batch_jobs.py
- tests/test_sqs/test_sqs_cloudformation.py
Github Actions started failing on batch tests, exposing:
- A timing issue where failing a job too late would not actually fail it
- Tests that were too dependent on Docker being fast - the moment Docker start-up takes longer than the usual 0.5 seconds, tests would fail.
Playing around with the `seconds_to_wait`-parameter ensures that the tests now wait a long time, in case Docker is slow.
This also fixes some SQS tests that would fail if too many queues were created in parallel.
> Increase Batch timeouts, in case Docker takes a while to start

- moto/elbv2/models.py
- moto/iam/models.py
- tests/test_elbv2/test_elbv2_integration.py
Certificates can be managed by both IAM and ACM - see https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#https-listener-certificates
The `modify_listener`-call now checks both ACM and IAM to see if the certificate exists
> ELBv2 - Allow IAM certificates when calling modify_listener

- moto/core/models.py
- tests/test_core/test_decorator_calls.py
Fixes #4831 
Classes that extend the `unittest.TestCase` can have a `setUp`-method - classes that do not use unittest will use `setup` (lowercase).
~~This PR ensures both use-cases are supported.~~
Edit: Pytest also supports a `setup_method` option, as described here: https://docs.pytest.org/en/latest/how-to/xunit_setup.html
This PR now supports everything, as far as I can tell.
---------
As of Pytest 7.x, it looks like the `setup` and `setup_method` require a `function`-argument, that will be populated with the value of the test-function executed next: `def setup(self, function)`.
Our tests all use `def setup(self, *args):` to ensure it works in both pytest 7.x and 6.x
> Non-unittest classes use a lowercase setup-method

- moto/cognitoidp/models.py
Minor fixes to cognito-idp:
* Added missing `TokenType` to  all `AuthenticationResults`
* `REFRESH_TOKEN_AUTH` flow is an alias for `REFRESH_TOKEN` flow, so can be handled by the same logic
* During token refresh, access_token and id_token were incorrectly switched
> FIX: Cognito-idp

- moto/s3/models.py
- tests/test_s3/test_s3.py
This PR addresses issue localstack/localstack#5121 where the user describes that having the same key_name in different bucket triggers the objects to share the same tags.
Changes:
- Addition of bucket name parameter during key object creation.
- Test creation that asserts that the issue is resolved.
> Addition of bucket name when creating a key object

- moto/ec2/responses/instances.py
- tests/test_ec2/test_instance_types.py
I have inspected the return result and saw that the instance types that should have Gpus do have the correct values.
For example, looking at the entry for `g4ad.8xlarge`:
```
{'GpuInfo': {'Gpus': [{'Count': 2,
'Manufacturer': 'AMD',
'MemoryInfo': {'SizeInMiB': 8192},
'Name': 'Radeon Pro V520'}],
'TotalGpuMemoryInMiB': 16384},
'InstanceStorageInfo': {'TotalSizeInGB': 1200},
'InstanceType': 'g4ad.8xlarge',
'MemoryInfo': {'SizeInMiB': 131072},
'ProcessorInfo': {'SupportedArchitectures': ['x86_64']},
'VCpuInfo': {'DefaultCores': 16,
'DefaultThreadsPerCore': 2,
'DefaultVCpus': 32}}
```
> ec2: Add GpuInfo to describe_instance_types

- moto/ec2/models.py
- tests/test_ec2/test_vpcs.py
This change affects both ec2s describe_managed_prefix_lists and describe_prefix_lists, as they boil down to the same method.
As you can see, in the current filter method, the result of filter_resources is (incorrectly) discarded, and replaced by describe_tag_filter (since both operations act on copies of the original object).
This PR fixes this behavior by calculating both operations on the currently valid result (so describe_tag_filter gets the already filtered result).
Also added a test for this behavior.
> Correctly use the filter for describe_..._prefix_lists

- moto/sqs/models.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_sqs/test_sqs.py
This PR addresses issue localstack/localstack#5330. CDK sends the boolean parameters with a capitalized string but the behaviour should be the same as if it send a lowercase string.
> Allow "True" in SQS Queue boolean attributes

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
The API documentation for `initiate_auth` and `admin_initiate_auth` Cognito IDP methods are ambiguous about the supported AuthFlow parameters.
As stated in #4623, AWS have confirmed via email what the valid attributes are. I have also validated the behaviour through testing.
This PR restricts the AuthFlow parameters to the known values for initiate_auth and admin_initiate_auth methods and raises `InvalidParameterException` for invalid or inappropriate auth_flow values.
In the test case raised by #4623, moto will properly emulate AWS by raising an `InvalidParameterException('Initiate Auth method not supported')` exception to the user for using `ADMIN_USER_PASSWORD_AUTH` with the regular user `initiate_auth` endpoint.
> Restrict initiate_auth and admin_initiate_auth AuthFlow

- moto/s3/exceptions.py
- moto/s3/models.py
- tests/test_s3/test_s3.py
In the real AWS S3 API, if you attempt to copy an object to itself without making any changes you get a `bad request` error.
```
import boto3
DEFAULT_REGION_NAME='us-east-1'
client = boto3.client("s3", region_name=DEFAULT_REGION_NAME)
bucket_name = "my-unique-bucket-123321"
s3 = boto3.resource("s3", region_name=DEFAULT_REGION_NAME)
key_name = "my_key"
key = s3.Object(bucket_name, key_name)
s3.create_bucket(Bucket=bucket_name)
s3.Bucket(name='my-unique-bucket-123321')
key.put(Body=b"some value")
client.copy_object(
...     Bucket=bucket_name,
...     CopySource="{}/{}".format(bucket_name, key_name),
...     Key=key_name,
... )
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 391, in _api_call …
```
> bugfix: raise an error when attempting to copy s3 object to itself without any changes

- moto/ses/responses.py
- tests/test_ses/test_server.py
This PR makes following fixes to the response for GetSendStatistics call:
- Change XML tags of statistics items to comply with upstream AWS response.
Closes https://github.com/localstack/localstack/issues/5074
AWS uses the XML tag `<member>` to represent each statictics object, not `<item>`
- Change timestamp representation to ISO 8601 format.
Closes https://github.com/localstack/localstack/issues/3645.
Currently the str representation of Python datetime is used, which causes various clients to fail timestamp parsing since they expect an ISO timestamp.
> SES: Fix GetSendStatistics response template

- moto/rds2/models.py
- tests/test_rds2/test_rds2_clusters.py
closes: #4841
related: #4790
As described in documentation only the following engines are supported for RDS clusters:
`aurora`
`aurora-mysql`
`aurora-postgresql`
`mysql`
`postgres`
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html
I get default versions by running this code:
```
aws rds describe-db-engine-versions --default-only --engine aurora --query "DBEngineVersions[].EngineVersion"
aws rds describe-db-engine-versions --default-only --engine aurora-mysql --query "DBEngineVersions[].EngineVersion"
aws rds describe-db-engine-versions --default-only --engine aurora-postgresql --query "DBEngineVersions[].EngineVersion"
aws rds describe-db-engine-versions --default-only --engine mysql --query "DBEngineVersions[].EngineVersion"
aws rds …
```
> RDS cluster engines' versions fix

- moto/secretsmanager/models.py
- moto/secretsmanager/responses.py
- tests/test_secretsmanager/test_secretsmanager.py
- tests/test_secretsmanager/test_server.py
LocalStack recently received some issue reports about the handling of PutSecretValue requests to secretsmanager. After validating the behaviour of AWS's secretsmanager with respect to PutSecretValue, CreateSecret and DeleteSecret requests, I propose the following fixes.
-- Please note that all tests introduced, or updated, were verified agains AWS before the opening of the pull request.
I updated moto's implementation of `PutSecretValue` to return the version of the secret resulting from the execution of the request itself. This is in contrast to the original logic, which returned the current/default version of the secret.
The fix consists in handling the derivation of the secret version's `VersionId` (either from validation of the provided `ClientRequestToken` value, or generating a new …
> [LocalStack] Fixes to secretsmanager's PutSecretValue, CreateSecret, DeleteSecret

- moto/ec2/exceptions.py
- moto/ec2/models.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
fixes #4852 by adding support for `NoDevice` parameter in `BlockDeviceMappings`.
> handle 'NoDevice' parameter in BlockDeviceMappings #4852

- moto/core/utils.py
- moto/ec2/models.py
- moto/ec2/responses/instances.py
- moto/ec2/urls.py
- moto/ec2/utils.py
- tests/test_apigateway/test_apigateway.py
- tests/test_ec2/test_amis.py
Some low-hanging fruit - these changes resulted in a 10 to 20% performance improvement
Another big improvement would be to have a global cache of templates - currently they are cached per `EC2Response()`-instance, and every request creates a new `EC2Response`
The APIGateway-test change is unrelated, but required to make the tests pass - the latest boto3 changed the format from `str` to `int`
> EC2 performance improvements

- moto/iam/models.py
When attempting to delete a policy that does not exist, a `NoSuchEntity` exception is expected to be returned, as described in the [boto3 iam docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.delete_policy).
This change addresses the `KeyError` that is raised when attempting to delete a policy that does not exist. It follows the logic from `def delete_role()` by first getting the policy from the existing policy dictionary. If the policy does not exist, an `IAMNotFoundException` is raised by `get_policy()` method.
> Fix KeyError Exception on iam.delete_policy

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudtrail.rst
- moto/cloudtrail/models.py
- moto/cloudtrail/responses.py
- moto/organizations/models.py
- tests/terraform-tests.success.txt
- tests/test_cloudtrail/test_cloudtrail.py
- tests/test_cloudtrail/test_cloudtrail_eventselectors.py
- tests/test_cloudtrail/test_cloudtrail_tags.py
- tests/test_organizations/organizations_test_utils.py
- tests/test_organizations/test_organizations_boto3.py
Closes #4780 
- Adds a bunch of new CloudTrail methods
- Adds support for more parameters when creating a trail
- Fixes a bug in `Organizations`, where the `SERVICE_CONTROL_POLICY` was enabled by default. A quick test against AWS itself revealed that no policy is enabled by default
> CloudTrail improvements

- docs/docs/services/sns.rst
- moto/sns/exceptions.py
- moto/sns/models.py
- moto/sns/responses.py
- tests/terraform-tests.success.txt
- tests/test_sns/test_publish_batch.py
- tests/test_sns/test_publishing_boto3.py
- tests/test_sns/test_topics_boto3.py
- Stores any SNS Notifications that were send, so that users can use the internal API to verify the contents
- Fixes the formatting of numbers used as message attributes
- Fixes a bug in publish_batch where message attributes would not be processed correctly
- Fixes the formatting of SNS Errors, so that TF understands error responses correctly
Fixes #3252
Fixes #4756 
Fixes #4757 
Fixes #4819 
Supercedes #4818
> SNS Improvements

- moto/rds2/models.py
- tests/test_rds2/test_rds2.py
This PR fixes `KeyError` exception which arises if `modify-db-instance` is called with a DBParameterGroupName that does not exist.
In that case it will raise a `DBParameterGroupNotFoundError`
> RDS modify-db-instance fix KeyError

- moto/rds2/models.py
- tests/test_rds2/test_rds2.py
This PR enables adding and removing tags from EventSubscription and DBParameterGroup.
Added testcase where DBParameterGroup + EventSubscription tags are modified.
> RDS: enable add and remove tag for resources

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
This relates to the change in https://github.com/spulec/moto/pull/4838.
When using the MetadataDirective, the copy_object call is still allowed, even if no other changes take place. The current version of moto 3.0.4 doesn't allow this.
Example using boto3:
```python
import boto3
key_name = "my_file.txt"
source_bucket = "bucket.bucket.com"
s3_client = boto3.client('s3')
s3 = boto3.resource("s3", region_name='eu-west-1')
key = s3.Object(source_bucket, key_name)
key.put(Body=b"some value")
s3_client.copy_object(
Bucket=source_bucket,
CopySource=f"{source_bucket}/{key_name}",
Key=key_name,
)
s3_client.copy_object(
Bucket=source_bucket,
CopySource=f"{source_bucket}/{key_name}",
Key=key_name,
MetadataDirective="REPLACE",
)
```
I'm not sure if I've done the correct thing here by adding a new …
> Fix copying S3 objects, when using MetadataDirective='REPLACE'

- CHANGELOG.md
- moto/awslambda/models.py
- moto/settings.py
~~Also changed the default to `mlupin/docker-lambda`.~~
Currently the image used for executing Lambda functions is hardcoded:
https://github.com/spulec/moto/blob/e84cc20abe5b92e3bb77bcddd9240d4233a9524e/moto/awslambda/models.py#L613
Unfortunately it seems that development has also stalled, the last release at the time of writing being over one year ago:
- https://github.com/lambci/docker-lambda
- https://hub.docker.com/r/lambci/lambda/tags
Because of this, there is no image built for Python 3.9 which means it is not possible to use this with moto.
~~Instead, we should~~ With this change it is possible to switch to using a supported fork:
- https://github.com/mLupine/docker-lambda
- https://hub.docker.com/r/mlupin/docker-lambda/tags
~~In addition, it is now possible to set~~ This is …
> Added support for custom AWS Lambda images.

- moto/iam/responses.py
- tests/test_iam/test_iam.py
- tests/test_iam/test_iam_cloudformation.py
This PR addresses localstack/localstack#5296. where the user describes that the IAM service is missing the Resource Id (GroupId, UserId and RoleId) when calling **ListEntitiesForPolicy**. I compared the Moto response to AWS and it's true.
Changes:
- Addition of GroupId's, RoleId's and UserId's to the **ListEntitiesForPolicy** response.
- Extension of Iam tests to validate the existanse of the attribute in the response.
> Addition of Entities Ids when listing

- moto/core/utils.py
- moto/s3control/urls.py
- tests/test_core/test_mock_regions.py
Fixes #4893 
The Backend for unknown regions would be recreated for every request, effectively resetting it every time.
This PR ensures a previously created cache entry is actually used
Also removes some unrelated warnings from S3Control
> Unknown regions - fixes a bug in caching mechanism

- moto/core/custom_responses_mock.py
- moto/core/responses_custom_registry.py
- tests/test_core/test_responses_module.py
Closes #4870 
Also match for responses registered against the default_mock, which may have happened before Moto started.
> Fix ordering issue with a user-defined Responses-activation

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
> fix for duplicate tag keys in secretsmanager

- moto/sts/models.py
The default separator, ':',  broke the underlying parser after a security update.
Source: https://bugs.launchpad.net/ubuntu/+source/python-xmltodict/+bug/1961800
Proposed fix to xmltodict: https://github.com/martinblech/xmltodict/pull/290
As far as I can tell, this is the only place where it affects Moto, as no other services use XML namespaces.
This PR should remove the need to wait for any upstream/downstream fixes that may or may not happen.
@thrau FYI, as it looks like were bitten by this first here: https://github.com/localstack/localstack/pull/5585
> Admin - change XML2Dict namespace separator

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
This fixes an issue with deleting secrets in AWS Secrets Manager not
being possible when using the full ARN as secret id, because SecretsStore
didn't do resolve from ARNs to secret names when using get().
Fixes #4917
> Fix deleting secrets by ARN

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2_listener_rules.py
This PR fixes an incorrect error being thrown for `DescribeTags` on listener rules, even when it is valid.
```
$ awslocal elbv2 describe-tags --resource-arns arn:aws:elasticloadbalancing:us-east-1:000000000000:listener-rule/foobar/50dc6c495c0c9188/None139624438527312/bdc4f6368e71c81f
An error occurred (LoadBalancerNotFound) when calling the DescribeTags operation: The specified load balancer does not exist.
```
This is fixed to return correct error for invalid listener rules
```
$ awslocal elbv2 describe-tags --resource-arns arn:aws:elasticloadbalancing:us-east-1:000000000000:listener-rule/foobar/50dc6c495c0c9188/None139835059098528/4e5d3770330e38dc
An error occurred (RuleNotFound) when calling the DescribeTags operation: The specified rule does not exist.
```
and expected response for …
> ELBv2: Fix LoadBalancerNotFound being thrown for listener rules

- moto/elbv2/exceptions.py
- tests/test_elbv2/test_elbv2.py
ELBv2 DescribeListeners requires either listener ARNs or a load balancer ARN. An exception is supposed to be thrown if these are missing.
This exception required an unused `arn` argument which was not passed, causing the following, which is fixed by this PR.
```
File "/home/viren/repo/moto-viren-nadkarni/moto/core/utils.py", line 261, in _wrapper
response = f(*args, **kwargs)
File "/home/viren/repo/moto-viren-nadkarni/moto/elbv2/responses.py", line 320, in describe_listeners
raise ListenerOrBalancerMissingError()
TypeError: __init__() missing 1 required positional argument: 'arn'
```
> ELBv2: DescribeListeners and missing ARNs

- moto/route53/models.py
- moto/route53/responses.py
- `PrivateZone` value type in response
- default behaviour for `PrivateZone` when `vpc` is present
> fixed route53 private zone value

- moto/timestreamwrite/responses.py
- tests/test_timestreamwrite/test_timestreamwrite_table.py
The botocore `WriteRecordsResponse` model was updated to include `RecordsIngested` a few months ago.[1]
* Include `RecordsIngested` in the `moto` response
* Use sample records from AWS documentation in `test_write_records`
[1]:https://github.com/boto/botocore/commit/4a2fc7f7c042b6f20b10b4d9c0454dae173c9969
Closes #4946
> Update Response for TimestreamWrite:WriteRecords

- moto/emr/models.py
- tests/test_emr/test_emr_boto3.py
This is according to the AWS EMR documentation[1] and has been verified against a real AWS backend.
[1]:https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.list_steps
Closes #1866
> Fix: EMR Steps should be returned in reverse order of creation

- tests/test_acm/test_acm.py
- tests/test_budgets/test_budgets.py
Skip tests if OverflowError is raised when boto3 is processing
timestamps.  This is a known limitation of boto3 on 32-bit platforms
(https://github.com/boto/botocore/issues/2355).
Catching OverflowError is the best option here since some 32-bit
platforms (e.g. NetBSD) use 64-bit time_t, and others are working
on providing a switch to the 64-bit type (e.g. glibc).
> Fix test failures on systems with 32-bit time_t

- moto/mediaconnect/responses.py
- tests/test_mediaconnect/test_mediaconnect.py
Currently, we don't return a `ListenerAddress` when creating and describing flows in media connect. This PR add this field in the response for listener based protocols.
> Added support for ListenerAddress based on srt or zixi-pull protocols.

- moto/iot/models.py
- tests/test_iot/test_iot_search.py
- The current implementation of `search_index` did not support wildcard search
- From https://docs.aws.amazon.com/iot/latest/developerguide/query-syntax.html
- "... but searching for "*" matches all things"
> Return all things when using "*" query_string parameter

- moto/elbv2/models.py
- moto/elbv2/responses.py
- moto/resourcegroupstaggingapi/models.py
- moto/utilities/tagging_service.py
- tests/test_elbv2/test_elbv2.py
- tests/test_elbv2/test_elbv2_listener_rule_tags.py
Simplifies the tagging logic in ELBv2. This is now handled by the TaggingService, similar to how other (most?) services handle tags.
This change also fixes a bug, so that it's now possible to add and remove tags from ListenerRules
> ELBv2 - improve tagging

- moto/rds/responses.py
- moto/rds/utils.py
- tests/test_rds/test_utils.py
Follow-up to #4965 
Reuses the generic `_get_multi_param`-method to read RDS filters, instead of a custom method/logic.
> RDS - simplify filter-parameter logic

- moto/ecr/models.py
- tests/test_ecr/test_ecr_boto3.py
Closes #4941 
The `batch_delete_image` only worked in happy scenarios, where one image existed and one image was deleted.
A test was added to verify that we can now delete only a subset of the existing images.
> ECR - Fix bug in batch_delete where images could not be deleted

- moto/logs/responses.py
- tests/test_logs/test_logs.py
Closes #4968 
The regex-pattern for validating the log group name was wrong in three ways:
- It didn't validate that the name should match the regex completely
- The regexes were inconsistent
- It matched against `.-_` - which is interpreted as `every character between . and _`. Changing the order to `-._` ensures that they are interpreted as three different characters
> Logs - fix typo in log-group-name regex

- requirements-dev.txt
https://github.com/psf/black/issues/2964
https://github.com/pallets/click/issues/2232
> Pin click-module, because it causes black to crash

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ecs.rst
- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_ecs/test_ecs_capacity_provider.py
Adds support for:
ECS: create_capacity_provider()
ECS: delete_capacity_provider()
ECS: describe_capacity_providers()
ECS:create_cluster() now supports the parameter `settings`
ECS:delete_service() and ECS:describe_service() can now also be called using ARN's, instead of just the plain name
Closes #4858
> ECS - support for CapacityProviders

- moto/backend_index.py
- moto/iotdata/models.py
- moto/iotdata/urls.py
Botocore 1.24.29 still released a list of regions in get_available_regions.
Botocore 1.24.30 now returns an empty list for `get_available_regions("iot-data").
IOT should have the same regions, so we can use that instead.
AWS also changed the IOTdata endpoint, so we now have to intercept both URL's.
https://github.com/aws/aws-sdk/issues/206
> IOTData - intercept new URLs in botocore 1.24.30

- moto/core/utils.py
- moto/s3/responses.py
- moto/s3/utils.py
- tests/test_s3/test_s3.py
Found out an issue while triaging localstack/localstack#5748, that while creating a bucket, the region from the aws client is not respected. From the comments, I get that in server mode the url is only `localhost:5000` so the url doesn't contain the region. But the region can be also extracted from the request authorization header.
During my testing with I found out that region extracted from the url takes precedence from the header region. So the my patch considers that order before setting the default region.
> Extract region from auth headers for s3 bucket creation

- moto/cloudformation/utils.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Currently the account id on the CloudFormation  stack arn and cloudformation change arn is hardcoded to be 123456789, that is not a valid account id since the length is not 12 digits and also it does not use the same account id as the rest of the resources.
The ACCOUNT_ID was introduced on [this](https://github.com/spulec/moto/pull/2641) PR
> fix cloudformation arn account id

- moto/ecr/models.py
I am pretty sure this should be "ecr" (the AWS name for the ECR service), not "ec2".
I presume the bug arises from a copy-paste error.
The service name appears to only be used to lookup supported regions, which is probably why this bug hasn't had any impact on users.
> Use correct service name for "ecr" in `BackendDict`

- docs/docs/getting_started.rst
This applies two tweaks to the discussion of the `AWS_...` environment variables in the documentation:
- set the same variables in the first block as in the following section (about `pytest`)
- reference the FAQ entry that discusses how to use a region name that AWS doesn't support
(Thanks for moto!)
> Make docs on AWS_... env vars consistent, cross reference FAQ

- docs/docs/services/s3.rst
- moto/s3/models.py
- moto/s3/notifications.py
- tests/test_awslambda/utilities.py
- tests/test_s3/test_s3_lambda_integration.py
It was always possible to persist the configurations for bucket notications (`put_bucket_notification_configuration`) - this PR adds support to send the actual notifications.
Whenever a user creates or copies an object in S3, the configured AWSLambda functions will be invoked and a message will be send to the configured SQS queues.
(Not all events are supported yet, such as deleting objects, creating tags, etc.)
> S3 - initial Notifications implementation

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/test_dynamodb.py
Closes #5010 
This also refactors the overall error handling in DynamoDB - we can now raise errors like in any other service, instead of having to rely on `def error(..)` to format our response
> DynamoDB - extend TransactWriteItems error handling

- moto/rds/responses.py
This pr is to remove the `tags` param in the modify_db_instance implementation as the boto3 API does not support that, otherwise, the existing tags will be cleared.
NOTE: I haven't checked other language SDKs.
> rds - modify_db_instance does not support tags

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2.py
This PR fixes response template for `SetRulePriorities` operations. The template now correctly renders the list of [Rule objects](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SetRulePriorities.html#API_SetRulePriorities_ResponseElements).
The list of valid [Load Balancer attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes) is also updated.
> ELB: Fix response templates

- CONTRIBUTING.md
- Makefile
- docs/docs/contributing/faq.rst
The correct black version is the one in requirements-dev.txt.
Instead of keeping the docs and Makefile in sync they now point to the source of truth.
> Refer to correct black version

- tests/test_swf/responses/test_decision_tasks.py
- tests/test_swf/responses/test_timeouts.py
My computer's local time zone is CEST. Without modifications I could make the
tests pass only by setting the environment variable `TZ=Etc/UTC`.
> fix(swf_tests): compare tz-aware timestamps

- moto/autoscaling/models.py
- moto/autoscaling/responses.py
- moto/ec2/_models/instances.py
- moto/packages/boto/ec2/blockdevicemapping.py
- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_launch_configurations.py
Fixes #4718 
Changes the source format of BlockDeviceMappings, so we can refer to it as a dict, instead of reading `ebs._volume_type`
Change the EC2-logic to also look for BlockDevices in launch_config/launch_template
Also parse the VolumeType in EC2, as that was missing until now
> Autoscaling - pass BlockDeviceMapping from launch_config/launch_template

- moto/autoscaling/models.py
- moto/autoscaling/responses.py
- moto/ec2/_models/amis.py
- moto/ec2/_models/instances.py
- moto/ec2/exceptions.py
- moto/ec2/resources/amis.json
- tests/terraformtests/terraform-tests.success.txt
- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_launch_configurations.py
- tests/test_ec2/test_amis.py
- BlockDeviceMappings defined in a launch config/launch template should be created in addition to the default block device that will be created for an instance.
(This is a follow-up to #5044, where the user-defined mappings replaces the default device)
- Adds the parameters ClassicLinkVPCId, ClassicLinkVPCSecurityGroups, MetadataOptions to the `create_launch_configuration` method
- Fix the ARN creation for launch configurations
- Persist the Throughput/Encrypted/NoDevice parameters when configuring BlockDeviceMappings
EC2 improvements:
- Don't throw an error when describing an image that has been deleted recently (behaviour confirmed against AWS)
- Deregistering the same image twice throws a custom error (behaviour confirmed against AWS)
> Autoscaling - create custom BlockDevice in addition to default image block device

- moto/events/models.py
- tests/test_events/test_events.py
events, delete_rule should throw a ValidationException when attempting to delete a rule which has targets. This PR adds an additional logic, one test case, and modifies two others tests.
The boto3 docs don't really outline this specific `ValidationException`, but they say "Before you can delete the rule, you must remove all targets, using RemoveTargets."
Through testing using my live account I found that it the API does raise a ValidationException with the string "Rule can't be deleted since it has targets."
> events: delete_rule implementation update

- MANIFEST.in
- moto/backends.py
- moto/core/__init__.py
- moto/core/models.py
- moto/core/responses.py
- moto/core/urls.py
- moto/moto_api/_internal/__init__.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
This extracts the MotoAPI functionality into it's own module.
The `core`-module now contains the mocking logic
The `moto_api` module contains the logic for accessing the various API methods that are exposed (such as `reset` and `reset-auth`)
> Admin - Extract MotoAPI functionality to dedicated module

- moto/ec2/_models/network_acls.py
- tests/test_ec2/test_network_acls.py
Adds support for additional filters for EC2 DescribeNetworkAcls operation (documented [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNetworkAcls.html#API_DescribeNetworkAcls_RequestParameters))
> EC2: More filters for DescribeNetworkAcls

- moto/settings.py
The `/proc/self/cgroup` file is not closed properly after reading which causes a `ResourceWarning` to be raised.
> Fix `ResourceWarning` in `moto.settings.is_docker()`.

- moto/sqs/exceptions.py
- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
The validation that a queue name cannot be used for the QueueUrl-parameter was originally introduced in #3657.
As @paulmdavies correctly noticed, this validation does not (anymore?) appear in AWS, so this PR essentially reverts the behaviour.
Closes #5064
> SQS - Accept queue-names as QueueUrl-parameter

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_cognitoidp/test_cognitoidp.py
Responses have been verified against AWS itself, or against the Terraform tests.
This PR also adds support for unauthenticated requests to `sign_up`/`confirm_sign_up`/`initiate_auth`.
As HTTP requests to these methods do not have any authentication-header, we do not know which region they originate from.
All we have is a ClientId coming from the user - which means we just cycle through all regions until we find the region that owns that ClientId
> CognitoIDP - improve default UserPool response

- requirements-dev.txt
The upstream issue <https://github.com/pallets/click/issues/2232> has been solved.
We can upgrade `black` to the latest version and do not need to pin `click`'s version.
> upgrade black and unpin click

- moto/ses/models.py
- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
Adds the get_identity_verification_attributes API
I used the scripts to generate the code, the took the XML from a debug output of awscli.
I'm not too sure if this is all correct, however the test passes. 
I wasn't sure if there was a way of setting a status _other_ than Success, although I feel that might mean we would need to explicitly record/track other status separately from the core boto3 API?
> Support SES get_identity_verification_attributes

- moto/core/responses.py
- moto/ec2/_models/spot_requests.py
- moto/ec2/responses/elastic_block_store.py
- moto/ec2/responses/flow_logs.py
- moto/ec2/responses/instances.py
- moto/ec2/responses/launch_templates.py
- moto/ec2/responses/spot_fleets.py
- tests/test_ec2/test_spot_fleet.py
Supports the `LaunchTemplateConfigs`-parameter in EC2:request_spot_fleet
Also refactors and simplifies the Tag-extraction across EC2 to make it more readable, but without any functional changes.
Closes #4746
> EC2 SpotFleetRequests - support LaunchTemplates

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_cognitoidp/test_cognitoidp.py
- update_group
- global_sign_out
- update_user_attributes
Closes #5001 
Closes #5047 
This also fixes a bug where `admin_user_global_sign_out` signs out every user, regardless of the username passed
> CognitoIDP: new methods

- moto/ec2/_models/instances.py
- moto/ec2/_models/spot_requests.py
- moto/ec2/responses/spot_fleets.py
- moto/ec2/responses/spot_instances.py
- tests/terraformtests/etc/0002-EC2-reduce-wait-times.patch
- tests/terraformtests/terraform-tests.success.txt
- tests/test_ec2/test_spot_instances.py
EC2:request_spot_fleet now supports the InstanceInterruptionBehavior-parameter
EC2:request_spot_instances now supports the InstanceInterruptionBehavior-parameter
EC2:request_spot_fleet now properly formats the spot price to 6 digits
The status of a spot instances request now automatically transitions to 'active/fulfilled'
All behaviour has been verified against Terraform tests
Closes #2625
> EC2 - Spot Requests improvements

- moto/mediaconnect/models.py
- tests/test_mediaconnect/test_mediaconnect.py
Sorry, I intended to fix this in my previous PR but I failed
I've noticed there's a quite a few mismatches between the moto create_flow response and the expected boto3 response (see https://youtype.github.io/boto3_stubs_docs/mypy_boto3_mediaconnect/type_defs/#flowtypedef). I'll try to do a bigger PR in the future to make it a closer match to that
For now this PR at least makes create_flow more usable
> mediaconnect: fix, actually fixing create_flow to allow no outputs

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/databrew.rst
- moto/databrew/exceptions.py
- moto/databrew/models.py
- moto/databrew/responses.py
- moto/databrew/urls.py
- tests/test_databrew/test_databrew_recipes.py
Adds recipe versioning to the databrew support.
This includes these additional methods:
* delete_recipe_version()
* list_recipe_versions()
* publish_recipe()
Also fixed exceptions raised by existing for recipe-related methods to match those in AWS documentation:
* RecipeAlreadyExistsException -> ConflictException
* RecipeNotFoundException -> ResourceNotFoundException
> Databrew: add recipe version support

- moto/core/responses.py
xmltodict 0.13.0 was released earlier today, and uses a `dict` by default - we should allow for both `OrderedDict`s and `dict`s to account for all possibilities.
https://github.com/martinblech/xmltodict/blob/master/CHANGELOG.md
> xmltodict - Allow both OrderedDicts and normal dicts

- moto/rekognition/models.py
- moto/rekognition/responses.py
- tests/test_rekognition/test_rekognition.py
Extends Rekognition support to include get_face_search and start_face_seach
Follows on from this work:
https://github.com/spulec/moto/pull/4957
refs:
https://docs.aws.amazon.com/rekognition/latest/dg/what-is.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rekognition.html
More specifically:
https://docs.aws.amazon.com/rekognition/latest/APIReference/API_GetFaceSearch.html
https://docs.aws.amazon.com/rekognition/latest/APIReference/API_StartFaceSearch.html
Related issue:
https://github.com/spulec/moto/issues/4071
> Extend Rekognition support to include get_face_search and start_face_seach

- moto/moto_server/templates/dashboard.html
Original dashboard can't show JSON (it results `[object Object]`). My fix shows JSON content.
Before 
After
> Fix dashboard not to show JSON as '[object Object]'

- moto/events/models.py
- tests/test_events/test_event_pattern.py
- tests/test_events/test_events_integration.py
Exists matching works on the presence or absence of a field in the JSON of the event.
The value of the field is not considered when evaluating a match.[1]
* Add sentinel to distinguish between missing fields and existing fields with None values
* Update event pattern matching tests to cover this specific use-case.
* Add integrated test to cover this scenario within a larger context.
[1]: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html
Closes #5125
> Fix `Exists` pattern matching with None values

- moto/ec2/models/subnets.py
- moto/ec2/responses/subnets.py
- tests/test_ec2/test_subnets.py
This is currently just a placeholder because Moto does not yet fully support
Ipv6 subnets, but it is included in the Ipv4 subnet responses (set to `False`).
Closes #5021
> Add `Ipv6Native` field to ec2:Subnet response templates

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
Add optional `launchType` parameter to the ECS service according to the latest [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.list_services) version and AWS API
> Add ability to list ECS services by launch type

- moto/apigateway/models.py
- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
Minor addition to the integration model object. The property `passthroughBehavior` is used in the template logic.
> add passthroughBehaviour to the integration

- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2_target_groups.py
The template variable name for the elbv2 healthcheck protocol is incorrect, which causes the healthcheck protocol in any api call response to always be an empty string.
> fix template variable typo

- setup.py
Currently, the moto requirement is `>= 3.0.0`, however, at this line:
https://github.com/spulec/moto/blob/5d84eec79e213c0f71cc3bd7bd94ef55e1d474e4/moto/glue/utils.py#L278
it uses the function `delimited_list` with kwarg `min=1`. 
This keyword only appears starting `3.0.7` in `pyparsing`, causing an exception if you have a lower `pyparsing` version installed.
Link to pyparsing file:
3.0.6
https://github.com/pyparsing/pyparsing/blob/pyparsing_3.0.6/pyparsing/helpers.py
3.0.7
https://github.com/pyparsing/pyparsing/blob/pyparsing_3.0.7/pyparsing/helpers.py
> Set `pyparsing >= 3.0.7` requirement

- setup.py
Closes #5162 
CloudFormation loads all modules, to retrieve the full list of CloudFormationModels that it knows about, so it should also install all dependencies.
> CloudFormation - specify all dependencies

- docs/docs/services/events.rst
- moto/events/models.py
- moto/events/notifications.py
- moto/s3/models.py
- tests/test_events/test_events_lambdatriggers_integration.py
This PR lays the groundwork for sending events when a specific event occurs.
(Docs: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-service-event.html)
Supported events in this PR: S3:CreateBucket
Supported targets: AWSLambda functions
Considering the number of combinations of possible targets and events, I wanted to keep it as simple as possible. It is extendable though, so future PR's can add to the list of supported events/targets.
Closes #2736
> Events - send events to (subset of) targets

- moto/iam/responses.py
This PR addresses localstack/localstack#6119. If HardExpiry is not set, Moto returns 'none' as value, which makes terraform crash when parsing the XML response.
> More param defaults for update password policy 

- moto/applicationautoscaling/models.py
This PR adds an application-autoscaling dimension for MSK. Currently `broker-storage`is the only resource dimension for Kafka: https://docs.aws.amazon.com/autoscaling/application/APIReference/API_ScalableTarget.html
This example request was taken from the docs here: https://docs.aws.amazon.com/autoscaling/application/userguide/services-that-can-integrate-msk.html
```sh
aws application-autoscaling register-scalable-target \
--service-namespace kafka \
--scalable-dimension kafka:broker-storage:VolumeSize \
--resource-id arn:aws:kafka:us-east-1:123456789012:cluster/demo-cluster-1/6357e0b2-0e6a-4b86-a0b4-70df934c2e31-5 \
--min-capacity 100 \
--max-capacity 800
```
I know that moto does not have MSK support yet, so I cannot add a proper test for it. I tested it against LocalStack.
> add kafka broker-storage VolumeSize to application autoscaling dimensions

- AUTHORS.md
- setup.py
`Werkzeug<0.5` fails installation on Moto with py38. Pinning to `>=0.5` allows the install to successfully happen.
(installing `werkzeug==0.4` after `moto`)
(installing `werkzeug==0.5` after `moto`)
> Pin versions of werkzeug

- moto/ec2/models/network_acls.py
- tests/test_ec2/test_network_acls.py
This PR adds the EC2 Network ACL filter for the `egress` flag. 
This is not in the [official documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNetworkAcls.html#API_DescribeNetworkAcls_RequestParameters
), for network acl filters, but AWS allows it (and it is sometimes queried by Terraform)
```
% aws ec2 describe-network-acls --filters Name=entry.egress,Values=false 
{
"NetworkAcls": [
{
"Associations": [
{
"NetworkAclAssociationId": "aclassoc-bc6a1111",
...
```
> add ec2 network-acl egress filter

- moto/kms/models.py
- tests/test_kms/test_kms_boto3.py
- tests/test_kms/test_model.py
When using Localstack with moto as the KMS provider, I encountered issues with selecting a key via the alias ARN. I believe this change fixes the issue by ensuring the `alias/` prefix is included when the name is extracted from the ARN. I've added tests to the KMS model to verify that, and that encryption works via all the other supported mechanisms
> Bug fix for selecting KMS key via alias ARN

- moto/route53/exceptions.py
- moto/route53/models.py
- moto/route53/responses.py
- moto/route53/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_route53/test_route53.py
- tests/test_route53/test_route53_cloudformation.py
- TestAccRoute53Record_basiac
- TestAccRoute53Record_underscored
- TestAccRoute53Record_disappears
- TestAccRoute53Record_Disappears_multipleRecords
- TestAccRoute53Record_Basic_fqdn
- TestAccRoute53Record_Basic_trailingPeriodAndZoneID
- TestAccRoute53Record_txtSupport
- TestAccRoute53Record_spfSupport
- TestAccRoute53Record_caaSupport
- TestAccRoute53Record_dsSupport
- TestAccRoute53Record_generatesSuffix
- TestAccRoute53Record_wildcard
- TestAccRoute53Record_failover
- TestAccRoute53Record_Weighted_basic
- TestAccRoute53Record_WeightedToSimple_basic
- TestAccRoute53Record_Alias_s3
- TestAccRoute53Record_Geolocation_basic
- TestAccRoute53Record_HealthCheckID_setIdentifierChange
- TestAccRoute53Record_HealthCheckID_typeChange
- TestAccRoute53Record_Latency_basic
- …
> fixed route53 rrset terraform suit

- moto/s3/exceptions.py
Hello!
This PR fixes the HTTP status code for the InvalidObjectState error.
The expected HTTP code ([AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html)) is 403.
> Fix InvalidObjectState HTTP status code

- docs/docs/services/cognito-idp.rst
- moto/cognitoidp/models.py
- moto/cognitoidp/utils.py
- moto/settings.py
- tests/test_cognitoidp/test_cognitoidp.py
Hi!
We create a Cogito UserPool before running integration tests, and random IDs complicate the process of finding a pool.
I added an environment variable `MOTO_COGNITO_IDP_USER_POOL_ID_STRATEGY=HASH`, setting which makes the ID of Cognito Userpool reproducible. I think this change will be useful to other moto users as well.
> Stable cognito user pool

- moto/route53/exceptions.py
- moto/route53/models.py
- moto/route53/responses.py
- moto/route53/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_route53/test_route53.py
**APIs**
- associate_vpc
- disassociate_vpc
- Mechanism to store VPC in FakeZone
- TestAccRoute53Zone_basic
- TestAccRoute53Zone_disappears
- TestAccRoute53Zone_multiple
- TestAccRoute53Zone_comment
- TestAccRoute53Zone_delegationSetID
- TestAccRoute53Zone_forceDestroy
- TestAccRoute53Zone_ForceDestroy_trailingPeriod
- TestAccRoute53Zone_tags
- TestAccRoute53Zone_VPC_single
- TestAccRoute53Zone_VPC_multiple
- TestAccRoute53Zone_VPC_updates
Note:
- The test `test_hosted_zone_private_zone_preserved` was expecting to create a vpc without having to add VPC info. In `create_hosted_zone` response VPCs section was having one entry with empty string so it was expecting len(vpc) == 1. (Which was changed to contain empty vpc list::: len(vpc) == 0)
- Future Work: Need to make sure we can create a …
> fixed tf suite: Route53HostedZone

- moto/databrew/models.py
- tests/test_databrew/test_databrew_datasets.py
This adds support for including a ResourceArn as part of the dataset(s) returned by `list_datasets()`, `describe_dataset()` and `update_dataset()`.
> Databrew: support for returning ResourceArn in databrew datasets

- moto/route53/models.py
- moto/route53/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_route53/test_route53.py
- TestAccRoute53ZoneAssociation
- TestAccRoute53ZoneAssociation_basic
- TestAccRoute53ZoneAssociation_disappears
- TestAccRoute53ZoneAssociation_Disappears_vpc
- TestAccRoute53ZoneAssociation_Disappears_zone
- TestAccRoute53ZoneAssociation_crossAccount
- TestAccRoute53ZoneAssociation_crossRegion
- TestAccRoute53ZoneDataSource_id
- TestAccRoute53ZoneDataSource_name
- TestAccRoute53ZoneDataSource_tags
- TestAccRoute53ZoneDataSource_vpc
- ListHostedZoneByVPC
- Updated association response to be more precise
> fixed tf-tests: TestAccRoute53Zone, TestAccRoute53ZoneDataSource

- moto/ec2/exceptions.py
- moto/ec2/models/route_tables.py
- tests/test_ec2/test_route_tables.py
Implemenation for handling non local routes that already exist for #5187 
Signed-off-by: mmerrill3 <jjpaacks@gmail.com>
> feature: handle overlapping routes (#5187)

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_functions.py
- create_function_definition
- list_function_definitions
- get_function_definition
- delete_function_definition
- update_function_definition
- create_function_definition_version
- list_function_definition_versions
- get_function_definition_version
> Greengrass Implement function_definition APIs 

- moto/s3/responses.py
- tests/test_s3/test_s3.py
This pr addresses issue #5228. Now that the list_objects_v2 response has the `EncodingType` attribute, Boto3 tries to decode the attributes `Prefix` and the `CommonPrefixes` like with the name of a Key Object. 
Changes: 
- Encoding of Prefix and CommonPrefixes if necessary.
- The added test groups the multiple reproducers provided in the issue.
> Fix encoding for prefix and commonPrefixes

- moto/secretsmanager/exceptions.py
- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
- tests/test_secretsmanager/test_server.py
Howdy folks, just started using moto, it's been a great help with testing some lambdas I've got. 
I noticed that the get_secret_value operation has a minor issue where we weren't checking that the version_stage and version_id match each other. the AWS cli and boto3 will throw an error in real life.
> Update get_secret_value to properly check versions and stages match

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/databrew.rst
- moto/databrew/models.py
- moto/databrew/responses.py
- moto/databrew/urls.py
- tests/test_databrew/test_databrew_jobs.py
- tests/test_databrew/test_databrew_rulesets.py
Adds initial support for databrew profile jobs and recipe jobs
The following new methods are supported:
* create_profile_job()
* create_recipe_job()
* delete_job()
* describe_job()
* list_jobs()
* update_profile_job()
* update_recipe_job()
Also fixed the following:
* describe_recipe() and describe_ruleset() now correctly get picked up by the scripts/implementation_coverage.py script and so appear in `IMPLEMENTATION_COVERAGE.md` and `docs/docs/services/databrew.rst`
* CreateDate field now correctly returned in recipes and datasets
* Fixed HTTP status code returned by databrew describe_ruleset() and delete_ruleset()
> Adds CRUD support for databrew recipe jobs and profile jobs

- moto/route53resolver/models.py
- tests/terraformtests/terraform-tests.success.txt
- TestAccRoute53ResolverEndpoint_basicInbound
- while using `create_resolver_endpoint` - SubnetID is required field and IP address is optional. If we dont provide IP address it should automatically assign ip from subnet cidr.
> fixed route53 resolver endpoint creation without ip address

- moto/glue/models.py
- tests/test_glue/test_datacatalog.py
Added a CreateTime key to the Glue get_table response to match the boto3 functionality here:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_table
Implemented just like the glue database CreateTime.
Really enjoying the library! Let me know of any edits you'd like to see.
> add createtime to glue table response

- moto/sns/models.py
- tests/test_sns/test_application_boto3.py
While making some changes for localstack/localstack#6256 in came to light that AWS deletes the endpoints of a deleted platform application.
Changes:
- deletion of endpoints when deleting the platform app.
- test  that validates that the endpoint doesn't exist after it's app was deleted.
Note: in AWS it takes like 5 seconds to delete the endpoint after the deletion of the app.
> Deletion of endpoints after platform app

- IMPLEMENTATION_COVERAGE.md
- moto/dynamodb/models/__init__.py
- moto/ec2/models/elastic_block_store.py
- moto/kms/models.py
- moto/kms/responses.py
- moto/kms/utils.py
- tests/test_kms/test_kms_boto3.py
This is adding support for KMS [sign](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html) and [verify](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html).
I added support for `KeySpec`  keeping support for the deprecated deprecated `CustomerMasterKeySpec`. I can move that change to another PR if it makes things easier.
This is not the full implementation for sign and verify, as the algorithm and private key type are hardcoded. But it's enough to use `sign` and `verify` within the application. Would that be enough for now? It is good enough for our use case.
`GrantTokens` and `MessageType` `DIGEST` are not supported as well.
> Add KMS Sign/Verify

- moto/kms/models.py
- moto/kms/responses.py
- tests/test_kms/test_kms_boto3.py
The deploy step is complaining about test coverage so I added more tests to
fix it. https://codecov.io/gh/spulec/moto/commit/25aad70481d2b99b80b1a89c90ad21c20628c2a2
By adding this coverage, I tested sending hash digests to sign and verify and they seem to be working fine, so I removed the warning.
> Improve test coverage of KMS sign and verify

- moto/s3/models.py
- tests/test_s3/test_s3.py
This is another fix for another issue that came from encoding the key's name. Mentioned in localstack/localstack#6323
> Fix: S3 Key safe_name should avoid encoding "/"

- moto/iot/models.py
- tests/test_iot/test_iot_policies.py
According to the [AWS documentation here](https://docs.aws.amazon.com/iot/latest/developerguide/thing-groups.html#group-attach-policy) the `target` can be one of these three:
- thing group ARN **(this PR)**
- certificate ARN _(already implemented)_
- Amazon Cognito Identity _(already implemented)_
I've add two tests and refactored the other tests in `test_iot_policies.py` to reduce duplication a bit.
If that is unwanted I'll be happy to revert the state of the tests.
Feedback greatly appreciated!
Thanks for all the work on this very helpful library and kind regards.
> IOT - allow attaching policies to ThingGroups

- moto/core/models.py
For tests with multiple decorators, each decorator will reset at the beginning, and make a call to `localhost:5000/moto_api/reset`.
However, the `reset`-implementation resets everything in the backend - so there's no point in calling the reset-API multiple times.
This only goes for ServerMode, but should increase performance of our internal tests by reducing the number of HTTP calls made.
> ServerMode - dont bother resetting multiple times in parallel

- moto/ec2/models/elastic_block_store.py
- moto/kms/models.py
Also ensures that KMS uses it's own ValidationException - there's no point in importing APIGateway's.
> EBS - Defer imports until it's necessary

- moto/cloudwatch/responses.py
- tests/test_cloudwatch/test_cloudwatch_alarms.py
This PR provides a fix for cloudwatch `describe-alarms`: 
- Parse the value of `ActionsEnabled` as boolean, and set in the template as string
- Enhanced test cases to verify behavior.
- Default value for `ActionsEnabled` is True [according to the API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html).
> fix return value of 'ActionsEnabled' for describe-alarms

- moto/iot/models.py
- tests/test_iot/test_iot_policies.py
According [to the docs](https://docs.aws.amazon.com/iot/latest/apireference/API_DeletePolicy.html) all non-default policy versions have to be deleted before deleting a policy itself.
> check for non-default policy versions before deleting

- moto/core/responses.py
- tests/test_core/test_responses.py
`DynamicDictLoader` supports caching but the loader and the environment would be created on each construction, rather than shared, enabling caching. Here we cache the Jinja environment (and loader) by response type.
In terms of real performance, this gives is a couple of ms (measurements made with the motoserver):
After this change:
```
In [106]: timeit for i in range(10): sqs_client.create_queue(QueueName=str(i))
85.5 ms ± 3.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [107]: timeit for i in range(10): sqs_client.create_queue(QueueName=str(i))
68.3 ms ± 3.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Master:
```
In [108]: timeit for i in range(10): sqs_client.create_queue(QueueName=str(i))
99.9 ms ± 3.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop …
```
> Cache Jinja environment by response type

- moto/iot/models.py
- tests/test_iot/test_iot_policies.py
The current implementation will not increment beyond 5 and will create duplicate version ids.
This fixes that by finding the current max version and incrementing that by one for the newly created one.
> fix increment policy version ids

- moto/iot/models.py
- tests/test_iot/test_iot_thing_groups.py
The current behaviour is incomplete.
See this usage of the cli and notice that the `thingGroupId` is equal in the last call:
```
❯ aws iot create-thing-group --thing-group-name example --thing-group-properties '{"thingGroupDescription": "example"}'
{
"thingGroupName": "example",
"thingGroupArn": "arn:aws:iot:eu-central-1:123456789012:thinggroup/example",
"thingGroupId": "e57b175c-87ed-41c9-99ae-bf505bedff0e"
}
❯ aws iot create-thing-group --thing-group-name example --thing-group-properties '{"thingGroupDescription": "another one"}'
An error occurred (ResourceAlreadyExistsException) when calling the CreateThingGroup operation: Thing Group example already exists in current account with different properties
❯ aws iot create-thing-group --thing-group-name example --thing-group-properties …
```
> check for existing thing group when creating

- moto/sns/models.py
- tests/test_sns/test_subscriptions_boto3.py
With this PR it is now possible to set the attribute SubscriptionRoleArn for a Subscription. Related to localstack/localstack#6426
> Allow subscription role attribute to SNS.Subscription

- moto/iam/models.py
- moto/iam/responses.py
- Add a missing attribute `EnableDate` to the `ListMFADevices` response.
- Save base64 encoded attribute `QRCodePNG` as plaintext instead of bytes for `CreateVirtualMFADevice`
Closes https://github.com/localstack/localstack/issues/6451, https://github.com/localstack/localstack/issues/6450
> IAM: Issues with ListMFADevices and CreateVirtualMFADevice

- moto/rds/models.py
- tests/test_rds/test_rds_clusters.py
Throw the correct exception if the requested cluster does not exist. Fixes #5320
> Fix KeyError on describe_db_clusters for non-existent cluster

- moto/codepipeline/models.py
- tests/test_codepipeline/test_codepipeline.py
Add a test where a valid trust policy is provided but where tests will fail and add a test where no tags are provided which will fail with the current code.
A commit will be added afterwards to make the tests green.
> bugfix codepipeline handling iam trust policies and absence of tags.

- moto/ec2/models/elastic_ip_addresses.py
- moto/ec2/responses/elastic_ip_addresses.py
- tests/test_ec2/test_elastic_ip_addresses.py
Added two new keys for the `describe-addresses` response:
1. `PrivateIPAddress`; 
2. `NetworkInterfaceOwnerId`.
Updated comment with outdated cloudformation link.
closes #4088.
> Add extra keys to EC2 `describe-addresses` operation

- moto/kms/models.py
- moto/kms/responses.py
- moto/kms/utils.py
- tests/test_kms/test_kms_boto3.py
The current version of moto/kms only supports single-region keys. This change adds some very basic support for multi-regional keys. For details about such keys see https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html
The added implementation is far from thorough. There is a whole infrastructure on AWS behind multi-regional keys - they get synced with each other automatically if certain fields get changed. Also not all the fields are supposed to be copied to a replica key from its master key. But it is at least something.
> Adding support for multi-region keys in KMS and implementing replicate_key API.

- moto/iot/models.py
- tests/test_iot/test_iot_thing_groups.py
This fixes a bug when updating a thing group without attributes.
To reproduce it:
```py
client = boto3.client("iot")
client.create_thing_group(thingGroupName="example")
client.update_thing_group(
thingGroupName=name,
thingGroupProperties={
"attributePayload": {
"attributes": {"example-attribute": "example-value"},
"merge": False,
}
},
)
```
I also fixed a minor difference in behaviour. When a thing group is updated with an empty object for `"attributes"` AWS will simply ignore it and not add it to the properties.
> fix attribute addition when updating thing groups

- moto/glue/responses.py
- tests/test_glue/helpers.py
- tests/test_glue/test_datacatalog.py
Related issue: https://github.com/spulec/moto/issues/3571
> This is still not fully solved, the CatalogId is not correctly handled. As seen in the Boto3 docs for [create_database](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_database) the call is made with CatalogId and DatabaseInput.
> 
> This means that in the [glue/responses.py](https://github.com/spulec/moto/blob/004c971a27d00b7a76b42f88cf3b095f672fff17/moto/glue/responses.py#L21) the CatalagId should be placed in the DatabaseInput or handled like database_name.
> 
> My suggestion would be the following:
> 
> ```python
>     def create_database(self):
>         database_input = self.parameters.get("DatabaseInput")
>         database_name = database_input.get("Name")
> …
```
> Support CatalogId in create_database

- moto/iam/models.py
- tests/test_iam/test_iam.py
According to this [doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html) an IAM user can only have a maximum of 2 access keys.
Related to:  https://github.com/localstack/localstack/pull/6488
> IAM Access Key limit per user

- moto/core/responses.py
- tests/test_core/test_responses.py
Fixes #5342
Jinja2 expects templates stored in an environment to be [named using strings](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment.get_template), not integers.
> Core: Use strings for Jinja2 template names

- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
AWS does not serialize NULL values.
Closes #5346
> Fix: `KeyName` should not be in `ec2:DescribeInstances` response if value is `None`

- IMPLEMENTATION_COVERAGE.md
- moto/iot/models.py
- moto/iot/responses.py
- tests/test_iot/test_iot_policies.py
according to the [docs of `ListPolicyPrincipals`](https://docs.aws.amazon.com/iot/latest/apireference/API_ListPolicyPrincipals.html) it is deprecated in favour of [`ListTargetsForPolicy`](https://docs.aws.amazon.com/iot/latest/apireference/API_ListTargetsForPolicy.html). That action is missing from the `IoTBackend` so I added it.
The behaviour is different to `ListPolicyPrincipals` when the policy does not exist:
```
❯ aws iot list-policy-principals --policy-name I_DO_NOT_EXIST
{
"principals": []
}
❯ aws iot list-targets-for-policy --policy-name I_DO_NOT_EXIST
An error occurred (ResourceNotFoundException) when calling the ListTargetsForPolicy operation: Policy not found
```
> add list_targets_for_policy action to IoTBackend

- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_key_length_exceptions.py
fix #5345 by making sure an exception is raised if a user is trying to get an item but providing an empty key
> DynamoDB: add check for empty key when getting an item (fix #5345)

- AUTHORS.md
- moto/iot/models.py
- tests/test_iot/test_iot_policies.py
```
❯ aws iot create-policy --policy-name example --policy-document '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Acti
on": "*", "Resource": "*"}]}'
An error occurred (ResourceAlreadyExistsException) when calling the CreatePolicy operation: Policy cannot be created - name already exists (name=example)
```
Right now the policy is just overwritten in `moto`
> check if policy name already taken

- .github/workflows/test_terraform.yml
- tests/terraformtests/terraform-tests.success.txt
Should half the run-time.
Only Route53 is split for now, as that is the only service that takes 40+ minutes - others may get the same treatment in the future.
> TF - split long-running tests

- moto/ec2/exceptions.py
- moto/ec2/models/launch_templates.py
- tests/test_ec2/test_launch_templates.py
Currently, when calling `ec2 describe-launch-templates` with a template name
that does not (yet) exist, an unhandled exception occurs and HTTP 500 is
returned.
This commit adds a check for the existence of the passed launch template name.
If a template by this name does not exist, an `InvalidLaunchTemplateNameNotFoundError` is raised.
It also renames the current `InvalidLaunchTemplateNameError` to `InvalidLaunchTemplateNameAlreadyExistsError`,
so that both cases are representable.
> fix(ec2): handle non-existent template for describe-launch-templates

- moto/ec2/resources/instance_types.json
This PR regenerates the instance_types.json file.
This is because some the instance types listed in instance type offerings, were not listed in instance_types.json
e.g.
```
botocore.exceptions.ClientError: An error occurred (InvalidInstanceType.NotFound) when calling the DescribeInstanceTypes operation: The instance type '{'c6a.2xlarge', 'c6a.large', 'c6a.24xlarge', 'c6a.xlarge', 'c6a.8xlarge', 'c6a.12xlarge', 'c6a.48xlarge', 'c6a.32xlarge', 'c6a.4xlarge', 'c6a.16xlarge'}' does not exist
```
> Regenerated instance types

- moto/rds/models.py
- tests/test_rds/test_rds.py
AvailabilityZone information was not printed in create/describe calls for regular RDS.
Resolves #5371
> Add AvailabilityZone to describe_db_instances

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ec2.rst
- moto/ec2/models/__init__.py
- moto/ec2/models/fleets.py
- moto/ec2/models/instances.py
- moto/ec2/responses/__init__.py
- moto/ec2/responses/fleets.py
- moto/ec2/utils.py
- tests/test_ec2/test_fleets.py
This MR adds:
- EC2 CreateFleet
- EC2 DescribeFleets
- EC2 DescribeFleetInstances
- EC2 DeleteFleets
The main reason is because I need they for another project that I'm working on. I'm not a 24/7 python developer, but most of the implementation was based on ~stolen from~ the `spot_requests` files.
> EC2: Add ec2 fleets basic api

- moto/awslambda/models.py
- tests/test_awslambda/test_lambda_layers.py
After reading the ticket above, I decided to try and fix the bug 😄 
The bug happened when a user created a layer, which resulted in a new layer version, and then deleted that same layer.
The issue here is that at first, there is no layer. When we create one, we add a new `Layer` to the `LayerStorage._layers`. Now, that same `Layer` we are going to add to its dict attribute `layer_versions` the first version. 
So now, `Layer` has `_latest_version = 1` and `layer_versions = {'1': layer_v1}`
Now when we delete that layer version, we don't reset `_latest_version` since we want to keep track of our versions, but we do remove element in the dictionary. I think _that's bug number one_
We also keep the layer instance in the Layer storage, and we retrieve all Layers, we used to retrieve all even …
> fix: Error listing Lambda layers after layer deletion

- moto/dynamodb/models/__init__.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/test_dynamodb.py
When doing `scan`, `get_item` and `query` operations, we can specify which attributes to get instead of getting all of them. For this case, AWS provided __projection expression__.
However, the value of __projection expression__ have some restrictions.
As specified in the [AWS documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html):
> If an attribute name begins with a number, contains a space or contains a reserved word, you must use an expression attribute name to replace that attribute's name in the expression.
Currently, we do not really check on the __projection expression__ value at all. Thus, as specified in the issue, when we do the following;
``` python
client.query(
TableName=table_name, …
```
> enhancement: add DynamoDB Projection Expression constraints check

- .github/workflows/test_outdated_versions.yml
- moto/core/custom_responses_mock.py
- moto/core/responses.py
- setup.py
Removes support for responses <= 0.12.1
Also removes an old workaround for older versions of Jinja2. We only support `Jinja2>=2.10.1` anyway, so overriding `DictLoader.get_source` is pointless.
> TechDebt - remove support for old Jinja2+Responses

- moto/route53/models.py
- tests/test_route53/test_route53_cloudformation.py
There is [exactly one backend defined for route53](https://github.com/spulec/moto/blob/master/moto/route53/models.py#L815), and it is the "global" one:
```python
route53_backends = BackendDict(
Route53Backend, "route53", use_boto3_regions=False, additional_regions=["global"]
)
```
But, this one method is using the given region, presumably the one of the containing CloudFormation stack?
I am pretty sure this was just an oversight in https://github.com/spulec/moto/pull/5192. The right region is used [15 or so lines above](https://github.com/spulec/moto/blob/master/moto/route53/models.py#L235):
```python
backend = route53_backends[account_id]["global"]
```
> Fix bug. route53 backend should be global

- moto/moto_api/_internal/responses.py
- tests/test_core/test_moto_api.py
Fixes #5326 
When calling `BaseModel.__new__`, created instances are stored in `model_data`
We then try and initialize the instance by calling `__init__`
However, initialization may fail, and if that happens none of the regular attributes will be set.
This PR ensures that we can still print/__repr__ the uninitialized instance, despite the fact that no attributes have been set
> MotoAPI - do not blow up on uninitialized objects

- moto/autoscaling/models.py
- tests/test_autoscaling/test_autoscaling.py
Fixes #5327 
Verified against AWS - it will just take the Default if no version is specified
> EC2: Allow ASG to be created without specifying a Template version

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/personalize.rst
- moto/__init__.py
- moto/backend_index.py
- moto/personalize/__init__.py
- moto/personalize/exceptions.py
- moto/personalize/models.py
- moto/personalize/responses.py
- moto/personalize/urls.py
- tests/test_personalize/test_personalize_schema.py
Initial implementation of the Personalize-service.
It only covers a small subset of the operations, but this should make subsequent PR's easier.
Closes #3785
> Feature: Personalize (Schemas)

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_multipart.py
This PR addresses localstack/localstack#6604. Now the S3 Multipart stores the 'SSE' and `KmsKeyId` values and uses them when creating the key parts and the complete key.
> Store and return ServerSideEncryption and KMS Key Id for S3 Multiparts

- moto/batch/models.py
- tests/test_batch/test_batch_jobs.py
I was testing AWS batch via a mock environment and identified some issues with `cancel_job`. Specifically, it raises a `AttributeError` when cancelling a non-existing job id. I would expect it to behave like `terminate_job`and raise a `ClientException("Job not found")`. Therefore, I have aligned `cancel_job` to behave like `terminate_job`.
> align batch cancel_job and terminate_job

- docs/docs/services/s3.rst
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_ownership.py
This PR addresses localstack/localstack#6634. With these changes the S3 service supports the CRUD operations of a bucket ownership rule.
> Support for ownership rule configuration

- moto/kms/models.py
- tests/test_kms/test_kms_grants.py
Revoke grant raises `NotFoundException` when the grant does not exist.
This aligns moto behavior with boto3/aws.
Also removed `test_revoke_grant_by_token` as it was just a copy of `test_retire_grant_by_token`.
There is no `revoke_grant_by_token` functionality in boto3's kms client. 
It must have have been a copy-paste leftover.
Issue [5411](https://github.com/spulec/moto/issues/5411)
> KMS: revoke grant raises NotFound

- moto/dynamodb/responses.py
- tests/test_dynamodb/test_dynamodb.py
Addresses #5354 by raising an exception.
> Dynamodb - ensure getItem does not use both expression and non-expression

- moto/apigateway/models.py
- tests/test_apigateway/test_apigateway.py
This PR adds a guard to cases where moto tries to add an integration response when there is no integration (yet).
The result is this exception.
```
File ".venv/lib/python3.10/site-packages/moto/apigateway/responses.py", line 497, in integration_responses
integration_response = self.backend.put_integration_response(
File ".venv/lib/python3.10/site-packages/moto/apigateway/models.py", line 1640, in put_integration_response
integration_response = integration.create_integration_response(
AttributeError: 'NoneType' object has no attribute 'create_integration_response'
```
> add guard against no integration when adding a new response

- docs/docs/services/logs.rst
- moto/logs/models.py
- moto/logs/utils.py
- tests/test_logs/test_logs.py
- tests/test_logs/test_logs_filter.py
Fixes #1873
This also moves some tests around, and reintroduces them as a TestCase, in order to reduce the code duplication between them.
> CloudWatchLogs:filter_log_events() now supports the filterPattern-parameter

- moto/acm/models.py
The `cryptography` library returns information about certificates using the UTC timezone (e.g., for the [`not_valid_before` property](https://cryptography.io/en/latest/x509/reference/?highlight=not_before#cryptography.x509.Certificate.not_valid_before)). However, `moto` uses `datetime.now()`, which returns the time for the user's current timezone.
I generated a self-signed certificate for testing some ACM behaviors, and I encountered this error:
> botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ImportCertificate operation: The certificate chain is not in effect yet, is not valid.
I tracked that error down to this code in `moto`: https://github.com/spulec/moto/blob/2c98b7574b82f803b6f333eeaf21653856603a98/moto/acm/models.py#L309-L318
In …
> fix(acm): use .utcnow() instead of .now()

- tests/test_iam/test_iam.py
New regions (such as me-central-1) do not show up in `boto3.Session().get_available_regions`.
Moto does return it, so we must know about it, but we don't know it exists afterwards in the test. Just skipping the test in 3.6 is the easiest workaround - we'll EOL 3.6 soon-ish anyway
> Tech Debt: Skip some tests in Py3.6, as we do not have access to all regions

- tests/test_sqs/test_sqs.py
Note: I'm not sure whether this actually requires a change in our SQS logic. 
This change makes the tests pass with both BOTO_DISABLE_COMMONNAME enabled and disabled, as outlined in the related ticket (https://github.com/boto/botocore/issues/2705)
> SQS: Future-proof the changes in URLs

- .github/workflows/test_outdated_versions.yml
- moto/apigateway/models.py
This package recently moved some files around in a backwards-incompatible way as part of a refactor.
Ref: https://github.com/p1c2u/openapi-spec-validator/commit/70325f638001c615909978381bb48ad3d924dafd
Closes #5457
> Fix `openapi-spec-validator` import error

- moto/apigatewayv2/models.py
- moto/apigatewayv2/responses.py
- tests/terraformtests/terraform-tests.failures.txt
- tests/terraformtests/terraform-tests.success.txt
- tests/test_apigatewayv2/test_apigatewayv2_authorizers.py
See #5144 
FYI @calvernaz - I've tested all combinations against AWS, and this is the correct behaviour as far as I can see
> APIGatewayV2: create_authorizer() now validates the AuthorizerPayloadFormatVersion

- moto/ec2/exceptions.py
- moto/ec2/models/launch_templates.py
- moto/ec2/utils.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_launch_templates.py
* Implement CloudFormation CRUD model for EC2 LaunchTemplate resources.
* Fix a bug (discovered while writing unit tests) in `describe-launch-template-versions`: an error should be raised when the specified template does not exist:
> aws ec2 describe-launch-template-versions --launch-template-name timski
> An error occurred (InvalidLaunchTemplateName.NotFoundException) when calling the DescribeLaunchTemplateVersions operation: The specified launch template, with template name timski, does not exist.
> Add CloudFormation support to EC2 Launch Templates

- moto/rds/models.py
- tests/test_rds/test_rds.py
Explicit test coverage added for the following responses:
CreateDBInstanceResponse
DescribeDBInstancesResponse
Closes #5473
> Add `DbInstancePort` to RDS Responses

- moto/iam/access_control.py
- moto/moto_server/threaded_moto_server.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_bucket_policy.py
Ideally we extend this to all actions (Get/Put/Etc), and move validation to a single place - for now we'll just validate GetObject to verify it works as expected.
Fixes #2892
> S3:get_object() - Simple BucketPolicy validation

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB: transact_write_items() should return failing item

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_clusters.py
The current implementation of mocking the  RDS `CreateDBCluster` sets HttpEndpointEnabled to False by default without regard to an enable_http_endpoint parameter value. 
The PR introduces a `self.enable_http_endpoint` attribute within the `Cluster` class and simulates the AWS API's conditional constraints for enabling HTTP endpoints within serverless V1 clusters. Specifically, the conditions relate to the desired engine, engine version, and engine_mode configurations for the cluster to be created.
> add rds enable_http_endpoint attribute

- docs/docs/iam.rst
Updating documentation with the current `access_control.py` link.
> Amending documentation link

- moto/organizations/models.py
- tests/test_organizations/test_organizations_boto3.py
Within the service `Organizations` for the operation `create_organization`, the docs ([doc1](https://docs.aws.amazon.com/cli/latest/reference/organizations/create-organization.html) and [doc2](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.create_organization)) state the following: 
> By default (or if you set the FeatureSet parameter to ALL ), the new organization is created with all features enabled and service control policies automatically enabled in the root.  
As of now, not setting the FeatureSet, and therefore relying on the default value, results in a KeyError.  
This PR solves this issue by setting "ALL" as the default if none is present.
> setting default FeatureSet to ALL in create_organization

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/glue.rst
- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/helpers.py
- tests/test_glue/test_datacatalog.py
Currently [boto3 implements](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.get_tables) `glue.get_tables` with additional `Expression` parameter:
> Expression (string) -- A regular expression pattern. If present, only those tables whose names match the pattern are returned.
This is the implementation.
> Add expression param to existing get_tables glue api

- moto/iam/models.py
- moto/iam/utils.py
- moto/sts/models.py
- tests/test_iam/test_iam.py
- tests/test_sts/test_sts.py
Currently, when assuming roles, the User Id returned (and also returned by sts get-caller-identity) is not identical to the supposed format `role_id:session_name`, but regenerated freshly every time.
* if a matching role exists, it will take the role id of that role. If not, the behavior will be unchanged (to prevent breaking behavior)
* Both access-key-ids and role ids are now, in accordance with AWS behavior, based on the account id. Basically, the first 9 characters after the 4 char prefix are (more or less) dependent on the account id. This generation is based on the blog post https://awsteele.com/blog/2020/09/26/aws-access-key-format.html, and is verified using `aws sts get-access-key-info --access-key-id ...`. The code is basically shifting the account id by an offset, and base32 …
> Make assumed role user ids dependent on role

- moto/dynamodb/exceptions.py
- moto/dynamodb/parsing/ast_nodes.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB: Validate duplicate expression paths

- moto/ec2/models/route_tables.py
- moto/ec2/responses/route_tables.py
- tests/test_ec2/test_route_tables.py
Fixes #5508 - replacing the main association raising an exception.
Fixes #5507 - showing all route tables as having the main association.
Fixes #5506 - the response for replace missing bits.
Existing unit tests fixed and a new one (testing replacing the main association) added.
> Fix 3 issues with route table associations

- moto/ec2/models/availability_zones_and_regions.py
- moto/ec2/models/instances.py
- moto/ec2/resources/instance_type_offerings/availability-zone/us-west-1.json
- scripts/ec2_get_instance_type_offerings.py
- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_autoscaling_cloudformation.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_regions.py
- tests/test_ec2/test_subnets.py
- tests/test_ec2/test_vpc_endpoint_services_integration.py
- tests/test_elb/test_elb_cloudformation.py
- tests/test_elbv2/test_elbv2.py
Fixes #5494 
Reverts #5513 
The availability zones that we expose are `us-west-1a` and `us-west-1b`. It is more consistent to ensure that the instance types we pull down from AWS also use `a` and `b`.
(As opposed to changing the zones that we expose to `b` and `c`, and introducing a potentially breaking change for everyone, which is what I originally did in #5513).
> EC2 availability zones in us-west-1: use A and B

- .github/workflows/test_terraform.yml
This PR is a workaround for the currently failing terraform tests.
See https://github.com/localstack/localstack/pull/6962 for an explanation.
> pin terraform version to 1.2.9 in terraform tests

- Makefile
The Makefile is using grep -oP. However, the -P flag to grep (for "use Perl regex syntax") is GNU-specific and does not exist in BSD grep (e.g., on MacOS).
We can use sed to accomplish the same thing in a way that will work on any POSIX-compliant system.
> More portable grep invocation in Makefile

- moto/s3/responses.py
- setup.cfg
In commit c4626888460, `r"x-amz-checksum-\w+:(\w+={1,2})"` was changed to  `b"x-amz-checksum-\w+:(\w+={1,2})"` (same content, different prefix). In addition to changing the type from to str to bytes (which was the intention), this lost the 'r' prefix which means that `\w` is now treated as an escape sequence.
Since it isn't actually a valid escape sequence, Python falls back to assuming it's not an escape sequence at all and the backslash is literal. This is correct and gets the same result as the "raw" version would, but generates `DeprecationWarning: invalid escape sequence \w`
This PR re-adds the `r` prefix as well as enabling the pylint check that would have caught this.
> Fix invalid escape sequence, enable pylint check

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/comprehend.rst
- docs/docs/services/ec2.rst
- moto/__init__.py
- moto/backend_index.py
- moto/comprehend/__init__.py
- moto/comprehend/exceptions.py
- moto/comprehend/models.py
- moto/comprehend/responses.py
- moto/comprehend/urls.py
- moto/ec2/models/vpcs.py
- moto/ec2/responses/vpcs.py
- tests/terraformtests/bin/run_go_test
- tests/terraformtests/etc/0007-Comprehend-Reduce-wait-times.patch
- tests/terraformtests/terraform-tests.success.txt
- tests/test_comprehend/test_comprehend.py
- tests/test_ec2/test_vpcs.py
Initial attempt to add the Comprehend-service to Moto. Only a subset of feature is implemented for now.
Closes #3895 
Implemented methods:
- create_entity_recognizer()
- delete_entity_recognizer()
- describe_entity_recognizer()
- list_entity_recognizers()
- stop_training_entity_recognizer()
Also adds EC2:modify_vpc_endpoint(), as it was necessary for the TF tests to pass.
> Service: Comprehend (Entity Recognizer)

- moto/glue/models.py
- tests/test_glue/test_datacatalog.py
Fix for issue discussed in PR conversation on https://github.com/spulec/moto/pull/5495
Glue `get_tables` treats expressions with `*` as a glob-like wildcard.
FYI @robert-schmidtke
> Fix glue expression

- moto/batch/models.py
When you use describe_jobs method, it should return logStreamKey as part of response in container object when job is running (currently logStreamKey is returned only when job is stopped).
> Make available logStreamName key when a job is running

- IMPLEMENTATION_COVERAGE.md
- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_clusters.py
This introduces a Moto implementation for the AWS RDS ModifyDbCluster endpoint. To enforce the attribute constraints specified within `Cluster.__init__()` during the modification of the `Cluster` instance, the appropriate attributes are now wrapped within a Python `@property` decorators that implement the constraint within their respective property setters.
With the introduction of property values, the `Cluster` instance's `__dict__` values will not contain the same attributes that other backend methods may have relied on (e.g. `restore_db_cluster_from_snapshot()`). To combat this, there's a `get_cfg()` method that will return a modified version of `__dict__` but with hidden attribute names having their prefix `_` removed.
> Add RDS modify_db_cluster()

- .github/workflows/release.yml
I noticed that the docker image of motoserver is not a multi platform build.  Therefore it creates some troubles when I try to run it with docker swarm locally on an M1 Macbook pro for my tests. I just added the needed steps to create a multi platform docker image, according to this [guide](https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md).
> Create multiplatform docker image that also runs on m1 macbooks

- moto/s3/models.py
- moto/s3/utils.py
- tests/test_s3/test_s3_file_handles.py
- tests/test_s3/test_s3_multipart.py
Followup to (and improved implementation of) #5545. This PR closes any FileHandle (FH) that is created when a key is destroyed, 
This PR enhances the earlier solution to close FH's the moment keys/multiparts are deleted. Additionally, all are closed as part of the destructor, just in case there are any FH's created that we forgot to close.
Also removes an method (`complete_multipart`) that is nowhere used or invoked, to remove any confusion.
@hannes-ucsc FYI: this is IMHO the best solution to ensure we're always closing file handles, regardless of where they come from/when they are no longer reachable. Is this acceptable for you?
> S3: Close FileHandles on GC

- moto/s3/models.py
- tests/test_s3/test_s3.py
Fixes #5561 
From the docs:
Delimiter (string) -- A delimiter is a character that you specify to group keys. All keys that contain the same string **between the prefix and the first occurrence of the delimiter** are grouped under a single result element in CommonPrefixes. These groups are counted as one result against the max-keys limitation. These keys are not returned elsewhere in the response.
Emphasis mine. The current implementation was much too broad, and included keys that contained the delimiter regardless of the prefix specified.
> S3:list_object_versions(): Fix delimiter to take prefix into account

- moto/athena/exceptions.py
- moto/cloudformation/exceptions.py
- moto/cognitoidentity/exceptions.py
- moto/cognitoidp/exceptions.py
- moto/kinesis/exceptions.py
- moto/managedblockchain/exceptions.py
- moto/meteringmarketplace/exceptions.py
- moto/opsworks/exceptions.py
- moto/rds/exceptions.py
- moto/redshift/exceptions.py
- moto/resourcegroups/exceptions.py
Simplifies and streamlines some exceptions by extending our custom Exception-object, instead of werkzeug's HttpException.
The format that AWS uses for it's exceptions, `"{'__type': .., 'message': ..}"` should now only be present in our overarching JsonRestError.
> Techdebt - Simplify some exceptions

- docs/docs/services/patching_other_services.rst
- docs/index.rst
As discussed here https://github.com/spulec/moto/issues/5572 right now how to patch an AWS service not covered by `moto` is not present in the documentation.
I've included a single page with a code snippet and the guidance of @bblommers to show an example of the Access Analyzer service.
Thanks!
> docs: Patching services not supported

- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_training.py
Fixes #5580 
Adds a missing `arn_formatter`-method that we forgot to implement.
Also removes two methods that were never called, including the `delete_training_job`-feature that does not actually exist in Boto3.
> Sagemaker:describe_training_job() - describe unknown job

- moto/s3/models.py
- tests/test_s3/test_s3_file_handles.py
Closes #5584 
Instead of having to list all buckets, and all keys inside buckets, we can  just use the builtin `instances` which will contain a list of all instances ever created.
> S3: Close filehandle of versioned keys

- moto/s3/models.py
- tests/test_s3/test_s3_file_handles.py
Fixes #5588 
Multithreaded bug where:
- User: calls list_object_versions
- Moto creates a list of all keys
- User: deletes a key
- Moto iterates over the previously created list, that contains a now-deleted key, and creates a copy of it
Catching any errors that occur while copying a key is the most straight-forward way to ensure this is not a problem.
The copied key is send back to the user, but for deleted keys it will never send the content, only info on whether the key exists - so the fact that the content is missing is irrelevant.
> S3: Ensure we can copy deleted keys

- moto/awslambda/models.py
- moto/awslambda/responses.py
When listing functions by versions, we need to return a custom ARN for the latest function. The easiest way is to create a copy of the function, but (in multithreaded applications) this operation occasionally fails with `TypeError: Cannot serialize socket object`. 
This PR fixes this by ensuring that the Docket-client (and  underlying socket) are not included in any copy-operations. This is not a problem, because Moto will always recreate the client if it doesn't exist anymore.
This should fix the current build failures.
Note: This may have been introduced with #5586? Not sure how, but I've only seen the build failures appear after this PR was merged.
> AWSLambda - Do not pickle reproducible Docker-client

- moto/s3/responses.py
- moto/s3bucket_path/utils.py
Fixes #5610 
When detecting whether the current request is a `DeleteObjectsRequest`, we want to know whether there is a querystring-parameter called delete.
There's really no need to verify the entire path, and/or verify the exact format of the url/path.
> S3: Simplify detection of delete-flag

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_tags.py
> CloudWatch: Ensure we can tag new Alarms that are currently tag-free

- moto/cloudtrail/models.py
- tests/test_cloudtrail/test_cloudtrail.py
From https://github.com/spulec/moto/issues/5604 we have realised that there is a missing condition when listing the trails from `describe_trail`.
If we don't include the condition:
```
if trail.is_multi_region or trail.region_name == backend.region_name:
```
Single multiregion trails will be shown in another regions when launching `describe_trail`
To test its effect please refer to the script included into the issue description
> fix(describe_trails): trail not multiregion case

- moto/ec2/responses/vpcs.py
- tests/test_ec2/test_vpcs.py
Adds support for `enableNetworkAddressUsageMetrics` to be used in `modify_vpc_attribute()` and `describe_attribute()` calls to the Ec2 service.
> Add EnableNetworkAddressUsageMetrics to VPC attribute

- moto/cloudwatch/models.py
Fixes https://github.com/spulec/moto/issues/5625
Data to be considered for aggregations should not include the `end_time`
More info on the ticket.
> End times for aggregations should be exclusive

- .github/workflows/build.yml
- Makefile
- requirements-tests.txt
- tests/test_xray/test_xray_client.py
Unpins `coverage`-dependency. This was pinned int he first place due to a incompatibility with the XRay SDK - see https://github.com/aws/aws-xray-sdk-python/issues/196.
This means that the XRay tests have to be run separately, without the coverage enabled.
> TechDebt - Unpin coverage-dependency to speed up Py3.11

- moto/rds/models.py
- tests/test_rds/test_rds_clusters.py
Note: on a real AWS backend, the value of EarliestRestorableTime changes based on the cluster's BackupRetentionPeriod, PreferredBackupWindow, and oldest snapshot. This behavior is not currently implemented in moto.
Closes #5379
> Add `EarliestRestorableTime` to rds:DescribeDBClusters response

- moto/organizations/models.py
- moto/organizations/responses.py
- tests/test_organizations/test_organizations_boto3.py
This PR adds the endpoint [delete_organizational_unit](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DeleteOrganizationalUnit.html) within Organizations.
Happy to adjust it, it's my first time adding functionality to moto..
> Add organizations delete_organizational_unit

- tests/test_awslambda/test_lambda.py
- tests/test_awslambda/utilities.py
When the Server Mode tests are run in parallel, it's possible for multiple tests to call `get_role_name` at approximately the same time.  When this happens at the beginning of a test run--before `my-role` has been created--the call to `iam.get_role` can fail for more than one caller, all of whom then attempt to execute `iam.create_role`.  The first call to `iam.create_role` will succeed, but all others will result in an `EntityAlreadyExistsException`, which was not handled by the original code and would result in the test failing.
This updated code wraps the entire process in an infinite loop and adds an exception clause for the `iam.create_role` call, which simply passes, allowing the loop to attempt the `iam.get_role` call again.
An explicit test case has been added, which was failing …
> Fix Race Condition in Parallel AWS Lambda Server Mode Tests

- moto/apigateway/integration_parsers/aws_parser.py
- moto/apigateway/integration_parsers/http_parser.py
- moto/apigateway/integration_parsers/unknown_parser.py
- moto/apigateway/models.py
- moto/apigateway/responses.py
- moto/wafv2/models.py
We now store models, such as ApiKey and MethodIntegration, as objects, instead of dictionaries.
Pro:
- This simplifies the object hierarchy, as our models only subclass BaseModel, instead of both BaseModel and dict
- It separates state (now stored in properties) and view (now exposed as a `to_json()`-method)
This PR also moves the logic for the `include_values`-parameter in `get_api_key` to the `responses.py`, as it is technically related to the view-logic - the state (`models.py`) should not care about this param.
> TechDebt - Fix MyPy issues that popped up in 0.990 release

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
According to [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html) JWT token must contain "username" and not `email`. In edge case, `username` can contain `sub` as value, but implementation of this package does not support that situation, so simply `email` was replaced with `username`.
> Replace email with username in cogntio JWT tokens

- moto/swf/responses.py
- tests/test_swf/responses/test_workflow_executions.py
> If a runId isn't specified, then the WorkflowExecutionSignaled event is recorded in the history of the current open workflow with the matching workflowId in the domain.
See https://docs.aws.amazon.com/amazonswf/latest/apireference/API_SignalWorkflowExecution.html
> [SWF] runId should be optional

- moto/swf/models/workflow_execution.py
- tests/test_swf/models/test_workflow_execution.py
> If something occurs that generates a decision task while a decider is processing another decision task, Amazon SWF queues the new task until the current task completes. After the current task completes, Amazon SWF makes the new decision task available. Also, decision tasks are batched in the sense that, if multiple activities complete while a decider is processing a decision task, Amazon SWF will create only a single new decision task to account for the multiple task completions. However, each task completion will receive an individual event in the workflow execution history.
See https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dg-dev-deciders.html#swf-dg-deciders-launch
> [SWF] Schedule a single task if another is started

- moto/s3/responses.py
- tests/test_s3/test_s3.py
I think the most common use case for IfModifiedSince is:
1. Call get_object
2. Remember the LastModified date
3. Call get_object again with IfModifiedSince=LastModified to only get the object if it has changed
The implementation in moto currently doesn't work for two reasons:
1. The check for returning 'NotModified should include the case when LastModified == IfModifiedSince.
2. The returned timestamps are truncated to seconds, but the internally stored ones include microseconds, so the directly comparing them doesn't work. I initially wanted to truncate the internal datetimes, but that changes a very large number of tests, because some hashes change.
> Fix IfModifiedSince handling in S3 get_object/head_object

- tests/test_rds/test_server.py
Test was incorrectly using JSON encoding in the body of the request, but RDS uses the Query protocol, which requires querystring-encoded parameters.
Note: This test has been passing because moto is extremely liberal when parsing incoming data, but it was fundamentally incorrect behavior and could break in the future if `moto` ever adheres more strictly to the AWS wire protocols when handling incoming requests.
> Fix: RDS server test should use Query protocol

- moto/timestreamwrite/models.py
Timestream is available in these regions.
-  Asia Pacific (Sydney) | ap-southeast-2
-  Asia Pacific (Tokyo) | ap-northeast-1
> Timestreamwrite: Add regions

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
As per Boto3 documentation the `SecretString` `create_secret` API parameter is not required. 
So if you try to enable rotation in a previously created secret without a `SecretString`, the moto `rotate_secret` fails with a `KeyError` due to the inexistence of `old_secret_version["secret_string"]`
```python
@mock_secretsmanager
def test_create_and_rotate_secret(self):
secretsmanager_client = client("secretsmanager", region_name="eu-west-1")
resp = secretsmanager_client.create_secret(
Name="test-secret"
)
secret_arn = resp["ARN"]
secret_name = resp["Name"]
secretsmanager_client.rotate_secret( # <-- this call fails with a KeyError
SecretId=secret_arn,
) 
```
> fix(add-secret): SecretString can be None

- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/test_dynamodb.py
`ReturnValuesOnConditionCheckFailure` supports `ALL_OLD` which returns the existing item.
The fix for `https://github.com/spulec/moto/pull/5482` goes some of the way!
Please excuse my code, I haven't edited this repository before - feel free to change my commit, or suggest edits.
AWS documentation is here:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ConditionCheck.html#DDB-Type-ConditionCheck-ReturnValuesOnConditionCheckFailure
> WIP fix: Add support for `ReturnValuesOnConditionCheckFailure=ALL_OLD`

- moto/ram/models.py
- moto/rds/exceptions.py
- moto/rds/models.py
- moto/rds/responses.py
- moto/rds/utils.py
- moto/redshift/exceptions.py
- moto/redshift/models.py
- moto/redshift/responses.py
- moto/resourcegroups/models.py
- moto/resourcegroupstaggingapi/models.py
See #5579 
This PR also simplifies the parameter-parsing for RDS and Redshift, by utilizing existing `_get_.._param` methods that are exposed in BaseResponse
> Techdebt: Replace string-format with f-strings (for r* dirs)

- moto/cloudfront/responses.py
- tests/test_cloudfront/test_cloudfront_invalidation.py
The mock_cloudfront behaved differently to the real boto3 implementation. This makes it the same.
Fixes #5698
> Don't add empty Items to list_invalidations

- moto/awslambda/models.py
- moto/ecr/models.py
- moto/settings.py
- tests/test_awslambda/test_lambda.py
- tests/test_ecr/test_ecr_boto3.py
- tests/test_ecr/test_ecr_helpers.py
The core of this PR is to allow the `create_function` method of lambda to reference the mocked ECR backend to find images. Most notably it leads to "image not found" behavior when trying to deploy with an `imageUri` which does not exist within the mocked ECR backend. It also leads to the correct retrieval of attributes such as `CodeSha256` for the `list_functions` pathways.
While using moto to test configuration flow of lambda deployments via ECR images I noticed two things:
1. Image digests are being created non-deterministically.
2. The lambda deployment is mocking out the CodeSha256 response parameter arbitrarily by hashing the imageUri.
This is all fine and good while interacting with each service independently, but I wanted to be able to populate the ECR repo with images via …
> Let `create_function` reference ECR via ImageUri

- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_stack_parsing.py
I ran into an issue testing a CloudFormation template that used Number Paramters with the Sub function where the integer value is passed directly to `str.replace()` while performing the substitution, resulting a TypeError. 
This PR fixes that bug by converting all values to strings before replacing.
Please let me know if there's anything you would like me to change or do.
> CloudFormation: Fixed TypeError using Number Parameters with Fn::Sub

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Switch between "aud" and "client_id" name of "client_id" key in JWT payload, since AWS Cognito uses "aud" claim in ID token and "client_id" claim in access token.
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html#amazon-cognito-user-pools-using-tokens-step-3
> Cognito payload - Switch key name of "client_id"

- moto/s3/responses.py
- Ignores `"` if present in the header IfNoneMatch
This PR will fix [localstack/issues/5345](https://github.com/localstack/localstack/issues/5345)
> fix: support for etag with quotes in IfNoneMatch header

- moto/batch/models.py
- tests/test_batch/test_batch_jobs.py
Fix  #5704: Moto isn't checking validity of the Batch job names
Add a regex to valid the job name when submitting a job to raise a ClientException
[] Feature is added
[x] The linter is happy
[x] Tests are added
[x] All tests pass, existing and new
> Fix  #5704: Moto isn't checking validity of the Batch job names

- moto/ec2/models/launch_templates.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_launch_templates.py
This PR:
1. Fixes an issue with EC2 launch templates API which prevented template names from being reused after they were deleted.
1. Raise the correct exception if template name or ID is not specified in the request
Steps to reproduce the (1) bug:
```
$ awslocal ec2 create-launch-template \
--launch-template-name sample \
--launch-template-data '{}'
{
"LaunchTemplate": {
"LaunchTemplateId": "lt-b5a04f8e468f70f4e",
"LaunchTemplateName": "sample",
"CreateTime": "2022-12-01T10:08:43+00:00",
"CreatedBy": "arn:aws:iam::000000000000:root",
"DefaultVersionNumber": 1,
"LatestVersionNumber": 1,
"Tags": []
}
}
$ awslocal ec2 delete-launch-template --launch-template-name sample
{
"LaunchTemplate": {
"LaunchTemplateId": "lt-b5a04f8e468f70f4e",
"LaunchTemplateName": "sample",
"DefaultVersionNumber": …
```
> EC2: fix launch template names not being reusable after delete

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
This PR adds the Label parameter for the get_metric_data request and allows modifying the label returned to the response.
> Add custom label param to cloudwatch get_metric_data

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudformation.rst
- moto/cloudformation/exceptions.py
- moto/cloudformation/models.py
- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_multi_accounts.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Fixes #3425
create_stack_instances() now returns the actual OperationId
create_stack_set() now validates the provided name
create_stack_set() now supports the DeploymentTargets-parameter
create_stack_set() now actually creates the provided resources
delete_stack_set() now validates that no instances are present before deleting the set
> CloudFormation: Improve behaviour of StackInstances

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudformation.rst
- moto/cloudformation/exceptions.py
- moto/cloudformation/models.py
- moto/cloudformation/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_cloudformation/test_cloudformation_stack_policies.py
describe_stack_set_operations(): Fixed the format of CreationTimestamp and EndTimestamp
create_stack(): Now propagates parameters StackPolicyBody and TimeoutInMinutes
create_stack_set(): Now propagates parameters AdministrationRoleARN and ExecutionRoleName
describe_stack_set(): Now returns the attributes Description, PermissionModel
Various methods have been moved to `models.py` to ensure they are picked up by the ImplementationCoverage-script
> Cloudformation: Various improvements

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
The [original commit to remove the `sleep` call][1] only considered newly-arriving messages, but didn't take into account that existing messages could become visible in a much shorter time duration than the wait timeout.  This commit addresses this by checking for newly-visible messages at the visibility timeout granularity (seconds), which is still a major improvement over the original 10 millisecond polling.
Fixes #5710 
[1]: <https://github.com/spulec/moto/commit/d560ff002d6a188ceba295a012ef47415896c753> "Remove Sleep Call"
> Fix: SQS fails to get newly-visible messages when long polling

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds.py
Currently moto/mock_rds doesn't support promote_read_replica(). This PR is to address that.
```shell
make lint
Running flake8...
flake8 moto tests
Running black...
(Make sure you have black-22.3.0 installed, as other versions will produce different results)
black --check moto/ tests/
All done! ✨ 🍰 ✨
1479 files would be left unchanged.
Running pylint...
pylint -j 0 moto tests
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
Running MyPy...
mypy --install-types --non-interactive
Success: no issues found in 171 source files
```
> Add RDS promote_read_replica

- moto/s3/models.py
After a completed multipart upload, the final FakeKey object contains a reference to the FakeMultipart object, which in turn contains references to the FakeKey objects used to represent each uploaded part. The FakeMultipart object, and its FakeKey objects, will have been disposed when the uploaded completed.
In list_object_versions, meanwhile, all FakeKey objects are deep copied, which results in copying and reading the values of the disposed FakeKey objects referenced by FakeMultipart objects.
Ultimately, this causes an exception in FakeKey.value(), since it's trying to read the value from a file that was closed when it was disposed. The exception is raised with a lock acquired, which results in a deadlock the next time the value is read.
> S3: Fix deadlock in list_object_versions after multipart upload

- moto/route53/exceptions.py
- moto/route53/models.py
- tests/terraformtests/terraform-tests.success.txt
Changes introduced in #5725 were not tested properly because of wrong Terraform test-case names.
This PR corrects the test case names. 
Source: https://github.com/hashicorp/terraform-provider-aws/blob/163210e073650650adba645b636128fbc19244f4/internal/service/route53/record_test.go#L1322
This needs to be accompanied with the fix. @bblommers would you be able to take this over?
> Route53: Record overwrites

- moto/core/responses.py
- moto/ecs/models.py
- moto/elb/models.py
- moto/emr/models.py
- moto/emr/responses.py
- moto/s3/models.py
- setup.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
- tests/test_ec2/test_spot_instances.py
- tests/test_emr/test_emr_boto3.py
- tests/test_events/test_events.py
- tests/test_glue/test_datacatalog.py
- tests/test_secretsmanager/test_secretsmanager.py
This removes the dependency on pytz, which was used to provide the UTC offset information for timezone aware datetime objects. While that was helpful for Python versions up to 3.1, UTC offset information is included in the standard library since Python 3.2. As moto doesn't support Python versions <3.6 anymore, using pytz isn't necessary anymore either.
> Remove dependency on pytz

- moto/s3/responses.py
- tests/test_s3/test_s3.py
The `x-amz-sdk-checksum-algorithm` header was being returned with an empty `''` value.
This PR includes a fix so that it is only returned if also set in the request.
Regression of #5735
> S3: Return checksum header only if set

- moto/sqs/responses.py
Potential fix for #5769 
`{{ value.string_value|e }}` results in HTML-encoded output: `StringValue>&lt;att1&gt;</StringValue>`, which is equivalent to what AWS sends.
Incidentally, this changes the computation of `MD5OfMessageAttributes`, which computes the wrong value when the `StringValue` has the additional `CDATA`-stuff. 
I presume this is what trips up the C#-SDK, as reported in the linked issue - the MD5 computation.
(The other changes - adding `<?xml..>` and the RequestID - are just for sake of completeness. I don't imagine C# cares much, but you never know.)
> SQS: Align receive_message() response with AWS

- moto/batch/models.py
- moto/route53/models.py
- tests/test_route53/test_route53.py
- tests/test_route53/test_route53_cloudformation.py
According to AWS Route 53 docs, an SOA record will be automatically added to any hosted zone created with create_hosted_zone.
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/SOA-NSrecords.html
See issue #5762
> Create SOA in create_hosted_zone

- tests/test_cognitoidentity/test_cognitoidentity.py
- tests/test_cognitoidp/test_cognitoidp.py
- tests/test_core/test_mock_regions.py
- tests/test_core/test_settings.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_eks/test_eks.py
From https://pypi.org/project/mock/,
> mock is now part of the Python standard library, available as
> unittest.mock in Python 3.3 onwards.
>
> This package contains a rolling backport of the standard library mock
> code compatible with Python 3.6 and up.
As moto already requires Python >= 3.6 [1], usage of the backport library is not necessary and can be replaced with the one from the standard library.
[1] https://github.com/spulec/moto/blob/4.0.11/setup.py#L141
---
This is part of efforts on dropping python-mock package in Arch Linux: https://archlinux.org/todo/drop-python-mock-checkdepends/
> Techdebt: replace mock with unittest.mock

- moto/kinesis/urls.py
- tests/test_kinesis/test_kinesis_stream_consumers.py
Somewhere around boto3-1.26.31 botocore-1.29.31, AWS started using a new endpoint:
{ACCOUNT_ID}.control-kinesis.us-east-1.amazonaws.com
Boto3 also added some ARN validation, so the provided parameter now has to look like an ARN before it makes a request to AWS/Moto.
These changes should fix the build.
> Kinesis: Support new endpoint for botocore 1.29.31

- moto/awslambda/models.py
- moto/ecr/models.py
- tests/test_awslambda/test_lambda.py
- tests/test_ecr/test_ecr_boto3.py
- tests/test_ecr/test_ecr_helpers.py
- `imageManifestMediaType` now present in `describe_image()` response model.
- Deployment of lambdas using `{imageUri}@{digest}` now supported.
- Multi-arch manifest lists now supported.
- `imageByteSize` now attempts to present manifest information, if not present, defaults to previous static value. It also returns `None` in the case it's a manifest list, as manifest lists do not have this in their response model.
Largely this PR is to support that which is captured in this screenshot:
The above shows 3 image manifests, and one manifest list. The `0.0.1` image manifest stands on it's own. The `0.0.2` image manifest list represents the metadata which describes the untagged image manifests as being either `arm64` or `amd64`. `docker pull {uri}:0.0.2` traverses this to pull the correct …
> ECR Manifest List Support

- moto/batch/models.py
Trying to cancel a job with an empty `job_id` results in an error message complaining about `reason` (and vice versa).
> Fix some Batch error message typos

- moto/kms/models.py
- moto/kms/policy_validator.py
- moto/kms/responses.py
- tests/test_kms/test_kms_policy_enforcement.py
Fixes #4600
AWS KMS Key Policies allow you to block access to various operations: i.e., it is possible to say 'User X is not allowed Action Y for key Z'.
Documentation:
- Overview: https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-overview.html
- Flow chart: https://docs.aws.amazon.com/kms/latest/developerguide/policy-evaluation.html
Note that the flow chart linked above only has one 'easy' decision: if there is an explicit and applicable Deny-statement in the policy, AWS will deny access for that operation.
This PR adds rudimentary support for this policy enforcement, raising an exception only if a Deny-statement is found where:
- The principal is set to "*"
- The resource is set to "*"
- The Action matches `describe_key`
Other principals/resources/actions, not to mention …
> KMS: Basic key policy enforcement

- docs/docs/services/sagemaker.rst
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_pipeline.py
Adding sagemaker mock call `delete_pipeline`
`boto3.client("sagemaker").delete_pipeline`
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.delete_pipeline
> Add sagemaker mock call: delete_pipeline

- moto/route53/exceptions.py
- moto/route53/models.py
- tests/test_route53/test_route53.py
From [AWS API Reference](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html) about the UPSERT action:
> `UPSERT`: If a resource set exists Route 53 updates it with the values in the request.
Thus, providing a resource record set that already exist to the UPSERT
action should succeed.
Additional changes in tests:
- Add check for error message in the existing unit test.
- Add unit test for creating a resource record with an UPSERT.
> fix(route53): Allow upsert for resource records that already exist.

- README.md
- Use black formatting
- Since Python 2.* is no longer supported, don't inherit from `object`
> chore(readme): Align code snippets formatting with project's rules.

- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
When a stack exists and an update is attempted with the same parameters and template body the AWS api responds with a specific message which is injected into the `ClientError` generated by boto.
To reduce complexity we make some of our processes ignorant of whether an update constitutes changes to a stack by checking if this exact message is returned as part of a `ClientError`. Reflecting this message in moto will allow us test the components that use this in their processes while preserving the the updates provided in https://github.com/spulec/moto/pull/4351.
> changing error message to match aws api (stack update attempt with no updates)

- moto/iam/responses.py
- tests/test_iam/test_iam.py
Currently the tags are missing for users, when running get-account-authorization-details.
It is present for roles, however.
Related localstack/localstack/issues/5230
* Add tags to response
* Test tags in response
It seems fine that an empty array is indeed returned without tags, as it is in parity with aws.
AWS response:
```
{
"Path": "/",
"UserName": "test-user",
"UserId": "AIDAXXXX",
"Arn": "arn:aws:iam::XXXXXXXXXXXX:user/test-user",
"CreateDate": "2022-12-22T16:30:32+00:00",
"GroupList": [],
"AttachedManagedPolicies": [],
"Tags": []
}
```
> Add tags for users in the get-account-authorization-details response

- docs/docs/getting_started.rst
The documentation sample code [currently in master](https://docs.getmoto.org/en/latest/docs/getting_started.html?highlight=caveats#patching-the-client-or-resource) runs into a "NameError: name `client` is not defined" exception if executed. 
This change updates the documentation to refer to the externally provided `client` as `outside_client` for example clarity + functional accuracy.
> docs: fix patching external client/resource docs

- moto/kms/responses.py
- moto/kms/utils.py
- tests/test_kms/test_kms_boto3.py
Small "fix" to add in TargetKeyIds to canonical aliased kms keys.
These keys are a curiosity to me. I can't seem to find a way to initialize them via boto3 in actual AWS land. If you setup, say, ssm and add a first key to it using the service kms key it auto-generates. \o/.
> Add TargetKeyId to default kms key alias response.

- .gitignore
- docs/docs/contributing/architecture.rst
- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
Fixes #5740
Note that the [architecture page](http://docs.getmoto.org/en/latest/docs/contributing/architecture.html#contributing-architecture) and [development tips](http://docs.getmoto.org/en/latest/docs/contributing/development_tips/index.html#contributing-tips) both say to put parameter validation in `responses.py`. But the validation of the `DataType` parameter was already done in `models.py`. So that's where I added this new validation.
I also fixed an unrelated typo in documentation.
And I added `.hypothesis` to the `.gitignore`.
> 5740 ssm param type validation

- moto/rds/models.py
- moto/rds/responses.py
- moto/rds/utils.py
- tests/test_rds/test_rds.py
Handle `PreferredMaintenanceWindow` parameters for creation and modification of RDS DB instances. Generate the relevant AWS exceptions as part of handling the same.
> #5838: Support PreferredMaintenanceWindow for RDS DBInstance

- moto/batch/models.py
- moto/batch/responses.py
- moto/batch/utils.py
- moto/logs/models.py
- tests/test_batch/test_batch_jobs.py
This adds multinode support to `mock_batch`. This will allow users to run jobs that have multiple different jobs configured.
Notes:
* describe_jobs doesn't return most container field
* describe_jobs doesn't respect the `#idx` suffix to job IDs
* all containers log to the same stream
* container exit logic is very simple and waits for them to finish in order so if replica 1 fails but 0 doesn't it may hang until timeout
* there's minimal/no validation on the job spec right now for nodeProperties
Test plan:
pyre
added multinode slow test
> batch: add multinode support

- moto/glue/models.py
- moto/glue/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_glue/test_schema_registry.py
Fixes #5816 
Implements Glue:
get_registry()
delete_registry()
list_registries()
get_schema()
update_schema()
Also moves Glue to a region-based implementation, as it should - it was erroneously implemented as a `global` service before.
> Glue: get/delete/list_registries, get/update_schema

- moto/dynamodb/parsing/key_condition_expression.py
- moto/ses/models.py
- moto/ses/template.py
- moto/utilities/tokenizer.py
- tests/test_ses/test_ses_boto3.py
- tests/test_ses/test_templating.py
Fixes #5594 
Improves generation of SES templates to also support for-each loops.
AWS supports a subset of the Handlebars templates. There is a python-fork that could be used to parse SES templates here: https://github.com/wbond/pybars3
However, it is unmaintained and slow (with an import time of about 400ms). That's why I chose instead to write a custom parser, reusing an existing tokenizer used in DynamoDB.
> SES: Improve template parsing

- .github/workflows/build.yml
Fixes #5858 
Related to #5553 - this applies the same solution to our `latest`-releases
> Enable Apple M1 support for Docker-builds with latest-tag

- moto/core/responses.py
- moto/ec2/models/fleets.py
- moto/ec2/responses/fleets.py
**moto/ec2/models/fleets.py**
- Exception handling and default value in case of `NoneType` for `spot_target_capacity` and `on_demand_target_capacity`
**moto/ec2/responses/fleets.py**
- Only add parameter in response if exsists
> ec2: default values in ec2 fleet

- moto/dynamodb/models/table.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB: transact_write_items() errors on empty GSI keys

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ecs.rst
- moto/autoscaling/models.py
- moto/autoscaling/responses.py
- moto/ecs/models.py
- moto/ecs/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_autoscaling/test_autoscaling.py
- tests/test_batch/test_batch_compute_envs.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_ecs/test_ecs_capacity_provider.py
- tests/test_ecs/test_ecs_cloudformation.py
- tests/test_ecs/test_ecs_efs.py
- tests/test_ecs/test_ecs_task_def_tags.py
- tests/test_ecs/test_ecs_tasksets.py
Support for:
ECS: put_cluster_capacity_providers()
ECS: update_capacity_provider()
ECS: update_cluster()
* ECS: create_cluster() now supports the parameters configuration, capacityProviders, defaultCapacityProviderStrategy
* ECS: delete_cluster() now marks the cluster as INACTIVE, rather than removing it outright, inline with how AWS behaves
* ECS: register_task_definition() now supports the parameters proxyConfiguration, inferenceAccelerators, runtimePlatform, ipcMode, pidMode, ephemeralStorage
* ECS now has improved tagging-support
* ECS: run_task() no longer crashes when providing launchType=FARGATE
Closes #2101
> ECS: Various improvements

- moto/eks/models.py
- setup.cfg
- tests/test_eks/test_eks_ec2.py
> EKS: NodeGroups: Verify LaunchTemplateID when providing name, and vice versa

- moto/ec2/models/instances.py
- tests/test_ec2/test_instances.py
AWS ec2 API allows providing a NIC "template" when creating instances, which does not contain any IP. ec2 assign an IP address automatically for each instance.
With moto, almost everything was made to reproduce the same behaviour, except that the dict containing the params was directly updated with the assigned IP address, and was producing an error the second time when checking if the IP was available, because it was checking it against the previously assigned IP.
The solution is very simple: duplicating the parameter to avoid updating the original entry.
> EC2: Allow providing NIC template when creating several instances

- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_glue.py
Hello,
while working with moto I got `NotImplementedError: The batch_get_crawlers action has not been implemented`, so I decided to implement the missing method 😉 
If you have any suggestions how to improve my code - please let me know!
> [Glue] Implement batch_get_crawlers

- moto/server.py
Part of a cleanup to simplify the server-logic. The command `moto_server ec2` can be used if you only want to serve EC2 requests on this MotoServer, but I'm not aware of any benefits of this. Running just `moto_server` does the same thing.
This feature was removed from the documentation in https://github.com/getmoto/moto/pull/3728
If someone is using this construct, and is able to show a use-case that I'm not seeing, we can always undo this.
> MotoServer - deprecate server-argument

- moto/awslambda/models.py
- moto/settings.py
- tests/test_awslambda/test_lambda_invoke.py
Closes #5886 
When invoking an AWSLambda function, the requested image can be found in one of these repos:
- `mlupin/docker-lambda` (the repo with up-to-date AWSLambda images
- `lambci/lambda` (the repo with older/outdated AWSLambda images
This PR ensures that we cycle through all of them - when we find the repo that contains our image, we use that one.
For most users, this means the `MOTO_DOCKER_LAMBDA_IMAGE`-variable is no longer required. But we'll keep the functionality in case people want to configure a different repository instead.
> AWSLambda: Try to pull images from multiple repositories

- moto/iam/access_control.py
- tests/test_s3/test_s3_bucket_policy.py
This PR fixes `AttributeError` when using policies that have a list of resources:
<https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_statement.html>
```js
{
'Action': 's3:*',
'Effect': 'Deny',
'Resource': [
'arn:aws:s3:::sls-test-local-serverlessdeploymentbuck-3f0d17f0/*',
'arn:aws:s3:::sls-test-local-serverlessdeploymentbuck-3f0d17f0'
]
}
```
```
...
File "/home/viren/repo/moto-ext/moto/core/utils.py", line 106, in __call__
result = self.callback(request, request.url, dict(request.headers))
File "/home/viren/repo/moto-ext/moto/utilities/aws_headers.py", line 64, in _wrapper
response = f(*args, **kwargs)
File "/home/viren/repo/moto-ext/moto/s3/responses.py", line 1122, in key_response
response = self._key_response(request, full_url, self.headers)
File …
```
> IAM: Fix resource list matching

- moto/ecs/exceptions.py
- moto/ecs/models.py
This PR has two small fixes:
1. Report the same error message as AWS for `DescribeTaskDefinition`
```
$ aws ecs describe-task-definition --task-definition foobar
An error occurred (ClientException) when calling the DescribeTaskDefinition operation: Unable to describe task definition.
```
2. Fix `AttributeError` when stopping Fargate tasks
```
...
File "/home/viren/repo/moto-ext/moto/ecs/responses.py", line 254, in stop_task
task = self.ecs_backend.stop_task(cluster_str, task, reason)
File "/home/viren/repo/moto-ext/moto/ecs/models.py", line 1418, in stop_task
container_instance_arn.split("/")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```
> ECS: Fixes to DescribeTaskDefinition and StopTask

- Makefile
- tests/test_acm/test_acm.py
- tests/test_amp/test_amp_workspaces.py
No new functionality - this just adds support to run tests for these services in parallel.
See #5464
> Techdebt: Parallellize ACM/AMP tests

- moto/glue/models.py
- moto/glue/utils.py
- tests/test_glue/test_partition_filter.py
This PR supports nanosecond-resolution timestamp partition filters for Glue. It does so by, instead of using a Python `datetime` to compare timestamps, using POSIX timestamps augmented to nanosecond resolution.
The validity of the timestamp string is still checked, but the POSIX representation is used internally for comparisons.
> Glue: support nanosecond-precision timestamp partition filtering

- moto/transcribe/models.py
- moto/transcribe/responses.py
- tests/test_transcribe/test_transcribe_boto3.py
The [start_transcription_job method](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transcribe.html#TranscribeService.Client.start_transcription_job) has an IdentifyMultipleLanguages attribute, and returns LanguageCodes if more than one language is found in the recording.
> Transcribe: add IdentifyMultipleLanguages and return LanguageCodes

- moto/dynamodb/models/table.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/test_dynamodb_create_table.py
Fixes #5916 
We assumed that when creating a Table, the user would only ever send two attributes: Hash and Range. 
But it is possible to specify a non-key attribute, so we should be very explicit in determining whether something is a Hash-key, Range-key, or something else all-together.
> DynamoDB: Support declaration of non-key attributes

- moto/core/base_backend.py
- moto/core/model_instances.py
- moto/core/models.py
- moto/iam/models.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- tests/test_s3/test_s3_file_handles.py
Fixes #5913 
Moto used to reset the entire `model_data`, for every service, whenever a backend for a single service was reset. 
This leads to problems when you reset one service, but have another service still active. For example:
```
with mock_s3():
create_object()
with mock_dynamodb():
assert model_data != []
```
This PR changes the approach to `model_data` in two ways:
- It is now stored separately, to make it clear it is an overarching (non service-specific) concept
- It is now reset explicitly on two occasions:
1. When the last mock exits
2. When making an HTTP request to `moto_api/reset` (done by the MotoServer)
> Core: Rework model_data to only clear on exit

- .github/workflows/data-update_ec2-instance-offerings.yml
- .github/workflows/data-update_ssm-default-amis.yml
- .github/workflows/data-update_ssm-default-parameters.yml
The EC2 instance types scripts already can be executed successfully: resulting PR here: https://github.com/getmoto/moto/pull/5923
This PR also changes that PR to remove the custom GithubToken, to test whether it is possible to use the default token instead when an action is executed per a schedule.
> Admin: Add Data automation scripts

- moto/core/responses.py
- moto/ec2/responses/amis.py
- moto/ec2/responses/elastic_block_store.py
- moto/ec2/responses/elastic_ip_addresses.py
- moto/ec2/responses/elastic_network_interfaces.py
- moto/ec2/responses/flow_logs.py
- moto/ec2/responses/instances.py
- moto/ec2/responses/internet_gateways.py
- moto/ec2/responses/ip_addresses.py
- moto/ec2/responses/key_pairs.py
- moto/ec2/responses/launch_templates.py
- moto/ec2/responses/monitoring.py
- moto/ec2/responses/placement_groups.py
- moto/ec2/responses/reserved_instances.py
- moto/ec2/responses/security_groups.py
- moto/ec2/responses/settings.py
- moto/ec2/responses/spot_instances.py
- moto/ec2/responses/tags.py
- moto/ecr/responses.py
- tests/test_ec2/test_elastic_ip_addresses.py
- tests/test_ec2/test_elastic_network_interfaces.py
- tests/test_ec2/test_instances.py
- tests/test_ec2/test_launch_templates.py
- tests/test_ec2/test_security_groups.py
- tests/test_ec2/test_spot_instances.py
Almost all EC2-methods followed the format:
```
if self.is_not_dryrun():
act()
```
where `self.is_not_dryrun` would either throw an error, or return True. 
This has all been refactored to the following:
```
self.error_on_dryrun
act()
```
This is easier to read, and also will make it easier to add type annotations later on.
> EC2: Simplify DryRun-handling

- moto/s3/models.py
- moto/s3/utils.py
- tests/test_s3/test_s3_file_handles.py
Fixes #5937 
Filehandles weren't closed when deleting versioned FakeKeys. 
Moving the dispose-logic to the `_VersionedKeyStore` ensures that we only have to invoke this logic in one place, regardless of whether we're creating, deleting, dealing with a versioned/non-versioned bucket, etc.
> S3: Close more filehandles

- moto/batch/models.py
If "import docker" fails https://github.com/getmoto/moto/blob/aa332c4d/moto/batch/models.py#L610 `Job.run`  fails with an obscure error `UnboundLocalError` error as:
```
.../_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread MOTO-BATCH-e3d4d43a-b68e-4f64-b2e8-7c396c0f3ad2
File ".../lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File ".../moto/batch/models.py", line 854, in run
for container in containers:
UnboundLocalError: local variable 'containers' referenced before assignment
warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```
The PR changes the scope of 'containers' variable to prevent the issue.
> Fix "local variable 'containers' referenced before assignment".

- moto/rds/models.py
- tests/test_rds/test_rds.py
Creating or describing a RDS `OptionGroup` is missing the parameter `OptionGroupArn`, as [examples described in the docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/create-option-group.html#examples):
> 
```
{
"OptionGroup": {
"OptionGroupName": "myoptiongroup",
"OptionGroupDescription": "Oracle Database Manager Database Control",
"EngineName": "oracle-ee",
"MajorEngineVersion": "11.2",
"Options": [],
"AllowsVpcAndNonVpcInstanceMemberships": true,
"OptionGroupArn": "arn:aws:rds:us-west-2:123456789012:og:myoptiongroup"
}
}
```
The arn is required e.g. for specific terraform deployments, and was [reported as an issue in LocalStack](https://github.com/localstack/localstack/issues/7721).
> add arn for rds OptionGroup

- moto/kms/models.py
- tests/test_kms/test_kms_boto3.py
- tests/test_kms/test_kms_encrypt.py
Fixes #5957 
This also moves all encrypt/decrypt-tests to a separate file. New test methods:
`test_encrypt_using_alias_name`, `test_encrypt_using_alias_arn`, `test_encrypt_using_key_arn`
> KMS: encrypt() should allow an alias as argument

- moto/ec2/utils.py
- tests/test_ec2/test_instances.py
Fixes #5966 
When checking if tags match, we put a lot of effort into ensuring that we support regexes - but we should also support specific tags that look like a regex, but are actually an exact match
> EC2: describe_instances() should be able to filter by exact tag-values

- moto/acm/responses.py
- tests/test_acm/test_acm.py
The purpose of this PR is to approach the behaviour of the ACM `list_certificates` API call including new fields. I don't know if this is a new feature of the ACM API but it would be helpful. 
Also, there are more fields present in the `list_certificates` call that are not covered by moto.
Rationale: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm.html#ACM.Client.list_certificates
Include the following fields in the `list_certificates` call:
- Status
- Type
- NotBefore
- NotAfter
- CreatedAt
- KeyAlgorithm
- RenewalEligibility
- ImportedAt
- IssuedAt
I don't know if in this case this is the best approach. I didn't make test for that reason, if so I'll do it.
> fix(acm): Include more info to the list_certificates

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_server.py
Fixes #5993 
The `com.amazonaws.dynamodb.v20111205#`-prefix was a holdover from the old DynamoDB, in use with boto2. All error types from the current DynamoDB version seem to be prefixed with `com.amazonaws.dynamodb.v20120810#` instead.
This also changes the error message in the body - `describe_table()` returns a slightly different error message than other methods.
> DynamoDB: describe_table() - return correct error msg

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Adds support for the following resources:
AWS::RDS::DBCluster
AWS::RDS::DBClusterSnapshot
Closes #5994
> Add ResourceGroupsTaggingAPI Support for Aurora Clusters

- .github/workflows/build.yml
- .gitignore
- moto/core/exceptions.py
- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- other_langs/tests_java/pom.xml
- other_langs/tests_java/src/main/java/moto/tests/DependencyFactory.java
- other_langs/tests_java/src/main/java/moto/tests/DynamoLogic.java
- other_langs/tests_java/src/main/java/moto/tests/Handler.java
- other_langs/tests_java/src/test/java/moto/tests/DynamoTest.java
- other_langs/tests_java/src/test/java/moto/tests/S3Test.java
- tests/test_dynamodb/test_server.py
Some very simple tests using the Java SDK to verify Moto behaves correctly.
Initial tests include some basic S3 and DynamoDB operations.
Why this is necessary:
As a user, when I create a table that already exists, DynamoDB throws a ResourceInUseException.
The Java SDK expects a specific header: `"Content-Type": "application/x-amz-json-1.0"`. Without this header, the Java-call throws a generic DynamoDbException, instead of the dedicated exception that the user expects.
This PR also adds the required header to DynamoDB to ensure the Java-test succeeds.
This should fix #5993
> Admin: Add Java tests

- .github/workflows/build.yml
- .github/workflows/dockertests.yml
- .github/workflows/tests_decoratormode.yml
- .github/workflows/tests_sdk_java.yml
- .github/workflows/tests_servermode.yml
Extract CI steps into separate files to make the overall configuration file more readable.
Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call
Other possible improvements:
- Reuse all the steps, so that the main workflow file only points to sub-workflows, without containing any logic
- Look into reusing individual steps (such as creation of the MotoServer Docker image, which is reproduced everywhere)
Based on a suggestion made in #6002.
This PR also fixes some wrong cache-keys, which resulted in the cache being filled with duplicates.
FYI @bpandola - I'm not sure yet whether this is the best approach, but it does help readability. Suggestions are always welcome!
> Admin: Introduce reusable CI workflows

- moto/glue/models.py
- tests/test_glue/test_datacatalog.py
> Glue: get_table() should return latest version

- moto/s3/exceptions.py
- moto/s3/responses.py
- moto/s3/utils.py
- tests/test_s3/test_s3_utils.py
- tests/test_s3/test_server.py
Fixes #6003 
- Moto now only returns one Origin header
- Moto now supports wildcards in the supplied AllowedOrigins
- Moto now raises an error if none of the supplied origins match
> S3: Improve Cors AllowedOrigin behaviour

- moto/ec2/models/vpcs.py
- tests/test_ec2/test_vpcs.py
> EC2: create_vpc_endpoint() should use default policy doc if not provided

- moto/s3/responses.py
- tests/test_s3/test_s3_storageclass.py
This PR fixes a bug where S3 objects with deep archive storage class could not be retrieved after restoration was complete.
> S3: Restored archived objects must be retrievable

- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_glue.py
Add support to more fields in Glue job
- `CodeGenConfigurationNodes`
- `ExecutionClass`
- `SourceControlDetails`
> [Glue] Add support to more fields in Glue job

- .github/workflows/data-update_ec2-instance-offerings.yml
- .github/workflows/data-update_ec2-instance-types.yml
- .github/workflows/data-update_ssm-default-amis.yml
- .github/workflows/data-update_ssm-default-parameters.yml
Closes #6014 
Closes #6015 
Closes #6016 
The old GH action would, somehow, push commits to it's own branch, but also onto other branches created 2 hours earlier.  (Best shown in #6014, where every GH execution pushed a commit to)
> Admin: Use different GH action to create PRs

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/secretsmanager.rst
- moto/secretsmanager/models.py
- moto/secretsmanager/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_secretsmanager/test_policy.py
Fixes #6034 
We no longer return a policy if there hasn't been one created, in-line with what AWS does. Only when it is created, do we return it.
> SecretsManager - put/delete_resource_policy

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Add support for cloudformation:stack, ecs:service, ecs:cluster, and ecs:task ResourceTypeFilters for ResourceGroupsTaggingAPI get_resources.
> Support CloudFormation and ECS ResourceTypeFilters in ResourceGroupsTaggingAPI get_resources()

- moto/ec2/models/security_groups.py
- moto/ec2/responses/security_groups.py
- tests/test_ec2/test_security_groups.py
Fixes #6032 
Fixes #6050 
EC2: revoke_security_group_egress() no longer throws an error when IPProtocol-argument is not provided
EC2: describe_security_group_rules() now provides the correct value for the IsEgress-parameter
> EC2: Revoke rules without specifying IPProtocol

- moto/athena/models.py
- moto/athena/responses.py
- tests/test_athena/test_athena.py
* Add the 3 athena mocks below:
* `list_named_queries()`  with pagination
* `create_prepared_statement()`
* `get_prepared_statement()`
* Enable default `primary` workgroup in athena_backend
* Ensure Named Queries are always part of a workgroup (default to primary)
> Some Athena fixes and additions

- moto/cloudformation/models.py
- moto/cloudformation/parsing.py
- moto/cloudformation/responses.py
- moto/cloudformation/utils.py
- moto/dynamodb_v20111205/models.py
- tests/test_cloudformation/test_cloudformation_nested_stacks.py
Fixes #6020 
Involves some minor refactorings:
- extracting the `get_stack_from_s3_url`-method to utils.py, as it is now called from both responses.py and models.py
- `MODEL_LIST` is now essentially a lazy property, to avoid any timing issues (e.g., the list is created before all models that it needs to gather are initialized)
- Removes code to create old DynamoDB (v20111205) tables. This isn't supported anymore since we dropped boto2-support, and wasn't reachable. 
(Refactoring the `MODEL_LIST` actually made this code reachable, and it broke all kinds of things because there is no way to differentiate between the two `AWS::DynamoDB::Table`-types, old and new)
> CloudFormation - support AWS::CloudFormation::Stack-resources

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/s3.rst
- moto/s3/models.py
- moto/s3/responses.py
- moto/s3/select_object_content.py
- setup.cfg
- tests/test_s3/test_s3_select.py
Initial (highly experimental) implementation of S3 Select, based on our own [parser](https://github.com/getmoto/py-partiql-parser).
Known missing features:
- Function aliases (`count(*) as cnt`)
- Most functions (only `count()` is supported)
- Result is always in JSON
- FieldDelimiters and RecordDelimiters are ignored
> S3: select_object_content() (Experimental)

- moto/ec2/models/route_tables.py
- tests/test_ec2/test_route_tables.py
Fixes #6096 
Partially reverts #5233 
@mmerrill3 Do you remember the details about the linked PR that you raised? From my testing, overlapping CIDR's are allowed - as long as it's not a direct match.
The docs even mention this scenario, and explain what happens when overlapping routes exist: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_route.html
Just wanted to know whether there was a specific reason that you added this check, maybe I missed some important details in my testing.
> EC2: create_route() should allow overlapping CIDR's

- .github/workflows/release.yml
- CHANGELOG.md
- moto/s3/models.py
- moto/s3/select_object_content.py
Also moves the S3 Select imports down, to ensure we only need the `py_partiql_parser`-dependency when the user actually makes a request to `select_object_content`
> Techdebt: Fix Docker SHA on release

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_server.py
> S3: head_bucket() now returns the region-header

- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html
I've written this to narrowly support the use case I need: retaining resources when deleting a CloudFormation Stack.
I haven't done anything to implement other DeletionPolicies (Snapshot). Nor have I done anything to change how this interacts with all the various CloudFormation abstractions (StackSets, StackInstances, ChangeSets, etc.)
> Support Retain DeletionPolicy in stacks

- moto/s3/responses.py
- tests/test_s3/test_server.py
> S3: get_object() now returns the AcceptRanges header

- moto/ec2/models/subnets.py
- moto/ec2/models/vpcs.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
- tests/test_ec2/test_ec2_cloudformation.py
This also removes `test_delete_stack_with_resource_missing_delete_attr`
because the test cases the assertions relied on (VPCs) are
no longer valid. Also, this functionality is better tested as part of
the CloudFormation test suite instead of the ec2 test suite.
I followed the pattern of ignoring types on these CloudFormation
classmethods.
> Implement CloudFormation Stack deletion for VPCs, Subnets

- CLOUDFORMATION_COVERAGE.md
- Makefile
- scripts/cloudformation_coverage.py
This change introduces a checklist similar to IMPLEMENTATION_COVERAGE.md
to document moto's adherence to the full CloudFormation specification.
The script (invoked via `make cloudformation_coverage`) finds any moto
models that implement `moto.core.common_models.CloudFormationModel` and
checks to see if all CRUD methods are implemented. For `has_cfn_attr`,
it also checks to see if all of the attributes exposed by `Fn::GetAtt` are
implemented. It does not check to see if `physical_resource_id` is
implemented because as far as I can tell, the published AWS spec doesn't
include that information:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html
A more aggressive approach would be to remove default implementations
from all the abstract methods and …
> CloudFormation: Add coverage checklist

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_neptune/test_clusters.py
- tests/test_rds/test_rds_clusters.py
* Add support for filtering by `db-cluster-id`.
* Add support for filtering by `engine`.
Obviates the need for the recent change (#6114) because the filter definition maps `db_cluster_id` to either `db_cluster_identifier` or `db_cluster_arn`.
Closes #6137
> Add filtering support for RDS::DBCluster

- CLOUDFORMATION_COVERAGE.md
- moto/logs/models.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#aws-resource-logs-loggroup-return-values
This brings CloudFormation's Ref behavior more in line with actual AWS behavior. Previously, it returned an instance of a LogGroup model.
I didn't add a test case for this but I'm happy to do so if requested.
> CloudFormation, Logs: Resolve LogGroup physical id and attributes

- moto/cloudformation/models.py
Fixing `delete_stack_instances`  implementation by clearing the `stack_instances` after iterating and deleting the stack_instances. 
ref: https://github.com/getmoto/moto/issues/6039
> Issue#6039: Fix Cloudformation delete stack implementation

- moto/dynamodb/models/dynamo_type.py
- tests/test_dynamodb/test_dynamodb.py
This should handle `ADD`, `PUT` and `DELETE` to set for number sets (NS) in dynamodb `update_item`
- Added test coverage
- tested with AWS backend
> feat: dynamodb AttributeUpdate ADD/PUT/DELETE for NS

- moto/s3/responses.py
- tests/test_s3/test_server.py
Fixes #6116 
Follow-up to #6121
> S3: head_object() now returns the AcceptRanges header

- moto/ecs/models.py
- tests/test_ecs/test_ecs_boto3.py
See #6153 
This also simplifies some of the tests, by removing unnecessary configuration
> ECS: run_task() now validates the provided launch-type

- moto/ec2/models/elastic_network_interfaces.py
- moto/ec2/responses/elastic_network_interfaces.py
- tests/test_ec2/test_elastic_network_interfaces.py
Currently the `EC2.NetworkInterface.assign_private_ip_addresses()` API only supports the use of `SecondaryPrivateIpAddressCount`, ignoring the `PrivateIpAddresses` parameter. This PR adds very basic support for specifying the IP addrs, based on the implementation of `assign_ipv6_addresses()`.
Note limitations:
- Ignores `AllowReassignment` parameter
- Ignores the fact that specifying `PrivateIpAddresses` together with `SecondaryPrivateIpAddressCount` or similar parameters should be an error.
Tested manually in a docker container, connecting over the default docker bridge:
```
appuser@fd068e185858:~$ export AWS_ACCESS_KEY_ID=key
appuser@fd068e185858:~$ export AWS_SECRET_ACCESS_KEY=key
appuser@fd068e185858:~$ python
Python 3.11.2 (main, Mar 17 2023, 02:28:16) [GCC 8.3.0] on linux
Type …
```
> EC2: Support assigning specified private IP addrs

- .github/workflows/test_terraform.yml
`actions/setup-go@v4` has a builtin caching mechanism, so we no longer need to explicitly use `actions/cache@v3`.
With this PR we also stop running the tests when pushing to master. These tests are now only executed for pull requests. Every change that comes in goes through a PR anyway, so there's no point in running these tests twice.
> Techdebt: TF tests: Use builtin cache-mechanism from GA

- moto/moto_server/templates/dashboard.html
Fixes #6162 
The `bootstrap`-dependencies could also be upgraded to 5.x, but that breaks all our CSS, so let's stick with the current version for now until it breaks
> Update JS dependencies in MotoServer dashboard

- moto/cognitoidp/models.py
Cognito special characters include a double quota mark (`"`), which is missing in the current version: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html
> Add missing double quota to Cognito special characters.

- moto/dynamodb/parsing/key_condition_expression.py
- tests/test_dynamodb/models/test_key_condition_expression_parser.py
> fix: DynamoDB:query() KeyConditionExpression now allows enclosing the sort key condition in brackets

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_server.py
Hi, thanks for creating this useful library. Following on from https://github.com/getmoto/moto/issues/5259 I think that AWS Cognito validates the `new_password` in the `NEW_PASSWORD_REQUIRED` challenge. Therefore it might be nice to validate in `CognitoIdpBackend.respond_to_auth_challenge` in moto also. That is provided in this PR.
> Validate password in NEW_PASSWORD_REQUIRED

- moto/ec2/models/security_groups.py
- tests/test_ec2/test_security_groups.py
This fixes the `revoke_security_group_ingress` effectively removing all ingress rules when attempting to remove one rule while leaving the rest of the rules in the group.
> EC2: Fix egress rules used in ingress revoke method

- moto/dynamodb/models/table.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Fixes #6182 
Partially reverts #5638
> DynamoDB: Allow attribute name 'S'

- moto/s3/responses.py
- tests/test_s3/test_server.py
A Bucket Creation does not require a Content-Length header.
All other PUT-requests do.
Because all other PUT-requests use the query-string to indicate the action (`?policy` to set a policy, `?tagging` to add tags to a bucket, etc) it should be safe to assume that a BucketCreation-request never includes a query-string.
Fixes #6179
> S3: Allow Bucket Creation without specifying Content-Length header

- moto/elbv2/models.py
Export `FakeLoadBalancer` attribute `"load_balancing.cross_zone.enabled"` with default value to `false`.
The field is expected by Ansible Module [`elb_network_lb_module`](https://docs.ansible.com/ansible/latest/collections/community/aws/elb_network_lb_module.html) and is crashing when running it when the attr `cross_zone_load_balancing` is set:
```
KeyError: 'load_balancing_cross_zone_enabled'
fatal: [localhost]: FAILED! => {
"attempts": 3,
"changed": false,
"module_stderr": Traceback (most recent call last):
File "/.ansible/tmp/ansible-tmp-1681102653.2061028-974426-83965977195528/AnsiballZ_elb_network_lb.py", line 107, in <module>
_ansiballz_main()
File "/.ansible/tmp/ansible-tmp-1681102653.2061028-974426-83965977195528/AnsiballZ_elb_network_lb.py", line 99, in _ansiballz_main …
```
> elbv2-FakeLoadBalancer: export attr load_balancing.cross_zone.enabled

- moto/applicationautoscaling/models.py
- tests/test_applicationautoscaling/test_applicationautoscaling.py
This PR fixes policy ARNs missing account IDs.
Closes https://github.com/localstack/localstack/issues/8132
> Fix autoscaling policy ARN

- moto/sts/models.py
- tests/test_sts/test_sts_integration.py
Currently, when performing sts.AssumeRole, we are storing the AccessKey in the account backend of the requesting account.
This, however, leads to the key not being found e.g. for sts.GetCallerIdentity, and also leads to wrong behavior in this method: https://github.com/getmoto/moto/blob/90d67db6eae20ccde57356b694e013fd5864d14a/moto/iam/models.py#L72 which is necessary for account detection.
* Store the access key in the store of the account the role belongs to instead of the one assuming the role. There are points to be made for both, depending on who you think the access key belongs to, but otherwise we would need to adapt the surrounding logic, so I just went forward and assumed the access key always belongs to the account of the role.
* Test the behavior by asserting on the output of …
> Store temporary access key in the correct account backend

- moto/elbv2/models.py
- tests/test_elbv2/test_elbv2.py
describe-target-health is not returning the expected structure when the target is new
- create the target group (without registering the target)
- send describe-target-health with a target as a parameter
```
botocore.errorfactory.InvalidTargetException: An error occurred (InvalidTarget) when calling the DescribeTargetHealth operation: The specified target does not exist or is not in the same VPC as the target group.
```
```
Valid `FakeHealthStatus`  with reason `Target.NotRegistered`
```
- https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetHealth.html
-
> fix/describe-target-health: return unavailable target

- moto/ecr/models.py
- tests/test_ecr/test_ecr_boto3.py
Currently, `ECRClient.batch_get_image` fails to return an image by any tag other than the one most recently PUT. This appears to be contrary to the functionality of `batch_get_image` against the AWS ECR API.
Code change to correct this issue very small but the PR does include a test case.
> fix: Corrects ECRClient.batch_get_image tag handling

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
> S3: get_object() should not return VersionId for non-versioned buckets

- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_glue.py
Hello,
while working with moto I got `NotImplementedError: The batch_get_jobs action has not been implemented`.
If you have any suggestions how to improve my code - please let me know!
cc @bblommers
> [Glue] Implement batch_get_jobs

- moto/ec2/models/route_tables.py
- tests/test_ec2/test_route_tables.py
This PR adds support for using a NetworkInterfaceId as the target in ReplaceRoute.
Also updated test case `test_route_tables.py::test_routes_replace`.
> Implement ReplaceRoute to NetworkInterfaceId

- moto/s3/responses.py
- tests/test_s3/test_s3_copyobject.py
Resolves https://github.com/getmoto/moto/issues/6234
> S3: add a checksum to a copied object if requested so

- moto/core/exceptions.py
- moto/sns/models.py
- moto/sns/responses.py
- tests/test_sns/test_publishing_boto3.py
- tests/test_sns/test_subscriptions_boto3.py
During work on https://github.com/getmoto/moto/issues/6087 I've run the `tests/test_sns/test_publishing_boto3.py` tests against the "real" AWS (after some modifications) and I've found out that there are issues with numeric filtering.
It's mostly about the types used.
Changes implemented:
1. [SNS filter policy using "numeric" matching](https://docs.aws.amazon.com/sns/latest/dg/numeric-value-matching.html) checks requires numbers (as in int/float) to be provided in the check, not strings
2. Message attributes of type "Number" should be provided (and returned in responses) as strings. They've been ints/floats till now
3. General parameter validation for numeric matching, although limited. The errors from AWS contain the exact location where the parsing error occurs and doingit the same way …
> sns: numeric filtering fixups + parameter validation

- moto/kinesis/models.py
- tests/test_kinesis/test_kinesis_stream_limits.py
Currently, the `put_records` limit validations have the following errors:
- The size of the partition key is not included in the calculation
- The data length is calculated using the base64 encoded data, which is approximately 34% larger
- The total records validation is checking for 5000000 bytes instead of 5*(2**20) bytes
- It is not possible to send a record with exactly 1 MiB
- It is not possible to send 5 MiB worth of records.
ref:
https://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html
> fix: calculating size of record using decoded data and partition key

- moto/cognitoidp/models.py
- moto/databrew/models.py
- moto/dax/models.py
- moto/ds/models.py
- moto/events/models.py
- moto/glue/models.py
- moto/iot/models.py
- moto/kinesis/models.py
- moto/logs/models.py
- moto/organizations/models.py
- moto/route53/models.py
- moto/route53resolver/models.py
- moto/sagemaker/models.py
- moto/ssoadmin/models.py
- moto/stepfunctions/models.py
- moto/utilities/aws_headers.py
- moto/utilities/distutils_version.py
- moto/utilities/docker_utilities.py
- moto/utilities/paginator.py
- moto/utilities/tagging_service.py
- moto/utilities/utils.py
- setup.cfg
- tests/test_utilities/test_paginator.py
MyPy currently does not support our usecase for the `paginate`-decorator, which means that we have to add `type: ignore` everywhere.
In the future, it should be typed using ParamSpec
https://stackoverflow.com/a/70591060/13245310
I believe this will work after https://github.com/python/mypy/pull/14903 is accepted
> Techdebt: MyPy U
