getmoto/moto

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/quicksight.rst
- moto/quicksight/models.py
- moto/quicksight/responses.py
- moto/quicksight/urls.py
- tests/test_quicksight/test_quicksight_datasets.py
- tests/test_quicksight/test_quicksight_groups.py
- tests/test_quicksight/test_quicksight_users.py
New methods:
- describe_group_membership
- list_groups
- list_group_memberships
- list_users
- create_group_membership
- create_data_set
- create_ingestion
`create_data_set` and `create_ingestion` is a no-op for now, it just returns static data
> QuickSight - More features

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/rds.rst
- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_cloudformation.py
- tests/test_rds/test_rds_clusters.py
Also removes some dead code, adds tests for previously untested code and renames some methods so they are included in the implementation coverage
> RDS - improve tagging support

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_server.py
> CognitoIDP - sign_up can be unauthenticated

- moto/databrew/exceptions.py
- moto/databrew/models.py
- moto/databrew/responses.py
- moto/databrew/urls.py
- tests/test_databrew/test_databrew_recipes.py
- tests/test_databrew/test_databrew_rulesets.py
This adds some new new methods to the databrew service for recipes and rulesets.
New methods:
- databrew:
-  update_recipe()
-  create_ruleset()
-  delete_ruleset()
-  update_ruleset()
-   list_rulesets()
> This adds some new new methods to the databrew service for recipes and rulesets.

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/application-autoscaling.rst
- moto/applicationautoscaling/models.py
- moto/applicationautoscaling/responses.py
- tests/test_applicationautoscaling/test_applicationautoscaling.py
> ApplicationAutoscaling - Scheduled Actions

- moto/ec2/_models/transit_gateway_route_tables.py
- tests/test_ec2/test_transit_gateway.py
> EC2 - search_transit_gateway_routes -search by CIDR

- setup.py
<details>
<summary>Full preview</summary>
</details>
> build(setup.py): Add issues, changelog link to PyPI

- moto/ses/models.py
- tests/test_ses/test_ses_boto3.py
fix #5042 
added a test to check the corrected behavior
> fix idempotency on verify_email_identity endpoint

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
This PR enhances the `get_metric_data` request of Cloudwatch.
If "dimensions" are part of the metric-queries for `get_metric_data`, the logs will be filtered accordingly.
[The docs state](https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-getmetricstatistics-data/):
> If the metric is created with multiple dimensions, then the data points for that metric can be retrieved only by specifying all the configured dimensions.
> cloudwatch: filter 'dimensions' for get_metric_data

- moto/elbv2/models.py
- moto/elbv2/responses.py
- setup.cfg
- tests/terraformtests/terraform-tests.failures.txt
- tests/terraformtests/terraform-tests.success.txt
- tests/test_elbv2/test_elbv2_target_groups.py
Also adds more default attributes for target groups
> ELBv2 - enable Tags for create_target_group

- moto/cloudformation/models.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
> CF - detect changesets without changes

- moto/apigatewayv2/responses.py
- moto/dax/exceptions.py
- moto/ec2/_models/vpcs.py
- requirements-dev.txt
- tests/test_cloudformation/test_cloudformation_custom_resources.py
- tests/test_cognitoidp/test_cognitoidp.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb2/test_dynamodb.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_elastic_ip_addresses.py
- tests/test_ec2/test_prefix_lists.py
- tests/test_ecr/test_ecr_policy_validation.py
- tests/test_elb/test_elb.py
- tests/test_elb/test_elb_policies.py
- tests/test_emrcontainers/test_emrcontainers.py
- tests/test_es/test_es.py
- tests/test_kms/test_kms_boto3.py
- tests/test_logs/test_logs.py
- tests/test_mediaconnect/test_mediaconnect.py
- tests/test_quicksight/test_quicksight_users.py
- tests/test_route53/test_route53.py
- tests/test_s3/test_s3_lambda_integration.py
- tests/test_sdb/test_sdb_domains.py
- tests/test_ses/test_ses_boto3.py
- tests/test_sns/test_publish_batch.py
- tests/test_transcribe/test_transcribe_boto3.py
> Upgrade flake8 to 4.x

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
Closes issue [#5065](https://github.com/spulec/moto/issues/5065).
Added test.
> [CloudWatch] Take into account _metric_name if dimensions are set

- moto/organizations/models.py
- tests/test_organizations/organizations_test_utils.py
- tests/test_organizations/test_organizations_boto3.py
* Returns no response body
* Account remains in org in SUSPENDED state
Fixes #5063.
> fix(org): close_account matches public API

- moto/elbv2/models.py
- moto/elbv2/responses.py
- tests/test_elbv2/test_elbv2_listener_rules.py
This PR adds support for all Action types in ELBv2 create_rule and set_rule_priorities responses.
> Support all Action types in ELBv2 create_rule and set_rule_priorities responses

- moto/core/responses.py
- moto/ec2/_models/instances.py
- moto/ec2/_models/spot_requests.py
- moto/ec2/responses/_base_response.py
- moto/ec2/utils.py
- tests/test_ec2/test_instances.py
> EC2 - Pass LaunchTemplate tags to new Instances

- moto/timestreamwrite/models.py
- moto/timestreamwrite/responses.py
- tests/terraformtests/terraform-tests.failures.txt
- tests/terraformtests/terraform-tests.success.txt
- tests/test_timestreamwrite/test_timestreamwrite_table.py
This is now supported for both `create_table` and `update_table`
> TimestreamWrite - support MagneticStoreWriteProps-argument

- .github/workflows/test_outdated_versions.yml
- moto/s3/responses.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_server.py
> S3 list_object_versions - ensure the prefix can contain a plus

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/test_cognitoidp/test_server.py
> CognitoIDP - allow unauthenticated requests to GetUser

- docs/docs/services/batch.rst
- moto/__init__.py
- moto/batch/models.py
- moto/batch_simple/__init__.py
- moto/batch_simple/models.py
- moto/batch_simple/responses.py
- moto/batch_simple/urls.py
- moto/utilities/docker_utilities.py
- tests/test_batch_simple/test_batch_cloudformation.py
- tests/test_batch_simple/test_batch_compute_envs.py
- tests/test_batch_simple/test_batch_jobs.py
> Feature: Dockerless Batch

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_filters.py
Fixes: https://github.com/spulec/moto/issues/5091
> RDS Filtering on db-cluster-id

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ebs.rst
- moto/__init__.py
- moto/backend_index.py
- moto/ebs/__init__.py
- moto/ebs/models.py
- moto/ebs/responses.py
- moto/ebs/urls.py
- setup.py
- tests/test_ebs/test_ebs.py
> Feature: EBS

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/rds.rst
- moto/rds/exceptions.py
- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds.py
- tests/test_rds/test_rds_clusters.py
> RDS - support for EnableCloudWatchLogExports-parameter

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
> AdminInitiateAuth - return correct AccessToken for Refresh-scenario

- moto/ec2/models/vpcs.py
- moto/ec2/responses/vpcs.py
- tests/test_ec2/test_vpcs.py
> EC2:describe_vpc_endpoints() - filter by vpc-endpoint-type

- moto/secretsmanager/models.py
- moto/secretsmanager/responses.py
- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_secretsmanager.py
> SSM - Integrate with SecretsManager

- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB - error when persisting an empty number set

- moto/rds/models.py
- tests/test_rds/test_server.py
> RDS - Dont return empty DBClusterIdentifier

- moto/core/__init__.py
- moto/core/base_backend.py
- moto/core/botocore_stubber.py
- moto/core/common_models.py
- moto/core/models.py
- moto/core/urls.py
- moto/ec2/models/spot_requests.py
- moto/instance_metadata/models.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
Also removes the `Model`-class, as it didn't have any use.
Follow-up to #5121
> Refactor BotocoreStubber/BaseBackend into separate files

- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_glue.py
- Implementing list_crawlers() function. First time contributing to this project so lmk if I've missed anything.
> list crawler implementation

- docs/docs/services/cloudfront.rst
- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- moto/cloudfront/urls.py
- moto/core/models.py
- tests/test_cloudfront/cloudfront_test_scaffolding.py
- tests/test_cloudfront/test_cloudfront.py
- tests/test_cloudfront/test_cloudfront_distributions.py
[ Adds update_distribution() support for cloudfront client ](https://github.com/spulec/moto/issues/5114)
- Basic update_distribution() functionality
- Tests not overly extensive, but verifies changes to an existing config get updated in the actual config.
> cloudront.update_distribution() support

- moto/s3/responses.py
- tests/test_s3/test_s3_auth.py
> S3 - Return custom response when calling DeleteObjects unauthenticated

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/test_cognitoidp/test_server.py
> CognitoIDP - allow respond_to_auth_challenge without Auth-header

- moto/organizations/models.py
- moto/organizations/responses.py
- moto/organizations/utils.py
- moto/ram/models.py
- tests/test_organizations/test_organizations_boto3.py
> Add pagination support for additional actions

- moto/ec2/exceptions.py
- moto/ec2/models/instances.py
- tests/test_ec2/test_instances.py
Fix to:
https://github.com/spulec/moto/issues/5128
> Add availability zone check on add instance

- moto/awslambda/models.py
- moto/dax/models.py
- moto/dax/responses.py
- moto/ecr/models.py
- tests/terraformtests/bin/run_go_test
- tests/terraformtests/terraform-tests.failures.txt
- tests/terraformtests/terraform-tests.success.txt
- tests/test_awslambda/test_lambda_layers.py
- tests/test_cloudformation/test_cloudformation_stack_integration.py
- tests/test_dax/test_dax.py
- tests/test_ecr/test_ecr_boto3.py
AWSLamba:publish_layer_version() now supports the CompatibleArchitectures-parameter
DAX:create_cluster() now supports the ClusterEndpointEncryptionType-parameter
> Enable more TF tests

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/elb.rst
- moto/ec2/models/instances.py
- moto/elb/models.py
- moto/elb/responses.py
- tests/test_elb/test_elb.py
> ELB:describe_instance_health() - implement OutOfService status

- moto/ec2/models/route_tables.py
- tests/test_ec2/test_route_tables.py
> Add `route.gateway-id` filter for ec2:DescribeRouteTables

- moto/rds/models.py
- tests/test_rds/test_server.py
> RDS - return unknown bools as false, instead of none

- moto/ec2/models/instances.py
- moto/ec2/models/key_pairs.py
- moto/settings.py
- tests/test_ec2/test_instances.py
proposed fix for https://github.com/spulec/moto/issues/5151
> Add keypair validation

- moto/ec2/models/key_pairs.py
Use the BaseModel as the base class of KeyPair to make this class
listed in the dashboard.
Fixes #5171
> [dashboard] Fix KeyPair tracking

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/guardduty.rst
- moto/guardduty/exceptions.py
- moto/guardduty/models.py
- moto/guardduty/responses.py
- moto/guardduty/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_guardduty/test_guardduty.py
- tests/test_guardduty/test_guardduty_filters.py
- tests/test_guardduty/test_guardduty_organization.py
Closes #5167 
New methods:
- create_filter()
- delete_detector()
- delete_filter()
- enable_organization_admin_account()
- get_detector()
- get_filter()
- list_organization_admin_accounts()
- update_detector()
- update_filter()
> GuardDuty - additional functionality around detectors and filters

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/kms.rst
- moto/kms/models.py
- moto/kms/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_kms/test_kms_grants.py
> KMS - add Grants API

- moto/s3/models.py
- moto/s3/responses.py
This PR corrects the last problem commented in #5181 by @tsiq-rob.
> s3 key_name encoding should be variable

- moto/dynamodb/parsing/expressions.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB - error when ending an UpdateExpression with a comma

- moto/cognitoidp/models.py
- moto/ec2/utils.py
- moto/efs/models.py
- moto/glacier/models.py
- moto/iam/models.py
- moto/kinesis/models.py
- moto/s3/models.py
- moto/sqs/models.py
- moto/utilities/utils.py
AKA: allow Moto to run on FIPS-enabled systems
Closes #5166
> MD5 - set usedforsecurity-parameter everywhere

- moto/greengrass/exceptions.py
- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_core.py
- get_core_definition
- delete_core_definition
- update_core_definition
- list_core_definitions
> Greengrass Implement core_definition CRUD operation

- moto/greengrass/exceptions.py
- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_core.py
- get_core_definition_version
- list_core_definition_versions
> Greengrass Implement core_definition_version READ operation

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_device.py
- create_device_definition
- create_device_definition_version
> Greengrass Implement create_device_definition 

- moto/secretsmanager/utils.py
- tests/test_secretsmanager/test_secretsmanager.py
> change secret ARNs to 6 random chars at end

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_device.py
- get_device_definition
- delete_device_definition
- update_device_definition
- list_device_definitions
> Greengrass Implement device_definition APIs

- IMPLEMENTATION_COVERAGE.md
- moto/ssoadmin/models.py
- moto/ssoadmin/responses.py
- moto/ssoadmin/utils.py
- tests/test_ssoadmin/test_ssoadmin.py
Add support for `SSOAdmin`:
- create_permission_set
- delete_permission_set
- update_permission_set
- describe_permission_set
- list_permission_sets
> sso-admin: add PermissionSet actions

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_device.py
- get_device_definition_version
- list_device_definition_versions
> Greengrass Implement device_definition_version APIs

- moto/ec2/exceptions.py
- moto/ec2/models/__init__.py
- moto/ec2/models/vpcs.py
- moto/ec2/responses/vpcs.py
- tests/test_ec2/test_vpcs.py
> Implements EC2 - create_default_vpc

- docs/docs/services/lambda.rst
- moto/awslambda/models.py
- tests/test_awslambda/test_lambda.py
> AWSlambda: Support creation of functions with PackageType=Image

- moto/ec2/exceptions.py
- moto/ec2/responses/_base_response.py
- tests/test_ec2/test_tags.py
> EC2 - Error when passing in TagSpec with 0 tags

- moto/apigateway/models.py
- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
- tests/test_apigateway/test_apigateway_integration.py
Fixes https://github.com/spulec/moto/issues/5220
> add request parameters to integration model

- docs/docs/services/eks.rst
- moto/eks/models.py
- moto/eks/responses.py
- moto/eks/urls.py
- tests/test_eks/test_eks.py
Implementation for EKS functions tag_resource, untag_resource, and list_tags_for_resources
Implements #5203 
Signed-off-by: mmerrill3 <jjpaacks@gmail.com>
> feature: tag functions in eks(#5203)

- moto/route53/exceptions.py
- moto/route53/models.py
- tests/test_route53/test_route53.py
Add validation for [Action](https://docs.aws.amazon.com/Route53/latest/APIReference/API_Change.html#Route53-Type-Change-Action) attribute in [ChangeResourceRecordSets](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html).
> feat[route53]: Validate action value in change_resource_record_sets.

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_resource.py
- create_resource_definition
- create_resource_definition_version
> Greengrass Implement create_resource_definition

- moto/greengrass/exceptions.py
- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_resource.py
- list_resource_definitions
- get_resource_definition
- delete_resource_definition
- update_resource_definition
> Greengrass Implement resource_definition APIs

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_resource.py
- list_resource_definition_versions
- get_resource_definition_version
> Greengrass Implement resource_definition_version APIs 

- moto/s3/models.py
- tests/test_s3/test_s3_tagging.py
> S3 - Return tag-count as string

- moto/route53resolver/models.py
- moto/route53resolver/responses.py
- tests/terraformtests/terraform-tests.success.txt
- associate_resolver_endpoint_ip_address
- disassociate_resolver_endpoint_ip_address
- TestAccRoute53ResolverEndpoint
- TestAccRoute53ResolverEndpoint_basicInbound
- TestAccRoute53ResolverEndpoint_updateOutbound
- TestAccRoute53ResolverEndpointDataSource_basic
- TestAccRoute53ResolverEndpointDataSource_filter
> feature route53resolver: ip address associate/disassociate

- moto/__init__.py
- moto/backend_index.py
- moto/ce/__init__.py
- moto/ce/exceptions.py
- moto/ce/models.py
- moto/ce/responses.py
- moto/ce/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_ce/test_ce.py
Initial implementation that covers the following features:
- create_cost_category_definition
- delete_cost_category_definition
- describe_cost_category_definition
- update_cost_category_definition
Closes #3166
> Feature: Cost Explorer

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudfront.rst
- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- moto/cloudfront/urls.py
- tests/terraformtests/bin/run_go_test
- tests/terraformtests/etc/0001-Patch-Hardcode-endpoints-to-local-server.patch
- tests/terraformtests/etc/0006-CF-Reduce-wait-times.patch
- tests/terraformtests/terraform-tests.success.txt
- tests/test_cloudfront/cloudfront_test_scaffolding.py
- tests/test_cloudfront/test_cloudfront_dist_tags.py
- tests/test_cloudfront/test_cloudfront_distributions.py
- tests/test_cloudfront/test_cloudfront_invalidation.py
- tests/test_cloudfront/test_server.py
New methods:
- create_distribution_with_tags()
- create_invalidation()
Extends list of supported distribution configurations.
Closes #5227
> CloudFront improvements

- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_groups.py
- associate_role_to_group
- get_associated_role
- disassociate_role_from_group
> Greengrass Implement group and role associate APIs 

- moto/core/responses.py
- tests/test_emr/test_emr_boto3.py
NOTE: This only fixes the error.  It doesn't change the fact that Moto doesn't currently do anything with this parameter.
Ref: #5276
> Fix TypeError when calling emr:RunJobFlow with AutoTerminationPolicy

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
> Add Domain to DescribeUserPool response

- moto/greengrass/exceptions.py
- moto/greengrass/models.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
- tests/test_greengrass/test_greengrass_deployment.py
mplement these APIs
- create_deployment
- list_deployments
- get_deployment_status
- reset_deployments
> Greengrass Implement Deployments APIs

- setup.py
- tests/terraformtests/etc/0002-EC2-reduce-wait-times.patch
This needs to be fixed properly down the line, but downgrading is good enough for now.
This PR also changes some TF timeouts to ensure the tests have a lower chance of timing out
> Downgrade werkzeug

- moto/rds/models.py
PR to add aurora-mysql and aurora-postgresql to the db instance module to fix
https://github.com/spulec/moto/issues/5310
> add aurora-mysql and aurora-postgresql to model

- moto/ec2/utils.py
- tests/test_ec2/test_instances.py
> Add `key-name` filter for `ec2:DescribeInstances`

- moto/iot/models.py
- tests/test_iot/test_iot_thing_groups.py
currently you cannot update the description of a thing group. Now you can.
> update thing group descriptions

- moto/ec2/models/availability_zones_and_regions.py
- moto/ec2/models/vpcs.py
- moto/ec2/responses/availability_zones_and_regions.py
- moto/ec2/responses/vpcs.py
- tests/terraformtests/etc/0002-EC2-reduce-wait-times.patch
- tests/terraformtests/terraform-tests.success.txt
- added filtering in `describe_availability_zones`
- updated `zone-type` in `zone`
- updated `describeVpcs` response
> fixed filtering in describe az

- IMPLEMENTATION_COVERAGE.md
- moto/mediaconnect/models.py
- moto/mediaconnect/responses.py
- moto/mediaconnect/urls.py
- tests/test_mediaconnect/test_mediaconnect.py
Implement add_flow_sources and update_flow_source.
> Implement mediaconnect

- moto/glue/exceptions.py
- moto/glue/glue_schema_registry_constants.py
- moto/glue/glue_schema_registry_utils.py
- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/fixtures/schema_registry.py
- tests/test_glue/helpers.py
- tests/test_glue/test_schema_registry.py
Feature Added: GetSchemaVersion API from Glue Schema Registry
Feature: Implemented GetSchemaByDefinition API featues from Glue Schema Registry.
Feature: Implemented PutSchemaVersionMetadata API featues from Glue Schema Registry.
Bug Fix: CreateSchema with default-registry
Feature: DeleteSchema API for Glue Schema Registry
This is for #5146
> Feature: Glue Schema Registry APIs: GetSchemaVersion, GetSchemaByDefinition, DeleteSchema, PutSchemaVersionMetadata

- moto/ec2/models/key_pairs.py
- moto/ec2/responses/key_pairs.py
- moto/ec2/utils.py
- tests/test_ec2/test_key_pairs.py
Makes all key pairs have a `KeyPairId`.
Closes: https://github.com/localstack/localstack/issues/6614
> Key pairs must have unique IDs

- setup.py
> Pin Flask to same version as werkzeug

- moto/ses/models.py
- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
Feature: Implemented SendBulkTemplatedEmail API feature from SES.
This is [#5360](https://github.com/spulec/moto/issues/5360)
> SES: Implement SendBulkTemplatedEmail

- moto/ses/exceptions.py
- moto/ses/models.py
- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
Closes https://github.com/localstack/localstack/issues/5742
> SES: Implement DescribeConfigurationSet

- moto/rds/models.py
> RDS - change ClusterSnapshot creationtime to UTC

- moto/s3/responses.py
- tests/test_s3/test_s3.py
This PR adds the Checksums Values in a S3.put_key response if they were sent.
Related to localstack/localstack#6619
> Checksum headers added to S3 response

- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
- tests/test_apigateway/test_apigateway_stage.py
Fixes response status codes according to https://docs.aws.amazon.com/apigateway/latest/api/API_Operations.html
/cc @bblommers the server mode tests are failing, however I don't see the connection with my PR
> fix apigateway rest API status codes

- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/test_dynamodb_table_without_range_key.py
> DynamoDB - ensure TableARN has correct region

- IMPLEMENTATION_COVERAGE.md
- moto/ec2/exceptions.py
- moto/ec2/models/elastic_block_store.py
- moto/ec2/responses/elastic_block_store.py
- tests/test_ec2/test_elastic_block_store.py
Closes https://github.com/localstack/localstack/issues/5684
> EC2: implement ModifyVolumes and DescribeVolumesModifications

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/glue.rst
- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_datacatalog.py
Leaning heavily on CreateDatabase, this PR adds support for Glue's UpdateDatabase operation.
> Add Glue UpdateDatabase

- docs/docs/contributing/architecture.rst
The tense of this verb needed to be corrected.
> Fix verb tense

- moto/s3/responses.py
- tests/test_s3/test_s3_multipart.py
> S3 - Fix a bug when requesting a presigned URL on an object without ACL

- moto/iam/policy_validation.py
> IAM: Allow STS:TagSession as policy action

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/lambda.rst
- moto/awslambda/exceptions.py
- moto/awslambda/models.py
- moto/awslambda/responses.py
- moto/awslambda/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_awslambda/test_lambda_function_urls.py
> Feature: AWSLambda Function URL Configs

- moto/apigateway/models.py
- tests/test_apigateway/test_apigateway_integration.py
> APIGateway: Support Sagemaker URI's as integrations

- moto/sns/models.py
- tests/test_sns/test_publishing_boto3.py
> SNS:subscribe() now has increased support for the FilterPolicy-argument

- moto/s3/responses.py
- tests/test_s3/test_s3_multipart.py
> S3:head_object() now returns the PartsCount-header

- moto/dynamodb/models/__init__.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB:batch_put_item() now has validatior for empty keys

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/amp.rst
- moto/__init__.py
- moto/amp/__init__.py
- moto/amp/exceptions.py
- moto/amp/models.py
- moto/amp/responses.py
- moto/amp/urls.py
- moto/amp/utils.py
- moto/backend_index.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_amp/test_amp_rulegroupnamespaces.py
- tests/test_amp/test_amp_workspaces.py
Closes #5362 
Implemented methods:
create_rule_groups_namespace()
create_workspace()
delete_rule_groups_namespace()
delete_workspace()
describe_rule_groups_namespace()
describe_workspace()
list_rule_groups_namespaces()
list_tags_for_resource()
list_workspaces()
put_rule_groups_namespace()
tag_resource()
untag_resource()
update_workspace_alias()
> Feature: Managed Prometheus (AMP)

- moto/kinesis/exceptions.py
- moto/kinesis/models.py
- moto/kinesis/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_kinesis/test_kinesis.py
> Kinesis:create_stream() now supports stream-mode=OnDemand

- moto/sagemaker/models.py
- tests/test_sagemaker/test_sagemaker_endpoint.py
Closes #5443 
Adds support for Serverless Config in ProductionVariants, and updates tests to cover this use case
> Add support for Serverless Endpoint Configurations

- moto/dynamodb/parsing/key_condition_expression.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/models/test_key_condition_expression_parser.py
- tests/test_dynamodb/test_dynamodb_consumedcapacity.py
Fixes #2856
Also adds additional validation for KeyConditionExpressions that do not supply the required HashKey.
> DynamoDB:query() now has improved support for KeyConditionExpression

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/kinesis.rst
- moto/kinesis/exceptions.py
- moto/kinesis/models.py
- moto/kinesis/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_kinesis/test_kinesis.py
- tests/test_kinesis/test_kinesis_stream_limits.py
Also adds some validation for the `put_records` method.
Fixes #5249
> Implements Kinesis:update_stream_mode()

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/wafv2.rst
- moto/apigateway/models.py
- moto/wafv2/exceptions.py
- moto/wafv2/models.py
- moto/wafv2/responses.py
- moto/wafv2/utils.py
- tests/terraformtests/terraform-tests.failures.txt
- tests/terraformtests/terraform-tests.success.txt
- tests/test_wafv2/test_wafv2.py
- tests/test_wafv2/test_wafv2_integration.py
- tests/test_wafv2/test_wafv2_rules.py
- tests/test_wafv2/test_wafv2_tags.py
New methods:
- associate_web_acl()
- delete_web_acl()
- disassociate_web_acl()
- get_web_acl()
- get_web_acl_for_resource()
- list_rule_groups()
- tag_resource()
- untag_resource()
- update_web_acl()
Fixes #2722
> WAFv2: Extend coverage

- moto/apigateway/models.py
- moto/cloudformation/parsing.py
- tests/test_apigateway/test_apigateway_cloudformation.py
> APIGateway: Treat props as non-mandatory, and dont crash on unsupported resource

- IMPLEMENTATION_COVERAGE.md
- moto/cloudfront/responses.py
- tests/test_cloudfront/test_cloudfront_dist_tags.py
Solve a bug with distribution with tags error if only exists a one tag and update coverage document adding create_distribution_with_tags
> Bug distribution with tags

- setup.py
> Dependencies - always include Flask

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp_exceptions.py
> CognitoIDP - Handle login with unknown refresh-token gracefully

- moto/ec2/models/instances.py
- tests/test_ec2/test_instances.py
> EC2:run_instances() now validates the provided SecurityGroup

- moto/rds/models.py
- moto/rds/responses.py
Suggested solution to https://github.com/spulec/moto/issues/5479
> Fix error listing tags for rds db subnet group

- moto/moto_server/werkzeug_app.py
- setup.py
> Admin: Improve UX when Flask dependencies are missing

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
> SSM: now returns DeliveryTimedOutCount-attr

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds.py
> RDS: Ensure cross-region replica returns ARN

- moto/awslambda/models.py
- moto/awslambda/policy.py
- moto/awslambda/responses.py
- tests/test_awslambda/test_lambda_policy.py
> AWSLambda:add_permission() now properly handles the PrincipalOrgID-param

- setup.py
> Fix License title to Apache 2.0

- moto/ec2/models/availability_zones_and_regions.py
- moto/ec2/models/instances.py
- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_autoscaling_cloudformation.py
- tests/test_ec2/test_ec2_cloudformation.py
- tests/test_ec2/test_regions.py
- tests/test_ec2/test_subnets.py
- tests/test_ec2/test_vpc_endpoint_services_integration.py
- tests/test_elb/test_elb_cloudformation.py
- tests/test_elbv2/test_elbv2.py
> EC2: Fix us-west-1 availability zones to b and c

- CHANGELOG.md
- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/glue.rst
- docs/docs/services/rds.rst
- moto/glue/models.py
- moto/glue/responses.py
Some Glue-methods have been moved around to ensure that the models-file contains the logic (instead of the view/responses).
> Prepare release 4.0.6

- moto/ec2/models/spot_requests.py
- moto/ec2/responses/spot_fleets.py
- tests/test_ec2/test_spot_fleet.py
> EC2:cancel_spot_fleet_request - Keep instances if Terminate=false

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
Resolves https://github.com/spulec/moto/issues/3688
> Issue 3688, add eni to an ecs task

- moto/ec2/models/instances.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
State-change actions include start, stop and terminate instances.
> Include actual previous state in EC2 instance state-change actions

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/test_dynamodb.py
Solution for https://github.com/spulec/moto/issues/5496
> Improve DDB transaction validation

- Makefile
- moto/applicationautoscaling/exceptions.py
- moto/applicationautoscaling/models.py
- moto/applicationautoscaling/responses.py
- moto/applicationautoscaling/utils.py
- moto/core/base_backend.py
- moto/core/exceptions.py
- moto/core/models.py
- moto/core/responses.py
- moto/core/utils.py
- moto/moto_api/_internal/moto_random.py
- requirements-dev.txt
- setup.cfg
Initially only added to ApplicationAutoscaling - other modules/services will follow later
> TechDebt: Introduce MyPy typing annotations

- Makefile
- moto/acm/exceptions.py
- moto/acm/models.py
- moto/acm/responses.py
- moto/acm/utils.py
- moto/core/exceptions.py
- moto/elb/models.py
- moto/elbv2/models.py
- tests/test_acm/test_acm.py
- Moves exceptions to a dedicated file, and renames them to be more descriptive
- Refactoring to ensure instance-variables are only assigned inside the __init__-method
- Removes some dead code
- Removes duplicate methods that are already present in `core/responses.py`
> TechDebt - MyPy the ACM module

- moto/s3/models.py
- tests/test_s3/test_s3_multipart.py
> S3: close FileHandles on reset

- IMPLEMENTATION_COVERAGE.md
- Makefile
- docs/docs/services/apigateway.rst
- moto/apigateway/exceptions.py
- moto/apigateway/integration_parsers/__init__.py
- moto/apigateway/integration_parsers/aws_parser.py
- moto/apigateway/integration_parsers/http_parser.py
- moto/apigateway/integration_parsers/unknown_parser.py
- moto/apigateway/models.py
- moto/apigateway/responses.py
- moto/apigateway/utils.py
- moto/core/common_models.py
- moto/core/utils.py
- moto/utilities/utils.py
- setup.cfg
- tests/test_apigateway/test_apigateway.py
Also removes coverage for three functions. They all  tried to invoke a non-existing method, so it never would have worked if users would have tried using them.
Also removes some parameters, `cliInputJson` and `generateCliSkeleton`, as they are not part of the boto3-contract.
> TechDebt: Enable MyPy on APIGateway-module

- moto/dynamodb/parsing/ast_nodes.py
- tests/test_dynamodb/test_dynamodb_update_expressions.py
> DynamoDB - check nested attrs when validating duplicate set-actions

- moto/ecr/models.py
- tests/test_ecr/test_ecr_boto3.py
> ECR - Tags should be unique

- moto/elbv2/models.py
> ELBv2 - Add missing header

- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- tests/test_cloudfront/test_cloudfront_invalidation.py
> Initial implementation of list_invalidations() for cloudfront.

- docs/docs/services/ses.rst
- moto/ses/models.py
Brings SES documentation in line with SNS documentation:
http://docs.getmoto.org/en/latest/docs/services/sns.html
Based on Stack Overflow answer here:
https://stackoverflow.com/a/74044893/363784
> Feature/improve SES documentation

- .github/workflows/test_terraform.yml
- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/amp.rst
- moto/amp/models.py
- moto/amp/responses.py
- moto/amp/urls.py
- moto/ec2/models/vpcs.py
- tests/terraformtests/etc/0007-Comprehend-Reduce-wait-times.patch
- tests/terraformtests/terraform-tests.success.txt
- tests/test_amp/test_amp_logging_config.py
Originally raised in https://github.com/hashicorp/terraform-provider-aws/issues/27049
Upgrading to the latest `main`-branch removes the need to pin Terraform to an older version.
The latest branch tests some functionality that's still not covered by Moto, so we had to remove some of the tests that previously passed.
> TechDebt - Unpin TF

- moto/batch/models.py
- moto/batch/responses.py
- moto/batch/utils.py
- moto/batch_simple/models.py
- moto/batch_simple/responses.py
- moto/core/base_backend.py
- moto/ec2/models/instances.py
- moto/ec2/models/security_groups.py
- moto/ec2/models/subnets.py
- moto/ecs/models.py
- moto/iam/models.py
- moto/logs/models.py
- moto/moto_api/_internal/managed_state_model.py
- moto/moto_api/_internal/state_manager.py
- moto/utilities/tagging_service.py
- setup.cfg
- tests/test_batch/test_batch_compute_envs.py
Also fixes a bug where `batch.update_compute_environment(serviceRole="..")` would throw an error.
> TechDebt: MyPy Batch

- moto/ec2/models/route_tables.py
- tests/test_ec2/test_route_tables.py
> Implement filter `route.vpc-peering-connection-id` for DescribeRouteTables

- moto/ec2/models/iam_instance_profile.py
- moto/ec2/models/instances.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
Improvement on https://github.com/spulec/moto/pull/3064
Links up IAM instance profile with the ec2 backend.
> feat: link instance profile with ec2 instance

- .github/workflows/build.yml
- .github/workflows/dockertests.yml
- .github/workflows/test_outdated_versions.yml
- .github/workflows/test_terraform.yml
- codecov.yml
- setup.py
Also removes a bunch of warnings in our CI
> Admin: Enable support for Py 3.11

- moto/dynamodb/parsing/validators.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Closes #5554 
Followup to #4245, which only checks `SET pk=..` - this PR also validates what happens if `pk` is defined as an ExpressionAttributeName, i.e. `SET :pk=..`
> DynamoDB - do not allow HashKey to be changed on update

- tests/test_sqs/test_sqs.py
> SQS: Ensure we use the correct queue names in tests

- moto/batch/models.py
- tests/test_batch_simple/test_batch_jobs.py
Fix  #5595 : batch_simple regression.
The container details weren't returned in the job description anymore.
[ ] Feature is added
[x] The linter is happy
[x] Tests are added
[x] All tests pass, existing and new
> Fix #5595 : batch_simple regression.

- moto/cloudformation/models.py
- moto/cloudformation/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Include the `EnableTerminationProtection` in the CFN API `Create_Stack` and `Describe_Stacks`.
> feat(CloudFormation): Include EnableTerminationProtection

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB: put_item(): Improve type validation

- moto/cloudformation/exceptions.py
- moto/cloudformation/models.py
- moto/cloudformation/parsing.py
- moto/cloudformation/responses.py
- moto/cloudformation/utils.py
- moto/cloudwatch/models.py
- moto/cloudwatch/utils.py
- moto/codebuild/models.py
- moto/codebuild/responses.py
- moto/codecommit/exceptions.py
- moto/codecommit/models.py
- moto/codepipeline/exceptions.py
- moto/codepipeline/models.py
- moto/cognitoidentity/utils.py
- moto/cognitoidp/models.py
- moto/config/exceptions.py
- moto/config/models.py
- moto/core/custom_responses_mock.py
- moto/core/exceptions.py
- moto/core/responses.py
- moto/core/utils.py
- setup.cfg
> Techdebt: Replace string-format with f-strings (for c* dirs)

- moto/batch/models.py
- moto/batch/utils.py
- moto/batch_simple/models.py
> Techdebt: Replace string-format with f-strings (for b* dirs)

- moto/cloudfront/models.py
- tests/test_cloudfront/test_cloudfront_distributions.py
Include the following missing fields using the `create_distribution` API:
- DefaultCacheBehaviour.FieldLevelEncryptionId
- DefaultCacheBehaviour.RealtimeLogConfigArn
- Logging
- Enabled
- IncludeCookies
- Bucket
- Prefix
- WebACLId
> feat(CloudFront): Include missing fields

- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- tests/test_cloudfront/test_cloudfront_distributions.py
Include the `get_distribution_config` CloudFront API call.
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_GetDistributionConfig.html
> feat(CloudFront): Include get_distribution_config

- moto/acm/models.py
- moto/acm/utils.py
- moto/apigateway/integration_parsers/unknown_parser.py
- moto/apigateway/models.py
- moto/apigateway/responses.py
- moto/applicationautoscaling/models.py
- moto/applicationautoscaling/responses.py
- moto/athena/models.py
- moto/autoscaling/exceptions.py
- moto/autoscaling/models.py
- moto/awslambda/exceptions.py
- moto/awslambda/models.py
- moto/awslambda/responses.py
- moto/awslambda/utils.py
> Techdebt: Replace string-format with f-strings (for a* dirs)

- moto/databrew/exceptions.py
- moto/databrew/models.py
- moto/datapipeline/utils.py
- moto/datasync/models.py
- moto/dynamodb/comparisons.py
- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- moto/dynamodb/models/dynamo_type.py
- moto/dynamodb/parsing/executors.py
- moto/dynamodb/parsing/expressions.py
- moto/dynamodb/parsing/tokens.py
- moto/dynamodb/parsing/validators.py
- moto/dynamodb/responses.py
- moto/dynamodb_v20111205/models.py
- moto/dynamodbstreams/models.py
> Techdebt: Replace string-format with f-strings (for d* dirs)

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
This PR fixes [an issue](https://github.com/localstack/localstack/issues/7154) reported for LocalStack: 
[According to the cloudwatch API ](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html)`put-metric-data` could also accepts a list of `values` and optional `counts` for those values.
> You can publish either individual data points in the Value field, or arrays of values and the number of times each value occurred during the period by using the Values and Counts fields in the MetricDatum structure.
For example:
`awslocal cloudwatch put-metric-data --namespace test --metric-data MetricName=mymetric,Values=10,1,Counts=1,2`
In this PR:
* parse `values` and `counts` if set and add datapoints accordingly
* added tests
Also [prepared a PR in …
> add support for cloudwatch put-metric-data with values list

- moto/swf/models/__init__.py
- tests/test_swf/responses/test_decision_tasks.py
It shouldn't be possible to start a second decision task while another is running.
> To ensure that no conflicting decisions are processed, Amazon SWF assigns each decision task to exactly one decider and allows only one decision task at a time to be active in a workflow execution.
See https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-tasks.html
> [SWF] Start just one decision task at a time

- moto/apigateway/models.py
- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
Adds response parameters to integration response model.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration-responseParameters.html
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration-response.html
> Add response parameters to integration response

- moto/glacier/responses.py
- moto/glue/exceptions.py
> Techdebt: Replace string-format with f-strings (for g* dirs)

- moto/iam/access_control.py
- moto/iam/config.py
- moto/iam/exceptions.py
- moto/iam/models.py
- moto/iam/policy_validation.py
- moto/instance_metadata/responses.py
- moto/iot/exceptions.py
- moto/iot/models.py
> Techdebt: Replace string-format with f-strings (for i* dirs)

- moto/kinesis/models.py
- moto/kinesis/utils.py
- moto/kinesisvideo/models.py
- moto/kinesisvideoarchivedmedia/models.py
- moto/kms/responses.py
- moto/kms/utils.py
> Techdebt: Replace string-format with f-strings (for k* dirs)

- moto/logs/exceptions.py
- moto/logs/models.py
- moto/logs/responses.py
> Techdebt: Replace string-format with f-strings (for l* dirs)

- moto/managedblockchain/exceptions.py
- moto/managedblockchain/models.py
- moto/mediaconnect/models.py
- moto/medialive/models.py
- moto/mediapackage/models.py
- moto/mediastore/models.py
- moto/mediastoredata/models.py
- moto/moto_server/utilities.py
- moto/moto_server/werkzeug_app.py
> Techdebt: Replace string-format with f-strings (for m* dirs)

- moto/polly/models.py
- moto/polly/responses.py
- moto/polly/utils.py
> Techdebt: Replace string-format with f-strings (for p* dirs)

- moto/transcribe/models.py
> Techdebt: Replace string-format with f-strings (for t* dirs)

- moto/utilities/distutils_version.py
- moto/utilities/paginator.py
- moto/xray/exceptions.py
- requirements-dev.txt
- tests/test_dynamodb/test_dynamodb.py
> Techdebt: Replace string-format with f-strings

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Resolves https://github.com/spulec/moto/issues/5666
> DDB transaction limit increased to 100

- moto/s3/responses.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_server.py
> S3: Allow keynames with spaces

- moto/awslambda/models.py
> AWSLambda: Modify LastModified-date to correct format

- moto/elb/exceptions.py
- moto/elb/models.py
- tests/test_elb/test_elb.py
> ELB: describe_instance_health() should check LB existence

- moto/sqs/models.py
- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
Dear sir,
I have written code to resolve the issue number #5372. I have made following changes for the same:
1. models.py file (moto/moto/sqs/models.py): 
Line number 47: Micro defined as MAXIMUM_MESSAGE_DELAY = 900
Line number 808: In send_message function, I have put condition to check if delay_seconds is greater than MAXIMUM_MESSAGE_DELAY. If it is greater then InvalidParameterValue exception is raised with message described in the issue
2. test_sqs.py file (moto/tests/test_sqs.py):
Line number 3125: Written test to check if above approach works for 2 messages that are given in the issue.  One message is sent with delayseconds =180 which has to be sent successfully and another message is sent with delayseconds=1800 which should raise an exception. 
When I run the test for sqs module, …
> added code to resolve issue #5372

- moto/__init__.py
- moto/acmpca/__init__.py
- moto/acmpca/exceptions.py
- moto/acmpca/models.py
- moto/acmpca/responses.py
- moto/acmpca/urls.py
- moto/backend_index.py
- scripts/scaffold.py
- scripts/template/lib/models.py.j2
- tests/terraformtests/terraform-tests.success.txt
- tests/test_acmpca/test_acmpca.py
Fixes #5558 
Supported methods:
- create_certificate_authority
- delete_certificate_authority
- describe_certificate_authority
- get_certificate
- get_certificate_authority_certificate
- get_certificate_authority_csr
- import_certificate_authority_certificate
- issue_certificate
- list_tags
- revoke_certificate
- tag_certificate_authority
- update_certificate_authority
- untag_certificate_authority
> Feature: ACM-PCA

- tests/test_resourcegroups/test_resourcegroups.py
Follow-up to #5616 
FYI @bpandola - that should fix the remaining PytestReturnNotNoneWarnings
> Techdebt: Refactor/remove warnings in ResourceGroups tests

- moto/route53/exceptions.py
- moto/route53/models.py
- moto/route53/responses.py
- tests/test_route53/test_route53.py
> Route53: Intercept duplicate calls to change_rr_sets

- moto/cloudfront/models.py
- tests/test_cloudfront/cloudfront_test_scaffolding.py
- tests/test_cloudfront/test_cloudfront.py
- tests/test_cloudfront/test_cloudfront_distributions.py
> CloudFront: Persist origin changes made via update-distribution calls

- .github/workflows/build.yml
See https://github.com/actions/setup-python/issues/544
> Admin: CI: Downgrade Ubuntu to ensure Py3.6 is available

- moto/cognitoidp/models.py
> Docs: CognitoIDP: Explain how to make a request to the JWKS uri

- moto/core/responses.py
- tests/test_cognitoidentity/test_cognitoidentity.py
> Core: Detect unknown regions as part of the URL

- moto/route53/models.py
- tests/test_route53/test_change_set_model.py
- tests/test_route53/test_route53.py
> Route53: Validate deletion of RRsets

- moto/iam/policy_validation.py
> IAM - Add all valid TrustPolicy actions

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
> SSM: Improve tag filtering

- moto/cognitoidp/exceptions.py
- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
- tests/test_cognitoidp/test_cognitoidp_exceptions.py
- tests/test_cognitoidp/test_server.py
Fixes #5259 
Followup to #5757
> CognitoIDP - Validate password using policy

- moto/dynamodb/models/__init__.py
- moto/dynamodb/parsing/ast_nodes.py
- moto/dynamodb/parsing/executors.py
- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_dynamodb_executor.py
> DynamoDB: Allow removal of multiple listitems

- moto/rds/models.py
> RDS: Extend valid option group engines

- docs/docs/services/timestream-write.rst
- moto/timestreamwrite/models.py
Fixes #5755 
https://moto--5772.org.readthedocs.build/en/5772/docs/services/timestream-write.html
> TimestreamWrite: Add docs on how to check records using the internal API

- docs/docs/services/sagemaker.rst
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_pipeline.py
Added the following mocking functionality for `sagemaker`:
- `create_pipeline`
- `list_pipelines`
> Feature for SageMaker: create_pipeline, list_pipelines

- moto/ec2/models/elastic_block_store.py
- moto/ec2/models/instances.py
- moto/ec2/responses/elastic_block_store.py
- tests/test_ec2/test_elastic_block_store.py
I would like to add `Iops` to `create_volume` and `describe_volumes`.
> Add iops to volume

- tests/test_kms/test_kms_boto3.py
- tests/test_kms/test_kms_grants.py
Mocking the cryptographic operation 'generate_private_key` speeds up the total test time by about 33%
> Techdebt: KMS: Mock RSA calls in some tests

- docs/docs/services/sagemaker.rst
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_pipeline.py
Adding sagemaker mock call `update_pipeline`
`boto3.client("sagemaker").update_pipeline`
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.update_pipeline
> Add sagemaker mock call: update_pipeline

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
> CognitoIDP: sign_out() should invalidate AccessToken

- moto/cloudwatch/models.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
This PR adds support for the `statistic-values` parameter for the `put-metric-data` operation in `cloudwatch`. 
It has initially been reported a while ago in #1615, but there was no actual implementation provided (just a fix for the `KeyError`). Recently, an issue with `statistic-values` has been reported for [LocalStack](https://github.com/localstack/localstack/issues/7263) as well.
> support statistic-values in put-metric-data

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ec2.rst
- moto/ec2/models/__init__.py
- moto/ec2/models/windows.py
- moto/ec2/responses/windows.py
- tests/test_ec2/test_windows.py
Implements mock [EC2:GetPasswordData](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetPasswordData.html)
Closes https://github.com/localstack/localstack/issues/7362
> EC2: Implement GetPasswordData

- moto/secretsmanager/models.py
- moto/secretsmanager/responses.py
- tests/test_secretsmanager/test_secretsmanager.py
> Implement secretsmanager `CancelRotateSecret`

- .github/workflows/test_outdated_versions.yml
- moto/iotdata/responses.py
- moto/iotdata/urls.py
- tests/test_iotdata/test_iotdata.py
> IOTData: Fix bug where publish() could only be called once

- requirements-tests.txt
`surer` is a fork of `sure`, with the same functionality, but with support for more recent Python versions.
See: https://github.com/getmoto/surer/issues/6
> Admin: Update sure

- docs/docs/configuration/prettify_responses.rst
- docs/docs/configuration/recorder/index.rst
- docs/docs/contributing/installation.rst
- docs/docs/getting_started.rst
- docs/docs/server_mode.rst
> Admin: Improve documentation

- moto/batch/models.py
- moto/batch_simple/models.py
- tests/test_batch/test_batch_jobs.py
- tests/test_batch_simple/test_batch_jobs.py
This PR solves #5824 
The changes added are the minimum required to include the 'logStreamName' property to Batch Simple.
> Batch simple jobs inform log stream name

- moto/dynamodb/models/__init__.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB: Add validation for GSI attrs set to None

- moto/apigateway/models.py
- moto/apigateway/responses.py
- moto/apigateway/urls.py
- moto/core/common_types.py
- tests/test_apigateway/resources/petstore-swagger-v3.yaml
- tests/test_apigateway/resources/test_deep_api.yaml
- tests/test_apigateway/test_apigateway_export.py
- tests/test_apigateway/test_apigateway_importrestapi.py
> APIGateway: get_export()

- moto/core/custom_responses_mock.py
> Techdebt: Add missing type-ignore

- moto/ec2/models/security_groups.py
- moto/ec2/responses/security_groups.py
- tests/test_ec2/test_security_groups.py
Closes #5810 and https://github.com/localstack/localstack/issues/7245
> Feature #5810: Implemented `describe_security_group_rules` for `ec2`

- moto/ses/models.py
- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
> SES: Ensure service is region-aware

- moto/ecs/models.py
- tests/test_ecs/test_ecs_boto3.py
> ECS: list_services() now throws correct error when providing unknown cluster

- moto/dynamodb/comparisons.py
- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- moto/dynamodb/models/dynamo_type.py
- moto/dynamodb/models/table.py
- moto/dynamodb/models/utilities.py
- moto/dynamodb/parsing/ast_nodes.py
- moto/dynamodb/parsing/executors.py
- moto/dynamodb/parsing/expressions.py
- moto/dynamodb/parsing/key_condition_expression.py
- moto/dynamodb/parsing/reserved_keywords.py
- moto/dynamodb/parsing/tokens.py
- moto/dynamodb/parsing/validators.py
- moto/dynamodb/responses.py
- moto/dynamodbstreams/models.py
- moto/utilities/utils.py
- setup.cfg
Some refactorings to make type-support easier:
- The LimitedSizeDict and Item-classes are now part of `dynamo_type.py`
- Table-related classes (Table, Backup, StreamShard, ..) are now separated into `models/table.py`
> Techdebt: MyPy dynamodb

- moto/apigateway/models.py
- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
Adds the connection type field to the integration model.
https://docs.aws.amazon.com/apigateway/latest/api/API_Integration.html
> add connection type field to integration model

- docs/docs/services/events.rst
- moto/events/models.py
- tests/test_events/test_events_integration.py
> Events: Support CrossAccount events

- moto/cognitoidp/models.py
Fix https://github.com/getmoto/moto/issues/5871
> CognitoIDP: fix REFRESH_TOKEN_AUTH flow in admin_initiate_auth()

- moto/batch/responses.py
- tests/test_batch/test_batch_jobs.py
> Batch: Return RequestId for all operations

- moto/cognitoidp/exceptions.py
- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp_exceptions.py
> CognitoIDP: Error when detecting a duplicate email

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ec2.rst
- moto/ec2/models/__init__.py
- moto/ec2/models/hosts.py
- moto/ec2/responses/__init__.py
- moto/ec2/responses/hosts.py
- moto/ec2/utils.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_ec2/test_hosts.py
Fixes #2423
This implements:
- allocate_hosts()
- describe_hosts()
- modify_hosts()
- release_hosts()
> EC2: Support Dedicated Hosts

- moto/iam/models.py
> Fixed an issue with the moto IAM backend when used in Thread Pools

- docs/docs/services/s3.rst
- moto/iam/access_control.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_bucket_policy.py
> S3: Improve bucket policy enforcement

- moto/kinesis/models.py
- moto/kinesis/responses.py
- moto/kinesis/urls.py
- tests/test_kinesis/test_kinesis.py
- tests/test_kinesis/test_kinesis_boto3.py
- tests/test_kinesis/test_kinesis_encryption.py
- tests/test_kinesis/test_kinesis_monitoring.py
Fixes #5889 
Boto3 introduced the StreamARN-parameter in all methods at some points - I believe only recently. We now support this parameter as well.
> Kinesis - support Stream ARNs across all methods

- moto/iam/models.py
- tests/test_iam/test_iam_groups.py
> IAM: add_user_to_group() should be idempotent

- .github/workflows/data-update_ec2-instance-types.yml
This will pull the latest EC2 instance types, and create a PR with all the changes
> Admin: Auto update EC2 instance types

- .github/workflows/data-update_ec2-instance-types.yml
> Admin: Manually update EC2 instance types

- moto/glue/models.py
- tests/test_glue/test_datacatalog.py
when calling from spark sdk throw the following error :
"Unable to parse date : 2023-02-08T13:36:29.833461"
> [Glue] fix return dates error on sdk .

- moto/ec2/resources/instance_types.json
default branch (https://github.com/getmoto/moto/tree/master)
<details>
<summary>Details: </summary>
<details>
<summary><em>add path</em></summary>
```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/build/src/bin
```
</details>
<details>
<summary><em>pip install boto3</em></summary>
```Shell
Collecting boto3
Downloading boto3-1.26.69-py3-none-any.whl (132 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.7/132.7 kB 4.5 MB/s eta 0:00:00
Collecting s3transfer<0.7.0,>=0.6.0
Downloading s3transfer-0.6.0-py3-none-any.whl (79 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 17.2 MB/s eta 0:00:00
Collecting botocore<1.30.0,>=1.29.69
Downloading botocore-1.29.69-py3-none-any.whl (10.4 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 …
```
> chore: update EC2 Instance Types

- moto/s3/models.py
- tests/test_s3/test_s3_file_handles.py
> S3: Close file-handles of created known FakeKeys explicitly

- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_datacatalog.py
> Glue:get_table_version() - Add VersionId/UpdateTime fields

- moto/iam/models.py
- moto/iam/responses.py
- tests/test_iam/test_iam_password_last_used.py
> IAM: get_user() should return PasswordLastUsed-field if set

- moto/dynamodb/models/table.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB: scan() should respect the Projection-attribute of GSI/LSI's

- moto/apigateway/models.py
- tests/test_apigateway/test_apigateway.py
- Add the capacity to update ("replace" operation) the **policy** attribute in **update_rest_api** endpoint.
- Enhancement and updating the tests.
> Enhancement - Add policy to update rest api for apigateway

- docs/docs/getting_started.rst
> Admin: Improve docs on how to run Moto in CI/CD systems

- moto/kms/responses.py
- tests/test_kms/test_kms_encrypt.py
Fixes #5963 
Follow-up  to #5959
> KMS: re_encrypt() should accept alias

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/glue.rst
- moto/glue/models.py
- moto/glue/responses.py
- moto/glue/utils.py
- tests/test_glue/test_datacatalog.py
> Glue delete_table_version()

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
This pull request solves https://github.com/getmoto/moto/issues/5976
I have simply taken the existing code in the `accessToken` and adapted it here.
> fix: add cognito:groups to idToken

- moto/acmpca/models.py
- moto/ce/models.py
- moto/ce/responses.py
- moto/ecs/models.py
- moto/ecs/responses.py
- moto/efs/exceptions.py
- moto/iam/models.py
- tests/terraformtests/etc/0001-Patch-Hardcode-endpoints-to-local-server.patch
- tests/terraformtests/terraform-tests.failures.txt
- tests/terraformtests/terraform-tests.success.txt
- tests/test_ce/test_ce.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_efs/test_file_system.py
- tests/test_efs/test_lifecycle_config.py
- tests/test_iam/test_iam_groups.py
ACMPCA - create_certificate_authority() now returns the default UsageMode-attribute
CostExplorer - create_cost_category_definition() now returns the correct EffectiveStart-parameter
ECS - create_cluster() and update_cluster() now supports the ClusterSettings and ServiceConnectDefaults-parameters
> Terraform - Update to latest

- moto/ec2/resources/instance_type_offerings/availability-zone-id/ap-northeast-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/ap-southeast-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/ap-southeast-2.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/eu-central-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/eu-north-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/eu-west-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/us-east-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone-id/us-west-2.json
- moto/ec2/resources/instance_type_offerings/availability-zone/ap-northeast-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone/ap-southeast-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone/ap-southeast-2.json
- moto/ec2/resources/instance_type_offerings/availability-zone/eu-central-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone/eu-north-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone/eu-west-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone/us-east-1.json
- moto/ec2/resources/instance_type_offerings/availability-zone/us-west-2.json
- moto/ec2/resources/instance_type_offerings/region/ap-northeast-1.json
- moto/ec2/resources/instance_type_offerings/region/ap-southeast-1.json
- moto/ec2/resources/instance_type_offerings/region/ap-southeast-2.json
- moto/ec2/resources/instance_type_offerings/region/eu-central-1.json
- moto/ec2/resources/instance_type_offerings/region/eu-north-1.json
default branch (https://github.com/getmoto/moto/tree/master)
<details>
<summary>Details: </summary>
<details>
<summary><em>add path</em></summary>
```Shell
/home/runner/work/_actions/technote-space/create-pr-action/v2/node_modules/npm-check-updates/build/src/bin
```
</details>
<details>
<summary><em>pip install boto3</em></summary>
```Shell
Requirement already satisfied: boto3 in /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages (1.26.79)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages (from boto3) (0.6.0)
Requirement already satisfied: …
```
> chore: update EC2 Instance Offerings

- .github/workflows/data-update_ec2-instance-offerings.yml
- .github/workflows/data-update_ec2-instance-types.yml
- .github/workflows/data-update_ssm-default-amis.yml
- .github/workflows/data-update_ssm-default-parameters.yml
- tests/test_acm/test_acm.py
- tests/test_cloudwatch/test_cloudwatch_dashboards.py
- tests/test_polly/test_polly.py
- tests/test_sqs/test_sqs.py
- tests/test_ssm/test_ssm_boto3.py
This PR:
- Spread out the timing of these actions
- Removes some unnecessary config
- makes the branch-name unique, to prevent conflicts
> Admin: Improve automatic resource updates

- moto/kms/models.py
- moto/kms/responses.py
- tests/test_kms/test_kms_boto3.py
filter kms alias list by key_id; make alias store consistently use key_id; write unit test for list_aliases with key_id parameter
Fixes #5990
> KMS - implement KeyId parameter for ListAliases

- moto/s3/models.py
- moto/s3/responses.py
- moto/s3/utils.py
> S3 - Add Glacier IR

- moto/dynamodb/parsing/validators.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
> DynamoDB: Ensure first argument to list_append() exists

- moto/cloudformation/parsing.py
- tests/test_cloudformation/fixtures/custom_lambda.py
- tests/test_cloudformation/test_cloudformation_custom_resources.py
> CloudFormation: Error when referencing unknown resource in FN:GetAtt

- tests/test_dax/test_dax.py
- tests/test_dax/test_server.py
- Removing sure: #6035
- Combined some tests using parametrize
- Small cosmetic changes to make tests more consistent and readable
> Techdebt: Sure - Dax

- moto/core/responses.py
- moto/core/utils.py
Attempt to fix #6033 
This is my first time trying to contribute, so please be indulgent :)
> fix:params not sorted properly when tags are present

- docs/docs/contributing/development_tips/tests.rst
> Techdebt: Sure - Documentation

- scripts/template/test/test_server.py.j2
- scripts/template/test/test_service.py.j2
> Techdebt: Sure - Scripts (test templates)

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
> CognitoIDP: ID-token has different key for username

- moto/ec2/models/amis.py
- moto/utilities/utils.py
> fix: add typing to AMIS

- moto/awslambda/models.py
- moto/settings.py
- setup.cfg
Closes #5180 
Also increases the minimum version for the Docker-dependency to 3.0.0 (released Feb 2018)
> AWSLambda: Ability to customize Dockers' data dir

- moto/iot/models.py
- moto/iot/responses.py
- tests/test_iot/test_iot_certificates.py
> IOT: delete_certificate() now supports the forceDelete-parameter

- moto/batch/models.py
`AWS_BATCH_JOB_MAIN_NODE_PRIVATE_IPV4_ADDRESS` is empty when a network is set using `MOTO_DOCKER_NETWORK_NAME`. This checks if the network is present in the container networks and uses that IP address if present. Custom networks are required to use container DNS names for multi node networking.
Test plan:
```
pytest tests/test_batch/test_batch_jobs
MOTO_DOCKER_NETWORK_NAME=foo pytest tests/test_batch/test_batch_jobs
```
This was discovered when adding distributed tests using moto in https://github.com/pytorch/torchx/pull/710 Those tests now pass.
> batch: use specified network IP address

- moto/rds/models.py
- tests/test_rds/test_rds_clusters.py
> RDS: describe_db_clusters() now accepts an ARN as identifier

- moto/ec2/resources/amis.json
> EC2: Remove duplicate AMI

- moto/secretsmanager/models.py
- moto/secretsmanager/utils.py
- tests/test_secretsmanager/test_secretsmanager.py
> SecretsManager - deal with partial ARNs

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/opensearch.rst
- moto/__init__.py
- moto/es/urls.py
- moto/iam/models.py
- moto/opensearch/__init__.py
- moto/opensearch/data.py
- moto/opensearch/exceptions.py
- moto/opensearch/models.py
- moto/opensearch/responses.py
- moto/opensearch/urls.py
- scripts/update_backend_index.py
- setup.cfg
- tests/terraformtests/terraform-tests.success.txt
- tests/test_opensearch/test_domain_tags.py
- tests/test_opensearch/test_opensearch.py
> Feature: OpenSearch

- other_langs/tests_java/pom.xml
Not sure if this is the best (or only) solution, but the Java dependabot PRs were gumming up the works, so I reset the base branch on those PRs so we could test the changes in combination (on this branch).  This seemed low risk, but was a bit of a manual process.  We may want to explore some of the dependabot configuration options to see if there's a better way going forward.
> Combined Java Dependabot Updates

- moto/ecr/models.py
- moto/ecr/responses.py
- tests/test_ecr/test_ecr_boto3.py
Add support for the optional imageManifestMedia, parameter as detailed in https://github.com/getmoto/moto/issues/6135
> ecr.put_image - Support imageManifestMediaType parameter (issue 6135)

- IMPLEMENTATION_COVERAGE.md
- moto/ec2/responses/launch_templates.py
- tests/test_ec2/test_launch_templates.py
<https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetLaunchTemplateData.html>
> EC2: Implement GetLaunchTemplateData

- moto/apigateway/models.py
- tests/test_apigateway/test_apigateway.py
> APIGateway: Allow semicolon in path

- .github/workflows/build.yml
- .github/workflows/test_terraform.yml
See https://github.com/getmoto/moto/pull/6145#issuecomment-1486381612
> Admin: Skip long-running tests for small Java-updates

- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_stack_parsing.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ToJsonString.html
> CloudFormation: Implement Fn::ToJsonString

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/athena.rst
- docs/docs/services/rds-data.rst
- moto/__init__.py
- moto/athena/models.py
- moto/backend_index.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
- moto/rdsdata/__init__.py
- moto/rdsdata/models.py
- moto/rdsdata/responses.py
- moto/rdsdata/urls.py
- setup.cfg
- tests/test_rdsdata/test_rdsdata.py
> Feature: RDS Data

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/lakeformation.rst
- moto/__init__.py
- moto/backend_index.py
- moto/iam/models.py
- moto/lakeformation/__init__.py
- moto/lakeformation/exceptions.py
- moto/lakeformation/models.py
- moto/lakeformation/responses.py
- moto/lakeformation/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_lakeformation/test_lakeformation.py
> Feature: LakeFormation

- moto/kinesis/models.py
- moto/logs/models.py
- tests/test_logs/test_integration.py
> Logs: put_subscription_filter() now supports KinesisStream destinations

- moto/s3/models.py
- tests/test_s3/test_s3.py
Fixes #6076 
Closes #6077 
Test was verified against AWS.
> S3: Fixes the behaviour where/when S3 returns the `DeleteMarker` and `VersionId` headers

- docs/docs/services/config.rst
- moto/config/exceptions.py
- moto/config/models.py
- moto/config/responses.py
- tests/test_config/test_config.py
- Added AWS Config Retention Configuration support
- Also added S3 KMS Key ARN support for the Delivery Channel
> Added support for AWS Config Retention Configuration

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/scheduler.rst
- moto/__init__.py
- moto/backend_index.py
- moto/scheduler/__init__.py
- moto/scheduler/exceptions.py
- moto/scheduler/models.py
- moto/scheduler/responses.py
- moto/scheduler/urls.py
- setup.cfg
- tests/terraformtests/terraform-tests.success.txt
- tests/test_scheduler/test_schedule_groups.py
- tests/test_scheduler/test_scheduler.py
- tests/test_scheduler/test_scheduler_tags.py
- tests/test_scheduler/test_server.py
> Service: Scheduler

- moto/ses/template.py
- tests/test_ses/test_templating.py
> SES - allow single curly brace in template

- moto/batch_simple/README.md
- moto/batch_simple/models.py
- tests/test_batch_simple/test_batch_jobs.py
Potential solution for https://github.com/getmoto/moto/issues/5168
> BatchSimple: jobs can fail or succeed

- moto/athena/models.py
- tests/test_athena/test_athena.py
> Athena - WorkGroup configuration should be a dictionary, not a string

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/dynamodb.rst
- moto/dynamodb/models/__init__.py
- moto/dynamodb/models/dynamo_type.py
- moto/dynamodb/parsing/partiql.py
- moto/dynamodb/responses.py
- moto/s3/select_object_content.py
- setup.cfg
- tests/test_dynamodb/test_dynamodb_statements.py
> DynamoDB: Initial support for execute_statement et. al.

- moto/ecs/models.py
- tests/test_ecs/test_ecs_boto3.py
> ECS: Fix a bug where a cluster cannot be tagged after creation

- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_boto3.py
> SSM: Allow filtering by existence of tag-name

- moto/settings.py
Made the retrieve S3_UPLOAD_PART_MIN_SIZE value configurable by retrieving it from an env variable
> retrieve S3_UPLOAD_PART_MIN_SIZE from env variable

- moto/sns/models.py
- moto/sns/responses.py
- tests/test_sns/test_publish_batch.py
- tests/test_sns/test_publishing_boto3.py
> Forward SNS MessageDeduplicationId to SQS queues

- moto/ec2/exceptions.py
- moto/ec2/models/amis.py
- moto/ec2/resources/amis.json
- moto/ec2/responses/amis.py
- tests/test_ec2/test_amis.py
Resolves https://github.com/getmoto/moto/issues/6239
> Fix ami attributes

- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
Closes https://github.com/getmoto/moto/issues/6282
> EC2: validate pagination parameters

- moto/rds/models.py
- tests/test_rds/test_rds_export_tasks.py
- Add new field `SouceType`.
- Add unittest for both `SourceType (CLUSTER | SNAPSHOT)`.
closes #6277
> RDS: Add `SourceType` field for the response of `start_export_task`

- IMPLEMENTATION_COVERAGE.md
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_transform.py
Implements `create_transform_job`,  `describe_transform_job`, and `list_transform_jobs`
> Sagemaker: Add transform jobs

- moto/ecs/models.py
- moto/s3/responses.py
- tests/test_ecs/test_ecs_boto3.py
Closes https://github.com/getmoto/moto/issues/6283
> ECS: allow ecs service to transition to arbitrary running task count

- moto/cloudformation/parsing.py
- moto/sns/models.py
- tests/test_sns/test_sns_cloudformation.py
Fixes #6311 
Also standardizes/normalizes resource deletion in the CF logic:
- call `resource.delete()` if the method exists, otherwise
- call `backend.delete_from_cloudformation_json` if the method exists
This logic is now the same for resources that are removed from a stack, and for resources in stacks that are deleted.
Deletion of a Topic using CloudFormation is also simplified. Because `sns_backend.delete_topic` already removes any subscriptions attached to that topic, these do not have to be removed manually.
> SNS: Allow Topic without properties to be deleted using CF

- moto/s3/responses.py
- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
Closes https://github.com/getmoto/moto/issues/6285
> Secrets: add NextRotationDate and LastRotatedDate to secrets

- moto/ec2/exceptions.py
- moto/ec2/models/route_tables.py
- moto/ec2/responses/route_tables.py
- tests/test_ec2/test_route_tables.py
Closes https://github.com/getmoto/moto/issues/6301
> EC2: vpc endpoint as a route target

- moto/iam/responses.py
- tests/test_iam/test_iam_groups.py
Closes https://github.com/getmoto/moto/issues/6320
> IAM: missing CreateDate from get_group response

- moto/core/responses.py
- tests/test_core/test_responses.py
Closes https://github.com/getmoto/moto/issues/6321
> Core: add date to response metadata

- moto/ec2/exceptions.py
- moto/ec2/models/spot_requests.py
- moto/ec2/responses/spot_fleets.py
- tests/test_ec2/test_spot_fleet.py
> Add `Tags` filed for the response of `describe_spot_fleet_requests`

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/comprehend.rst
- docs/docs/services/sagemaker.rst
- moto/comprehend/exceptions.py
- moto/comprehend/models.py
- moto/comprehend/responses.py
- tests/test_comprehend/test_comprehend.py
Closes https://github.com/getmoto/moto/issues/6268
> Comprehend: implement canned responses for detect_* functions

- docs/docs/services/appsync.rst
- moto/appsync/exceptions.py
- moto/appsync/models.py
- moto/appsync/responses.py
- moto/appsync/urls.py
- tests/test_appsync/test_appsync_schema.py
This PR implements AppSync get_introspection_schema.
> Appsync: Implement get_introspection_schema

- moto/ecr/exceptions.py
- moto/ecr/models.py
- tests/test_ecr/test_ecr_boto3.py
I hit this error running some boto code and wanted to handle it in a unit test but then noticed that moto didn't implement it so I thought I'd give it a shot.
> ECR: Implement ImageAlreadyExistsException

- setup.cfg
- tests/test_s3/test_s3_select.py
> S3 Select: Support nested from-clauses

- moto/rds/models.py
- moto/redshift/models.py
> RDS, Redshift: Ensure creation-times are UTC

- moto/s3/models.py
- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_maintenance_windows.py
> SSM: Support tags for Maintenance Windows

- tests/test_acm/test_acm.py
- tests/test_acmpca/test_acmpca.py
See #6035 
Below a cheat sheet of the regexes used to automatically find/replace some of these constructs.
If there are two find-statements, the first one is used for single-line statements -the second regex takes whitespace into account.
---------------
F `(\S+)\.should.equal\((.*)\)`
F `(\S+)\.should.equal\(\s+(\S+)\s+\)`
R `assert $1 == $2`
F `(\S+)\.should.not.equal\((.*)\)`
R `assert $1 != $2`
F `(\S+.+)\.should.contain\((.*)\)`
F `(\S+.+)\.should.contain\(\s+(".+")\s+\)`
R `assert $2 in $1`
F `(\S+.+)\.shouldnt.contain\((.*)\)`
F `(\S+.+)\.should.not.contain\((.*)\)`
R `assert $2 not in $1`
F `(\S+)\.should.have.length_of\((.*)\)`
R `assert len($1) == $2`
F `(\S+)\.should.have.length_of\(\s+(\d+)\s+\)`
R `assert len($1) == $2`
F `(\S+)\.shouldnt.have.key\((.*)\)`
R `assert $2 not in …
> Techdebt: Replace sure with regular asserts in ACM tests

- tests/test_amp/test_amp_logging_config.py
- tests/test_amp/test_amp_rulegroupnamespaces.py
- tests/test_amp/test_amp_workspaces.py
> Techdebt: Replace sure with regular asserts in AMP tests

- tests/test_apigateway/test_apigateway.py
- tests/test_apigateway/test_apigateway_cloudformation.py
- tests/test_apigateway/test_apigateway_deployments.py
- tests/test_apigateway/test_apigateway_export.py
- tests/test_apigateway/test_apigateway_gatewayresponses.py
- tests/test_apigateway/test_apigateway_importrestapi.py
- tests/test_apigateway/test_apigateway_integration.py
- tests/test_apigateway/test_apigateway_putrestapi.py
- tests/test_apigateway/test_apigateway_stage.py
- tests/test_apigateway/test_apigateway_validators.py
- tests/test_apigateway/test_apigateway_vpclink.py
- tests/test_apigateway/test_server.py
> Techdebt: Replace sure with regular asserts in APIGateway tests

- moto/ec2/models/flow_logs.py
- tests/test_ec2/test_flow_logs.py
See title, issue and commit for list of changes and their justifications
> EC2: allow creation multiple flow logs on same resource id

- moto/s3/responses.py
- tests/test_s3/test_server.py
> S3: Return CORS headers for GET/PUT requests

- tests/test_applicationautoscaling/test_applicationautoscaling.py
- tests/test_applicationautoscaling/test_validation.py
> Techdebt: Replace sure with regular asserts in ApplicationAutoscaling tests

- moto/ec2/models/elastic_block_store.py
- moto/ec2/responses/elastic_block_store.py
- tests/test_ec2/test_elastic_block_store.py
I would like to add `Throughput` to create_volume and describe_volumes.
> EC2: create_volume(): support Throughput-parameter

- tests/test_apigatewayv2/test_apigatewayv2.py
- tests/test_apigatewayv2/test_apigatewayv2_authorizers.py
- tests/test_apigatewayv2/test_apigatewayv2_domains.py
- tests/test_apigatewayv2/test_apigatewayv2_integrationresponses.py
- tests/test_apigatewayv2/test_apigatewayv2_integrations.py
- tests/test_apigatewayv2/test_apigatewayv2_mappings.py
- tests/test_apigatewayv2/test_apigatewayv2_models.py
- tests/test_apigatewayv2/test_apigatewayv2_reimport.py
- tests/test_apigatewayv2/test_apigatewayv2_routes.py
- tests/test_apigatewayv2/test_apigatewayv2_tags.py
- tests/test_apigatewayv2/test_apigatewayv2_vpclinks.py
- tests/test_apigatewayv2/test_server.py
> Techdebt: Replace sure with regular asserts in APIGatewayV2 tests

- tests/test_appsync/test_appsync.py
- tests/test_appsync/test_appsync_apikeys.py
- tests/test_appsync/test_appsync_schema.py
- tests/test_appsync/test_appsync_tags.py
- tests/test_appsync/test_server.py
> Techdebt: Replace sure with regular asserts in AppSync tests

- tests/test_athena/test_athena.py
- tests/test_athena/test_athena_server_api.py
> Techdebt: Replace sure with regular asserts in Athena tests

- tests/test_autoscaling/test_autoscaling.py
- tests/test_autoscaling/test_autoscaling_cloudformation.py
- tests/test_autoscaling/test_autoscaling_groups.py
- tests/test_autoscaling/test_autoscaling_metrics.py
- tests/test_autoscaling/test_autoscaling_scheduledactions.py
- tests/test_autoscaling/test_autoscaling_tags.py
- tests/test_autoscaling/test_elb.py
- tests/test_autoscaling/test_elbv2.py
- tests/test_autoscaling/test_launch_configurations.py
- tests/test_autoscaling/test_policies.py
- tests/test_autoscaling/test_server.py
> Techdebt: Replace sure with regular asserts in Autoscaling

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/appconfig.rst
- moto/__init__.py
- moto/appconfig/__init__.py
- moto/appconfig/exceptions.py
- moto/appconfig/models.py
- moto/appconfig/responses.py
- moto/appconfig/urls.py
- moto/backend_index.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_appconfig/test_appconfig_applications.py
- tests/test_appconfig/test_appconfig_config_profiles.py
- tests/test_appconfig/test_appconfig_hosted_config_versions.py
Fixes #6372 
Includes methods:
- create_application()
- create_configuration_profile()
- create_hosted_configuration_version()
- delete_application()
- delete_configuration_profile()
- delete_hosted_configuration_version()
- get_application()
- get_configuration_profile()
- get_hosted_configuration_version()
- list_configuration_profiles()
- tag_resource()
- untag_resource()
- update_application()
- update_configuration_profile()
> Feature: AppConfig

- moto/codebuild/responses.py
- tests/test_codebuild/test_codebuild.py
> Codebuild - create_project(): Loosen serviceRole validation

- tests/test_batch/test_batch.py
- tests/test_batch/test_batch_cloudformation.py
- tests/test_batch/test_batch_compute_envs.py
- tests/test_batch/test_batch_job_queue.py
- tests/test_batch/test_batch_jobs.py
- tests/test_batch/test_batch_scheduling_policy.py
- tests/test_batch/test_batch_tags_job_definition.py
- tests/test_batch/test_batch_tags_job_queue.py
- tests/test_batch/test_batch_tags_scheduling_policy.py
- tests/test_batch/test_batch_task_definition.py
- tests/test_batch/test_server.py
- tests/test_batch_simple/test_batch_cloudformation.py
- tests/test_batch_simple/test_batch_compute_envs.py
> Techdebt: Replace sure with regular asserts in Batch

- moto/iam/models.py
- tests/test_iam/test_iam.py
Closes https://github.com/getmoto/moto/issues/6404
> IAM: additional role on instance profile validation

- Dockerfile
See https://github.com/getmoto/moto/issues/6423
> Add cURL install to Dockerfile

- IMPLEMENTATION_COVERAGE.md
- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_patch_baseline.py
This pr adds the operations corresponding to the SSM Patch Baseline resource.
> add patch baseline operations

- moto/config/models.py
- tests/test_config/test_config.py
- Added support for AWS Config resource type exclusions
- Updated the data model to account for the newest changes to boto for AWS Config recorders
> AWS Config support for Resource Type Exclusions

- moto/ssm/exceptions.py
- moto/ssm/models.py
- moto/ssm/responses.py
- tests/test_ssm/test_ssm_boto3.py
Resolves https://github.com/getmoto/moto/issues/6416
> SSM: broken ssm param update, updated error message

- tests/test_dax/test_dax.py
- tests/test_dms/test_dms.py
> Techdebt: Replace sure with regular asserts for DAX+DMS

- moto/stepfunctions/exceptions.py
- moto/stepfunctions/models.py
- tests/test_stepfunctions/test_stepfunctions.py
Closes https://github.com/getmoto/moto/issues/6438
> StepFunctions: validation according to api docs

- moto/dynamodb/responses.py
- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_dynamodb_table_without_range_key.py
Closes https://github.com/getmoto/moto/issues/6441
> DynamoDB: correct no table error

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/apigatewayv2.rst
- moto/apigatewayv2/exceptions.py
- moto/apigatewayv2/models.py
- moto/apigatewayv2/responses.py
- moto/apigatewayv2/urls.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_apigatewayv2/test_apigatewayv2_stages.py
- create_stage()
- delete_stage()
- get_stage()
- get_stages()
> APIGatewayV2: Stages

- tests/test_budgets/test_budgets.py
- tests/test_budgets/test_notifications.py
- tests/test_budgets/test_server.py
> Techdebt: Replace sure with regular asserts in Budgets

- tests/test_databrew/test_databrew_datasets.py
- tests/test_databrew/test_databrew_jobs.py
- tests/test_databrew/test_databrew_recipes.py
- tests/test_databrew/test_databrew_rulesets.py
> Techdebt: Replace sure with regular asserts in DataBrew

- moto/batch/models.py
- tests/test_batch/test_batch_compute_envs.py
> Batch: create_compute_environment() now validates instanceRole and minvCpu

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
Fixes #6461 
FYI @rafcio19 - do you see any issues with this?
> SecretsManager: delete_secret should throw an error for 0 day Recovery

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/route53.rst
- moto/route53/responses.py
- moto/route53/urls.py
- tests/test_route53/test_route53_healthchecks.py
This PR adds support for GetHealthCheckStatus endpoint in Route53
<https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetHealthCheckStatus.html>
> Route53: Implement GetHealthCheckStatus

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- docs/docs/contributing/installation.rst
Greetings!
I've added a `devcontainer.json` to aide in the development of Moto.
Let me know if you have any questions or feedback!
> Add a Devcontainer

- tests/test_efs/test_access_point_tagging.py
- tests/test_efs/test_access_points.py
- tests/test_efs/test_file_system.py
- tests/test_efs/test_filesystem_tagging.py
- tests/test_efs/test_lifecycle_config.py
- tests/test_efs/test_mount_target.py
- tests/test_efs/test_mount_target_security_groups.py
> Techdebt: Replace sure with regular asserts in EFS

- tests/helpers.py
- tests/test_cloudfront/test_cloudfront.py
- tests/test_cloudfront/test_cloudfront_dist_tags.py
- tests/test_cloudfront/test_cloudfront_distributions.py
- tests/test_cloudfront/test_cloudfront_invalidation.py
> Techdebt: Replace sure with regular asserts in CloudFront

- tests/test_greengrass/test_greengrass_core.py
- tests/test_greengrass/test_greengrass_deployment.py
- tests/test_greengrass/test_greengrass_device.py
- tests/test_greengrass/test_greengrass_functions.py
- tests/test_greengrass/test_greengrass_groups.py
- tests/test_greengrass/test_greengrass_resource.py
- tests/test_greengrass/test_greengrass_subscriptions.py
> Techdebt: Replace sure with regular assertions in GreenGrass

- tests/test_cloudtrail/test_cloudtrail.py
- tests/test_cloudtrail/test_cloudtrail_eventselectors.py
- tests/test_cloudtrail/test_cloudtrail_tags.py
- tests/test_cloudtrail/test_server.py
> Techdebt: Replace sure with regular asserts in CloudTrail

- moto/route53/responses.py
- tests/test_route53/test_route53.py
> Route53: create_hosted_zone() now returns the Location

- tests/test_cloudwatch/test_cloudwatch_alarms.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
- tests/test_cloudwatch/test_cloudwatch_dashboards.py
- tests/test_cloudwatch/test_cloudwatch_tags.py
> Techdebt: Replace sure with regular assertions in CloudWatch

- tests/test_opensearch/test_opensearch.py
> Techdebt: Replace sure with regular asserts in OpenSearch

- tests/test_cognitoidentity/test_cognitoidentity.py
- tests/test_cognitoidentity/test_server.py
- tests/test_cognitoidp/test_cognitoidp.py
- tests/test_cognitoidp/test_cognitoidp_exceptions.py
- tests/test_cognitoidp/test_cognitoidp_replay.py
- tests/test_cognitoidp/test_server.py
> Techdebt: Replace sure with regular asserts in Cognito

- tests/test_textract/test_server.py
- tests/test_textract/test_textract.py
> Techdebt: Replace sure with regular assertions in Textract

- tests/test_comprehend/test_comprehend.py
> Techdebt: Replace sure with regular assertions in Comprehend

- tests/test_config/test_config.py
> Techdebt: Replace sure with regular assertions in Config

- moto/iotdata/responses.py
- tests/test_iotdata/test_iotdata.py
> IOTData: publish() should be able to handle non-Unicode bytes

- tests/test_datapipeline/test_datapipeline.py
- tests/test_datapipeline/test_datapipeline_cloudformation.py
- tests/test_datapipeline/test_server.py
> Techdebt: Replace sure with regular assertions in DataPipeline

- tests/test_datasync/test_datasync.py
> Techdebt: Replace sure with regular assertions in DataSync

- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/exceptions/test_key_length_exceptions.py
- tests/test_dynamodb/models/test_key_condition_expression_parser.py
- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_dynamodb_batch_get_item.py
- tests/test_dynamodb/test_dynamodb_cloudformation.py
- tests/test_dynamodb/test_dynamodb_condition_expressions.py
- tests/test_dynamodb/test_dynamodb_consumedcapacity.py
- tests/test_dynamodb/test_dynamodb_create_table.py
- tests/test_dynamodb/test_dynamodb_executor.py
- tests/test_dynamodb/test_dynamodb_expression_tokenizer.py
- tests/test_dynamodb/test_dynamodb_expressions.py
- tests/test_dynamodb/test_dynamodb_statements.py
- tests/test_dynamodb/test_dynamodb_table_with_range_key.py
- tests/test_dynamodb/test_dynamodb_table_without_range_key.py
- tests/test_dynamodb/test_dynamodb_update_expressions.py
- tests/test_dynamodb/test_dynamodb_update_table.py
- tests/test_dynamodb/test_server.py
> Techdebt: Replace sure with regular assertions in DynamoDB

- moto/rds/exceptions.py
- moto/rds/models.py
- tests/test_rds/test_rds.py
- tests/test_rds/test_rds_cloudformation.py
Closes https://github.com/getmoto/moto/issues/6511
> RDS: db instance identifier validation

- moto/logs/models.py
- moto/logs/responses.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_logs/test_logs.py
- Support for Destinations
- added support for api `GetDestination`
- added support for api `PutDestination`
- added support for api `DeleteDestination`
- added support for api `DescribeDestinations`
- added support for api `PutDestinationPolicy`
https://github.com/getmoto/moto/pull/4659
> Logs: added support for destinations mocking

- tests/test_ebs/test_ebs.py
> Techdebt: Replace sure with regular assertions in EBS

- tests/test_dynamodb_v20111205/test_server.py
- tests/test_dynamodb_v20111205/test_servermode.py
> Techdebt: Replace sure with regular assertions in DynamoDB v20111205

- tests/test_ec2/test_elastic_block_store.py
- tests/test_ec2/test_elastic_ip_addresses.py
- tests/test_ec2/test_general.py
- tests/test_ec2/test_instance_types.py
- tests/test_ec2/test_network_acls.py
- tests/test_ec2/test_prefix_lists.py
- tests/test_ec2/test_route_tables.py
- tests/test_ecs/test_ecs_account_settings.py
- tests/test_ecs/test_ecs_boto3.py
- tests/test_ecs/test_ecs_capacity_provider.py
- tests/test_ecs/test_ecs_cloudformation.py
- tests/test_ecs/test_ecs_efs.py
- tests/test_ecs/test_ecs_task_def_tags.py
- tests/test_ecs/test_ecs_tasksets.py
See #6035 
Also fixes a few assertions that I missed in EC2 after #6525
> Techdebt: Replace sure with regular assertions in ECS

- moto/iot/models.py
- tests/test_iot/test_iot_search.py
> IOT: search_index() now returns the connectivity-attribute

- tests/test_eks/test_eks.py
- tests/test_eks/test_eks_ec2.py
- tests/test_eks/test_server.py
> Techdebt: Replace sure with regular assertions in EKS

- moto/organizations/models.py
See <https://docs.aws.amazon.com/organizations/latest/userguide/orgs_integrate_services_list.html>
Closes https://github.com/localstack/localstack/issues/8559
> Organizations: Update trusted service principals

- tests/test_elasticache/test_elasticache.py
- tests/test_elasticache/test_server.py
> Techdebt: Replace sure with regular assertions in ElastiCache

- tests/test_elasticbeanstalk/test_eb.py
> Techdebt: Replace sure with regular assertions in ElasticBeanstalk

- tests/test_elastictranscoder/test_elastictranscoder.py
- tests/test_elastictranscoder/test_server.py
> Techdebt: Replace sure with regular assertions in ElasticTranscoder

- tests/test_elb/test_elb.py
- tests/test_elb/test_elb_availabilityzones.py
- tests/test_elb/test_elb_cloudformation.py
- tests/test_elb/test_elb_policies.py
- tests/test_elb/test_elb_subnets.py
- tests/test_elb/test_server.py
> Techdebt: Replace sure with regular assertions in ELB

- tests/test_elbv2/test_elbv2.py
- tests/test_elbv2/test_elbv2_cloudformation.py
- tests/test_elbv2/test_elbv2_integration.py
- tests/test_elbv2/test_elbv2_listener_rule_tags.py
- tests/test_elbv2/test_elbv2_listener_rules.py
- tests/test_elbv2/test_elbv2_listener_tags.py
- tests/test_elbv2/test_elbv2_set_subnets.py
- tests/test_elbv2/test_elbv2_target_groups.py
- tests/test_elbv2/test_server.py
> Techdebt: Replace sure with regular assertions in ELBv2

- tests/test_emr/test_emr_boto3.py
- tests/test_emr/test_emr_integration.py
- tests/test_emr/test_server.py
> Techdebt: Replace sure with regular assertions in EMR

- tests/test_es/test_es.py
- tests/test_es/test_server.py
> Techdebt: Replace sure with regular assertions in ElasticSearch

- tests/test_events/test_event_pattern.py
- tests/test_events/test_events.py
- tests/test_events/test_events_cloudformation.py
- tests/test_events/test_events_integration.py
- tests/test_events/test_events_lambdatriggers_integration.py
> Techdebt: Replace sure with regular assertions in Events

- tests/test_firehose/test_firehose_destination_types.py
- tests/test_firehose/test_firehose_encryption.py
- tests/test_firehose/test_firehose_put.py
- tests/test_firehose/test_http_destinations.py
> Techdebt: Replace sure with regular assertions in Firehose

- tests/test_glacier/test_glacier_archives.py
- tests/test_glacier/test_glacier_jobs.py
- tests/test_glacier/test_glacier_vaults.py
- tests/test_glacier/test_server.py
> Techdebt: Replace sure with regular assertions in Glacier

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_clusters.py
> RDS: create_db_cluster() now supports the VpcSecurityGroupIds-parameter

- tests/test_glue/test_datacatalog.py
- tests/test_glue/test_glue.py
- tests/test_glue/test_glue_job_runs.py
- tests/test_glue/test_partition_filter.py
- tests/test_glue/test_schema_registry.py
> Techdebt: Replace sure with regular assertions in Glue

- tests/test_guardduty/test_guardduty.py
- tests/test_guardduty/test_guardduty_filters.py
- tests/test_guardduty/test_guardduty_organization.py
- tests/test_guardduty/test_server.py
> Techdebt: Replace sure with regular assertions in GuardDuty

- tests/test_iot/test_iot.py
- tests/test_iot/test_iot_ca_certificates.py
- tests/test_iot/test_iot_certificates.py
- tests/test_iot/test_iot_deprecate_thing_type.py
- tests/test_iot/test_iot_domain_configuration.py
- tests/test_iot/test_iot_job_executions.py
- tests/test_iot/test_iot_jobs.py
- tests/test_iot/test_iot_policies.py
- tests/test_iot/test_iot_search.py
- tests/test_iot/test_iot_thing_groups.py
- tests/test_iot/test_iot_thing_types.py
- tests/test_iot/test_iot_things.py
- tests/test_iot/test_iot_topic_rules.py
- tests/test_iot/test_server.py
> Techdebt: Replace sure with regular assertions in IOT

- moto/ec2/models/vpc_service_configuration.py
- moto/ec2/models/vpcs.py
- tests/test_ec2/test_vpc_service_configuration.py
> EC2: describe_vpc_endpoint_services() now returns user-defined ones

- tests/test_kinesis/test_kinesis.py
- tests/test_kinesis/test_kinesis_boto3.py
- tests/test_kinesis/test_kinesis_cloudformation.py
- tests/test_kinesis/test_kinesis_encryption.py
- tests/test_kinesis/test_kinesis_monitoring.py
- tests/test_kinesis/test_kinesis_stream_consumers.py
- tests/test_kinesis/test_kinesis_stream_limits.py
- tests/test_kinesis/test_server.py
> Techdebt: Replace sure with regular assertions in Kinesis

- tests/test_kinesisvideo/test_kinesisvideo.py
- tests/test_kinesisvideo/test_server.py
- tests/test_kinesisvideoarchivedmedia/test_kinesisvideoarchivedmedia.py
- tests/test_kinesisvideoarchivedmedia/test_server.py
> Techdebt: Replace sure with regular assertions in KinesisVideo

- tests/test_kms/test_kms_boto3.py
- tests/test_kms/test_kms_encrypt.py
- tests/test_kms/test_kms_grants.py
- tests/test_kms/test_kms_policy_enforcement.py
- tests/test_kms/test_server.py
- tests/test_kms/test_utils.py
> Techdebt: Replace sure with regular assertions in KMS

- tests/test_sdb/test_sdb_attributes.py
- tests/test_sdb/test_sdb_domains.py
- tests/test_sdb/test_server.py
Thought I would help out with the edits in the tests/test_s* directories.
> Techdebt: Replace sure with regular assertions in SDB

- tests/test_s3control/test_s3control.py
- tests/test_s3control/test_s3control_access_points.py
- tests/test_s3control/test_s3control_accesspoint_policy.py
- tests/test_s3control/test_s3control_config_integration.py
- tests/test_s3control/test_s3control_s3.py
> Techdebt: Replace sure with regular assertions in s3control

- tests/test_s3bucket_path/test_s3bucket_path_utils.py
- tests/test_s3bucket_path/test_server.py
> Techdebt: Replace sure with regular assertions in s3bucket_path

- tests/test_servicequotas/test_servicequotas.py
> Techdebt: Replace sure with regular assertions in servicequotas

- moto/kms/models.py
> Fix typo of `__ensure_valid_signing_augorithm`

- tests/test_s3/test_multiple_accounts_server.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_acl.py
- tests/test_s3/test_s3_auth.py
- tests/test_s3/test_s3_bucket_policy.py
- tests/test_s3/test_s3_classdecorator.py
- tests/test_s3/test_s3_cloudformation.py
- tests/test_s3/test_s3_config.py
- tests/test_s3/test_s3_copyobject.py
- tests/test_s3/test_s3_custom_endpoint.py
- tests/test_s3/test_s3_encryption.py
- tests/test_s3/test_s3_file_handles.py
- tests/test_s3/test_s3_lambda_integration.py
- tests/test_s3/test_s3_lifecycle.py
- tests/test_s3/test_s3_lock.py
- tests/test_s3/test_s3_logging.py
- tests/test_s3/test_s3_metadata.py
- tests/test_s3/test_s3_multipart.py
- tests/test_s3/test_s3_object_attributes.py
- tests/test_s3/test_s3_ownership.py
- tests/test_s3/test_s3_replication.py
- tests/test_s3/test_s3_select.py
- tests/test_s3/test_s3_storageclass.py
- tests/test_s3/test_s3_tagging.py
- tests/test_s3/test_s3_utils.py
- tests/test_s3/test_server.py
> Techdebt: Replace sure with regular assertions in S3

- moto/kms/models.py
- tests/test_kms/test_kms_boto3.py
Add a signing algorithm `SM2DSA`.
closes #6608
> Add `SM2DSA` signing algorithms

- tests/test_ssoadmin/test_server.py
- tests/test_ssoadmin/test_ssoadmin.py
> Techdebt: Replace sure with regular assertions in ssoadmin

- tests/test_servicediscovery/test_server.py
- tests/test_servicediscovery/test_servicediscovery_httpnamespaces.py
- tests/test_servicediscovery/test_servicediscovery_operations.py
- tests/test_servicediscovery/test_servicediscovery_service.py
- tests/test_servicediscovery/test_servicediscovery_tags.py
> Techdebt: Replace sure with regular assertions in servicediscovery

- tests/test_sagemaker/test_sagemaker_cloudformation.py
- tests/test_sagemaker/test_sagemaker_endpoint.py
- tests/test_sagemaker/test_sagemaker_model_packages.py
- tests/test_sagemaker/test_sagemaker_models.py
- tests/test_sagemaker/test_sagemaker_notebooks.py
- tests/test_sagemaker/test_sagemaker_pipeline.py
- tests/test_sagemaker/test_sagemaker_processing.py
- tests/test_sagemaker/test_sagemaker_search.py
- tests/test_sagemaker/test_sagemaker_training.py
- tests/test_sagemaker/test_sagemaker_transform.py
- tests/test_sagemaker/test_sagemaker_trial_component.py
Also, I noticed a test failure when running on my system that does not show up when the tests are run within the GitHub workflow.  Created a ticket for the issue:  https://github.com/getmoto/moto/issues/6615.
Lastly, my editor runs pylint and pylint is not happy with variable names less than 3 characters.  With past PRs I've made the corrections, but I stopped doing that with this PR as it can be harder to look at the changes relevant just for the PR and it's a little tedious.
> Techdebt: Replace sure with regular assertions in sagemaker

- tests/test_secretsmanager/test_list_secrets.py
- tests/test_secretsmanager/test_policy.py
- tests/test_secretsmanager/test_secretsmanager.py
- tests/test_secretsmanager/test_server.py
> Techdebt: Replace sure with regular assertions in secretsmanager

- tests/test_ec2/test_vpc_endpoint_services_integration.py
- tests/test_ec2/test_vpc_service_configuration.py
Should fix the `Service-specific Dependencies` CI run
> Techdebt: Move some tests around

- tests/test_iotdata/test_iotdata.py
- tests/test_iotdata/test_server.py
> Techdebt: Replace sure with regular assertions in IOTData

- tests/test_logs/test_integration.py
- tests/test_logs/test_logs.py
- tests/test_logs/test_logs_filter.py
- tests/test_logs/test_models.py
> Techdebt: Replace sure with regular assertions in Logs

- tests/test_stepfunctions/test_stepfunctions.py
- tests/test_stepfunctions/test_stepfunctions_cloudformation.py
> Techdebt: Replace sure with regular assertions in stepfunctions

- tests/test_support/test_server.py
- tests/test_support/test_support.py
> Techdebt: Replace sure with regular assertions in support

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/apigatewaymanagementapi.rst
- moto/__init__.py
- moto/apigatewaymanagementapi/__init__.py
- moto/apigatewaymanagementapi/models.py
- moto/apigatewaymanagementapi/responses.py
- moto/apigatewaymanagementapi/urls.py
- moto/backend_index.py
- moto/moto_server/werkzeug_app.py
- tests/test_apigatewaymanagementapi/test_apigatewaymanagementapi.py
> Feature: APIGateway Management API

- tests/test_sts/test_server.py
- tests/test_sts/test_sts.py
- tests/test_sts/test_sts_integration.py
> Techdebt: Replace sure with regular assertions in STS

- moto/iot/models.py
- moto/iotdata/models.py
- moto/iotdata/responses.py
- tests/test_iotdata/test_iotdata.py
> IOTData: Support named shadows

- moto/core/responses.py
- moto/iam/access_control.py
- moto/s3/responses.py
- tests/test_core/test_auth.py
> S3: Allow specific resource in IAM access policy

- tests/test_sqs/test_server.py
- tests/test_sqs/test_sqs.py
- tests/test_sqs/test_sqs_cloudformation.py
- tests/test_sqs/test_sqs_integration.py
- tests/test_sqs/test_sqs_multiaccount.py
This one is a little tricky because of the use of "sure" constructions in pytest parameterizations.  Also, one file is large.
> Techdebt: Replace sure with regular assertions in SQS

- tests/test_swf/models/test_activity_task.py
- tests/test_swf/models/test_decision_task.py
- tests/test_swf/models/test_domain.py
- tests/test_swf/models/test_generic_type.py
- tests/test_swf/models/test_history_event.py
- tests/test_swf/models/test_timeout.py
- tests/test_swf/models/test_workflow_execution.py
- tests/test_swf/responses/test_activity_tasks.py
- tests/test_swf/responses/test_activity_types.py
- tests/test_swf/responses/test_decision_tasks.py
- tests/test_swf/responses/test_domains.py
- tests/test_swf/responses/test_timeouts.py
- tests/test_swf/responses/test_workflow_executions.py
- tests/test_swf/responses/test_workflow_types.py
- tests/test_swf/test_exceptions.py
- tests/test_swf/test_utils.py
Some of the files were DOS-formatted.  I converted them to UNIX format.
> Techdebt: Replace sure with regular assertions in SWF

- moto/scheduler/exceptions.py
- moto/scheduler/models.py
- tests/test_scheduler/test_scheduler.py
> Scheduler: create_scheduler() now errors on duplicate names

- moto/backend_index.py
Ref: https://github.com/getmoto/moto/security/code-scanning/76
Closes #6646
> Fix Code Scanning Alert

- tests/test_mediaconnect/test_mediaconnect.py
- tests/test_mediaconnect/test_server.py
> Techdebt: Replace sure with regular assertions in MediaConnect

- tests/test_medialive/test_medialive.py
- tests/test_medialive/test_server.py
> Techdebt: Replace sure with regular assertions in MediaLive

- tests/test_mediapackage/test_mediapackage.py
- tests/test_mediapackage/test_server.py
> Techdebt: Replace sure with regular assertions in MediaPackage

- tests/test_mediastore/test_mediastore.py
- tests/test_mediastore/test_server.py
- tests/test_mediastoredata/test_mediastoredata.py
- tests/test_mediastoredata/test_server.py
> Techdebt: Replace sure with regular assertions in MediaStore

- tests/test_ses/test_ses_sns_boto3.py
- tests/test_ssm/test_ssm_boto3.py
- tests/test_ssm/test_ssm_cloudformation.py
- tests/test_ssm/test_ssm_default_amis.py
- tests/test_ssm/test_ssm_defaults.py
- tests/test_ssm/test_ssm_doc_permissions.py
- tests/test_ssm/test_ssm_docs.py
- tests/test_ssm/test_ssm_ec2_integration.py
- tests/test_ssm/test_ssm_ecs_images.py
- tests/test_ssm/test_ssm_maintenance_windows.py
- tests/test_ssm/test_ssm_parameterstore.py
- tests/test_ssm/test_ssm_patch_baseline.py
- tests/test_ssm/test_ssm_secretsmanager.py
- tests/test_ssm/test_ssm_utils.py
Will work on tests/test_t* thru tests/test_w* next.
Also included one file from test_ses where I failed to remove the "import sure" statement.
> Techdebt: Replace sure with regular assertions in SSM

- moto/identitystore/models.py
- moto/identitystore/responses.py
- tests/test_identitystore/test_identitystore.py
Implemented IdentityStore list_groups.
> Implemented IdentityStore list_groups function

- tests/test_timestreamwrite/test_server.py
- tests/test_timestreamwrite/test_timestreamwrite_database.py
- tests/test_timestreamwrite/test_timestreamwrite_table.py
- tests/test_timestreamwrite/test_timestreamwrite_tagging.py
> Techdebt: Replace sure with regular assertions in Timestreamwrite

- tests/test_xray/test_xray_boto3.py
- tests/test_xray/test_xray_client.py
> Techdebt: Replace sure with regular assertions in Xray

- tests/test_wafv2/test_server.py
- tests/test_wafv2/test_wafv2.py
- tests/test_wafv2/test_wafv2_integration.py
- tests/test_wafv2/test_wafv2_rules.py
- tests/test_wafv2/test_wafv2_tags.py
> Techdebt: Replace sure with regular assertions in WAFv2

- tests/test_meteringmarketplace/test_meteringmarketplace.py
- tests/test_moto_api/mock_random/test_mock_random.py
- tests/test_moto_api/recorder/test_recorder.py
- tests/test_moto_api/state_manager/servermode/test_inmemory_server.py
- tests/test_moto_api/state_manager/servermode/test_state_manager.py
- tests/test_moto_api/state_manager/test_batch_integration.py
- tests/test_moto_api/state_manager/test_managed_state_model.py
- tests/test_moto_api/state_manager/test_state_manager.py
> Techdebt: Replace sure with regular assertions in MotoAPI

- tests/test_mq/test_mq.py
- tests/test_mq/test_mq_configuration.py
- tests/test_mq/test_mq_tags.py
- tests/test_mq/test_mq_users.py
- tests/test_mq/test_server.py
> Techdebt: Replace sure with regular assertions in MQ

- tests/test_emrcontainers/test_emrcontainers.py
- tests/test_emrcontainers/test_server.py
- tests/test_emrserverless/test_emrserverless.py
- tests/test_emrserverless/test_server.py
Removed import of sure and did some pylint cleanup mostly.
> Techdebt: Replace sure with assertions in EMR containers, serverless

- tests/test_cloudfront/test_server.py
One file seems to have been missed.
> Techdebt:  Replace some missed usage of sure in CloudFront

- tests/test_forecast/test_forecast.py
> Techdebt: Replace sure with regular assertions in Forecast

- tests/test_meteringmarketplace/test_meteringmarketplace.py
> Techdebt: Replace sure with regular assertions in Meteringmarketplace

- moto/s3/responses.py
Partially reverts https://github.com/getmoto/moto/pull/6635, as that seemed to cause Comprehend Terraform tests to fail. Somehow.
> Techdebt: Revert using parsed_url in S3

- tests/test_utilities/test_docker_utilities.py
- tests/test_utilities/test_paginator.py
- tests/test_utilities/test_tagging_service.py
- tests/test_utilities/test_threaded_server.py
> Techdebt: Replace sure with regular assertions in Utilities

- tests/test_opsworks/test_apps.py
- tests/test_opsworks/test_instances.py
- tests/test_opsworks/test_layers.py
- tests/test_opsworks/test_stack.py
> Techdebt: Replace sure with regular assertions in OpsWorks

- tests/test_organizations/organizations_test_utils.py
- tests/test_organizations/test_organizations_boto3.py
> Techdebt: Replace sure with regular assertions in Organizations

- tests/test_pinpoint/test_pinpoint.py
- tests/test_pinpoint/test_pinpoint_application_tags.py
- tests/test_pinpoint/test_pinpoint_event_stream.py
> Techdebt: Replace sure with regular assertions in Pinpoint

- moto/ec2/models/instances.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
Include the Detailed Monitoring attribute in `run_instances` and `describe_instances`.
> feat(ec2): Add Instance Monitoring attribute

- tests/test_polly/test_polly.py
- tests/test_polly/test_server.py
> Techdebt: Replace sure with regular assertions in Polly

- tests/test_quicksight/test_quicksight_datasets.py
- tests/test_quicksight/test_quicksight_groups.py
- tests/test_quicksight/test_quicksight_users.py
> Techdebt: Replace sure with regular assertions in QuickSight

- tests/test_ram/test_ram.py
> Techdebt: Replace sure with regular assertions in RAM

- tests/test_rds/test_db_cluster_param_group.py
- tests/test_rds/test_filters.py
- tests/test_rds/test_global_clusters.py
- tests/test_rds/test_rds.py
- tests/test_rds/test_rds_cloudformation.py
- tests/test_rds/test_rds_clusters.py
- tests/test_rds/test_rds_clusters_with_instances.py
- tests/test_rds/test_rds_event_subscriptions.py
- tests/test_rds/test_rds_export_tasks.py
- tests/test_rds/test_server.py
- tests/test_rds/test_utils.py
> Techdebt: Replace sure with regular assertions in RDS

- tests/test_rekognition/test_rekognition.py
> Techdebt: Replace sure with regular assertions in Rekognition

- tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_glue.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
- tests/test_resourcegroupstaggingapi/test_server.py
> Techdebt: Replace sure with assertions in ResourceGroupStagging API

- moto/cloudtrail/models.py
- tests/test_cloudtrail/test_cloudtrail.py
Fixes #6686 
The `get_trail_status` function must return the status for MultiRegion trails.
> fix(cloudtrail): get_trail_status must work with MultiRegion trails

- moto/iot/responses.py
- tests/test_iot/test_iot_thing_groups.py
> IOT: group names can now contain special characters

- moto/dynamodb/models/__init__.py
- moto/dynamodb/models/dynamo_type.py
- moto/dynamodb/models/table.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/models/test_item.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB: Allow ProjectionExpressions on attributes that contain a .

- moto/kms/utils.py
- tests/test_kms/test_kms_boto3.py
- Add `RSASSA_PSS_SHA_384` and `RSASSA_PSS_SHA_512` signing algorithm for RSA key specs.
- ADd unittests.
> KMS: add `RSASSA_PSS_SHA_384` and `RSASSA_PSS_SHA_512` signing algorithm

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
Fixes #6705 
Also changes the return-format of a few operations, to only return fields if/when they have a value.
All new/modified tests have been verified against AWS.
> SecretsManager: Allow creation/update of secrets without values

- moto/identitystore/models.py
- moto/identitystore/responses.py
- tests/test_identitystore/test_identitystore.py
Implemented identitystore list_users
> IdentityStore: list_users()

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/logs.rst
- docs/docs/services/resourcegroupstaggingapi.rst
- moto/awslambda/models.py
- moto/batch/models.py
- moto/logs/models.py
- moto/logs/responses.py
- moto/resourcegroupstaggingapi/models.py
- tests/terraformtests/terraform-tests.success.txt
- tests/test_logs/test_logs.py
- tests/test_logs/test_logs_tags.py
- tests/test_logs/test_models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_logs.py
Fixes #6669 
New methods:
- tag_resource()
- untag_resource()
Also includes ResourceGroupsTaggingAPI support for LogGroups.
> Logs: Tagging support

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_clusters.py
> RDS: Clusters now support the ServerlessV2ScalingConfiguration parameter

- tests/test_kms/test_kms_boto3.py
Adding fail test cases for RSA private key verification:
- Cases if a message has been falsified.
> KMS: Add fail test cases for verification of RSA Signing algorithms

- moto/s3/models.py
- moto/settings.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_cross_account.py
> S3: Allow CrossAccount access to be disabled

- moto/iam/policy_validation.py
- tests/test_iam/test_iam_policies.py
> IAM policies: allow s3 accesspoint arns

- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_notebooks.py
> SageMaker: list_notebook_instances()

- moto/awslambda/models.py
Using a TemporaryDirectory to extract the zip is a bit of a waist of IO, considering we can use an in-memory stream.
This doesn't solve any particular problem, just something I ran into while looking into adding layers to a volume.
> AWSLambda: Stream function-contents into container

- setup.cfg
> Dependencies: Update PyPartiqlParser to latest (0.3.7)

- moto/s3/responses.py
- tests/test_s3/test_s3.py
Hello,
It seems AWS has a weird way of handling HTTP `Range` request for S3. It seems it does not follow the RFC, and is instead very forgiving, failing only in certain circumstances. 
Basically, if the range request is badly formatted or not following the RFC, S3 will just treat the request as a non-range request and will return the entire object with a 200 status code.
Only certain conditions will trigger an exception and 416, mainly if the beginning of the request is above the end of the object and the request is a valid Range request (meaning it can be parsed), or if the request is a "suffix" request and it ends with 0.
I've thoroughly tested those changes against AWS, and it's been reported by one of our users.
I've updated the code and added the tests for most of the weird cases I …
> S3: fix Range request handling

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/robomaker.rst
- moto/__init__.py
- moto/backend_index.py
- moto/robomaker/__init__.py
- moto/robomaker/models.py
- moto/robomaker/responses.py
- moto/robomaker/urls.py
- tests/test_robomaker/test_robomaker.py
Fixes #2093 
This is a minimal implementation of RoboMaker, just to get the ball started.
Currently only supports 4 operations:
- create_robot_application()
- delete_robot_application()
- describe_robot_application()
- list_robot_applications()
> Feature: RoboMaker: *_robot_applications()

- .github/workflows/build.yml
- docs/docs/contributing/installation.rst
> Admin: Replace flake8 references with ruff

- moto/stepfunctions/responses.py
- tests/test_stepfunctions/test_stepfunctions.py
> SFN: list_executions() now returns the StopDate-attribute

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/events.rst
- moto/events/models.py
- moto/events/responses.py
- tests/test_events/test_events_partners_integration.py
> Events: Support for partner event sources

- moto/iam/models.py
- moto/sts/models.py
- tests/test_iam/test_iam_access_integration.py
- tests/test_iam/test_iam_resets.py
> IAM: Populate role last used

- moto/dynamodb/models/dynamo_type.py
- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_dynamodb_batch_get_item.py
Fixes #6827 
Followup to #6816
> DynamoDB - Return binary data in right format

- moto/config/resources/aws_managed_rules.json
- scripts/pull_down_aws_managed_rules.py
Also updated the managed rule list.
> Config: Add checks for valid html when pulling managed rules

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Fix for issue #6852, with the following changes:
- add capacity to disable MFA settings and clear relaated properties
- add capacity to enable MFA with SMS and TOTP in parallel
> CognitoIDP: clean MFA settings capability and enable multiple MFA methods

- moto/iam/responses.py
- tests/test_iam/test_iam.py
- tests/test_iam/test_iam_groups.py
> IAM: list_groups() now returns the CreateDate-attribute

- docs/docs/configuration/state_transition/models.rst
- moto/ecs/models.py
- tests/test_ecs/test_ecs_boto3.py
> Implement state transitions for ECS tasks

- .github/workflows/tests_real_aws.yml
- moto/ec2/models/fleets.py
- moto/ec2/responses/fleets.py
- tests/test_ec2/__init__.py
- tests/test_ec2/test_fleets.py
> EC2: delete_fleet() should set correct status

- moto/glue/models.py
- tests/test_glue/test_datacatalog.py
> Glue: Default CatalogId should be the AccountID

- moto/ec2/models/instances.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
> EC2: run_instances() now returns the Placement.HostId attribute

- moto/s3/exceptions.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3.py
> S3: head() should return MethodNotAllowed for DeleteMarkers

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ivs.rst
- moto/__init__.py
- moto/backend_index.py
- moto/ivs/__init__.py
- moto/ivs/exceptions.py
- moto/ivs/models.py
- moto/ivs/responses.py
- moto/ivs/urls.py
- moto/moto_api/_internal/moto_random.py
- tests/test_ivs/test_ivs.py
- tests/test_moto_api/mock_random/test_mock_random.py
This PR adds rudimentary support for IVS (Interactive Video Service). It's my first PR here so please let me know of anything I can improve!
For now I just added the endpoints related to channel management. I might come back and add more another time. I also tried to get the tagging endpoints working but it was giving me trouble, I may ask for help with that at some point. :-)
I didn't go very deep with the level of emulation, I'm not sure what's expected there or what the goal is. For now the only "real"ness it delivers is generating an error if a resource does not exist.
Boto documentation: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ivs.html
AWS user guide: https://docs.aws.amazon.com/ivs/latest/LowLatencyUserGuide/what-is.html
AWS api reference: …
> Rudimentary support for IVS

- .github/workflows/tests_real_aws.yml
- setup.cfg
- tests/test_dynamodb/__init__.py
- tests/test_dynamodb/test_dynamodb_statements.py
- tests/test_ec2/test_fleets.py
- tests/test_lakeformation/test_resource_tags_integration.py
- tests/test_s3/test_s3_select.py
- tests/test_ses/test_ses_boto3.py
All PartiQL tests are now verified against AWS
> S3/DynamoDB: Improve PartiQL tests

- IMPLEMENTATION_COVERAGE.md
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_model_package_groups.py
This pull request implements for sagemaker :
- describe_model_package_group
> Sagemaker: Add describe_model_package_group

- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
> EC2: create_instances() - Validate instance profile before creating Instances

- moto/iot/models.py
- tests/test_iot/test_iot_things.py
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iot/client/update_thing.html
- To remove an attribute, call UpdateThing with an empty attribute value.
> [iot] update_thing(): delete empty attributes with merge=true

- moto/sesv2/responses.py
- tests/test_sesv2/test_sesv2.py
> SESv2 send_email(): Ensure email-body is persisted

- moto/iot/models.py
- tests/test_iot/test_iot_things.py
The last patch missed some cases and the behaviour was wrong.
I added all those cases in the test and fixed the problems.
> IOT: update_thing() now behaves correctly with merge=True

- moto/ec2/models/key_pairs.py
- moto/ec2/responses/key_pairs.py
- tests/test_ec2/test_key_pairs.py
Fixes #6907 
`create_key_pair()` now supports the TagSpecifications-argument
`describe_key_pairs()` now returns the Tags-attribute
`describe_key_pairs()` now supports the `tag:` and `tag-key` filters
> EC2: KeyPairs now support tags

- moto/awslambda/models.py
- tests/test_awslambda/test_lambda_layers.py
> AWSLambda: publish_layer_version() should always set the code_sha_256 attr

- moto/databrew/responses.py
- tests/test_databrew/test_databrew_datasets.py
- tests/test_databrew/test_databrew_jobs.py
- tests/test_databrew/test_databrew_recipes.py
- tests/test_databrew/test_databrew_rulesets.py
> Databrew: Allow spaces in rules/dataset/recipe/.. names

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ecr.rst
- moto/ecr/models.py
- moto/ecr/responses.py
- tests/test_ecr/test_ecr_scanning_config.py
> ECR: batch_get_repository_scanning_configuration() + put_registry_scanning_configuration()

- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3control/test_s3control_s3.py
Resolves https://github.com/getmoto/moto/issues/6912
> S3: s3 access point reads / writes reach destination bucket

- setup.cfg
- tests/test_dynamodb/test_dynamodb_statements.py
Fixes #6900 
- Nested clauses
- OR-clauses
- Functions: attribute_type, IF (NOT) MISSING, comparison operators (<, >)
> DynamoDB: execute_statement() - improve support Where-clauses

- moto/batch/models.py
- moto/batch/responses.py
- moto/batch_simple/models.py
- tests/test_batch/test_batch_jobs.py
> Batch: submit_job() now returns the jobArn-attribute

- .github/workflows/tests_real_aws.yml
- moto/s3control/responses.py
- tests/test_s3/__init__.py
- tests/test_s3control/test_s3control_access_points.py
> S3Control: create_access_point() now returns the correct Alias

- moto/kinesisvideoarchivedmedia/models.py
> Fix typo in models.py

- moto/sagemaker/models.py
- tests/test_sagemaker/test_sagemaker_model_package_groups.py
- tests/test_sagemaker/test_sagemaker_model_packages.py
> Sagemaker: Fix pagination for ModelPackages(Groups)

- moto/__init__.py
- moto/awslambda/responses.py
- moto/awslambda_simple/__init__.py
- moto/awslambda_simple/models.py
- moto/awslambda_simple/responses.py
- moto/awslambda_simple/urls.py
- moto/core/responses.py
- tests/test_awslambda_simple/test_lambda_simple.py
`_simple` lambda implementation, for operations which don't require docker or running the function code.
> Lambda: simple lambda

- moto/rds/exceptions.py
- moto/rds/models.py
- tests/test_rds/test_rds_clusters.py
- tests/test_rds/test_rds_clusters_with_instances.py
Resolves https://github.com/getmoto/moto/issues/6993
> RDS: detect rds instance / cluster engine mismatch

- moto/ecr/models.py
- moto/ecr/responses.py
- tests/test_ecr/test_ecr_boto3.py
Resolves https://github.com/getmoto/moto/issues/6997
> ECR: image digest fix

- moto/ec2/models/vpcs.py
- tests/test_ec2/test_vpcs.py
This PR fixes a bad key in default policy for VPC endpoints.
> EC2: Fix VPC endpoint default policy

- moto/ecs/exceptions.py
- moto/ecs/models.py
- tests/test_ecs/test_ecs_boto3.py
Resolves https://github.com/getmoto/moto/issues/7006
> ECS: fix container definition validation

- moto/lakeformation/models.py
- tests/test_lakeformation/test_lakeformation.py
> LakeFormation: deregister_resource() should handle unknown resources

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/s3.rst
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_config.py
> Docs: mark S3:put_public_access_block() as implemented

- moto/awslambda/responses.py
- moto/awslambda_simple/models.py
- tests/test_awslambda_simple/test_lambda_simple.py
Resolves https://github.com/getmoto/moto/issues/7033
> Lambda: no log response bug

- tests/test_core/test_decorator_calls.py
- tests/test_core/test_responses_module.py
- tests/test_logs/test_logs.py
- tests/test_s3/test_s3_acl.py
- tests/test_s3/test_s3_auth.py
- tests/test_s3/test_s3_custom_endpoint.py
- tests/test_s3/test_s3_multipart.py
- tests/test_s3/test_s3_ownership.py
- tests/test_s3/test_s3_tagging.py
- tests/test_utilities/test_threaded_server.py
following the example of https://github.com/getmoto/moto/pull/4194
> Techdebt: add regions for various tests

- moto/cognitoidentity/models.py
- moto/cognitoidentity/responses.py
- tests/test_cognitoidentity/test_cognitoidentity.py
Hi, nice to meet you.
I added a cognito-identity implementation.
If you can hire me, I will be able to make progress in the development of my project.
Thank you very much.
> cognito-identity: Support for list identity pools

- moto/logs/models.py
- moto/logs/responses.py
- tests/test_logs/test_logs.py
This revision brings improvements to the `moto` library, with a focus on enhancing logging capabilities and export task features. A breakdown of the updates is as follows:
- The `logs/models.py` file has been revised to include new imports and updates to the `LogsBackend` class.
- Introduction of a new class, `ExportTask`, designed to manage export tasks encompassing aspects like task initiation, status monitoring, and JSON format representation.
- The `LogsBackend` class has been modified to facilitate the initiation and management of export tasks through methods like `create_export_task` and `describe_export_tasks`, which handle tasks from start to finish and provide detailed descriptions of export tasks.
- Changes in `logs/responses.py` include an updated `create_export_task` and the …
> Enhancements to CloudWatch Export Tasks Testing

- moto/batch/models.py
- tests/test_batch/test_batch_jobs.py
> Batch: Only join running Threads

- moto/awslambda/models.py
- tests/test_awslambda/__init__.py
- tests/test_awslambda/test_lambda.py
Fixes #7108 
We now verify this behaviour against AWS, our first Lambda test (hence the ridiculous number of test-changes compared to actual logic changes..)
> AWSLambda: PackageType now defaults to Zip

- moto/ec2/models/availability_zones_and_regions.py
- moto/ec2/responses/availability_zones_and_regions.py
- tests/test_ec2/test_availability_zones_and_regions.py
> EC2: describe_availability_zones() now supports additional parameters

- .github/workflows/dockertests.yml
This fixes the build, was broken with #7140
> Techdebt: Use unique names for test output

- moto/dynamodb/models/table.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB: scan() - Fixed bug in the ScanFilter-attribute

- docs/docs/faq.rst
Enhance Moto's documentation to explicitly explain its lack of support for multithreaded access/multiprocessing. Emphasize the Python threading model where a new thread copies the global context from the main thread, highlighting that this is a one-time snapshot at thread creation. Clarify the implications for read-only access and recommend performing Moto operations within the same thread context as the application or test logic to ensure consistent behavior.
related to #7164
> docs: Improve Moto concurrency safety documentation

- moto/scheduler/exceptions.py
- moto/scheduler/models.py
- tests/test_scheduler/test_scheduler.py
> fix Scheduler: delete_schedule will crash when specified schedule does not exists

- moto/identitystore/models.py
- moto/identitystore/responses.py
- tests/test_identitystore/test_identitystore.py
> IdentityStore: add  list_group_memberships_for_member

- moto/ssoadmin/models.py
- moto/ssoadmin/responses.py
- moto/ssoadmin/utils.py
- tests/test_ssoadmin/test_server.py
- tests/test_ssoadmin/test_ssoadmin.py
Added pagination for sso-admin list-account-assignments.
> sso-admin: list_account_assignments() pagination

- moto/cloudformation/models.py
- moto/s3control/config.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Closes https://github.com/getmoto/moto/issues/7155
> Cloudformation: broken changeset update

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
> CognitoIDP: ID-token now exposes custom attributes

- moto/events/notifications.py
> Fix typo in `moto/events/notifications.py`

- moto/s3/models.py
- moto/s3/notifications.py
- moto/s3/responses.py
- Adding a validation method for `S3NotificationEvent`.
- Adding event name validation where necessary.
> S3: Adding a validation method for s3 notification event name

- moto/s3/notifications.py
> Techdebt: Fix typos in S3 notifications

- moto/dynamodb/models/table.py
- tests/test_dynamodb/test_dynamodb.py
Fixes #7265 
Bug introduced in #7208
> DynamoDB: query() should sort the results before filtering/limiting

- .github/workflows/tests_terraform_examples.yml
- moto/elbv2/models.py
- other_langs/terraform/elb/load_balancer.tf
- other_langs/terraform/elb/provider.tf
> ELBv2: ModifyLoadBalancerAttributes has a new valid attribute

- moto/sqs/models.py
- other_langs/terraform/sqs/provider.tf
- other_langs/terraform/sqs/queue.tf
> SQS: Add missing property SQSManagedSSEEnabled

- moto/ec2/models/availability_zones_and_regions.py
See https://github.com/localstack/localstack/issues/10122
Information obtained from https://www.cloudregions.io/aws/region/eu-central-2
> EC2: Add availability zones for eu-central-2

- .github/workflows/tests_terraform_examples.yml
- .gitignore
- moto/awslambda/models.py
- moto/awslambda/responses.py
- moto/kinesis/models.py
- other_langs/terraform/awslambda/event_source_mapping.tf
- other_langs/terraform/awslambda/provider.tf
- tests/test_awslambda/test_lambda_eventsourcemapping.py
Fixes #7268
Also improves the output and error handling of EventSourceMappings, so that TF doesn't fall over trying to create/delete them.
> Lambda: Support Kinesis as EventSourceMapping target

- moto/dynamodb/models/__init__.py
- setup.cfg
- tests/test_dynamodb/test_dynamodb_statements.py
> DynamoDB: Improve support for Update-statements in batch_execute-statement()

- moto/route53/models.py
- moto/route53/responses.py
- moto/route53/utils.py
- tests/test_route53/test_route53.py
> Route53: list_hosted_zones() now supports pagination

- moto/amp/models.py
- moto/athena/models.py
- moto/cognitoidp/models.py
- moto/databrew/models.py
- moto/dax/models.py
- moto/ds/models.py
- moto/events/models.py
- moto/glue/models.py
- moto/glue/responses.py
- moto/identitystore/models.py
- moto/kinesis/responses.py
- moto/organizations/models.py
- moto/panorama/models.py
- moto/route53/models.py
- moto/route53resolver/models.py
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- moto/ssoadmin/models.py
- moto/stepfunctions/models.py
- moto/utilities/paginator.py
Long overdue - this removes a ton of `type: ignore`'s throughout the code base
> Techdebt: Type the Paginator-class

- moto/core/responses.py
- tests/test_cognitoidp/test_cognitoidp.py
> CognitoIDP: Allow public actions even if IAM auth is enabled

- moto/resourcegroupstaggingapi/models.py
- scripts/implementation_coverage.py
- scripts/update_backend_index.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Added resourcegroupstagging api support for ELB (classic load balancer)
> ResourceGroupsTagging support for ELB

- moto/ses/exceptions.py
- other_langs/tests_java/pom.xml
- other_langs/tests_java/src/main/java/moto/tests/DependencyFactory.java
- other_langs/tests_java/src/test/java/moto/tests/SESTest.java
> SES: Correct Exception format + Java tests

- .github/workflows/test_outdated_versions.yml
> Techdebt: Verify support for urllib3==2.2.1

- docs/docs/services/apigateway.rst
- moto/apigateway/models.py
- tests/test_apigateway/test_apigateway.py
> ApiGateway: update_usage_plan() now supports adding apiStages

- moto/dynamodb/models/dynamo_type.py
- tests/test_dynamodb/test_dynamodb_update_expressions.py
Supercedes #7352 
Fixes #7349 
All credits to @jtherrmann - I've just fixed the typing and added tests
> DynamoDB: Fix calculation when adding/subtracting decimals

- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- tests/test_cloudfront/test_cloudfront_distributions.py
> CloudFront: create_distribution() now supports CustomHeaders

- moto/sqs/models.py
- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
> SQS: send_message() should respect DelaySeconds of 0

- moto/core/responses.py
- tests/test_cloudwatch/test_cloudwatch_boto3.py
> Core: Allow compressed requests for query-protocol

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/ce.rst
- moto/ce/models.py
- moto/ce/responses.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
- tests/test_ce/test_ce_cost_and_usage.py
> CostExplorer - get_cost_and_usage()

- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_list_object_versions.py
Versioning is not active immediately, so we need to wait a little bit before we start uploading objects.
> Techdebt: Improve AWS tests

- moto/sns/models.py
- moto/sns/utils.py
- tests/test_sns/test_publishing_boto3.py
- tests/test_sns/test_subscriptions_boto3.py
> SNS: Support filters , suffix, equals-ignore-case

- docs/docs/configuration/index.rst
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
- tests/test_core/test_config.py
> Core: Add endpoint to configure Dockerless services in ServerMode

- docs/docs/getting_started.rst
Bumped into this while reading the docs.
Thanks for your work on moto!
> Fix a minor typo

- tests/test_athena/test_athena_server_api.py
> Athena: Add additional proxy tests

- moto/sqs/models.py
- tests/test_sqs/test_sqs.py
Closes https://github.com/getmoto/moto/issues/7398
> SQS: message send param validation

- moto/athena/models.py
- tests/test_athena/test_athena.py
> Athena: get_query_execution() should return exact OutputLocation file

- moto/cloudfront/models.py
- tests/test_cloudfront/test_cloudfront.py
Fix [issue #7412](https://github.com/getmoto/moto/issues/7412) - apply distribution configuration changes when using Cloudfront `update_distribution`
> Cloudfront update_distribution - apply configuration changes

- moto/ec2/models/core.py
- moto/ec2/models/security_groups.py
- moto/ec2/responses/security_groups.py
- tests/test_ec2/test_security_groups.py
Closes https://github.com/getmoto/moto/issues/7408
> EC2: SG rule tagging

- moto/iam/models.py
- tests/test_iam/__init__.py
- tests/test_iam/test_iam_cloudformation.py
> IAM: Allow CF to delete InstanceProfile with existing role

- moto/emr/models.py
- tests/test_emr/test_emr_cloudformation.py
> EMR: Allow CF deletion of Cluster, Create/Delete of SecurityConfig

- moto/ec2/models/vpcs.py
- moto/efs/models.py
- tests/test_efs/test_efs_cloudformation.py
See #7381 
An implementation for `AWS::EFS::FileSystem` already existed, but was completely broken. This PR fixes it + adds tests for it.
> EFS: CF support for FileSystems/AccessPoints

- moto/s3/models.py
- tests/test_s3/__init__.py
- tests/test_s3/test_s3_logging.py
> S3: put_bucket_logging() should handle prefix correctly

- moto/iam/models.py
- tests/test_iam/test_iam_cloudformation.py
> CloudFormation: AWS::IAM::Role now supports RoleId

- moto/apigateway/models.py
- tests/test_apigateway/test_apigateway.py
> APIGateway: update_usage_plan() now supports some remove-operations

- moto/elasticache/exceptions.py
- moto/elasticache/models.py
- moto/elasticache/responses.py
- tests/test_elasticache/test_elasticache.py
Implement the list_tags_for_resource function for elasticache.
Based primarily on the RDS list_tags_for_resource implementation
> Add list_tags_for_resource for Elasticache

- moto/awslambda/exceptions.py
- moto/awslambda/models.py
- moto/awslambda/policy.py
- tests/test_awslambda/test_lambda_policy.py
Closes https://github.com/getmoto/moto/issues/7475
> Lambda: throw error on empty resource policy

- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
> Add StateTransitionReason to ec2:DescribeInstances response

- docs/docs/services/lambda.rst
- moto/awslambda/responses.py
- moto/awslambda_simple/models.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
- tests/test_awslambda_simple/test_lambda_simple.py
- tests/test_stepfunctions/parser/test_stepfunctions_sns_integration.py
Customise Lambda response by posting desired results to a new, static moto endpoint.
Resolves https://github.com/getmoto/moto/issues/7481
> Lambda: simple lambda custom responses

- moto/backend_index.py
- moto/backends.py
- moto/resourcegroupstaggingapi/models.py
- moto/workspaces/__init__.py
- moto/workspaces/exceptions.py
- moto/workspaces/models.py
- moto/workspaces/responses.py
- moto/workspaces/urls.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_glue.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
- tests/test_workspaces/test_workspaces.py
This is the initial implementation of AWS Workspace api. Can I get a feedback on this.
1. I have added 15 API endpoints. 
2. I have changed 'us-west-1' to 'us-west-2' for glue and ec2 vpc in test_resourcetaggingapi because that region is not supported by AWS workspace and I was getting errors.
3. There are few unknowns, for e.g. computer_name
4. I have added tagging support in resourcegroupstaggingapi
> feat: Workspaceapi 

- moto/batch/models.py
- tests/test_batch/test_batch_compute_envs.py
Resolves https://github.com/getmoto/moto/issues/7492
> Batch: improve parameter validation

- moto/autoscaling/models.py
- moto/autoscaling/responses.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Closes https://github.com/getmoto/moto/issues/7528
> Cloudformation: ASG parameter error

- moto/secretsmanager/models.py
- moto/secretsmanager/responses.py
- tests/test_secretsmanager/test_secretsmanager.py
- tests/test_secretsmanager/test_server.py
Hi all, I've been working on some stuff these days and stumbled upon this [issue](https://github.com/localstack/localstack/issues/9982) on the LocalStack board. 
So, I decided to contribute by providing an implementation for the batch_get_secret_value feature.
> SecretsManager: Add BatchGetSecretValue implementation

- moto/dynamodb/responses.py
- tests/test_dynamodb/conftest.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/test_dynamodb_batch_get_item.py
Closes https://github.com/getmoto/moto/issues/7538
> DynamoDB: duplicate error should be thrown for batch writer

- moto/events/models.py
- tests/test_events/test_events.py
> Events: put_events should check if detail type, detail or source are empty

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudwatch.rst
- moto/cloudwatch/models.py
- moto/cloudwatch/responses.py
- tests/test_cloudwatch/test_cloudwatch_alarms.py
No new functionality, just improving the docs/types/making parameters optional
> CloudWatch: Improve typing/docs

- moto/iotdata/models.py
- setup.cfg
- tests/test_iotdata/test_iotdata.py
- tests/test_iotdata/test_server.py
> IOTData: Fix typing

- moto/sqs/models.py
- tests/test_cloudformation/test_stack_parsing.py
- tests/test_sqs/test_sqs.py
Closes https://github.com/getmoto/moto/issues/7559
> SQS: sqs q name validation

- moto/ec2/models/transit_gateway_attachments.py
- moto/ec2/models/transit_gateway_route_tables.py
- moto/ec2/responses/transit_gateway_route_tables.py
- tests/test_ec2/test_transit_gateway.py
Fixes #7556 
New test was validated against AWS
> EC2: RouteTables: Allow multiple propagations

- moto/stepfunctions/parser/asl/component/common/retry/backoff_rate_decl.py
- moto/stepfunctions/parser/asl/component/common/retry/interval_seconds_decl.py
- moto/stepfunctions/parser/asl/component/common/retry/jitter_strategy_decl.py
- moto/stepfunctions/parser/asl/component/common/retry/max_attempts_decl.py
- moto/stepfunctions/parser/asl/component/common/retry/max_delay_seconds_decl.py
- moto/stepfunctions/parser/asl/component/common/retry/retrier_decl.py
- moto/stepfunctions/parser/asl/component/eval_component.py
- moto/stepfunctions/parser/asl/component/program/program.py
- moto/stepfunctions/parser/asl/parse/preprocessor.py
- tests/test_stepfunctions/parser/templates/retry.py
- tests/test_stepfunctions/parser/templates/retry_jitter_none.py
- tests/test_stepfunctions/parser/test_stepfunctions_lambda_retry_integration.py
Upstream changes taken from https://github.com/localstack/localstack/pull/10267
> StepFunctions: Improve retry-functionality

- moto/stepfunctions/parser/asl/component/intrinsic/function/statesfunction/states_function.py
- moto/stepfunctions/parser/asl/parse/asl_parser.py
- moto/stepfunctions/parser/asl/parse/intrinsic/preprocessor.py
- moto/stepfunctions/parser/asl/parse/preprocessor.py
Upstream changes taken from https://github.com/localstack/localstack/pull/10372
> SFN: ASL Grammar enhancements

- moto/iot/models.py
- tests/test_iot/test_iot_search.py
Hello,
I would like to add support for searching through things while filtering by ThingType.
> feat: add Thing Type support for IoT thing search

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_boto3.py
Resolves https://github.com/getmoto/moto/issues/7564
> ECS: update service use all parameters

- moto/stepfunctions/parser/asl/component/state/exec/state_task/service/state_task_service_callback.py
- tests/test_stepfunctions/parser/__init__.py
- tests/test_stepfunctions/parser/templates/services/dynamodb_task_token.json
- tests/test_stepfunctions/parser/test_stepfunctions_dynamodb_integration.py
> StepFunctions: DynamoDB: Handle missing TaskToken

- moto/stepfunctions/models.py
- moto/stepfunctions/parser/asl/component/common/error_name/custom_error_name.py
- moto/stepfunctions/parser/models.py
- moto/stepfunctions/responses.py
- tests/test_stepfunctions/parser/templates/services/dynamodb_invalid_task_token.json
- tests/test_stepfunctions/parser/test_stepfunctions_dynamodb_integration.py
> SFN: send_task_success()/send_task_failure() fixes

- IMPLEMENTATION_COVERAGE.md
- moto/rekognition/models.py
- moto/rekognition/responses.py
- tests/test_rekognition/test_rekognition.py
Response data copied from https://docs.aws.amazon.com/rekognition/latest/customlabels-dg/detecting-custom-labels.html#text-response.
> Rekognition: add DetectCustomLabels support

- moto/ec2/models/elastic_ip_addresses.py
- moto/ec2/responses/elastic_ip_addresses.py
- tests/test_ec2/test_elastic_ip_addresses.py
Very bare-bones implementation, but should fix the CI
> EC2: describe_addresses_attributes()

- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- tests/test_cloudfront/test_cloudfront_distributions.py
Resolves https://github.com/getmoto/moto/issues/7586
> Cloudfront: fix cachebehavior response

- moto/core/responses.py
- moto/greengrass/responses.py
- moto/greengrass/urls.py
> Techdebt: Simplify GreenGrass responses

- moto/stepfunctions/parser/api.py
- tests/test_stepfunctions/parser/test_stepfunctions_dynamodb_integration.py
Resolves https://github.com/getmoto/moto/issues/7581
> StepFunction: fix error msg

- moto/appsync/urls.py
> Appsync: Simplify URL routing

- moto/athena/models.py
- moto/athena/responses.py
- tests/test_athena/test_athena.py
> Athena: start_query_execution() now supports the ExecutionParameters-parameter

- moto/quicksight/responses.py
- moto/quicksight/urls.py
> Quicksight: Simplify URL routing

- moto/s3control/models.py
- moto/s3control/responses.py
- moto/s3control/urls.py
> Techdebt: Simplify S3Control URL routing

- moto/guardduty/responses.py
- moto/guardduty/urls.py
> GuardDuty: Simplify URL routing

- moto/dynamodb/models/table_import.py
- setup.cfg
`py-partiql-parser` 0.5.5 contains performance improvements for S3 files that contains many documents, useful when using the `import_table` feature.
> DynamoDB: Update PyPartiqlParser version

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/glacier.rst
- moto/glacier/models.py
- moto/glacier/responses.py
- moto/glacier/urls.py
- tests/test_glacier/test_glacier_jobs.py
Behaviour is exactly the same, just with a simplified URL routing.
> Techdebt: Improve Glacier URL routing

- moto/ec2/exceptions.py
- moto/ec2/models/elastic_network_interfaces.py
- moto/ec2/models/vpcs.py
- tests/test_ec2/test_elastic_network_interfaces.py
Resolves https://github.com/getmoto/moto/issues/7678
> EC2: Eni detach error

- setup.cfg
> Requests: Mark 2.32.0 as broken (PT 2)

- .github/workflows/tests_terraform_examples.yml
- moto/iam/responses.py
- other_langs/terraform/iam/iam.tf
- other_langs/terraform/iam/providers.tf
- tests/test_iam/test_iam.py
> IAM: create_policy() should return tags in correct format

- moto/s3/models.py
- tests/test_ec2/test_flow_logs.py
When a user creates a bucket in `cn-north-1`, but tries to retrieve a bucket via `us-east-1`, it currently throws a recursion error:
```
File "/moto/s3/models.py", line 1856, in get_bucket
return s3_backends[account_id][self.partition].get_bucket(bucket_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/moto/s3/models.py", line 1856, in get_bucket
return s3_backends[account_id][self.partition].get_bucket(bucket_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/moto/s3/models.py", line 1856, in get_bucket
return s3_backends[account_id][self.partition].get_bucket(bucket_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Previous line repeated 968 more times]
```
We use the `bucket_accounts` to keep track of which …
> S3: Fix recursion for buckets in different partition

- moto/dynamodb/comparisons.py
- moto/dynamodb/models/__init__.py
- moto/dynamodb/parsing/ast_nodes.py
- moto/dynamodb/parsing/expressions.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/exceptions/test_dynamodb_transactions.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB: Improved validation

- moto/ec2/models/route_tables.py
- tests/test_ec2/test_route_tables.py
Added filter 'transit gateway id' for the DescribeRouteTables operation
> EC2: TransitGatewayId filter for DescribeRouteTables

- .github/workflows/tests_terraform_examples.yml
- moto/rds/models.py
- moto/rds/responses.py
- other_langs/terraform/rds/providers.tf
- other_langs/terraform/rds/rds.tf
> RDS: Change status to 'available' to ensure TF works

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_clusters.py
https://github.com/getmoto/moto/issues/7734
> RDS: parse more input parameters

- moto/ssm/models.py
- tests/test_ssm/test_ssm_boto3.py
Closes https://github.com/getmoto/moto/issues/7748
> SSM: return ssm param if arn used as a name

- moto/elbv2/models.py
- tests/test_elbv2/test_elbv2_target_health.py
> ELBv2 - describe_target_health() should detect unknown/never-registered instances

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/budgets.rst
- docs/docs/services/ec2.rst
- docs/docs/services/events.rst
- docs/docs/services/lakeformation.rst
- docs/docs/services/opensearchserverless.rst
- docs/docs/services/personalize.rst
- docs/docs/services/quicksight.rst
- docs/docs/services/resiliencehub.rst
- docs/docs/services/swf.rst
- moto/backend_index.py
- moto/backends.py
- moto/opensearchserverless/__init__.py
- moto/opensearchserverless/exceptions.py
- moto/opensearchserverless/models.py
- moto/opensearchserverless/responses.py
- moto/opensearchserverless/urls.py
- tests/test_opensearchserverless/test_opensearchserverless.py
This is the initial moto implementation of AWS Opensearch serverless api. I have added 12 API endpoints. Can I get a feedback on this.
> feat: opensearch api

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/emr-serverless.rst
- docs/docs/services/shield.rst
- moto/backend_index.py
- moto/backends.py
- moto/shield/__init__.py
- moto/shield/exceptions.py
- moto/shield/models.py
- moto/shield/responses.py
- moto/shield/urls.py
- tests/test_shield/test_shield.py
This is the initial moto implementation of AWS Shield api. I have added 7 API endpoints. Can I get a feedback on this.
> feat: Shield API

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
> ResourceGroupsTagging: Add support for `elasticfilesystem` resource type filter

- moto/core/utils.py
- moto/iotdata/models.py
- moto/iotdata/responses.py
- tests/test_iotdata/__init__.py
- tests/test_iotdata/test_iotdata.py
> IOTData: Fix delta calculation

- .github/workflows/tests_proxymode.yml
- moto/moto_proxy/certificate_creator.py
> Proxy: Ensure it runs on Windows

- docs/docs/services/athena.rst
- moto/athena/models.py
- tests/test_athena/__init__.py
- tests/test_athena/test_athena_integration.py
> Athena: Store QueryResults in S3

- moto/sesv2/responses.py
- tests/test_sesv2/test_sesv2.py
Resolves https://github.com/getmoto/moto/issues/7816
> SESv2: send_email() response fix

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds_clusters.py
- tests/test_rds/test_rds_proxy.py
Just a few little things I came across while working on something else.  Yes, `None` is technically "falsy", but ensuring these boolean values can only be `True` or `False` makes the code more correct and makes a difference when serializing responses.  
@bblommers These commits be atomic!  😄  Please `Rebase and merge` instead of squashing.  Thanks!
> RDS: Boolean Value Fixes

- moto/dynamodb/models/table.py
- tests/test_dynamodb/test_dynamodb_query.py
Fixes https://github.com/getmoto/moto/issues/7834
If any of the keys don't exist (because we're not using a GSI or the item doesn't have them) falls through to the next attribute in the list.
> This is my first PR contributing to moto - please let me know on any standards/etc. that I've missed (ran tests and lint locally, both were passing)
> DynamoDB: Sorts by the keys of the GSI before sorting by keys of the table

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Adds RTAPI tag_resource support for sagemaker
> Feature: Add RTAPI tag resource for SageMaker

- moto/scheduler/models.py
- moto/scheduler/responses.py
- tests/test_scheduler/test_scheduler.py
> EventBridge Scheduler - get_schedule() now returns the ActionAfterCompletion

- docs/docs/services/networkmanager.rst
- moto/networkmanager/models.py
- moto/networkmanager/responses.py
- moto/networkmanager/urls.py
- tests/test_networkmanager/test_networkmanager.py
Resolves #7844 
Network Manager Endpoints:
- **Devices**: Create, Get, Delete
- **Links**: Create, Get, Delete
- **Sites**: Create, Get, Delete
- ListTagsForResource
https://docs.aws.amazon.com/networkmanager/latest/APIReference/API_GetDevices.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/networkmanager/client/get_sites.html
> Network Manager - Add Devices, Links & Sites

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_db_cluster_param_group.py
- tests/test_rds/test_rds_proxy.py
* Rename existing model classes to match AWS conventions for RDS (e.g. `Database` to `DBInstance`).
* Add `RDSBaseModel` class to encapsulate Amazon Resource Name (ARN) property for all models.
* Refactor `account_id` and `region_name` parameters out of RDS object creation (i.e. use `RDSBackend` object).
All tests are passing after refactoring.  Only change to test code was a minor typo fix.
> RDS: Refactorings

- moto/rds/models.py
- tests/test_rds/test_rds.py
- tests/test_rds/test_rds_clusters.py
A series of atomic commits with various improvements for the RDS module. 
* Remove duplication
* Remove dead code
* Fix defect and add test coverage
> RDS Refactorings

- moto/rds/models.py
> RDS: Fix Engine Family Typo

- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_model_expainability.py
Adds support  for Sagemaker Model Explainability Job Definition create, list, describe, and delete
> Feature: Sagemaker Model Explainability Job Definition

- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_hyper_parameter_tuning_job.py
Adds support for Sagemaker Hyper Parameter Tuning Job create, describe, list, and delete.
> Feature: Sagemaker Hyper Parameter Tuning Job

- moto/cognitoidp/models.py
- requirements-tests.txt
- tests/test_cognitoidp/__init__.py
- tests/test_cognitoidp/test_cognitoidp.py
Fixes #7758 
Majority of this PR are changes to the tests, to ensure that they can be run against AWS.
> CognitoIDP: ID-token is different when username=email

- moto/rds/models.py
- moto/rds/responses.py
More RDS code clean-up.  Just trying to get rid of as much code duplication as possible before working on more substantive refactorings.
> RDS Refactoring

- docs/docs/services/sagemaker.rst
- moto/sagemaker/exceptions.py
- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- moto/sagemaker/utils.py
- tests/test_sagemaker/test_sagemaker_model_cards.py
Adds support for SageMaker Model Card create, list, describe, delete
> Feature: SageMaker Model Cards

- moto/awslambda/models.py
- tests/test_awslambda/test_awslambda_cloudformation.py
> AWSLambda: Allow CF creation of Lambdas with ImageURI's

- moto/sqs/exceptions.py
- moto/sqs/responses.py
- tests/conftest.py
- tests/test_logs/test_export_tasks.py
- tests/test_sqs/__init__.py
- tests/test_sqs/test_sqs.py
All relevant tests are now verified against AWS.
Fixes #7827
> SQS: Improve error handling for unknown queues

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/athena.rst
- moto/athena/models.py
- moto/athena/responses.py
- tests/test_athena/test_athena.py
> Athena: delete_work_group() and default configuration

- moto/dynamodb/models/__init__.py
- tests/test_dynamodb/test_dynamodb.py
- tests/test_dynamodb/test_dynamodb_batch_write.py
- tests/test_dynamodb/test_dynamodb_transact.py
> DynamoDB: Allow TableARN for TableName-parameters

- moto/sagemaker/models.py
- tests/test_sagemaker/test_sagemaker_model_package_groups.py
> Sagemaker: search() now supports ModelPackageGroups

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/kms.rst
- moto/dynamodb/models/table.py
- moto/ec2/models/elastic_block_store.py
- moto/kms/models.py
- moto/kms/responses.py
- tests/test_kms/test_model.py
> KMS: Update ImplementationCoverage; rename internal alias methods

- .github/workflows/tests_terraform_examples.yml
- moto/codebuild/models.py
- moto/codebuild/responses.py
- moto/ds/models.py
- other_langs/terraform/codebuild/project.tf
- other_langs/terraform/codebuild/provider.tf
- other_langs/terraform/ds/provider.tf
- other_langs/terraform/ds/simple_ad.tf
- tests/test_codebuild/test_codebuild.py
Fixes #7947 
Improves the response format of both CodeBuild and DS to get more parity, and ensure that these services can be used with Terraform.
> Codebuild & DS - Improve AWS parity

- moto/organizations/models.py
- tests/test_organizations/test_organizations_boto3.py
> Organizations: create_account() now comes preconfigured with an IAM role

- moto/dynamodb/exceptions.py
- moto/dynamodb/models/__init__.py
- moto/dynamodb/models/table.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/test_dynamodb_resource_policy.py
> DynamoDB: Resource Policies

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- tests/test_cognitoidp/__init__.py
- tests/test_cognitoidp/test_cognitoidp.py
> CognitoIDP: sign_up() now returns CodeDeliveryDetails

- docs/docs/configuration/index.rst
- docs/docs/getting_started.rst
- docs/docs/server_mode.rst
- moto/moto_server/threaded_moto_server.py
- tests/test_core/test_server.py
Fixes #7892
Fixes #7894 
Fixes #7895
> Docs: Improve fixtures and ThreadedMotoServer

- moto/events/models.py
- tests/test_events/test_events.py
Adds `SecretArn` attribute to Eventbridge connections
> EventBridge: create_connection() now creates a KMS Secret

- moto/autoscaling/models.py
- tests/test_autoscaling/test_autoscaling.py
> Autoscaling: update_group() now validates that the Group exists

- moto/route53/exceptions.py
- moto/route53/models.py
- moto/route53/utils.py
- tests/test_route53/test_route53.py
> Route53: list_resource_record_sets() now validates record names

- moto/ec2/models/elastic_network_interfaces.py
- tests/test_ecs/test_ecs_boto3.py
> ECS: Tasks can now be created with unknown security groups

- moto/apigatewaymanagementapi/responses.py
- moto/apigatewaymanagementapi/urls.py
- moto/backend_index.py
- tests/test_apigateway/test_apigateway_integration.py
- tests/test_apigatewaymanagementapi/test_apigatewaymanagementapi.py
> APIGatewayManagement() - can now be called with an APIgw endpoint URL

- moto/acmpca/models.py
Changes introduced in https://github.com/getmoto/moto/pull/7950 make the x509 Issuer a part of the `CertificateAuthority` model. Firstly, it is not necesary to retain this attribute in-memory. Secondly, because the x509 Issuer object is natively implemented in Rust, it cannot be serialised with pickle which breaks certain functionality in LocalStack.
This PR changes the issuer into a class property which builds the x509 Issuer object on-demand.
> ACM-PCA: Ensure backend is serialisable

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/timestream-query.rst
- moto/backend_index.py
- moto/backends.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
- moto/timestreamquery/__init__.py
- moto/timestreamquery/exceptions.py
- moto/timestreamquery/models.py
- moto/timestreamquery/urls.py
- moto/timestreamwrite/responses.py
- tests/test_timestreamquery/test_timestreamquery.py
> Service: TimestreamQuery

- moto/sns/models.py
- moto/sns/responses.py
- moto/sns/urls.py
- tests/test_sns/test_http_message_verification.py
- tests/test_sns/test_publishing_boto3.py
- tests/test_sns/test_sns.py
> SNS: Signature of HTTP Messages are now valid

- moto/cloudformation/parsing.py
- tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
> CloudFormation now supports Fn::Base64

- moto/s3/exceptions.py
- moto/s3/models.py
- moto/s3/responses.py
- tests/test_s3/test_s3_bucket_policy.py
- tests/test_s3/test_s3_lock.py
> S3: delete_objects() now respects BucketPolicy and ObjectLocks

- moto/cognitoidp/models.py
- moto/cognitoidp/responses.py
- requirements-tests.txt
- tests/test_cognitoidp/__init__.py
- tests/test_cognitoidp/test_cognitoidp.py
> Cognito: Implement MFA_SETUP challenge

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
Fixes #8029
- Forces MFA setup when MFA_CONFIG is ON, not when it's optional
- Respond with SOFTWARE_TOKEN_MFA when it's the user preference, or when MFA_CONFIG is ON and user already had a token verified
- Verifies an auth flow after MFA has been configured
> CognitoIDP - improve MFA flows

- moto/s3/responses.py
- tests/test_s3/test_s3.py
> S3: head_object() now handles Range-parameter correctly

- moto/core/responses.py
- moto/s3/models.py
- moto/s3/responses.py
Follow-up to #8000
No logical changes - just extracting the logic of various stand-alone parts into dedicated methods.
> Techdebt: Untangle S3 Key PUT methods

- moto/sqs/exceptions.py
- moto/sqs/responses.py
- tests/test_sqs/test_sqs.py
> SQS: delete_message_batch() now validates there's at least one entry

- moto/s3/responses.py
> Techdebt: S3: Untangle object GET methods

- moto/ec2/models/instances.py
- moto/ec2/responses/instances.py
- tests/test_ec2/test_instances.py
> EC2: run_instances() now supports the parameter Ipv6AddressCount

- moto/kms/models.py
- tests/test_kms/test_kms_boto3.py
> KMS: sign() now supports Alias ARNs

- .github/workflows/data-update_ssm-optimized-amis.yml
- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/appconfig.rst
- docs/docs/services/bedrock-agent.rst
- docs/docs/services/bedrock.rst
- docs/docs/services/codepipeline.rst
- docs/docs/services/ec2.rst
- docs/docs/services/ecr.rst
- docs/docs/services/elbv2.rst
- docs/docs/services/glue.rst
- docs/docs/services/lambda.rst
- docs/docs/services/logs.rst
- docs/docs/services/mediaconnect.rst
- docs/docs/services/personalize.rst
- docs/docs/services/quicksight.rst
- docs/docs/services/resiliencehub.rst
- docs/docs/services/s3control.rst
- docs/docs/services/sagemaker-runtime.rst
- docs/docs/services/shield.rst
- docs/docs/services/ssm.rst
- scripts/ec2_get_instance_type_offerings.py
- scripts/get_instance_info.py
- scripts/ssm_get_default_amis.py
- scripts/ssm_get_optimized_amis.py
- tests/test_s3/test_s3.py
- tests/test_s3/test_s3_bucket_policy.py
See #8087  - I expected the new region to be picked up automatically, but I put too much faith in AWS.
This PR also updates the service coverage for the next release.
> Techdebt: Retrieve static data from Malaysia

- moto/s3/responses.py
- tests/test_s3/test_s3.py
> S3: put_object() now support conditional writes

- moto/dynamodb/exceptions.py
- moto/dynamodb/parsing/ast_nodes.py
- tests/test_dynamodb/test_dynamodb_update_expressions.py
> DynamoDB: Improve parsing of UpdateExpressions with multiple REMOVE clauses

- moto/backend_index.py
- moto/backends.py
- moto/resourcegroupstaggingapi/models.py
- moto/workspacesweb/__init__.py
- moto/workspacesweb/exceptions.py
- moto/workspacesweb/models.py
- moto/workspacesweb/responses.py
- moto/workspacesweb/urls.py
- tests/test_workspacesweb/test_workspacesweb.py
Added mocking for workspaces web (workspaces secure browser)
> Workspaces Web Support

- moto/dynamodb/models/dynamo_type.py
- tests/test_dynamodb/test_dynamodb_update_expressions.py
> DynamoDB: update_item() can now remove last item from set

- moto/route53/models.py
- moto/route53/responses.py
- tests/test_route53/test_route53.py
Resolves #8130 
Adds additional test scenarios
> [BUG FIX] route53 list_tags_for_resources no results & hostedzone ids not decoding properly

- moto/guardduty/models.py
- moto/guardduty/responses.py
- tests/test_guardduty/test_guardduty.py
GuardDuty Detector - Add "Feature" support to Create, Delete and Update apis
Ref:
https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DetectorFeatureConfiguration.html
https://docs.aws.amazon.com/guardduty/latest/APIReference/API_UpdateDetector.html#guardduty-UpdateDetector-request-features
> GuardDuty Detector - Add "Feature" support to Create, Delete and Update apis

- moto/firehose/models.py
- tests/test_firehose/test_firehose_put.py
Hello, based on my last PR (https://github.com/getmoto/moto/pull/8122), I completely forgot to add the modifications for the `put_record_batch` function.
I'm sorry, here is the FIX :) :)
> [BUG FIX] Firehose - Snowflake destination: Fix `put_record` and `put_record_batch` functions

- moto/ds/exceptions.py
- moto/ds/models.py
- moto/ds/responses.py
- moto/ds/utils.py
- moto/ds/validations.py
- tests/test_ds/test_ds.py
- tests/test_ds/test_ds_microsoft_ad.py
Adding several features to Directory Service (DS)
**LDAPs**
- EnableLDAPS
- DisableLDAPS
- DescribeLDAPS
**Trust Relationships**
- CreateTrust
- DeleteTrust
- DescribeTrust
> Directory Service - Enable/Disable/Describe LDAPs & Create/Delete/Describe Trusts

- moto/apigatewaymanagementapi/urls.py
- moto/backend_index.py
- tests/test_core/test_botocore_stubber.py
> Core: Improve URL matching regex for APIGatewayMgmt

- moto/appsync/models.py
- moto/appsync/responses.py
- tests/test_appsync/test_appsync.py
Adds visibility option to the **appsync graphql api**
> AppSync: Add visibility options

- moto/apigateway/models.py
- moto/apigateway/responses.py
- tests/test_apigateway/test_apigateway.py
> APIGateway: get_api_keys()/get_usage_plan_keys() now support the nameQuery param

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudfront.rst
- moto/cloudfront/models.py
- moto/cloudfront/responses.py
- moto/cloudfront/urls.py
- tests/test_cloudfront/test_cloudfront_keys.py
> CloudFront: KeyGroups and PublicKeys

- moto/quicksight/data_models.py
- moto/quicksight/exceptions.py
- moto/quicksight/models.py
- moto/quicksight/responses.py
- moto/quicksight/urls.py
- moto/quicksight/utils.py
- tests/test_quicksight/test_quicksight_groups.py
- tests/test_quicksight/test_quicksight_users.py
__Enhancements:__
* Added all missing user handling functions
* Added all missing group handling functions
* Added pagination support for all user and group list functions
* Added search support for groups
__Fixes:__
* Use function to get URL path parameters
> QuickSight finalize user and group handling

- moto/memorydb/models.py
The response for 'TLSEnabled' and 'AutoMinorVersionUpgrade' is always True even when they are set to False. This PR fixes this issue.
> MemoryDB: create_cluster() ensure TLSEnabled can be False

- moto/elbv2/models.py
Should fix the build - TF is complaining that this value is not supported.
> ELBv2: modify_lb_attr() now supports zonal-shift config

- moto/awslambda/models.py
> Lambda: Properly pass dynamodb streams event name

- moto/elbv2/models.py
- moto/elbv2/responses.py
- other_langs/terraform/elb/listener.tf
- tests/test_elbv2/test_elbv2_listener_attributes.py
> ELBv2: Describe/Modify Listener Attributes

- moto/ecs/models.py
- moto/ecs/responses.py
- tests/test_ecs/test_ecs_tasksets.py
> ECS: create_task_set() now creates tasks

- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Creates two test clusters, `TestDuplicateProjectionExpressions` and `TestReturnValuesOnConditionCheckFailure`. 
Both test cases only create the necessary table once, which decreases the execution time when running them against AWS. It also greatly reduces the amount of duplication.
> DynamoDB: Improve exception tests

- moto/batch/models.py
- moto/batch/responses.py
- tests/test_batch/test_batch_jobs.py
> Batch: list_jobs() now supports the arrayJobId-parameter

- moto/s3/models.py
- moto/s3/notifications.py
- tests/test_s3/test_s3_eventbridge_integration.py
- tests/test_s3/test_s3_notifications.py
- Sending a notification to EventBridge when object acl updated.
related https://github.com/getmoto/moto/issues/7363
> S3: Sending notification to EventBridge ObjectAcl:Put

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/directconnect.rst
* Minor doc update related to directconnect ( forgotten in #8360 )
> directconnect: doc update (coverage)

- moto/rds/exceptions.py
- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds.py
...and improve the validation of RDS instance identifiers.
> Validate RDS snapshot identifiers

- moto/core/base_backend.py
See https://github.com/getmoto/moto/issues/5469#issuecomment-2474897120
> Core: Only instantiate Session when required

- moto/athena/responses.py
- tests/test_athena/test_athena.py
> Athena: start_query_execution() should support WorkGroups

- moto/dynamodb/models/utilities.py
- tests/test_dynamodb/test_dynamodb.py
> DynamoDB: update_item() can now return list of binaries

- moto/stepfunctions/models.py
- moto/stepfunctions/responses.py
- tests/test_stepfunctions/test_stepfunctions_versions.py
> StepFunctions: describe_state_machine() now takes Version ARN's

- tests/test_rds/test_rds.py
Getting rid of almost 700 lines of code, mostly by refactoring the copy&paste parts.
> Refactor test_rds.py

- setup.cfg
Ref: https://github.com/getsentry/responses/issues/751
> Exclude bad `responses` version

- moto/kafka/models.py
- tests/test_kafka/test_kafka.py
> Kafka - Update responses for list_clusters_v2

- tests/test_dsql/test_dsql.py
> DSQL: Verify we can generate tokens

- moto/ec2/models/amis.py
- moto/ec2/utils.py
- tests/test_ec2/test_utils.py
- tests/test_special_cases/test_custom_amis.py
> Support tagging in custom AMI definitions

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_secretsmanager.py
Fixes #8512 
Reimplements (fixes) the original implementation in #8504 
The original bug report mentioned that there should be no value for the `AWSPENDING` secret during rotation.
However, we should have the existing value when only invoking the `testSecret`-step (that is, when we're not rotating the secret immediately).
> SecretsManager: get_secret_value() no longer errors after delayed secret rotation

- moto/ecr/policy_validation.py
- tests/test_ecr/test_ecr_boto3.py
- tests/test_ecr/test_ecr_policy_validation.py
> ECR: Lifecycle Policies() now support the tagPatternList-parameter

- moto/apigatewayv2/models.py
- moto/ecr/models.py
- other_langs/terraform/apigw2/apigateway.tf
- other_langs/terraform/apigw2/data.tf
- other_langs/terraform/apigw2/provider.tf
- other_langs/terraform/ecr/provider.tf
- other_langs/terraform/ecr/repository.tf
> APIGatewayV2/ECR: Change date formatting for TF-compatibility

- moto/cognitoidp/models.py
- tests/test_cognitoidp/test_cognitoidp.py
> CognitoIDP: AccessTokens and IDTokens now contain the jti and origin_jti values

- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_filters.py
- tests/test_rds/test_rds.py
- tests/test_rds/test_rds_clusters.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_rds.py
Various enhancements and fixes for the RDS Backend.
Closes #8568
> RDS Improvements

- moto/awslambda/models.py
- tests/test_awslambda/test_lambda_eventsourcemapping.py
> Lambda EventSourceMapping: Support all properties

- moto/core/responses.py
- other_langs/tests_js/lambda.test.js
- other_langs/tests_js/package.json
> AWSLambda: Make ListFunctions work for JS SDK

- moto/rds/exceptions.py
- moto/rds/models.py
- moto/rds/responses.py
- moto/rds/serialize.py
- tests/test_rds/__init__.py
- tests/test_rds/test_filters.py
- tests/test_rds/test_rds.py
- tests/test_rds/test_rds_clusters.py
- tests/test_rds/test_rds_proxy.py
- tests/test_rds/test_rds_proxy_target_groups.py
- tests/test_rds/test_server.py
Various enhancements and fixes for the RDS Backend, including:
New Operations:
- DescribeEvents
- DescribeDBLogFiles
- FailoverDBCluster
- RestoreDBClusterToPointInTime
Support for Cross-Region Snapshot Copy (closes #8389)
> RDS Backend Improvements

- moto/s3/responses.py
Caused by #8495
This fixes #8592
It was broken with the checksum workaround. The workaround relied on something dangerous called `input_stream` defined in werkzeug on the request, and it is not always an `io.BytesIO`; sometimes it is a `BufferedReader`, sometimes it is a `bytes`.
https://github.com/pallets/werkzeug/blob/7868bef5d978093a8baa0784464ebe5d775ae92a/src/werkzeug/wrappers/request.py#L355-L364
```
input_stream = environ_property[t.IO[bytes]](
"wsgi.input",
doc="""The raw WSGI input stream, without any safety checks.
This is dangerous to use. It does not guard against infinite streams or reading
past :attr:`content_length` or :attr:`max_content_length`.
Use :attr:`stream` instead.
""",
)
```
I could not reproduce the behavior with a moto unit test; but it was failing when using …
> Properly handle CopyObject with content length 0 in moto_server after checksum workaround

- moto/rds/models.py
- tests/test_rds/test_global_clusters.py
> RDS: Add GlobalCluster.Endpoint attribute

- moto/backend_index.py
- moto/dynamodb/urls.py
- tests/test_dynamodb/test_dynamodb_account_mode.py
> DynamoDB: Support AccountMode

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Adds event-bus support to resourcetaggingapi
> [EventBridge] Add event-bus support to resourcetaggingapi

- moto/rds/exceptions.py
- moto/rds/models.py
- tests/test_rds/test_rds_clusters_with_instances.py
> RDS: Raise error when trying to add DBInstance to non-existent DBCluster

- moto/ssm/resources/regions.json
- moto/ssm/resources/services.json
- tests/test_ssm/test_ssm_defaults.py
Reopened from original PR (#8667) that broke the build after it was merged and had to be reverted.
> chore: update SSM default parameters

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/cloudformation.rst
- docs/docs/services/glue.rst
- docs/docs/services/guardduty.rst
- docs/docs/services/sesv2.rst
- docs/docs/services/timestream-influxdb.rst
- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_glue.py
Resolves https://github.com/getmoto/moto/issues/8652
> [Glue] Put and Get Encryption Settings

- moto/rds/exceptions.py
- moto/rds/models.py
- moto/rds/responses.py
- tests/test_rds/test_rds.py
Added support for rds API: copy_db_parameter_group.
In addition, I fixed an incorrect key in the response for describe_db_parameter.
> RDS: implement CopyDBParameterGoup

- moto/ds/models.py
- moto/ds/responses.py
- moto/ds/utils.py
- tests/test_ds/test_ds.py
Adds the following endpoints to Directory Service:
- Create_Log_Subscription
- List_Log_Subscriptions
- Delete_Log_Subscription
> [DS] Log Subscriptions - Create, List, Delete

- .github/workflows/tests_sdk_go.yml
- other_langs/tests_go/eks_test.go
- other_langs/tests_go/go.mod
> EKS: Add test using AWS SDK for Go v2

- moto/redshift/models.py
- moto/redshift/responses.py
- tests/test_redshift/test_redshift.py
Adds the following redshift endpoints:
- [Enable_Logging](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift/client/enable_logging.html)
- Disable_logging
- Describe_logging
> [Redshift] Logging - Enable, Disable, Describe

- moto/resourcegroupstaggingapi/models.py
- tests/test_appsync/test_appsync_tags.py
Adds AppSync support to ResourceGroupsTaggingApi
> [Appsync] Add support to resourcegroupstagging api

- moto/resourcegroupstaggingapi/models.py
- tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Adding cloudfront distribution support to resourcetaggingapi
> [Cloudfront] Add cloudfront distribution support to resourcetaggingapi

- docs/docs/services/ecr.rst
- moto/ecr/models.py
- moto/moto_api/_internal/models.py
- moto/moto_api/_internal/responses.py
- moto/moto_api/_internal/urls.py
> ECR: describe_image_scan_findings: Allow custom results

- tests/test_ecr/test_ecr_scan_results.py
Should have been part of #8683, but I forgot to add the file :facepalm:
> ECR: Add test for custom scan findings

- moto/mediaconnect/models.py
- moto/mediaconnect/responses.py
- tests/test_mediaconnect/test_mediaconnect.py
The parameter to set the desired maintainance window schedule when creating a Flow is missing.
> [MediaConnect] Accept Maintenance value during MediaConnect flow creation

- moto/sns/models.py
- tests/test_sns/test_publishing_boto3.py
> SNS: Expose sms messages using Moto API

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/batch.rst
- docs/docs/services/bedrock.rst
- docs/docs/services/cloudformation.rst
- docs/docs/services/elbv2.rst
- docs/docs/services/route53resolver.rst
- docs/docs/services/sagemaker.rst
- docs/docs/services/sesv2.rst
- docs/docs/services/timestream-influxdb.rst
- docs/docs/services/workspaces.rst
- moto/route53resolver/models.py
- moto/route53resolver/responses.py
- tests/test_route53resolver/test_route53resolver.py
Resolves https://github.com/getmoto/moto/issues/8765
> [Route53] Resolver Queries

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/wafv2.rst
- moto/wafv2/models.py
- moto/wafv2/responses.py
- moto/wafv2/utils.py
- tests/test_wafv2/test_regex_pattern_sets.py
This PR implements the following API endpoints for WAFv2:
- [`CreateRegexPatternSet`](https://docs.aws.amazon.com/goto/WebAPI/wafv2-2019-07-29/CreateRegexPatternSet)
- [`GetRegexPatternSet`](https://docs.aws.amazon.com/goto/WebAPI/wafv2-2019-07-29/GetRegexPatternSet)
- [`ListRegexPatternSets`](https://docs.aws.amazon.com/waf/latest/APIReference/API_ListRegexPatternSets.html)
- [`UpdateRegexPatternSet`](https://docs.aws.amazon.com/waf/latest/APIReference/API_UpdateRegexPatternSet.html)
- [`DeleteRegexPatternSet`](https://docs.aws.amazon.com/waf/latest/APIReference/API_DeleteRegexPatternSet.html)
```bash
(.venv) @HarshCasper ➜ /workspaces/moto (wafv2-regex-endpoints) $ pytest -sv tests/test_wafv2/test_regex_pattern_sets.py …
```
> WAFv2: add implementation for `RegexPatternSet`

- moto/secretsmanager/models.py
- tests/test_secretsmanager/test_server.py
> SecretsManager: display Secrets on dashboard

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/batch.rst
- docs/docs/services/bedrock.rst
- docs/docs/services/cloudformation.rst
- docs/docs/services/dms.rst
- docs/docs/services/ec2.rst
- docs/docs/services/elbv2.rst
- docs/docs/services/s3control.rst
- docs/docs/services/sagemaker.rst
- docs/docs/services/sesv2.rst
- docs/docs/services/timestream-influxdb.rst
- docs/docs/services/workspaces.rst
- moto/sesv2/models.py
- moto/sesv2/responses.py
- moto/sesv2/urls.py
- tests/test_sesv2/test_sesv2.py
Resolves https://github.com/getmoto/moto/issues/8778
> [SES] Identity Policies

- moto/acmpca/responses.py
- tests/test_acmpca/test_acmpca.py
Fixes https://github.com/localstack/localstack/issues/12076
> fix the `GetCertificateAuthorityCertificate` API in ACM PCA

- moto/acm/models.py
- tests/test_acm/test_acm.py
Fixes https://github.com/localstack/localstack/issues/11152
> feat(acm): Update status to EXPIRED when Not After has past

- moto/ses/models.py
- moto/ses/responses.py
- moto/sesv2/models.py
- moto/sesv2/responses.py
- tests/test_sesv2/test_sesv2.py
Fixes SES & SESv2 configuration set pagination
> [SES] Configuration Set List Pagination

- moto/resourcegroupstaggingapi/models.py
- tests/test_kinesisanalyticsv2/test_kinesisanalyticsv2.py
Adds kinesisanalyticsv2 support to resourcetaggingapi.
> [kinesisanalyticsv2] Add kinesisanalyticsv2 support to resourcetaggingapi

- moto/ses/models.py
- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
See https://github.com/localstack/localstack/issues/5744
> implement UpdateConfigurationSetReputationMetricsEnabled API for SES

- moto/ses/models.py
- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
See https://github.com/localstack/localstack/issues/5743
> feat(ses): implement `GetIdentityDkimAttributes` API

- moto/iam/models.py
- tests/test_iam/test_iam_cloudformation.py
Fixes #8590 
If a stack has both a Role and an InlinePolicy attached to this role, there are two scenarios on deletion:
1. Policy is deleted first
a) removes policy from the roles it's attached to
b) removes the policy itself
c) removes the role last
2. Role is deleted first
a) removes the role
b) removes inline policy from the roles it's attached to
c) removes policy itself
This PR ensures that, at step 2b, we don't try to remove a policy from a role that no longer exist.
> IAM: Handle CF deletion of policies attached to a role

- moto/organizations/models.py
- moto/organizations/utils.py
- tests/test_organizations/test_organizations_boto3.py
See https://github.com/localstack/localstack/issues/11530
> feat (organizations): support `TAG_POLICY` type

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/comprehend.rst
- moto/comprehend/models.py
- moto/comprehend/responses.py
- tests/test_comprehend/test_comprehend.py
Added more mock functions to Amazon Comprehend.
[create_document_classifier ](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/comprehend/client/create_document_classifier.html) 
[create_endpoint](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/comprehend/client/create_endpoint.html)  
[create_flywheel](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/comprehend/client/create_flywheel.html)  
[describe_document_classifier](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/comprehend/client/describe_document_classifier.html)  
[describe_endpoint](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/comprehend/client/describe_endpoint.html) …
> [Comprehend] Additional Amazon Comprehend Functions

- moto/appsync/models.py
- tests/test_appsync/test_appsync.py
Adds the missing tags to app sync responses.
> [AppSync] Add tags to list and get

- moto/rds/models.py
- moto/rds/utils.py
- tests/test_neptune/test_clusters.py
Enables create_db_instance for Neptune
> [Neptune] Enable create_db_instance where engine is neptune

- moto/textract/models.py
- moto/textract/responses.py
- tests/test_textract/test_textract.py
Relates to https://github.com/localstack/localstack/issues/12372
> add support for Textract SNS integration

- moto/sagemaker/models.py
- moto/sagemaker/responses.py
- tests/test_sagemaker/test_sagemaker_endpoint.py
This is just some very rough work that helped me locally. I assume it needs polishing.
No tests yet...
closes #8783
> fix(sagemaker): supports "AsyncInferenceConfig" for EndpointConfigs

- moto/core/exceptions.py
- moto/core/mime_types.py
- moto/s3/responses.py
- tests/test_s3/test_s3_response_headers.py
> S3: Add Content-Type=application/xml headers where appropriate

- moto/resourcegroups/exceptions.py
- moto/resourcegroups/models.py
- tests/test_resourcegroups/test_resourcegroups.py
> ResourceGroups: support retrieval by the name or the ARN of the resource group

- IMPLEMENTATION_COVERAGE.md
- moto/glue/models.py
- moto/glue/responses.py
- tests/test_glue/test_glue.py
Fixes: https://github.com/getmoto/moto/issues/8945
> Glue: Added implementation for delete_resource_policy

- moto/ec2/models/core.py
- moto/ec2/models/transit_gateway_attachments.py
- moto/ec2/models/transit_gateway_route_tables.py
- moto/ec2/responses/transit_gateway_route_tables.py
@bpandola FYI - I finally got around to playing around with your serializer! 
It took some finagling, because the existing models didn't really align with the actual data model, but I think this is an improvement overall.
> EC2: Serialize Transit Gateway Route Tables

- moto/awslambda/models.py
- moto/core/responses.py
fixes https://github.com/getmoto/moto/issues/8969 and https://github.com/getmoto/moto/issues/8971
> Lambda ESM: Support SQS Fifo batch size and TF compatibility

- AUTHORS.md
- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/apigatewayv2.rst
- docs/docs/services/appsync.rst
- docs/docs/services/athena.rst
- docs/docs/services/ce.rst
- docs/docs/services/clouddirectory.rst
- docs/docs/services/cloudtrail.rst
- docs/docs/services/directconnect.rst
- docs/docs/services/ec2.rst
- docs/docs/services/glue.rst
- docs/docs/services/network-firewall.rst
- docs/docs/services/stepfunctions.rst
- moto/athena/models.py
- moto/athena/responses.py
- tests/test_athena/test_athena.py
* Added `get_query_runtime_statistics` to Athena
* Ran `make implementation_coverage` to update implementation coverage
> Added athena get_query_runtime_statistics

- moto/dynamodb/comparisons.py
- moto/dynamodb/responses.py
- tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
- tests/test_dynamodb/test_dynamodb.py
> Dynamodb: UpdateItem(): Validation for ExpressionAttributesNames/Values

- moto/core/responses.py
- moto/core/serialize.py
- tests/test_core/test_response_serialization.py
- tests/test_core/test_serialize.py
Various refactorings and added features to allow finer-grained control and customization of the serialization pipeline.
> Core: Serialization Updates

- moto/ram/models.py
- moto/ram/utils.py
- tests/test_ram/test_ram.py
Hello, again!
In this PR, I'm implementing some refatoring in the `models.py` file. Since I'm willing to implement new logic to interact with the managed permissions specifications, I decided to refactor the models we have and introduce two new model classes, in order to configure the backend for the next RAM implementations. Here's a summary of the changes:
- I created the `ResourceType` class to represent a model of any resource type implemented in the backend of the RAM service;
- I created the `ManagedPermission` class to represent a model of any managed permission implemented in the backend of the RAM service;
- Since I introduced two new classes to represent parts of the service, I added new class attributes for the `ResourceAccessManagerBackend` class. The difference now is that …
> RAM - Some refactoring for the next steps

- moto/ses/responses.py
- tests/test_ses/test_ses_boto3.py
The template only returns the configuration set name.
There are other [ConfigurationSetAttributeNames](https://docs.aws.amazon.com/ses/latest/APIReference/API_DescribeConfigurationSet.html) that should be added in the future, like `trackingOptions | deliveryOptions | reputationOptions`. Same with other types of destinations like `CloudWatchDestination` and `KinesisFirehoseDestination` .
Related to https://github.com/localstack/localstack/issues/12722
> SES: add SNS event destinations to describe_configuration_set

- moto/ec2/models/amis.py
- moto/ec2/responses/amis.py
- tests/test_ec2/test_amis.py
> EC2: implement `source-instance-id` filter for DescribeImages

- moto/sdb/exceptions.py
- moto/sdb/responses.py
SimpleDB was super simple to integrate. No model or test updates required.
> SDB: integrate with core response serializer

- moto/logs/models.py
- tests/test_logs/test_logs.py
> [Cloudwatch Logs] Only filter if there is a prefix specified

- moto/awslambda/models.py
- moto/batch/models.py
- moto/codepipeline/models.py
- moto/core/responses.py
- moto/iam/access_control.py
- moto/iam/exceptions.py
- moto/iam/models.py
- moto/iam/responses.py
- tests/test_iam/test_iam.py
- tests/test_iam/test_iam_groups.py
Also a fair bit of clean up and a number of defects fixed.  Some of those existing error code assertions were 🤨
> IAM: integrate exceptions with core serializer

- moto/elasticache/exceptions.py
- moto/elasticache/models.py
- moto/elasticache/responses.py
- tests/test_elasticache/test_elasticache.py
Straightforward integration with just a few model attributes added or renamed.  Some additional test coverage added as well.
> [!WARNING]
> This service had large, complex XML templates with pretty weak test coverage overall.  There's a better chance than usual that this PR causes a regression--although anything that might crop up will be easier to address.
> ElastiCache: integrate with core response serializer

- moto/sts/exceptions.py
- moto/sts/models.py
- moto/sts/responses.py
No model or test changes required.
> STS: integrate with core response serializer

- moto/eks/models.py
- moto/eks/responses.py
- moto/eks/urls.py
- tests/test_eks/test_eks.py
- tests/test_eks/test_eks_constants.py
This PR addresses https://github.com/getmoto/moto/issues/9118 by adding support for  [update_cluster_config](https://docs.getmoto.org/en/latest/docs/services/eks.html#:~:text=update_cluster_config)
> [EKS] Adding support for update-cluster-config

- moto/config/models.py
With the new unified [request parsing/response serialization](https://github.com/getmoto/moto/issues/9073) in Moto, we are deprecating and eventually removing bespoke code, like [AWSServiceSpec](https://github.com/getmoto/moto/blob/de1b65e025ee1edbad17ae8f85c9402559e4e4f8/moto/core/responses.py#L1108), that has now been superseded.
> Config: remove `AWSServiceSpec` dependency

- moto/iot/models.py
- moto/iot/responses.py
- moto/iot/utils.py
- tests/test_iot/test_iot_billing_groups.py
- tests/test_iot/test_iot_cloudformation.py
- tests/test_iot/test_iot_things.py
* Implement `BillingGroup` support for AWS IoT Core
* Implement `AWS::IoT::BillingGroup` Cloudformation object
> IoT: BillingGroup support

- moto/glue/exceptions.py
- moto/glue/models.py
- moto/glue/responses.py
- moto/glue/utils.py
- tests/test_glue/test_glue.py
Been working on implementing glue workflow functionality, but I found I needed to improve a bunch of trigger sub-fields in order for the backend to start using their content to set up workflows.
> Glue trigger sub objects

- moto/iot/models.py
- tests/test_iot/test_iot_search.py
Hello,
Here is additional support for  IoT Search when using thing groups matching that should also include billing groups
> feat: add iot search on thing and billing  groups

- moto/core/serialize.py
- tests/test_core/test_serialize.py
https://smithy.io/2.0/aws/protocols/aws-query-protocol.html#aws-protocols-awsquerycompatible-trait
> Serializer: support `awsQueryCompatible` trait

- moto/iot/models.py
- tests/test_iot/test_iot_search.py
* Enhance IoT `search_index` API capabilities by adding a logical expression handling (doc: https://docs.aws.amazon.com/iot/latest/developerguide/query-syntax.html)
> IoT: Enhance search_index query syntax

- moto/kinesis/models.py
- moto/kinesis/responses.py
- tests/test_kinesis/test_kinesis_boto3.py
> feat: implement kinesis DescribeLimits API

- moto/servicecatalogappregistry/models.py
- moto/servicecatalogappregistry/responses.py
- moto/servicecatalogappregistry/urls.py
- tests/test_servicecatalogappregistry/test_servicecatalogappregistry.py
Changes to accept requests to /configuration, for put and get operations to set the configuration of account/region AppRegistry.
> [AppRegistry] get/put_configuration

- IMPLEMENTATION_COVERAGE.md
- docs/docs/services/mediapackagev2.rst
- moto/backend_index.py
- moto/mediapackagev2/__init__.py
- moto/mediapackagev2/exceptions.py
- moto/mediapackagev2/models.py
- moto/mediapackagev2/responses.py
- moto/mediapackagev2/urls.py
- moto/mediapackagev2/utils.py
- tests/test_mediapackagev2/test_interaction_mediapackage_v1_and_v2.py
- tests/test_mediapackagev2/test_mediapackagev2.py
Fixes #8328 
Support for the following methods:
- create_channel()
- create_channel_group()
- delete_channel()
- delete_channel_group()
- get_channel()
- get_channel_group()
- list_channel_groups()
> Service: MediaPackageV2
