moto/scheduler/responses.py, tests/test_scheduler/test_scheduler.py
The `scheduler:UpdateSchedule` method is broken when using schedule groups since it cannot find the targeted schedule:
```
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the UpdateSchedule operation: Schedule not found
```
The issue is that the retrieved parameter is `groupName` whereas the right parameter for the UpdateSchedule seems to be `GroupName`.
Also, added a new test for this use case.
=> Scheduler: Fix update_schedule raising ResourceNotFound errors when using schedule groups

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3_copyobject.py
Hello!
This PR should fix the issues mentioned in #6263
I tried to be as exhaustive as possible in the tests to allow reproduction of the current issues. I've also extensively tested those against AWS.
This would fix the following:
- Don't use the following from the source key:
- `ServerSideEncryption`
- `BucketKeyEnabled`
- `SSEKMSKeyId`
- `StorageClass`
- `ACL`
- `ObjectLockMode`
- `ObjectLockRetainUntilDate`
- `ObjectLockLegalHoldStatus`
- Use and set those parameters to the destination key:
- `ObjectLockMode`
- `ObjectLockRetainUntilDate`
- `ObjectLockLegalHoldStatus`
- Rework the check to allow copying "in-place"
- Return `x-amz-copy-source-version-id` if the source bucket/key was versioned
If anything is missing, feel free and I'll try to fix it asap!
=> update CopyObject logic

docs/docs/multi_account.rst
Problem statement: default account id in docs does not correspond with DEFAULT_ACCOUNT_ID in moto model.
=> Fix default account id in docs

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3_multipart.py
Current implementation unquotes key two times, firstly in `self.backend.put_object` and then in `self.backend.put_object_acl` -> `self.get_object`. To fix this issue I have exposed `key_is_clean` in `put_object_acl` and set it to `True`.
=> Do not unquote the key two times on multipart upload complete

moto/s3/responses.py, tests/test_s3/test_s3_lock.py
As reported in #6294, `PutObjectRetention` and `PutObjectLegalHold` would not take into account the `versionId` as it was not accessing it the same way as `PutObjectTagging` for example. I've pulled the retrieval of the `versionId` outside of the `if` blocks, so that all operations needing it could access it.
I've ran the tests against AWS as well and it confirms the behaviour the user was expecting.
=> fix S3 PutObjectRetention and PutObjectLegalHold not using versionId

moto/cloudformation/models.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
=> Cloudformation: delete_stack_instances() can remove multiple regions

moto/s3/responses.py, tests/test_s3/test_s3_copyobject.py
This PR would fix #6307. 
When copying in place, we would try to access the already overwritten key and it would raise an exception.
This makes use of the new key to calculate the checksum.
=> S3: fix copy in place when requesting checksum

moto/s3/models.py, moto/s3/utils.py, tests/test_s3/test_s3_copyobject.py, tests/test_s3/test_s3_utils.py
While working against AWS, I realised moto was returning different checksum after copying an object and recalculating its checksum. It seems the calculation was bit wrong, as it was using `hexdigest` instead of the binary `digest` when passing the hash to the base64 encoding.
I've tried to add a test to cover all checksum calculation by using a checksum recalculation property of `CopyObject`.
Also fixed CopyObject behaviour, when copying a key that has a Checksum, if not asked to be recalculated, it will also copy it to the destination key. This has been verified with AWS (same with the values, so we can check that the recalculation works properly, even when not provided by boto in the first request like in `test_copy_key_boto3_with_both_sha256_checksum`).
=> S3: fix checksum calculation

moto/core/models.py, tests/test_core/test_importorder.py
=> Core: Prevent duplicate handlers when calling patch_client

moto/autoscaling/responses.py, tests/test_autoscaling/test_autoscaling.py
AWS recently added support of metric math for target tracking scaling and changed scheme by adding new field `Metrics` to `CustomizedMetricSpecification`.
AWS blog announcement - https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ec2-auto-scaling-supports-metric-math-target-tracking-policies/
This PR adds `Metrics` to moto responses for ec2 target tracking scaling.
=> Autoscaling: Add metrics for E2 target tracking scaling

moto/sns/models.py, moto/sns/responses.py, moto/sns/utils.py, tests/test_sns/test_publishing_boto3.py, tests/test_sns/test_subscriptions_boto3.py, tests/test_sns/test_utils.py
This resolves: https://github.com/getmoto/moto/issues/6087
[AWS blog article about the feature](https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/)
1. Recognition of the [`FilterPolicyScope` attribute](https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html#sns-message-filtering-scope) for an SNS subscription
2. Validation of the [filter policy's complexity](https://docs.aws.amazon.com/sns/latest/dg/subscription-filter-policy-constraints.html)
3. Actual logic for filtering the messages based on `FilterPolicyScope` that's set
Both 1 and 2 were pretty much taken as-is from https://github.com/localstack/moto/pull/62.
The biggest change is in the `_matches_filter_policy` function, I've created subfunctions for checking the actual …
=> sns: support FilterPolicyScope attribute, including filtering

moto/s3/responses.py, tests/test_s3/test_server.py
Followup to #6121 and #6157 
Typo: We should return `Accept-Ranges`, not `AcceptRanges`
=> S3: Accept-Ranges headers should have dash

moto/events/models.py, moto/sns/models.py, moto/utilities/arns.py, tests/test_sns/test_topics_boto3.py
This PR introduces cross-account support for SNS topics.
This basically means that topics will now be retrieved from the appropriate backend based on the value of account ID and region in the ARN. Any account can now retrieve an SNS topic with its ARN.
Cross-account access now works for `GetTopicAttributes`, `SetTopicAttributes`, `AddPermission`, `RemovePermission`, `DeleteTopic`, `Subscribe`, `ListSubscriptionsByTopic`, `Publish`, similar to AWS. 
IAM enforcement is left out of scope.
=> SNS: Cross-account access for topics

moto/organizations/models.py, tests/test_organizations/test_organizations_boto3.py
add tags to FakePolicy under organizations client. 
Reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations/client/tag_resource.html#tag-resource
=> add tags to service-control-policies (organizations client)

moto/apigateway/models.py, requirements-dev.txt, tests/test_apigateway/test_apigateway_importrestapi.py, tests/test_apigateway/test_apigateway_putrestapi.py
`typing_extensions` released version 4.6.0 last night, which broke things for Python 3.7 - see https://github.com/getmoto/moto/actions/runs/5053892087/jobs/9068737646
Pinning it to an older version until we figure out why
=> Pin typing_extensions for Py3.7

.github/workflows/test_sqs.yml, moto/core/exceptions.py, moto/sqs/models.py, moto/sqs/responses.py, moto/sqs/utils.py, moto/utilities/constants.py
=> SQS: Support JSON format

moto/ec2/models/key_pairs.py, moto/ec2/responses/key_pairs.py, tests/test_ec2/test_key_pairs.py
currently the EC2 Key Pair model doesn't expose the `CreateTime` property (this property [is returned](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_key_pairs.html) by `boto3`, however)
I've implemented this by following the same pattern established with the `CreateDate` property on an IAM User in `moto`
=> add CreateTime property to EC2 key pairs

docs/docs/services/sns.rst, moto/sns/models.py, moto/sns/responses.py, tests/test_sns/test_topics_boto3.py
This PR includes a small fix for the error message when topic is not found. It is changed to match AWS (checked for following operations):
- list-subscriptions-by-topic
- add-permission
- remove-permission
- publish
- subscribe
- delete-topic
- get-topic-attributes
The delete-topic is fixed not to throw an error for nonexistent topics because it is [idempotent](https://docs.aws.amazon.com/sns/latest/api/API_DeleteTopic.html)
Also updated is the documented list of implemented SNS operations.
=> SNS: Fix error message when topic is not found

moto/sns/models.py, tests/test_sns/test_topics_boto3.py
Fixes #6354 
Looks like this snuck in with #6330. Cross-account access for topic is good, but we should not allow access across regions.
@viren-nadkarni Do you see any problems with this change?
=> SNS: Disable cross-region access

moto/ssm/models.py, tests/test_cloudformation/test_cloudformation_stack_integration.py
The current SSM model does not provide the PhysicalResourceId, resulting in an empty string value when calling the `list_stack_resources` from a CloudFormation client.
=> SSM: Implement physical_resource_id property

moto/dynamodb/models/dynamo_type.py, moto/dynamodb/models/table.py, moto/dynamodb/models/utilities.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/models/test_item.py, tests/test_dynamodb/models/test_utilities.py, tests/test_dynamodb/test_dynamodb.py
Improves ProjectionExpressions in scan/query/get_item operations.
The old method would create a copy of the Item and then remove unwanted keys, acting as a filter.
That makes it difficult to filter lists, especially if there are multiple expressions acting on the same list (`listkey[0].a,listkey[1].a`).
This PR introduces a new approach that works the other way around: it recreates a new dictionary containing _just_ the value specified by the expression: `{"listkey": [..]}`.
These partial dictionaries are merged together afterwards to create the final result.
Fixes #6360
=> DynamoDB: Support projection expressions in lists

moto/ec2/models/availability_zones_and_regions.py
We found cases where LocalStack users where unable to do a create_subnet for existing availability zones. This led to a investigation of missing zones.
* Add found missing availability zones
Due to my AWS account not being activated for certain regions, I was unable to check some regions: af-south-1, ap-east-1, ap-southeast-3, eu-south-1, me-south-1, cn-north-1, cn-northwest-1, us-gov-west-1, us-gov-east-1
I created a little script to find missing zones:
```python
#!/usr/bin/env python3
import dataclasses
import boto3
@dataclasses.dataclass
class Zone:
region_name: str
name: str
zone_id: str
def check_zones(defined_zones: dict[str, list[Zone]]):
for region, zones in defined_zones.items():
print(f"Processing region {region}")
zone_names = [zone.name for zone in zones]
try:
ec2_client = …
```
=> Add missing/new availability zones

moto/cloudfront/responses.py, tests/test_cloudfront/test_cloudfront_invalidation.py
Fixes #6386
Using the `force_list` parameter ensures that path items are always encapsulated in a list, even if only a single path is supplied.
=> Cloudfront: correct create_invalidation API response when supplying a single path

moto/ses/models.py, moto/ses/responses.py, moto/sesv2/responses.py, tests/test_sesv2/test_sesv2.py
Before we would use query-parameters to get the arguments - but the query-parameters parser sometimes get confused if the body contains a `=`. Considering the parameters are send as JSON, we can just parse the body directly.
The actual message is base64 encoded, so we now decode the message before handing it off to the backend.
Because the message is now in proper email format, we can read and store the `source` and `destinations` of the email (with a few modifications)
=> SESv2: send_email(): raw emails are send as JSON

moto/ecr/models.py, tests/test_ecr/test_ecr_boto3.py
=> ECR: put_image() - ensure that we can overwrite tags on image with multiple tags

moto/awslambda/exceptions.py, moto/awslambda/models.py, moto/awslambda/responses.py, moto/awslambda/urls.py, tests/test_awslambda/test_lambda_layers.py
Fixes #6400 
The `get_layer_version` receives the same fix, so the `LayerName`-parameter can be both a Name and an ARN.
This PR also fixes the error format when creating a function with a non-existing layer. 
Before it would throw a generic `ValueError`. When running tests in ServerMode, `boto3` would constantly retry the request in case the `ValueError` was temporary, resulting in a very slow test (+8 seconds).
Moto now throws a regular `ClientError`, which means `boto3` now immediately understands it's a failure - without having to retry.
=> Lambda: delete_layer_version() now also accepts an ARN

moto/core/base_backend.py, tests/test_awslambda/test_lambda.py, tests/test_stepfunctions/test_stepfunctions.py, tests/test_sts/test_sts.py
This PR extends support of moto to all AWS Partitions.
One can see all Partitions, Regions, and DNS Suffixes with: `curl https://raw.githubusercontent.com/boto/botocore/develop/botocore/data/endpoints.json | jq '.partitions[] | [.partitionName, .partition, .regions, .dnsSuffix]'`
=> Feat: Support All AWS Partitions

moto/ses/models.py, moto/sesv2/responses.py, tests/test_sesv2/test_sesv2.py
In relation to #6399 and #6405,  I noticed that unexpected errors occur for certain inputs.
- The value of the email address specified in Destination can also be a value with a display-name, such as `"foo, bar" <to@example.com>`.
- This could cause the parsing of destinations in `SESBackend.send_raw_email()` to be split into multiple invalid strings because of the simple use of `str.split()`.
- It seems that `email.utils.getaddresses` can be used to correctly parse them.
- In #6405, only `send_email()` was fixed to decode `self.body` as JSON, but it still needed to be fixed elsewhere as well.
- For example, `Topics[].DisplayName` in `create_contact_list()` can be any string. Of course, you can include `"="`!
- This still causes the problem I pointed out in #6399, so `get_params_dict()` …
=> Fix SESV2Response, and SESBackend.send_raw_email

moto/glue/utils.py, tests/test_glue/test_partition_filter.py
Pyparsing 3.1.0 was released (https://github.com/pyparsing/pyparsing/releases/tag/3.1.0) and has added `DelimitedList` in favor of `delimited_list`. This PR handles the announced future deprecation.
Also, the experimental warning on Glue partition filtering is removed. I use this excessively in my tests and found no issues, so I think this is safe to do.
=> pyparsing 3.1.0 support, remove experimental warning on Glue partition filtering

moto/ec2/exceptions.py, moto/ec2/models/route_tables.py, tests/test_ec2/test_route_tables.py
Currently the `EC2.Client.replace_route()` API does not error if a missing route is given, which is inconsistent with AWS behaviour.
The expected error code is `InvalidRoute.NotFound`, in line with what's returned from `delete_route()` and similar cases such as `InvalidRouteTable.NotFound` being returned if an invalid route table ID is given. However, AWS current behaviour is to return `InvalidParameterValue` instead, so that's what this PR gets moto to do (the [docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReplaceRoute.html) are vague about what error code to expect, but this has been manually checked). This issue has been raised with AWS via a case (unfortunately no public link available), but there is not yet agreement to fix this.
=> EC2: Return appropriate error when calling EC2.Client.replace_route() with missing route

IMPLEMENTATION_COVERAGE.md, moto/ssm/models.py, moto/ssm/responses.py, tests/test_ssm/test_ssm_maintenance_windows.py
This PR adds support for the next operations:
=> add support for maintenance window targets

moto/config/models.py, tests/test_config/test_config.py
Fixed logic bug in handling the default empty `exclusionByResourceTypes` dictionary passed in.
=> Fixed bug in new Config recorder logic

moto/ssm/models.py, tests/test_ssm/test_ssm_boto3.py
Resolves https://github.com/getmoto/moto/issues/6416
=> fix: missing type from param update response

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3_config.py, tests/test_s3/test_s3_lifecycle.py
Hi @bblommers,
Some points about the implementation:
- I noticed that also `NoncurrentVersionTransitions` could be a list of multiple transitions so I made some changes to allow also multiple `NoncurrentVersionTransitions`.
- I added the property  `NewerNoncurrentVersions` to `NoncurrentVersionTransitions`. https://docs.aws.amazon.com/AmazonS3/latest/API/API_NoncurrentVersionTransition.html
- I've created 2 new classes `LifecycleTransition` and `LifeCycleNoncurrentVersionTransition` along the lines of `LifecycleRule` but I didn't understand exactly the purpose of `BaseModel` class. Is this approach ok?
- I added also `Transitions` and  `NoncurrentVersionTransitions` to the dict returned by `LifecyleRule.to_config_dict` but I don't understand if I need to respect some structure or …
=> S3: Multiple Transitions in lifecycle configuration

IMPLEMENTATION_COVERAGE.md, docs/docs/services/rds.rst, moto/rds/models.py, moto/rds/responses.py, tests/test_rds/test_filters.py, tests/test_rds/test_rds.py, tests/test_rds/test_rds_clusters.py
SnapshotType is set to `manual` for snapshots created by the user, and set to `automated` for snapshots created when a cluster is deleted.
This applies to both DatabaseSnapshots and ClusterSnapshots.
The `snapshot-type`-filter has also been fixed.
This PR also removes some duplicate validation when copying a snapshot. We now just call the `create..`-method, instead of duplicating the entire logic on copy.
Fixes #6419
=> RDS: Automated snapshots now have the appropriate SnapshotType

IMPLEMENTATION_COVERAGE.md, moto/ssm/models.py, moto/ssm/responses.py, tests/test_ssm/test_ssm_maintenance_windows.py
This PR adds support for some operations related to Maintenance Window Tasks:
I'll rebase it after #6429 is merged
=> add support for ssm maintenance window tasks

moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
There is a small parity issue within the operation `describe-security-group-rules` ([aws-examples-link](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-group-rules.html#examples)) as it is missing the field `GroupId`. This appeared due to a ticket within [localstack](https://github.com/localstack/localstack/issues/8528), which very nicely describes the issue.
This PR is a quick draft to resolve this - I'm not particularly familiar with ec2 or moto (:smile:) and haven't added a test to this yet. something like `assert "GroupId" in rules[0]` [here](https://github.com/getmoto/moto/blob/dab6318f90dba1fdbb758603879e430e038a3c85/tests/test_ec2/test_security_groups.py#L589)? thx for any hints
=> add GroupId to SecurityGroupRules

moto/awslambda/exceptions.py, moto/awslambda/models.py, moto/awslambda/responses.py, tests/test_awslambda/test_lambda.py, tests/test_awslambda/test_lambda_alias.py
- Creates the [list_aliases](https://boto3.amazonaws.com/v1/documentation/api/1.26.85/reference/services/lambda/client/list_aliases.html) functionality
- Redesign internal storage of aliases to correct mistaken implementation (Duplicate alias names could be created under the same lambda pointing to different versions)
- Adds tests for new functionality
- Worth noting I've not included functionality to filter by "version", can be implemented if needed
=> Lambda: create list_aliases functionality

moto/cloudfront/models.py, tests/test_cloudfront/test_cloudfront_distributions.py
If there is only 1 alias, it would be serialized as a string (`"alias1"`), instead of as a list (`["alias1"]`). 
When generating the response, we expect a list of aliases to iterate over. So if we're iterating over a string instead, Moto would return `Aliases=["a", "l", "i", "a", "s"]` instead
=> CF:create_distribution() - fix config with single alias

tests/test_cloudformation/fixtures/single_instance_with_ebs_volume.py, tests/test_cloudformation/fixtures/vpc_single_instance_in_subnet.py, tests/test_dynamodb/models/test_item.py, tests/test_dynamodb/models/test_utilities.py, tests/test_ec2/test_instances.py
- Remove WaitCondition/WaitConditionHandle from CF tests, as we don't support it anyway
- Upgrade tests to use `setup_method` - the `setup`-method is deprecated in pytest
- Use known AMI
=> Techdebt: Remove warnings from tests

moto/ec2/responses/launch_templates.py, tests/test_ec2/test_launch_templates.py
The default response of ec2's DescribeLaunchTemplateVersions fails due to the variable `template` being referenced without assignment [here](https://github.com/getmoto/moto/blob/db002cb95813255a083ed4af24eb68ae3224f31e/moto/ec2/responses/launch_templates.py#L204). The default should be an empty list. This came to light because of an issue report in [localstack](https://github.com/localstack/localstack/issues/8606).
Granted, this is rather an ugly quick fix, but it seems to work. Alternatively the default could be to create an empty launch template? (Open to adjust if you could give me some guidance what would be a more sensible approach here)
=> EC2: fix DescribeLaunchTemplateVersions default response

moto/core/exceptions.py, moto/sns/exceptions.py, tests/test_sns/test_topics_boto3.py
AWS error responses have a field called `Type` which indicates where the blame for the error lies. There is little documentation on this, but HTTP 4xx errors seem to have this field set to `Sender`.
This PR introduces support for this field. To start with, SNS errors are correctly mapped.
The other two templates do not contain the field:
- `SINGLE_ERROR_RESPONSE`: Used for S3 response, see <https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html>
- `ERROR_RESPONSE`: Used for EC2 response, see <https://github.com/boto/botocore/blob/82f6e194716e36c838fc016eddc4a2ef8e449ec4/botocore/parsers.py#L614>
Also see: <https://github.com/boto/botocore/blob/82f6e194716e36c838fc016eddc4a2ef8e449ec4/tests/unit/test_parsers.py#L1200-L1271>
=> Add type field to error response

moto/ecr/models.py, tests/test_ecr/test_ecr_boto3.py
This is a small fix to add name validation for the `repository-name` within ECR's `create-repository`.
Currently there is no name validation during the creation - but the [documentation](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreateRepository.html#API_CreateRepository_RequestSyntax) states that it needs to follow a regex pattern. I found this through a [localstack issue](https://github.com/localstack/localstack/issues/8051).
=> ECR: add CreateRepository name validation

moto/iam/models.py, tests/test_iam/test_iam.py
The error handling for a non-existent policy was not implemented for `attach_role_policy`, (only for `attach_user_policy`).
Also, the error messages did not match the AWS error:
```
"Error": {
"Code": "NoSuchEntity",
"Message": "Policy arn:aws:iam::111111111111:policy/policy-name does not exist or is not attachable.",
"Type": "Sender"
},
```
* Add error handling for KeyError in `attach_role_policy`
* Change error message for `attach_user_policy`
* Add testing this error in `test_attach_detach_user_policy`
* Duplicate `test_attach_detach_user_policy` to usage with roles as `test_attach_detach_role_policy`
=> Fix KeyError when attaching non-existent policy to role

moto/ssm/models.py, tests/test_ssm/test_ssm_boto3.py
This PR fixes an issue where if PutParameter is called without parameter type, it creates an invalid state within SSM. Consequently, all calls to DescribeParameters break.
It is caused by peeking into a default dict which creates an empty list, which itself is the invalid state.
```
$ awslocal ssm put-parameter --name foo --value bar
An error occurred (ValidationException) when calling the PutParameter operation: A parameter type is required when you create a parameter.
```
```
$ awslocal ssm describe-parameters
An error occurred (InternalError) when calling the DescribeParameters operation (reached max retries: 4): exception while calling ssm.DescribeParameters: Traceback (most recent call last):
File "/home/viren/repo/localstack/localstack/aws/chain.py", line 90, in handle
handler(self, …
```
=> SSM: Fix bad state caused by invalid PutParameter request

moto/emr/responses.py, moto/emr/utils.py, tests/test_emr/test_emr_boto3.py
This PR fixes parsing issues for the `Properties` field for `run_job_flow` and `add_job_flow_steps`. 
Enhanced the test to use the `Properties` and fixed response templates.
=> EMR: fix handling of Properties for job flows

moto/s3/responses.py, tests/test_s3/test_s3_tagging.py
- S3 bucket and object tagging can accept empty values.
- https://github.com/localstack/localstack/issues/8598
- https://github.com/localstack/localstack/pull/8638
=> S3: fixed tagging

moto/sqs/models.py
When sending messages in batch to AWS SQS a `BatchRequestTooLong` is thrown by AWS if the length of all the messages put together is greater than the AWS limit. See AWS documentation [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html#:~:text=Status%20Code%3A%20400-,BatchRequestTooLong,-The%20length%20of).
This PR fixes the logic that determines if a `BatchRequestTooLong` exception should be thrown. Prior to this PR, a `BatchRequestTooLong` exception is thrown only if a message in the batch of messages to be sent is greater than the AWS limit. After this PR, an exception will be thrown if the sum of all the messages exceeds the AWS limit.
=> Fix: SQS BatchRequestTooLong exception

moto/backend_index.py, moto/glue/glue_schema_registry_constants.py, moto/ssm/models.py
The two range-based regexs were clearly incorrect.  The unescaped periods in the `meteringmarketplace` urls seem like an oversight, unless those urls work in some unique way I'm not understanding.
=> Fix code scanning alerts

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
When a user is disabled, it should raise a `NotAuthorizedException` exception when attempting to login
=> Deny login if user account is disabled

moto/cloudfront/models.py, tests/test_cloudfront/test_cloudfront.py
Fixes #6546 
Also fixes a bug where `update` fails when no `Aliases` or `OriginSslProtocols` are provided
=> Cloudfront: update_distribution() now supports DefaultRootObject

moto/dynamodb/models/dynamo_type.py, tests/test_awslambda/test_lambda_eventsourcemapping.py
Calling `to_json` on a nested item (i.e., a DynamoDB Item that contains a Map) currently throws an error:
`TypeError: Object of type DynamoType is not JSON serializable`
=> DynamoDB: Support sending nested items to ESM's

moto/sns/models.py
This fixes a bug when publishing to an SNS FifoTopic. Currently any message published to a FifoTopic results in the following error:
> The topic should either have ContentBasedDeduplication enabled or MessageDeduplicationId provided explicitly
=> [Bug fix] Add required deduplication_id parameter to sns:PublishBatch

moto/cloudwatch/metric_data_expression_parser.py, moto/cloudwatch/models.py, moto/cloudwatch/responses.py, tests/test_cloudwatch/test_cloudwatch_expression_parser.py, tests/test_cloudwatch/test_cloudwatch_expressions.py
Fixes #3323 
Biggest fix: Moto no longer throws a KeyError when `MetricStat` is not supplied.
If neither `MetricStat` or `Expression` are supplied, we throw an error (in line with AWS)
Expression support:
Currently only supports for extremely simple use cases, where the entire expression consists of the `Id` of another Query.
Once people request support for more complicated expressions, we can always extend this.
=> CloudWatch: get_metric_data() now support (simple) Expressions

moto/resourcegroupstaggingapi/models.py, scripts/dependency_test.sh, setup.cfg, tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_glue.py
Fixes #5931 
This PR also adds (almost) all dependencies for `moto[resourcegroupstaggingapi]`, as they were missing until now.
Test run that validates these dependencies are enough: https://github.com/bblommers/moto/actions/runs/5708608444
=> ResourceGroupsTaggingAPI: Support Glue resources

moto/awslambda/models.py, tests/test_awslambda/test_lambda.py
If a lambda function's working directory is not defined, it should not be reported. Adjust model to omit member entirely instead of reporting it with an empty string in this case.
Fixes #6583
=> AWSLambda: Don't report undefined working directory

tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_glue.py
Running tests in parallel sometimes results in resources with duplicate keys
=> Techdebt: Ensure RT API has unique tag keys

moto/awslambda/models.py, tests/test_awslambda/test_lambda.py
This apparently got missed, resulting in a null operation when this method was called for an ECR-based lambda.
This fix consolidates code management logic into a single internal helper method, and then adjusts `create_function()` and `update_function_code()` implementations to use that helper. There are a few puzzling aspects to the logic which are worthy of further review by someone who has a clue:
* The check for S3 input is slightly different; I went with the old "update" version which fires only when both `S3Bucket` and `S3Key` are present (vs old create behavior that didn't directly check `S3Key`). The Amazon documentation is vague regarding whether or not both must be present. I am uncertain if `and "S3Key" in updated_spec` should remain or be removed (or worse, continue to be …
=> Add ECR support to lambda `update_function_code()`

.github/workflows/tests_servermode.yml, moto/core/responses.py, moto/core/utils.py, moto/core/versions.py, moto/s3/models.py, moto/s3/responses.py, moto/s3/utils.py, tests/test_core/test_utils.py, tests/test_s3/test_s3_utils.py
Python >= 3.8 uses newer versions of `werkzeug` (>2.3.x). Those `werkzeug` versions handle incoming requests slightly differently, by exposing the original path to the developer.
Older versions of werkzeug expose the quoted version of the path.
Most of this PR is spent ensuring that the path that we extract the path in the same format, regardless of the request coming in:
- botocore requests
- werkzeug (< 2.3.x)
- werkzeug (>= 2.3.x)
Iv'e also moved the `clean_key_name` to `responses.py` - we can tackle that at the same time as we `clean` the incoming werkzeug name.
Note that the actual implementation hasn't changed - we just convert the input format to make things work.
This also opens the door to (finally) upgrade the python version used in the official Docker image.
=> Techdebt: Run ServerMode tests in newer Python versions

moto/s3/models.py, moto/s3/responses.py, moto/s3/select_object_content.py, tests/test_s3/test_s3_select.py
Fixes #6613 
Also reset the default delimiter to `\n`, instead of a comma
=> S3: select_object_content() now takes RecordDelimiter into account

moto/core/custom_responses_mock.py, moto/core/responses.py, moto/core/versions.py, moto/databrew/responses.py, moto/emr/responses.py, moto/managedblockchain/responses.py, moto/route53/responses.py, moto/s3/responses.py
Also moves the `responses` version logic into `moto/core/versions.py`
=> Techdebt: Reuse parsed URL across services

moto/dynamodb/models/__init__.py, moto/dynamodb/models/table.py, moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
=> DynamoDB: FilterExpressions/ProjectionExpressions cannot be empty

moto/sagemaker/models.py
Fixes #6615 
The current implementation is broken. `datetime_now` represented a timezone-aware datetime, but `creation_time_before_datetime` a timezone-naive datetime. When comparing them, Python throws the following error:
`TypeError: can't compare offset-naive and offset-aware datetimes`
This used to work by accident, because of https://github.com/spulec/freezegun/issues/89 - `freezegun` would create a timezone-naive datetime when calling `datetime.utcnow()`. 
Changing this to `datetime.now(pytz.UTC)` causes `freezegun` to work properly.
=> Sagemaker: list_model_package(): Fixed a bug in CreationTime params

moto/core/versions.py
(new contributor here)
I just unrolled the [Development Installation](http://docs.getmoto.org/en/latest/docs/contributing/installation.html) guide that states python 3.x as requirement.
My workstation runs python3.11, I created a dedicated venv. When running the `make test` on master (as of writing at c8b5470e25012477f817a619e88f9ad1bea08bbe) I came across a mypy error:
```
$ mypy --install-types --non-interactive
moto/core/versions.py:6:5: error: Name "version" already defined (possibly by an import)  [no-redef]
``` 
I was able to reproduce the same issue in the CI by running the lint suite with python3.11 [with a one-line edit](https://github.com/ajoga/moto/commit/5543db1a644c553d1b3c56d56f8b584f8c1a23b0) : https://github.com/ajoga/moto/actions/runs/5842743552/job/15844189693 
Using …
=> Techdebt: Re-add an ignore for mypy

tests/test_awslambda/test_lambda_alias.py, tests/test_ec2/test_server.py
Bit of tidying up ... Removed sure imports that were not being used and not used by the tests for their associated AWS service.  Performed some pylint cleanup at the same time.
=> Techdebt: Remove sure import if not used by service

moto/awslambda/models.py, tests/test_awslambda/test_lambda.py
In real life, AWS lambda does not allow unbounded concurrency. Refine behavior of `put_function_concurrency()` to provide an approximation of the correct behavior:
* By default, no concurrency limits are enforced (old behavior);
* If environment variable `MOTO_LAMBDA_CONCURRENCY_QUOTA` is defined (to a positive integer), then enforcement is enabled (use 1000 to match the AWS default limit);
* If cumulative reservations result in fewer than 100 unreserved instances (i.e. by default, 900 reserved instances) then an `InvalidParameterValueException` is raised and no change is made;
* The simulation applies the limit across all defined functions (rather than only functions in the same account and region) -- my judgment is that this distinction is unimportant in nearly all test scenarios (and …
=> awslambda: enforce concurrency quota in `put_function_concurrency()`

moto/awslambda/exceptions.py, moto/awslambda/responses.py, tests/test_awslambda/test_lambda.py, tests/test_awslambda/test_lambda_layers.py
In real life, `lambda:CreateFunction` fails if the caller attempts to create a function that already exists. Accurately model this behavior.
Yes, the actual AWS response really is written in broken English. ;-)
=> awslambda: `create_function()` should fail on duplicate

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
This PR is a proposal to fix the issue raised up at #6697
When the user initiates a USER_SRP_AUTH authentication flow, it's challenged with the password verification, in this scenario, if the user status is FORCE_CHANGE_PASSWORD, cognito should responde with a new challenge to require the new password (NEW_PASSWORD_REQUIRED) instead of authorizing the user.
Once the user provides a new password, the access token is emitted.
=> CognitoIDP: user status FORCE_CHANGE_PASSWORD in USER_SRP_AUTH should require new password

moto/kms/models.py, moto/kms/utils.py, tests/test_kms/test_kms_boto3.py
- Adding string Enum of supported kms key specs (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kms/client/create_key.html)
- Adding a method to validate that a given key spec is supported or not.
=> KMS: Validate key specs

moto/rds/models.py
ClusterSnapshot template is missing the TagList.
This means that describe_db_cluster_snapshots will make all the snapshots look like there are not tags.
This will solve #6695
=> RDS: Fix ClusterSnapshot template to include tags

moto/kms/models.py, moto/kms/utils.py, tests/test_kms/test_kms_boto3.py, tests/test_kms/test_utils.py
- `signing_algorithms` property returns the correct signing algorithms for the given key spec.
- Adding string enum for signing algorithms.
- Adding `KeySpec` arguments to pass the unittests.
| key spec | signing algorithm |
| :--- | :--- |
| `SYMMETRIC_DEFAULT` | |
| `RSA_2048, 3072, 4096` | `RSASSA_PSS_SHA_256` |
|  | `RSASSA_PSS_SHA_384` |
|  | `RSASSA_PSS_SHA_512` |
|  | `RSASSA_PKCS1_V1_5_SHA_256` |
|  | `RSASSA_PKCS1_V1_5_SHA_384` |
|  | `RSASSA_PKCS1_V1_5_SHA_512` |
| `ECC_NIST_P256, P256K1` | `ECDSA_SHA_256` |
| `ECC_NIST_P384` | `ECDSA_SHA_384` |
| `ECC_NIST_P512` | `ECDSA_SHA_512` |
| `SM2` | `SM2DSA` |
ref: https://docs.aws.amazon.com/kms/latest/developerguide/asymmetric-key-specs.html
=> KMS: refactoring `signing_algorithms` property

moto/kms/models.py, moto/kms/utils.py, tests/test_kms/test_kms_boto3.py
- Expanding `generate_private_key` method to be able to return multiple private key algorithm by using abstract class.
- Add `RSASSA_PSS_SHA_256` private key.
- We can use the following unittest for this changes.
https://github.com/getmoto/moto/blob/5e1b166f2521eacd737f2ccb241fbc0b2e8bb931/tests/test_kms/test_kms_boto3.py#L1166-L1194
=> KMS: Add `RSASSA_PSS_SHA_256` private key

docs/docs/server_mode.rst
There is a disused method shown in `docs/docs/server_mode.rst`, which is `.should.equal`
it is better that using `assertEqual` instead of `.should.equal`
=> Docs: refactor document for server mode (TestThreadedMotoServer)

moto/kms/utils.py, tests/test_kms/test_kms_boto3.py, tests/test_kms/test_utils.py
Support key sizes 3072 and 4098 key sizes for RSA private key.
=> KMS: Support 3072 and 4098 key sizes for RSA

.github/workflows/release.yml, CHANGELOG.md, Dockerfile, moto/__init__.py
Long time coming - but this was blocked by #6602 until now
Should provide a significant speedup across the board.
=> Docker image is now based on Python 3.11

moto/sqs/models.py, tests/test_sqs/test_sqs.py
Hello,
I ran into an issue yesterday with SQS and sending batch messages. The actual error causing my test failures was not surfaced and it was overwritten by the `failedInvalidDelay` catch. Current local `boto3` version is `1.28.33` and the `moto` version is `4.2.0`.
Actual boto3 behavior:
```
>>> import boto3
>>> sqs = boto3.client("sqs", region_name="us-west-1")
>>> sqs.create_queue(
...     QueueName="adrian-test.fifo", Attributes=dict(FifoQueue="true")
... )
{'QueueUrl': 'https://sqs.us-west-1.amazonaws.com/123456789012/adrian-test.fifo', 'ResponseMetadata': {'RequestId': 'e7a00bb0-ec4a-5685-8fd9-56d16051e640', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'e7a00bb0-ec4a-5685-8fd9-56d16051e640', 'date': 'Thu, 24 Aug 2023 16:48:27 GMT', 'content-type': 'text/xml', …
```
=> SQS: Fix broad catch statement for failedInvalidDelay

moto/sqs/models.py
Follow up to https://github.com/getmoto/moto/pull/6721
I extracted the individual SQS message validation logic into a new `_validate_message` method and I am calling that from `send_message_batch` for all messages before attempting to send them via `send_message`. This replicates boto3 behavior. All tests are passing locally without changes required.
Tagging @bblommers for visibility.
=> SQS: perform validation on all messages before attempting a send

moto/logs/models.py, moto/logs/responses.py, tests/test_logs/test_integration.py
Fixes #6713 
SubscriptionFilters are now a first-class citizen, as part of the `LogGroup`-model:
- They have their own model, instead of being a regular dict
- put_log_events() requests the list of subscription filters when necessary (instead of `LogStream` having to keep a reference to the ARN/filter name)
=> Logs: Support two subscription filters

moto/utilities/paginator.py
Follow-up to #6723 
The build is currently failing for IdentityStore:list_users() in python 3.7. AFAICT this is due to the fact that `type(x) == dict` does not work for `OrderedDicts` in python 3.7. Using the `is_instance` instead should fix the build.
=> Techdebt - Allow OrderedDict when paginating

moto/core/responses.py, moto/core/utils.py, moto/s3/responses.py, tests/test_core/test_responses.py
Fixes #6692 
This PR enable support for request compression, coming to an SDK near you. It is a very naive and simple approach, but I intend to fine-tune this as necessary when compression arrives in boto3.
=> Core: Allow request decompression

moto/rds/models.py, moto/resourcegroupstaggingapi/models.py, moto/resourcegroupstaggingapi/responses.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_rds.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Fixes #6688 
Also refactors the `_get_resource_generator` in ResourceGroupTaggingAPI, as it is the same logic across all RDS resource types.
=> ResourceGroupsTaggingAPI: tag_resource() for RDS resources

tests/test_kms/test_kms_boto3.py
Adding tests to check that the verification fails if a different algorithm is used than the one used when signing.
=> KMS: Add fail test cases for signing algorithms of RSA

moto/kms/utils.py, tests/test_kms/test_kms_boto3.py
Adding the following signing algorithms and unittests.
- `RSASSA_PKCS1_V1_5_SHA_256`
- `RSASSA_PKCS1_V1_5_SHA_384`
- `RSASSA_PKCS1_V1_5_SHA_512`
Refactoring that a methods to select padding and hash functions is extracted.
=> KMS: Add `RSASSA_PKCS1_V1_5_SHA_256, 384, 512` signing algorithms

IMPLEMENTATION_COVERAGE.md, docs/docs/services/logs.rst, moto/logs/logs_query/__init__.py, moto/logs/logs_query/query_parser.py, moto/logs/models.py, moto/logs/responses.py, tests/test_logs/test_logs.py, tests/test_logs/test_logs_query/test_boto3.py, tests/test_logs/test_logs_query/test_query.py, tests/test_logs/test_logs_query/test_query_parser.py
Fixes #5015
Includes a basic parser for Logs Queries: 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AnalyzingLogData.html
Tested query:
```
fields @timestamp, @message, @logStream, @log
| sort @timestamp desc
| limit 20
```
Supercedes #6054
=> Logs: get_query_results() and describe_queries()

.github/workflows/tests_decoratormode.yml, .github/workflows/tests_servermode.yml, Makefile, moto/awslambda/models.py, tests/test_apigateway/test_apigateway_cloudformation.py, tests/test_awslambda/test_lambda.py, tests/test_awslambda/test_lambda_alias.py, tests/test_awslambda/test_lambda_concurrency.py, tests/test_awslambda/test_lambda_eventsourcemapping.py, tests/test_awslambda/test_lambda_function_urls.py, tests/test_awslambda/test_lambda_invoke.py, tests/test_awslambda/test_lambda_layers.py, tests/test_awslambda/test_lambda_policy.py, tests/test_awslambda/test_lambda_tags.py, tests/test_awslambda/utilities.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py, tests/test_cloudformation/test_cloudformation_stack_integration.py, tests/test_config/test_config_rules_integration.py, tests/test_events/test_events_lambdatriggers_integration.py, tests/test_logs/test_integration.py, tests/test_logs/test_logs_query/test_boto3.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py, tests/test_s3/test_s3_lambda_integration.py, tests/test_secretsmanager/test_secretsmanager.py, tests/test_secretsmanager/test_server.py, tests/test_sqs/test_sqs.py, tests/test_sqs/test_sqs_integration.py
1. Changes the default Lambda runtime to Python 3.11
2. Refactor AWSLambda tests to re-use same function for multiple tests
3. Removes a duplicate test
4. XFail a test that fails intermittently. It has something to do with the fact that we run Lambda tests in parallel - potentially because the Docker process times out while processing the response
5. Downloads the Docker image for the Lambda runtime before tests start, to prevent tests pulling the same image multiple times
6. Creates unique names for some SQS test queues, to prevent tests from hitting each others queues
=> Techdebt: Streamline AWSLambda/Docker tests

tests/test_core/test_ec2_vpc_endpoint_services.py, tests/test_ec2/test_vpc_endpoint_services_integration.py
These tests are called from EC2, but collect data from all services
There are some issues with running these tests in parallel - running them as part of 'moto/core' avoids that problem
Previous attempts to fix this problem:
#6631 
#6682
=> Techdebt: Reenable EC2 VPC endpoint services tests

moto/amp/urls.py, moto/apigateway/urls.py, moto/apigatewayv2/urls.py, moto/appconfig/urls.py, moto/appsync/urls.py, moto/awslambda/urls.py, moto/cloudfront/urls.py, moto/cognitoidp/urls.py, moto/core/responses.py, moto/databrew/urls.py, moto/ebs/urls.py, moto/elastictranscoder/urls.py, moto/glacier/responses.py, moto/glacier/urls.py, moto/greengrass/urls.py, moto/guardduty/urls.py, moto/instance_metadata/urls.py, moto/iot/urls.py, moto/managedblockchain/exceptions.py, moto/managedblockchain/urls.py, moto/mq/urls.py, moto/pinpoint/urls.py, moto/quicksight/urls.py, moto/route53/urls.py, moto/s3/urls.py, moto/s3control/responses.py, moto/s3control/urls.py, moto/scheduler/urls.py, tests/test_core/test_server.py, tests/test_s3/test_s3_file_handles.py
Fixes #6745
Currently, for the following services:
```
amp
apigateway
apigatewayv2
appconfig
appsync
awslambda
cloudfront
cognitoidp
databrew
ebs
elastictranscoder
glacier
greengrass
guardduty
instance_metadata
iot
managedblockchain
mq
pinpoint
quicksight
route53
s3
s3control
eventbridgescheduler
```
we use a single instance of the respective `...Response` class to handle all the requests.
In LocalStack, this leads to issues with parallel requests influencing each others state, most notably of region and account.
There are a couple of different ways to fix this, we chose one that was minimally intrusive to the existing logic, but ensured a separate instance of the Response class for every request.
Unaffected services use the `dispatch` method. There are some services which use the …
=> Fix usage of a single object instances for multiple concurrent requests

moto/core/models.py, moto/managedblockchain/exceptions.py, moto/managedblockchain/responses.py, moto/managedblockchain/urls.py, tests/test_managedblockchain/test_managedblockchain_invitations.py, tests/test_managedblockchain/test_managedblockchain_members.py, tests/test_managedblockchain/test_managedblockchain_networks.py, tests/test_managedblockchain/test_managedblockchain_nodes.py
Simplify request parsing by delegating it to the `dispatch`-method
(FYI @dfangl - this already removes some of the `method_dispatch`-invocations introduced in #6746 )
Remove the custom `exceptionhandler`, as this is also handled by `dispatch`
Reduce some logic in the tests.
Configure boto3 to only retry requests once. Boto3 will automatically retry these requests up to 5 times, but we know that they fail, so there is no reason to wait for them to fail 5 times.
This PR reduces the test time for `managed blockchain` from **22** to **6** seconds
=> Techdebt: Simplify ManagedBlockchain setup & tests

moto/ec2/models/transit_gateway.py, moto/ec2/responses/transit_gateways.py, tests/test_ec2/test_transit_gateway.py
Fixes a small parity issue with AWS. Here's an link to the [examples](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-transit-gateway.html#examples) and I also tried it out against actual AWS and it does indeed populate the ARN on create.
This also fixes this bug https://github.com/localstack/localstack/issues/9042 in `localstack`
=> EC2: Add missing transitGatewayArn field for CreateTransitGatewayResponse

moto/ses/models.py, tests/test_ses/test_ses_boto3.py
=> SES: set_identity_mail_from_domain() - the Identity can be an email

.github/workflows/tests_servermode.yml, moto/ec2/models/amis.py, moto/settings.py, tests/__init__.py, tests/test_autoscaling/test_launch_configurations.py, tests/test_ec2/test_amis.py, tests/test_ec2/test_elastic_block_store.py, tests/test_ec2/test_instances.py, tests/test_ec2/test_windows.py, tests/test_special_cases/test_custom_amis.py, tests/test_ssm/test_ssm_ec2_integration.py, tests/test_ssm/test_ssm_ecs_images.py
When executing our tests, Moto spends significant time (re-)creating the default AMI's and volumes that come with it.
For the vast majority of tests, we don't actually need that - so we can safely skip that functionality.
=> Techdebt: Do not load EC2 images unless necessary

moto/core/responses_custom_registry.py
An attempt to fix https://github.com/getmoto/moto/issues/6763
The issue with:
```python
all_possibles = responses._default_mock._registry.registered
all_possibles.extend(self._registered[request.method])
```
is that the original `all_possibles` gets mutated and keeps growing bigger and bigger.
We verified that behaviour in our project which uses moto.
`all_possibles = responses._default_mock._registry.registered + self._registered[request.method]` gives us a new list each time, instead of mutating the original.
This `.extend()` code exists in versions >= 4.1.13
This is what v4.1.12 does:
https://github.com/getmoto/moto/blob/2543f9af73e5537c8517c78ca79bb03dd24e2a77/moto/core/responses_custom_registry.py#L20
=> Fix memory leak when comparing requests

moto/ec2/models/transit_gateway.py, tests/test_ec2/test_transit_gateway.py
Noticed transit gateways can't be filtered by tags, which is supported in AWS. Wasn't really sure how to do this, since there are several ways to do filters in the different models. Let me know if this isn't the right way to do it.
=> EC2: Support filtering transit gateways by tag

moto/secretsmanager/models.py, tests/test_secretsmanager/test_secretsmanager.py
Fixes the updating of an initial no-value secret.
If a secret was initially created without a value, then subsequent updates causes a `KeyError: None` as `default_version_id` is `None`.
Noticed downstream on the latest Localstack build.
=> fix(secretsmanager): fix update of no-value initial secret

moto/dynamodb/parsing/key_condition_expression.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/models/test_key_condition_expression_parser.py, tests/test_dynamodb/test_dynamodb.py
Fixes #6781 
Verified against AWS
=> DynamoDB: key_condition_expression cannot contain a literal value

moto/core/responses.py, moto/iam/access_control.py, tests/test_core/test_auth.py
Fixes #6782 
**Change 1: Interrogate the headers to find the Action**
Until now, IAM validation only had (verified) support for requests that contained the Action in the body:
`Action=RunInstances&...`
SSM uses the `X-Amz-Target`-header to send this information, so we need to use that instead, if it exists.
**Change 2: Differentiate between `body` and `data`**
The `IAMRequestBase`-class now contains two different attributes that contain request information:
- `data` - a dictionary of the key=value pairs described in the body + querystring + some headers
- `body` - the raw body
Until now, we used the `data`-attribute to calculate the signature of the incoming request, but that is not guaranteed to be the same as the body. That's why we're now sending the (unchanged) `body` along as well, …
=> IAM validation: Now supports SSM requests

moto/s3/models.py, moto/s3/utils.py, tests/test_s3/test_s3_logging.py
**Context**
Related issue: https://github.com/getmoto/moto/issues/6659
This PR enables for moto s3 buckets to enable logging if they have an appropriate bucket policy set (in addition to the existing logic that enables this if an appropriate ACL is set)
**Testing**
Added to existing unit tests.
=> S3: add granting logging perms using bucket policy

moto/athena/responses.py, tests/test_athena/test_athena.py
Fixes #6776 
Simple fix that checks the first command in the sql query and determines the statement type. I based the list of commands off of this page from the AWS Athena docs: [https://docs.aws.amazon.com/athena/latest/ug/ddl-reference.html](https://docs.aws.amazon.com/athena/latest/ug/ddl-reference.html)
=> Athena: make statement type dependent on query command

moto/batch/models.py, moto/batch/utils.py, tests/test_batch/test_utils.py
- Adding Enum for Batch job status and some utility methods.
- Adding unit tests for the methods. 
- Replacing some codes where job status is hard coded.
=> Batch: Using enum for job status

moto/kms/models.py, moto/kms/responses.py, tests/test_kms/test_kms_boto3.py
=> KMS: sign/verify should use the original message, not the base64-version

moto/core/models.py, tests/test_core/test_environ_patching.py
Fixes #6805 
> DynamoDB local version 2.0.0 and greater AWS_ACCESS_KEY_ID can contain only letters (A–Z, a–z) and numbers (0–9). 
>
Little odd that DynamoDB local cares about that, but it is the format that AWS uses for their access keys/secrets - so it makes sense to follow this.
=> Core: Mocked ACCESS_KEY values now adhere to AWS guidelines

moto/core/responses.py, moto/iam/access_control.py, moto/sts/responses.py, tests/test_core/test_auth.py, tests/test_s3/test_s3_bucket_policy.py
This PR uses the validation logic to validate the resource attribute of the principal-attached policies during `sts:AssumeRole`
It relates to the discussion in https://github.com/getmoto/moto/pull/6793#issuecomment-1712505836
What do you think of this draft @bblommers ? I implemented following your directions. I don't have enough experience to make an alternative proposition, and what you offered makes sense. It feels like it's going to be rather intense to implement each map of (service, method) to the corresponding resource attribute, but I don't see an alternative. 
If it looks good for you, I'll include in this PR the logic in TokenResponse._determine_resource() for every actions already supported for STS before submitting it as PR.
It's breaking some tests and there's one I've looked …
=> IAM validation: Resource is now processed during authorization

moto/elbv2/exceptions.py, moto/elbv2/models.py, moto/elbv2/responses.py, tests/test_autoscaling/test_elbv2.py, tests/test_elbv2/test_elbv2.py, tests/test_elbv2/test_elbv2_target_groups.py, tests/test_sqs/test_sqs.py
- This PR aims to make target group in parity with AWS.
- Parameter validation for `create_target_group`
- Default values for `create_target_group`
- Adjusted test cases accordingly
- Fixed `create_target_group` response
- Related PR for AWS Validated Test Case: https://github.com/localstack/localstack-ext/pull/2064
=> ELBv2: added validation for target group

moto/cognitoidp/models.py
Hello!
In this pull request (PR), I have made changes to ensure that the created user pool ID is limited to a maximum of 55 characters.
When using the ```MOTO_COGNITO_IDP_USER_POOL_ID_STRATEGY=HASH``` configuration, creating a user pool with ```create-user-pool``` resulted in an ID that was 56 characters long. 
According to [AWS documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserPoolType.html#CognitoUserPools-Type-UserPoolType-Id), the maximum character limit for a user pool ID is 55 characters .
This poses an issue when Cognito client libraries check the character count of the user pool ID, using Moto's Cognito mock unusable for such scenarios. For example, [Amplify-JS allows user pool IDs of up to 55 …
=> Cognito: Limit user pool ID to 55 characters

moto/elbv2/exceptions.py, moto/elbv2/models.py, moto/elbv2/responses.py, tests/test_elbv2/test_elbv2_target_groups.py
This PR fixes minor parity gaps with aws in `describe_target_groups` api
- sorting the list of target group before returning it
- multiple arguments in describe call raises an exception
- Added test cases for `describe_target_groups` api
=> ELBv2: fix parity in describe_target_group

moto/dynamodb/models/dynamo_type.py, moto/dynamodb/models/utilities.py, tests/test_dynamodb/test_dynamodb.py
Fixes #6815 
When receiving an item with a Binary value, the SDK's will base64-encode it before sending it over the wire. That means that Moto receives a JSON like this:
```
"B": "dmFsdWU="
```
Inside `DynamoType.to_regular_json()`, we use the builtin boto3 TypeSerializers to convert the item to a DynamoDB compliant object. That means converting it back to the original value, to make sure that the type (`B`) and value (bytes) align:
```
"B": b"value"
```
However, when calling `to_json()`, we want the dictionary that we can send back over the wire - which means converting it back into the base64-encoded version.
Bug was introduced with the introduction of `to_regular_json()` in #6375
=> DynamoDB: Fix projection expression with binary attribute

moto/elbv2/models.py, tests/test_elbv2/test_elbv2.py, tests/test_elbv2/test_elbv2_target_groups.py
- `create_target_group`: parameter validation added for `TargetType == 'lambda'`
- `set_ip_address_type `:  parameter validation added for ip address type
- Adjusted test case and added new scenarios
=> ELBv2: added validation for create_target_group() and set_ip_address_type()

moto/elbv2/models.py, tests/terraformtests/terraform-tests.success.txt, tests/test_elbv2/test_elbv2_target_groups.py
FYI @macnev2013 - some minor improvements to your earlier PRs.
The `healthcheck_timeout_seconds`-validation was tested against AWS - the additional attributes were deduced based on the docs and the TF tests.
=> ELBv2: Improve Target Group validation

docs/docs/services/opensearch.rst, moto/__init__.py, moto/es/urls.py, moto/opensearch/exceptions.py, moto/opensearch/models.py, moto/opensearch/responses.py, tests/test_opensearch/test_opensearch.py
Add the Opensearch `list_domain_names` method support. The pagination functionality hasn't been implemented yet, just the base configuration for listing all the domain names for Opensearch.
=> Opensearch: Add the `list_domain_names` method support

moto/ecs/models.py, tests/test_ecs/test_ecs_boto3.py
ECS on FARGATE only allows `task` for pidMode
https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html
=> ECS: add pidMode validation for FARGATE

moto/settings.py, tests/test_apigateway/test_apigateway.py, tests/test_apigateway/test_apigateway_integration.py, tests/test_awslambda/test_lambda.py, tests/test_s3/test_multiple_accounts_server.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_auth.py, tests/test_s3/test_s3_cross_account.py, tests/test_s3/test_s3_custom_endpoint.py, tests/test_s3/test_s3_file_handles.py, tests/test_s3/test_s3_logging.py, tests/test_s3/test_s3_multipart.py
This will make it easier to introduce a additional proxy mode (soon™), where tests will be automatically skipped because that also counts as `not TEST_DECORATOR_MODE`.
Not all tests are converted yet, but it's a start
=> Admin: Rework skipped tests for ServerMode

moto/ec2/exceptions.py, moto/ec2/models/transit_gateway_attachments.py, moto/ec2/models/vpc_peering_connections.py, moto/ec2/models/vpcs.py, moto/ec2/responses/vpc_peering_connections.py, tests/test_ec2/test_vpc_peering.py
AWS allows VPCs to be peered as long as their CIDR ranges do not overlap. Peering can happen within the same account/region or cross-account/region.
https://github.com/getmoto/moto/pull/2195 added VPC peering support across-regions.
This PR introduces VPC peering support across-accounts.
Exisiting tests have been parametrised to run all assertions within the same account and across accounts. 
Closes: https://github.com/localstack/localstack/issues/8550
=> EC2: Cross-account VPC peering connections

moto/config/resources/aws_managed_rules.json, scripts/pull_down_aws_managed_rules.py
The script, `scripts/pull_down_aws_managed_rules.py`, used to download markdown files from an AWS repo.  Those markdown files contained info on managed rules, similar to what appears on AWS official documentation, but in a format that's easier to parse.  However, the repo containing markdown files was archived on June 15, 2023 as AWS doesn't want to maintain a separate list of the managed rules ([read their explanation here](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/)).
So `scripts/pull_down_aws_managed_rules.py` has been updated to pull the managed rule info from AWS documentation websites and the parsed results (`moto/config/resources/aws_managed_rules.json`) has been updated to match that documentation.  The updates in the last year for manged rules …
=> Update script that creates managed rule list used by Config

moto/elbv2/responses.py, tests/test_elbv2/test_elbv2.py
This PR aims to add an SSL policy: `ELBSecurityPolicy-TLS13-1-2-2021-06` to `elbv2` service. 
adds security policies with:
- TLS protocol 
- TLS ciphers
=> elbv2: adds a new ssl policy

moto/core/responses.py, moto/s3/responses.py
Handling form-data is currently only required for S3, but it just makes more sense to have all the request-parsing logic in a single place.
This also removes some deduplication.
=> Admin: Move form-data handling to core

.github/workflows/tests_real_aws.yml, setup.cfg, tests/test_s3/__init__.py, tests/test_s3/test_s3.py
Currently only enabled for (2) S3 tests, just to verify the point.
Tests should be marked with two decorators:
```
@pytest.mark.aws_verified
@s3_aws_verified
```
The `s3_aws_verified`-decorator creates a bucket, and passes the bucket-name to the method.
Pytest expects any 'plain' argument to be a fixture, so the bucket-name argument should have a default value to stop pytest from throwing an error:
```
def test_(name=None):
```
I'm expecting to extend this to other tests/services at some point. Based on that, there will probably be some refactoring to make this easier to maintain/extend.
=> Admin: Enable some tests to run against AWS

moto/ec2/exceptions.py, moto/ec2/models/transit_gateway_attachments.py, tests/test_ec2/test_transit_gateway_peering_attachments.py
This PR adds cross-region and cross-account peering attachments for transit gateways.
<https://docs.aws.amazon.com/vpc/latest/tgw/tgw-peering.html>
It takes an approach similar to VPC peering. See: https://github.com/getmoto/moto/pull/6826
=> EC2: Cross-account transit gateway peering attachments

.github/workflows/tests_real_aws.yml, moto/ses/models.py, moto/ses/responses.py, moto/ses/template.py, moto/utilities/tokenizer.py, tests/test_ses/__init__.py, tests/test_ses/test_ses_boto3.py, tests/test_ses/test_templating.py
Fixes #6862 
Considering that all constructs (`each`, `if, `else`, ..) can be nested into obvivion, having a single parser was never going to be a good solution. I rewritten it so that the logic for every construct now is now in it's own separate class.
The existing integration test has been extended and is now verified against AWS.
This PR also contains the logic for `delete_template`, just because I needed to actually delete the template after the AWS test finishes.
=> SES: Support templates with if/else constructs

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
Hi!
In this PR, I've fixed the behavior of `update_user_pool`.
I discovered that `update_user_pool` overwrites default values even when the request doesn't contain those parameters.
However, the [AWS docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html) state:
>If you don't provide a value for an attribute, Amazon Cognito sets it to its default value.
Therefore, I've added a method to extend the default config, ensuring that UserPool uses it during both creation and configuration updates.
Best regards.
=> cognito-idp: Use default values for unspecified settings in update_user_pool

moto/events/models.py, tests/test_events/test_events.py
=> Events: put_events() now throws a warning when Detail field is not a dict

moto/ec2/exceptions.py, moto/ec2/models/subnets.py, moto/ec2/responses/_base_response.py, moto/ec2/responses/subnets.py, tests/test_ec2/test_tags.py
Wrong inputs are common among users and the crashing of the service instead of returning the correct error message confuse them. This PR adds some extra validations for the situation encountered in localstack/localstack#9195
=> EC2: Add validations for create_subnet tags

tests/test_lakeformation/test_lakeformation.py, tests/test_lakeformation/test_resource_tags_integration.py
These tests depend on multiple services (i.e., Glue and S3), and the names should therefore follow a specific convention (test_*integration.py). 
This will ensure that the DependencyTests know to ignore these.
https://github.com/getmoto/moto/blob/197e8710afcd311cf3845811dccdea7535711feb/scripts/dependency_test.sh#L8
=> Admin: Lakeformation: Fix test names

moto/s3/responses.py, tests/test_s3/test_s3_multipart.py
=> S3: ContentLength-headers should be strings

moto/elbv2/models.py, tests/test_elbv2/test_elbv2_target_groups.py
This Pull Request introduces a test case that validates the behavior of health check parameters for target groups.
- When the protocol is set to HTTP or HTTPS and HealthCheckIntervalSeconds is equal to HealthCheckTimeoutSeconds, AWS generates an exception (this has been addressed in Moto).
- Test cases have been added to verify this behavior.
=> ELBv2: fixed exception message for target group

docs/docs/contributing/development_tips/tests.rst, docs/docs/contributing/installation.rst
So I recently read through the documentation and followed the instructions. And I think a few small things can be improved. Let me know if these suggestions are incorrect or if I missed something!
- When I run `moto_server` it starts the version installed by pip, and not the code that I'm actually working on. So I think in the instructions about running the ServerMode tests, `moto_server` should be replaced by `python moto/server.py`.
- I added a reference to the `make lint` target, because I think it may have helped me to prevent pushing code with linting errors.
- Likewise, I updated the section in the documentation for how to test one specific service. I referred to this a lot while writing code because these commands give quick feedback. And I was actually curious why `ruff` was only …
=> Small documentation improvements for new developers

moto/elbv2/exceptions.py, moto/elbv2/models.py, moto/elbv2/responses.py, tests/terraformtests/bin/run_go_test, tests/terraformtests/terraform-tests.failures.txt, tests/terraformtests/terraform-tests.success.txt, tests/test_elbv2/test_elbv2_target_groups.py
-  `modify-target-group-attributes` : fixed validation for `stickiness` and `deregistration_delay.timeout_seconds` and added exception handling
- added new exception `InvalidConfigurationRequest`
- added new tags in target-group `creation` and `describe` response
- added test cases
=> ELBv2: target-group creation and modification

moto/ec2/models/dhcp_options.py, moto/ec2/responses/dhcp_options.py, moto/ec2/responses/vpcs.py, tests/test_ec2/test_dhcp_options.py
AWS provides the `AssociateDhcpOptions` operation to associate a DHCP Options Set with a VPC.
There is no `DisassociateDhcpOptions` operation to remove a DHCP Options Set from a VPC. Instead, `DhcpOptionsId` must be set to `default` when calling `AssociateDhcpOptions` to achieve this.
This PR implements this capability.
See: <https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateDhcpOptions.html#API_AssociateDhcpOptions_RequestParameters>
Closes: https://github.com/localstack/localstack/issues/9222
=> EC2: Add default DHCP options set for VPCs

moto/batch/models.py, moto/batch/responses.py, moto/batch_simple/models.py, tests/test_batch/test_batch_jobs.py, tests/test_batch_simple/test_batch_jobs.py
Closes https://github.com/getmoto/moto/issues/6512
=> Batch: arraySize and child jobs

moto/ec2/models/key_pairs.py, moto/ec2/responses/key_pairs.py, moto/ec2/utils.py, tests/test_ec2/helpers.py, tests/test_ec2/test_key_pairs.py, tests/test_ec2/test_utils.py
This PR adds support for ED25519 SSH key pairs in EC2.
It is now possible to use the `KeyType` field in `CreateKeyPair`, as well as the ability to `ImportKeyPair` ED25519 keys.
See:
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateKeyPair.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportKeyPair.html
- https://github.com/localstack/localstack/issues/9237
=> EC2: Add support for ED25519 SSH key pairs

moto/ec2/responses/instances.py, tests/test_ec2/test_instances.py
The duplicate copy/pasta nature before meant that  `run_instances()` and `describe_instances()` were missing different fields in the response. 
The output of both methods is now the same.
Fixes #6903
=> EC2: Streamline output of run_instances()/describe_instances()

moto/route53/models.py, moto/route53/responses.py, tests/test_route53/test_route53.py
According to the response syntax of [`GetHostedZone`](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/get_hosted_zone.html#Route53.Client.get_hosted_zone), the caller reference should be returned in the hosted zone object.
This PR fixes this behavior.
=> Route53: add CallerReference to the GetHostedZone response

moto/s3/exceptions.py, moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3.py
Followup/Correction of #6889 
As @jagoodhand pointed out in https://github.com/getmoto/moto/issues/6837#issuecomment-1764206738, we should only return a 405 when calling `head_object()` on a DeleteMarker when the VersionId is specified. 
If `head_object()` is called without the VersionId, we should return a normal 404.
The existing test has been extended to verify this scenario, and passes when run against AWS.
=> S3: head_object() only returns 405 on DeleteMarkers when specifying VersionId

moto/sesv2/responses.py, tests/test_sesv2/test_sesv2.py
Fix of #6909, part 2.
#6913 handled the case of "Text" body. The goal of this PR is to handle the "Html" body case.
Ref: see SES v2 [send_email](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sesv2/client/send_email.html).
Cc: @bblommers
=> Fix: SESV2 send_email with HTML body

moto/iot/models.py
Certain IoT resource types had bad hardcoded account ID (`1`) in their ARNs, like so:
```
arn:aws:iot:us-east-1:1:job/asdf123
```
This PR ensures that the ARNs have the proper account IDs.
The resource types are:
- ThingType
- ThingGroup
- Job
- Rule
- DomainConfiguration
=> IoT: Fix bad account IDs in ARNs

tests/test_awslambda/test_lambda_layers_invoked.py
Otherwise without docker it fails like this;
```
msg = success_result["Payload"].read().decode("utf-8")
>       assert msg == '"2.31.0"'
E       assert "error runnin... directory'))" == '"2.31.0"'
E         - "2.31.0"
E         + error running docker: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
=> AWSLambda: mark layers test as requiring docker

moto/core/responses.py, moto/core/utils.py, moto/s3/responses.py, tests/test_core/test_utils.py, tests/test_s3/test_s3.py
As reported in https://github.com/localstack/localstack/issues/9428, moto is decoding the content of the `DeleteObjects` body, but those keys are not going through the URL encoding as they're in the XML, and should be used as is.
I've removed the `get_safe_path` call from `DeleteObjects` and added a test validating the behaviour, tested against AWS.
This devolved into a bit of a rabbit hole, as it seems fixing this still did not delete the keys, because they were saved with an emoji in the name where it should have been using the raw url encoded format like S3.
```python
object_key_emoji = "a/%F0%9F%98%80"
client.put_object(Bucket=bucket_name, Key=object_key_emoji, Body="emoji percent encoding")
```
Result of `ListObjects`:
```json
{
"Contents": [
{
"ETag": …
```
=> S3: fix unquoting of S3 object keys in DeleteObjects

.github/workflows/test_outdated_versions.yml, moto/apigateway/models.py, requirements-tests.txt, setup.cfg, tests/test_core/test_docker.py
`openapi-spec-validator 0.5.0` was [released over a year ago](https://github.com/python-openapi/openapi-spec-validator/releases/tag/0.5.0), so it's reasonable to make that the new minimum version IMO. That way we can finally get rid of the ugly ImportError.
This PR also switches our dev-dependencies to use `pytest-order` (https://github.com/pytest-dev/pytest-order), as that a maintained fork of `pytest-ordering`.
Closes #6937
=> Up openapi-spec-validator version; swith to pytest-order

moto/dynamodb/exceptions.py, moto/dynamodb/models/__init__.py, moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/test_dynamodb.py
Fixes #6949 
This also improves the behaviour of `ReturnValuesOnConditionCheckFailure` for `transact_write_items`.
All new/updated tests are verified against AWS.
=> DynamoDB: update_item() now returns item for ConditionalCheckFailed-exceptions

moto/apigateway/models.py, tests/test_s3/test_s3.py
As of 0.7.x, `openapi_spec_validator` recommends using the `validate`-method.
The old `validate-spec` method still exists, but throws a warning.
This also refactors one of the new S3 tests a bit to ensure we can run this against AWS.
=> APIGateway: Use new OpenAPISpecValidator API

moto/sns/exceptions.py, moto/sns/models.py, moto/sns/responses.py, tests/test_sns/__init__.py, tests/test_sns/test_application_boto3.py
Fixes #2333 
- create_platform_application now only returns the existing endpoint of both EndpointAttributes and CustomUserData is the same
- list_endpoints_by_platform_application() now throws an exception if the application does not exist
All modified tests around these features are verified against AWS.
=> SNS: Improve PlatformApplication error handling

CHANGELOG.md, moto/dynamodb/parsing/README.md
I have fixed some typos in markdown files. Following are the fixed typos:
1. availabilty -> availability
2. Miscellanous -> Miscellaneous
3. expresion -> expression 
I kindly request the repository maintainers to review and merge it. Thanks!
=> docs: fix typos in markdown files

moto/organizations/exceptions.py, moto/organizations/models.py, tests/test_organizations/test_organizations_boto3.py
At the moment, the PolicyNotFoundException raised by the mock_organizations is not returning the same `Error` responses as the boto3 client.
The mocked response returns a `Code` of `"400"` and an XML string in the `Message` block.
The expected behaviour based on the boto3 client would be to return a `Code` of `"PolicyNotFoundException"` and a message specific to the call, for example, `"We can't find a policy with the PolicyId that you specified."` for [DescribePolicy](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribePolicy.html#API_DescribePolicy_Errors).
Steps to reproduce:
```python
import boto3
import moto
client = boto3.client("organizations")
try:
client.describe_policy(PolicyId="p-definitelydoesnotexist")
except Exception as e:
print(type(e).__name__) …
```
=> Align organizations PolicyNotFoundException with boto3 response

IMPLEMENTATION_COVERAGE.md, docs/docs/services/signer.rst, moto/signer/models.py, moto/signer/responses.py, moto/signer/urls.py, tests/test_signer/test_signing_profiles.py
New methods:
- list_tags_by_resource()
- tag_resource()
- untag_resource()
The `put_signing_profile()`-method now also supports the `SigningMaterial`-parameter
=> Signer: Add tagging methods

moto/mq/exceptions.py, moto/mq/models.py, tests/test_mq/test_mq.py, tests/test_mq/test_mq_configuration.py
Configuring brokers with RabbitMQ wasn't possible at first, but it is now.
See the AWS blog post about this feature:
https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-mq-managed-configuration-rabbitmq-brokers/
We now also create a default configuration, instead of pointing it to a random (non-existing) identifier.
=> MQ: Rabbits can now be configured

.github/workflows/build.yml, .github/workflows/tests_decoratormode.yml, .github/workflows/tests_proxymode.yml, .github/workflows/tests_servermode.yml, codecov.yml, setup.cfg, tests/test_ec2/test_instances.py, tests/test_events/test_events.py
Includes an upgrade to `py-partiql-parser` to a version that supports Py 3.12
From the 3.12 release notes:
> [datetime](https://docs.python.org/3/library/datetime.html#module-datetime): [datetime.datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime)’s [utcnow()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) and [utcfromtimestamp()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp) are deprecated and will be removed in a future version
Moto already took care of this in #6803, but botocore still uses these methods - so it throws a lot of warnings.
The test changes are necessary because we're suddenly also catching these deprecated datetime warnings, not just our own.
=> Admin: Support Py 3.12

moto/timestreamwrite/models.py, tests/test_timestreamwrite/__init__.py, tests/test_timestreamwrite/test_timestreamwrite_database.py, tests/test_timestreamwrite/test_timestreamwrite_table.py, tests/test_timestreamwrite/test_timestreamwrite_tagging.py
Now that tests are inline with how AWS behaves, we should be able to remove the (failing) Terraform tests for this service.
=> TimestreamWrite - ensure test parity with AWS

docs/docs/server_mode.rst
Add better docker run command to start the `moto` docker.
- Use `--rm` to delete the docker after exit
- `-p` to open the port to the host (otherwise there's no point in that docker...)
- `--name` to properly identify the docker
=> Update server_mode.rst with better docker run commands

moto/dynamodb/comparisons.py, moto/dynamodb/exceptions.py, moto/dynamodb/models/__init__.py, moto/dynamodb/parsing/key_condition_expression.py, moto/dynamodb/responses.py, tests/test_dynamodb/__init__.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/test_dynamodb.py, tests/test_dynamodb/test_dynamodb_create_table.py, tests/test_dynamodb/test_dynamodb_statements.py
Fixes #6973 
Fixes #6979 
IIRC, an unknown KeyType during table creation such as `{"AttributeName": "sk", "KeyType": "SORT"}` used to be ignored.
Because of that, we copied this behaviour in #5919 
But AWS now throws an error, and explicitly states that only `HASH` and `RANGE` are acceptable key-types - so we'll follow that.
=> DynamoDB: Improve validation around KeyTypes and ExpressionAttributeValues

docs/docs/faq.rst, moto/core/models.py, setup.cfg, tests/test_core/test_responses_module.py
Fixes #6417 
Moto uses it's own Responses-mock to intercept AWS requests, so if you need to intercept custom (non-AWS) request as part of your tests, you may find that Moto 'swallows' any pass-thru's that you have defined.
You can pass your own Responses-mock to Moto, to ensure that any custom (non-AWS) are handled by that Responses-mock.
Note that this feature requires `responses>=0.24.0`, [released today](https://pypi.org/project/responses/0.24.0/).
```
from moto.core.models import override_responses_real_send
my_own_mock = responses.RequestsMock(assert_all_requests_are_fired=True)
override_responses_real_send(my_own_mock)
my_own_mock.start()
my_own_mock.add_passthru("http://some-website.com")
```
=> Support override of Responses.real_send()

moto/awslambda/models.py, moto/awslambda/responses.py
As per [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/API_GetPolicy.html#API_GetPolicy_RequestSyntax), the get policy call also accepts a Qualifier parameter as well as an function ARN.
Notes:
- Although the ARN and qualifier is accepted, a larger change will be required to return different policies based on that qualifier which I haven't done as part of this change
- There is already a test `test_get_policy_with_qualifier` that calls this endpoint with a qualifier, although it doesn't test that the returned policy is different with and without the qualifier.
=> Lambda: Allow Qualifier on get policy call

moto/rds/exceptions.py, moto/rds/models.py, tests/test_rds/test_rds_clusters_with_instances.py
Error response code and message confirmed against actual AWS backend.
Fixes #6992
=> RDS: Can't delete DBCluster with active DBInstances

moto/awslambda/models.py, setup.cfg
Follow-up to #6969 
This makes it possible to use @awslambda_simple without needing to install the `docker`-module
=> AWSLambda: Ensure simple backend does not require docker-module

moto/ec2/responses/instances.py
It was discovered that Terraform plugin was crashing with the following sample:
```tf
data "aws_ec2_instance_type" "example" {
instance_type = "t2.micro"
}
resource "aws_instance" "example" {
ami           = "ami-ff0fea8310f3"
instance_type = data.aws_ec2_instance_type.example.instance_type
}
```
returning following error:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                     
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9aae86f]                                                                                    
goroutine 311 [running]: …
```
=> EC2: Improve DescribeInstanceTypes response

moto/rds/models.py, moto/rds/utils.py, tests/test_rds/test_rds_clusters.py, tests/test_rds/test_rds_clusters_with_instances.py
1. added Enum for valid cluster engines
- Ref document: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds/client/create_db_cluster.html#:~:text=Valid%20Values%3A%20aurora%2Dmysql%20%7C%20aurora%2Dpostgresql%20%7C%20mysql%20%7C%20postgres
2. add cluster engine validation when creating a rds cluster
3. added unittest for the validation
=> RDS: add cluster engine validation when creating a rds cluster

moto/ecr/models.py, moto/ecs/models.py, moto/glacier/models.py, moto/sqs/responses.py, tests/test_dynamodb/test_dynamodb.py, tests/test_ec2/test_flow_logs.py, tests/test_ecr/test_ecr_boto3.py, tests/test_ecs/test_ecs_boto3.py, tests/test_glacier/test_glacier_archives.py, tests/test_glacier/test_glacier_vaults.py, tests/test_opsworks/test_apps.py, tests/test_opsworks/test_instances.py, tests/test_opsworks/test_layers.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_multipart.py, tests/test_sqs/test_sqs.py
There are a few instances where Moto raises a generic Exception. That sorta works - but in ServerMode this results in a 500, and subsequently `boto3` will try to re-try the operation a few times, resulting in a very slow-running tests.
Converting this into Moto/boto3-specific exceptions ensures that ServerMode always returns a 400-request, and `boto3` then understands it doesn't need to retry these operations.
------------
All SQS operations have to understand both JSON and XML responses, as boto3 can send a request in either format.
The `list_queue_tags` would always send an XML error response, which resulted in a failing test on our side.
Adding the `jsonify_error`-decorator ensures that our tests pass again.
=> Techdebt: Improve/fix exception handling in tests

moto/ec2/models/hosts.py, moto/ec2/responses/hosts.py, tests/test_ec2/test_hosts.py
=> EC2: describe_hosts() now returns the AllocationTime-attribute

moto/efs/models.py
https://github.com/getmoto/moto/issues/7014
EFS Access point ID string value does not match valid access point ID pattern as described in [AWS EFS documentation](https://docs.aws.amazon.com/efs/latest/ug/API_AccessPointDescription.htm).
EFS access point ID has the following regex pattern:  `fsap-[0-9a-f]{8,40}`
The previous implementation returns a 8 character hex string *without* the `fsap-` prefix. 
**Proposed change**:
- (old) ~`abcd1234`~
- (new) `fsap-abcd1234`
=> Fix EFS access point ID pattern

.github/workflows/build.yml, .github/workflows/release.yml, CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/faq.rst, docs/docs/services/comprehend.rst, docs/docs/services/ec2.rst, docs/docs/services/eks.rst, docs/docs/services/identitystore.rst, docs/docs/services/logs.rst, docs/docs/services/rds.rst, docs/docs/services/redshift.rst, moto/awslambda/models.py
Also enables Trusted Publisher workflow with PyPi, so we no longer need passwords/API keys.
https://docs.pypi.org/trusted-publishers/using-a-publisher/
=> Prep release 4.2.8

moto/s3/models.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_file_handles.py, tests/test_s3/test_s3_multipart.py
No functional changes - just ensuring that MyPy will complain if we ever forget to pass an AccountId here.
=> S3: typing: FakeKey should always have an account_id

moto/ecs/models.py, moto/ecs/responses.py, tests/test_ecs/test_ecs_boto3.py, tests/test_ecs/test_ecs_task_tags.py
Fixes #7027 
Adds support for tagging Tasks using the `tag_resource`/`untag_resource`/`list_tags_for_resource` trinity.
Fixes a bug where `describe_tasks` would actually delete the tags if called without the `include`-parameter.
=> ECS: Tagging is now supported for Tasks

moto/lakeformation/exceptions.py, moto/lakeformation/models.py, moto/lakeformation/responses.py, tests/test_lakeformation/test_lakeformation.py
This implements the key behavior of filtering the results of lakeformation's list_permissions operation based on the passed parameters.
Implemented filtering by:
```
CatalogId, Principal, ResourceType, Resource
```
where:
```
ResourceType = [DATABASE, TABLE, CATALOG, DATA_LOCATION]
```
and 
```
Resource = [
{
"Database": {
"CatalogId": "string", 
"Name": "string"
}
},
{
"Table": {
"CatalogId": "string", 
"DatabaseName": "string"
"Name": "string",
"TableWildcard": {}
}
},
{
"Catalog": {}
},
]
```
Used reference documents for behaviour:
- https://boto3.amazonaws.com/v1/documentation/api/1.26.83/reference/services/lakeformation/client/list_permissions.html
- https://docs.aws.amazon.com/cli/latest/reference/lakeformation/list-permissions.html
Note: 
I could not get all preexisting tests …
=> LakeFormation: Add Parameters for list_permissions()

moto/transcribe/models.py, moto/transcribe/responses.py, tests/test_transcribe/test_transcribe_boto3.py
Adds support for translating the `Subtitle.Formats` configuration key into appropriate outputs given `OutputBucketName` and `OutputKey` configuration. Also fixes the formatting of `Transcript.TranscriptFileUri` in the output when `OutputBucketName` and `OutputKey` are both set. When that is the case the job name is not part of the output key.
=> Add subtitle support for `transcribe`

tests/test_eks/test_server.py, tests/test_redshift/test_server.py, tests/test_redshiftdata/test_server.py, tests/test_secretsmanager/test_server.py
These tests already run against a (in-memory) FlaskServer, so it's pointless to also run them while the MotoServer is active.
=> Techdebt: Disable some duplicate tests

moto/logs/models.py, tests/test_logs/test_logs_cloudformation.py
CloudFormation AWS::Logs::LogGroup expects tags as an array of Tags:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
Whereas boto3's Logs `create_log_group()` expects tags to be a dict:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs/client/create_log_group.html
So we need to transform how we provide tags to avoid getting:
```
E       AttributeError: 'list' object has no attribute 'items'
```
=> Fix CloudFormation AWS::Logs::LogGroup tagging

moto/efs/models.py, moto/efs/responses.py, tests/test_efs/test_access_points.py
The current moto implementation of `describe_access_points` for EFS service does support the full functionality described in boto. Namely it does not support filtering results based on file system Id (see [`EFSClient.describe_access_points`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/efs/client/describe_access_points.html#)).
This change adds support for filtering based on file system id. 
added unit tests to cover additional filter scenarios for `efs.describe_access_points`
=> EFS: Add support for describing access points using File system ID filter

tests/test_batch/test_batch_jobs.py
Similar to https://github.com/getmoto/moto/pull/6938, this test fails without docker:
```
___________________________ test_cancel_pending_job ____________________________
@mock_logs
@mock_ec2
@mock_ecs
@mock_iam
@mock_batch
def test_cancel_pending_job():
ec2_client, iam_client, _, _, batch_client = _get_clients()
_, _, _, iam_arn = _setup(ec2_client, iam_client)
commands = ["sleep", "10"]
job_def_arn, queue_arn = prepare_job(batch_client, commands, iam_arn, "deptest")
resp = batch_client.submit_job(
jobName="test1", jobQueue=queue_arn, jobDefinition=job_def_arn
)
delayed_job = resp["jobId"]
depends_on = [{"jobId": delayed_job, "type": "SEQUENTIAL"}]
resp = batch_client.submit_job(
jobName="test_job_name",
jobQueue=queue_arn,
jobDefinition=job_def_arn,
dependsOn=depends_on,
)
job_id = …
```
=> Batch: mark job test as requiring docker

moto/lakeformation/models.py, moto/lakeformation/responses.py, tests/test_lakeformation/test_lakeformation.py
This implements the additional resource of type `DataLocation` for filtering the results of lakeformation's list_permissions operation.
Resources now additionally supports the following format:
```
Resource = [
{
"DataLocation: {
"ResourceArn": "string",
"CatalogId": "string"
}
}
]
```
Used reference documents for behaviour:
https://boto3.amazonaws.com/v1/documentation/api/1.26.83/reference/services/lakeformation/client/list_permissions.html
https://docs.aws.amazon.com/cli/latest/reference/lakeformation/list-permissions.html
=> LakeFormation: extend functionality of list_permissions

moto/lakeformation/exceptions.py, moto/lakeformation/models.py, tests/test_lakeformation/test_lakeformation.py
The register-resource method of lakeformation is missing the functionality to raise AlreadyExistsException when a resource is already registered.
Resource:
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation/client/register_resource.html,
- Testing with AWS CLI
=> LakeFormation: raise AlreadyExistsException when registering an existing resource

.coveragerc, moto/__init__.py, moto/core/models.py, moto/identitystore/models.py, requirements-dev.txt, setup.cfg, tests/test_core/test_decorator_calls.py, tests/test_core/test_mypy.py, tests/test_core/test_responses_module.py
This is my attempt to complete the work from https://github.com/getmoto/moto/pull/6421
I rebased it, and then used a Protocol to allow lazy_load to work properly. If you don't like the protocol, it also works if lazy_load has a return type of base_decorator and we just cast the inner function to that. 
I wasn't sure if maybe the name for the protocol class should be more distinct to avoid confusion.
I also added the other uses of the mock decorators listed in https://github.com/getmoto/moto/issues/4944#issuecomment-1596169486 to test_mypy.py. That was probably not really necessary, but it seemed like a reasonable thing to do.
=> MyPy improvements

moto/core/utils.py, tests/test_autoscaling/test_autoscaling_tags.py, tests/test_cloudwatch/test_cloudwatch_boto3.py
Fix for https://github.com/localstack/localstack/issues/9663; related to https://github.com/getmoto/moto/issues/6033: 
When more than 10 members need to be parsed, the string-sort leads to `IndexError`. 
For `Tags` this was already tackled and fixed in https://github.com/getmoto/moto/pull/6038. 
* The proposed solution should handle more generic cases. 
* However, there may still be issues with nested members.
* Added a test case for autoscaling-tags, to verify the tag-parsing still works.
* Added a test for cloudwatch with a couple of metric-queries to cover the case reported in https://github.com/localstack/localstack/issues/9663
=> Core: Parameter handling: fix parsing of >= 10 members

.github/workflows/build.yml, .github/workflows/tests_sdk_dotnet.yml, .github/workflows/tests_sdk_java.yml, .github/workflows/tests_sdk_ruby.yml, .gitignore, moto/sqs/responses.py, other_langs/tests_ruby/Gemfile, other_langs/tests_ruby/test/aws_sqs_test.rb
Fixes #7054 
Followup to #6331 
Validates the behaviour using the Ruby SDK, which is more strict in parsing the SQS responses.
=> SQS: Ensure all SQS responses are in JSON format

moto/cognitoidentity/models.py
Hi.
The type of Credentials.Expiration is a timestamp number type.
ref: https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetCredentialsForIdentity.html#API_GetCredentialsForIdentity_ResponseSyntax
It was discovered by a type conversion error in Golang's sdk v2.
ref: https://github.com/aws/aws-sdk-go-v2/blob/6afe5286d243f06aa040d3954b765b38366b88c2/service/cognitoidentity/deserializers.go#L3374-L3383
Thank you very much.
=> CognitoIdentity: get_credentials_for_identity() should have Expiration as number.

moto/autoscaling/models.py, tests/test_autoscaling/test_autoscaling_tags.py
=> Autoscaling: describe_tags() now supports the key/value filters

moto/ssm/models.py, moto/ssm/responses.py, tests/test_ssm/test_ssm_boto3.py
This fixes a bug I stumbled across when running localstack (which runs moto server in the background) and using SSM parameters.
The Bug:  overwrite does not just change the fields supplied.  It instead, replaces all values that were not explicitily specified.  This does not happen when the same code is tested against AWS.
Changes:
1. Added a test for verifying that metadata is preserved when an overwrite occurs
2. Coalesce all Parameter values to the previous parameter if they are None type
3. update the response model to not default Tags to any empty array since that's meaningful for erasure (it is coalesced in the backend anyway)
4. Add some warnings about `Tier` and `Policies` configuration options since they seem to be new comparatively
=> SSM: fix overwrite preserving non-indicated values

moto/autoscaling/models.py, moto/awslambda/models.py, moto/awslambda/policy.py, moto/batch/models.py, moto/batch/responses.py, moto/cloudtrail/models.py, moto/ecr/models.py, moto/ecs/models.py, moto/elb/models.py, moto/elb/responses.py, moto/iam/models.py, moto/iot/models.py, moto/logs/models.py, moto/logs/responses.py, moto/redshift/models.py, moto/route53/models.py, moto/ssm/models.py, moto/ssm/responses.py, tests/test_ecs/test_ecs_cloudformation.py, tests/test_elb/test_elb_cloudformation.py, tests/test_iam/test_iam_access_integration.py, tests/test_ssm/test_ssm_boto3.py
New features:
-  SSM: put_parameter() now supports the Tier and Policies arguments
Bugfixes:
- CloudFormation: updating `AWS::ECS::Service` with a different `ClusterName` no longer throws an error
- CloudFormation: creating `AWS::ElasticLoadBalancing::LoadBalancer` that contain `Policies` no longer throws an error
- IAM: `generate_credential_report()` no longer throws an error when multiple accounts were used
=> Techdebt: Improve some type annotations

moto/logs/exceptions.py, moto/logs/models.py, moto/logs/responses.py, tests/test_logs/test_export_tasks.py, tests/test_logs/test_integration.py, tests/test_logs/test_logs.py, tests/test_logs/test_logs_query/test_boto3.py
Fixes #7079 
More specifically:
- Ensures that the `from`/`to` are milliseconds after the epoch
- Iterate through all the streams
- Creates a compressed (gzipped) file in S3, containing all the existing log messages
- Fixes/improves error handling for `create_export_task()`
Marking it as draft until #7069 is merged, as we need to resolve any merge conflicts first
=> Logs: create_export_task() now actually exports the data

moto/dynamodb/models/table.py, tests/test_dynamodb/test_dynamodb_table_with_range_key.py, tests/test_dynamodb/test_dynamodb_table_without_range_key.py
Fixes #7080 
Our `scan()` implementation would iterate through the entire dataset, and only trim the results at the end.
This approach has multiple downsides:
- We're needlessly filtering/copying all items in the table
- The ScannedCount is wrong - because we're scanning the whole table, we're essentially saying that `ScannedCount = len(table)`
This PR changes the approach so that we only read the necessary items.
- we only start processing items when we've reached the ExclusiveStartKey (DynamoDB's pagination key)
- we immediately end processing when the result set has reached the desired size (either in length or in bytesize)
Note that `query` still follows the old approach, and presumably suffers from the same problems. We should rewrite that operation in the same way at some point.
=> DynamoDB: Fix ScannedCount calculation for Limit-ed calls

moto/__init__.py, moto/backend_index.py, scripts/ci_moto_server.sh, tests/test_rdsdata/test_rdsdata.py
This is consistent with redshift-data, cloudtrail-data, etc
Plus a few stray tweaks to testing that I made in the process of debugging.
I figured out what I was missing before; it was the matching change in backends_index.py. I guess it probably doesn't
matter since apparently nothing was broken by 'rdsdata' not matching the name used by boto3. But it didn't seem right to me.
=> Techdebt: Update boto3_name to 'rds-data'

moto/__init__.py, moto/config/models.py, moto/core/__init__.py, moto/core/botocore_stubber.py, moto/core/common_models.py, moto/core/models.py, moto/iam/access_control.py, moto/iam/config.py, moto/iam/models.py, moto/moto_proxy/proxy3.py, moto/s3/config.py, moto/s3control/config.py, requirements-dev.txt
This MR cleans up as many ignores in moto.iam as I felt like I could do safely. I also enabled additional mypy strictness locally to see what else might turn up in there.
Of particular note:
- updates moto.core.common_models.ConfigQueryModel to be a generic type, parameterized by the kind of backend in use
- mypy --install-types wasn't installing up botocore-stubs, so I added that to the requirements-dev.txt file
- I refactored some logic in moto/iam/config.py so that mypy could follow what was going on. It should be identical in effect, but the flow of conditionals was too complicated before.
- Separate from the issue of typing per se, I added my solution for the issue of outside users manually setting AccessKey.last_used (of which I am one in one codebase I maintain). This allows you to …
=> Improve typing for IAM

moto/route53/responses.py, tests/test_route53/test_route53.py
This PR adds `CallerReference` to the return type of both [ListHostedZones](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/list_hosted_zones.html) and [ListHostedZonedByName](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/list_hosted_zones_by_name.html).
`test_route53.py::test_list_hosted_zones` already checks for the first operation. I improved `test_route53.py::test_list_hosted_zones_by_dns_name` for the latter.
This is a follow-up of https://github.com/getmoto/moto/pull/6911
=> route53: add CallerReference to ListHostedZones and ListHostedZonesByName

moto/kms/utils.py, tests/test_kms/__init__.py, tests/test_kms/test_kms_encrypt.py
=> KMS: encrypt() now validates payloads that are too large

IMPLEMENTATION_COVERAGE.md, docs/docs/services/s3.rst, moto/s3/models.py, moto/s3/responses.py, moto/s3/utils.py, tests/test_s3/test_s3_copyobject.py
Fixes #7103 
This PR:
- Extends the list of headers that we should keep as part of the key's metadata (the fix for the linked issue)
- Computes the correct checksum algorithm for multipart uploads
- Sets the `checksum_algorithm`/`checksum_value`-attributes on a copied key, if this is copied using MultipartUpload
- Renames `copy_part` to `upload_part_copy` so that our implementation script picks it up properly
Both tests in this PR that assert the behaviour is now correct are verified against AWS.
=> S3: copy() using multiparts should respect ExtraArgs

IMPLEMENTATION_COVERAGE.md, docs/docs/services/s3.rst, moto/s3/exceptions.py, moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3_tagging.py
Fixes #7104 
All tests changed in this PR are verified against AWS
=> S3: put_object_tagging() now validates the number of tags provided

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3.py
This adds paging to list_object_versions(). The original motivation was to enable moto testing for an S3 point-in-time recovery tool, where proper handling of paging is important.
CC @bblommers
=> S3: Add paging to list_object_versions()

moto/iam/models.py, moto/iam/utils.py
`fromisoformat` is a more performant way to get a date-object from a string.
Using `choices(.., k=x)` is the builtin way to loop over `choice` x time - and also happens to more performant.
=> IAM: Performance improvements

moto/ecr/models.py
When executing ECR.DescribeImages() and there is an image to describe the Go AWS SDK fails to de-serialize the response with the following message de serialization failed, failed to decode response body, expected PushTimestamp to be a JSON Number, got string instead . 
When looking into the code https://github.com/getmoto/moto/blob/master/moto/ecr/models.py line 279 (self.image_pushed_at = str(datetime.now(timezone.utc).isoformat()) ) which obviously is a string. When looking at the AWS API documentation at https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribeImages.html#API_DescribeImages_ResponseSyntax AWS expects a number (likely a timestamp) so the bug seems to not be in the GO SDK, but in Moto. 
Trying the patched version did indeed fix the problem.
=> ECR: fix image wrong type for pushed_at

moto/core/responses.py, setup.cfg, tests/test_core/test_account_id_resolution.py, tests/test_core/test_auth.py, tests/test_core/test_backenddict.py, tests/test_core/test_context_manager.py, tests/test_core/test_docker.py, tests/test_core/test_ec2_vpc_endpoint_services.py, tests/test_core/test_environ_patching.py, tests/test_core/test_importorder.py, tests/test_core/test_instance_metadata.py, tests/test_core/test_mock_regions.py, tests/test_core/test_moto_api.py, tests/test_core/test_nested.py, tests/test_core/test_responses.py, tests/test_core/test_server.py, tests/test_core/test_settings.py, tests/test_core/test_socket.py, tests/test_core/test_url_base_regex.py, tests/test_core/test_url_mapping.py, tests/test_core/test_utils.py
The `set_initial_no_auth_action_count`-decorator is now properly typed
=> Techdebt: Improve type annotations

moto/dynamodb/parsing/tokens.py, tests/test_dynamodb/test_dynamodb_update_expressions.py
Fixes #7127 
Behaviour is now verified against AWS
=> DynamoDB: UpdateExpressions can contain a new-line

moto/dynamodb/models/__init__.py, moto/dynamodb/parsing/partiql.py, setup.cfg, tests/test_dynamodb/test_dynamodb_statements.py
The `py_partiql_parser` module supports updates as of >= 0.5.0. It now sends back a list of tuples in the form: `(before, after)`
This PR introduces the appropriate changes in Moto to insert data (if `before` is None), update data (if `before` and `after` are set) or delete rows (if `after` is None)
=> DynamoDB: execute_statement() now supports INSERT/UPDATE/DELETE queries

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
Title: 
Summary:
Issue Encountered: In Moto version 4.2.11 with Botocore version 1.32.7 on Python 3.11, an issue was identified where the admin_initiate_auth method incorrectly returned a valid token AuthenticationResult, even when Multi-Factor Authentication (MFA) was enabled for a user. This behavior was inconsistent with the expected results, as a challenge-response (specifically for Time-based One-Time Password (TOTP)) was anticipated.
Issue link: https://github.com/getmoto/moto/issues/7125
=> CognitoIDP: admin_initiate_auth() now correctly returns a Challenge when 2FA is enabled

moto/cloudformation/parsing.py, moto/ec2/models/launch_templates.py, tests/test_ec2/test_launch_templates_cloudformation.py
* Add support for getting attributes of `AWS::EC2::LaunchTemplate` resources.
* Fix bug. Sorta. The real bug is that moto's cloudformation parsing does not honor dependencies between resources -- instead it retries resource updates that raise errors (up to 5 times). This is fine if the update raises errors, but if no error is raised, the updates may process out of order. This was discovered while writing tests for the previous bullet. In our case, we have an AutoScalingGroup that depends on a LaunchTemplate. If the updates to the AutoScalingGroup are handled first, it picks up the current/old version of the LaunchTemplate instead of the new one (because the new one is not created yet). Honoring dependency order appears hard (probably why it is not yet implemented). As a fallback, this PR …
=> CloudFormation: Implement Fn::GetAtt for AWS::EC2::LaunchTemplate

moto/ec2/responses/instances.py, tests/test_ec2/test_instance_types.py
This PR fixes an incorrect dict key and adds valid fallback value for the response field [`EnaSupport`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_NetworkInfo.html) for the `DescribeInstanceTypes` API operation.
See https://github.com/localstack/localstack/issues/9854
=> EC2: Fix invalid value for NetworkInfo.EnaSupport

moto/ec2/models/launch_templates.py, moto/ec2/utils.py, tests/test_ec2/test_launch_templates_cloudformation.py
Fixes a bug in the creation of launch templates via CloudFormation. If your template has more than one ***unnamed*** launch template, creation will fail with
> botocore.exceptions.ClientError: An error occurred (InvalidLaunchTemplateName.AlreadyExistsException) when calling the CreateStack operation: Launch template name already in use.
This is because moto's implementation expects that the resource have a `LaunchTemplateName` property even though [it is optional](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html#cfn-ec2-launchtemplate-launchtemplatename).
=> EC2: launch templates created by CloudFormation have a generated name if not provided

tests/test_redshiftdata/test_redshiftdata.py
Following our own examples in the docs: The `mock_..`-decorators should be used inside the fixture, otherwise the client isn't mocked properly.
Currently, these tests actually fail on master, when run on their own (`TEST_SERVER_MODE=true pytest tests/test_redshiftdata/`). They only pass in conjunction with other tests (`TEST_SERVER_MODE=true pytest tests/test_core/ tests/test_redshiftdata/`) - presumably because that alters the import order somehow.
With this change, the tests do succeed.
=> Techdebt: RedshiftData test fixtures should be mocked

tests/test_route53resolver/test_route53resolver_endpoint.py
These started failing as of botocore-1.34.3
=> Techdebt: Fix Route53Resolver tests

IMPLEMENTATION_COVERAGE.md, docs/docs/services/cognito-idp.rst, moto/cognitoidp/models.py, moto/cognitoidp/responses.py, tests/test_cognitoidp/test_cognitoidp.py
Implements `cognitoidp`.`admin_respond_to_auth_challenge`. It simply calls the corresponding public endpoint `respond_to_auth_challenge` internally as there is no relevant differences between them.
Since there are no changes in logic, I didn't add any additional tests, but I did convert existing tests so a call to `admin_initiate_auth` and `initiate_auth` uses the appropriate API `admin_respond_to_auth_challenge` and `respond_to_auth_challenge` respectively.
Let me know if there's anything I missed.
=> Add cognitoidp.admin_respond_to_auth_challenge

.github/workflows/build.yml, .github/workflows/tests_terraform_examples.yml, .gitignore, moto/acm/models.py, other_langs/terraform/acm/acm.tf, other_langs/terraform/acm/providers.tf, tests/test_acm/test_acm.py
Fixes #7138 
Also enables a small, focused Terraform test to verify this behaviour is equivalent to how AWS behaves.
=> ACM: describe_certificate() should return a DomainValidationOption for each SN

moto/cloudfront/exceptions.py, moto/core/exceptions.py, moto/ec2/exceptions.py, moto/elasticache/exceptions.py, moto/elasticbeanstalk/exceptions.py, moto/s3/exceptions.py, moto/s3control/exceptions.py, moto/sagemaker/exceptions.py, moto/sdb/exceptions.py
Address https://github.com/getmoto/moto/issues/7142
By taking advantage of the caching logic in [Environment](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment)
=> Speed up exception handling by re-using Environments

moto/core/responses.py, moto/core/utils.py, moto/events/models.py, moto/secretsmanager/models.py, tests/test_cloudwatch/test_cloudwatch_boto3.py
=> Techdebt: Replace deprecated utcfromtimestamp-methods

moto/ec2/models/launch_templates.py, tests/test_ec2/test_launch_templates_cloudformation.py
Looking up a launch template resource by its name attribute can be tricky when that name is randomly generated by cloudformation rather than one of the declared resource attributes. Instead, do the lookup using the physical resource id.
=> Update LaunchTemplate by physical ID rather than by name

.github/workflows/tests_terraform_examples.yml, moto/route53/models.py, other_langs/terraform/route53/providers.tf, other_langs/terraform/route53/route53.tf, tests/test_route53/test_route53.py
Fixes #7151 
The boto3 [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/change_resource_record_sets.html) states:
To delete a resource record set, you must specify all the same values that you specified when you created it.
Which is the rule that Moto follows. But it looks like the actual behaviour is more like:
To delete a resource record set, you must specify the same values for Name and Type (and TTL/ResourceRecords if specified)
Any other attributes such as MultiValueAnswer can be omitted, which is what Terraform does.
This feature was originally introduced in #5743
=> Route53: change_resource_record_sets(): Relax DELETE validation

.github/workflows/build.yml, .github/workflows/dockertests.yml, docs/docs/contributing/development_tips/new_state_transitions.rst, moto/__init__.py, moto/batch/models.py, moto/cloudfront/models.py, moto/cognitoidp/models.py, moto/cognitoidp/responses.py, moto/dax/models.py, moto/ec2/models/vpcs.py, moto/ecs/models.py, moto/glue/models.py, moto/moto_api/__init__.py, moto/s3/models.py, moto/support/models.py, moto/transcribe/models.py, moto/utilities/utils.py, tests/test_efs/test_server.py, tests/test_iam/test_iam.py
- Enable the linter for all recent Python versions
- Upgrade the Python-version for our Docker tests
- Moves the StateManager transitions to a central place, making it easier to maintain
- Cognito: The RegionAgnosticBackend had a bug where we could theoretically try to return a `backend` (or account+region) that hadn't been initialized yet. This change adds an explicit fallback
- EC2: Endpoint Services are now explicitly listed. More performant, and only a small additional maintenance overhead because the list doesn't change that often
- And finally: Skip some tests in ServerMode, because we're testing the same thing as when using the decorators
=> Techdebt: Various improvements

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
=> fix CognitoIDP: create_resource_server will crash when `scopes` not specified

moto/sagemaker/models.py, tests/test_sagemaker/test_sagemaker_model_packages.py
The current implementation for SageMaker Model Registry has some issues regarding the usage of both `ModelPackageGroup` and `ModelPackage` when using the API [CreateModelPackage](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModelPackage.html).
As the documentation states:
> [ModelPackageGroupName](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModelPackage.html#API_CreateModelPackage_RequestSyntax)
**This parameter is required for versioned models, and does not apply to unversioned models.**
> [ModelPackageName](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModelPackage.html#API_CreateModelPackage_RequestSyntax)
This parameter is required for unversioned models. It is not applicable to versioned models.
The current behavior …
=> Sagemaker model: support versioned models

moto/ssoadmin/models.py, moto/ssoadmin/responses.py, moto/ssoadmin/utils.py, tests/test_ssoadmin/test_ssoadmin.py
Implemented `sso-admin` `list_account_assignments_for_principal` [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/list_account_assignments_for_principal.html).
Included the pagination implementation of this method and ensured proper testing.
=> SSO Admin: list_account_assignments_for_principal

moto/ssoadmin/exceptions.py, moto/ssoadmin/models.py, moto/ssoadmin/responses.py, tests/test_ssoadmin/test_ssoadmin.py, tests/test_ssoadmin/test_ssoadmin_policies.py
Implemented basic CRUD operations for the following sso-admin methods:
- [get_inline_policy_for_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/get_inline_policy_for_permission_set.html)
- [put_inline_policy_to_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/put_inline_policy_to_permission_set.html)
- [delete_inline_policy_from_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/delete_inline_policy_from_permission_set.html)
Additionally renamed the the exception `ResourceNotFound` to `ResourceNotFoundException` to comply with the proper name for the exception (`SSOAdmin.Client.exceptions.ResourceNotFoundException`)
=> SSO-admin: Add basic inline policy crud operations

moto/ssoadmin/exceptions.py, moto/ssoadmin/models.py, moto/ssoadmin/responses.py, moto/ssoadmin/utils.py, tests/test_ssoadmin/test_ssoadmin_policies.py
Added AWS Managed policy operations for sso-admin permissionsets.
The following API calls are implemented:
- [detach_managed_policy_from_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/detach_managed_policy_from_permission_set.html)
- [attach_managed_policy_to_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/attach_managed_policy_to_permission_set.html)
- [list_managed_policies_in_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/list_managed_policies_in_permission_set.html)
Added additional exception handling.
Also references the managed policies [here](https://github.com/getmoto/moto/blob/master/moto/iam/aws_manag …
=> Implements sso-admin AWS Managed Policies 

moto/sagemaker/models.py, tests/test_sagemaker/test_sagemaker_model_package_groups.py
Right now, SageMaker Model Package Groups can't have tags added, removed, or deleted. This MR is a quick fix for adding this behavior.
=> SageMaker: model-package-group supports list_tags, add_tags and remove_tags

moto/ssoadmin/models.py, moto/ssoadmin/responses.py, moto/ssoadmin/utils.py, tests/test_ssoadmin/test_ssoadmin_policies.py
Add basic functionality for attaching/detaching customer managed policies references to permissionsets.
The following api calls were implemented for sso-admin:
- [attach_customer_managed_policy_reference_to_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/attach_customer_managed_policy_reference_to_permission_set.html)
- [detach_customer_managed_policy_reference_from_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/detach_customer_managed_policy_reference_from_permission_set.html)
- [list_customer_managed_policy_references_in_permission_set](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sso-admin/client/list_customer_managed_policy_references_in …
=> sso-admin: Add basic functionality for attaching/detaching customer managed policies references to permissionsets

moto/databrew/responses.py, moto/databrew/urls.py
Simplify request parsing by delegating it to the dispatch-method
The `method_dispatch` was originally introduced in #6746
=> Techdebt: Simplify DataBrew routing

moto/mq/exceptions.py, moto/mq/responses.py, moto/mq/urls.py
Simplify request parsing by delegating it to the dispatch-method
The method_dispatch was originally introduced in https://github.com/getmoto/moto/pull/6746
=> Techdebt: Simplify MQ routing

moto/pinpoint/responses.py, moto/pinpoint/urls.py
Simplify request parsing by delegating it to the dispatch-method
The method_dispatch was originally introduced in https://github.com/getmoto/moto/pull/6746
Note that the `tags`-operations still require the old routing, as the `dispatch`-method can't figure out what method to cal based on body/headers alone
=> Techdebt: Simplify PinPoint routing

moto/lakeformation/models.py, tests/test_lakeformation/test_lakeformation.py, tests/test_lakeformation/test_permission.py
Implementation for issue https://github.com/getmoto/moto/issues/7150
=> LakeFormation: extend permissions catalog functionality 

moto/rds/models.py
When trying to execute the action `CreateDBSnapshot` a deserialization error occurs. When looking at the response from Moto it became clear what the problem was:
If the value used in the template was none / nil / null it occurs in the response XML as "None" which is not valid, if a boolean value is expected. 
The proposed solution removes the values from the XML if they are none. It works with the Golang SDK.
=> RDS DB snapshot none handling

moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
This PR adds tagging support for security group rules.
<https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html#working-with-security-group-rules>
See https://github.com/localstack/localstack/issues/8642
=> EC2: Add tag support for security group rules

moto/dynamodb/models/table.py, tests/test_dynamodb/test_dynamodb.py, tests/test_dynamodb/test_dynamodb_table_with_range_key.py
Fixes #7206 
Followup to #7085, where we fixed this calculation for the `scan()` method
=> DynamoDB: query() now returns the correct ScannedCount

docs/docs/configuration/index.rst, moto/__init__.py, moto/backends.py, moto/core/botocore_stubber.py, moto/core/config.py, moto/core/custom_responses_mock.py, moto/core/models.py, tests/test_core/test_backends.py, tests/test_core/test_environ_patching.py, tests/test_core/test_request_passthrough.py
User-facing changes:
- Allow user to specify which services/urls should not be mocked
- Add type suppport for the `config`-parameter of the `mock_aws`-decorator
- Add documentation
Supporting changes:
- Refactor the config-logic with some utility methods
- Refactor the way credentials are mocked
- Overrides the `responses.BaseResponse.match`-method to add a escape hatch for URL's that should not be intercepted by us
=> Feature: Allow requests to passthrough to AWS

moto/sagemakerruntime/models.py, moto/sagemakerruntime/responses.py, moto/sagemakerruntime/urls.py, tests/test_sagemakerruntime/test_sagemakerruntime.py
Fixes #7205 
Similar to the `invoke_endpoint` implementation, but this `async` version returns an S3 bucket with the results.
Configuring results is done in the same manner as well - see http://docs.getmoto.org/en/latest/docs/services/sagemaker-runtime.html
Results that are supplied by the user are just stored in S3, instead of returned by the API.
=> SagemakerRuntime: invoke_endpoint_async() implementation

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3.py
The pagination-logic is moved to `models.py`, to ensure the distributed continuation tokens are persisted.
Tokens are an MD5-hash of the key-name at the moment, but can always be extended/changed later on.
Fixes #7152
=> S3: list_objects_v2() should have a hashed NextContinuationToken

docs/requirements.txt
There was some dependency conflict that stopped the doc builds, so our documentation was slightly outdated. This should be fixed now.
=> Admin: Update documentation generation requirements

CHANGELOG.md, moto/__init__.py, moto/core/botocore_stubber.py, moto/core/decorator.py, moto/core/models.py, tests/test_core/test_decorator_calls.py, tests/test_core/test_mypy.py
Prefixes all private methods/attributes with a `_`, to make it clear that users should not use them.
Only the following methods are now exposed:
- reset()
- start()
- stop()
Also moves the actual decorator to `moto.core.decorator.py`, to keep the `__init__`-file clean of unnecessary imports/logic
Also removes the `botocorestubber.reset()`, as we were'nt resetting the `botocorestubber` anymore. We can now call the `BackendDict.reset`-method directly.
=> Techdebt: Hide private decorator-methods/attributes

moto/core/config.py, moto/iam/models.py, moto/settings.py, tests/test_iam/test_iam.py, tests/test_iam/test_iam_groups.py, tests/test_iam/test_iam_resets.py, tests/test_moto_api/seeder/test_seeder.py
Loading these policies (and resetting them after every test) is quite time-consuming, and only a minority of Moto users will actually use these policies.
This PR only loads the IAM Managed Policies on request, either by configuring the decorator or by setting an environment variable:
```
@mock_aws(config={"iam": {"load_aws_managed_policies": True}})`
```
```
MOTO_IAM_LOAD_MANAGED_POLICIES=true
```
The overall runtime of our internal tests drop from ~45 minutes to ~30 minutes with this change.
=> IAM: Only load AWS Managed Policies on request

.github/workflows/test_outdated_versions.yml, moto/__init__.py, moto/core/versions.py, setup.cfg, tests/test_awslambda/test_lambda.py, tests/test_awslambda/test_lambda_function_urls.py, tests/test_awslambda/test_lambda_layers.py, tests/test_awslambda/test_lambda_policy.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py, tests/test_cloudformation/test_cloudformation_stack_integration.py, tests/test_core/test_auth.py, tests/test_core/test_ec2_vpc_endpoint_services.py, tests/test_core/test_importorder.py, tests/test_core/test_request_passthrough.py, tests/test_iotdata/test_iotdata.py
Officially verify that tests against an outdated version of boto3 still pass
Remove some old patching that should no longer be necessary for recent boto3 versions
Also skips a bunch of tests (~20) when running the old botocore version, because of parameters that are only available in newer versions
=> Techdebt: Verify minimum boto3-version, up minimum responses version

tests/test_acm/test_acm.py, tests/test_sagemaker/test_sagemaker_pipeline.py
Fix two more test failures that are caused by platform `time_t` not being able to represent dates beyond 2038.  This is the same approach as used in #4954.
=> Fix more test failures on platforms with 32-bit time_t

moto/moto_server/werkzeug_app.py, tests/test_dynamodb_v20111205/test_servermode.py
This was useful when running multiple MotoServer's, one for each service, but now that we use a single MotoServer to service all requests, this is no longer necessary.
With this change, MotoServer determines the intended target for an incoming request based on:
- authorization header
- path
- action header
- action-value in the body
In the following order:
- Check if path points to an internal API (such as `/moto-api/reset`)
- Check if path points to the EC2 metadata (`/latest/meta-data`)
- If the request is authorized
- Get service/region from authorization header
- Else:
- Check if the unsigned request comes from CognitoIDP (based on request body)
- Check if the unsigned request comes from STS (based on request body)
- Check if the request body contains a specific SDK version (used for …
=> MotoServer: skip using HTTP_HOST header when determining request origin

.github/workflows/tests_terraform_examples.yml, moto/acm/models.py, moto/route53/models.py, moto/route53/responses.py, tests/test_acm/test_acm.py, tests/test_route53/test_route53.py
Followup to #7144 
Fixes #7228 
This PR also ensures that `route53.list_resource_record_sets()` now returns the `MultiValueAnswer`-attribute, to ensure TF behaves the same for subsequent requests
=> ACM: DomainValidationOptions should be the same for validated certificates

moto/events/notifications.py, moto/events/utils.py
Adding typing for the event message structure.
(supported only in moto v5. Check https://github.com/getmoto/moto/pull/7230)
Document: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html
=> Refactoring: Adding typing for event message structure

moto/s3/exceptions.py, moto/s3/models.py, moto/s3/notifications.py, moto/s3/responses.py, tests/test_s3/test_s3.py
- S3 notification events are updated.
- Using an enum for the event list.
- Refactoring error message.
Documents for the supported event: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/put_bucket_notification_configuration.html
=> Using Enum for s3 notification events

Makefile, moto/sagemaker/models.py, tests/test_sagemaker/test_sagemaker_model_package_groups.py
The message that boto3 raises when a `ValidationException` happens (the model package group does not exist) is actually:
```shell
❯ aws sagemaker describe-model-package-group --model-package-group-name hello
An error occurred (ValidationException) when calling the DescribeModelPackageGroup operation: ModelPackageGroup arn:aws:sagemaker:us-east-1:12345678910:model-package-group/hello does not exist.
```
=> SageMaker: correct describe_model_package_group does not exist msg

moto/core/utils.py, tests/test_core/test_utils.py, tests/test_s3/test_s3_locales.py
`strftime` uses the current locale to translate values - so weekday/month values may not be in English
For our usecase, we need these values to always be in English, otherwise botocore is unable to parse it.
Having a hardcoded list ensures this always works, even if the user does not have an English locale installed
=> S3: LastModified-date should always be in English

moto/sns/models.py, tests/test_sns/test_subscriptions_boto3.py
We've had a report that a user could not "unset" a FilterPolicy by setting it to an empty string like they could in AWS.
This was due to always trying to decode the FilterPolicy as JSON, raising a `JSONDecodeError`. 
I've introduce a conditional check for the value, and manually set the filter policy and the matcher to None to not have a filter in place anymore. 
I've also sneaked a little change to what is returned from `GetSubscriptionAttributes`: SNS does not return the FilterPolicy if it is not set (None or empty string), and will not return the FilterPolicyScope either in that case. Also, if a FilterPolicy is set without manually setting a FilterPolicyScope, it will return the default filter policy scope as well in the fields. This was validated against AWS.
=> SNS: allow SetSubscriptionAttributes to unset FilterPolicy

CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/services/appsync.rst, docs/docs/services/backup.rst, docs/docs/services/cloudtrail.rst, docs/docs/services/codebuild.rst, docs/docs/services/codecommit.rst, docs/docs/services/dynamodb.rst, docs/docs/services/efs.rst, docs/docs/services/eks.rst, docs/docs/services/elasticache.rst, docs/docs/services/emr.rst, docs/docs/services/guardduty.rst, docs/docs/services/inspector2.rst, docs/docs/services/iot.rst, docs/docs/services/logs.rst, docs/docs/services/mediaconnect.rst, docs/docs/services/opensearch.rst, docs/docs/services/quicksight.rst, docs/docs/services/rds.rst, docs/docs/services/s3.rst, docs/docs/services/sagemaker-runtime.rst, docs/docs/services/sagemaker.rst, docs/docs/services/transcribe.rst, setup.cfg
Also removes the `sshpubkeys`-dependency from some modules, as this is really only required for EC2 (and specifically the `import_key_pair`-method).
=> Prep release 4.2.14

moto/route53/exceptions.py, moto/route53/models.py, tests/test_route53/test_route53.py
Project does not support Route53 create_hosted_zone raising ConflictingDomainExists if one attempts to create a hosted zone with the same name on the same delegation set.  According to the docs, this should raise a ClientError named ConflictingDomainExists.
Simple Reproduction
```
@mock_route53
def test():
conn = boto3.client('route53')
conn.create_hosted_zone(Name='test.com', CallerReference='1', DelegationSetId='1')
conn.create_hosted_zone(Name='test.com', CallerReference='2', DelegationSetId='1')
```
[Reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Route53/Types/ConflictingDomainExists.html)
Introduced test covers:
- Two create_hosted_zone requests on the same delegation set == should raise exception
- Two create_hosted_zone reqs with unnamed delegation set ids == should …
=> Support Route53 create_hosted_zone raising ClientError ConflictingDomainExists

.github/workflows/tests_terraform_examples.yml, moto/cloudfront/exceptions.py, moto/cloudfront/models.py, other_langs/terraform/cloudfront/cloudfront.tf, other_langs/terraform/cloudfront/providers.tf, tests/test_cloudfront/test_cloudfront_distributions.py
Fixes #7245 
TF updates the Distribution to disable it and remove it's OriginConfigs, before proceeding with the deletion. So it is possible to have an Origin configured without an `S3OriginConfig` or `CustomOriginConfig` specified.
The test that is removed here, `test_create_origin_without_origin_config`, does succeed against AWS, indicating that there is something wrong about that particular combination of input parameters. But I don't know what it is exactly. IMO it's better to be too liberal in what we accept, then too conservative and throw errors where we shouldn't.
Validation was originally introduced in #4640
=> CloudFront - Remove InvalidOriginServer validation, as it's not correct

setup.cfg
Not sure how - I think this broke somewhere with the v5 merge. I verified that all dependencies were correct on the v5 branch itself, but after it was merged into master it suddenly broke (as in - APIGatewayV2 no longer had the correct dependencies)
=> Admin: Add missing dependency for APIGatewayV2

moto/__init__.py
This is required for mypy to recognize this as exported with [`--no-implicit-reexport`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport) (implied by `--strict`).
=> Mark `mock_aws` for explicit reexport

IMPLEMENTATION_COVERAGE.md, docs/docs/services/secretsmanager.rst, moto/secretsmanager/exceptions.py, moto/secretsmanager/models.py, moto/secretsmanager/responses.py, moto/ssm/models.py, tests/test_secretsmanager/test_list_secrets.py, tests/test_secretsmanager/test_secrets_duplication.py
Fixes #7247 
New Methods:
SecretsManager: remove_regions_from_replication()
SecretsManager: replicate_secret_to_regions()
Miscellaneous:
SecretsManager: create_secrets() now supports the parameters `AddReplicaRegions` and `ForceOverwriteReplicaSecret`
SecretsManager: list_secrets() now supports the filters `primary-region` and `owning-service`
=> SecretsManager: Replica Secrets are now supported

moto/s3/models.py, tests/test_s3/test_s3.py
`list_objects_v2` called `list_objects` with a `max_keys`-value of 1000, which meant that we would always only get 1000 keys back - regardless of however were available.
Passing `max_keys=None` means that we can just tell `list_objects()` to not truncate anything, and take care of that in `list_objects_v2` instead
Fixes #7282 
This was broken in #7187
=> S3: list_objects_v2() should return more than 1000 files

docs/docs/configuration/index.rst, moto/core/config.py, moto/core/models.py, tests/__init__.py
When creating boto3-client for the first time, `boto3` will create a default session that caches all kinds of things - including credentials. Subsequent boto3-clients will reuse that `Session`.
If the first test in your test suite is mocked, the default `Session` created in that test will have fake credentials, as supplied by Moto. But if the next test is not mocked and should reach out to AWS, it would do so with the mocked credentials from our cached `Session`.
That is why Moto resets the `boto3-Session`, to make sure that it is recreated with the correct credentials (either fake or real) everytime. (This was introduced in #2578) It does come at a cost though, as instantiating a new boto3-Session is an expensive operation.
If all of your tests use Moto, and you never want to reach out …
=> Feature: Allow user to specify to not reset boto3-Sessions

moto/s3/models.py, tests/test_s3/test_s3_copyobject.py
AWS allows self-copies for keys when the bucket has versioning enabled.
Fixes #7300
Related earlier work: #6303
=> S3: Allow in place copies when bucket versioning is enabled

moto/events/models.py, moto/events/utils.py
- The typing for event messages is applided in `moto/events/models.py`.
- A base event message is added.
- The typing of `time` field in event message structure is expanded for internal use in moto.
=> Techdebt: Use typing for event message

IMPLEMENTATION_COVERAGE.md, docs/docs/services/ec2.rst, moto/ec2/models/amis.py, moto/ec2/responses/amis.py, tests/test_ec2/test_amis.py
Fixes #7318 
`modify_image_attributes()` now supports the `LaunchPermission`, `OrganizationArns` and `OrganizationalUnitArns` attributes
Internally, the launch_permissions are now stored as a dict, more closely resembling the actual data.
=> EC2: modify_image_attributes() now supports all LaunchPermissions

moto/glue/models.py, moto/glue/responses.py, tests/test_glue/helpers.py, tests/test_glue/test_datacatalog.py
This PR resolves #7316.
I believe that some other taggable Glue resources are affected by the same problem. So if this PR goes into the right direction, I might add tagging-support for those resources as well.
=> Support tags in Glue create_database

moto/autoscaling/models.py, moto/autoscaling/responses.py, tests/test_autoscaling/test_autoscaling_cloudformation.py, tests/test_autoscaling/test_autoscaling_scheduledactions.py
Add support for batch put and batch delete APIs for Scheduled Scaling Actions on AutoScaling Groups. Delete nonexistent action now fails. Also adds support for the `TimeZone` property for actions. The behavior changes I've made in this PR are to align with the behavior I can observe by experimenting with the API.
- [Batch put API reference](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_BatchPutScheduledUpdateGroupAction.html)
- [Batch delete API reference](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_BatchDeleteScheduledAction.html)
=> Add ASG Scheduled Scaling Action batch APIs

moto/core/responses.py, tests/test_cognitoidentity/test_cognitoidentity.py
Fixes #7320 
Followup to #7331
=> CognitoIdentity: Allow public actions even if IAM auth is enabled

moto/awslambda/models.py, tests/test_awslambda/test_lambda_invoke.py
With the proposed change it is possible to use `public.ecr.aws/lambda/python:3.12` image in a hacky way as
```
@mock.patch.dict(
os.environ,
{
"MOTO_DOCKER_LAMBDA_IMAGE": "public.ecr.aws/lambda/python",
},
)
def test_send_message():
...
func = lambda_.create_function(
FunctionName=function_name,
Runtime=f"{sys.version_info.major}.{sys.version_info.minor}",
ImageConfig={
"EntryPoint": [
"/var/lang/bin/python3",
"-c",
f"import sys, json; from {handler_package} import {handler_callback} as cb; cb(json.loads(sys.argv[2]), None)",
],
},
)
...
```
=> feat: use AWS Lambda entry point if ImageConfig.EntryPoint is set

moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
=> DynamoDB: create_table() now validates the number of KeySchema-items

moto/secretsmanager/models.py, moto/secretsmanager/responses.py, tests/test_awslambda/test_lambda_invoke.py, tests/test_secretsmanager/test_rotate_simple_lambda.py
`rotate_secret()` can now also be invoked using the simple AWSLambda backend.
Fixes #7342 
Fixes #7343
=> SecretsManager: rotate_secret() now supports the RotateImmediately-parameter

.github/workflows/build.yml, .github/workflows/dockertests.yml, .github/workflows/test_outdated_versions.yml, .github/workflows/tests_decoratormode.yml, .github/workflows/tests_proxymode.yml, .github/workflows/tests_real_aws.yml, .github/workflows/tests_sdk_dotnet.yml, .github/workflows/tests_servermode.yml, moto/acm/models.py, moto/acmpca/models.py, tests/test_awslambda/test_lambda_invoke.py, tests/test_core/test_mypy.py, tests/test_ec2/test_route_tables.py
Cryptography >= 40.0.0 introduces a new property, `not_valid_before_utc`, that will replace the old `not_valid_before`-property. This PR supports both properties (and therefore all versions of cryptography).
This PR also:
- updates some CI dependencies
- tests these changes with an older version of `cryptography`
- improves an EC2 test to reduce the chances that it finds a resources created by other tests.
- fixes some `pytest` warnings since tests (methods that start with `test_`) should not return anything
=> Techdebt: Remove warnings

docs/requirements.txt, moto/cognitoidp/models.py, moto/ec2/utils.py, setup.cfg, tests/test_cognitoidp/test_cognitoidp.py, tests/test_ec2/test_key_pairs.py
Supercedes #7285 
Fixes #7244 
Fixes #7248
=> Techdebt: Remove ECDSA dependency

docs/docs/services/s3.rst
`upload_file, upload_fileobj` method is added to the documentation of moto.
closes #7364 
https://github.com/getmoto/moto/blob/7c87bddeae2e222f29def0aa73735baac1d32eb6/tests/test_s3/test_s3.py#L814-L829
https://github.com/getmoto/moto/blob/7c87bddeae2e222f29def0aa73735baac1d32eb6/tests/test_s3/test_s3.py#L3214-L3232
=> Doc: Adding `upload_file, upload_fileobj` method to the document

moto/dynamodb/models/__init__.py, tests/test_dynamodb/exceptions/test_dynamodb_transactions.py, tests/test_dynamodb/test_dynamodb.py
DynamoDB: transact_write_items() should raise ValidationException when putting and deleting the same item.
Given
`main.py`
```python
import boto3
def main():
client = boto3.client("dynamodb", region_name="us-east-1")
client.transact_write_items(
TransactItems=[
{
"Put": {
"TableName": "test-table",
"Item": {
"pk": {"S": "test-pk"},
"sk": {"S": "test-sk"},
"field": {"S": "test-field"}
}
}
},
{
"Delete": {
"TableName": "test-table",
"Key": {
"pk": {"S": "test-pk"},
"sk": {"S": "test-sk"},
}
}
}
]
)
if __name__ == "__main__":
main()
```
and `test_main.py`
```python
import boto3
from moto import mock_aws
@mock_aws
def test_main():
client = boto3.client("dynamodb", region_name="us-east-1")
client.create_table(
TableName="test-table",
KeySchema=[
{"AttributeName": "pk", "KeyType": "HASH"}, …
```
=> DynamoDB: transact_write_items() should raise ValidationException when putting and deleting the same item

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
- Return `SMS_MFA` challenge if user has sms MFA enabled in `admin_initiate_auth`
- Support `SMS_MFA` type in `respond_to_auth_challange`
=> CognitoIDP: Add `SMS_MFA` support to admin_initiate_auth and respond_to_auth_challenge methods

moto/autoscaling/models.py, moto/autoscaling/responses.py, tests/test_autoscaling/test_autoscaling_group_filters.py
**Description:**
This PR introduces support for filtering auto-scaling groups by tags in the [describe_auto_scaling_groups ](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling/client/describe_auto_scaling_groups.html)method. It enhances the functionality of the method by allowing users to specify filters based on tag keys, tag values, or key-value pairs.
=> ASG: support filters in describe_autoscaling_groups

moto/dynamodb/models/dynamo_type.py, moto/dynamodb/responses.py, tests/test_dynamodb/test_dynamodb_condition_expressions.py
The tests in this example (prior to the fix) reproduce an issue where the exception `TypeError: Object of type DynamoType is not JSON serializable` is raised when `Dynamo.Item.to_json` is passed a top level list.
I have chosen to test this via a condition expression with `ReturnValuesOnConditionCheckFailure="ALL_OLD"` as this is a very close reproduction to the issue I faced.
Some additional tests for top level string sets and lists in dictionaries were added to ensure different paths through the new and existing code are handled correctly.
Also fixes issue with `UPDATED_NEW` handling for lists:
- Before this change: when `update` is called to change one value in a list, `_build_updated_new_attributes` attempts to return the list with the value at the position of the changed element as an …
=> DynamoDB: fix: support top level lists for Dynamo Item to_json

moto/rds/models.py, tests/test_rds/test_rds.py
Fix a regression introduced in #6444, in which copying a snapshot of an already deleted DB instance results in raising a `DBInstanceNotFoundError`.
The expected behavior is that copying a snapshot is supported regardless whether its source database exists or not.
Change `create_db_snapshot` to accept a `Database` object (instead of an identifier), and use this flow in the `copy_db_snapshot` implementation. This works because the actual `Database` object is not deleted (as it is referred to by the snapshot), but rather it is already removed from the `databases` dictionary.
=> RDS: Allow copying snapshots of deleted DB instances

.github/workflows/tests_terraform_examples.yml, moto/ec2/responses/virtual_private_gateways.py, other_langs/terraform/ec2/provider.tf, other_langs/terraform/ec2/vpc.tf
It was discovered that Terraform was crashing with the following sample:
```
module "vpc" {
source = "terraform-aws-modules/vpc/aws"
name = "my-vpc"
cidr = "10.0.0.0/16"
azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
enable_nat_gateway = true
enable_vpn_gateway = true
tags = {
Terraform = "true"
Environment = "dev"
}
}
```
With the following stack trace:
```
Stack trace from the terraform-provider-aws plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10353a858]
goroutine 293 [running]:
github.com/hashicorp/terraform-provider-aws/internal/tags.(*TagData) …
```
=> EC2: Fix vpn gateway tags and type

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3_eventbridge_integration.py
Sending a notification when an object is uploaded to S3 via POST request.
related: #7363
=> S3: Sending notification to EventBridge `ObjectCreated:Post`

moto/s3/models.py, tests/test_s3/test_s3_eventbridge_integration.py
- Adding a test of EventBridge notification for `ObjectCreated:Copy`.
- Some helper methods to set up AWS resources and retrieve sent event logs were added for reuse.
- `disable_notification` argument were added for `put_object` method to handle notification.
=> S3: Adding tests of EventBridge notification `ObjectCreated:Copy`

moto/cloudformation/parsing.py, moto/iam/models.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Scenario: Resource A depends on resource B
When CloudFormation tries to delete both resources, it will do so in an unspecified order.
If CF tries to delete resource B first, it will fail because A depends on it
CloudFormation continues with the deletion of resource A (and any other unrelated resources)
Because B is not yet deleted, CF will iterate over the remaining resources. Nothing depends on resource B anymore, so it will be deleted successfully.
This was already implemented, but with the caveat that we would only iterate over the list of remaining resources up to 5 times.
With this change, we will iterate as long as we are deleting some resources per iteration, i.e.: there is some progression. This has two benefits:
- Deletion of resources with a chain of 5 or more dependencies …
=> CloudFormation: Allow deletion of deeply nested structures

moto/s3/models.py, tests/test_s3/test_s3_eventbridge_integration.py
PR for DeleteObject in #7363 
- send EventBridge notification when Object is Deleted(for buckets that are versioned and not versioned)
- added a test case for sending eventbridge notification
=> S3: Add EventBridge Notification for DeleteObject

moto/dynamodb/parsing/validators.py, tests/test_dynamodb/test_dynamodb.py
when doing dynamodb `update_item`, it should check for type mismatch 
e.g. for attribute defined as `String`, it should throws an error when `NULL`, or other data type e.g. `Number`, `Binary` is received
=> fix: add dynamodb type mismatch validator

moto/secretsmanager/models.py, tests/test_secretsmanager/__init__.py, tests/test_secretsmanager/test_secretsmanager.py
=> SecretsManager: Ensure AWSPREVIOUS is only ever tied to one version

moto/s3/models.py, tests/test_s3/test_s3_eventbridge_integration.py
- Sending a notification to EventBridge when multipart upload is completed.
- Unittest is added.
related #7363
=> S3: Sending notification to EventBridge `OBJECT_CREATED_COMPLETE_MULTIPART_UPLOAD_EVENT`

docs/docs/multi_account.rst
Later examples have a `client1` and a `client2`. This one only has `client`.
=> Docs: refer to client, not client2, in sample

moto/emr/models.py, moto/emr/responses.py, tests/test_emr/test_emr_cloudformation.py
=> CloudFormation: Support AWS::EMR::InstanceGroupConfig

moto/ec2/models/vpcs.py
=> Techdebt: Lock VPC service collection to remove race condition

IMPLEMENTATION_COVERAGE.md, docs/docs/services/s3.rst, moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_eventbridge_integration.py, tests/test_s3/test_s3_storageclass.py
See @7363
@tsugumi-sys The `restore_object`-function was implemented in S3, it was just hidden in `responses.py`.
This PR:
- extracts the logic into the models-class
- Adds a notification when a Restore-action is initiated and completed
Any feedback/improvements that you can see?
=> S3: Add Notifications for Restore-actions

IMPLEMENTATION_COVERAGE.md, docs/docs/services/resiliencehub.rst, moto/backend_index.py, moto/backends.py, moto/resiliencehub/__init__.py, moto/resiliencehub/exceptions.py, moto/resiliencehub/models.py, moto/resiliencehub/responses.py, moto/resiliencehub/urls.py, tests/test_resiliencehub/test_resiliencehub.py, tests/test_resiliencehub/test_resiliencyhub_tagging.py
=> Service: ResilienceHub

moto/dynamodb/models/__init__.py, moto/dynamodb/models/table.py, moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/test_dynamodb_table_with_range_key.py, tests/test_dynamodb/test_dynamodb_table_without_range_key.py
`ConsistentRead` is not supported on global secondary indexes for Query and Scan operations. Adding validation.
`ConsistentRead` is still supported on local secondary indexes and on the primary key, so this behaviour must not change.
=> DynamoDB: raise validation error on consistent read on GSI

moto/core/botocore_stubber.py, moto/core/responses_custom_registry.py, moto/core/utils.py, tests/test_s3/test_s3_custom_endpoint.py
Prior to the commit that introduced mock_aws (a7f3b367b), it was possible to use the requests mock to access S3 presigned URLs that had a custom endpoint.
This commit restores that behavior by applying the hostname-remapping logic from BotocoreStubber to CustomRegistry.
=> Fix requests mock for custom S3 endpoints

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
The current implementation is not updating the Cognito IDP User field UserLastModifiedDate when updating or removing attributes. So this change proposes to fix this.
=> Cognito: update UserLastModifiedDate when changing user attributes

.github/workflows/tests_real_aws.yml, moto/cloudformation/parsing.py, moto/cloudformation/responses.py, tests/test_cloudformation/__init__.py, tests/test_cloudformation/test_cloudformation_custom_resources.py, tests/test_cloudformation/test_conditions.py
=> CloudFormation: Allow Conditions in Outputs

Makefile
If you run `make format`, ruff shows the following warning.
I changed the ruff command to solve this warning.
=> Admin: Fix ruff warning

moto/s3/exceptions.py, moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3.py
- Raise error when both `Days` and `Type` parameters exist in restore object request.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/restore_object.html
related: https://github.com/getmoto/moto/issues/7467
=> S3: `Days` must not be provided for select request when restoring object

moto/autoscaling/models.py, moto/autoscaling/responses.py, tests/test_autoscaling/test_autoscaling.py
Use the current time instead of hard coded '2013-05-06T17:47:15.107Z' when creating an autoscaling group.
Updated template to return the correct created time.
Added unit test.
=> Sets autoscalinggroup CreatedTime during creation.

IMPLEMENTATION_COVERAGE.md, docs/docs/services/resiliencehub.rst, moto/resiliencehub/exceptions.py, moto/resiliencehub/models.py, moto/resiliencehub/responses.py, moto/resiliencehub/urls.py, tests/test_resiliencehub/test_resiliencyhub_resources.py
- create_app_version_app_component()
- create_app_version_resource()
- import_resources_to_draft_app_version()
- list_app_version_app_components()
- list_app_version_resources()
- list_app_versions()
- publish_app_version()
See #7438
=> ResilienceHub - Resource-related functionality

moto/dynamodb/models/table.py, tests/test_dynamodb/__init__.py, tests/test_dynamodb/test_dynamodb.py, tests/test_dynamodb/test_dynamodb_table_without_range_key.py
=> DynamoDB: query(): LastEvaluatedKey does not have to exist

moto/moto_server/threaded_moto_server.py
This PR aims to replace the busy waiting of the `ThreadedMotoServer` startup with the more clear `threading.Event` object. This change will also reduce the `ThreadedMotoServer.start` method execution time, as the Werkzeug server startup time is usually less than 0.1 seconds.
=> Server: check ready state with `threading.Event`

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_dynamodb.py
Currently, mock_resourcegroupstagging is not able to get the dynamodb tables created using mock_dynamodb. This PR is to add that support.
=> Adding dynamodb support to get_resources in resourcegroupstagging api

moto/kinesis/responses.py, tests/test_kinesis/test_kinesis.py, tests/test_kinesis/test_server.py
The default [boto3 response](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kinesis/client/list_streams.html) includes the StreamSummaries key.  This is added in this PR.
Closes #7476
=> Add StreamSummaries to the respose of kinesis.list_streams

Makefile, moto/route53resolver/models.py, tests/test_route53resolver/test_route53resolver_rule.py
- Updated default value for `shared_status` in route53resolver
- Removed unused code from `Makefile` which was used for terraform tests
- Updated the test cases
=> updated default value for share status in route53resolver

tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
- Fix the following error by ruff: 
- black format is applied.
```
tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py:851:9: F841 Local variable `image` is assigned to but never used.
```
=> Fix: ruff check error in `test_resourcegroupstaggingapi.py

Makefile
- Add format checking by ruff in Github Action workflow.
https://docs.astral.sh/ruff/formatter/
=> Adim: Add format check by ruff in Github Actions

moto/ec2/models/__init__.py, moto/secretsmanager/list_secrets/filters.py, tests/test_secretsmanager/test_list_secrets.py
This PR addresses the issue in the list operation of Secrets Manager where filters were incorrectly applied to the entire key rather than just the prefix.
Previously, filters were matched against the entire key, which is incorrect. The correct behavior is to match filters against the prefix only.
- Reference: [AWS Boto3 Secrets Manager list_secrets documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager/client/list_secrets.html#list-secrets)
- This issue was initially reported in [LocalStack issue #4820](https://github.com/localstack/localstack/issues/4820).
- AWS validated test case implemented [here](https://github.com/localstack/localstack/pull/10520).
- More details on the list api: …
=> fixed secretsmanager list api to support filtering correctly

moto/sns/models.py, tests/test_sns/test_application_boto3.py
=> SNS: delete_endpoint() is now an idempotent operation, just like AWS

moto/s3/models.py, tests/test_s3/test_s3_list_objects.py
=> S3: list_objects() Marker can be any keyname

moto/secretsmanager/list_secrets/filters.py, moto/secretsmanager/models.py, tests/test_secretsmanager/test_secretsmanager.py
This PR resolves the problem outlined in https://github.com/localstack/localstack/issues/10477.
- Secret creation without tags.
- Addition of tags to the secret.
- Removal of all tags from the secret.
- Describing the secret reveals a `Tags` key with an empty list `[]`. *(Previously, this functionality was defective in moto.)*
- Secret creation without tags.
- Addition of tags to the secret.
- Complete tag removal using `untag_resource` by specifying all tags.
- On describing the secret, it should not contain of any tags. *(Previously, this was not correctly implemented in moto.)*
- Changing the default value of tags to `None` to identify weather the tags ever added.
- Addition of `NoneType` handling in filtering functions
- Updated logic for `untag_resource` to remove multiple tags at …
=> fix tag operations in secretsmanager

moto/dynamodb/models/table.py, moto/dynamodb/responses.py, tests/test_dynamodb/test_dynamodb.py
Recent logic added in 194088 to accommodate a missing start key brain-damaged pagination because determination of previously-encountered items was not implemented correctly for all use cases.
* Make sure comparisons are performed in the sense of `ScanIndexForward` (previously, this was assumed to be `True` -- the default -- and returned incorrect results when reverse sorting was requested)
* When querying/scanning a secondary index, make comparisons using the index attribute(s) instead of the primary table attribute(s)
This commit now passes my project's internal test suite, and also passes all existing moto DynamoDB unit tests. I expect to add a commit with a unit test that exercises a query with reverse sorting on a GSI with different key attributes, which describes my application's …
=> DynamoDB: query/scan secondary index fixes

moto/stepfunctions/models.py, tests/test_stepfunctions/parser/__init__.py, tests/test_stepfunctions/parser/templates/failure.json, tests/test_stepfunctions/parser/test_stepfunctions.py, tests/test_stepfunctions/test_stepfunctions.py
Fixes #7561
Also changes the existing tests for the parser to validate this behaviour against AWS
=> SFN: Input for mock should be the same as input for parser

moto/cognitoidp/models.py
If an unexisting refresh token was passed to the `initiate_auth` with the `REFRESH_TOKEN_AUTH` flow, firstly the operation fails because of `KeyError` and after a few retrials, Moto returns a 500 status code response.
The fix was to use the `.get()` method to get a dictionary member or `None` if such doesn't exist instead of direct dictionary access with `[]`.
=> fix(cognito-idp): avoid KeyError on unexisting refresh token

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstagging_glue.py
This PR fixes a bug in ResourceGroupsTaggingAPI GetResources operation when called in us-east-2.
Internally the operation enumerates through the backends on various services. Backends also check whether a given service is available in a region. In this case, if a request to ResourceGroupsTaggingAPI GetResources is made to us-east-2 (or any region where Workspaces is not supported), an unhandled exception is thrown.
The issue is fixed by checking whether a service exists in a given region before attempting backend retrieval.
```py
$ ipy
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import boto3
...: import os
...: from moto import mock_aws …
```
=> ResourceGroupsTaggingAPI: Fix Workspaces access in unsupported region

moto/ec2/models/amis.py, moto/ec2/responses/amis.py, moto/ec2/utils.py, tests/test_ec2/test_amis.py
Extend `Filters=` support in `ec2.describe_instances()` so that it now supports `product-code` and `product-code.type` filters, with the following restriction:
* All codes registered in `amis.json` in an image's `product_codes` property are treated as "marketplace" codes, i.e. it is not possible to specify an image with "devpay" codes.
The latent formatting support clearly intended these to be used as marketplace codes, and that's the use case I require, so this scratches my itch as-is.
=> ec2: improve describe_instances() filters

moto/athena/models.py, tests/test_athena/test_athena.py
Resolves: https://github.com/getmoto/moto/issues/7602
Add a None type check before iterating. Check is to a recent addition to the Athena Execution model. This allows for None configs, as is supported by Athena for configurations overridden by Workspace configs.
=> Athena: Check for None on config before iterating to avoid execute_query error

moto/elasticache/models.py, tests/test_elasticache/test_elasticache.py
Due to an oversight, a default cache cluster is being created during the initialization phase of the Elasticache model. The default cluster is being created under the `cache_cluster` dictionary.
- Removed the default `cache_cluster` creation step
- Update the `test_describe_all_cache_clusters` Elasticache test to exclude the action to delete the default `cache_cluster`
#7591
=> Refactor: Remove the Elasticache default cluster configuration

moto/apigateway/models.py, moto/apigateway/responses.py, moto/apigateway/urls.py, tests/test_apigateway/test_apigateway.py, tests/test_apigateway/test_apigateway_stage.py, tests/test_apigateway/test_server.py
Remove the manual request dispatching where possible, and just let the `dispatch`-method handle this.
This PR just adds tests for `(un)tag_resource`, as the functionality already existed
=> APIGateway: Refactor request handling

moto/awslambda/models.py, moto/awslambda/responses.py, moto/awslambda/urls.py, moto/core/responses.py, tests/test_awslambda/test_lambda_eventsourcemapping.py
=> Techdebt: Refactor request-handling AWSLambda

moto/route53/responses.py, moto/route53/urls.py
=> Techdebt: Refactor Route53 responses

moto/ec2/models/security_groups.py, tests/test_ec2/test_security_groups.py
This PR fixes an unhandled case where a non-existent security group when passed to `RevokeSecurityGroupIngress` and `RevokeSecurityGroupEgress` would raise an `AttributeError`.
```
File "/home/viren/repo/moto-ext/moto/core/responses.py", line 270, in dispatch
return cls()._dispatch(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/viren/repo/moto-ext/moto/core/responses.py", line 478, in _dispatch
return self.call_action()
^^^^^^^^^^^^^^^^^^
File "/home/viren/repo/moto-ext/moto/core/responses.py", line 575, in call_action
response = method()
^^^^^^^^
File "/home/viren/repo/moto-ext/moto/ec2/responses/security_groups.py", line 236, in revoke_security_group_ingress
self.ec2_backend.revoke_security_group_ingress(**args)
File …
```
=> EC2: Fix unhandled error for nonexistent security groups

moto/dynamodb/parsing/executors.py, tests/test_dynamodb/test_dynamodb_update_expressions.py
=> DynamoDB: Deleting items from a set should be idempotent

moto/ses/responses.py, other_langs/tests_java/pom.xml, other_langs/tests_java/src/test/java/moto/tests/SESTest.java, tests/test_ses/test_server.py
=> SES: GetSendStatistics() now uses a datetime format that the Java SDK understands

moto/dynamodb/responses.py
Behaviour stays the same, but this will make it easier to reuse the validation in the future
=> Techdebt: DynamoDB: Simplify validation for CreateTable

moto/ec2/models/route_tables.py, tests/test_ec2/test_route_tables.py
In my work, we do DescribeRouteTables and filter by `route.nat-gateway-id`. However, it is currently not implemented yet and returns the following error:
```
moto.ec2.exceptions.FilterNotImplementedError: The filter 'route.nat-gateway-id' for DescribeRouteTables has not been implemented in Moto yet. Feel free to open an issue at https://github.com/getmoto/moto/issues
```
- Implement filter by `route.nat-gateway-id`
- Add test
=> RouteTables: Filter by route.nat-gateway-id

moto/ec2/models/network_acls.py, tests/test_ec2/test_network_acls.py
I attempted to add coverage to DescribeNetworkAcls when using the `association.subnet-id` filter (since [this issue](https://github.com/localstack/localstack/issues/10097) was reported a while ago) to ensure it works as expected.
This also fixes a small bug where network ACLs could be deleted even when associated to subnets (according to [AWS's documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteNetworkAcl.html), this cannot happen).
=> EC2: Add test for DescribeNetworkAcls using the association.subnet-id filter

moto/wafv2/exceptions.py, moto/wafv2/models.py, moto/wafv2/responses.py, moto/wafv2/utils.py, tests/test_wafv2/test_wafv2.py
This pull request introduces support for IP Sets and Logging configurations resources within the WAFv2 service. It includes the implementation of new operations:
- create_ip_set
- delete_ip_set
- list_ip_sets
- get_ip_set
- update_ip_set
- put_logging_configuration
- get_logging_configuration
- list_logging_configurations
- delete_logging_configuration
Additionally, two CRUD tests have been added for these resources. These tests have been successfully executed against AWS without any complications.
Partially addresses localstack/localstack#10558
=> WAFv2: Add support for IP sets and logging configuration

moto/databrew/models.py, tests/test_databrew/test_databrew_recipes.py
Corrects an issue where the Create Date of the Latest Working version remains the same as the published version. This should be the Publish Date as observed through interactions with AWS API Interactions for Publish Recipe.
Steps:
* Added field setting in moto/databrew/models.py
* Updated Publish Recipe Tests to compare publish date and latest working create date
Issues Addressed:
* [Issue 7666](https://github.com/getmoto/moto/issues/7666)
=> Update Data Brew Recipe Latest Working Version Create Date

IMPLEMENTATION_COVERAGE.md, docs/docs/services/iam.rst, moto/iam/models.py, moto/iam/responses.py, tests/test_iam/test_iam.py
IAM instance profile missed an implementation to add & remove tags (besides creation). This PR adds the functionality.
=> IAM: add instance profile tagging

moto/dynamodb/parsing/executors.py, tests/test_dynamodb/test_dynamodb_update_expressions.py
=> DynamoDB: update_item() now throws the appriopriate exception when adding an empty set

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
The resource group tagging api `get_resources` method doesn't allow for filtering for lambda functions using a `lambda:function` resource type filter, it's only checking for `lambda` - this adds support for that, in the same way it's done for other kinds of resources
First commit has the failing test:
```
resp = rtapi.get_resources(ResourceTypeFilters=["lambda:function"])
>       assert_response(resp, [circle_arn, rectangle_arn])
tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py:708: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
response = {'ResourceTagMappingList': [], 'ResponseMetadata': {'HTTPHeaders': {'date': 'Mon, 13 May 2024 11:09:28 GMT', 'server':...Hw8'}, 'HTTPStatusCode': 200, 'RequestId': …
```
=> ResourceGroupTagging: Fix filtering for lambda functions with "lambda:function"

moto/core/responses.py
Following #7626, we've noticed a regression in performance while calling API Gateway. Trying to pin down the issue, it seems `BaseResponse._get_action_from_method_and_request_uri` was responsible for it, as the caching is now disabled (following #6746) as we create a new `APIGatewayResponse` for every call to `BaseResponse.dispatch`. API Gateway used `BaseResponse.dispatch_method` before the refactor, which didn't need to route the incoming request to the right operation. 
This PR pulls building the `method_url` out of `_get_action_from_method_and_request_uri` in order to be cacheable (the cache key is the service name and the region, as it seems we're creating the specs based on it, not sure the region is really mandatory?). We then used the cached result in order to regex match the …
=> cache methods_url for BaseResponse._get_action_from_method_and_request_uri

moto/ecs/models.py, tests/test_ecs/test_ecs_boto3.py
Resolves https://github.com/getmoto/moto/issues/7664
=> ECS: update_service reflects correct counts

moto/ssoadmin/models.py
This small PR fixes the service name passed to the `BackendDict` for the SSO Admin service.
=> Fit service name for sso-admin

CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/services/events.rst, docs/docs/services/lakeformation.rst, docs/docs/services/networkmanager.rst, docs/docs/services/quicksight.rst, moto/core/responses.py, setup.cfg
Reverts ##7713 and #7715 - now that there is a new Docker release, the latest requests-module no longer breaks. (https://github.com/docker/docker-py/issues/3256)
A few days ago the `aws` terraform provider was updated from `5.50.0` to `5.51.0`. This broke our Terraform tests for ACM and Route53. More specifically, a call to `ChangeResourceRecordSets` suddenly no longer worked.
The underlying problem is that Terraform used to make a POST request to `/2013-04-01/hostedzone/<id>/rrset/`, but with the `5.51.0` release would make a request to `/2013-04-01/hostedzone/<id>/rrset` (without trailing slash).
It's safe to assume that AWS allows both versions, so this PR also changes our logic to also allow both versions of this particular URL.
(A first iteration made all leading slashes optional, to …
=> Prep release 5.0.8

tests/test_dynamodb/test_dynamodb_update_expressions.py, tests/test_s3/test_s3_logging.py, tests/test_sns/test_application_boto3.py
DynamoDB: The AWS error message has a bit more information, so we can't match on equality
S3: The `put_bucket_logging` is async, so there may be a small delay before the `LoggingConfig` is available
SNS: Fix the error handling - the old implementation would attempt to use the `application_arn` before it was defined, if a command failed for any reason
=> Admin: Fix AWS parity tests

moto/applicationautoscaling/models.py, moto/elb/models.py, moto/elbv2/models.py, moto/iotdata/models.py, moto/opsworks/models.py, moto/signer/models.py
This PR updates certain BackendDict initialisations so that they use proper Botocore service name.
Earlier, these services used `ec2` or `lambda` since `boto3.Session().get_available_regions(...)` used to return an empty list.
There are still a few instantiations remaining that were not updated for the above reason, these are:
- `redshiftdata` should use `redshift-data`
- `apigatewaymanagementapi` should use `apigatewaymanagementapi`
- `bedrockagent`
- `ec2instanceconnect` should use `ec2-instance-connect`
=> Fix BackendDict instantiation service names

IMPLEMENTATION_COVERAGE.md, docs/docs/services/sso-admin.rst, moto/ssoadmin/models.py, moto/ssoadmin/responses.py, tests/test_ssoadmin/test_ssoadmin_instances.py, tests/test_ssoadmin/test_ssoadmin_permission_sets.py
New methods:
- list_accounts_for_provisioned_permission_set()
- list_instances()
- list_permission_sets_provisioned_to_account()
- update_instance()
The `list_instances`-call returns a default SSO instance that is created on start-up.
=> SSO-Admin instances

moto/dynamodb/models/table.py, tests/test_dynamodb/test_dynamodb_query.py
=> DynamoDB: query() should handle GSI's without range key

moto/ec2/models/key_pairs.py, moto/ec2/responses/key_pairs.py, moto/ec2/utils.py
Currently in the internal representation for EC2 Key Pairs, the `KeyPair` class defines an attribute `material`. However this attribute is not consistently used.
If the key pair object is created using `ImportKeyPair`, `material` contains the base64 encoded public key. If the key pair is created using `CreateKeyPair`, `material` contains the PEM encoded private key.
This PR introduces makes changes such that `material` always contains the private key material (wherever applicable) and adds a new attribute `material_public` always contains the public key in OpenSSH format. There is no impact on the external API.
=> EC2: Fix inconsistent private/public key pair attribute

moto/ec2/models/amis.py, tests/test_ec2/test_amis.py
This adds a missing mapping on `self` to the current `account_id` for the `describe_images` `exec_users` endpoint parameter, as well as a check bypass for public images.
Similar to the `Owners` field, `ExecutableUsers` can be filtered by `self` (ref: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html#API_DescribeImages_RequestParameters)
Currently, filtering images with `exec_users=["self"]` returns an empty list, even when having public images.
=> EC2: describe_images() - feat: support filtering images by ExecutableUsers=['self']

moto/cognitoidp/models.py, moto/cognitoidp/responses.py, moto/cognitoidp/utils.py, tests/test_cognitoidp/test_cognitoidp.py
boto3 supports pagination for `admin_list_groups_by_user`. This commit adds the same flags (Limit and NextToken) to the moto cognitoidp module.
See: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/admin_list_groups_for_user.html
Unit tests for pagination are added as part of the pull request. Most of this is just copied over code from list_groups with modifications for adjusting to the `admin_list_groups_by_user` API.
=> CognitoIDP: feat: support pagination for admin_list_groups_by_user

moto/eks/responses.py
```
moto.eks.create_nodegroup(
cluserName="foo",
nodegroupName="bar",
taints=[{"key":"soft","effect":"PREFER_NO_SCHEDULE"}]
)
print(
moto.eks.describe_nodegroup(
cluserName="foo",
nodegroupName="bar",
).get('nodegroup', {}).get('taints')
)
```
I expect `taints` to be `[{"key":"soft","effect":"PREFER_NO_SCHEDULE"}]`
I see `taints` is `[]`
This pull request
=> fix(eks): set taints in create_nodegroup

moto/elbv2/models.py, tests/test_elbv2/test_elbv2.py
As per the current implementation if we use `client_keep_alive.seconds` in `elbv2` we get `InvalidConfigurationRequest` error thrown. 
This PR adds `client_keep_alive.seconds ` attribute to the `modify_load_balancer_attributes` handler and writes a test to verify the changes. 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattribute.html
=> elbv2: add client_keep_alive.seconds to modify load balancer attributes

moto/sts/responses.py
The `get_federation_token` operation did not return the arn with the correct partition in the `FederatedUser.Arn` field, it was hardcoded to `aws`.
* Return the federated user ARN with the correct partition for the `get_federation_token` response
=> Add correct partition for get_federation_token response

moto/dynamodb/models/table.py, tests/test_dynamodb/test_dynamodb_query.py, tests/test_dynamodb/test_dynamodb_scan.py
Fixes #7751 
Given a Table with attributes (pk, sk)
And a GSI  with attributes (gsi_pk, gsi_sk)
When processing an `ExclusiveStartKey`, Moto would use the combination of `gsi_pk` and `gsi_sk` to determine whether a specific item comes before or after this Key (and therefore whether this specific item should be returned).
However: GSI sort keys do not need to be unique. If we have 10 items where `gsi_pk` and `gsi_sk` have the same value, and our StartKey is the 5th element, we need another way to determine the sort order. That's why we now also use the `sk`-attribute to determine whether an item comes before or after the StartKey.
Note that the existing functionality stays the same - if `gsi_sk` is not unique, it will be ordered based off that value.
All tests have been verified against …
=> DynamoDB: Query() should use all sort keys when sorting

moto/cloudformation/utils.py, setup.cfg, tests/test_cloudformation/test_validate.py
[cfn-lint 1.3.0](https://pypi.org/project/cfn-lint/1.3.0) was released on 2024-06-19.
Currently Moto pins it as `cfn-lint>=0.40.0` which causes the latest version to be picked up and integration to break.
This PR fixes the breaking changes and updates its usage.
=> Fix cfn-lint breaking changes

moto/dynamodb/models/table.py, tests/test_dynamodb/test_dynamodb_query.py, tests/test_dynamodb/test_dynamodb_scan.py
=> DynamoDB: query() should use all range keys when sorting

moto/elbv2/exceptions.py, moto/elbv2/models.py, moto/elbv2/responses.py, tests/test_elbv2/test_elbv2.py
Attaching too many certificates to a load balancer listener (with the `AddListenerCertificates` operation) should raise a `TooManyCertificatesException`. This check is not currently implemented.
25 seems to be the limit as per [AWS docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html).
=> elbv2: check for too many certificates

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
AWS Resource Groups Tagging API only supports S3 bucket resources[1], so `s3` and `s3:bucket` are interchangeable and return the same results.
[1]: https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html
Closes #7797
=> ResourceGroupsTagging: Add support for `s3:bucket` resource type filter

docs/docs/getting_started.rst
A few typos/fixes I saw when reading the docs.
=> Fix docs typos

moto/dynamodb/models/__init__.py, tests/test_dynamodb/test_dynamodb.py, tests/test_dynamodb/test_dynamodb_batch_write.py
=> DynamoDB: transact_write_items() should not require ExprAttrNames

moto/dynamodb/parsing/ast_nodes.py, tests/test_dynamodb/exceptions/test_dynamodb_transactions.py
Fixes #7817 
`SET action1, action2` is allowed. `SET action1 SET action2` is not allowed.
So when validating this, we need to count the number of clauses (SET statements)  - not the number of actions ([action1, action2]).
=> DynamoDB: transact_write_items() should validate set clauses, not actions

moto/ec2/models/instances.py
When using the `run_instances` method in moto and specifying the version as `$Default` or `$Latest`, an error occurs. This issue prevents users from running instances with the `$Default` or `$Latest` version.
This is a complete test which reproduces the issue.
```python
from moto import mock_aws
import boto3
import traceback
@mock_aws
def test():
client = boto3.client('ec2', region_name='us-west-1')
launch_template = client.create_launch_template(
LaunchTemplateName='test',
VersionDescription='test',
LaunchTemplateData={
'InstanceType': 't2.micro',
}
)
launch_template_id = launch_template['LaunchTemplate']['LaunchTemplateId']
try:
response = client.run_instances(
LaunchTemplate={
'LaunchTemplateId': launch_template_id,
"Version": "$Default"
},
MinCount=1,
MaxCount=1,
)
except Exception as …
```
=> EC2: run_instances() can now use $Default or $Latest  launch template version

moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
It was reported that [`DescribeSecurityGroupRules`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSecurityGroupRules.html) does not return the `Description` field, see https://github.com/localstack/localstack/issues/8985.
Furthermore it was observed that the response is incorrectly constructed if the rules were adding to the security group using the [`IpPermission`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html) objects:
```text
$ security_group_id=$(awslocal ec2 create-security-group --group-name example --description "Example security group" | jq -r .GroupId)
$ awslocal ec2 authorize-security-group-ingress --group-id "${security_group_id}" \
--ip-permissions 'IpProtocol=tcp,FromPort=1111,ToPort=1111,IpRanges=[{CidrIp=127.0.0.1/32,Descri …
```
=> EC2: Fix security group rule enumeration

moto/events/models.py, moto/events/responses.py, moto/events/utils.py, tests/test_events/test_events.py
Supercedes #7842 
We now use the `@paginate`-decorator, instead of relying on custom pagination logic. Also adds a test to verify this feature now works properly.
=> Events: list_targets_by_rule() pagination

moto/s3/responses.py, tests/test_s3/test_s3_bucket_policy.py
Previously, policy enforcement for s3:PutObject only occurred if the key already existed (`if key:`), I changed this to (`if bucket:`) and now policy enforcement works when creating new objects too
I don't know if I broke anything or if I did something terribly wrong, but all the S3 tests pass
Fixes #7837
=> S3: Fix bucket policy enforcement for s3:PutObject when creating new objects

moto/s3/exceptions.py, moto/s3/responses.py, tests/test_s3/__init__.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_copyobject.py, tests/test_s3/test_s3_list_objects.py
Fixes #7779 
If we call `get_object(.., PartNumber=x)` on a multipart upload, we should probably return only that specific part - but that's not yet implemented.
For now, we only support `PartNumber=1` on an entire key, and treat it as a RangeRequest for the entire key (just like AWS does).
=> S3: head_object()/get_object() now support the PartNumber for regular keys

moto/rds/models.py, moto/rds/responses.py
* Use the `_get_bool_param` helper
* Explicitly guard against None values in the model
* Standardize XML output
=> RDS: Improve handling of boolean attributes

pyproject.toml
The default setting does not use color if it doesn't detect a terminal.
=> Enable pytest colored output in GitHub workflow runs

moto/acmpca/models.py, moto/awslambda/utils.py, moto/cloudformation/parsing.py, moto/moto_proxy/proxy3.py
MyPy 1.11.0 contains some improvements in how partial functions are typed. This PR is mostly adding `type: ignore`-s to make the build work again - doing a deep dive into how to fix the typing properly would require a lot of time.
This also fixes compatibility with `cryptography-43.0.0`, as the CommonName is now a required field when issuing a certificate - and Moto (erroneously) used an empty string as value.
=> Admin: Fix MyPy 1.11.0 compatibility

moto/rds/exceptions.py, tests/test_rds/test_rds_event_subscriptions.py, tests/test_rds/test_rds_export_tasks.py
These exceptions were all using the botocore Shape name instead of the actual AWS error code.
Example for reference:
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteEventSubscription.html
=> RDS: Fix Error Codes

IMPLEMENTATION_COVERAGE.md, docs/docs/services/resourcegroupstaggingapi.rst, docs/docs/services/route53.rst, moto/route53/models.py, moto/route53/responses.py, moto/route53/urls.py, tests/test_route53/test_route53.py
Implements Route53.Client.list_tags_for_resources API
=> Route53 list tags for resources

moto/acm/models.py, moto/acm/responses.py, tests/test_acm/test_acm.py
Closes #7858 
This PR checks the constraints on ExportCertificate as Amazon does, and only allows exporting private certificates.
Additionally, this enables creating private certificates via the RequestCertificate call.
Ideally those certificates would also enter the ISSUED state before they could be exported, but this is a start to begin supporting ACM/PCA interactions correctly.
=> ACM: Enforce ExportCertificate constraints, and issue Private CA certificates via RequestCertificate

AUTHORS.md, moto/core/utils.py, moto/dynamodb/models/__init__.py, moto/dynamodb/models/table_export.py, moto/dynamodb/responses.py, tests/test_dynamodb/test_dynamodb_export_table.py
Implemented 3 dynamodb functions:
- export_table_to_point_in_time
- list_export
- describe_export
=> DynamoDB: table exports

moto/firehose/models.py, tests/test_firehose/test_firehose_put.py
This pull request addresses a bug in AWS Firehose where the S3 prefix for data delivery defaults to /YYYY/MM/dd/HH instead of YYYY/MM/dd/HH when no prefix is provided. According to the [official documentation](https://docs.aws.amazon.com/firehose/latest/dev/s3-prefixes.html), the expected behavior is that the prefix should be YYYY/MM/dd/HH when no custom prefix is specified.
This is a complete test which reproduces the issue.
```python
from moto import mock_aws
import boto3
@mock_aws
def test():
client = boto3.client('firehose', region_name='us-west-1')
s3 = boto3.client('s3')
s3.create_bucket(Bucket='my_bucket')
client.create_delivery_stream(
DeliveryStreamName='test-stream',
DeliveryStreamType='DirectPut',
S3DestinationConfiguration={
'RoleARN': …
```
=> firehose: Fix S3 object path prefix formatting when prefix is empty

docs/docs/configuration/index.rst, moto/core/config.py, moto/iot/models.py, moto/settings.py, tests/test_iot/test_iot_ca_certificates.py
Previous algorithm was based on the PEM format and produced an incorrect certificate ID.
Includes configurable certificate validity for backwards compatibility.
=> IoT: Set Certificate ID to SHA256 hexdigest of DER.

moto/events/models.py, moto/resourcegroups/models.py
With #7716 there were already some changes to support arns with `aws-us-gov` and `aws-cn` (for example) partitions in validation regexes.
However, it seems two were missed, in `events` and `resourcegroups`.
* Use the `ARN_PARTITION_REGEX` to make two validation regex compatible with non-default partitions.
=> Allow non-default partitions in events and resourcegroups regexes

moto/acm/models.py, tests/test_acm/test_acm.py
=> ACM: DomainValidationOptions should have SUCCESS-status

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
The initiate_auth call with a AuthFlow of USERNAME_PASSWORD_AUTH was not accounting for SMS MFA and was returning a AuthenticationResult instead of a Challenge as expected.
-- EDIT --
It also was not accounting for software token MFA and not returning a Challenge as expected.
=> CognitoIDP: initiate_auth with USERNAME_PASSWORD_AUTH and SMS/Software Token MFA

.github/workflows/release.yml, CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/configuration/index.rst, docs/docs/services/bedrock-agent.rst, docs/docs/services/dynamodb.rst, docs/docs/services/ec2.rst, docs/docs/services/neptune.rst, docs/docs/services/networkmanager.rst, docs/docs/services/quicksight.rst, docs/docs/services/sagemaker.rst, moto/sagemaker/models.py, pyproject.toml, tests/test_directconnect/test_directconnect.py, tests/test_sesv2/test_sesv2.py
Fixes release process:
- Commit version number changes before creating a release
- This ensures that the PyPi release has the exact same changes as the commit it references
- Include setup.cfg, as the version nr in that file hadn't been updated in some time
Also adds pytest markers to get rid of the dozens of warnings when running tests.
These markers were already defined in `setup.cfg` - not sure why they weren't picked up before though.
Includes some tiny code/test improvements, but no logic changes.
=> Prep release 5.0.12

moto/cloudwatch/models.py, tests/test_cloudwatch/__init__.py, tests/test_cloudwatch/test_cloudwatch_expressions.py
=> CloudWatch: get_metric_data() now returns everything when querying for Metric Insights Queries

moto/resourcegroupstaggingapi/models.py
Adds ResourceGroupsTaggingAPI support for Sagemaker resource types: compilation-job, domain, model-explainability-job-definition, model-quality-job-definition, and hyper-parameter-tuning-job
=> Feature: Add RGTAPI support for additional Sagemaker resource types

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3_copyobject.py
Fixes #7868 
All modified tests are verified against AWS.
=> S3: copy_object() now respects the CopySourceIfNoneMatch-parameter

moto/cloudformation/responses.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
=> CloudFormation: describe_stacks() now returns export names in the Outputs

moto/acmpca/exceptions.py, moto/acmpca/models.py, moto/acmpca/responses.py, tests/test_acmpca/test_acmpca.py
This PR fixes ACM-PCA so that it generates valid set of certificates. The certificate parameters (x.509 extensions, etc.) now resemble AWS.
- `CreateCertificateAuthority` now obeys certificate subject attributes provided by the client (only country, state, organisation, organisational unit and common name)
- `GetCertificateAuthorityCsr` now produces a CSR with proper CA attributes and extensions
- `IssueCertificate` gains limited support for [certificate templates](https://docs.aws.amazon.com/privateca/latest/userguide/UsingTemplates.html) (only [RootCACertificate/V1](https://docs.aws.amazon.com/privateca/latest/userguide/UsingTemplates.html#RootCACertificate-V1) and [EndEntityCertificate/V1](https://docs.aws.amazon.com/privateca/latest/userguide/UsingTemplates.html#EndEntityCertificate-V1 …
=> ACM-PCA: Fix x.509 certificate generation

moto/elastictranscoder/responses.py, moto/sagemaker/models.py, moto/ssm/models.py
During extensive testing, I found some more errors when accepting / generating ARNs for partitions other than `aws` in moto.
* Accept role ARNs from non-default partitions in elastictranscoder
* Accept cluster ARNs from non-default partitions in sagemaker
* Properly generate the SSM prefix, to strip it correctly in the `get_parameter` operation.
=> Fix issues for non-default partitions in elastictranscoder, sagemaker, and SSM

moto/ec2/exceptions.py, moto/ec2/models/elastic_network_interfaces.py, moto/ec2/models/instances.py, moto/ec2/responses/elastic_network_interfaces.py, tests/test_ec2/test_elastic_network_interfaces.py
Fixes #7896 
The `DeleteOnTermination` attribute is now also returned properly - before it would always come back as False, regardless of what was configured.
=> EC2: Terminating an instance now also terminates any NIC's

moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
Fixes #7915 
Both the (very extensive) new test and the modified test are now verified against AWS.
=> EC2: describe_security_group_rules() should not combine Rules

moto/transfer/models.py
Related issue https://github.com/getmoto/moto/issues/7790 and PR https://github.com/getmoto/moto/pull/7891, in particular comment https://github.com/getmoto/moto/pull/7891#issuecomment-2272715013. Tagging @bblommers and @armichaud.
The `HomeDirectoryMappings` argument for the Transfer client’s `create_user()` function is _not_ marked as required, i.e. it’s optional, and should be typed & handled as such. Docs [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/transfer/client/create_user.html).
Refs: 416e30425cf9acff77adcb64c6466a4155fe1c4b
=> fix: make home_directory_mappings arg for Transfer's create_user() optional

moto/cloudformation/models.py, moto/cloudformation/utils.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
**Summary:**
This PR refactors the `create_change_set` function to improve validation by centralizing it in a new `validate_create_change_set` function. This change ensures all parameters are validated consistently and makes it easier to extend validation in the future.
**Changes:**
- **Added `validate_create_change_set` Function**:
- Centralizes validation for all parameters, currently including `change_set_name` rules (e.g., must start with a letter, be alphanumeric, and under 128 characters).
- **Updated `create_change_set`**:
- Calls `validate_create_change_set` to validate inputs before processing.
**Testing:**
- Updated unit tests to cover validation scenarios.
[Documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation/client/create_chan …
=> CloudFormation: create_change_set ChangeSetName more rules

moto/core/base_backend.py, tests/test_core/test_backenddict.py
This PR adds a utility method to iterate over a flattened view of a `BackendDict`.
Each record is a tuple of account ID, region, and the corresponding `BaseBackend`.
=> Utility to iterate over flattened backends

moto/batch/models.py, moto/batch/responses.py, moto/batch_simple/models.py, tests/test_batch/__init__.py, tests/test_batch/test_batch_jobs.py
This PR adds support for using parameters in job commands. It also implements the ability to overwrite parameters during the submit job operation.
=> Batch: add support for parameters in Job commands

moto/apigateway/responses.py, moto/apigateway/urls.py, moto/apigatewayv2/responses.py, moto/apigatewayv2/urls.py, tests/test_apigateway/test_apigateway.py, tests/test_apigatewayv2/test_apigatewayv2.py
Fixes https://github.com/getmoto/moto/issues/7974
AWS returns a 200 empty response when doing a `get_api` with an empty string in `apigatewayv2`. Same behaviour is seen with `get_rest_api` in `apigateway`. `boto` is returning a 404 `not yet implemented` error. This PR tries to mock that use case.
```
import boto3
import json
client = boto3.session.Session(profile_name="dev", region_name="us-east-1").client("apigateway")
resp = client.get_rest_api(restApiId="")
print(json.dumps(resp, default=str))
client = boto3.session.Session(profile_name="dev", region_name="us-east-1").client("apigatewayv2")
resp = client.get_api(ApiId="")
print(json.dumps(resp, default=str))
```
Both returns:
```
{
"ResponseMetadata": {
"RequestId": "e156a293-3eff-4b81-be31-6712e05c843f",
"HTTPStatusCode": 200, …
```
=> feat: Deal with APIGateway GetAPI with an empty string

moto/emr/models.py, moto/emr/utils.py, moto/events/models.py, moto/secretsmanager/models.py, moto/utilities/utils.py, tests/test_events/test_events.py
Related to #7698 - behaviour is now verified against AWS. Secret is now also deleted automatically when deleting a connection.
=> Events: create_connection() now creates a Secret with the right value

.github/workflows/build.yml, .github/workflows/tests_decoratormode.yml, moto/ses/models.py, setup.cfg
The SES changes are due to a logic bug that only manifests in Python3.13.
When no CC/BCC fields are set, the `fieldvalues` would be set to something like: `['to@example.com, foo@example.com', '', '']`
Sending that to the builtin `emails.utils.getaddresses`-method in Python 3.12 results in:
`[('', 'to@example.com'), ('', 'foo@example.com'), ('', '')]`
But in Python 3.13, this results in an empty list.
This PR ensures that there are no empty strings in `fieldvalues`, which in turns means that the `getaddresses`-method keeps working.
=> Admin: Support Py 3.13

moto/dynamodb/models/__init__.py, moto/dynamodb/responses.py, tests/test_dynamodb/test_dynamodb.py, tests/test_dynamodb/test_dynamodb_update_expressions.py
Hi, this is intended to fix an issue with dynamodb where an emtpy update expression given to `update_item` raises an unexpected exception: https://github.com/getmoto/moto/issues/7988
=> DynamoDB: empty update expression now returns a ValidationException

moto/rds/models.py, tests/test_rds/test_rds.py
Previous code broke if you tried to create more than one PIT restore due to a KeyError on 'db_subnet_group' when trying to delete the key.  This just checks for existence before deleting the key
Added a test to the existing `test_restore_db_instance_to_point_in_time()`.  Don't know if it's wanted or if I should ass it to a separate function
=> RDS Fix bug that causes second PIT restore to fail

moto/cognitoidp/models.py, moto/ec2/models/instance_types.py, moto/utilities/utils.py, setup.py
Fixes #7909 
Registers a new custom Command when running `python -m build` that finds all JSON files and compresses them.
This only happens during `bdist` creation, so the source distribution is left intact.
@bpandola How do you feel about this approach?
=> Admin: Compress JSON in binary distributions

IMPLEMENTATION_COVERAGE.md, docs/docs/services/s3.rst, moto/s3/models.py, moto/s3/responses.py, tests/test_core/test_responses.py, tests/test_s3/test_server.py
No logical changes - this just untangles the massive `_key_response_get`-method in S3Response.
The end-goal here is to get rid of the `if ".." in querystring..` spaghetti altogether, and let our regular `dispatch` method handle the dispatching, but there are several steps that need to be handled first:
1. untangle POST/PUT/DELETE requests
2. ensure dispatch() can handle querystrings
3. ensure dispatch() knows and can handle the difference between virtual-host and path-style URL's
4. change `s3/urls.py` to use `dispatch`
5. and then we can remove all `if ".." in querystring` sections
=> Techdebt: S3: Untangle GET-methods

moto/ec2/models/elastic_block_store.py, moto/ec2/responses/elastic_block_store.py, tests/test_ec2/test_elastic_block_store.py
=> EC2: describe_snapshots() now supports the kms-key-id filter

moto/s3/exceptions.py, moto/s3/responses.py, tests/test_awslambda/test_lambda.py, tests/test_cloudformation/test_cloudformation_stack_integration.py, tests/test_cloudwatch/test_cloudwatch_boto3.py, tests/test_firehose/test_firehose_put.py, tests/test_logs/test_integration.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_acl.py, tests/test_s3/test_s3_copyobject.py, tests/test_s3/test_s3_lifecycle.py, tests/test_s3/test_s3_logging.py, tests/test_s3/test_s3_storageclass.py, tests/test_sagemaker/test_sagemaker_pipeline.py
Fixes #7774
The provided LocationConstraint must be equal to the region that the request was send to, same as with AWS.
Note that this may catch a lot of people out if region names are not explicitly specified, and it is taken from either a previous (cached) boto3-client, a configuration setting or from a environment variable.
For example, if `~/.aws/config` states that `region = us-east-1`, the following now (correctly) fails:
```
s3_conn = boto3.client("s3")
s3_conn.create_bucket(Bucket=bucket_name, "CreateBucketConfiguration": {"LocationConstraint": "us-west-2"})
```
Moto was (until now) quite forgiving and simply assumed that you really meant to send this request to `us-west-2`, but will now throw a `InvalidLocationConstraint`-exception.
=> S3: create_bucket() now has additional LocationConstraint-validation

moto/autoscaling/models.py, moto/ec2/models/launch_templates.py, tests/test_autoscaling/test_autoscaling_groups.py
=> Autoscaling: LaunchTemplate tags are now propagated to EC2 instances

moto/wafv2/models.py
Currently, the service name in the wafv2 backend dict is "waf-regional". This mismatch leads to errors when trying to load the service based on the service name in the backend dict (as in LocalStack persistence).
It would be nice to match the service name to the actual service, so this mismatch is prevented.
The `waf-regional` name is for waf classic, not wafv2: https://docs.aws.amazon.com/waf/latest/developerguide/classic-waf-chapter.html
* Change wafv2 backend service name from `waf-regional` to `wafv2`
=> Match wafv2 backend service name to service

moto/sagemaker/models.py, tests/test_sagemaker/test_sagemaker_search.py
=> SageMaker: search() now supports the CONTAINS filter

moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
=> DynamoDB: update_item() now validates empty string sets

.github/workflows/tests_real_aws.yml, moto/logs/models.py, moto/logs/responses.py, moto/s3/exceptions.py, moto/s3/models.py, moto/s3/responses.py, tests/test_logs/test_export_tasks.py, tests/test_s3/__init__.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_bucket_policy.py, tests/test_s3/test_s3_list_object_versions.py, tests/test_s3/test_s3_lock.py, tests/test_sns/test_application_boto3.py
Changes the AWS parity tests to run with `loadscope == file`, meaning all tests in a file still run syncronously
Implements `Logs: cancel_export_task()`
S3: Adds support for LockMode=GOVERNANCE
S3: Adds validation that a bucket is versioned before calling `put_object_lock_configuration`
S3: Adds validation to the parameters of `put_object_lock_configuration`
S3: delete_objects() now returns the `DeleteMarkerVersionId`-attribute
SNS: Removes `aws_ verified` ready for SNS test, as it started failing
Followup to #8024 
Should fix the AWS parity tests.
=> S3: Improve Lock behaviour

tests/test_route53/test_route53.py
CI is throwing a warning about an invalid string escape (`"\ "`) ([recent example](https://github.com/getmoto/moto/actions/runs/10570098846/job/29284013829#step:7:849)).
This PR addresses the `DeprecationWarning` by updating the test string to `"\\ "`.
=> Resolve a `DeprecationWarning` due to an invalid string escape

moto/batch/models.py, tests/test_batch/test_batch_jobs.py
As this [document](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters) shows. The parameters are defined in a command like `Ref::parameter` and not `$parameter`. This was a small error introduced in my last PR.
=> Batch: fix job parameters definition

moto/s3/models.py, moto/s3/responses.py
=> Techdebt: Untangle S3 DELETE-methods

moto/s3/responses.py, tests/test_s3/test_s3.py
Follow-up from #8007: it seems the PR was a bit too strict.
AWS S3 allows you to create buckets in other regions if your client region is set in `us-east-1` (and only from that region, as its behavior is already quite specific). 
Due to this, the bucket can also have a region different from the client region.
=> S3: fix CreateBucket from us-east-1 in other regions, and set bucket region to LocationConstraint

moto/acm/responses.py, moto/elb/models.py, moto/elbv2/models.py, tests/test_acm/test_acm.py
This PR is similar to https://github.com/getmoto/moto/pull/4414, implementing the same use case for ELBV2.
In a nutshell, it updates the `InUseBy` property of an ACM certificate when attaching it to an ELBV2 listener.
I also fixed the `ListCertificate` operation that should return a boolean `InUse` property, which gets computed from the `InUseBy` attached to the certificate description.
=> ACM InUseBy with elbv2

moto/events/responses.py, tests/test_events/test_events.py
This PR adds the missing 'Name' parameter to EventBridge [ListConnections](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_ListConnections.html#API_ListConnections_ResponseSyntax) operation.
This patch is from the LocalStack fork.
=> EventBridge: Add Name param to ListConnections response

.github/dependabot.yml
Avoid the multiple PR spam by grouping all Java and DotNet dependency updates into a single PR.
=> Group Dependabot Updates for Java/DotNet

moto/core/responses.py, moto/iam/access_control.py, tests/test_awslambda/test_lambda_invoke.py
Supercedes #8063
When determining whether the current request is allowed, we need the action that is invoked - e.g. S3:ListBucket, Lambda:Invoke.
Before it would only look at the `X-Amz-Target`-header and at the `Action=`-parameter (typically found in request bodies).
However, for a lot of other services, we need to query `botocore` to determine the action based on the request-url and method. Luckily, the `_get_action`-method combines all methods (`X-Amz-Target`, `Action=`, `botocore`), so we can just use that.
=> Core: Support auth calls for AWSLambda

moto/ec2/models/security_groups.py, tests/test_ec2/test_security_groups.py
When using the `describe-security-group-rules` call with a security-group-id `filter`, it correctly returns the egress and ingress rules. However, if we try to use the `describe-security-group-rules` call and specify the `--security-group-rule-ids`, it does not return the rule as expected. 
This PR will now consider both egress and ingress rules while using `--security-group-rule-ids` param in the command. 
Fixes: https://github.com/localstack/localstack/issues/11445
=> ec2: fix security groups describe rule response

.github/workflows/tests_terraform_examples.yml, docs/conf.py, moto/autoscaling/models.py, other_langs/terraform/autoscaling/data.tf, other_langs/terraform/autoscaling/main.tf, other_langs/terraform/autoscaling/provider.tf, other_langs/terraform/autoscaling/security_groups.tf, other_langs/terraform/autoscaling/variables.tf, tests/test_autoscaling/test_autoscaling.py, update_version_from_git.py
Howdy,
When creating an AutoScaling Group the  `CreatedTime` should be in ISO format. At the moment the returned value is causing a deserialization error.
```
│ Error: reading Auto Scaling Group (sandwich): operation error Auto Scaling: DescribeAutoScalingGroups, https response error StatusCode: 200, RequestID: ucKD1cbqn2lqSIvuMlxcMYuaWEyT6kImWKuyBdbUHE7Gr4YZ0VdO, deserialization failed, failed to decode response body, unable to parse time string, parse errors:
│  * "2006-01-02T15:04:05.999999999Z": parsing time "2024-09-06 02:13:02.824378" as "2006-01-02T15:04:05.999999999Z": cannot parse " 02:13:02.824378" as "T"
│  * "2006-01-02T15:04:05.999999999": parsing time "2024-09-06 02:13:02.824378" as "2006-01-02T15:04:05.999999999": cannot parse " 02:13:02.824378" as "T"
│  * …
```
=> Austoscaling: Ensure CreateDate is in isoformat

moto/elbv2/models.py, tests/test_elbv2/test_elbv2_cloudformation.py
Context:
Recently our tests started failing with a next error:
```
pattern = '^arn:(aws|aws-cn|aws-iso|aws-iso-b|aws-us-gov):iam:'
string = [{'CertificateArn': 'arn:aws:acm:us-east-1:123456789012:certificate/<cert_id>', 'certificate_arn': 'arn:aws:acm:us-east-1:123456789012:certificate/<cert_id>'}]
flags = 0
def search(pattern, string, flags=0):
"""Scan through string looking for a match to the pattern, returning
a Match object, or None if no match was found."""
>       return _compile(pattern, flags).search(string)
E       TypeError: expected string or bytes-like object, got 'list'
```
I tracked down an issue to this change - https://github.com/getmoto/moto/pull/8054
In my understanding in case of listener creation from cloudformation `certificate` variable is not a string, but an array …
=> ELBv2: Fix CF bug when passing certificates to ELB listener creation

tests/test_elbv2/test_elbv2_target_health.py
Should fix the build again, that started failing with botocore 1.35.15.
=> ELBv2: Workaround botocore bug for Delete-LB waiter

moto/iam/models.py, moto/iam/responses.py, other_langs/terraform/iam/data.tf, other_langs/terraform/iam/iam.tf, other_langs/terraform/iam/output.tf, other_langs/terraform/iam/providers.tf, other_langs/terraform/iam/sample-metadata.xml, tests/test_iam/test_iam.py
G'day,
When passing an XML document the characters in the XML are causing the response value to return with a different value.
```
Error: reading IAM SAML Provider (arn:aws:iam::123456789012:saml-provider/sso-test): operation error IAM: GetSAMLProvider, https response error StatusCode: 200, RequestID: aZ44KsVPnA1fs9yDDYUHUddNxQrOiUyu8scM4elFE6CUdtCNCI1O, deserialization failed, failed to decode response body, expected value for SAMLMetadataDocument element, got xml.StartElement type {{urn:oasis:names:tc:SAML:2.0:metadata EntityDescriptor} [{{ xmlns} urn:oasis:names:tc:SAML:2.0:metadata} {{xmlns saml} urn:oasis:names:tc:SAML:2.0:assertion} {{xmlns ds} http://www.w3.org/2000/09/xmldsig#} {{ entityID} urn:amazon:webservices} {{ validUntil} 2025-08-30T00:00:00Z}]} instead
```
[Sample …
=> IAM: Escape SAML metadata XML document when creating a SAML provider

moto/apigateway/models.py, moto/apigateway/responses.py, moto/apigateway/urls.py, tests/test_apigateway/test_apigateway.py
- Implement get_account and update_account for apigateway
- Added rootResourceId to the RestAPI class and its to_dict function so that it will be returned as it was missing ([create_rest_api](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway/client/create_rest_api.html), [get_rest_api](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway/client/get_rest_api.html))
=> Apigateway Account APIs

IMPLEMENTATION_COVERAGE.md, docs/docs/services/memorydb.rst, moto/backend_index.py, moto/backends.py, moto/memorydb/__init__.py, moto/memorydb/exceptions.py, moto/memorydb/models.py, moto/memorydb/responses.py, moto/memorydb/urls.py, moto/moto_server/werkzeug_app.py, tests/test_memorydb/test_memorydb.py
This is the initial moto implementation of AWS MemoryDB API.
=> feat: Implementation of  memorydb api

moto/firehose/models.py, moto/firehose/responses.py, tests/test_firehose/test_firehose_destination_types.py
So far we cannot use moto to test Firehose Service with the Snowflake destination
Example:
```python
@pytest.fixture(autouse=True, scope="class")
def firehose_client_inst(self):
with mock_aws():
firehose_client = boto3.client("firehose", region_name="eu-west-1")
for firehose_stream_name in FIREHOSE_STREAM_NAMES:
firehose_client.create_delivery_stream(
DeliveryStreamName=firehose_stream_name,
SnowflakeDestinationConfiguration={
"RoleARN": f"arn:aws:iam::{DEFAULT_ACCOUNT_ID}:role/firehose_delivery_role",
"AccountUrl": "fake-account.eu-west-1.snowflakecomputing.com",
"Database": "myDatabase",
"Schema": "mySchema",
"Table": "myTable",
"S3BackupMode": "FailedDataOnly",
"S3Configuration": {
"RoleARN": f"arn:aws:iam::{DEFAULT_ACCOUNT_ID}:role/firehose_delivery_role",
"BucketARN": …
```
=> Firehose: Add Snowflake Destination

moto/ec2/models/availability_zones_and_regions.py, tests/test_ec2/test_availability_zones_and_regions.py
Related to #8087 
Zones are now automatically created for every region that `botocore` returns - making it future proof for new regions added in the future.
Some explicit zone mappings were kept for backwards compatibility.
=> EC2: Ensure all regions have availability zones

tests/test_events/test_events_integration.py
The test suite validates that an SQS FIFO queue with content-deduplication disabled does not receive messages from EventBridge, but doesn't catch and verify the `UserWarning` that gets raised in the code because of this ([recent example in CI](https://github.com/getmoto/moto/actions/runs/10570098846/job/29284013829#step:7:865)). As a result, that `UserWarning` gets reported by pytest at the end of the test run.
This PR uses `pytest.warns()` to catch and verify the expected `UserWarning`.
=> Catch and verify an expected `UserWarning` in the test suite

moto/networkmanager/models.py, moto/networkmanager/responses.py, tests/test_networkmanager/test_networkmanager.py
For NetworkManager: Update resource states to 'AVAILABLE' from 'PENDING' after create response to more accurately represent the mocked resource
=> NetworkManager: Update resource states to 'AVAILABLE' from 'PENDING' after create response

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
The `resourcegroupstaggingapi` is lacking support for VPC subnets
This PR adds VPC subnets to the output of `get_resources`
=> Add output of VPC subnet tagging to `resourcegroupstaggingapi`

moto/route53/responses.py, tests/test_route53/test_route53.py
Fixes two bugs.
1. When list_tags_for_resource is passed only a single ID, the request is a string and not a list
2. The regex for deriving resource_type was always None
=> [BUG Fix] route53 - list_tags_for_resources: Resolve when a single ID is provided

moto/ec2/models/tags.py
Although EC2 API does not provide a method to update existing tags, [CreateTags](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) will overwrite existing tag keys with the new given value. Therefore, existing tags passed as argument to `create_tags()` method should not be taken into consideration to validate `TagLimitExceeded` exception when the resource underneath exists.
It has been tested in AWS that, updating one or more tag values of a resource which tag count is already on the limit (50), works well using AWS CLI, boto3 and Terraform.
=> [BUG FIX] EC2: Exclude existing tags to be overwritten from the TagLimitExceeded validation

moto/fsx/models.py, tests/test_fsx/test_fsx.py
This change intends to address https://github.com/getmoto/moto/issues/8148
Modifies how fsx fs id is generated so that:
* there are not collisions for requests that happen in parallel
* it complies with the expected regex.
=> [FSx] Update file system id generation to expected regex

moto/ec2/models/elastic_block_store.py, moto/ec2/responses/elastic_block_store.py, tests/test_ec2/test_elastic_block_store.py
Adds support for the API endpoint **ModifyEbsDefaultKmsKeyId**
Ref:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyEbsDefaultKmsKeyId.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/modify-ebs-default-kms-key-id.html
=> ECS - modify-ebs-default-kms-keyid support

moto/resourcegroupstaggingapi/models.py
https://github.com/getmoto/moto/pull/8142 introduced the output for EC2 VPC subnets in the resourcestaggingapi service. 
Further requests from users have shown that there are quite a lot more missing which can easily be added.
This PR adds the missing resources from users and unifies the EC2 resource handling to be more easily readable (inspired by how, e.g., RDS is handled in the same file)
=> Unify EC2 resource tags and add new ones

docs/docs/services/sns.rst, moto/sns/models.py, moto/sns/responses.py, tests/test_sns/test_publish_batch.py, tests/test_sns/test_publishing_boto3.py
Hi! I implemented the parameter `MessageStructure` for SNS's publish and publish_batch methods.
I added unit tests. I tested those changes in the integration tests of my project, which work similarly to the AWS implementation (in my case).
I hope, my changes will be useful to others.
I will be happy to adapt my PR to Moto project standards if needed.
=> SNS: Support MessageStructure=json for publish and publish_batch

moto/batch/models.py, tests/test_batch/test_utils.py
https://github.com/getmoto/moto/pull/7973 introduced support for parameters in job commands.
However, the `_add_parameters_to_command` function had a bug that resulted in duplicated arguments, when the number of arguments was greater than one.
This was due to the nested list comprehension logic adopted.
For instance, the  given the following job parameters `{'dossier_md5': 'abc', 'event_id': 'E12340060311'}` and the following command `['--dossier_md5', 'Ref::dossier_md5', '--event_id', 'Ref::event_id']` we were given the following output:
```
['--dossier_md5', '--dossier_md5', 'abc', 'Ref::dossier_md5', '--event_id', '--event_id', 'Ref::event_id', 'E12340060311']
```
This PR adjusts the logic accordingly and adds a simple unit test to verify the fix.
=> batch: fix bug in add_parameters_to_command

moto/ecs/models.py, tests/test_ecs/test_ecs_cloudformation.py
Very similar to: https://github.com/getmoto/moto/pull/7280
But for cases when register task definition is being called via cloudformation.
=> Fix Cloudformation ECS task definition memory validation

.github/workflows/tests_terraform_examples.yml, moto/ec2/models/network_acls.py, moto/ec2/responses/network_acls.py, tests/test_ec2/test_network_acls.py
With this parameter now returning correctly, `terraform` no longer feels the need to recreate NetworkACL entries every time.
And because of that, we can run the same test steps (apply / plan / delete) for all terraform tests, including EC2.
=> EC2: create_network_acl_entry() now supports the Ipv6CidrBlock-parameter

moto/scheduler/exceptions.py, moto/scheduler/models.py, tests/test_scheduler/test_scheduler.py
There is a missing validation on the `start_date` parameter in `create_schedule` action if the `schedule_expression` is recurrence and `start_date` is today's date, so there might be a `ValidationException` with the message: _**The StartDate you specify cannot be earlier than 5 minutes ago.**_
=> Scheduler: start_date parameter validation (create_schedule)

moto/scheduler/exceptions.py, moto/scheduler/models.py, tests/test_scheduler/__init__.py, tests/test_scheduler/test_scheduler.py
[#8172](https://github.com/getmoto/moto/pull/8172) covered only a use case I was working with. Still, I got suspicious about a few behavior nuances and delved a bit into it, then discovered that it is not only the current today date that throws that exception but any other date before it. The mentioned PR's code raises an exception for `start_date` with today's date but higher properties such as hours, minutes, etc (even though I was able to test all of these properties in  localhost, in GH actions for Python it fails for others times smaller properties as minutes, microseconds, etc. _probably due to -j flag for parallel jobs_). This new PR is more robust and covers other cases slipping on the previous one.
=> Scheduler: generalized start_date parameter validation (create_schedule)

moto/shield/exceptions.py, moto/shield/models.py, tests/test_shield/test_shield.py
Resolves: #8180 & added test to validate
Code should be "ResourceNotFound"
Message should be "The subscription does not exist."
Reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/shield/client/describe_subscription.html
=> Update Shield exception for no subscription on describe_subscriptions

moto/dynamodb/models/__init__.py, moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Fixes #8192 
The new test has been run on AWS
=> DynamoDB: return item on condition check failure in delete_item (#8192)

moto/sagemaker/models.py, tests/test_sagemaker/test_sagemaker_search.py
Fixes #8155 
We now use the existing `get_response_object()` for each resource, so we now automatically return all attributes (instead of only the hardcoded ones).
=> SageMaker: search() now also supports ModelPackages/Pipelines/Jobs/Executions

moto/core/responses.py
Found an issue on how the URIs send by the boto3 client converted into function names.
I have 2 URI:
1. `/accounts/{AwsAccountId}/namespaces/{Namespace}/groups`
2. `/accounts/{AwsAccountId}/namespaces/{Namespace}/users/{UserName}/groups`
These URIs were converted into these regular expressions:
1. `/accounts/(?P<AwsAccountId>.*)/namespaces/(?P<Namespace>.*)/groups`
2. `/accounts/(?P<AwsAccountId>.*)/namespaces/(?P<Namespace>.*)/users/(?P<UserName>.*)/groups`
Unfortunately both request URIs match regular expression 1:
1. `/accounts/1235/namespaces/default/groups`
2. `/accounts/123456789012/namespaces/default/users/authoremail%40example.com/groups`
Investigating on how AWS defines the requestUri in the service.json files I found that there are 2 types of parameters.
1. e.g. quicksight: …
=> Fix BaseResponse.uri_to_regexp

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
=> Step Function - Add support for State Machine to resourcegrouptaggingapi

moto/apigateway/models.py, tests/test_apigateway/test_apigateway.py
Following #8202, the behavior was not fully compliant with AWS, as even if not documented at all by AWS, the `nameQuery` parameter also accepts prefixes. This was validated on AWS for both `GetApiKeys` and `GetUsagePlanKeys`.
=> APIGateway: fix strict filtering for API keys

.github/workflows/build.yml, .github/workflows/tests_decoratormode.yml, .github/workflows/tests_sdk_js.yml, .gitignore, moto/ec2/responses/instances.py, moto/rds/models.py, other_langs/tests_js/ec2.test.js, other_langs/tests_js/package.json, other_langs/tests_js/rds.test.js, other_langs/tests_js/s3.test.js
=> RDS: DBInstances: Ensure compatibility with NodeJS SDK

setup.py
Make `.json.gz` files deterministic to fix reproducible builds.
See https://reproducible-builds.org/ for why this is good.
=> Make .json.gz files deterministic

moto/secretsmanager/models.py, tests/test_secretsmanager/test_secretsmanager.py
AWS supports force deletion of already deleted secrets, but this is blocked in moto.
This PR enables this, including a test.
* Allow force-deletion of secrets already marked for deletion
=> SecretsManager - Allow force deletion of already marked-for-delete secret

.github/workflows/build.yml, .github/workflows/release_dev.yml
Triggering a dev release for every PR has resulted in a incredibly large number of dev releases on PyPi - so many in fact that we've been running out of space. There is a 10 GB max, and at least 95% consists of dev releases that are multiple releases behind (i.e., never used).
This PR disables the automatic dev release, and instead switches it to a workflow dispatch. So if necessary, a maintainer can still easily create a dev release if a user requests it.
=> Admin: Disable automatic dev releases, allow manual triggering instead

moto/apigateway/models.py, moto/apigateway/utils.py, moto/secretsmanager/models.py, moto/secretsmanager/utils.py, moto/utilities/id_generator.py, tests/conftest.py, tests/test_apigateway/test_apigateway_custom_ids.py, tests/test_secretsmanager/test_secretsmanager.py, tests/test_utilities/test_id_generator.py
This pr aims to introduce a mechanism by which we can define custom ids in order to be able to create a resource with deterministic ids.
A `ResourceIdentifier` base class will allow us to quickly create objects to manage ids. Each resource can implement their own `generate` method giving us much flexibility when it comes to the type of id created.
The `MotoIdManager` implements an interface over the registered custom ids. It also contains a method `add_id_source` that will allow us the possibility to further expand the behaviour of the id manager.
- Implementation of the id manager
- Integration of the `ResourceIdentifier` in `apigateway` and `secretsmanager` as to provide examples of how it can be used.
- Added tests for implemented services.
Many services can benefit from this upgrade, …
=> Support custom ids

moto/ec2/models/iam_instance_profile.py, moto/ec2/responses/vpcs.py, moto/packages/boto/ec2/instance.py, moto/s3/models.py
With it's latest release, `mypy` has improved it's capabilities to [Inferring Unions for Conditional Expressions](https://github.com/python/mypy/blob/master/CHANGELOG.md#inferring-unions-for-conditional-expressions). This created a new issues with `mypy` and [tests failing](https://github.com/getmoto/moto/actions/runs/11337740019) at the linting step.
- Added type annotation to prevent inference at declaration (`var = None`) conflict with inference in conditional expression (`var = "string" if cond() else None`) resulting in `expression has type "Union[Any, str]", variable has type "None"` error.
=> Core: fixed typing for conditional expression

moto/iam/models.py, moto/iam/responses.py, tests/test_iam/test_iam.py
Currently, moto does not urlencode (or quote) IAM policy strings in its return values.
While this seemingly matches the AWS behavior, as described here: https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetRolePolicy.html , more investigation shows AWS actually quoting the IAM policies, as shown in responses (printed by boto3 in debug mode):
```
<GetUserPolicyResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">\n  <GetUserPolicyResult>\n    <PolicyDocument>%7B%22Version%22%3A%20%222012-10-17%22%2C%20%22Statement%22%3A%20%5B%7B%22Effect%22%3A%20%22Allow%22%2C%20%22Action%22%3A%20%5B%22apigatway%3APUT%22%5D%2C%20%22Resource%22%3A%20%5B%22arn%3Aaws%3Aapigateway%3Aeu-central-1%3A%3A%2Ftags%2Farn%253Aaws%253Aapigateway%253Aeu-central-1%253A%253A%252Frestapis%252Faaeeieije%22%5D%7D% …
```
=> IAM: Urlencode IAM policies in responses to match AWS

moto/elbv2/models.py, tests/test_elbv2/test_elbv2.py, tests/test_elbv2/test_elbv2_listener_rule_tags.py, tests/test_elbv2/test_elbv2_listener_tags.py, tests/test_elbv2/test_elbv2_target_groups.py
This pr aims to add parity with `remove_tags` API of `elbv2` that throws exception in certain scenarios. Currently, no exceptions were being thrown from `remove_tags`.
Include logic to throw exceptions similar to `add_tags` by using the method `_get_resource_by_arn` that can check for various NotFound scenarios.
Added test cases for loadbalancer, listener, listener rule and target group to reflect the new behavior. 
It doesn't currently cover the singular nature of the API. Even though the parameter `ResourceArns` expects a list but only one ARN can be passed. This use case is not covered yet.
=> ELBv2: remove_tags() now throws a ResourceNotFound Exception

moto/apigateway/models.py, moto/secretsmanager/models.py, moto/utilities/id_generator.py, tests/test_apigateway/test_apigateway_custom_ids.py, tests/test_secretsmanager/test_secretsmanager.py, tests/test_utilities/test_id_generator.py
As a follow up to #8216, This pr aims at expanding support of custom ids to resources that can be created with tags. Providing a tag named `_custom_ids` at creation can be used to create a custom id for the created resource.
- Fixed `get_id_from_tags` method to by able to accept tags created as dict (e.g `{"_custom_id_": "myCustomId"}`) or as a list (e.g. `[ {"Key": "_custom_id_", "Value": "myCustomId"} ]`)
- Added tests for apigw and secrets manager to showcase an example of each type
=> Custom id tag support

moto/pinpoint/models.py, tests/test_pinpoint/test_pinpoint.py
This PR fixes the hardcoded region in Pinpoint Application resource.
This region is now correctly picked up from the request context.
=> Pinpoint: Fix region in application ARN

moto/cloudformation/responses.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Adds missing support for using the UsePreviousTemplate param with UsePreviousValue in the parameter list with calling the cloudformation create_change_set method.
Adds unit tests.
Code clean-up.
=> Adds support for UsePreviousTemplate to create_change_set

.github/workflows/tests_terraform_examples.yml, IMPLEMENTATION_COVERAGE.md, docs/docs/services/rds.rst, moto/rds/models.py, moto/rds/responses.py, other_langs/terraform/rds/providers.tf, other_langs/terraform/rds/proxy.tf, tests/test_rds/test_rds_proxy.py, tests/test_rds/test_rds_proxy_target_groups.py
=> RDS: Proxy Target Groups

moto/cognitoidp/models.py, moto/cognitoidp/responses.py, other_langs/tests_java/pom.xml, other_langs/tests_java/src/main/java/moto/tests/DependencyFactory.java, other_langs/tests_java/src/test/java/moto/tests/CognitoIDPTest.java, tests/test_cognitoidp/test_server.py
=> CognitoIDP: Ensure MFA functions work with non-python SDK's

CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/services/quicksight.rst, docs/docs/services/redshift.rst, docs/docs/services/transfer.rst, moto/backend_index.py, moto/meteringmarketplace/urls.py, moto/moto_api/_internal/urls.py, moto/sagemakermetrics/urls.py, moto/sns/models.py, moto/timestreamquery/urls.py, tests/test_iam/test_iam_signing_certificates.py, tests/test_secretsmanager/test_secretsmanager.py, tests/test_stepfunctions/parser/test_stepfunctions.py
Includes:
- A bunch of regex fixes, where we want to match on the dot-character (`\.`) instead of any characters
- Some test fixes, like a missing region
- Explicit deletion of a KMS key in an AWS parity test, to avoid having to delete resources manually from our AWS account
- Fix a StepFunction test as we were using a unsupported value in `create_state_machine(encryption_config.type)`, and AWS apparently only added validation for that field recently
- Improve the key size for some RSA keys, as the GitHub vulnarability scanner complains about key sizes < 2048
=> Prep release 5.0.18

moto/ec2/models/key_pairs.py, moto/ec2/utils.py, tests/test_ec2/test_key_pairs.py, tests/test_ec2/test_utils.py
Resolves [localstack issue](https://github.com/localstack/localstack/issues/9337)
@viren-nadkarni is recommended to make changes in `moto` in [this](https://github.com/localstack/localstack/pull/11567#pullrequestreview-2324592555) comment
=> Add SHA1 and SHA256 algorithms for EC2 fingerprint calculation

setup.cfg
Reverts #8248 
Should work again now that botocore 1.35.46 is out (see https://github.com/boto/botocore/issues/3284)
=> Update `botocore` version specifiers

moto/organizations/exceptions.py, moto/organizations/models.py, tests/test_organizations/test_organizations_boto3.py
This PR unlocks cross-account support for AWS Organizations.
After creating an organization and adding a member account to it, it is now possible to retrieve the details of the parent organization using `DescribeOrganization` from the member account.
Plus:
- Calling `CloseAccount` on an already closed account raises
- Calling `RemoveAccountFromOrganization` on an account which does not belong to any raises
A similar pattern was employed for S3 in https://github.com/getmoto/moto/pull/6333
=> Organizations: Allow cross-account access

moto/instance_metadata/responses.py
Werkzeug 3.1.x has changed the `EnvironHeaders`-class, and the `update`-method no longer accepts another `EnvironHeaders`-class as an argument.
This PR changes the `InstanceMetadata`-class to return the headers as a dictionary. That is a more standardized way to handle headers, and also ensures that `EnvironHeaders.update(headers_as_dict)` works.
=> InstanceMetadata: Fix compatibility with werkzeug 3.1.x

CLOUDFORMATION_COVERAGE.md, moto/cloudformation/parsing.py, moto/iot/models.py, tests/test_iot/test_iot_cloudformation.py
I'd like to contribute CloudFormation models for AWS IoT Core service.
Initial models for:
* AWS::IoT::Thing
* AWS::IoT::ThingType
* AWS::IoT::Policy
=> CloudFormation models for some IoT objects

CLOUDFORMATION_COVERAGE.md, IMPLEMENTATION_COVERAGE.md, moto/iot/models.py, moto/iot/responses.py, tests/test_iot/test_iot_cloudformation.py, tests/test_iot/test_iot_rolealias.py, tests/test_iot/test_iot_search.py
In this PR I'd like to contribute:
* IoT RoleAlias API: `create_role_alias()`, `list_role_aliases()`, `describe_role_alias()`, `update_role_alias()`, `delete_role_alias()`
* `AWS::IoT::RoleAlias` CloudFormation object
Enhance search() index response - add missing `thingGroupNames` and `shadow` fields
=> IOT RoleAlias support - API and CloudFormation object, enhancements to search_index() response

moto/ecr/models.py, moto/ecr/responses.py, tests/test_ecr/test_ecr_boto3.py
Fixes #8269 
The `list_images()`-method returns a `dict(imageDigest=..., imageTag=...)`, which means that we images may be listed multiple times if they have multiple tags.
The original implementation ([added 7 years ago!](https://github.com/getmoto/moto/pull/961)) didn't account for that, and would only return every image with it's latest tag and ignore other tags.
=> ECR: list_images() should list images with multiple tags separately

setup.cfg
Universal wheels were a great way to indicate that a project supported both Python 2 _and_ 3.. but it's probably time to get rid of that.
That should also get rid of a deprecation warning when building the project:
```
2024-11-08T19:59:54.2032474Z /tmp/.../setuptools/_distutils/cmd.py:111: SetuptoolsDeprecationWarning: bdist_wheel.universal is deprecated
2024-11-08T19:59:54.2034257Z !!
2024-11-08T19:59:54.2034534Z 
2024-11-08T19:59:54.2037019Z         ********************************************************************************
2024-11-08T19:59:54.2038500Z         With Python 2.7 end-of-life, support for building universal wheels
2024-11-08T19:59:54.2039705Z         (i.e., wheels that support both Python 2 and Python 3)
2024-11-08T19:59:54.2040740Z         is being obviated. …
```
=> Admin: Remove univeral wheel option

moto/dynamodb/exceptions.py, moto/dynamodb/parsing/ast_nodes.py, moto/dynamodb/responses.py, moto/dynamodb/utils.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Hi, this is a proposed fix for issue #8297 
In case of duplicate paths in PorjectionExpression AWS raises an error below. Moto - does not.
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the Query operation: Invalid ProjectionExpression: Two document paths overlap with each other; must remove or rewrite one of these paths; path one: [body], path two: [body]
Appreciate your feedback a lot!
=> DynamoDB: Validate duplicate path in projection expression

moto/stepfunctions/parser/api.py, tests/test_ec2/test_security_groups.py, tests/test_iot/test_iot_integration.py, tests/test_iot/test_iot_search.py, tests/test_stepfunctions/parser/test_stepfunctions.py, tests/test_stepfunctions/parser/test_stepfunctions_dynamodb_integration.py
- EC2 security group changes were a result of AWS returning additional attributes that we don't yet support
- StepFunction changes were a result of AWS changing the error details
- The IOT test was moved to an `_integration.py`-file as it integrates with `iotdata`, because our ServiceDependencies workflow expects every tests that integrates a different service to be in a dedicated file.
=> Admin: Fix various tests to keep parity with AWS

moto/dynamodb/models/__init__.py, moto/dynamodb/models/dynamo_type.py, moto/dynamodb/models/table.py, moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/test_dynamodb_scan.py
=> DynamoDB: scan() now supports parallelization using the Segment/TotalSegments parameters

IMPLEMENTATION_COVERAGE.md, moto/iot/models.py, moto/iot/responses.py, tests/test_iot/test_iot_indexing_configuration.py
I'd like to contribute two IoT calls with a very simple implementation: `get_indexing_configuration()` and `update_indexing_configuration()`
=> IoT: Add get_indexing_configuration(), update_indexing_configuration()

moto/s3/responses.py, tests/test_s3/test_s3_storageclass.py
=> S3: get_object_attributes() now also works for Glacier objects

moto/ec2/responses/fleets.py, tests/test_ec2/test_fleets.py
=> EC2: create_fleet() now correctly handles Overrides with a single value

CLOUDFORMATION_COVERAGE.md, IMPLEMENTATION_COVERAGE.md, moto/iot/exceptions.py, moto/iot/models.py, moto/iot/responses.py, moto/iot/utils.py, tests/test_iot/test_iot_cloudformation.py, tests/test_iot/test_iot_job_templates.py, tests/test_iot/test_iot_jobs.py
Hello
In this PR I'd like to enhance IoT Job object and JobTemplate
=> Improve IoT Job and JobTemplate

.github/workflows/release.yml, CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/services/bedrock-agent.rst, docs/docs/services/cloudtrail.rst, docs/docs/services/iam.rst, docs/docs/services/iot.rst, docs/docs/services/lakeformation.rst, docs/docs/services/opensearch.rst, docs/docs/services/quicksight.rst, docs/docs/services/sts.rst, moto/iot/models.py, moto/iot/responses.py
Fixes our release process to always update the `latest` docker tag, in addition to making a separate `<version>` tag
=> Prep release 5.0.21

docs/docs/releases.rst
Hello folks!
I have spent some time in trying to figure out that when using Moto with OpenTofu and I was able to find only an entry in the 5.0.0-alpha3 release note. I think we should list that change as a breaking change so possible other folks hitting that can hopefully find it more easily!
Thanks!
---
Since Moto 5.0.0 for performance reasons the AWS IAM managed policies are no longer automatically loaded anymore by default.
This can break usages relying on AWS IAM managed policies.
Document how to preserve the pre-5.0.0 behavior.
=> Docs: managed policies are not loaded by default

docs/docs/services/lambda.rst, moto/awslambda/models.py
A small typo I encountered when going through the source code.
=> Fix typo in Lambda docstring

moto/secretsmanager/models.py, moto/secretsmanager/responses.py, tests/test_secretsmanager/test_list_secrets.py
Original Issue: https://github.com/localstack/localstack/issues/11635
Description:
This PR addresses an issue where deleted secrets were still being displayed in the list-secrets API response.
Changes:
Modified list-secrets API: The list-secrets API has been modified to filter out deleted secrets by default.
Updated Unit Tests: Unit tests have been updated to verify the correct behavior of the list-secrets API.
=> SecretsManager: Improve list-secrets to exclude deleted secrets

moto/ec2/utils.py, tests/test_moto_api/seeder/test_seeder.py
Since July 2018, AWS uses longer 17 character resource IDs for EC2.
See:
- https://www.amazonaws.cn/en/ec2/faqs/
- https://aws.amazon.com/about-aws/whats-new/2018/02/longer-format-resource-ids-are-now-available-in-amazon-ec2/
- https://aws.amazon.com/blogs/compute/longer-resource-ids-in-2018-for-amazon-ec2-amazon-ebs-and-amazon-vpc/
=> EC2: Generate longer resource IDs

moto/iotdata/models.py, tests/test_iotdata/test_iotdata.py
Fixes #8331 
If there are other scenarios that I've missed, and the diff computation becomes even more complex, it might make sense to move away from `jsondiff` altogether, and add our own implementation. The whole point of `jsondiff` is to not have to deal with complexity like this. But for now, this will do.
=> IOTData: update_thing_shadow() now properly handles complex nested deltas

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py
Add support for the Secrets Manager for the get_resources function of the resourcegroupstaggingapi.
=> ResourceGroupsTaggingAPI: Add support for Secrets Manager for get_resources

moto/s3/responses.py
HeadObject is not part of S3 actions for use in IAM permission policies.
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html
The reference for HeadObject states that the required permission is GetObject
> General purpose bucket permissions - To use HEAD, you must have the s3:GetObject permission. 
https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html
Indeed, `s3:HeadObject` is not a valid action for a bucket policy (screenshot from AWS Bucket Policy Editor).
=> Fix required permission for HeadObject, which requires GetObject

moto/elbv2/exceptions.py, moto/elbv2/models.py, tests/test_elbv2/test_elbv2_target_health.py
=> ELBv2: register_targets() now validates that instances are running

moto/memorydb/models.py, tests/test_memorydb/test_memorydb.py
Added Tagging functionality to Memorydb Snapshots and subnets.
=> MemoryDB: adding tagging functionality to snapshots and subnets

moto/athena/models.py, moto/athena/responses.py, tests/test_athena/test_athena.py
Added filtering ability to list_query_execution() using the `WorkGroup` param to better align the function to the documentation.
Changed the types for workgroup in `start_query_execution` as they did not reflect what was being passed in during the tests.
=> Athena: list_query_execution() not filtering by workgroup name

moto/kms/responses.py, tests/test_kms/test_kms_boto3.py
Fixes #8364 
The error provided was coming from the function `_validate_cmk_id()` which obviously raises an error when used with an alias, and if I understood correctly especially since `describe_key()` is using ` any_id_to_key_id()`.
Tests are passing and none seem to be broken.
=> fix(kms): get_public_key now works with alias (name and arn)

moto/rds/models.py, tests/test_rds/test_rds.py
Previously, this failed with
`TypeError: cannot pickle 'generator' object`
when the code tried to deepcopy the `backend`. But the backend is not needed, anyway, so just skip it when deepcopying.
=> Allow RDS restore_db_instance_from_db_snapshot() to custom db_subnet_group

moto/awslambda/models.py, tests/test_awslambda/__init__.py, tests/test_awslambda/test_lambda.py
Fixes #8337 
Partially reverts #5734 
The docs for `publish_function` state:
> Lambda publishes a new function version only if the code has never been published, or if the code has changed from the last published version. If there is no change, the function version remains at the last published version.
The actual behaviour is that Lambda publishes a new function version only if [..] the `update_function_code` or `update_function_configuration` functions have been called.
If you call the 'update'-function, AWS does not check whether the provided code is different - they just assume it is different, and will publish a new version.
The new tests for this behaviour are verified against AWS.
=> AWSLambda: Publish when update_fn has been called

moto/ds/models.py, tests/test_ds/test_ds.py
Fixes bug where no directory_id is provided, type error.
Per docs: _"If no input parameters are provided, such as DirectoryId or TrustIds, this request describes all the trust relationships belonging to the account."_
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ds/client/describe_trusts.html
=> ds: Fix describe_trusts with no directory_id provided

moto/efs/models.py, moto/efs/responses.py, moto/efs/urls.py, tests/test_efs/test_filesystem_policy.py
Adds support for file system policies for EFS.
[efs.PutFileSystemPolicy](https://docs.aws.amazon.com/efs/latest/ug/API_PutFileSystemPolicy.html)
[efs.DescribeFileSystemPolicy](https://docs.aws.amazon.com/efs/latest/ug/API_DescribeFileSystemPolicy.html)
=> efs - add file system policy support

setup.cfg
The current min. cryptography version (`3.3.1`) isn't sufficient for moto's IoT submodule - versions of cryptography between `3.3.1` and `3.4.8` (inclusive) didn't support importing from `cryptography.hazmat._oid`:
```
.pyenv/versions/3.11.6/lib/python3.11/site-packages/moto/iot/models.py:9: in <module>
from cryptography.hazmat._oid import NameOID
E   ImportError: cannot import name 'NameOID' from 'cryptography.hazmat._oid' (/home/vlas-sokolov/.pyenv/versions/3.11.6/lib/python3.11/site-packages/cryptography/hazmat/_oid.py)
```
This can be easily verified by installing any cryptography version prior to `35.0.0` and running moto's test suit from `tests/test_iot` - they will all fail. The import structure moto relies on was introduced in this …
=> bump cryptography version from 3.3.1 to 35.0.0

moto/s3/responses.py, tests/test_s3/test_s3_multipart.py
Followup to  #8109 where it was introduced for `put_object()`
=> S3: complete_multipart_upload() now supports IfNoneMatch-parameter

moto/rds/models.py, moto/rds/responses.py, tests/test_rds/test_rds.py, tests/test_rds/test_rds_clusters.py
Hi everyone,
this is my first pull request in this repo, so if something is missing or unclear, let me know.
As requested in this issue https://github.com/getmoto/moto/issues/8294, this MR adds the implementation of the Managed Master Password handling for db_instance and db_cluster resources. This contains the following actions:
- Enabling/Disabling Managed Master User Password has an impact on the db_instance or db_cluster resource response and contains mocked data
- Providing a custom kms key with `MasterUserSecretKmsKeyId`will be respected in moto's response
- Setting `RotateMasterUserPassword` in a `modify_db_instance` or `modify_db_cluster`-call will set the status of the Master User Secret to `rotating`.
To keep things simple, I do not actually create a secret in moto's mocked …
=> RDS: Implement Managed Master Password Handling

moto/rds/models.py
Original code was popping the `backend` attribute off of the existing cluster instance.
=> RDS: Fix config copy

moto/es/models.py, moto/es/responses.py, moto/es/urls.py, moto/opensearch/models.py, moto/opensearch/responses.py, moto/opensearch/urls.py, tests/test_es/test_es.py, tests/test_opensearch/test_opensearch.py
Adds support for [describe_elasticsearch_domains](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/es/client/describe_elasticsearch_domains.html) for  ES.
Adds support for [describe_domains](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/opensearch/client/describe_domains.html) for opensearch.
Also changed ElasticSearch service_name from "elasticsearch" to "es". I had the ["unknown service" issue like this prior example](https://github.com/getmoto/moto/pull/6969#discussion_r1376735532). Didn't seem to break anything existing
=> es & opensearch - add describe_elasticsearch_domains & describe_domains support

moto/dynamodb/models/__init__.py, tests/test_dynamodb/test_dynamodb_update_table.py
This was previously impossible due to the conditional that required the argument `deletion_protection_enabled` to be truthy for any update to be applied.
=> DynamoDB: Make it possible to disable delete protection on a table

moto/cognitoidp/models.py, moto/cognitoidp/responses.py, tests/test_cognitoidp/test_cognitoidp.py
Fixes #8363
* move `filt` to the backend list_users logic so that the paginator decorator can pick up the right filter users
* Also added the test case for this specific issue
=> CognitoIDP: Fix Limit and Filter params for list_users()

moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
As stated in the [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_security_group.html) the methods for creating and describing a Security Group resource should include the attribute SecurityGroupArn.
- ARN generation in the SecurityGroup model
- Addition of the attribute in the response templates.
- Extension of an existing test to assert the presence of the attribute
=> EC2: add SecurityGroupArn to security groups

moto/ec2/models/route_tables.py, tests/test_ec2/test_route_tables.py
Updated EC2 update_route to correctly use the decided destination type instead of `destination_cidr_block`.
Also added additional test cases to verify this logic.
This references issue #8394 .
=> EC2: update_route() now correctly handles DestinationPrefixListId

moto/ec2/models/elastic_network_interfaces.py, tests/test_ec2/test_elastic_network_interfaces.py
Hello! Issue #7896 was not completely fixed, the test code in the bug report did not run completely through. The fixed IP address of the deleted instance was still kept in an internal field of the Subnet, so that another instance with the same IP address could not get created.
I tried fixing this, and added a test. All EC2 tests pass, except two that seem unrelated and also fail for me on current master (one in test_availability_zones_and_regions.py and one in test_security_groups.py).
Thanks!
=> EC2: Remove internal Network Interface traces from the Subnet after deletion

CHANGELOG.md, tests/test_core/test_responses_module.py
=> Core: Use internal server to test requests passthrough

moto/backend_index.py, moto/backends.py, moto/dsql/__init__.py, moto/dsql/exceptions.py, moto/dsql/models.py, moto/dsql/responses.py, moto/dsql/urls.py, moto/moto_api/__init__.py, moto/moto_server/werkzeug_app.py, tests/test_dsql/test_dsql.py
This PR is part of #8413 
add DSQL `create_cluster()` implementation.
=> DSQL: implement create_cluster()

.github/workflows/tests_terraform_examples.yml
Currently, ubuntu-latest is specified as the Runner in Git Hub Actions, but ubuntu-latest will soon be changed to point to ubuntu-24.04.
The ubuntu-24.04 Runner does not have a built-in Terraform command, so terraform tests will suddenly fail one day.
- https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/
- https://github.com/actions/runner-images/issues/10636
I used a forked repository to perform the following tests.
- I explicitly specified ubuntu-24.04 at the `runs-on` and confirmed that the test failed.
- https://github.com/cm-iwata/moto/actions/runs/12453251643/job/34763159915
- I then added a step to setup Terraform and confirmed that the test was successful.
- https://github.com/cm-iwata/moto/actions/runs/12453304689/job/34763283277
=> chore: Fixed workflow to prevent terraform tests from failing

moto/iotdata/models.py, setup.cfg, tests/test_iotdata/test_iotdata.py
Fixes #8408 
Computing the delta using `jsondiff` was introduced in the very beginning: https://github.com/getmoto/moto/pull/1303, and further 'improved' with #7814 and #8342
Trying to mangle `jsondiff` into making it behave the way we wanted introduced more problems then it solved though, so this PR simplifies the implementation to compute the delta manually (which turns out to be fairly straightforward).
=> IOTData: Simplify delta calculation

setup.cfg
Just a minuscule addition to package metadata, which is shown in places like the PyPI project page (https://pypi.org/project/moto/) or in the output of some tools, such as `poetry show`.
=> Add short project description in package metadata

moto/dsql/exceptions.py, moto/dsql/models.py, moto/dsql/responses.py, moto/dsql/urls.py, tests/test_dsql/test_dsql.py
This PR is part of https://github.com/getmoto/moto/issues/8413
add DSQL get_cluster() implementation.
=> DSQL: implement get_cluster()

moto/ds/models.py
The Settings list of dictionaries is a shadow copy, resulting in unexpected results when there are 2+ directories with changed settings.
A deep copy resolves this issue.
=> [Bug Fix] Directory Service - change settings init to deep copy

moto/s3/models.py, moto/s3/responses.py, moto/s3/select_object_content.py, setup.cfg, tests/test_s3/test_s3_select.py
=> S3: select_object_content() now returns the proper Stats

.github/workflows/tests_real_aws.yml, tests/test_stepfunctions/parser/__init__.py
The tests against AWS tend to fail for two reason:
- The SFN executions take too long, causing the test to timeout
- The overall tests take too long, causing the IAM credentials to timeout
This should fix both.
=> Admin: Increase SFN test duration

moto/rds/models.py, tests/test_rds/test_rds.py
Follow up to #8374 that fixes a new `deepcopy` call from #8373 in `modify_db_instance` and another one in `restore_db_instance_to_point_in_time`. Previously, this failed with
`TypeError: cannot pickle 'generator' object`
=> RDS: Allow more db-instance operations in custom subnets

moto/stepfunctions/responses.py
Ruff complains about the formatting of a `type: ignore` all of a sudden.
I've tried upgrading ruff, which would improve the formatting - but the new formatting is not compatible with Python 3.8. So we can't do that yet.
=> Admin: Ruff formatting

moto/dynamodb/parsing/key_condition_expression.py, tests/test_dynamodb/test_dynamodb_query.py
=> DynamoDB: KeyConditionExpression can have additional parentheses

moto/ec2/models/security_groups.py, tests/test_ec2/test_security_groups.py
https://github.com/getmoto/moto/pull/8393 introduced the SecurityGroupArn field to supported operations, however the format of the ARN was incorrect. The correct format is:
```
arn:${Partition}:ec2:${Region}:${Account}:security-group/${SecurityGroupId}
```
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html#amazonec2-resources-for-iam-policies
cc: @pinzon
=> EC2: Fix SecurityGroup ARN

moto/rds/models.py, tests/test_rds/test_rds_clusters.py
Fix hardcoded cluster id in error message, which I found while refactoring the test cases.
Happy new year!
=> RDS: Fix hardcoded cluster id in error message

moto/kinesis/models.py, moto/kinesis/responses.py, tests/test_kinesis/test_kinesis_resource_policy.py
Fixes https://github.com/getmoto/moto/issues/8465
=> Kinesis resource based policy implementation

moto/stepfunctions/models.py, moto/stepfunctions/parser/models.py, moto/stepfunctions/responses.py, tests/test_stepfunctions/test_stepfunctions_versions.py
=> StepFunctions: Support Version Descriptions

moto/secretsmanager/list_secrets/filters.py, tests/test_secretsmanager/test_list_secrets.py
Fixes #8421 
[The documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager/client/list_secrets.html) states that when filtering by e.g. name or description, the search happens by `Prefix match`.
When filtering by `all` (that is, name *and* description *and* tags), search approach is:
> Breaks the filter value string into words and then searches all attributes for matches.
Until now Moto would split values by spaces (`my test` -> [`my`, `test`]), but AWS uses upper case letters to recognize words (`MyTest` -> [`My`, `Test`]).
Testing this feature showed that filtering by `description` would also break it into words - it is not a prefix match, as the docs state.
Also introduces proper case insensitivity for the `description` and `all` filters. …
=> SecretsManager: list_secrets() now properly splits words when filtering

IMPLEMENTATION_COVERAGE.md, moto/kms/exceptions.py, moto/kms/models.py, moto/kms/responses.py, moto/kms/utils.py, tests/test_kms/test_kms_key_rotation.py, tests/test_kms/test_kms_mac.py
Implemented New Methods for KMS:
- `generate_mac`
- `rotate_key_on_demand`
- `list_key_rotations`
- `verify_mac`
Added these already implemented methods as dummies to the Backend so they show up in the coverage:
- `list_key_policies`
- `generate_random`
(When I ran `scripts/implementation_coverage.py` it also updated a bunch of other rst-files (>50) with new methods, I'm not sure if I should commit those as well, as most are unrelated to KMS)
=> Feat: Add KMS methods for Key Rotations and MACs

moto/rds/exceptions.py, moto/rds/models.py, tests/test_rds/test_rds.py
When creating a new RDS instance, check if an instance with the same instance identifier already exists and raise an error in that case, just like real AWS does.
=> RDS: Check if new instance ID already exists

moto/scheduler/exceptions.py, moto/scheduler/models.py, tests/test_scheduler/test_schedule_groups.py, tests/test_scheduler/test_scheduler.py
Service: Event Bridge Scheduler
During extending our test coverage (in this PR: https://github.com/localstack/localstack/pull/12114) we noticed, that there is a slight discrepancy between AWS responses and MOTO responses.
This PR introduces the fixes for the response status code, as well as the response message for scheduler groups.
In addition, it also adds tests in moto for these new changes.
=> Scheduler: Fix Exception code/format and default timezone

moto/ses/models.py, moto/ses/responses.py, moto/sesv2/models.py, moto/sesv2/responses.py, moto/sesv2/urls.py, tests/test_ses/test_ses_boto3.py, tests/test_sesv2/test_sesv2.py
Adds support for Configuration Sets & Dedicated IP Pools for SESv2. (#8472 )
- Shared backend with SES
- Updated SES Configuration Set implementation
**SESv2 Additions**
- CreateConfigurationSet
- GetConfigurationSet
- ListConfigurationSets
- DeleteConfigurationSet
- CreateDedicatedIpPool
- GetDedicatedIpPool
- ListDedicatedIpPools
- DeleteDedicatedIpPool
=> Support for SESV2 - Configuration Sets & Dedicated IP Pools

tests/test_rds/test_filters.py, tests/test_rds/test_rds_clusters.py, tests/test_rds/test_rds_clusters_with_instances.py, tests/test_rds/test_rds_event_subscriptions.py, tests/test_rds/test_rds_export_tasks.py
Slightly simplifying the test case for RDS, continuation of #8461.
=> RDS: refactoring .get() calls in test cases

moto/rds/models.py, tests/test_rds/test_rds.py, tests/test_rds/test_rds_clusters.py
Make it possible to call `copy_db_cluster_snapshot()` even when the original cluster was already deleted. A similar bug was fixed in #7392, but for normal RDS instances. This also fixes it for RDS clusters.
While implementing the new code, I wondered what happens when a snapshot with `SnapshotType=="automated"` gets copied. Does the copy have the same property (because it was copied) or does it have `SnapshotType=="manual"` because the snapshot was manually created? Turns out the latter is true, and this is correctly implemented by moto. But there weren't any test cases for this, so the second commit adds them.
=> RDS: Allow copy_db_cluster_snapshot() for deleted cluster

moto/acm/models.py
The Terraform AWS provider added validation for this particular detail in either 5.83.0 or 5.83.1 - this should fix the build again.
FYI @bpandola
=> ACM: Resource Record name is slightly different for wildcard SAN's

docs/docs/services/glue.rst, moto/glue/models.py, moto/glue/responses.py, tests/test_glue/test_glue.py
Issue: https://github.com/getmoto/moto/issues/8488#issue-2785343083
New Boto Methods Added
- get_dev_endpoints()
- create_dev_endpoint()
- get_dev_endpoints()
=> Glue: get_dev_endpoints, create_dev_endpoint, get_dev_endpoint

moto/moto_api/_internal/recorder/models.py, moto/moto_proxy/proxy3.py, moto/s3/responses.py, tests/test_s3/__init__.py, tests/test_s3/test_s3.py, tests/test_s3/test_s3_copyobject.py, tests/test_s3/test_s3_lock.py, tests/test_s3/test_s3_object_attributes.py
The latest version of `botocore` adds some customizations to the S3 client that break some of our S3 tests:
* S3 client behavior is updated to always calculate a CRC32 checksum by default for operations that support it (such as PutObject or UploadPart), or require it (such as DeleteObjects). 
* Botocore will no longer automatically compute and populate the Content-MD5 header.
This PR removes assertions around the default checksum behavior (as it now varies across `botocore` versions).  It also manually supplies the `ContentMD5` parameter for API calls that require it, as `botocore` no longer automatically computes it.
This PR also contains minor `request.body` processing tweaks for S3 as well as during `proxy` or `recording` mode, due to the new `aws-chunked` encoding and the …
=> Ensure compatibility with latest `botocore` S3 client customizations

moto/core/responses_custom_registry.py, tests/test_core/test_request_mocking.py
=> Core: Allow replace/remove of mocked responses

moto/secretsmanager/models.py, tests/test_awslambda/__init__.py, tests/test_secretsmanager/__init__.py, tests/test_secretsmanager/test_secretsmanager.py
Fixes #8403 
When calling `rotate_secret()`, a `AWSPENDING` stage should exist, but it should not have a value. This can be verified by calling `get_secret_value()` during the rotation, at the `createSecret` step - it will throw an error.
The existing test that verifies the rotation works has been changed to reflect this:
- During rotation, the current state is stored in a DynamoDB table
- After the test finishes, we assert that we do indeed get a `ResourceNotFoundException` when calling `get_secret_value()`
- (A lot more state is available, but we currently do not have any assertions to verify that they are correct)
- The test has been modified to pass against AWS (having correct permissions, deleting everything afterwards, etc)
=> SecretsManager: rotate_secret() should create AWSPending without a value

tests/test_utilities/test_id_generator.py
Pytest will attempt to collect test cases from any class whose name starts with "test", so we have to explicitly mark this class as not a test.
=> Resolve `pytest` warning

pyproject.toml
This warning is needlessly filling up the CI logs and is safe to ignore.
=> Silence `utcnow` deprecation warnings from `botocore`

moto/secretsmanager/list_secrets/filters.py, tests/test_secretsmanager/test_list_secrets.py
Followup to #8469, words are now also split by special characters (`/`, `+`, and a few others).
Fixes #8421 
Whether this is the final form of this algorithm, I don't know - it's quite possible that I've missed some use cases. It is currently closer to AWS parity than before though, with the (AWS-validated) tests to prove it.
=> SecretsManager: list_secrets() now filters values with special chars correctly

moto/organizations/models.py, tests/test_organizations/test_organizations_boto3.py
Default account is linked to the organization, whereas other accounts within the organization do not have this reference. This PR fixes this issue.
Once an organization is created and a member account is added, the member account can now retrieve the details of the root account by using the `ListRoots` API.
Plus, if a member account is not part of any organization, the `AWSOrganizationsNotInUseException` exception will be raised, as described in the [AWS documentation](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListRoots.html).
This PR re-uses approach introduced in the #8260
=> Organizations: return organization roots for requests made by other accounts within the organization

tests/test_s3/test_s3.py
No existing moto S3 tests utilize the `download_file` method of the boto3 S3 client.  
This has come up recently in #8498 and #8527, so this PR ensures that our tests explicitly cover this client call.
=> Add test for `download_file` method of boto3 S3 client

moto/athena/models.py, moto/config/exceptions.py, moto/config/models.py, moto/databrew/models.py, moto/ec2/exceptions.py, moto/logs/models.py, moto/route53resolver/models.py, moto/sagemaker/models.py, moto/secretsmanager/models.py, moto/sqs/exceptions.py, tests/test_ds/test_ds_simple_ad_directory.py, tests/test_dynamodb/test_dynamodb.py, tests/test_s3/test_s3.py, tests/test_ses/test_ses_boto3.py
I accidentally formatted the code with ruff version 0.9.4 and it produced some code simplifications that ruff 0.3.3 does not object to.
=> Make code ruffer

moto/s3/responses.py, tests/test_s3/test_s3.py
Fixes https://github.com/getmoto/moto/issues/8534
=> S3: Return ETag in 304 responses from get_object

moto/dynamodb/models/__init__.py, tests/test_dynamodb/test_dynamodb_transact.py
Fixes https://github.com/getmoto/moto/issues/8516
Tested locally and in AWS via `MOTO_TEST_ALLOW_AWS_REQUEST` flag
=> DynamoDB: Support ReturnValuesOnConditionCheckFailure for all op types in transact_write_items

.github/workflows/build.yml, .github/workflows/tests_cdk.yml, moto/cloudformation/responses.py
This PR just adds an additional CI step to validate that we can bootstrap the CDK.
=> Core: Support CDK

moto/rds/exceptions.py, moto/rds/models.py, moto/rds/responses.py, moto/rds/serialize.py, moto/rds/utils.py, moto/rds/viewmodels.py
This PR adds a response serializer for the AWS Query protocol to the RDS backend, eliminating the need for manually editing XML Jinja templates.  The serializer uses the model information already present in the `botocore` data files to output formatted, type-aware XML responses based on the `moto` RDS model classes.
This changeset attempts to be as clean as possible, with most file changes containing only additions or deletions.  The exception to this is `responses.py`, where each controller method was migrated from a template-based string response to a serialized response, resulting in a large but still understandable diff.
Eliminating 1500+ lines of Jinja template strings and `to_xml()` model methods is a big maintenance win.  Future updates to RDS need only add new attributes to the …
=> [RDS] Replace XML Jinja Templates with proper XML Response Serializer

moto/ec2/models/elastic_block_store.py, tests/test_ec2/test_elastic_block_store.py
Related to https://github.com/localstack/localstack/issues/11522
=> EC2: Require size/snapshot when creating EBS volume

moto/elbv2/exceptions.py, moto/elbv2/models.py, other_langs/terraform/elb/load_balancer.tf, tests/test_elbv2/test_elbv2.py
When creating a listener, port and protocol should satisfy some conditions base on the load balancer type.
https://docs.aws.amazon.com/cli/latest/reference/elbv2/create-listener.html#options
=> ELB: Port and protocol validations for create listener

moto/ec2/responses/_base_response.py, moto/utilities/utils.py, tests/test_ec2/test_amis.py, tests/test_ec2/test_availability_zones_and_regions.py, tests/test_ec2/test_subnets.py
When a filter is provided that doesn't have `Values` or has an empty list as `Values` moto raises TypeError 
```
% aws ec2 describe-subnets --filters Name=vpc-id
{
"Subnets": []
}
```
```
% aws ec2 describe-subnets --filters Name=vpc-id --endpoint-url http://127.0.0.1:5000
Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'<!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```
from logs:
```
File "moto/moto/ec2/responses/_base_response.py", line 20, in <dictcomp>
return {f["Name"]: f["Value"] for f in _filters} …
```
=> EC2: Handle filtering without Values

moto/ses/exceptions.py, moto/ses/models.py, tests/test_ses/test_ses_boto3.py
[CreateReceiptRule](https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateReceiptRule.html) and [CreateReceiptRuleSet](https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateReceiptRuleSet.html) should raise `AlreadyExists` error according to the docs.
Also, updating messages for `RuleDoesNotExist` and `RuleSetDoesNotExist` to match what AWS returns.
=> SES: Fix AlreadyExists and DoesNotExist error messages

.devcontainer/devcontainer.json
Adds a Launch Configuration to run Moto Server Tests
Features:
- A single click to start up MotoServer and MotoServer Tests
- A prompt for an optional "pytest -k" filter to filter for specific test
- Runs on the GitHub Codespaces "Public Port"
=> [codespaces] Launch Configurations

moto/ecs/models.py, tests/test_ecs/test_ecs_boto3.py
Resolves https://github.com/getmoto/moto/issues/8319
=> ECS: tasks include containers objects

moto/kms/models.py, moto/kms/responses.py, tests/test_kms/test_kms_boto3.py
This is a change to allow the 'Origin' parameter in create_key to affect the origin of the mocked key.
=> Allow non kms origin in create_key

moto/awslambda/models.py
=> Lambda: Pick Lambda image deterministically

moto/ec2/exceptions.py, moto/ec2/models/instances.py, moto/ec2/responses/instances.py, tests/test_ec2/test_instances.py
Hi moto team 👋🏼 
I'm opening this PR to tacke these two issues:
- The EC2 parameter`DisableApiStop` is not propagated when running an instance, instead uses default (`DisableApiStop=False`).
This leads to inconsistencies when trying to create ec2 instances with localstack with terraform & pulumi, due to these changes not being stored in the instance so these IAC detect changes and modify the instance when running corresponding iac scripts.
- On the other side, took advantage to throw the corresponding exception when trying to stop an ec2 instance that was created with  `DisableApiStop=True` as that was not handled.
=> EC2: Properly handle disableApiStop in instance lifecycle

IMPLEMENTATION_COVERAGE.md, docs/docs/services/logs.rst, moto/logs/exceptions.py, moto/logs/models.py, moto/logs/responses.py, tests/test_logs/test_logs.py
Adding the following methods for Logs
- create_delivery
- delete_delivery
- delete_delivery_destination
- delete_delivery_destination_policy
- delete_delivery_source
- describe_deliveries
- describe_delivery_destinations
- describe_delivery_sources
- get_delivery
- get_delivery_destination
- get_delivery_destination_policy
- get_delivery_source
- put_delivery_destination
- put_delivery_destination_policy
- put_delivery_source
=> Logs: Add new methods

.github/workflows/build.yml, .github/workflows/tests_sdk_cpp.yml, other_langs/tests_cpp/CMakeLists.txt, other_langs/tests_cpp/Makefile, other_langs/tests_cpp/hello_s3.cpp
Some very simple tests using C++, just to verify that the MotoServer works against this SDK. I've included a cache for the actual build output as well. Downloading all build tools + building the project takes 5 minutes, so including a cache should avoid some unnecessary compute time.
The need to have this was raised in #8592, a bug report that only occurred when using C++ SDK.
This PR only includes smoke tests - it does not create the exact conditions described in #8592, and therefore does not test this scenario.
Documentation used:
- https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/sdk-from-pm.html
- https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/cpp_s3_code_examples.html
Outstanding tasks:
- Rework this to use proper unit tests (for example by using …
=> Admin: Add CPP tests

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/tests_decoratormode.yml, .github/workflows/tests_sdk_dotnet.yml, .github/workflows/tests_sdk_java.yml, .github/workflows/tests_sdk_ruby.yml, .github/workflows/tests_servermode.yml, .github/workflows/tests_terraform_examples.yml, moto/core/base_backend.py, moto/core/exceptions.py, moto/core/versions.py, moto/s3/utils.py, moto/utilities/collections.py, moto/utilities/utils.py, setup.cfg, tests/test_s3/test_s3.py
Now that we no longer support for 3.8 we can also simplify a bunch of types - i.e. `List[str]` can become `list[str]`, same for Set->set, etc.
That is a bigger change though, so I'll tackle that later.
=> Admin: Drop support for Python 3.8

moto/glue/models.py, moto/glue/responses.py, tests/test_glue/test_glue.py
- [CreateConnection](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/create_connection.html)
- [GetConnection](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/get_connection.html)
- [GetConnections](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue/client/get_connections.html)
- Only display Public Address if a subnet is provided.
-- The PublicAddress field is present only when you create a non-virtual private cloud (VPC) DevEndpoint." per Boto3 docs
=> [Glue] Added Connections Support

moto/rds/models.py, moto/rds/serialize.py
Fixes #8627 
FYI @bpandola - a little refactoring to get rid of this dependency. I replaced `TypeAlias` completely because it is a) only introduced in 3.10, and b) [was deprecated again in 3.12](https://docs.python.org/3/library/typing.html#typing.TypeAlias). It seems to run fine without it, so I think it's OK? Happy to be corrected though, typing is not my strong suit. :)
=> Admin: Remove typing_extensions module

moto/core/serialize.py, tests/test_core/protocols/output/ec2.json, tests/test_core/protocols/output/json.json, tests/test_core/protocols/output/query.json, tests/test_core/protocols/output/rest-json.json, tests/test_core/protocols/output/rest-xml.json, tests/test_core/test_protocols.py, tests/test_core/test_serialize.py
These serializers translate any backend result into a properly formatted HTTP response according to the [AWS protocol specifications](https://smithy.io/2.0/aws/protocols/index.html) and the `botocore` model data for a particular service/operation.
This PR contains a battery of low-level protocol tests to ensure adherence to the specifications.  Some future tweaks may be required for integration with individual AWS services.
Benefits:
* No need for Jinja XML templates in response classes.
* No need for `.to_dict()` methods on backend objects.
* No need for manually string formatting date values or coercing boolean values.
Next Steps:
These serializers will be slowly integrated into each individual service backend, starting with the services that will benefit the most (e.g. Query …
=> Add AWS Protocol Serializers

moto/rds/models.py, tests/test_rds/test_rds.py, tests/test_rds/test_rds_clusters.py
Pulled from #8634 to separate unrelated changes (RDS and TimestreamWrite).
=> RDS: Add `DBCluster.AutoMinorVersionUpgrade` attribute

tests/test_cognitoidp/test_cognitoidp.py
This works better if the tests are being run on an installed wheel, where `jwks-public.json` has been compressed; and it matches how this test already handles `jwks-private.json`.
=> test_cognitoidp: Load jwks-public.json using load_resource

moto/wafv2/responses.py, moto/wafv2/utils.py, tests/test_wafv2/test_server.py, tests/test_wafv2/test_utils.py, tests/test_wafv2/test_wafv2.py, tests/test_wafv2/test_wafv2_rules.py
Reported in https://github.com/localstack/localstack/issues/12272.
ARN for WAF resources in Cloudfront scope should specify `us-east-1` region. Currently region is being set to `global` in moto.
I checked in AWS console that it stands true for all WAF resources: Web ACLs, IP sets, Regex pattern sets, Rule groups.
The regression was likely introduced in #7710.
Region for global scope backend [defaults](https://github.com/getmoto/moto/blob/d00aa025b6c3d37977508b5d5e81ecad4ca15159/moto/core/base_backend.py#L272) to `"aws"`. It needs to be overridden with `us-east-1` for ARN purposes as Cloudfront-related resources are [managed from](https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateIPSet.html#WAF-CreateIPSet-request-Scope) `us-east-1` and have it specified in ARN. However backend …
=> WAFv2: fix incorrect ARNs in Cloudfront scope

moto/core/exceptions.py, moto/core/responses.py, moto/core/serialize.py, moto/rds/exceptions.py, moto/rds/models.py, moto/rds/responses.py, tests/test_core/test_exceptions.py, tests/test_core/test_protocols.py, tests/test_core/test_serialize.py
This PR adds the following base classes to facilitate integration of our new AWS protocol response serializers:
`ActionResult` - a thin wrapper over any object, dict, etc. returned from a `responses.py` method
`ServiceException` - a base class mapping `moto` service exceptions to `botocore` error models
Additionally, this PR adds code hooks in `BaseResponse` to pass instances of these classes directly to the appropriate response serializer.  Because any `ActionResult` returned or any raised exception derived from `ServiceException` will trigger the new serialization flow, we can gradually remove serialization concerns from the backend one service (or even one method or exception) at a time, without interfering with the existing flow.
The RDS backend, which was already making use of the …
=> Add code hooks for new response serialization flow

moto/elasticache/responses.py, tests/test_elasticache/test_elasticache.py
For `create_cache_cluster` function passing `AutoMinorVersionUpgrade` or `TransitEncryptionEnabled` had no effect and the result always contained `False`. This PR fixes that issue and updates unit test to validate the updated behaviour.
Fixes https://github.com/getmoto/moto/issues/8636
=> ElastiCache: fixed AutoMinorVersionUpgrade and TransitEncryptionEnabled argument issue

moto/autoscaling/models.py, tests/test_autoscaling/test_autoscaling.py
Ensure launch template is passed when creating instances in autoscaling groups.
This allows listing all disks which are created when an instance is created.
=> fix(autoscaling): Ensure launch template is passed when creating instances in autoscaling groups.

moto/backend_index.py, moto/dynamodb/urls.py, tests/test_core/test_url_base_regex.py
There have been a number of (seemingly) random CI failures lately ([1](https://github.com/getmoto/moto/actions/runs/13835470472/job/38709588990), [2](https://github.com/getmoto/moto/actions/runs/13863398864/job/38797171887), [3](https://github.com/getmoto/moto/actions/runs/13817630158/job/38655165818)) resulting in the following error:
```
botocore.exceptions.ClientError: An error occurred (404) when calling the CreateBucket operation: Not Found
```
Looking deeper at the logs in some of these cases revealed a pattern:
```
operation_name = 'CreateBucket'
api_params = {'Bucket': '99de52f2-6849-40c0-b76c-99da9acaaddb'}
```
```
operation_name = 'CreateBucket'
api_params = {'Bucket': '68d04331-de3b-43eb-8988-a5bba5a3eddb'}
```
```
operation_name = 'CreateBucket'
api_params = {'Bucket': …
```
=> Fix: Dynamodb account-based endpoint urls

moto/awslambda/models.py, moto/core/serialize.py, moto/dynamodbstreams/models.py, moto/dynamodbstreams/responses.py, moto/ec2/models/transit_gateway.py, moto/ec2/responses/transit_gateways.py, moto/ecr/exceptions.py, moto/ecr/models.py, moto/ecr/responses.py, moto/mq/exceptions.py, moto/mq/models.py, moto/mq/responses.py, tests/test_core/test_protocols.py, tests/test_core/test_serialize.py, tests/test_ec2/test_transit_gateway.py, tests/test_ecr/test_ecr_policy_validation.py, tests/test_mq/test_mq.py
| Protocol | Service | Comments |
| :-----------------------: | --- | --- |
| `ec2` | Amazon Elastic Compute Cloud | Only migrated `TransitGateway` responses, which illustrates how this can be done piecemeal for larger service backends.  Still a good chunk of XML template code deleted, even for this one small part of EC2! |
| `json` - `1.0` | Amazon DynamoDB Streams | Currently has an open issue related to serialization (#8622). Very simple backend (no `exceptions.py` file). |
| `json` - `1.1` | Amazon Elastic Container Registry | This service had a lot of specialized serialization code polluting the backend models.  All gone now! |
| `rest-json` | AmazonMQ | Currently has an open issue related to serialization (#8632).  Lots of `.to_json()` methods deleted.  A good example of modelled …
=> Core: add response serialization reference implementations for each AWS protocol

moto/mediaconnect/responses.py, tests/test_apigateway/test_apigateway_integration.py
The Parameter names changed to UpperCase in botocore==1.37.16, breaking all our tests.
https://github.com/boto/botocore/commit/e26766703cd11937c144ad74edf16c657d13c3f9#diff-519c5d5eac7160096946a495de3480423e1a0e56b14c4fbf1b38d1b6bc57303f
These tests are also run against older botocore versions, so we know for sure that the current implementation serves both the current and older botocore versions.
In order to ensure that all tests pass against all dependencies, some APIGateway tests were disabled for `requests`-versions under `0.1.7.0`, just because those scenarios were not yet supported.
=> MediaConnect: Fix botocore>=1.37.16 compatibility

.github/workflows/test_outdated_versions.yml, setup.cfg, tests/test_awslambda/test_lambda_eventsourcemapping.py
Ups the minimum botocore version that supports both `is_document_type` and `error_code` - both properties of `botocore.model` that are now used by the serialization code, but were only introduced in [1.1.6.0](https://github.com/boto/botocore/commit/1d91dbbf23ab883f3c92fe7f6c22e0fc726d5c7d) and [1.20.88](https://github.com/boto/botocore/commit/3b87b23002d99df480b147252897b45fd10241a1) respectively.
Also updates the outdated dependency tests to verify that the tests pass with this version.
FYI @bpandola
=> Admin: Up minimum botocore version to 1.20.88

moto/applicationautoscaling/models.py, moto/applicationautoscaling/responses.py, tests/test_applicationautoscaling/test_applicationautoscaling.py
This PR makes [`RegisterScalableTarget`](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_RegisterScalableTarget.html) and [`DescribeScalableTargets`](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalableTargets.html) return the [ARN of the scalable target](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsapplicationautoscaling.html#awsapplicationautoscaling-resources-for-iam-policies).
```
$ aws application-autoscaling register-scalable-target \                                                                                                                                          
--service-namespace dynamodb \ …
```
=> Application Autoscaling: Add ARN for scalable targets

moto/dynamodb/models/__init__.py, moto/dynamodb/parsing/key_condition_expression.py, moto/dynamodb/responses.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/models/test_key_condition_expression_parser.py, tests/test_dynamodb/test_dynamodb.py, tests/test_dynamodb/test_dynamodb_condition_expressions.py
This addresses issue https://github.com/getmoto/moto/issues/8474
In the responses file, I added validation checks that every attribute name is used in the various expressions that each request takes. Without major changes, these validations have to be done at the responses level instead of the backend level, because some response functions call the same backend functions, and which expressions need to be included in the check varies between request types.
I had to adapt a couple of the parsers to track which attribute names they used during parsing.
I skipped batch_write_items because [boto doesn't support any expressions in it](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/batch_write_item.html), for some reason. I also skipped …
=> DynamoDB: Add attribute name use checks to validation layer

moto/route53/models.py, tests/test_route53/test_route53.py
This pr adds support for creating hosted zone with deterministic ids.
Added the `moto_id` wrapper to `create_route53_zone_id` to enable the id manager to return a set custom id
=> Route53: Hosted zone custom id support

moto/moto_api/_internal/recorder/models.py, moto/s3/responses.py
This started with #8495, which attempted to address breaking changes introduced in boto/boto3#4392.  A key part of those changes was "S3 clients [now] default to enabling an additional checksum on all Put calls".  This trailing checksum is provided via a "chunked" stream (the body of the request is sent with the checksum following).  In #8495, a hacky conditional was added to the S3 responses class to detect this type of request when replayed via moto's `recording` api in order to get the request `body` from the underlying `input_stream`.  
Werkzeug is unable ([for good reason](https://github.com/pallets/werkzeug/issues/2346#issuecomment-1059246951)) to handle a `dechunked` request sent with a `chunked` transfer encoding, which is exactly what happens when the `moto` recorder attempts to …
=> Recorder: fix replay of `chunked` requests

moto/dynamodb/exceptions.py, moto/dynamodb/models/__init__.py, moto/dynamodb/parsing/ast_nodes.py, moto/dynamodb/parsing/validators.py, moto/dynamodb/responses.py, moto/dynamodb/utils.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py, tests/test_dynamodb/exceptions/test_dynamodb_transactions.py, tests/test_dynamodb/test_dynamodb_utils.py
This addresses [issue 8582](https://github.com/getmoto/moto/issues/8582).
I discovered a lot about the AWS api's handling of overlapping paths while making test cases for this one:
- AWS does substitute attribute names in the error messages
- AWS only catches overlapping paths if neither path is an attribute name
- AWS does detect duplicate paths if one or more of them is an attribute name
- AWS splits the path into a list in the error message
Based on this, I found the following issues with the current validation:
- it only checked for conflicts between adds and deletes, or between set actions
- it only checked for duplicate paths
- it didn't handle attribute name substitution
I realized that by limiting a validation to an UpdateExpression, I could add top-level checks to the already …
=> DynamoDB: Path overlap check for all types of updates

moto/ec2/models/launch_templates.py, moto/ec2/responses/launch_templates.py, tests/test_ec2/test_launch_templates.py
Hi, this pull request is to add the ModifyLaunchTemplate response to EC2. The action is used to set the default version of the launch template (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/modify_launch_template.html). I have linted the commits according to the contribution guide and tests pass.
This is my first pull request, and if there is additional work required or other feedback, I'm happy to work through that.
=> EC2: ModifyLaunchTemplate

moto/events/models.py, moto/rds/models.py, moto/secretsmanager/models.py, tests/test_events/test_events.py, tests/test_rds/test_integrations.py, tests/test_rds/test_rds.py, tests/test_rds/test_rds_clusters.py, tests/test_secretsmanager/test_secretsmanager.py
This PR builds on #8373, integrating the RDS and SecretsManager backends to provide an AWS managed secret for storing DBCluster/DBInstance master user passwords.
An internal `create_managed_secret` method has been added to the SecretsManager backend, allowing other services to easily create managed secrets.  The EventBridge backend, which had been doing its own simulation of a managed secret, has been updated to use this new method.
Comprehensive `aws_verified` tests covering the entire Managed Master User Password lifecycle are also included. 
Closes #8724
=> RDS: integrate with SecretsManager for managing master user password 

MANIFEST.in, setup.cfg
Fixes #8738 
The license-expression was changed recently due to [PEP 639](https://peps.python.org/pep-0639/). [The docs](https://packaging.python.org/en/latest/specifications/core-metadata/#classifier-multiple-use) now explicitly call out that `License ::` is deprecated in favor of `License-Expression ::`.
The reference to `tests/terraformtests` is very old - that folder was removed ages ago (in favor of `other_langs/terraform`).
With these changes, there are no warnings anymore when building the wheel for Moto.
------
Note: If/when we ever move to the `pyproject.toml` setup, we should consolidate the license-declarations. We currently have two, one as a top-level field and another as a classifier, but Python suggest only using the top-level field `license_expression`.
See …
=> Admin: Update project metadata

moto/s3/responses.py
Looks like the casing changed (`True` -> `true` in a recent `botocore` update (potentially [this one](https://pypi.org/project/botocore/1.37.25/)), and Moto didn't understand the provided parameter anymore. This should fix the tests on master.
=> S3: delete_objects(): BypassGovernanceMode should handle both True and true

moto/dynamodb/parsing/validators.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Fixes #8740 
If we only have a root name (and not an expression, so 'path' instead of '#path'), AWS only checks for direct matches, not path overlaps. However, this code path should trigger only if we have a root name (`root`, one child) - not with a nested name (`root.child`, which resolves to three children)
@BlizzardOf - considering it's a minor adjustment to [your earlier PR](https://github.com/getmoto/moto/pull/8648) where we introduced path overlap checks, do you want to review this?
=> DynamoDB: Dont trigger Path overlap on expressions with shared root

moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
Previously when an ingress/egress rule is created with multiple
{IpRanges,UserIdGroupPairs,PrefixListIds} a single rule was created to
hold all of these rules. This is different from AWS behavior where each
of these result in a distinct rule.
Fixes #8729
=> EC2: Create SecurityRule objects for each IpPermission

tests/test_ec2/__init__.py, tests/test_ec2/test_fleets.py, tests/test_ec2/test_security_groups.py
This PR validates some additional EC2 tests against AWS, to make sure that the changes in #8733 are correct.
The `ec2_aws_verified`-fixture has been updated to automatically create/delete VPC's/SecurityGroups, making it a lot more simple to apply this fixture to future tests.
=> EC2: Validate SG Rules tests against AWS

setup.cfg
Followup to #8739 - PyPi rejected the original License-Expression.
=> Admin: Fix license expression

.github/workflows/tests_real_aws.yml, tests/test_rds/test_rds.py
@bblommers Not sure if there's a process that needs to be followed before enabling, so I've requested your review.
There are only three `aws_verified` RDS tests.  Two in `tests/test_rds/test_integrations.py` (which I recently committed) and one that you wrote some time ago (that required a minor change in this PR because a subsequent commit from someone else made `client` a fixture [with mocking enabled]).
I did a one-off run for the tests I wrote, and they do pass:
Link to run: https://github.com/getmoto/moto/actions/runs/14187655393/job/39745796366
=> Admin: enable verified RDS tests to run against AWS

moto/rds/models.py, tests/test_rds/test_rds.py
=> RDS: snapshot type should be `manual` when stopping a DBInstance

moto/s3/responses.py, tests/test_s3/test_s3_replication.py
Add account ID to bucket replication when provided, to support mocking cross accounts.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/put_bucket_replication.html
=> [S3] Add Account to Replication

moto/ec2/exceptions.py, moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
Applies the standard `moto` EC2 filtering pattern to security group rules, simplifying the backend implementation. 
Closes #8735
=> EC2: refactor `DescribeSecurityGroupRules` filtering

moto/ec2/models/fleets.py, tests/test_ec2/test_fleets.py
In the current implementation, instance-level tags were not being applied to EC2 instances when the fleet type was set to "instant". According to the [AWS documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_fleet.html), instance tags should be applied when the fleet type is `instant`, but not when it's `request` and `maintain `. 
- Added support for instance-level tags when the fleet type is set to "instant".
- Added unit tests to verify that instance tags are correctly applied when the fleet type is `instant`.
- Added tests to ensure that instance tags are not applied for fleet types of `request`, aligning with AWS specifications.
This change primarily affects the EC2 Fleet tag handling. There are no major impacts on other parts of …
=> feat(ec2): Support instance-level tags for EC2 fleets with type="instant"

.github/workflows/build.yml, .github/workflows/tests_cli.yml, moto/cognitoidentity/models.py, other_langs/tests_cli/test_cognity_identity.bats
Fixes #8719 
The `get_id()` method is authenticated, which means we do not always know which region it was sent to. 
- If it is sent to `us-east-1`, then we're lucky, because we always default to that region if we can't find any
- If botocore is used, we're lucky, because it adds a specific `region` header (even if there is no Authorization-header)
- If the CLI is used, for a non-standard region, we're in trouble, because then we cannot determine which region the request was sent to.
But: he identity_pool_id is always prefixed with the region it was created in, so we assume that is also the region the request was sent to.
Also adds new test cases using [the Bats-framework](https://bats-core.readthedocs.io/en/stable/) to test this scenario against the CLI.
=> CognityIdentity: Handle unauthenticated requests (without region) to `get_id()`

moto/acm/models.py, tests/test_acm/test_acm.py
Fixes https://github.com/localstack/localstack/issues/11584
=> fix(acm): Fix certificate issuance logic for private CAs and add corresponding tests

moto/batch/models.py, tests/test_batch/test_batch_tags_job_queue.py
When creating a Batch Job queue AWS allows to provide a compute env name instead of its ARN as part of the `--compute-environment-order` argument. Although the documentation mentions only the ARN https://docs.aws.amazon.com/cli/latest/reference/batch/create-job-queue.html the operation works if the name is provided.
=> Batch: Accept compute env name in computeEnvironmentOrder when creating job queue

moto/rds/models.py, tests/test_rds/test_rds.py, tests/test_rds/test_rds_clusters.py
I've stumbled across this while updating moto in my project. Tests which sent two modify requests with `ManageMasterUserPassword=False` are started failing afterwards.
Even though I don't remember why I wrote those tests this way and make them work again, I think it is more convenient if moto does not fail when multiple modify requests are sent with the same parameter. What do you think?
=> RDS: do not throw an error if multiple modify requests are sent with ManageMasterUserPassword=False

moto/ec2/models/vpcs.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py, tests/test_ec2/test_vpcs.py
AWS does not allow deleting VPCs that have subnets associated with it. This PR adds this behaviour to Moto.
=> EC2: Raise when deleting VPCs with dependent Subnets

IMPLEMENTATION_COVERAGE.md, docs/docs/services/ec2.rst, moto/ec2/exceptions.py, moto/ec2/models/__init__.py, moto/ec2/models/instances.py, moto/ec2/models/subnets.py, moto/ec2/models/vpcs.py, moto/ec2/responses/subnets.py, moto/elb/models.py, tests/test_ec2/test_subnets.py, tests/test_ec2/test_vpcs.py
This PR implements the EC2 [CreateDefaultSubnet](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateDefaultSubnet.html) operation.
> `CreateDefaultSubnet` operation creates a default subnet with a size `/20` IPv4 CIDR block in the specified Availability Zone in your default VPC. You can have only one default subnet per Availability Zone.
Moto already supports the EC2 [CreateDefaultVpc](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateDefaultVpc.html) and this is updated such that it also [creates the default subnets](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc-components.html).
The implementation assigns the `/20` CIDR blocks to AZs in sequence as follows, but that's not always the case on AWS:
- ...a: `172.31.0.0/20`
- ...b: `172.31.16.0/20` …
=> EC2: Implement CreateDefaultSubnet operation

moto/s3/exceptions.py, moto/s3/models.py, tests/test_s3/test_s3.py
Originally introduced in #7468. The validation surrounding the Days-parameter is a lot more complicated then the docs suggest, so the current implementation throws the exception when it shouldn't.
I've tried testing this against AWS, but they keep returning a `MalformedXML`-exception without explaining what's wrong - so that makes it a lot more difficult to determine how this is supposed to work. Hence the current 'fix', that just removes the validation - better to have no validation, then wrong validation.
Fixes #8635
=> S3: RestoreObject: Remove validation around Days-parameter

docs/docs/services/acm.rst, moto/acm/models.py, moto/acm/responses.py, tests/test_acm/test_acm.py
Adds support for the following in ACM:
- https://docs.aws.amazon.com/acm/latest/APIReference/API_GetAccountConfiguration.html
- https://docs.aws.amazon.com/acm/latest/APIReference/API_PutAccountConfiguration.html
=> feat(acm): implement `GetAccountConfiguration` and `PutAccountConfiguration` APIs

docs/docs/services/acm-pca.rst, moto/acmpca/exceptions.py, moto/acmpca/models.py, moto/acmpca/responses.py, tests/test_acmpca/test_acmpca.py
Adds support for the following in ACM:
- https://docs.aws.amazon.com/privateca/latest/APIReference/API_PutPolicy.html
- https://docs.aws.amazon.com/privateca/latest/APIReference/API_GetPolicy.html
- https://docs.aws.amazon.com/privateca/latest/APIReference/API_DeletePolicy.html
=> feat(acm-pca): add support for `PutPolicy`, `GetPolicy`, and `DeletePolicy`

moto/ec2/exceptions.py, moto/ec2/models/instances.py, tests/test_ec2/test_instances.py
On AWS, EC2 [RunInstances](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html) does not require a subnet ID. By default, it uses the [default subnet](https://docs.aws.amazon.com/vpc/latest/userguide/work-with-default-vpc.html) from the default VPC. However, if the default subnet and VPCs are not available (i.e. if they were manually deleted), the subnet ID is mandatory.
This PR implements this behaviour in Moto.
=> EC2: RunInstances must raise if default and request subnet is missing

moto/s3/exceptions.py, moto/s3/models.py, moto/s3/responses.py, scripts/scaffold.py, tests/test_s3/test_s3.py
Adds support for:
- [put_bucket_inventory_configurations](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/put_bucket_inventory_configuration.html)
- [get_bucket_inventory_configuration](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/get_bucket_inventory_configuration.html)
- [list_bucket_inventory_configuration](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/list_bucket_inventory_configurations.html)
** Including minor scaffolding fix to resolve #8726
=> [S3] inventory_configuration support

moto/ec2/models/instances.py, tests/test_ec2/test_instances.py
This PR updates the filtering logic used in describe_instance_status to align with AWS EC2's behavior, where multiple filters must all match (AND condition).　As documented in the [describe_instance_status boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_instance_status.html) is written 
> If you specify multiple filters, the filters are joined with an AND, and the request returns only results that match all of the specified filters.
Previously, filters were evaluated in a way that allowed instances to match if any single filter matched (OR behavior). This has now been corrected.
Changes include:
- Filtering logic in describe_instance_status now requires all filters to match.
- Tests added to confirm correct behavior with:
- …
=> EC2: Update describe_instance_status filter logic to require all filters to match

moto/iam/policy_conditions.py, tests/test_core/test_auth.py
With introduction of policies conditions evaluation in #8680, for currently non-supported ones the explicit exception is throwing. However, according to the investigation for #8839, S3 bucket policies are also evaluating through the same iam `access_control` mechanism and introducing blockers for previously working scenarios.
Main goal of this PR is to provide the backward compatibility check - the condition is not supported, then it is not blocking the further flow like it was before the new logic introduction.
=> [Policies conditions] Fixed compatability issue for currently non-supported policy conditions operations

moto/ec2/models/instances.py, tests/test_ec2/test_instances.py
This pull request updates the behavior of `describe_instance_status` to conform to the AWS API specification regarding how filters interact with the `InstanceIds` parameter.
- Previously, the internal `get_multi_instances_by_id` method enforced that all specified instance IDs must also satisfy any provided filters, which does not match AWS behavior.
- As per [boto3 describe_instance_status documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_instance_status.html):
> A filter name and value pair that is used to return a more specific list of results from a describe operation. Filters can be used to match a set of resources by specific criteria, such as tags, attributes, or IDs.
- Therefore, the updated logic:
- First narrows down the …
=> EC2: Update describe_instance_status instance ID filtering logic

moto/rds/exceptions.py, moto/rds/models.py, tests/test_rds/test_rds_clusters.py
**Make** `target_db_instance_identifier` **parameter optional in** `failover_db_cluster`
In the previous implementation, target_db_instance_identifier was a required parameter. This change aligns the behavior with the AWS API, where the failover target can be selected automatically if the parameter is omitted.
A unit test has been added to cover this updated behavior.
=> RDS: make failover target parameter optional

moto/rds/models.py, tests/test_rds/test_integrations.py
As far as I can tell, the managed secret for an RDS cluster is a json object dumped as string. Sadly I cannot find any official documentation, only confirmation from AWS Support.
At least https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_secret_json_structure.html mentions that secrets for RDS/Aurora are supposed to have JSON structure
=> RDS: store managed secret as json with appropriate fields

moto/servicecatalogappregistry/models.py, tests/test_servicecatalogappregistry/test_servicecatalogappregistry.py, tests/test_servicecatalogappregistry/test_servicecatalogappregistry_cloudformation.py
- Move the CF imports to reduce the initial loading time, from 1.6 secs to 0.6 secs. (CloudFormation imports everything, so this is quite an expensive import)
- Move the CF-specific tests to a dedicated file, so this is skipped when verifying the [service-specific dependencies](https://github.com/getmoto/moto/blob/master/.github/workflows/dependency_test.yml)
=> ServiceCatalogAppRegistry - Local CF import

tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi.py, tests/test_workspaces/test_workspaces.py
The WorkDocs service is [deprecated as of April 25th 2025](https://www.reddit.com/r/aws/comments/1cd1iqb/workdocsamazon_has_decided_to_end_support_for_the/), and `botocore` has removed support for the `EnableWorkDocs`-parameter in [version 1.38.13](https://github.com/boto/botocore/commit/d996fb2fac60d7413e10272ebad14ea55b344694).
This PR:
- Removes all references to `EnableWorkDocs` in the regular `Workspaces` tests
- Adds a new test for older botocore versions to verify that this still behaves correctly in Moto 
- Removes the `test_register_workspace_directory_with_subnets`, as it was equivalent to `test_register_workspace_directory`.
=> Workspaces Tests: Deprecate EnableWorkDocs-param

moto/core/utils.py, moto/iotdata/models.py, tests/test_iotdata/test_iotdata.py
Improves the parity between how `update_thing_shadow()` behaves when sending empty dictionaries. The existing implementation had two problems.
First: when a user calls `update_thing_shadow` with an empty desired or reported state, we should ignore this empty dict.
```json
{
"state": {
"reported": {}
}
}
```
However, if an attribute within the state is empty, we should keep it:
```json
{
"state": {
"reported": {
"attr": {}
}
}
}
```
Our implementation treated the two cases the same, and always removed empty dictionaries. With this change, we make it explicit that empty reported/desired states are effectively ignored
The second problem is that we always assumed that types would not change - that is, if a new value for attribute `a` is a dictionary, it was assumed that the original value for …
=> IOTData: update_thing_shadow() should keep empty dicts

.github/workflows/build.yml, .github/workflows/tests_sdk_sagemaker.yml, moto/iam/models.py, moto/iam/responses.py, other_langs/tests_sagemaker_client/custom_script.py, other_langs/tests_sagemaker_client/test_model_training.py, other_langs/tests_sagemaker_client/test_pipeline_session.py
We have an [outstanding feature request](https://github.com/getmoto/moto/issues/7037) to add support for SageMaker PipelineSessions, which is a feature specific to the [Sagemaker client](https://sagemaker.readthedocs.io/en/stable/overview.html).
This PR adds some initial tests for this library to verify that Moto can interact with it.
There is also a minor improvement to `IAM:create_role`, where we don't need to return the tags. Unrelated, just something I noticed while debugging.
=> Tests: Add SageMakerClient test

tests/test_ec2/test_elastic_network_interfaces.py
EC2 tests are run in parallel, so extra care needs to be taken when asserting against responses, as they can contain entities created by other concurrently running tests.
This particular test has been causing a number of CI failures of late.
=> EC2: Fix Flaky Test

moto/apigateway/models.py, tests/test_apigateway/test_apigateway.py
This PR:
- Raises `ApiKeyNotFoundException` for `update_api_key` when the key is not found
- Raises `ApiKeyNotFoundException` for `delete_api_key` when the key is not found
- Adds test cases for both functions
Previously these functions would raise `KeyError` instead of what AWS would raise in this case.
=> [APIGateway] Add ApiKeyNotFoundException for update/delete_api_key

moto/events/models.py, moto/events/responses.py, tests/test_events/test_events.py
1. Updated the event bus schema to match boto3 API for describe_event_bus and create_event_bus: https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DescribeEventBus.html
- Added timestamp fields (CreationTime and LastModifiedTime) to the EventBus class
- Added support for optional fields (DeadLetterConfig, Description, and KmsKeyIdentifier) to match the full AWS API schema
=> EventBridge: Update describe_event_bus schema

moto/sqs/responses.py, tests/test_sqs/test_sqs.py
In our tests we were missing the MessageGroupId which AWS SQS returns when specified in the `MessageSystemAttributeNames` parameters of `receive_message`. See [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/receive_message.html).
We added support for returning the MessageGroupId and several other system attributes and added tests for those as well.
=> SQS: Return MessageGroupId (and similar attributes) on receive_messages

moto/batch/models.py, moto/batch/responses.py, tests/test_batch/test_batch_compute_envs.py
Added the ability to use tags in the batch compute environment for the following two functions:
**1. create_compute_environment
2. describe_compute_environment**
Fixes: https://github.com/getmoto/moto/issues/8895
=> Added the ability to use tags in batch compute environment

IMPLEMENTATION_COVERAGE.md, docs/docs/services/ec2.rst, moto/ec2/exceptions.py, moto/ec2/models/security_groups.py, moto/ec2/responses/security_groups.py, tests/test_ec2/test_security_groups.py
This PR implements the EC2 [ModifySecurityGroupRules](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifySecurityGroupRules.html) operation. Only IPv4 CIDR ranges are supported.
There is an accompanying AWS validated test.
=> EC2: Implement ModifySecurityGroupRules

moto/ecr/models.py, tests/test_ecr/test_ecr_boto3.py
A recent customer request in LocalStack hinted towards validation errors of an ECR policy.
After some investigation, it turns out that the ECR repository policy had duplicated Sids in different statements.
While this is discouraged, it works with ECR on AWS, so it should work with moto as well.
* Remove requirement for sid uniqueness on ECR repository policies
* Add test to validate the special cases of ECR policy validation
=> Allow duplicated Sids in ECR policies

moto/cognitoidp/models.py, moto/settings.py, tests/test_cognitoidp/test_cognitoidp.py
Same as #5194 , but for user pool client.
My use case is: 
I have a frontend which uses cognito for login and i want to connect to moto server for testing and developing. Every time I run the compose file, it creates a new user pool client with a different id, and the frontend breaks.
=> Stable cognito user pool client

moto/s3tables/responses.py, moto/s3tables/urls.py, tests/test_s3tables/test_server.py
See changeset: https://github.com/boto/botocore/commit/75060cf32da8ba035e74362a2558bdf8edfbb99d#diff-3f3b0b087fa041bc9956863e5c76ee5b7f44d31a5a581182850e2f9bc7fe975b
The URL for the `GetTable`-command changed from `/tables/{tableBucketARN}/{namespace}/{name}` to `/get-table`.
=> S3Tables: Support new URL for botocore 1.38.32

moto/sns/models.py, moto/sqs/models.py, tests/test_sns/__init__.py, tests/test_sns/test_publishing_boto3.py, tests/test_sns/test_subscriptions_boto3.py
Fixes #8899 
- Enables sending messages from a FIFO topic to a standard Queue
- Adds validation when subscribing from a standard topic to a FIFO queue
- Adds validation when subscribing to SQS without specifying an ARN
- Adds AWS-validated tests for all
=> SNS: Allow sending messages from standard topic to FIFO queue

moto/ec2/models/security_groups.py, tests/test_ec2/test_security_groups.py
This pr fixes a typo in `ModifySecurityGroupRule`. Attempting to modify a security group rule with a security group association would fail as `ReferencedGroupId` was misspelled.
=> EC2: VPC: Fix typo in referenced group

moto/core/constants.py, moto/core/serialize.py, moto/core/utils.py, tests/test_core/test_serialize.py
There is often a mismatch between the attribute names in the botocore model data (which are typically `camelCase` or `PascalCase`) and the Python objects in the moto backend (which are `snake_case`). The serializer attempts to pluck values from a backend object by checking various "aliases" for a given attribute name.  This PR refactors the alias list into a generator based on discrete `AliasProvider` classes, which properly encapsulate the logic behind each alias and speeds things up by only calculating them as needed.
=> Serialization: Refactor Attribute Access

moto/iam/models.py, moto/iam/responses.py, tests/test_iam/test_iam.py
This PR excises the original Jinja/XML template-based responses in favor of direct integration with our dedicated Query Protocol Serializer:
* all serialization concerns have been removed from the model, e.g. base64 encodings, string formatting of datetime objects, etc.
* very minor test updates were required, mostly just for a couple of methods where we're now (automatically) returning additional response fields
Out of scope for this PR:
* the backend handles tagging inconsistently (i.e. some models use the `moto` TaggingService`, but not all)
* pagination response attributes were maintained if they were part of the original XML templates, but they are (still) applied somewhat haphazardly
* hard-coded values contained in the original XML templates have been moved unchanged to either the …
=> IAM: integrate with core AWS response serializer

moto/awslambda/models.py, other_langs/terraform/awslambda/event_source_mapping.tf, other_langs/terraform/awslambda/event_source_mapping_common.tf, other_langs/terraform/awslambda/event_source_mapping_sqs.tf, other_langs/terraform/awslambda/event_source_mapping_sqs_fifo.tf
Follow up # #8972
`StartingPosition` now only defaults to `TRIM_HORIZON` when the source is not SQS. (Based on [the TF docs](https://registry.terraform.io/providers/hashicorp/aws/4.58.0/docs/resources/lambda_event_source_mapping#starting_position-1).)
This ensures that ESM's are only updated when something changes, and are not destroyed and recreated with every `terraform apply`.
Includes some minor refactorings to make things more readable (like removing the `_validate_event_source`-method, and making the `event_source_arn`-parameter to `_get_service_source_from_arn` optional
New Terraform scripts are now included to verify that we can create/manage/delete ESM's without problems.
=> AWSLambda: TF compatibility

moto/kms/models.py
When scheduling deletion of a KMS key the a local time value is created but then treated as UTC when converted to a float. So use the `utcnow` utility function instead.
=> kms - use UTC rather than local time

tests/test_dynamodb/__init__.py, tests/test_dynamodb/test_dynamodb.py
See #8916 where this behaviour was questioned. Both tests pass against AWS (as-is), indicating that Moto does behave as it should.
=> DynamoDB: Verify KEYS_ONLY projection type against indexes

moto/moto_proxy/proxy3.py, tests/test_core/test_proxy.py, tests/test_core/test_responses_module.py, tests/test_core/utilities.py, tests/test_sns/test_http_message_verification.py
The proxy tests time out regularly, as they try to reach out to `httpbin.org` which appears to be unreliable
- Allow requests to a host on a custom port to be passed through (i.e. `http://localhost:8080`)
- Change test to pass through to a local server for HTTP requests
- Disable test that passes through HTTPS request, as there's no need to run this every time
- Refactor the `SimpleServer` concept, as the same class is used in multiple places
=> Proxy: Test passthrough with local server

moto/route53/models.py, moto/route53/responses.py, tests/test_route53/test_route53.py, tests/test_route53/test_route53_hosted_zone_ids.py
Fixes #8931 
- Increases the size of the HostedZoneID to 22 characters (inline with AWS)
- This was originally introduced in #1184, which was 8 years ago, so maybe the length was 15 back then? In any case, it's 22 now for new hosted zones.
- Adds ResourceId length validation to `change_tags_for_resource()` and `list_tags_for_resource()`
- Adds check that a HostedZone exists when calling `change_tags_for_resource()`
- Adds AWS-validated tests
=> Route53: change_tags_for_resource(): Validate ZoneId parameter

docs/docs/services/ram.rst, moto/ram/models.py, moto/ram/responses.py, moto/ram/urls.py, tests/test_ram/test_ram.py
Greetings.
Recently, I'm working with the RAM methods and I noticed that we don't have some API methods for this service implemented here. So, I commited some changes in the lib:
- I'm adding the AWS Glue `database`, `table` and `catalog` shared resource types to enable these resources for the currently available API implementations;
- I'm implementing the `list_resource_types()` API, just to pavimentate the next implementations I'm willing to code.
I've been thinking about implementing the permissions methods in another PR, such as:
- `create_permission()`;
- `get_permission()`;
- `list_permissions()`;
- `list_permission_associations()`;
- `list_resource_share_permissions()`
I'm new here, so, feel free to recomend any design pattern for the implementations I added and to guide me with …
=> RAM - Implementing ListResourceTypes

IMPLEMENTATION_COVERAGE.md, docs/docs/services/ecs.rst, moto/ecs/models.py, moto/ecs/responses.py, tests/test_ecs/test_ecs_boto3.py, tests/test_ecs/test_ecs_task_definitions.py
While I'm working on my personal project, I found there are some features missing in ECS that I need. So I implemented:
- I found that current `list_task_definitions` does not support `status` filter. I implement it added tests for it.
-The `delete_task_definitions` feature is not implemented, so I implemented it.
I have some questions:
- Because I thought `test_ecs_boto3.py` file quite big, I added tests for `delete_task_definitions` in new file, `test_ecs_task_definitions.py`. If I should merge the file, please let me know.
Thank you for maintaining this library. Please feel free to suggest any changes!
=> Implement ECS `delete_task_definition` and `status` filter for `list_task_definitions`

moto/dynamodb/parsing/key_condition_expression.py, tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Fixes #8655 
All tests are validated against AWS.
=> DynamoDB: Query() should validate extra Attrs in KeyExpression

moto/s3/models.py, tests/test_s3/test_s3_content_encoding.py
Fixes #9007 
`botocore` sometimes adds the Content-Encoding header `aws-chunked` (since https://github.com/boto/botocore/pull/2859)
Moto receives the headers, and returns it as-is. But: AWS: removes the `aws-chunked` part, and only returns whatever the user explicitly provided.
Note that in `botocore==1.35.0` this did not happen - the `aws-chunked` encoding is not added. My assumption is that this changed with https://github.com/boto/boto3/issues/4392 (fixed on our side with https://github.com/getmoto/moto/pull/8495), which would align with the observation from the user that this started around February. I haven't done any deepdive into the root cause though.
This PR explicitly removes the `aws-chunked` value (if provided), improving parity with AWS.
=> S3: get_object() should not return ContentEncoding=aws-chunked

moto/ssm/models.py, tests/test_ssm/test_ssm_boto3.py
Make sure add_tags_to_resource and remove_tags_from_resource are reflected when running describe_parameters with filters.
=> Ssm: Ensure describe_parameters honors tag updates

moto/core/responses.py, moto/core/serialize.py, tests/test_core/protocols/output/query-json.json, tests/test_core/test_protocols.py
For a number of Query protocol-based services (e.g. Cloud Formation, Redshift, SNS), the original `boto` library would add a `ContentType=JSON` parameter to the request, which would cause the AWS backend to return JSON instead of the default XML normally used by the protocol.  When `botocore`/`boto3` came on the scene, they dropped this optional parameter and only supported XML responses for these services.  There was a bit of a painful transition for `moto` during this time, as it had to support both `boto` and `boto3` (see #402, #444, https://github.com/getmoto/moto/commit/3cdb4afad0f6a42c790c39c56e2b6f0680d54ff7).
Direct support for the `boto` library was dropped from `moto` long ago, but the code supporting both JSON and XML responses for some service backends remains.  The …
=> Core: add serializer for Query protocol requests that return JSON responses

moto/s3/models.py, moto/s3/responses.py, tests/test_s3/test_s3.py
According to the AWS S3 documentation, the [`PutBucketCors` operation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html#API_PutBucketCors_RequestSyntax) can have an optional field `ID` for every rule with an arbitrary string for later identification. These IDs are stored with the rule and can be retrieved with the [`GetBucketCors` operation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketCors.html#API_GetBucketCors_ResponseSyntax).
This PR adds this field to the internal CORS rule representation and adds test statements in the appropriate tests to ensure they are retrieved correctly by `boto3`.
=> feat: Add ID field to CORS rule

moto/elb/models.py, moto/elb/responses.py, tests/test_elb/test_elb.py
To maintainers and reviewers @bblommers  and @bpandola. This PR fixes #9025. It adds the `AdditionalAttributes` to ELB response. This is unofficial because the aws boto3 api reference does not show an `AdditionalAttributes` block in their example xml, neither is there an example. This block is needed for the `modify_load_balancer_attributes()` and `describe_load_balancer_attributes() `endpoints. See [docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elb.html#client)
Here is the presented default xml:
```xml
<ModifyLoadBalancerAttributesResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
<ModifyLoadBalancerAttributesResult> 
<LoadBalancerName>my-loadbalancer</LoadBalancerName>
<LoadBalancerAttributes>
<CrossZoneLoadBalancing> …
```
=> [ELB] Added additional attribute to ELB response. 

.github/workflows/tests_sdk_sagemaker.yml
Sagemaker tests started failing three days ago, and I tracked it down to the `sagemaker_core` module. Not sure what changed or why it's now failing - hopefully they resolve it with the next release though
=> Admin: Skip Sagemaker-Core==1.0.42 to avoid test breakage

moto/core/base_backend.py, moto/core/common_models.py, moto/core/model_instances.py, moto/moto_api/_internal/responses.py, moto/s3/models.py, tests/test_core/test_moto_api.py
Renaming for clarity and to avoid colliding with subclass attribute names (e.g. `ec2:Reservation.instances`).
=> Core: rename InstanceTracker attribute

moto/ssm/models.py, tests/test_ssm/test_ssm_parameterstore_cloudformation.py
Use the `resource_name` to delete the SSM Parameter when using Cloudformation.
Will fallback to using the Cloudformation JSON if `resource_name` is not specified.
The JSON `cloudformation_json` would not match the resource name if Parameter values are being used in the Cloudformation template to represent the SSM ParameterStore name.
In the `cloudformation_json` case below, the SSM parameter that is passed to `ssm_backend.delete_parameter` is the literal value, not the parsed value.
```
{
"Properties": {
"Name": {
"Fn::Sub": "${Name}"
},
"Type": "String",
"Value": {
"Ref": "Value"
}
},
"Type": "AWS::SSM::Parameter"
}
```
=> ssm: Delete ssm parameter based on resource name

moto/elasticbeanstalk/exceptions.py, moto/elasticbeanstalk/models.py, moto/elasticbeanstalk/responses.py, tests/test_elasticbeanstalk/test_elasticbeanstalk.py, tests/test_elasticbeanstalk/test_server.py
Relatively minor changeset required for integration:
* generated new list of solution stacks (previous values were from 2019).
* dropped `Fake` prefix from model names to align with Botocore.
* changed `DeleteApplication` logic when passed a non-existent application name (behavior verified against real AWS backend).
1300+ lines of XML templates deleted!
=> Elastic Beanstalk: integrate with core response serializer

.dockerignore, Dockerfile
This takes a few steps to reduce the size of the generated Docker image, making it faster to load for developers and CI machines.
The arm64 image was 792 MB before I started this work and the result is a 523 MB image, so a reduction of 269 MB.
I have broken the steps taken into individual commits to make it easier to review. Each commit message mentions the size reduction the change gives.
=> Reduce size of the Docker image

moto/core/serialize.py, moto/sns/exceptions.py, moto/sns/models.py, moto/sns/responses.py, tests/test_sns/test_publishing_boto3.py, tests/test_sns/test_subscriptions_boto3.py, tests/test_sns/test_topics_boto3.py
Relatively minor changeset required for integration:
* model only required the addition of a couple attributes
* http status code information was dropped from exception classes (because it's in the service definition)
* tests only required correcting the `InvalidParameter` code (verified against actual AWS)
This PR also contains a minor fix for determining "fault" when serializing errors for the Query and Rest-XML protocols.  The SNS service has an "InternalErrorException" that returns a 500 status code with fault set to "Receiver" (both of which are now covered by test assertions).
> [!NOTE]
> SNS is another service that supported (some) JSON responses for Boto along with the XML responses for Boto3.  None of this code has been covered by tests since Moto dropped support for Boto--and …
=> SNS: integrate with core response serializer

IMPLEMENTATION_COVERAGE.md, moto/rds/models.py, moto/rds/responses.py, tests/test_rds/test_db_cluster_params.py
To reviewers and maintainers @bblommers and @bpandola. This PR adds support for 
```mermaid
flowchart TD
subgraph Scene1 ["Scene 1"]
A1["**👨‍💻 Dev**: Hey RDS, we need to talk..."]
end
subgraph Scene2 ["Scene 2"]
A2["**🗄️ RDS**: Is it about the read replicas again?"]
A3["**👨‍💻 Dev**: No, it's... something deeper."]
end
subgraph Scene3 ["Scene 3"]
A4["**👨‍💻 Dev**: You have too many connections... and you never commit."]
end
subgraph Scene4 ["Scene 4"]
A5["**🗄️ RDS**: That's not true! I committed last night at 03:00 UTC."]
A6["**👨‍💻 Dev**: To a snapshot, not this relationship."]
end
%% Connect scenes
A1 --> A2 --> A3 --> A4 --> A5 --> A6
```
=> [RDS] Adds support for modify db cluster  params.

moto/ec2/models/core.py, moto/ec2/models/internet_gateways.py, moto/ec2/responses/availability_zones_and_regions.py, moto/ec2/responses/carrier_gateways.py, moto/ec2/responses/customer_gateways.py, moto/ec2/responses/egress_only_internet_gateways.py, moto/ec2/responses/tags.py, moto/ec2/responses/windows.py
This PR integrates a few of the simpler EC2 backends (i.e. those that require only additive model updates and no logic updates) with the new serialization flow.
=> EC2: integrate simple responses with core response serializer

moto/cloudformation/parsing.py, moto/cloudformation/responses.py
Moto's Cloud Formation parser manually sets a `type` attribute on each resource after instantiation.  This attribute name is generic and not defined in the [CloudFormationModel](https://github.com/getmoto/moto/blob/f8638d14d2ea245f697d86090fd0f6fc925bd7a3/moto/core/common_models.py#L20) interface.  I considered refactoring this out altogether, as it strikes me as brittle and error-prone, but it would take some effort to get the current custom resource implementation to work.  
Taking everything into consideration, I settled on simply renaming the attribute for clarity and to avoid clashing with the many model definitions that also contain a generic "type" attribute (e.g. `elbv2:LoadBalancer.type`).
=> CloudFormation: rename `type` attribute to avoid clashes

moto/ec2/models/core.py, moto/ec2/models/elastic_network_interfaces.py, moto/ec2/models/managed_prefixes.py, moto/ec2/models/route_tables.py, moto/ec2/models/vpcs.py, moto/ec2/responses/vpcs.py, moto/ec2/utils.py, tests/test_ec2/test_vpcs.py
VPCs are a foundational component of EC2, so some minor tweaks were required for related backends.  A number of boolean values that had been stored as strings have been converted to native Python bool values, which necessitated a new boolean filter matcher.  Outside of correcting assertions for empty arrays, all tests passed without modification.
=> EC2: integrate VPC responses with core serializer

moto/core/parsers.py, moto/core/responses.py, moto/core/utils.py, moto/ec2/models/vpc_service_configuration.py, moto/elbv2/exceptions.py, moto/elbv2/models.py, moto/elbv2/responses.py, tests/test_elbv2/test_elbv2.py
Another fairly clean integration.  Model updates amounted to just renaming a few attributes and using `bool` and `int` instead of `str` where appropriate.  A couple response transformers were needed, but they are simple and easy to understand.
Outside of a single error code correction, all tests continue to pass with no modifications.
Note: this PR also contains some minor tweaks to the core request parsing code, all of which are detailed in individual atomic commits.
=> ELBv2: integrate with core response serializer

moto/cloudformation/exceptions.py, moto/cloudformation/models.py, moto/cloudformation/responses.py, moto/core/serialize.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py, tests/test_cloudformation/test_server.py, tests/test_cloudformation/test_stack_parsing.py
Relatively minor changeset required for integration:
* Model changes consist of just adding/renaming attributes, and dropping the "Fake" prefix from model names.
* Response(s) changes include some DTO classes (to combine data from multiple models) along with some simple transformers.
* Tests did not require any changes; some new assertions were added for better coverage.
This is the first integration to specify a "serialization alias" for a response.  The `Stack` model has both a `parameters` and `stack_parameters` attribute, which differ in their behavior and were the source of a recently reported issue (#9077).  Instead of trying to untangle exactly how these attribute work/should work, I elected to bypass them entirely for the `Stack.Parameters` response attribute, which is aliased to …
=> CloudFormation: integrate with core response serializer

moto/core/parsers.py, moto/ses/exceptions.py, moto/ses/models.py, moto/ses/responses.py, tests/test_ses/test_ses_boto3.py
This one was very straightforward.  There was a lot of really old parameter parsing code in `responses.py`, which I cleaned up a bit.  No tests were modified except for a couple of corrected error code assertions.
=> SES: integrate with core response serializer

moto/ec2/models/amis.py, moto/ec2/responses/amis.py, tests/test_ec2/test_amis.py
`"KernelId"` assertions were removed, as they were just comparing `"None" == "None"` when using Jinja templates.  New serializer does not serialize `None` values, which matches AWS serialization behavior.
Was able to drop the `is_public_string` property because I recently added boolean filter support in another [Pull Request](https://github.com/getmoto/moto/pull/9095/commits/094b23abb71137f03ccba8f1ce883e8afbd9cf63).
=> EC2: integrate AMI responses with core serializer

moto/elbv2/models.py, tests/test_elbv2/test_elbv2.py
Looks like this attribute was hardcoded in the [original XML template](https://github.com/getmoto/moto/blob/60378f74fdcd90f08795262a8c45fe67efa9d169/moto/elbv2/responses.py#L1142C32-L1142C46) and I missed it when I migrated this service to the new serializer (#9098).
This PR just puts the hardcoded value back.  Some additional effort would still be required to make this value meaningful.
Closes #9115
=> ELBv2: Add CanonicalHostedZoneId attribute to LoadBalancer

moto/rds/models.py, tests/test_rds/test_rds_clusters.py
Extracted the `VPCSecurityGroupIds` attribute out into an explicit getter/setter property, with differing behavior for `DBInstance` depending on whether it's part of a `DBCluster`.
Closes #9126
=> RDS: fix modifying DBCluster.VpcSecurityGroupIds

moto/ec2/models/vpcs.py, tests/test_ec2/test_vpcs.py
Adds `Groups` and `CreationTimestamp` to the `DescribeVpcEndpoints` response, as well as associated test coverage.
I left in the `TODO` from the [original XML template](https://github.com/getmoto/moto/blob/b55f533b711f68fa4c4b6950a0a2b42e99af4779/moto/ec2/responses/vpcs.py#L744)
Closes #9124
=> EC2: add missing attributes to `DescribeVpcEndpoints` response

moto/cloudformation/models.py, moto/cloudformation/responses.py, tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py
Support the LogicalResourceId parameter in the DescribeStackResources API.
When set, it returns the resource wrapped in a list if it exists, or returns an empty list if the resource doesn't exist.
Make the tests clearer by removing an unneeded call to DescribeStacks. We don't need to compare the StackId here.
A solution for #9116 .
=> CloudFormation: Add LogicalResourceId param to DescribeStackResources

moto/ec2/models/vpcs.py, moto/ec2/responses/vpcs.py, tests/test_ec2/test_vpcs.py
Fixes https://github.com/getmoto/moto/issues/9111, I decided to separate the tests for the API call and also added tests for the duplicate checks for both subnets and route tables.
If possible I'd also take a crack at the GroupName population in a separate PR.
=> EC2: Add subnet removal funtionality to modify_vpc_endpoints, check for duplicates in adds

moto/s3control/models.py, moto/s3control/responses.py, moto/s3control/urls.py, tests/test_s3control/test_s3control.py
This PR adds support for the following S3 Control APIs:
- [put_storage_lens_configuration_tagging](https://docs.getmoto.org/en/latest/docs/services/s3control.html#:~:text=put_storage_lens_configuration_tagging)
- [get_storage_lens_configuration_tagging](https://docs.getmoto.org/en/latest/docs/services/s3control.html#:~:text=get_storage_lens_configuration_tagging)
Addresses https://github.com/getmoto/moto/issues/9150
=> [S3 Control] Adding support for storage lens configuration tagging 

moto/sqs/models.py, tests/test_sqs/test_sqs.py
Now that SQS supports setting a MessageGroupId on standard queues as part of the "fair queues" feature, this validation logic isn't necessary. See https://github.com/getmoto/moto/issues/9146 for more context
Linting, type checking, and unit tests were all run locally and passed.
=> SQS: Support MessageGroupId on standard queues

moto/ec2/models/managed_prefixes.py, tests/test_ec2/test_prefix_lists.py
This PR adjusts the behaviour of [DescribeManagedPrefixLists](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeManagedPrefixLists.html) operation to resemble AWS.
AWS normally does not return a value for [StateMessage](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ManagedPrefixList.html) field.
The behaviour is validated against AWS using a verified test.
=> EC2: Prefix lists do not return StateMessage

moto/elbv2/models.py, tests/test_elbv2/test_elbv2.py
This PR makes ELB rules assume a default weight if not specified in the request.
This behaviour was checked against AWS.
=> ELBv2: Default weights for TargetGroups

moto/elbv2/models.py, moto/elbv2/utils.py, tests/test_elbv2/test_elbv2.py, tests/test_elbv2/test_elbv2_target_groups.py
This PR updates the ARN construction logic for following resources such that they are unique:
- Listeners
- Load balancers
- Target groups
=> ELB: Resource ARNs must be unique

moto/ecr/models.py, moto/ecr/responses.py, tests/test_ecr/test_ecr_boto3.py, tests/test_ecr/test_ecr_cloudformation.py
Resolves https://github.com/getmoto/moto/issues/8717 in the process.
Along with supporting `IMMUTABLE` value of `imageTagProperty`, this PR also implements (and tests) behaviour when `imageTagMutabilityExclusionFilters` are passed
=> ECR: Supporting mutable and immutable versions of imageTagMutability property of a repository (with exclusion filters)

moto/mediapackage/responses.py, tests/test_mediapackage/test_mediapackage.py
This started with just trying to get rid of the `._get_list_prefix()` call, but then I realized these parameters weren't being parsed at all.  Parsing of the `timeDelaySeconds` and `whitelist` parameters is now fixed and covered with test assertions.
=> MediaPackage: parameter parsing fix-ups

IMPLEMENTATION_COVERAGE.md, docs/docs/services/es.rst, moto/es/models.py, moto/es/urls.py, moto/opensearch/models.py, moto/opensearch/responses.py, tests/test_es/test_es.py
This PR enables describe_elasticsearch_domain_config in ES service which uses merged functionality from OpenSearch service.
=> Enabling describe_elasticsearch_domain_config in ES service

moto/cognitoidp/models.py, moto/cognitoidp/responses.py, moto/core/responses.py, tests/test_cognitoidp/test_server.py
This is a minimal viable changeset to integrate the Cognito backend with Moto's new serialization pipeline.  The impetus for this is #9204, which raised the issue of incorrect date serialization in Cognito responses.  The timestamps have been fixed in the Moto models and are now serialized correctly based on the Botocore models.  One test was modified, as it was asserting against attributes that are not present in a real AWS response from Cognito (and are no longer present in the equivalent Moto response).
This PR also contains a minor enhancement to the serializer that allows for custom response headers, in order to support the `x-moto-forgot-password-confirmation-code` workflow.
The Cognito backend in Moto contains multiple `to_json()` methods, which could be refactored out as a result …
=> Cognito: integrate with core response serializer

moto/autoscaling/models.py, moto/autoscaling/responses.py, moto/cloudformation/models.py, moto/cloudformation/responses.py, moto/cloudwatch/models.py, moto/cloudwatch/responses.py, moto/core/parsers.py, moto/core/responses.py, moto/elasticache/responses.py, moto/elb/responses.py, moto/elbv2/responses.py, moto/iam/models.py, moto/iam/responses.py, moto/redshift/responses.py, moto/sdb/models.py, moto/sdb/responses.py, moto/ses/models.py, moto/ses/responses.py, moto/sns/responses.py, moto/sts/responses.py, tests/test_autoscaling/test_autoscaling_tags.py, tests/test_cloudwatch/test_cloudwatch_boto3.py, tests/test_elb/test_elb.py, tests/test_redshift/test_server.py
This PR opts all of the Query-protocol-based services in to the new request parsing pipeline.  The dedicated QueryParser obviates the need for many of the existing helper methods (e.g. `_get_multi_param()`, `_get_object_map()`, etc.), which have been replaced with the generic `_get_param()`.  Because the new parsing flow takes parameter type information from the Botocore models into account, some minor Moto model changes were also required (mostly around boolean values that were previously stored as strings).
The changeset for this PR is provided as a series of atomic commits, one for each affected service.
=> Core: normalize request parsing for services using the AWS Query protocol

moto/core/request.py, moto/moto_server/utilities.py, moto/moto_server/werkzeug_app.py, tests/test_cloudwatch/test_cloudwatch_boto3.py, tests/test_core/test_server.py
While doing some testing related to CloudWatch's upcoming switch to the JSON protocol, I inadvertently discovered a regression introduced in #9224.  That PR opted all of the Query protocol services into the new request parsing pipeline, which did not handle compressed request bodies.  There was actually a test that covered this, but [it didn't have any assertions](https://github.com/getmoto/moto/blob/152d0e0559829dee48f4efebad7982d824ce2433/tests/test_cloudwatch/test_cloudwatch_boto3.py#L65) and was just failing silently after the merge.  That test was also skipped in server mode.
This PR adds request decompression to the new request parsing pipeline, as well as to requests received in server mode.  It also modifies the existing test, adding assertions and removing the server mode skip.
=> Core: handle compressed requests in server mode

moto/iot/responses.py, tests/test_iot/test_iot_billing_groups.py
iot:list_things_in_billing_group action return only ThingNames, not full Thing descriptions.
Docs for reference:
* https://docs.aws.amazon.com/iot/latest/apireference/API_ListThingsInBillingGroup.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iot/client/list_things_in_billing_group.html
=> fix: iot:list_things_in_billing_group return Names

moto/ec2/models/transit_gateway.py, moto/ec2/responses/transit_gateway_attachments.py, moto/ec2/responses/transit_gateways.py, tests/test_ec2/__init__.py, tests/test_ec2/test_transit_gateway.py
Some minor parity improvements to the response of EC2's `create_transit_gateway_vpc_attachment` and `describe_transit_gateway_vpc_attachments`:
- The creation time is now returned correctly
- Tags are not returned at all if not set
- The `securityGroupReferencingSupport`-option is now returned (hardcoded for now)
The majority of this changeset is ensuring that we can run any transit gateway tests against AWS, and making sure that it deletes all resources (transit gateways, attachments, route tables, etc) afterwards.
=> EC2: Transit Gateway: Improve response parity

moto/core/request.py, moto/core/responses.py
Botocore models can now support multiple wire protocols, so this PR adds logic to determine the correct protocol for Moto to use for request parsing/response serialization.
Ref: https://smithy.io/2.0/spec/protocol-traits.html#serialization-and-protocol-traits
=> Core: enhance logic for request/response protocol selection

.github/workflows/test_cloudwatch.yml
In order to ensure that Moto is ready for Botocore's upcoming switch from the Query protocol to the JSON protocol when communicating with CloudWatch (#9195), this PR adds a dedicated workflow to run the CloudWatch test suite using both protocols.  With these tests passing, Moto will be forward- and backward-compatible with the planned Botocore changes.
> [!WARNING]\
> Botocore is switching from the Query protocol to the JSON protocol for CloudWatch, but other SDKs (notably Golang 2.x) will be switching from the Query protocol to the RPC v2 CBOR protocol, for which there is no current (or planned) support in Moto.
It's worth pointing out that Moto is able to simultaneously support both of these protocols _without making a single modification to the CloudWatch backend_, which is remarkable …
=> CloudWatch: support Query/JSON protocols simultaneously

moto/directconnect/models.py, tests/test_directconnect/test_directconnect.py
This PR looks to address the issue with DirectConnect resources not having proper arn format. Some small changes were made using this [doc](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsdirectconnect.html#awsdirectconnect-dxcon:~:text=arn%3A%24%7BPartition%7D%3Adirectconnect%3A%24%7BRegion%7D%3A%24%7BAccount%7D%3Adxcon/%24%7BConnectionId%7D) as reference for how ARN should be structured.
=> [DirectConnect] Updating ARNs to match AWS

tests/test_cloudwatch/test_cloudwatch_boto3.py
In anticipation of CloudWatch switching the wire protocol from Query to JSON in a future version of Botocore, this PR drops the `tzinfo` response asserts.  Botocore parses dates serialized via the Query protocol as UTC always, but the local timezone is used when parsing dates serialized via the JSON protocol.
We didn't catch this with our [dedicated CloudWatch protocol tests](https://github.com/getmoto/moto/blob/192289fb8308caee3849961713cf65ac100d8c30/.github/workflows/test_cloudwatch.yml) because the local time on GitHub Actions runners is Coordinated Universal Time (UTC).
Reported here: https://github.com/getmoto/moto/pull/9253#issuecomment-3268109315
=> CloudWatch: fix-ups for datetime asserts in anticipation of protocol change

moto/cognitoidp/models.py, tests/test_cognitoidp/test_cognitoidp.py
Include the default `aws.cognito.signin.user.admin` scope in access token. This scope is included by default in all access tokens created by `AdminInitiateAuth` and `InitiateAuth`, however it can be stripped by a custom pre-token-generation lambda trigger.
Ref: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html
=> fix(cognitoidp): aws.cognito.signin.user.admin scope in access token

moto/cloudwatch/models.py, tests/test_cloudwatch/test_cloudwatch_boto3.py
CloudWatch was recently migrated to the new request parsing pipeline, which properly deserializes boolean values; but the model was still doing a string comparison.  This PR fixes the bug and adds test coverage.
Closes #9280
=> CloudWatch: fix `ReturnData` check

IMPLEMENTATION_COVERAGE.md, moto/s3/responses.py, tests/test_s3/test_s3_lifecycle.py
This PR fixes the issue when an empty lifecycle configuration (which is used to delete all lifecycle rules). Moto had a bug in the XML parsing logic that expected a Rule key even when the lifecycle configuration was empty.
A test has been added `Test that empty lifecycle configuration (no rules) works correctly` 
IMPLEMENTATION_COVERAGE.md has also been updated to mention support for `put_bucket_lifecycle_configuration` and `get_bucket_lifecycle_configuration`
https://github.com/getmoto/moto/issues/9271
=> feat: Handle empty S3 lifecycle configuration

CHANGELOG.md, IMPLEMENTATION_COVERAGE.md, docs/docs/services/amp.rst, docs/docs/services/athena.rst, docs/docs/services/cloudwatch.rst, docs/docs/services/macie2.rst, docs/docs/services/osis.rst, docs/docs/services/quicksight.rst, docs/docs/services/s3.rst, moto/athena/models.py, moto/athena/responses.py, moto/elasticache/models.py, moto/s3/models.py, tests/test_elasticache/test_elasticache.py, tests/test_sns/test_publish_batch.py
- Added Changelog for `5.1.13`
- Athena: Fixed a typo to make sure the method-names align with the API names
- ElastiCache: Removed unnecessary arguments, added tests to verify pagination
- ElastiCache: delete_replication_group: Indented the logic correctly so that we only process the `retain_primary_cluster` parameter **iff** the cluster exists.
- S3: Some explicit renaming of methods to ensure it is picked up by the feature coverage
- SNS: Additional test that should have been part of #9296
=> Prep release 5.1.13

tests/test_rds/test_rds_proxy.py
The latest `boto3`/`botocore` release adds new validation for RDS, causing our tests to fail with the following ValidationErrors:
> FAILED tests/test_rds/test_rds_proxy.py::test_create_db_proxy - botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter Auth[0].SecretArn, value: 13, valid min length: 20
Invalid length for parameter RoleArn, value: 7, valid min length: 20
This PR fixes that by increasing the length of the ARN's.
=> RDS Proxy tests: Longer ARNs

moto/macie2/models.py, moto/macie2/responses.py, moto/macie2/urls.py, tests/test_macie/test_macie.py
Updating the current Macie implementation by adding EnableOrganizationAdminAccount and ListOrganizationAdminAccounts to handle the designation and retrieval of a delegated administrator for an AWS Organization.  Also adding DisassociateMember, which correctly removes accounts that were added via direct invitation.
=> [Macie]Adding support for organization admin accounts and member disassociation

moto/securityhub/models.py, moto/securityhub/responses.py, moto/securityhub/urls.py, tests/test_securityhub/test_securityhub.py
This PR adds the following methods:
enable_security_hub – Enables SecurityHub for the account and region. Handles the EnableDefaultStandards parameter.
disable_security_hub – Disables SecurityHub for the account and region.
describe_hub – Returns hub metadata, including the optional HubArn.
Also added tests
=> [SecurityHub]Adding lifecycle methods in Moto SecurityHub

moto/s3/responses.py, other_langs/tests_java/src/test/java/moto/tests/S3Test.java
Fixes #9263
Fixes #9310 
The Java SDK uses the `STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER` signature by default, so we can verify this behaviour with a simple `PUT`->`GET` test.
=> S3: Support STREAMING-AWS4-HMAC-SHA256-PAYLOAD-TRAILER signature in S3 PUT

moto/resourcegroupstaggingapi/models.py, tests/test_resourcegroupstaggingapi/test_resourcegroupstaggingapi_kms.py
=> ResourceGroupsTaggingAPI: get_resources() now supports the 'kms:key' type

moto/ec2/exceptions.py, moto/ec2/models/vpn_connections.py, moto/ec2/responses/vpn_connections.py, tests/test_ec2/test_customer_gateways.py, tests/test_ec2/test_transit_gateway.py, tests/test_ec2/test_vpn_connections.py
I've been wanting to fix #9050 for a while now, but every time I look at it, I discover other bugs/parity issues in our (test) code. This PR should make it easier to improve the TransitGateways, and improves parity in a few areas.
- `create_vpn_connection()` now validates that only one of [VPNGateway|TransitGateway] is provided
- `create_vpn_connection()` now validates that the provided CustomerGateway and TransitGateway exists
- Removes reference to the `static_routes_only`-parameter, as that wasn't implemented anyway
- Adds `aws_verified` tests for all changes
=> EC2: Improve VPN Connections validation

.github/workflows/test_sqs.yml, tests/test_sqs/test_sqs.py
The SQS Tests workflow broke with the merging of #8902, but it was never triggered because that PR didn't have the `service-sqs` label applied.  This PR changes the workflow to trigger on changes to any SQS-related files, so no one has to remember to add a manual label.  This PR also adds a conditional to the tests added in #8902 so they work with both the current JSON protocol service specification as well as the outdated (but still supported) Query protocol service definition.
=> SQS: Improve Wire Protocol Testing

moto/ec2/exceptions.py, moto/ec2/models/transit_gateway_attachments.py, moto/ec2/models/transit_gateway_route_tables.py, tests/test_ec2/__init__.py, tests/test_ec2/test_transit_gateway.py
I've been wanting to fix #9050 for a while now, but every time I look at it, I discover other bugs/parity issues in our (test) code. This PR improves the way we store VPC Attachments.
(See also: #9344 )
- `create_transit_gateway_vpc_attachment()` now validates that the TransitGateway exists
- `create_transit_gateway_vpc_attachment()` now validates that no other attachment to this VPC exists
- `create_transit_gateway_vpc_attachment()` now automatically adds the attachment to the default RouteTable
- `create_transit_gateway_vpc_attachment()` now correctly creates multiple attachments if called twice (for different VPC's)
- Adds `aws_verified` tests for all changes
=> EC2: Transit Gateways: Allow multiple RouteTable Associations
